docs/source/tutorial/recurrentnet.rst
This bug is reported by https://twitter.com/tmasada/status/608177076370182144. Thank you Masada-san!
=> Fix a bug of the sample code in the recurrent net tutorial

chainer/optimizers/adam.py
I found a tiny difference between codes of CPU and GPU in Adam.
Thus I fix the GPU code, based on AdaGrad.
=> Fix a gap between codes for CPU and GPU in Adam

tests/functions_tests/test_hierarchical_softmax.py
=> Use assertAlmostEqual to compare float value

examples/ptb/train_ptb.py
=> Support loss accumulation on gpu

docs/source/tutorial/basic.rst
Noticed this minor parenthesis missing while trying out Chainer's tutorial.
This project is incredible, a unique framework and filled with new ideas. Thank you!
=> Added missing right parenthesis to example.

chainer/functions/batch_normalization.py
=> Hide `cuda.cutools` from `batch_normalization`

examples/sentiment/download.py, examples/sentiment/download.sh
=> Remove dependency on wget and unzip from sentiment example

chainer/optimizer.py, tests/functions_tests/test_basic_math.py, tests/optimizers_tests/linear_model.py, tests/optimizers_tests/test_ada_delta.py, tests/optimizers_tests/test_ada_grad.py, tests/optimizers_tests/test_adam.py, tests/optimizers_tests/test_momentum_sgd.py, tests/optimizers_tests/test_rmsprop.py, tests/optimizers_tests/test_sgd.py, tests/test_function_set.py, tests/test_optimizer.py, tests/test_variable.py
This PR is implementation of #5 . It includes :
* More unittest for unary and binary operations for `Variable`
* Unittest for `Variable`
* Unittest for `FunctionSet` where `FunctionSet` is nested.
* Unittest for utility of `Optimizer`
* Functionality test for each optimizers
Since issue #5 contains implementation of tests for multiple modules, I would recommend we should split it into more smaller issues.
=> Test core functionalities

tests/optimizers_tests/linear_model.py, tests/test_optimizer.py, tests/test_variable.py
=> Disable cuda.init when cuda is disabled

chainer/functions/hierarchical_softmax.py, docs/source/reference/functions.rst
I wrote a document of `BinaryHierarchicalSoftmax` function.
=> Write document of HSM

chainer/functions/basic_math.py, tests/functions_tests/test_basic_math.py
Fix  `__rsub__` bug (Issue #44).
=> Fix  `__rsub__` bug #44

chainer/cuda.py, chainer/functions/basic_math.py, chainer/variable.py, tests/functions_tests/test_basic_math.py
Fix #43
`__array_priority__`　is added to `Variable`.
http://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array_priority__
And, I add a hook to binary operators of `GPUArray`, because `GPUArray` is to Ignore `__array_priority__`.
=> Fix binary operation

examples/sentiment/README.md
Related to #52, #38.
Tiny fix.
=> Fix a typo in the README.md of the sentiment analysis example

chainer/variable.py, tests/test_variable.py
=> Insert type check to Variable.__init__

docs/source/contribution.rst, docs/source/index.rst
I wrote the contribution guide. This document includes our development process, issues and PRs policy, and coding/testing guidelines.
=> Contribution guide

chainer/functions/basic_math.py, chainer/utils/__init__.py, tests/functions_tests/test_basic_math.py
I wrapped scalar values with 0-dimensional vector.
fix #107
=> Vectorize return values of operators

chainer/functions/__init__.py, chainer/functions/basic_math.py, tests/functions_tests/test_basic_math.py
This PR is implementation of #11.
=> Add an elementwise absolute value function

chainer/functions/__init__.py, chainer/functions/negative_sampling.py, chainer/utils/__init__.py, chainer/utils/walker_alias.py, docs/source/reference/functions.rst, docs/source/reference/util.rst, tests/functions_tests/test_negative_sampling.py, tests/utils_tests/test_walker_alias.py
I implemented negative sampling function. I used Walker's alias method for efficient sampling.
See also:
- T. Mikolov, I. Sutskever, K. Chen, G. Corrado, J. Dean, Distributed Representations of Words and Phrases and their Compositionality, in NIPS 2013.
- http://en.wikipedia.org/wiki/Alias_method
=> Implemented Negative sampling

tests/functions_tests/test_accuracy.py
I added a test for shape of result of `accuracy` function.
It is related to #100
=> Add test for shape of result of accuracy function

chainer/functions/mean_squared_error.py, tests/functions_tests/test_mean_squared_error.py
=> Change return type of MSE to float32

chainer/functions/linear.py
It fixes test failures of Linear in Python3.
=> Fix a bug of F.Linear in Py3

chainer/functions/hierarchical_softmax.py, chainer/functions/negative_sampling.py, chainer/functions/sigmoid_cross_entropy.py, tests/functions_tests/test_accuracy.py, tests/functions_tests/test_batch_normalization.py, tests/functions_tests/test_convolution_2d.py, tests/functions_tests/test_embed_id.py, tests/functions_tests/test_hierarchical_softmax.py, tests/functions_tests/test_leaky_relu.py, tests/functions_tests/test_linear.py, tests/functions_tests/test_local_response_normalization.py, tests/functions_tests/test_lstm.py, tests/functions_tests/test_negative_sampling.py, tests/functions_tests/test_parameter.py, tests/functions_tests/test_pooling_2d.py, tests/functions_tests/test_prelu.py, tests/functions_tests/test_relu.py, tests/functions_tests/test_reshape.py, tests/functions_tests/test_sigmoid.py, tests/functions_tests/test_sigmoid_cross_entropy.py, tests/functions_tests/test_softmax.py, tests/functions_tests/test_softmax_cross_entropy.py, tests/functions_tests/test_sum.py, tests/functions_tests/test_tanh.py
I fixed test codes to check types of return values for all functions.
And, I found problems in some functions, and fixed them.
fix #133
=> Add check code for float32

chainer/functions/inceptionbn.py, chainer/functions/negative_sampling.py, docs/source/reference/functions.rst
This PR includes following changes:
- I fixed some wording of NegativeSampling.
- I wrote a documentation of InceptionBN.
- I added the InceptionBN, matmul, and batch_matmul to the reference.
=> Add and improve the function documentations

chainer/functions/caffe/caffe_function.py
This PR aims to support a recent specification of caffemodel.
A current ``chainer.functions.caffe.CaffeFunction`` does not support the ``.caffemodel`` created by the latest caffe because the ``CaffeFunction`` assumes that there exists positive values
in ``height`` and ``width`` fields in ``Blob`` (the current caffe explicitly uses the ``shape`` field in order to support a two-dimensional array).
Although the original code works well when we load an old version of ``.caffemodel`` (i.e., bvlc_reference_caffenet.caffemodel), I wrote an additional code for supporting the latest model.
Please note that I do not add any test files for this PR just like the original ``caffe_function.py`` (I tested it on my laptop and confirmed that it works correctly, though).
=> Support a recent specification of caffe

examples/mnist/train_mnist.py
When batchsize is not chosen appropriately, accuracy may exceed 1.
=> It is fix batchsize in training and evaluation.

chainer/functions/__init__.py, chainer/functions/split_axis.py, docs/source/reference/functions.rst, tests/functions_tests/test_split_axis.py
This PR implements #10 .
`split_axis` behaves opposite to the `concat`.
=> Add split_axis function

chainer/functions/__init__.py, chainer/functions/convolution_2d.py, chainer/functions/linear.py, chainer/functions/nonparameterized_convolution_2d.py, chainer/functions/nonparameterized_linear.py, docs/source/reference/functions.rst, tests/functions_tests/test_convolution_2d.py, tests/functions_tests/test_nonparameterized_convolution_2d.py, tests/functions_tests/test_nonparameterized_linear.py
=> Non-parameterized versions of Linear and Convolution2D

tests/functions_tests/test_hierarchical_softmax.py
=> Fix test for HSM

examples/imagenet/README.md, examples/imagenet/compute_mean.py, examples/imagenet/train_imagenet.py, examples/modelzoo/README.md, examples/modelzoo/evaluate_caffe_net.py, setup.py
=> Stop using OpenCV in examples

chainer/functions/split_axis.py, tests/functions_tests/test_split_axis.py
I fixed `foward_gpu` function.
=> Fix buf: if arguments is a sections in SplitAxis

chainer/functions/split_axis.py
This PR was discussed in the #157.
=> Add shape check about zero-length output to SplitAxis

chainer/cuda.py, tests/test_cuda.py
=> Check version of depedent libraries in runtime for cuda

chainer/functions/split_axis.py
* Fix return value of `split_axis`
* Add note about zero-size outputs of `split_axis`
* Fix minor grammatical errors.
=> Fix document of split_axis

README.md
It improves the CUDA installation section.
=> Fix readme for CUDA installation

chainer/functions/hierarchical_softmax.py, tests/functions_tests/test_hierarchical_softmax.py
* Add type check to `HierarchicalSoftmax` Function.
Related to #123
=> Add typecheck to hierachical softmax

chainer/functions/negative_sampling.py, tests/functions_tests/test_negative_sampling.py
=> Add type check to Negative sampling

cuda_deps/setup.py
I will upload it to PyPI after the merge.
=> Update cuda_deps to 1.1.0.1 (for scikit-cuda)

tests/test_runnable.py
=> Add test to check if all tests are runnable

chainer/functions/batch_normalization.py
* Add typecheck to BatchNormalization
Related to #123
=> Batch Normalization typecheck

chainer/utils/type_check.py, tests/utils_tests/test_type_check.py
- Show quatations of str constants
- Show values of list and tuple constants
- Fix behavior of GetAttr by second arguments
=> Fix behavior of str method of Expr

chainer/cuda.py
Show warning message and reinstall operation
fix #201
=> Show warning when old scikits.cuda package is found

chainer/cuda.py, docs/source/conf.py, docs/source/tutorial/gpu.rst
=> Use skcuda module

chainer/functions/reshape.py
=> typecheck for Reshape Function

chainer/functions/copy.py, tests/functions_tests/test_copy.py
* Add type check for `Copy` Function 
* Add unittest(cpu-only) for `Copy` Function to test type check.
Related to #123
=> Add unittest(cpu-only) and typecheck for Copy

chainer/functions/basic_math.py, chainer/functions/local_response_normalization.py, tests/functions_tests/test_basic_math.py
=> Negative pow

chainer/functions/convolution_2d.py
* Add type check for `Convolution2D` Function 
Related to #123
=> Add type check for convolution

chainer/functions/pooling_2d.py
=> Add typecheck to MaxPooling2D and AveragePooling2D

chainer/functions/mean_squared_error.py
=> Add typecheck to MeanSquaredError

chainer/functions/sum.py
=> Add typecheck to Sum

chainer/functions/sigmoid_cross_entropy.py
=> Add typecheck to SigmodCrossEntropy

chainer/functions/relu.py
=> Add forward typecheck to ReLU

chainer/functions/prelu.py
=> Remove PReLU._check_shape and add typecheck

chainer/function.py, chainer/functions/basic_math.py, chainer/functions/sigmoid.py, chainer/functions/tanh.py
typecheck for following functions:
- Neg
- Absolute
- AddConstant
- SubFromConstatnt
- MulConstant
- DivFromConstant
- PowVarConst
- PowConstVar
- Exp
- Log
- Tanh
- Sigmoid
Related #123
=> Add typecheck for unary operator

chainer/functions/matmul.py
=> Add typecheck to matmul

chainer/functions/split_axis.py
=> Add typecheck to split axis

chainer/functions/basic_math.py, chainer/functions/matmul.py, chainer/functions/sigmoid_cross_entropy.py, chainer/variable.py, tests/functions_tests/test_sum.py, tests/test_variable.py
It fixes the second point of #209. `Variable.grad` is now a property whose setter checks the type, dtype, and shape of the argument. This PR also contains several fixes on Function implementations and some tests.
=> Check type at setting Variable.grad

docs/source/tutorial/basic.rst
=> Fix tutorial to use prepared function

chainer/computational_graph.py, chainer/variable.py, tests/functions_tests/test_basic_math.py
=> Disable comparison operation

README.md
=> Write links to readme

chainer/functions/parameter.py
=> Add typecheck to Parameter function

chainer/functions/identity.py
=> Explicitly pass Identity.check_type_forward

chainer/cuda.py, tests/test_cuda.py
=> Check availability of cuda in functions in cuda.py

chainer/functions/nonparameterized_linear.py
=> Write type check for nonparameterized linear

chainer/functions/nonparameterized_convolution_2d.py
=> Write type check for non-parameterized convolution 2d

docs/source/tutorial/recurrentnet.rst
=> Fix shape of data in RNN tutorial

chainer/functions/local_response_normalization.py
=> Write type check for LRN

chainer/functions/dropout.py, tests/functions_tests/test_dropout.py
=> Dropout typecheck

chainer/functions/leaky_relu.py, tests/functions_tests/test_leaky_relu.py
=> Write type check for leaky relu

chainer/functions/split_axis.py, tests/functions_tests/test_split_axis.py
=> Insert cast into prod in split_axis

chainer/functions/concat.py, tests/functions_tests/test_concat.py
=> Fix concat axis

chainer/optimizer.py, tests/test_optimizer.py
=> Fix weight decay (#261)

chainer/functions/concat.py, tests/functions_tests/test_concat.py
=> Use tuple for shape of return value of concat

index.html
I added a thumbnail of slide to the index page.
=> Add a link to slide and its thumbnail

docs/source/tutorial/index.rst, docs/source/tutorial/type_check.rst
=> Write a tutorial about type check

chainer/function_set.py, tests/test_function_set.py
=> Use copyto in copy_parameters_from

chainer/functions/inception.py, chainer/functions/inceptionbn.py
=> Add Inception{,BN}.check_type_forward in which we explicitly pass

tests/test_variable.py
=> Add unittest for Variable.set_creator

docs/source/index.rst, docs/source/tips.rst
I made a tips page and wrote a tips for pycuda installation.
http://askubuntu.com/questions/643270/how-can-i-install-chainer-cuda-deps
related to #33
=> Wrote tips for pycuda installation

setup.py, tests/test_optimizer.py
This test uses mock package.
fix #71
=> Write unittest for optimizer

chainer/function.py, setup.py, tests/test_function.py
=> Write unit test of Function

docs/source/tips.rst
=> Write tips about sudo pip

tests/utils_tests/test_conv.py, tests/utils_tests/test_utils.py
=> Test utils

chainer/functions/negative_sampling.py, chainer/utils/walker_alias.py, tests/functions_tests/test_negative_sampling.py, tests/utils_tests/test_walker_alias.py
=> Negative sampling supports `to_cpu`

chainer/gradient_check.py, tests/test_gradient_check.py
=> Gradient check unittest

chainer/gradient_check.py, tests/test_gradient_check.py
=> Show alert when GPU and CPU arrays are mixed

chainer/functions/__init__.py, chainer/functions/softplus.py, docs/source/reference/functions.rst, tests/functions_tests/test_softplus.py
I implemented softplus function.
=> Implemented softplus function

chainer/functions/__init__.py, chainer/functions/gaussian.py, docs/source/reference/functions.rst, tests/functions_tests/test_gaussian.py
I implemented Gaussian noise function.
=> Implemented gaussian sampling function

chainer/functions/pooling_2d.py
=> Pass use_cudnn on spatial_pyramid_pooling_2d

chainer/functions/mean_squared_error.py
We need to split check of size and check of each value.
=> Fix typecheck of mean squared error

chainer/cuda.py
In a special situation, package is found though import fails.
Thanks to @jheymann85
This PR is based on #246
=> Raise an error when cuda import failed.

chainer/functions/split_axis.py, tests/functions_tests/test_split_axis.py
=> Support None gradient in split_axis

chainer/cudnn/cudnn.py, chainer/functions/basic_math.py, chainer/functions/relu.py, chainer/utils/__init__.py, tests/functions_tests/test_relu.py, tests/utils_tests/test_utils.py
=> Fix relu zero dim

chainer/functions/vae.py, docs/source/reference/functions.rst, tests/functions_tests/test_vae.py
- KL-divergence between a given gaussian and the normal gaussian
- NLL of Bernoulli distribution
- NLL of Gaussian distribution
fix #170
=> Components of VAE

chainer/functions/hierarchical_softmax.py, tests/functions_tests/test_hierarchical_softmax.py
=> Use unique ids to fix create_huffman_tree

chainer/functions/hierarchical_softmax.py, tests/functions_tests/test_hierarchical_softmax.py
=> GPU mode of hierarchical softmax

tests/functions_tests/test_inception.py
=> Inception unittest

chainer/functions/hierarchical_softmax.py, tests/functions_tests/test_hierarchical_softmax.py
=> Fix to_cpu method of hierarchical softmax

chainer/function_set.py, tests/test_function_set.py
Fix docstring of `getitem` and add a test.
related to #290
=> Functionset getitem

chainer/functions/inceptionbn.py, tests/functions_tests/test_inceptionbn.py
This PR fixes #295 
Note that this PR changes `InceptionBN` function for testability. The reason is described in the commit message of f167ccb. I believe this does not change the behavior of the function. But please point it out if my understanding is incorrect.
=> Inceptionbn unittest

chainer/function_set.py, chainer/optimizer.py, docs/source/tutorial/basic.rst, docs/source/tutorial/gpu.rst, docs/source/tutorial/recurrentnet.rst, examples/imagenet/train_imagenet.py, examples/mnist/train_mnist.py, examples/mnist/train_mnist_model_parallel.py, examples/ptb/train_ptb.py, examples/sentiment/train_sentiment.py, examples/word2vec/train_word2vec.py, tests/optimizers_tests/test_optimizers_by_linear_model.py, tests/test_function_set.py
Made ``optimizer.setup`` to accept ``FunctionSet`` itself. I think this simplifies the API and easier to remember.
=> API: Allow optimizer.setup to accept FunctionSet

index.html
=> Update web page to 1.2.0

cupy/__init__.py, cupy/manipulation/dims.py, tests/cupy_tests/manipulation_tests/test_dims.py
=> Implement expand_dims

chainer/functions/batch_normalization.py
=> Fix scaling of mean moving average

cupy/__init__.py, cupy/creation/basic.py, cupy/creation/from_data.py, cupy/creation/ranges.py, cupy/cuda/memory.py, cupy/indexing/indexing.py, cupy/manipulation/basic.py, cupy/manipulation/dims.py, cupy/manipulation/join.py, cupy/manipulation/shape.py, cupy/manipulation/split.py, cupy/math/misc.py, cupy/reduction.py, docs/source/cupy-reference/kernel.rst, docs/source/cupy-reference/memoize.rst, docs/source/cupy-reference/overview.rst, docs/source/cupy-reference/random.rst
This PR improves the CuPy docs, including typo fixes, appearance improvement, etc.
=> Improve cupy docs

chainer/functions/sum.py, tests/chainer_tests/functions_tests/test_sum.py
Add axis option like numpy.sum for functions.Sum
```
s = list(x[0].shape)
s[self.axis] = 1
gy = gy[0].reshape(s)
```
If `cupy.expand_dims` is implemented, this cord is replaced with `gy = xp.expand_dims(gy[0], axis=self.axis)`
=> add axis option and apply cupy for functions.Sum

examples/imagenet/train_imagenet.py
has tested locally that model file had correct  name  was generated
=> fixed bug that --out argument in train_imagenet.py dimmed

README.md, setup.py
=> Fix requirement

tests/chainer_tests/functions_tests/test_basic_math.py
=> Add unittest for label properties of basic math functions

docs/source/cupy-reference/overview.rst
=> Fix inline markup

cupy/manipulation/dims.py
Py3 cannot compare None and int.
=> Fill zero for py3

chainer/function.py, chainer/utils/type_check.py
=> Make a global variable that enables type check

chainer/cuda.py, examples/imagenet/train_imagenet.py, examples/mnist/train_mnist.py, examples/mnist/train_mnist_model_parallel.py, examples/modelzoo/evaluate_caffe_net.py, examples/ptb/train_ptb.py, examples/sentiment/train_sentiment.py, examples/word2vec/train_word2vec.py
=> Check avaiability of cuda in examples

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/linear.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_linear.py
fix #367. It also fixes nonparameterized convolution_2d without bias.
=> Fix nonparameterized linear without bias

docs/source/cupy-reference/overview.rst, docs/source/tips.rst
I added a FAQ on GPU compilation time.
=> Add a faq on compilation time

cupy/manipulation/shape.py
=> Fix typo in reshape

cupy/random/generator.py, tests/cupy_tests/random_tests/test_generator.py
This PR implements unittest for `cupy.random.generator` module.
=> Unittest cupy.random.generator

cupy/linalg/product.py, tests/cupy_tests/linalg_tests/test_product.py
=> Fix linalog/product bug

docs/source/conf.py, docs/source/cupy-reference/kernel.rst, docs/source/reference/functions.rst, docs/source/tutorial/basic.rst, docs/source/tutorial/function.rst, docs/source/tutorial/gpu.rst, docs/source/tutorial/recurrentnet.rst, docs/source/tutorial/type_check.rst
I wrote doctest using doctest extension of sphinx: http://sphinx-doc.org/ext/doctest.html
Please use this command to run the test.
```
$ cd docs
$ make doctest
```
fix #395
=> Support doctest

cupy/__init__.py, tests/cupy_tests/test_ndarray_unary_op.py
=> Fix __nonzero__ operator

cupy/cuda/curand.py, tests/cupy_tests/cuda_tests/test_curand.py
This PR fixes #390. Currently, I simply fix the problem by forbidding generation of even number of values.
=> Fix generate normal

chainer/functions/caffe/caffe_function.py
fix #297.
If you want to test , please insert the following code to the 58-th row of modelzoo example.
```python:
pickle.dump(func, open("model.pickle", 'wb'), -1)
func = pickle.load(open("model.pickle", 'rb'))
```
https://github.com/pfnet/chainer/blob/v1.3.0/examples/modelzoo/evaluate_caffe_net.py#L58
=> Support pickling to CaffeFunction

cupy/__init__.py, cupy/random/generator.py, tests/cupy_tests/creation_tests/test_basic.py, tests/cupy_tests/random_tests/test_generator.py, tests/cupy_tests/test_ndarray.py
=> Move _get_size from generator to cupy.__init__ and use it in ndarray

cupy/__init__.py, cupy/cuda/curand.py, cupy/random/generator.py, tests/cupy_tests/cuda_tests/test_curand.py, tests/cupy_tests/random_tests/test_generator.py, tests/cupy_tests/test_ndarray.py
Fix #422 
Merge #425 before this PR
=> Support odd elements

cupy/__init__.py, cupy/elementwise.py, cupy/math/misc.py, cupy/reduction.py, cupy/testing/helper.py, tests/cupy_tests/manipulation_tests/test_shape.py, tests/cupy_tests/math_tests/test_misc.py, tests/cupy_tests/test_ndarray_elementwise_op.py
fix #421.
I fix some cases that are different behavior of the type conversion in numpy and cupy.
=> Fix type casting

tests/cupy_tests/test_ndarray_unary_op.py
=> Write test for unary operators

tests/cupy_tests/creation_tests/test_from_data.py
=> Fix test_copy

cupy/testing/helper.py
=> Add None check to helper function

tests/cupy_tests/random_tests/test_random.py
=> Write functional test for seed

cupy/math/arithmetic.py
I fixed syntax error in remainder.
=> Fix syntax error in remainder

tests/cupy_tests/test_ndarray_elementwise_op.py
Switch div operator to support py3.
=> Fix div for py3

tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
A test for gaussian function sometimes fails. I fixed its condition.
=> Fix condition of test for gaussian

cupy/elementwise.py, tests/cupy_tests/test_ndarray_elementwise_op.py
=> Fix divmod

tests/cupy_tests/test_ndarray_elementwise_op.py
=> Add rdivmod tests

cupy/testing/__init__.py, cupy/testing/helper.py, tests/cupy_tests/math_tests/test_arithmetic.py, tests/cupy_tests/math_tests/test_explog.py, tests/cupy_tests/test_ndarray_elementwise_op.py
I changed tests to minimize the effect of `numpy.seterr`.
Please merge #464 and #465 before this PR.
=> Minimize the effect of `numpy.seterr`

chainer/functions/array/reshape.py, tests/chainer_tests/functions_tests/array_tests/test_reshape.py
=> Support negative reshape

chainer/function.py
This PR fixes tiny document redundancy in `Function` class.
=> Document fix in Function

.travis.yml, setup.py
Fix travis configuration file to test model branch.
=> Fix travis

chainer/cuda.py
=> Add cuda.init mehthod to show warning

chainer/functions/__init__.py, chainer/functions/array/swapaxes.py, chainer/functions/array/transpose.py, tests/chainer_tests/functions_tests/array_tests/test_swapaxes.py, tests/chainer_tests/functions_tests/array_tests/test_transpose.py
Simple wrappers around the corresponding cupy functions.
=> Add chainer Functions Transpose and Swapaxes.

chainer/cuda.py, tests/chainer_tests/test_cuda.py
=> Raise type error in to_cpu if array is neither numpy.ndarray nor cupy.ndarray

cupy/carray.cuh
As suggested by Seiya Tokui on the forum: https://groups.google.com/forum/#!topic/chainer/2P9nuZfJfls
These should make writing complex CUDA kernels easier.
=> Added shape() and strides() methods to CArray.

examples/ptb/download.py, examples/sentiment/download.py
=> Use six to download

cupy/manipulation/dims.py, cupy/testing/__init__.py, cupy/testing/helper.py, tests/cupy_tests/manipulation_tests/test_dims.py
=> Raise ValueError when broadcasting fails

chainer/functions/connection/bilinear.py, chainer/functions/connection/linear.py, tests/chainer_tests/utils_tests/test_type_check.py
=> Use type_check.prod

chainer/gradient_check.py, tests/chainer_tests/test_gradient_check.py
=> Insert copy to numerical_grad

chainer/function_set.py, tests/chainer_tests/test_function_set.py
Fix #502. `FunctionSet.gradients` have same problems as `FunctionSet.parameters`. This PR also fixes `gradients` .
=> Fix setter of FunctionSet.parameters and FunctionSet.gradients

chainer/cuda.py, tests/chainer_tests/test_cuda.py
=> Return dummy device when no memory is allocated

tests/chainer_tests/test_gradient_check.py
I made a test to check whether `eps` works.
=> Make a test for different eps

cupy/testing/__init__.py, cupy/testing/parameterized.py, tests/cupy_tests/test_ndarray.py
fix #536 
We want to use this decorator in chainer.
=> Make parameterize decorator and use it in test_ndarray

cupy/__init__.py, cupy/sorting/count.py, docs/source/cupy-reference/overview.rst, docs/source/cupy-reference/sorting.rst, tests/cupy_tests/sorting_tests/test_count.py
I implemented `count_nonzero` method.
=> Implement count_nonzero

chainer/functions/__init__.py, chainer/functions/array/where.py, cupy/__init__.py, cupy/sorting/search.py, docs/source/cupy-reference/overview.rst, docs/source/cupy-reference/sorting.rst, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_where.py, tests/cupy_tests/sorting_tests/test_search.py
I implemented `cupy.where` partially, and `Where` function for chainer.
=> Where method and where function

chainer/functions/loss/softmax_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
=> Softmax cross entropy ignore

chainer/testing/__init__.py, chainer/testing/parameterized.py
=> Add parameterize decolator to chainer.testing

chainer/functions/__init__.py, chainer/functions/array/broadcast.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_broadcast.py
fix #511 
Please merge #510 before this PR.
=> Implement broadcast function

cupy/sorting/search.py
=> Add type conditions to `where` method to avoid cuda6.5 bug

chainer/optimizers/__init__.py, chainer/optimizers/nesterov_ag.py, docs/source/reference/optimizers.rst, tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
I implemented Nesterov's Accelerated Gradient(NAG).
I use NAG's formulation of http://arxiv.org/abs/1212.0901 .
=> Add Nesterov's Accelerated Gradient.

.travis.yml, README.md
=> Support Python 3.5

tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
=> Change atol in CTC test 

tests/chainer_tests/test_gradient_check.py
=> Remove too small eps from gradient test

tests/chainer_tests/functions_tests/loss_tests/test_hierarchical_softmax.py
=> Fix test condition of hsm

cupy/cuda/memory.py, tests/cupy_tests/cuda_tests/test_memory.py
This PR fix error at the time of gpu memory release.
=> Fix 0-size malloc

cupy/reduction.py, cupy/sorting/count.py, cupy/testing/helper.py, tests/cupy_tests/sorting_tests/test_count.py
=> Fix count_nonzero and argmin/argmax

chainer/functions/loss/ctc.py
=> Fix ctc codestyle

cupy/internal.py, tests/cupy_tests/test_ndarray_indexing.py
=> Raise an error when invalid index value is given

chainer/functions/connection/parameter.py, tests/chainer_tests/functions_tests/connection_tests/test_parameter.py
=> Fix parameter so that it can accept cupy.ndarray

chainer/function.py, chainer/utils/type_check.py, tests/chainer_tests/test_function.py
=> Functin.check_type_forward raises understandable errors

docs/source/reference/functions.rst
Add index of connectionist temporal classification to documents.
=> Add index of connectionist temporal classification to documents.

cupy/testing/__init__.py, cupy/testing/helper.py, tests/cupy_tests/test_ndarray_elementwise_op.py, tests/cupy_tests/testing_tests/test_helper.py
=> Type combination test

cupy/__init__.py, cupy/internal.py, tests/cupy_tests/test_internal.py, tests/cupy_tests/test_ndarray_indexing.py
Supported negative indexing.
related to #507
=> Negative indexing

cupy/reduction.py, tests/cupy_tests/test_reduction.py
This PR improve reduction performance for a large shape array.
=> Improve reduction performance

chainer/functions/connection/embed_id.py, tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
=> Support multi-dimensional embed id

examples/sentiment/train_sentiment.py
This PR fixes sentiment example to catch up the latest `chain` branch.
Changes themselves are almost same as #494 (except using `Chain` instead of `DictLink`). But I could not merge `chain` branch into #494 because of tremendous conflicts.
=> Fix sentiment example for Chain

cupy/__init__.py, cupy/manipulation/tiling.py, docs/source/cupy-reference/manipulation.rst, tests/cupy_tests/manipulation_tests/test_tiling.py
=> ``repeat`` manipulation for cupy.ndarray

.travis.yml
=> Use new infrastructure of Travis

chainer/links/connection/lstm.py, tests/chainer_tests/links_tests/connection_tests/test_lstm.py
I found that input size is incorrect.
=> Fix LSTM link and write a test

.travis.yml, setup.cfg
I added a configuration for flake8. It simplify flake8 command.
=> Make a setting file for flake8

docs/source/comparison.rst
Comparison table is out-dated. This PR updates it.
=> Fix comparison table

chainer/functions/noise/dropout.py
I think that precision is enough even in float32.
=> Use float32 rand in dropout

setup.cfg
I fixed setup.cfg to ignore temporary files.
=> Fix setup.cfg for flake8

tests/cupy_tests/core_tests/test_core.py
I wrote a test for internal methods in cupy. These methods are written in cython.
=> Write test for core module of cupy

cupy/__init__.py, cupy/statistics/histogram.py, docs/source/cupy-reference/overview.rst, docs/source/cupy-reference/statistics.rst, tests/cupy_tests/statics_tests/test_histogram.py
related to #612.
We need to discuss about multi-dimension support.
=> Implement bincount

cupy/testing/helper.py, tests/cupy_tests/testing_tests/test_helper.py
=> Show traceback on cupy_numpy_raises when an error happens

cupy/cuda/function.pyx, cupy/testing/helper.py
=> Fix acceptable dtypes

chainer_setup_build.py
This patch checks availability of headers and libraries.
=> Check if libraries and headers available

chainer/functions/__init__.py, chainer/functions/connection/deconvolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
#315
I updated @tnarihi's deconvolution implementation to make it working on current chainer, and added tests.
=> Add Deconvolution2D

docs/source/reference/functions.rst, docs/source/reference/links.rst
=> Add reference to deconvolution2D

chainer_setup_build.py
The PR is changed to setup script that is based on the path of `nvcc`.
=> The nvcc path based setup scipt

chainer_setup_build.py
=> Use relative path

tests/chainer_tests/functions_tests/array_tests/test_broadcast.py, tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py, tests/chainer_tests/links_tests/connection_tests/test_lstm.py, tests/chainer_tests/test_flag.py, tests/chainer_tests/test_gradient_check.py, tests/chainer_tests/test_link.py, tests/chainer_tests/test_runnable.py
I found that `glob` doesn't find files recursively. I replaced `glob` with `os.walk` to check all files.
=> Fix runnable

chainer/functions/loss/sigmoid_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
=> Insert cast for too large mini-batch

README.md
=> Fix chainer cuda deps

cupy/cuda/compiler.py, tests/cupy_tests/cuda_tests/test_compiler.py
=> Show readable error message when nvcc failed

chainer_setup_build.py
=> Add both lib and lib64 to library path

cupy/core/core.pyx
=> Remove print

chainer/functions/math/matmul.py
=> Use uintp instead of intp

cupy/cuda/compiler.py
=> Fix reraise

chainer/cuda.py, tests/chainer_tests/test_variable.py
=> Always copy ndarray when it is copied to another device

docs/source/contribution.rst
The contribution guide includes obsolete expressions in the current workflow. This PR fixes them.
=> Update contribution guide

docs/source/index.rst, docs/source/install.rst
=> Write install guide

chainer/functions/loss/softmax_cross_entropy.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
fix #584 
I wrote a code which uses `CUDNN_SOFTMAX_LOG`, but cudnn v2 doesn't support it.
=> Stable softmax cross entropy

README.md, docs/source/install.rst
Old setuptools causes installation problems.
=> Write about setuptools

setup.py
=> Change version

tests/chainer_tests/test_variable.py
`@attr.gpu` is not necessary here.
=> Fix variable test

cupy/manipulation/split.py, tests/cupy_tests/manipulation_tests/test_split.py
=> Fix array_split to support empty indices

cupy/math/misc.py, tests/cupy_tests/math_tests/test_misc.py
=> Fix clip method and add a test for function version of clip

appveyor.yml, appveyor/install.ps1, appveyor/run_with_env.cmd
Merge #758 and #759 before this PR.
https://ci.appveyor.com/project/okuta/chainer
=> Test on Windows

cupy/cuda/memory.pyx, tests/cupy_tests/cuda_tests/test_memory.py
=> Set None to ptr

tests/cupy_tests/sorting_tests/test_search.py
Use combination test instead of `for_all_dtypes`
=> Use combination test

examples/word2vec/train_word2vec.py
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chainer/rpQdqoGlgcg/NJcWyRPlDgAJ
=> Fix bug in word2vec sample

cupy/testing/__init__.py
=> Expose cupy.testing.for_dtypes_combination

cupy/testing/__init__.py, cupy/testing/helper.py
I made `with_requires` decorator which checks library version.
=> Make a decorator to check library

chainer_setup_build.py
=> Check library version

cupy/creation/ranges.py, tests/cupy_tests/creation_tests/test_ranges.py
I wrote a test for `ranges.py`, and found different behaviors.
=> Write test for range and fix linspace method

chainer/links/normalization/batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
This PR fix bug when use `volatile="on"` and ~~`test=True`~~ `test=False`.
=> Fix batch normalization

tests/cupy_tests/test_ndarray_elementwise_op.py
0 div causes infinity or NaN, and it causes error.
related to #801
=> Use positive values only in tests for elementwise operators

README.md
=> Fix account information

.travis.yml, chainer/functions/math/matmul.py, chainer/gradient_check.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py, tests/chainer_tests/test_function_set.py, tests/chainer_tests/test_variable.py
=> Remove deprecated warning

chainer/serializers/hdf5.py, tests/chainer_tests/serializers_tests/test_hdf5.py
=> Fix HDFSerializer.__getitem__

chainer/links/connection/lstm.py, tests/chainer_tests/links_tests/connection_tests/test_lstm.py
=> to_cpu and to_gpu move LSTM's states

chainer/functions/__init__.py, chainer/functions/activation/elu.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/activation_tests/test_elu.py
=> Implement ELU

chainer/functions/__init__.py, chainer/functions/array/expand_dims.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_expand_dims.py
I implemented expand_dims function.
=> expand_dims function

cupy/cudnn.py
I found odd messages (and typo), so fixed them.
=> Fix error messages of create_tensor_descriptor

docs/source/install.rst, docs/source/tutorial/type_check.rst
It was wrong symbol of the list that you are using for the manual.
=> fixes manual's list format.

cupy/testing/__init__.py, cupy/testing/helper.py, tests/cupy_tests/testing_tests/test_helper.py
=> Fix assertion name in cupy.testing

cupy/__init__.py, cupy/manipulation/dims.py, docs/source/cupy-reference/manipulation.rst, docs/source/cupy-reference/overview.rst, tests/cupy_tests/manipulation_tests/test_dims.py
=> Implement broadcast_to

chainer/functions/__init__.py, chainer/functions/evaluation/binary_accuracy.py, tests/chainer_tests/functions_tests/evaluation_tests/test_binary_accuracy.py
This is the function to compute accuracy of binary classification. (typically used with sigmoid_cross_entropy)
=> Add binary accuracy

cupy/__init__.py, cupy/manipulation/rearrange.py, docs/source/cupy-reference/manipulation.rst, docs/source/cupy-reference/overview.rst, tests/cupy_tests/manipulation_tests/test_rearrange.py
=> Implement roll

chainer/functions/array/select_item.py
`operator(int[])` is faster than `operator(int)`.
=> Use int[] indexing in select_item

chainer/functions/__init__.py, chainer/functions/array/broadcast.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_broadcast.py
I implemented `broadcast_to` function.
related to #642
=> broadcast_to function

docs/source/tutorial/basic.rst
fixed the summation of accuracy
=> fixed tutorial docs

.travis.yml, README.md, chainer/serializers/__init__.py, chainer/serializers/hdf5.py, chainer_setup_build.py, docs/source/install.rst, setup.py, tests/chainer_tests/serializers_tests/test_hdf5.py
=> H5py optional

tests/chainer_tests/serializers_tests/test_hdf5.py
We also need to remove `npz` from `sys.module`
=> Remove npz from sys.module on testning import

tests/chainer_tests/functions_tests/math_tests/test_sum.py
=> Change atol for test of sum

cupy/core/core.pyx, tests/cupy_tests/core_tests/test_ndarray.py
=> Fix take and make a test

cupy/core/core.pyx, tests/cupy_tests/core_tests/test_ndarray.py
=> Support int indices for take, and fix test

docs/source/install.rst
=> Fix supported numpy version

tests/chainer_tests/functions_tests/math_tests/test_sum.py
I changed gradient value for test of `sum` to prevent errors.
=> Use random value for gradient in test script

.travis.yml
=> Only install hacking

cupy/core/core.pyx
`cupy.take` is slow as it uses `ndarray::operator(int)`. To improve its performance, I made a special kernel for a specific case such that `a.ndim==2` and `axis==0`, that is used in `F.EmbedID`.
Here is the performance comparison:
original:
```
% time python take_test.py
python take_test.py  3.70s user 1.75s system 87% cpu 6.232 total
```
nvprof
```
Time(%)      Time     Calls       Avg       Min       Max  Name
99.88%  4.49121s      1000  4.4912ms  4.4110ms  5.4444ms  cupy_take
```
improved:
```
% time python take_test.py
python take_test.py  0.83s user 1.07s system 71% cpu 2.657 total
```
nvprof
```
Time(%)      Time     Calls       Avg       Min       Max  Name
99.47%  964.29ms      1000  964.29us  904.14us  1.3731ms  cupy_take_2dim_0axis
```
And, this is the test script:
```
% cat …
```
=> Make a special kernel for take function

docs/source/compatibility.rst, docs/source/index.rst
=> Add compatibility policy

cupy/cuda/stream.py
Fix #793. It still lacks tests (as is).
=> Fix Stream and Event nullptr value

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/gradient_check.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
Fix #816.
This PR is related to #850.
=> Support noncontiguous array

chainer/functions/loss/ctc.py, tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
=> Fix CTC document

chainer/functions/loss/softmax_cross_entropy.py
=> Improve softmax_cross_entropy

chainer_setup_build.py
=> Add return value to test code of check_cuda_version and check_cudnn_version

tests/chainer_tests/functions_tests/activation_tests/test_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py, tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
=> Add tests which check if functions use cudnn correctly

cupy/cuda/compiler.py, tests/cupy_tests/cuda_tests/test_compiler.py
=> Change a message of an error called when nvcc fails

README.md
=> Write minimum version of g++

chainer/links/connection/mlp_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py
I wrote a test for `MLPConvolution2D`, and fixed a bug.
=> Write test for mlp-confolution-2d

.travis.yml
=> Test sdist install in travis

docs/source/install.rst
=> Fix document of cudnn installation

docs/source/tutorial/function.rst
It took me quite a while to figure out what _exactly_ the `backward` methods suppose to compute, so I added a short definition. Maybe that is obvious, but I have more a math than a CS background.
PS: I don't know how I can test the latex formating
=> mathematical definition of backward method

chainer_setup_build.py, setup.py
=> Fix setup problem with numpy 1.11b3

README.md
I hope this makes it easier to go to the documentation page.
=> Add documentation link badge

chainer/variable.py, tests/chainer_tests/test_variable.py
Closes #786. 
@delta2323  Could you take a look?
=> Add Variable.debug_print method

chainer/functions/__init__.py, chainer/functions/pooling/unpooling_2d.py, chainer/utils/conv.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
Closes #597 #301 
Demos
* https://gist.github.com/wkentaro/bb8300867a5ed6d53200 (only unpooling)
* https://gist.github.com/wkentaro/d778c48575d7a0e93042 (stacked pooling & unpooling layers)
Actually, currently I'm not so confident about the operation in `backward_cpu` and it's slow.
=> Unpooling2D Function

docs/source/tutorial/function.rst
I am not an expert in cupy, but these seemed to be typos.
=> Documentation: Fix cupy code in MulAdd (in tutorial on functions)

examples/mnist/train_mnist.py
`remove_split` option is deprecated.
=> Remove remove_split option

chainer/functions/math/det.py, tests/chainer_tests/functions_tests/math_tests/test_det.py
=> Change the shape of return value of det

chainer/functions/__init__.py, chainer/functions/activation/slstm.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/activation_tests/test_slstm.py
=> Implement S-LSTM function

chainer/variable.py, tests/chainer_tests/test_variable.py
=> Check inconsistency of backward calculation and show its function name

tests/chainer_tests/functions_tests/math_tests/test_det.py
Please merge #987 before this PR.
=> Refactor unittests of BatchDet and Det

chainer/__init__.py, chainer/function.py, chainer/variable.py, docs/source/reference/core.rst, docs/source/reference/core/debug.rst, tests/chainer_tests/test_function.py, tests/chainer_tests/test_variable.py
I added debug mode. It raises an error when nan is detected.
=> Debug mode

chainer/functions/__init__.py, chainer/functions/activation/log_softmax.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
I implemented `log_softmax` activation function, which is defined as `log_softmax(x) = log(softmax(x))`
=> Log softmax

chainer/functions/array/select_item.py, chainer/functions/connection/embed_id.py, chainer/functions/loss/softmax_cross_entropy.py, tests/chainer_tests/functions_tests/array_tests/test_select_item.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py, tests/chainer_tests/links_tests/connection_tests/test_embed_id.py, tests/chainer_tests/test_function.py
I'll add check code to functions
- array boundary
- value condition for math functions (such as logarithm)
fix #302 
related to #457 
Please merge #899 before this PR
=> Check input values

tests/chainer_tests/functions_tests/array_tests/test_select_item.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Sometimes empty causes NaN. I fixed test value to use valid values.
=> Use random values

appveyor.yml
I fixed appvayer config to only install hacking.
=> Use hacking instead of flake8 on appvayer

chainer/function.py, chainer/variable.py, tests/chainer_tests/test_function.py
- only check float inputs
- ignore none for gradients
fix #999
=> Check int for input and None for grad

docs/source/tips.rst
fix #704 
This problem is caused in outside of Chainer. I wrote tips about the problem instead of fixing it.
=> Write tips about veclib

chainer/link.py, tests/chainer_tests/test_link.py
=> Copy ChainList's children when it is copied.

chainer_setup_build.py, cupy/cuda/function.pyx, setup.py
This PR remove NumPy dependency during setup.
=> Remove setup_requires

examples/sentiment/train_sentiment.py, examples/word2vec/train_word2vec.py
I simplified the test codes. This patch reduces time for test.
=> Don't read entire data on test mode

docs/source/_static/css/modified_theme.css
=> Add !important to enable our fix for colors

docs/source/tutorial/gpu.rst
=> Fix dead link to MNIST example

chainer/functions/loss/ctc.py, tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Fix following issue.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chainer-jp/k6B7LPSPsbU/3vt33rTNFwAJ
=> Fix ctc when using volatile option

.travis.yml
=> Enable ucs2

setup.py
=> Add function_hooks to setup.py

chainer/variable.py, tests/chainer_tests/test_variable.py
I fixed Variable to raise a TypeError with a readable message when an invalid argument is given.
=> Raise type error

docs/source/contribution.rst
I updated contribution guide.
- fix description of major/minor/revision
- fix CI environment especially about AppVeryor
- remove pyformat and isort
=> Fix contribution guide

docs/source/tutorial/gpu.rst
=> Fix dead link

examples/mnist/train_mnist.py
I fixed mnist example to show throughput.
=> Show throuput in mnist example

.travis.yml, appveyor.yml
This PR reduce installation script bug (see #1050) .
=> Improve test scripts

chainer_setup_build.py
=> Show error detail

.travis.yml, chainer/function.py, chainer/function_set.py, chainer/functions/activation/lstm.py, chainer/functions/activation/maxout.py, chainer/utils/type_check.py, cupy/__init__.py, cupy/testing/helper.py
=> Use doctest

install/build.py, tests/install_tests/test_build.py
#904 made a regression in which it disables changes e76ff5 and 0cf546. This PR reverts them.
=> Fix chainer setup build

tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
This PR is to simplify the test.
=> Use asfortranarray

chainer/functions/array/split_axis.py, tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
=> Support force_tuple argument

.travis.yml, chainer_setup_build.py, install/build.py, install/utils.py, tests/install_tests/test_build.py, tests/install_tests/test_utils.py
We need to import `setuptools` to use `distutils.ccompiler`. And, we also need to set include directory properly to check availability of CUDA.
=> Move methods for test

.coveragerc
I fixed configuration file for coverage to ignore caffe functions
=> Fix coverage configuration for caffe function

chainer/links/normalization/batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
=> Fix decay rate in fine tuning of batch normalization

examples/ptb/genetxt.py, examples/ptb/train_ptb.py
Current example doesn't show how to use the leaning result.
So, I added sample script for the clarification.
=> Add text generation sample to example-ptb

examples/vae/README.md, examples/vae/data.py, examples/vae/net.py, examples/vae/train_vae.py
I have implemented VAE example, which has been suggested in #806
=> Add VAE example

chainer/optimizer.py, tests/chainer_tests/test_optimizer.py
I implements LASSO regularization as optimizer hook.
=> add LASSO optimizer hook

README.md, docs/source/install.rst
=> Support numpy 1.11

chainer/functions/loss/vae.py
I found bernoulli_nll can be slightly more efficient.
=> Shorter version of bernoulli_nll impl

chainer/links/normalization/batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
=> Fix BatchNormalization link on non-current devices

tests/install_tests/test_build.py
=> Call customize_compiler

docs/source/install.rst
=> Clarified CUDA_PATH settings

chainer/__init__.py
=> Show warning on python 3.5.0

chainer/cuda.py, tests/chainer_tests/test_cuda.py
Please merge #1128 before this PR.
=> Fix to_cpu on a multi gpu environment

appveyor.yml
The test is taking about 100 minutes now.
By this PR, test time will be 20 minutes.
=> Speed up the test on AppVeyor

chainer/cuda.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, tests/chainer_tests/test_cuda.py
This PR Improve performance of Chainer
Before
```
alexnet
Average Forward:   38.6161026001  ms
Average Backward:  92.0883331299  ms
Average Total:     131.70443573  ms
googlenet
Average Forward:   186.244589233  ms
Average Backward:  436.125770378  ms
Average Total:     623.370359612  ms
vgga
Average Forward:   242.906954956  ms
Average Backward:  484.999596786  ms
Average Total:     728.906551743  ms
overfeat
Average Forward:   127.565898132  ms
Average Backward:  267.213549757  ms
Average Total:     395.779447889  ms
```
After
```
alexnet
Average Forward:   35.5342430115  ms
Average Backward:  80.5552033186  ms
Average Total:     117.08944633  ms
googlenet
Average Forward:   148.332102966  ms
Average Backward:  337.020146561  ms
Average Total:     486.352249527  ms
vgga
Average Forward: …
```
=> Improve  workspace management of cuDNN

chainer/functions/__init__.py, chainer/functions/pooling/roi_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
=> Add ROIPooling2D function

tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
=> Fix roi pooling test

chainer/functions/activation/relu.py, chainer/functions/activation/sigmoid.py, chainer/functions/activation/tanh.py, cupy/cudnn.py, tests/chainer_tests/functions_tests/activation_tests/test_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
=> cuDNN c-contiguous

chainer/functions/activation/sigmoid.py, chainer/functions/activation/tanh.py, tests/chainer_tests/functions_tests/activation_tests/test_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
I fixed activation functions to support zero-dimensional arrays
merge #1198 first
=> Activation functions for zero-dim arrays

cupy/__init__.py, tests/cupy_tests/test_init.py
=> Change error message when CuPy is not installed

tests/chainer_tests/functions_tests/array_tests/test_broadcast.py, tests/chainer_tests/functions_tests/array_tests/test_concat.py, tests/chainer_tests/functions_tests/array_tests/test_copy.py, tests/chainer_tests/functions_tests/array_tests/test_expand_dims.py, tests/chainer_tests/functions_tests/array_tests/test_reshape.py, tests/chainer_tests/functions_tests/array_tests/test_select_item.py, tests/chainer_tests/functions_tests/array_tests/test_split_axis.py, tests/chainer_tests/functions_tests/array_tests/test_swapaxes.py, tests/chainer_tests/functions_tests/array_tests/test_transpose.py, tests/chainer_tests/functions_tests/array_tests/test_where.py
Please merge #1201 before this PR.
=> Add tests for float16 and float64 in functions.array

chainer/function.py, chainer/functions/array/copy.py, tests/chainer_tests/functions_tests/array_tests/test_copy.py
I fixed copy function to support copying arrays between CPU and GPU.
fix #1157
=> Copy arrays between CPU and GPU

chainer/functions/pooling/average_pooling_2d.py, chainer/functions/pooling/max_pooling_2d.py, chainer/functions/pooling/pooling_2d.py, chainer/functions/pooling/unpooling_2d.py, chainer/utils/conv.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
=> Loosen type condition in pooling functions

chainer/functions/activation/clipped_relu.py, chainer/functions/activation/elu.py, chainer/functions/activation/leaky_relu.py, chainer/functions/activation/log_softmax.py, chainer/functions/activation/lstm.py, chainer/functions/activation/maxout.py, chainer/functions/activation/prelu.py, chainer/functions/activation/relu.py, chainer/functions/activation/sigmoid.py, chainer/functions/activation/slstm.py, chainer/functions/activation/softmax.py, chainer/functions/activation/softplus.py, chainer/functions/activation/tanh.py, cupy/cudnn.py, tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_elu.py, tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_lstm.py, tests/chainer_tests/functions_tests/activation_tests/test_maxout.py, tests/chainer_tests/functions_tests/activation_tests/test_prelu.py, tests/chainer_tests/functions_tests/activation_tests/test_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_slstm.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softplus.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_local_response_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
=> Loosen type condition in activation functions

README.md, docs/source/install.rst
=> Add cuDNN v5 information

chainer/functions/activation/log_softmax.py, chainer/functions/activation/relu.py, chainer/functions/activation/sigmoid.py, chainer/functions/activation/softmax.py, chainer/functions/activation/tanh.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
The cuDNN v2 do not support float16 operation.
=> Fix activation functions bug on cuDNN v2

chainer/functions/__init__.py, chainer/functions/activation/hard_sigmoid.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py
I implemented hard sigmoid function.
=> Implement hard-sigmoid

chainer/functions/__init__.py, chainer/functions/math/linear_interpolate.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_linear_interpolate.py
I implemented linear-interpolation function. It is about two times faster than simple implementation with math-operators, and reduces required memory.
=> Linear interpolate

chainer/computational_graph.py, examples/mnist/train_mnist.py, tests/chainer_tests/test_computational_graph.py
=> Add feature to customize dot graph

chainer/functions/__init__.py, chainer/functions/math/exponential_m1.py, chainer/functions/math/logarithm_1p.py, tests/chainer_tests/functions_tests/math_tests/test_exponential_m1.py, tests/chainer_tests/functions_tests/math_tests/test_logarithm_1p.py
I am really sorry for opening another pull request that is the same as #1173 .
If there is something wrong, please give me comments.
Thanks.
=> Add log1p and expm1 functions.

chainer/computational_graph.py, tests/chainer_tests/test_computational_graph.py
=> Set direction of dotgraph by rankdir

tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
The optimizers accept an array of numpy.float16, numpy.float32 and numpy.float64.
Please merge #1162 before this PR.
See also #555.
=> Add tests of float16 and float64 to the optimzers

tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py
I fixed unstable test for hard-sigmoid.
=> Avoid unstable test

chainer/functions/__init__.py, chainer/functions/array/cast.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_cast.py
I think this function is required to use fp16.
=> Cast function

chainer/cuda.py, docs/source/reference/util.rst
=> Add document about functions of cuDNN workspace

chainer/links/__init__.py, chainer/links/connection/lstm.py, docs/source/reference/links.rst, tests/chainer_tests/links_tests/connection_tests/test_lstm.py
=> Implement StatelessLSTM

README.md
I removed  a badge showing download count.
=> Remove donwload badge which doesn't work

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> Check broadcast before calculation on var-const operations

chainer/computational_graph.py
This PR fixes a bug in computational_graph.
=> DotNode: attribute dict should be updated

chainer/functions/array/get_item.py, tests/chainer_tests/functions_tests/array_tests/test_get_item.py
I fixed get_item function to support newaxis.
=> Support newaxis

chainer/functions/__init__.py, chainer/functions/array/transpose_sequence.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_transpose_sequence.py
I implemented transpose sequence function which transposes list of `Variable`s. It requires to make new LSTM function.
related to #1146
=> Transpose sequence

cupy/__init__.py, cupy/manipulation/join.py, tests/cupy_tests/manipulation_tests/test_join.py
I implemented stack function that is supported numpy >= 1.10.
=> Implement stack function on CuPy

chainer/function.py, tests/chainer_tests/test_function.py
=> Wrap input values with Variable automatically

chainer/functions/__init__.py, chainer/functions/array/permutate.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_permutate.py
I implemented permutate function. This is a special case of `take` function.
related to #1146
=> Permutate function

docs/source/cupy-reference/manipulation.rst
I added a document of stack function.
=> Add document of stack

chainer/functions/array/concat.py, cupy/manipulation/split.py, tests/chainer_tests/functions_tests/array_tests/test_concat.py, tests/cupy_tests/manipulation_tests/test_split.py
=> Fix concat function when using negative index

cupy/__init__.py, cupy/core/core.pyx, cupy/indexing/generate.py, cupy/sorting/search.py, docs/source/cupy-reference/indexing.rst, docs/source/cupy-reference/sorting.rst, tests/cupy_tests/core_tests/test_scan.py, tests/cupy_tests/indexing_tests/test_generate.py, tests/cupy_tests/sorting_tests/test_search.py
This PR is add some  cupy functions.
- cupy.nonzero
- cupy.flatnonzero
- cupy.ix_
- cupy.ndarray.nonzero
1. src = [-1, 1, 0, 2]
2. candidate = src != 0 ==> \[ True, True, False, True \] (bool array) ==> \[1, 1, 0, 1\] (int array)
3. scan = inclusive_scan( candidate) ==> [ 1, 2, 2, 3 ]
4. for i in xrange(len(src) ): nonzero[ scan[n]-1 ] = n if src[n] != 0
5. nonzero ==> [ 0, 1, 3]
=> add cupy.nonzero, cupy.flatnonzero, cupy.ix_

chainer/variable.py
=> Fix docstring

chainer/functions/pooling/average_pooling_2d.py, chainer/functions/pooling/unpooling_2d.py, cupy/core/core.pyx, cupy/manipulation/dims.py
`numpy.newasix` and `cupy.newaxis` is `None`.
=> Stop using numpy.newaxis and cupy.newaxis

setup.cfg
=> Delete old file information

.travis.yml
=> Enable cache on travis

chainer/cuda.py, tests/chainer_tests/test_cuda.py
=> Fix get_device

chainer/functions/math/sum.py, tests/chainer_tests/functions_tests/math_tests/test_sum.py
I'm going to fix #1152 at June 21st http://chainer.connpass.com/event/33526/.
=> fix 0-dim sum backward

chainer/initializers/constant.py, chainer/initializers/normal.py, chainer/links/caffe/caffe_function.py, cupy/random/distributions.py, examples/word2vec/README.md
=> Fix some typos

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/deconvolution_2d.py
This reverts commit 737a6e5fcc175e5d70edbaa83dee000dfdf25fdb, reversing
changes made to 8c9e0c6136a3f3ed87afafb365efd155b40c1905.
=> Revert merging pull request #1189

chainer/functions/__init__.py, chainer/functions/array/stack.py, tests/chainer_tests/functions_tests/array_tests/test_stack.py
I implemented stack function.
It is equivalent to stack method in numpy.
http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.stack.html
=> Stack function

chainer/links/caffe/caffe_function.py
=> Fix document of caffe function

chainer/optimizers/smorms3.py
Some GPU tests related to SMORMS3 optimizer fails. This PR fixes it.
=> Fix SMORMS3

chainer/optimizers/smorms3.py
I removed redundant calculation.
=> Optimize smorms

chainer/functions/__init__.py, chainer/functions/activation/crelu.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/activation_tests/test_crelu.py
This PR implements a new activation function CReLU (Concatenated ReLU) described in http://arxiv.org/abs/1603.05201.
=> Implement CReLU (Concatenated ReLU)

docs/source/contribution.rst
This PR adds the description on contribution-welcome labels to the document.
=> Add description on contribution-welcome category

chainer/functions/array/split_axis.py, tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
=> Support empty section

chainer/functions/__init__.py, chainer/functions/loss/triplet.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
This PR is only the triplet loss from #1225
=> Triplet loss

docs/source/reference/check.rst
Added missing whitespace before 'automodule'.
=> Fix reference documentation

chainer/links/normalization/batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Initialize `batch_normalization` link's gamma and beta using `initializers`. #1243
=> initializers for batch_normalization

chainer/functions/__init__.py, chainer/functions/normalization/l2_normalization.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
This PR is only the l2 normalization layer from #1225.
=> Normalize l2

chainer/functions/pooling/unpooling_2d.py
=> Fix the description of cover_all option of unpooling_2d

chainer/dataset/convert.py, chainer/dataset/dataset_mixin.py, chainer/dataset/download.py, chainer/dataset/iterator.py, chainer/datasets/image_dataset.py, chainer/datasets/mnist.py, chainer/datasets/sub_dataset.py, chainer/iterators/multiprocess_iterator.py, chainer/iterators/sequential_iterator.py, chainer/iterators/shuffled_iterator.py, chainer/reporter.py, chainer/training/__init__.py, chainer/training/extensions/evaluator.py, chainer/training/extensions/linear_shift.py, chainer/training/trainer.py, chainer/training/trigger.py, chainer/training/updater.py, docs/source/reference/iterators.rst, examples/mnist/train_mnist_data_parallel.py, tests/chainer_tests/dataset_tests/test_convert.py, tests/chainer_tests/dataset_tests/test_dataset_mixin.py, tests/chainer_tests/dataset_tests/test_download.py, tests/chainer_tests/datasets_tests/test_dict_dataset.py, tests/chainer_tests/datasets_tests/test_sub_dataset.py, tests/chainer_tests/datasets_tests/test_tuple_dataset.py, tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py, tests/chainer_tests/iterators_tests/test_sequential_iterator.py, tests/chainer_tests/iterators_tests/test_shuffled_iterator.py
This PR adds ParallelUpdater that implements data parallelism on multiple GPU. An example of data parallel model using 2 GPUs is given for the mnist dataset.
=> Added data parallel example

chainer/functions/__init__.py, chainer/functions/math/minmax.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_minmax.py
I implemented argmin and argmax function.
related to #1020 and #1092
=> Argmin argmax

chainer/functions/pooling/roi_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
(continued from #1273)
I fixed a bug in test.
=> fix bug in roi pooling forwarding with cpu (continued from #1273)

docs/source/conf.py, docs/source/tutorial/basic.rst, docs/source/tutorial/gpu.rst
I fixed code snippets in the document to pass doctest.
=> Fix document to pass test

chainer/cuda.py, cupy/core/core.pyx, cupy/cuda/memory.pyx, cupy/cuda/runtime.pyx, cupy/cuda/stream.py, tests/chainer_tests/test_cuda.py
=> Async to_gpu

chainer/optimizer.py, tests/chainer_tests/test_optimizer.py
Support gradient hard-clipping #701
=> Add gradient hard-clipping

chainer/functions/math/maximum.py, chainer/functions/math/minimum.py, docs/source/reference/functions.rst
This PR fixes broken documentations in maximum and minimum functions.
=> Fix broken documentations in maximum and minimum.

tests/chainer_tests/test_optimizer.py
I fixed the test of gradient noise with fixing random value.
=> Remove random behavior from gradient noise test

chainer/functions/math/bias.py, chainer/functions/math/scale.py, chainer/links/connection/bias.py, chainer/links/connection/scale.py
This PR fixes broken documentation in bias and scale.
=> Fix broken documentation in bias and scale.

chainer/links/connection/lstm.py, tests/chainer_tests/links_tests/connection_tests/test_lstm.py
This PR is for adding set_state method to LSTM link #1370 .
=> Add set_state to LSTM.

chainer/functions/array/transpose_sequence.py
This patch is about 10x faster than the original. fix #1365
=> Improve transpose sequence

docs/source/cupy-reference/environment.rst, docs/source/cupy-reference/index.rst, docs/source/install.rst, docs/source/reference/environment.rst, docs/source/reference/index.rst
fix #1227
We need to consider about CHAINER_SEED.
=> Write document about environment variables

chainer/training/extensions/log_report.py
=> Fix file name format of LogReport.

docs/source/tutorial/gpu.rst
=> Add note on the scale of the gradient in multi-gpu setting

examples/ptb/README.md
The ptb example downloads data automatically.
=> Remove an obsolete sentence from ptb example's README

chainer/functions/__init__.py, chainer/functions/array/select_item.py, chainer/functions/loss/crf1d.py, chainer/links/__init__.py, chainer/links/loss/crf1d.py, docs/source/reference/functions.rst, docs/source/reference/links.rst, tests/chainer_tests/functions_tests/loss_tests/test_crf1d.py
I implemented crf loss function which calculates negative log-likelihood of linear-chain CRF. It also contains Viterbi algorithm to find the best path.
And this PR contains log-sum-exp function and argmin/argmax function.
=> Linear-chain CRF

chainer/iterators/serial_iterator.py, tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py, tests/chainer_tests/iterators_tests/test_serial_iterator.py
=> Fix the shuffle timing to always re-shuffle after an epoch #1416

chainer/datasets/cifar.py, chainer/function_set.py, chainer/functions/loss/contrastive.py, chainer/optimizer.py
=> fix markup in docstring

chainer/link.py, tests/chainer_tests/test_link.py
=> Deduplicate Chain.zerograd

chainer/functions/activation/clipped_relu.py, chainer/functions/activation/hard_sigmoid.py, chainer/functions/activation/softplus.py, chainer/functions/array/cast.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/linear.py, chainer/functions/math/basic_math.py, chainer/functions/math/exponential_m1.py, chainer/functions/math/logarithm_1p.py, chainer/functions/pooling/roi_pooling_2d.py, chainer/gradient_check.py, chainer/links/loss/hierarchical_softmax.py, chainer/utils/__init__.py, tests/chainer_tests/utils_tests/test_utils.py
`astype` returns new array in default mode.
This PR uses `copy=False` option.
And, PR extends `utils.force_array` that receives `dtype` argument.
=> Reduce extra copy

chainer/training/extensions/log_report.py
This PR fixes the problem reported in #1394.
=> Remove log file if it exists in LogReport

chainer/functions/loss/softmax_cross_entropy.py
LogSoftmax and SoftmaxCrossEntropy have the same codes. I replaced the shared code to simplify it.
=> Use LogSoftmax in SoftmaxCrossEntropy

chainer/functions/loss/sigmoid_cross_entropy.py
follow the document in softmax_cross_entropy
cf. https://github.com/pfnet/chainer/blob/master/chainer/functions/loss/softmax_cross_entropy.py#L177
=> Fix the document in sigmoid_cross_entropy

chainer/datasets/cifar.py
#1422 
I tried get_cifar10 method, But output error.
This is typo?
=> modify datasets/cifar.py

chainer/training/updater.py
I fixed ParallelUpdater for dict type dataset.
=> Fix parallel updater

cupy/__init__.py, cupy/indexing/insert.py, docs/source/cupy-reference/indexing.rst, tests/cupy_tests/indexing_tests/test_insert.py
Related to #1294 
http://docs.scipy.org/doc/numpy-1.11.0/reference/generated/numpy.fill_diagonal.html
=> Implement cupy.fill_diagonal()

chainer/functions/array/split_axis.py
`splix_axis` needs to support both int and long in python2.
=> Accept both int and long

.flake8.cython, .travis.yml, docs/source/contribution.rst
I added config file for flake8 command for cython code.
relate to #1292
=> Flake8 cython config

chainer/initializers/constant.py
=> Simplify the identity initializer

cupy/core/carray.cuh
=> Fix division of float16

chainer/functions/math/basic_math.py, chainer/functions/math/matmul.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_matmul.py
=> Implement matmul operator to Variable

chainer/functions/__init__.py, chainer/functions/loss/black_out.py, chainer/links/__init__.py, chainer/links/loss/black_out.py, tests/chainer_tests/functions_tests/loss_tests/test_black_out.py, tests/chainer_tests/links_tests/loss_tests/test_black_out.py
I implemented blackout loss. This PR contains `logsumexp` function implemented in #1216.
And, I sometimes faces overflow with this implementation. I think it sometimes generates inf. 
fix #1073
=> Blackout loss function

tests/chainer_tests/functions_tests/math_tests/test_matmul.py
Sorry, matmul test is broken. related to #1138
=> Fix matmul test

chainer/functions/activation/lstm.py, chainer/links/connection/lstm.py, tests/chainer_tests/functions_tests/activation_tests/test_lstm.py, tests/chainer_tests/links_tests/connection_tests/test_lstm.py
=> Support variable length inputs for LSTM

chainer/functions/__init__.py, chainer/functions/math/trigonometric.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_trigonometric.py
This PR implements trigonometric `tan` function.
=> Implement tangent function.

chainer/training/extensions/evaluator.py
In `Evaluator`, volatile of `Variable` needs to be `on`.
=> Set volatile on in Evaluator

chainer/datasets/cifar.py
=> Fix download function of CIFAR-100

chainer/training/extensions/progress_bar.py
=> Fix ProgressBar iters per sec

tests/chainer_tests/training_tests/extensions_tests/test_exponential_shift.py
I wrote a unit test for ExponentialShift.
=> Added test for exponential_shift

tests/chainer_tests/training_tests/extensions_tests/test_linear_shift.py
I wrote a test for LinearShift.
=> Add test for linear_shift

chainer/functions/__init__.py, chainer/functions/array/hstack.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_hstack.py
This PR is for supporting `hstack` mentioned in #1280 .
It is equivalent to hstack method in numpy.
=> Support hstack function

tests/chainer_tests/functions_tests/math_tests/test_trigonometric.py
I fixed test for sin, cos and tan to check `float16`, `float32` and `float64`. I also refactored the test to make it parameterized one.
related to #1480
=> Fix trigonometric test

cupy/core/reduction.pxi, tests/cupy_tests/core_tests/test_reduction.py
=> Fix overflow in reduction kernel

chainer/functions/math/clip.py, tests/chainer_tests/functions_tests/math_tests/test_clip.py
clip supports all float types.
related to #555
=> Support float types in clip function

chainer/functions/activation/maxout.py, chainer/functions/array/separate.py, chainer/functions/loss/black_out.py, chainer/functions/loss/crf1d.py, chainer/functions/loss/ctc.py, chainer/functions/loss/vae.py, chainer/functions/math/bias.py, chainer/functions/math/det.py, chainer/functions/math/scale.py, chainer/functions/pooling/spatial_pyramid_pooling_2d.py, chainer/gradient_check.py, chainer/links/connection/bilinear.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/linear.py, chainer/links/connection/lstm.py, chainer/links/connection/peephole.py, chainer/links/loss/black_out.py, chainer/links/loss/hierarchical_softmax.py, chainer/links/normalization/batch_normalization.py, chainer/variable.py, tests/chainer_tests/test_variable.py
Some links and functions uses attributes of `Variable.data`. So I cannot use `numpy.ndarray` and `cudpy.ndarray` directly although `Function` supports ndarrays.
I added attributes to `Variable` which returns corresponding values of ndarray.
=> Variable attribute

chainer/functions/activation/crelu.py, tests/chainer_tests/functions_tests/activation_tests/test_crelu.py
CRelu supports all float types.
related to #555
=> Crelu dtype

tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
matmul test is unstable now. I fixed it.
=> Make matmul test stable

chainer/links/caffe/caffe_function.py, tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
=> Added support for Slice Caffe function.

chainer/functions/noise/dropout.py, tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
dropout supports all float types.
related to #555
=> Support float types in dropout function

chainer/reporter.py, tests/chainer_tests/test_reporter.py
=> Support reporter to report scalar variable

README.md, docs/source/install.rst
=> Support cuDNN v5.1

cupy/cuda/compiler.py
=> Check nvcc version and use it to calculate hash value for cubin file name

chainer/links/connection/peephole.py
This PR fixes StatefulPeepholeLSTM's docstring.
=> Fix docstring of StatefulPeepholeLSTM.

chainer/training/extensions/progress_bar.py
```
epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy
total [..................................................]  0.83%
this epoch [########..........................................] 16.67%
100 iter, 0 epoch / 20 epochs
inf iters/sec. Estimated time to finish: 0:00:00.
```
=> Show progress bar at first iteration

chainer/functions/__init__.py, chainer/functions/math/hyperbolic.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_hyperbolic.py
This PR implements hyperbolic cosine and sine functions.
Hyperbolic tangent function `tanh` is already supported as an activation function, so I added a link to show that in reference to let users jump.
=> Implement hyperbolic cosine and sine functions.

cupy/manipulation/join.py, tests/cupy_tests/manipulation_tests/test_join.py
=> Fix vstack

cupy/manipulation/join.py, tests/cupy_tests/manipulation_tests/test_join.py
=> Fix cupy.dstack

chainer/training/updater.py
Use deep copy for slave models in ParallelUpdater. Zero parameter gradients just before backward computation (to allow for parameters initialized on first call).
In ParallelUpdater, each of the main model and the slave models needed to have its own version of `_uninitialized_params`. In the previous code that was a set shared between the models (because of the shallow copy). When one model has the delayed parameters initialized at call time, the set became empty and no other models could have their parameters initialized. So I used deep copy. 
The change also means that the parameters initialized at call time (using parameter shape place holder) will not be the same across the main and the slave models. 
Additionally, the gradients are zeroed only once all the parameters have been …
=> This fixes the 'train_mnist_data_parallel.py' example when using shape placeholder in MLP.

cupy/core/core.pyx, cupy/cuda/cublas.pxd, cupy/cuda/cublas.pyx, cupy/cuda/cupy_cuda.h, cupy/cuda/runtime.pxd, cupy/cuda/runtime.pyx
Cupy use cublasSgemmEx to reduce memory usage.
=> Use cublasSgemmEx when input dtype is float16

chainer/cuda.py
=> Restrict the cuDNN warning not to print more than once

chainer/link.py, chainer/optimizer.py, chainer/variable.py
Deprecate `Link.zerograds` and `Variable.zerograd`
=> Deprecate zerograd(s)

chainer/functions/__init__.py, chainer/functions/array/flatten.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_flatten.py
I implemented flatten function.
=> Implement flatten function

docs/source/reference/functions.rst
=> Fix functions.rst

.travis.yml
I fixed travis config to install pillow and to run test of image dataset.
related to #1513
=> Install pillow to test imagadataset

chainer/optimizer.py
This is useful than passing an argument of the update method.
=> Modify GradientMethod to use a flag of an object for cleargrads.

chainer/cuda.py
Fix https://github.com/pfnet/chainer/issues/1454
=> Suppress cuDNN warning when cuDNN is disabled by a user

docs/source/tutorial/basic.rst, docs/source/tutorial/gpu.rst, docs/source/tutorial/recurrentnet.rst
Depends on https://github.com/pfnet/chainer/pull/1570.
=> Use cleargrads in tutorial

docs/source/tutorial/basic.rst, docs/source/tutorial/gpu.rst, examples/mnist/train_mnist.py, examples/mnist/train_mnist_model_parallel.py
Documentation to https://github.com/pfnet/chainer/pull/1551
=> Update documentation for parameter shape placeholder in MNIST example.

cupy/core/core.pyx
Reduce copy in tensordot_core.
=> Reduce copy in tensordot_core

tests/cupy_tests/cuda_tests/test_stream.py, tests/cupy_tests/test_init.py
Remove cupy_test's dependency to chainer
=> Remove cupy_test's dependency to chainer

cupy/core/core.pyx
Fixes https://github.com/pfnet/chainer/issues/1609.
Ref: https://github.com/pfnet/chainer/pull/1612
=> Fix build for Cython 0.23

chainer/__init__.py
=> Fix note notation

tests/cupy_tests/core_tests/test_ndarray.py, tests/cupy_tests/core_tests/test_reduction.py, tests/cupy_tests/indexing_tests/test_insert.py, tests/cupy_tests/manipulation_tests/test_dims.py
I removed redundant `accept_error` arguments.
related to #1553
=> Fix accept_error

chainer/training/triggers/minmax_value_trigger.py, chainer/training/util.py
I found some dead links in the document of triggers.
related to #1506
=> Fix trigger document

setup.py
This PR may add license description to PyPI.
=> Add license description to setup.py

chainer/functions/__init__.py, chainer/functions/math/floor.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_floor.py
This PR implements floor function with covering test for input of dtype float16, float32 and float64.
=> Implement floor function.

chainer/functions/__init__.py, chainer/functions/math/ceil.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_ceil.py
This PR implements ceil function with covering test for input of dtype float16, float32 and float64.
=> Implement ceil function.

chainer/functions/loss/black_out.py, docs/source/reference/functions.rst, docs/source/reference/links.rst
https://github.com/pfnet/chainer/issues/1073
=> Add BlackOut to docs

cupy/cuda/cupy_cuda.h, cupy/cuda/nvtx.pyx
=> Fix nvtx on Read the Docs

.travis.yml
Sometimes document on Read the Docs is broken.
This PR will detect a build error.
=> Add build test for Read the Docs

tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
This reduces waiting time for test.
=> Add slow attribute to TestConvolutionND

chainer/__init__.py
Fix https://github.com/pfnet/chainer/issues/1655.
=> Raise an exception on Python 3.5.0

chainer/functions/__init__.py, chainer/functions/connection/dilated_convolution_2d.py, chainer/links/__init__.py, chainer/links/connection/dilated_convolution_2d.py, chainer/utils/conv.py, docs/source/reference/functions.rst, docs/source/reference/links.rst, tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/utils_tests/test_conv.py
I created the issue in #1283. This PR will add dilated convolution layer (https://arxiv.org/abs/1511.07122).
=> Dilated Convolution Layer

tests/chainer_tests/functions_tests/activation_tests/test_lstm.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py, tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/links_tests/connection_tests/test_gru.py, tests/chainer_tests/links_tests/connection_tests/test_highway.py, tests/chainer_tests/links_tests/connection_tests/test_linear.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
This PR reduces extra test cases.
=> Speed up tests

chainer/functions/math/trigonometric.py
This PR removes an unused variable in trigonometric functions.
=> Remove unused variable in trigonometric functions.

chainer/functions/activation/lstm.py, chainer/functions/activation/sigmoid.py, chainer/functions/activation/slstm.py, tests/chainer_tests/functions_tests/activation_tests/test_lstm.py, tests/chainer_tests/functions_tests/activation_tests/test_slstm.py, tests/chainer_tests/links_tests/connection_tests/test_gru.py, tests/chainer_tests/links_tests/connection_tests/test_peephole.py
=> Use tanh instead of exp

.coveragerc
I fixed coverage configuration file for new names of protobuf files.
=> Fix coverage configuration file

docs/source/reference/functions.rst, docs/source/reference/links.rst
=> Fix rst format of the document

chainer/functions/math/basic_math.py
To prevent to show a first argument, I replaced names of arguments with `self`.
fix #1382
=> Added docstring of math operators of Variable

chainer/functions/connection/embed_id.py
Link of See also at http://docs.chainer.org/en/stable/reference/functions.html#embed-id is missed.
=> fix document of functions.embed_id

README.md, docs/source/install.rst
=> Write installation method of pillow in the document

chainer/functions/__init__.py, chainer/functions/array/dstack.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_dstack.py
This PR is for supporting `functions.dstack` mentioned in #1280 .
=> Support dstack

chainer/functions/math/inv.py
This PR fixes some minor document bugs.
=> Fix documents of inv

tests/chainer_tests/functions_tests/math_tests/test_basic_math.py, tests/cupy_tests/core_tests/test_reduction.py
=> Fix style in test

chainer/utils/conv_nd.py
This PR removes unnecessary comments that are missed to remove at 629daf73c7b5c32fadef218dfa0dcb82323efdb7 .
=> Remove unnecessary comments.

docs/source/reference/core/debug.rst
=> Wrote detail of debug mode

docs/source/cupy-reference/difference.rst, docs/source/cupy-reference/index.rst
I made an article about difference between cupy and numpy.
fix #557, #583, #610, #815 
related to #520
=> Make an article about difference between cupy and numpy

docs/source/contribution.rst
=> Add a note about nose option

docker/Dockerfile
I made a draft version of official Dockerfile.
fix #1458
=> Make a dockerfile

chainer/functions/loss/crf1d.py, tests/chainer_tests/functions_tests/loss_tests/test_crf1d.py
I fixed crf1d function to support variable length inputs same as #1209. Users need to sort inputs sequences by length.
=> Support variable length inputs for crf1d

cupy/cuda/cublas.pyx, cupy/cuda/cudnn.pyx, cupy/cuda/curand.pyx, cupy/cuda/runtime.pyx
=> Use nogil statements to enable cupy to use async callback

chainer_setup_build.py
Remove overwrite `from os import path`.
=> Fix setup script

cupy/cuda/cupy_cuda.h, cupy/cuda/cupy_cudnn.h
Note that the header files are always included from a C++ file, checking `__cplusplus` is unnecessary.
=> Add extern "C"

chainer/functions/connection/n_step_lstm.py
=> Make n_step_lstm work with ndarray

chainer/variable.py, tests/chainer_tests/test_variable.py
=> Fix addgrad for cleargrad

chainer/functions/connection/convolution_2d.py
Of course, do not merge this PR before releasing 1.17.0.
=> Clarify convolution_2d's docstring

chainer/functions/__init__.py, chainer/functions/array/tile.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_tile.py
This PR implements tile function which constructs an array by tiling a given array. NumPy and CuPy already have their `tile` functions.
http://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html
=> Implement tile function.

chainer/function_set.py, chainer/functions/activation/lstm.py, chainer/functions/activation/maxout.py, chainer/functions/loss/crf1d.py, chainer/functions/util/forget.py, cupy/cuda/__init__.py, cupy/indexing/generate.py, cupy/indexing/insert.py, cupy/testing/helper.py, docs/source/conf.py, docs/source/tutorial/basic.rst
I fixed all code snippets in docstrings runnable. We can test all codes with `make doctest` under `docs` directory.
=> Make all code snippets runnable

README.md, chainer_setup_build.py, docs/source/install.rst
I found that distutils support CFLAGS and LDFLAGS. Users can override CUDA_PATH with these flags.
=> CFLAGS and LDFLAGS

chainer/functions/__init__.py, chainer/functions/noise/zoneout.py, chainer/links/__init__.py, chainer/links/connection/zoneoutlstm.py, tests/chainer_tests/functions_tests/noise_tests/test_zoneout.py, tests/chainer_tests/links_tests/connection_tests/test_zoneoutlstm.py
I implemented zoneout function and LSTM with zoneout #1339 .
Test Codes has not been implemented yet.
=> Implement zoneout #1339

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/embed_id.py
links of "See also" part in following documents are broken
http://docs.chainer.org/en/stable/reference/functions.html#convolution-2d
http://docs.chainer.org/en/stable/reference/functions.html#convolution-nd
=> fix broken link of convolution_2d and convolution_nd document.

cupy/core/elementwise.pxi, cupy/core/reduction.pxi, tests/cupy_tests/core_tests/test_userkernel.py
Fixed the issue of user defined kernel with fully manual indexing. #1802
=> fix issue of user defined kernel

README.md, docs/source/install.rst
=> Support CUDA 8

docs/source/reference/caffe.rst
=> Fix caffe function name

tests/chainer_tests/training_tests/test_updater.py
I tried to make a unit test for Updater. I made dummy classes for it. I made mock-methods for these dummy classes to check arguments.
=> Add test for updater

README.md, docs/source/install.rst
I wrote a quick description about Docker image.
related to #1756
=> Write description of docker image

cupy/random/generator.py
=> Fix RandomState.__del__ to check if initialization succeeded

cupy/cuda/cupy_cuda.h, cupy/cuda/cupy_cudnn.h
=> Reorganize header file (cupy_cuda.h)

cupy/cuda/cudnn.pxd
=> Fix order of ctypedef in cudnn.pxd

examples/mnist/train_mnist_data_parallel.py
This PR selects default device to fix memory allocation bug.
This problem reported in Japanese forum.
https://groups.google.com/forum/#!msg/chainer-jp/RvnEJ_mtM3U/KlplzOdFCAAJ
=> Fix multi gpu mnist exmaple

chainer/cuda.py, chainer/dataset/convert.py, chainer_setup_build.py, cupy/cuda/__init__.py, cupy/cuda/cupy_cuda.h, cupy/cuda/memory.pyx, cupy/cuda/pinned_memory.pxd, cupy/cuda/pinned_memory.pyx, cupy/cuda/runtime.pxd, cupy/cuda/runtime.pyx, cupy/cuda/stream.py, tests/chainer_tests/test_cuda.py, tests/cupy_tests/core_tests/test_ndarray_get.py, tests/cupy_tests/cuda_tests/test_pinned_memory.py, tests/cupy_tests/cuda_tests/test_stream.py
Please merge #1709 before this PR.
=> Implement pinned memory

chainer/functions/__init__.py
=> Add functions.absolute

chainer_setup_build.py, setup.py
This PR provides simple install script.
=> Use cythonize in install script

cupy/cuda/cupy_cuda.h
=> Fix cuda build on macOS

chainer_setup_build.py
=> Call get_config_vars to initialize config_vars in distutils

cupy/random/__init__.py, cupy/random/distributions.py, docs/source/cupy-reference/random.rst
I implemented sampling method from Gumbel distribution. This function is required for Gumbel-max trick.
=> Sampling method for Gumbel distribution

docker/Dockerfile
=> Remove unnecessary files in Docker script

chainer/functions/__init__.py, chainer/functions/loss/crf1d.py, chainer/links/loss/crf1d.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/loss_tests/test_crf1d.py
I wrote description of argmax function for linear-chain CRF, and made these methods public.
We need to consider about its interface.
=> Wrote document of CRF1d argmax

cupy/__init__.py, cupy/core/__init__.py, cupy/core/core.pyx, cupy/statistics/order.py, docs/source/cupy-reference/statistics.rst, tests/cupy_tests/statics_tests/test_order.py
I implemented nanmin and nanmax.
related to #1536
=> Nanmin and nanmax

chainer/functions/loss/contrastive.py, chainer/functions/loss/cross_covariance.py, chainer/functions/loss/ctc.py, chainer/functions/loss/softmax_cross_entropy.py, chainer/functions/math/batch_l2_norm_squared.py, chainer/functions/math/inv.py, chainer/functions/math/matmul.py, chainer/functions/normalization/batch_normalization.py, chainer/functions/pooling/average_pooling_2d.py, chainer/functions/pooling/spatial_pyramid_pooling_2d.py, chainer/links/activation/maxout.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/dilated_convolution_2d.py, chainer/links/connection/linear.py, chainer/links/connection/lstm.py, chainer/links/connection/scale.py, chainer/links/normalization/batch_normalization.py
Most of commit is emphasis policy.
=> Improve doc consistency

chainer/links/connection/peephole.py
=> Fix peephole doc

chainer_setup_build.py, setup.py
Current install script has some bugs.
This PR reverts #1755.
=> Revert use-cythonize branch

chainer_setup_build.py
Fix https://github.com/pfnet/chainer/issues/1845
=> Use old libstdc++ ABI for Anaconda

tests/chainer_tests/training_tests/test_trainer.py
Fix this problem.
https://ci.appveyor.com/project/pfnet/chainer/build/5659/job/2l1bp05ry42mo8u3
=> Fix elapsed time test on Windows

chainer/functions/array/concat.py
Unifu coding style as other stack function.
=> Refactoring concat

chainer/functions/loss/softmax_cross_entropy.py
I thinks it's redundant assignment.
=> Remove redundant assignment in SoftmaxCrossEntropy

chainer/__init__.py, chainer/cuda.py, chainer/dataset/__init__.py, chainer/datasets/__init__.py, chainer/function_hooks/__init__.py, chainer/functions/__init__.py, chainer/initializers/__init__.py, chainer/iterators/__init__.py, chainer/links/__init__.py, chainer/optimizers/__init__.py, chainer/serializers/__init__.py, chainer/testing/__init__.py, chainer/training/__init__.py, chainer/training/extensions/__init__.py, chainer/training/triggers/__init__.py, chainer/utils/__init__.py, cupy/__init__.py, cupy/core/__init__.py, cupy/cuda/__init__.py, cupy/linalg/__init__.py, cupy/random/__init__.py
Fix #1763
This PR use direct import that imports class and function.
=> Use direct import

cupy/cuda/cupy_cudnn.h
This PR deletes duplicate declarations.
rel #1675
=> Reorganize header file (cupy_cudnn.h)

chainer_setup_build.py, cupy/core/core.pyx, cupy/core/flags.pyx, cupy/core/internal.pyx, cupy/cuda/cublas.pyx, cupy/cuda/cudnn.pyx, cupy/cuda/curand.pyx, cupy/cuda/device.pyx, cupy/cuda/driver.pyx, cupy/cuda/function.pyx, cupy/cuda/memory.pyx, cupy/cuda/nvtx.pyx, cupy/cuda/pinned_memory.pyx, cupy/cuda/profiler.pyx, cupy/cuda/runtime.pyx, cupy/util.pyx, setup.py
This PR provides simple install script.
This PR includes #1775, #1850, #1854 and #1850.
=> Use cythonize to simplify install script

chainer/links/connection/mlp_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py
In current version chainer, I think that MLP convolution shape place holder is supported.
I modified doc and added test for the shape place holder.
=> Test and doc for MLP conv shapeplace holder.

chainer/functions/activation/log_softmax.py
I think the math equations here is corrupted.
=> fix logsoftmax math

chainer/functions/loss/vae.py
Especially, the sign of the second term is wrong.
=> fix bernoulli_nll doc

chainer/functions/math/inv.py, chainer/functions/math/matmul.py
This PR uses `cupy.matmul`.
Rel #1794
=> Simplify matmul function

examples/cifar/models/VGG.py
Fix a pep8 warning when running autopep8.
=> fix pep8 warning on CIFAR example

chainer/functions/evaluation/classification_summary.py, docs/source/reference/functions.rst
Includes the modification of the document.
=> Add classification_summary() to reference

cupy/cuda/driver.pyx
=> Fix GIL problem in load module methods

docs/source/reference/links.rst
I added NStepLSTM to the document.
=> Add document of NStepLSTM

appveyor.yml
=> Disable slow tests in AppVayor

chainer/functions/pooling/upsampling_2d.py
I fixed doctest of upsampling_2d
=> Fix doctest of upsampling_2d

cupy/cuda/runtime.pyx
Ref: https://github.com/pfnet/chainer/issues/1973, https://github.com/pfnet/chainer/pull/1995
=> Add 'with nogil' to cudaStreamWaitEvent call

chainer/variable.py, tests/chainer_tests/test_variable.py
We need to make return value an array for zero-dim arrays.
fix #2021
=> Fix backward accumulation for zero-dim array

cupy/cuda/driver.pyx, cupy/cuda/nvtx.pyx, cupy/cuda/profiler.pyx
Add nogil to CUDA API declarations.
=> Add nogil to CUDA API functions

docs/source/reference/functions.rst
I added description of `n_step_lstm` function.
=> Add document of n_step_lstm

tests/chainer_tests/datasets_tests/test_cifar.py
Use 'autospec'. Related to https://github.com/pfnet/chainer/pull/2037
=> Use autospec in mock creation.

chainer/functions/activation/hard_sigmoid.py
Reference of hard sigmoid function is not correct.
=> fix hard sigmoid reference

.travis.yml, chainer/functions/__init__.py, chainer/functions/theano/theano_function.py, chainer/links/__init__.py, chainer/links/theano/theano_function.py, cupy/cuda/memory.pyx, setup.py, tests/chainer_tests/functions_tests/theano_tests/test_theano.py, tests/chainer_tests/links_tests/theano_tests/test_theano_function.py
I implemented Theano function wrapper. This implementation only support parts of theano functions.
fix #1102
=> Theano function

chainer/functions/connection/n_step_lstm.py
I fixed format of the document of n_step_lstm method.
=> Fixed document format of n_step_lstm

tests/cupy_tests/core_tests/test_ndarray.py, tests/cupy_tests/core_tests/test_scan.py
Add `@testing.gpu` to ignore GPU tests.
=> Add @testing.gpu

cupy/cuda/cupy_cuda.h, cupy/cuda/cupy_cudnn.h
Remove parameters for maintainability.
=> Remove parameters from function declarations in cupy_*.h

cupy/__init__.py, cupy/core/core.pyx, cupy/indexing/indexing.py, tests/cupy_tests/indexing_tests/test_indexing.py
=> Choose method

LICENSE, docs/source/contribution.rst, docs/source/index.rst, docs/source/license.rst
This PR contains suggestions about NumPy 's license.
rel #2004.
=> Add NumPy license and fix contribution guide

chainer/functions/__init__.py, chainer/functions/loss/decov.py, tests/chainer_tests/functions_tests/loss_tests/test_decov.py
This PR is for adding DeCov loss.
The most of the code is from cross_covariance.py, except the diagonal elements are set to zero.
=> Add DeCov loss (https://arxiv.org/abs/1511.06068)

cupy/__init__.py, cupy/indexing/generate.py, tests/cupy_tests/indexing_tests/test_generate.py
Sorry for my commits. I changed these comments if they're not implemented in CuPy compared with NumPy. If you think about anything in writing code or comments of mine, please let me know about that. Thank you.
=> Fix comments problem.

cupy/core/elementwise.pxi, cupy/core/reduction.pxi
This PR add "stream" argument to ElementwiseKernel and ReductionKernel to enable concurrent kernel execution with those kernel.
=> Enable concurrent kernel execution with ElementwiseKernel and ReductionKernel

docs/source/tutorial/basic.rst
I fixed some small issues with the grammar whilst reading the tutorial pages.
=> fixed some small grammatical issues in documentation

docs/source/contribution.rst
Small fix in the contribution guide.
=> Fix markup language

setup.py
Ref: https://github.com/pfnet/chainer/pull/2043
=> Add cupy.ext to packages in the setup function call

cupy/ext/scatter.py
Ref: https://github.com/pfnet/chainer/pull/2094
=> Fix doctest in scatter_add

cupy/core/core.pyx, cupy/core/internal.pxd, cupy/core/internal.pyx, tests/cupy_tests/core_tests/test_internal.py, tests/cupy_tests/core_tests/test_ndarray.py
This PR adds `cupy.ndarray` order option.
=> Add order option to  cupy.ndarray

tests/chainer_tests/serializers_tests/test_hdf5.py
I found that we can use `sys.modules` to emulate h5py unavailable environment.
fix #2078
=> Use sys.modules to emulate situation that h5py is not installed

chainer/functions/math/inv.py, chainer/links/connection/gru.py, chainer/links/connection/lstm.py, chainer/links/connection/peephole.py, chainer/links/connection/zoneoutlstm.py, chainer/links/normalization/batch_normalization.py, tests/chainer_tests/links_tests/connection_tests/test_lstm.py, tests/chainer_tests/links_tests/connection_tests/test_peephole.py, tests/chainer_tests/links_tests/connection_tests/test_zoneoutlstm.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Fix of the issue described here https://github.com/pfnet/chainer/issues/1869.
Reopen from https://github.com/pfnet/chainer/pull/1876(Sorry, this previous PR has some problems and I closed it.)
=> Fix bug about multi gpu in LSTM

README.md
=> Support Python 3.6

cupy/core/internal.pyx, tests/cupy_tests/core_tests/test_internal.py, tests/cupy_tests/core_tests/test_ndarray_indexing.py
Change behavior of complete_slice to fit numpy 1.12.0
=> Change behavior of complete_slice to fit numpy 1.12.0

cupy/core/core.pyx, tests/cupy_tests/core_tests/test_ndarray.py
=> Fix shape setter behavior

chainer/links/caffe/caffe_function.py
=> Remove fs attribute from CaffeFunction

chainer/training/updater.py
#2120 
I fixed `updater.py` for multi optimizers.
=> Fix update.py for multi optimizers

README.md
This PR should be merged after https://github.com/pfnet/chainer/pull/2114.
=> Support NumPy 1.12

chainer/serializer.py
=> Remove ABC

chainer/variable.py, tests/chainer_tests/test_variable.py
Change for https://github.com/pfnet/chainer/issues/1792
=> Change the behaviour of Variable.__len__

cupy/__init__.py
=> Use for instead of generator

tests/cupy_tests/core_tests/test_carray.py
I made a unittest for CArray class written in CUDA.
related to #2150
=> Make a unittest for CArray class

cupy/core/core.pyx
=> Fix name of variable

chainer/functions/connection/linear.py
- linear (functions)
One possible issue to discuss: should the example include all the optional variables (in this case, `b`)?
=> Improve docs of functions/connection/linear

chainer/functions/activation/crelu.py, chainer/functions/activation/elu.py, chainer/functions/activation/slstm.py, chainer/functions/array/depth2space.py, chainer/functions/array/space2depth.py, chainer/functions/loss/black_out.py, chainer/functions/loss/cross_covariance.py, chainer/functions/loss/negative_sampling.py, chainer/functions/noise/dropout.py, chainer/functions/noise/zoneout.py, chainer/functions/normalization/batch_normalization.py, chainer/functions/pooling/roi_pooling_2d.py, chainer/functions/pooling/spatial_pyramid_pooling_2d.py, chainer/initializers/normal.py, chainer/initializers/orthogonal.py, chainer/links/activation/prelu.py, chainer/links/connection/gru.py, chainer/links/connection/inception.py, chainer/links/connection/inceptionbn.py, chainer/links/connection/mlp_convolution_2d.py, chainer/links/model/vision/resnet.py, chainer/links/normalization/batch_normalization.py, chainer/optimizer.py, chainer/optimizers/adam.py, chainer/optimizers/nesterov_ag.py, chainer/optimizers/rmsprop_graves.py, docs/source/reference/graph.rst, examples/cifar/README.md, examples/cifar/models/VGG.py, tests/chainer_tests/functions_tests/loss_tests/test_vae.py
=> Use HTTPS for arXiv

examples/modelzoo/download_model.py
http://research.microsoft.com/en-us/um/people/kahe/resnet/models.zip is removed.
=> Remove resnet from examples/modelzoo/download_model.py

chainer/functions/normalization/batch_normalization.py
=> Add eps to the variance in fixed_batch_normalization

chainer/functions/array/transpose_sequence.py
I slightly improved transpose_sequence.
=> Slightly optimize transpose_sequence

chainer/functions/connection/n_step_lstm.py
I found redundant copy in NStepLSTM.
=> Remove redundant copy from NStepLSTM

chainer/variable.py
`cuda.Device` is slow.
This PR reduces CUDA API call.
=> Improve backward

cupy/core/core.pyx
Merge after #2126.
This PR optimizes `cupy.ndarray.__getitem__` by removing unnecessary copy call using a trick descrbied in #2126.
Here is a benchmark code.
```python
#
import cupy
def benchmark(a, slices):
start = cupy.cuda.Event()
end = cupy.cuda.Event()
start.record()
a[slices]
end.record()
end.synchronize()
time = cupy.cuda.get_elapsed_time(start, end)
return time
n = 3000
slices = (cupy.arange(n), slice(None), cupy.arange(n))
a = cupy.ones((n, 2, n))
cupy.cuda.Stream(null=True).synchronize()
for i in range(5):
benchmark(a, slices)
with cupy.cuda.profile():
print benchmark(a, slices)
```
And result of kernel calls.
Before optimization
```
97.75%  809.65us         1  809.65us  809.65us  809.65us  cupy_copy
0.62%  5.1200us         1  5.1200us  5.1200us  5.1200us  cupy_take_0axis
0.53% …
```
=> Optimize multiple integer array indexing for cupy.ndarray.__getitem__

cupy/__init__.py, cupy/math/sumprod.py, tests/cupy_tests/math_tests/test_sumprod.py
I implemented `cumsum` method. It currently doesn't support `axis` argument.
=> Implemenet cumsum

cupy/cuda/stream.py
=> Fix stream and event bug

cupy/core/elementwise.pxi
Fix the problem not equal two types 'numpy.int32'
=> Numpy.int32 i and l

cupy/core/core.pyx, cupy/manipulation/join.py, tests/cupy_tests/manipulation_tests/test_join.py
I made an optimized kernel for ``concatenate`` method.
related to #1492
=> Optimize concatenate

cupy/core/__init__.py, cupy/core/core.pyx, cupy/manipulation/join.py
Please merge #2144 before this pr.
Concat method is slow because it consumes to check arguments. I cythonized concat method.
=> Cythonize concat method

cupy/__init__.py
=> Remove redundant raise

chainer/functions/__init__.py, chainer/functions/array/fliplr.py, chainer/functions/array/flipud.py, cupy/__init__.py, cupy/manipulation/rearrange.py, tests/chainer_tests/functions_tests/array_tests/test_fliplr.py, tests/chainer_tests/functions_tests/array_tests/test_flipud.py, tests/cupy_tests/manipulation_tests/test_rearrange.py
I fixed #1838 and appended test codes.
This PR includes #1838. Thank you @tsuchm !
=> Implement fliplr and flipud

docs/source/cupy-reference/manipulation.rst, docs/source/reference/functions.rst
=> Add document for fliplr and flipud

cupy/core/core.pyx
This PR reduces the count of kernel launch and memcpy.
=> Optimize concatenate when number of array is small

cupy/core/core.pyx
Some windows environment do not have int32_t.
=> Use int for windows

chainer/functions/connection/n_step_lstm.py
`workspace` attribute is not used
=> Remove unused memory

cupy/cuda/memory.pyx
=> Call gc to release memory when memory is not enough

chainer/training/extensions/plot_report.py
=> Remove matplotlib.use from PlotReport

chainer/computational_graph.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py, tests/chainer_tests/test_init_docstring.py
I wrote a test script to check if all __init__ method do not have docstrings. And I fixed some classes.
fix #2240
=> Write test for docstring of __init__

docs/source/install.rst
I fixed recommended install method for cuDNN.
=> Fix cuDNN installation guide to recommend deb package

chainer/links/connection/n_step_lstm.py, tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py
I fixed NStepLSTM to accept None for h and c like LSTM link.
=> Fix NStepLSTM to accept None

chainer/training/extensions/_snapshot.py, tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
=> Remove trigger option from snapshot and snapshot_object.

chainer/training/extensions/plot_report.py, examples/mnist/train_mnist.py, install/build.py
=> PlotReport causes error in MNIST example when matplotlib doesn't exist

docs/source/tutorial/gpu.rst
=> Fixed GPU tutorial code

docs/source/tutorial/gpu.rst
=> Fixed cupy document link

docs/source/tutorial/function.rst
This PR adds a section explaining how to write a function that supports train/test mode.
=> Add a section about train flag to tutorial

tests/chainer_tests/test_init_docstring.py
I found that pkgutil's importer causes an error. I instead use importlib, and it fixes the problem.
=> Use importlib

chainer/configuration.py
I fixed format of show method to pass its test.
=> Fix config.show format

chainer/configuration.py, tests/chainer_tests/test_configuration.py
This PR improves the printing format of config.show (it was once merged to v2 without tests and was then reverted. This PR updates tests as well).
=> Improve the format of config.show

chainer/functions/activation/crelu.py, chainer/functions/activation/elu.py, chainer/functions/activation/relu.py, cupy/core/core.pyx
I fixed docstrings to pass doctest.
=> Fix doctest result

chainer/functions/noise/gaussian.py, tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
To support zero-dim arrays, I added `force_array`.
=> Fix gaussian to support zero-dim array

docs/source/reference/core/configuration.rst
=> Fix docstring to pass doctest

examples/seq2seq/europal.py, examples/seq2seq/seq2seq.py
This is PR to modify seq2seq example.
I added or fixed
- strings normalization for apostrophes
- tokenization
- dividing loss by the size of minibatch
- using Adam in spite of Adagrad, with changing learning rate
- availability of gpus except for the default one (gpu=0)
in addition to them, I did some minor modifications including
- observing more (and maybe better) examples of inference decoding while training
- observing perplexity
- changing spans for calculating BLEU, due to its calculation time
=> Fix seq2seq example

chainer/configuration.py
I fixed document of configuration to skip doctest.
=> Skip configuration doctest

chainer/functions/caffe/__init__.py, setup.py
=> Remove chainer.functions.caffe.CaffeFunction

chainer/utils/conv_nd_kernel.py, chainer/utils/type_check.py, examples/cifar/train_cifar.py, examples/dcgan/train_dcgan.py, examples/mnist/train_mnist.py, examples/sentiment/train_sentiment.py, examples/vae/train_vae.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py, tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py, tests/chainer_tests/functions_tests/loss_tests/test_hinge.py, tests/chainer_tests/functions_tests/math_tests/test_bias.py, tests/chainer_tests/functions_tests/math_tests/test_ceil.py, tests/chainer_tests/functions_tests/math_tests/test_exponential_m1.py, tests/chainer_tests/functions_tests/math_tests/test_floor.py, tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py, tests/chainer_tests/functions_tests/math_tests/test_matmul.py, tests/chainer_tests/functions_tests/math_tests/test_maximum.py, tests/chainer_tests/functions_tests/math_tests/test_minimum.py, tests/chainer_tests/functions_tests/math_tests/test_scale.py, tests/chainer_tests/functions_tests/math_tests/test_sum.py, tests/chainer_tests/functions_tests/noise_tests/test_zoneout.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py, tests/chainer_tests/functions_tests/pooling_tests/test_upsampling_2d.py, tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py, tests/chainer_tests/links_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_zoneoutlstm.py, tests/chainer_tests/links_tests/model_tests/test_vision.py
=> follow autopep8

tests/cupy_tests/prof_tests/test_range.py
=> Fix range test

tests/chainer_tests/functions_tests/array_tests/test_pad.py
I fixed pad test to stabilize it.
=> Fix pad test

examples/dcgan/net.py, examples/dcgan/updater.py, examples/imagenet/nin.py, examples/word2vec/train_word2vec.py
`Variable.shape` and `Variable.__len__` are recommended in v2 because an argument which a Link received may be ndarray.
=> Use __len__ and shape directly

chainer/training/extensions/__init__.py, chainer/training/extensions/micro_average.py
I made an extension which calculates micro-average of precision.
=> Micro average precision

tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
`test_mean_absolute_error` sometimes fails. I changed random value to prevent error.
=> Change random value to prevent test error

tests/chainer_tests/functions_tests/math_tests/test_fmod.py
fmod test is unstable. I fixed test condition.
=> Change test condition to stabilize fmod test

examples/mnist/train_mnist.py
I changed mnist example to specify frequency of taking a snapshot, because previous scripts had mismatch between comment and script.
=> Add snapshot frequency option to mnist example

chainer/function.py, chainer/function_hooks/debug_print.py
This is PR for fixing doctest of function_hooks.
=> fix doctest of function_hooks

cupy/core/core.pyx, cupy/core/elementwise.pxi
This PR improves Windows support to build Chainer on Windows environments, following @kmatsuura 's change.
=> Improve Windows support.

chainer/variable.py
=> Stop creating cuda.Device in Variable.backward when cupy is not used

.travis.yml
=> Remove rtd build test on osx

chainer/functions/activation/maxout.py
=> Improve docs of maxout

cupy/testing/condition.py, tests/cupy_tests/testing_tests/test_condition.py
=> Fix repeat in cupy

chainer/functions/array/split_axis.py, tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
=> Check validity of sections argument in splix_axis

chainer/optimizer.py, tests/chainer_tests/test_optimizer.py
=> Support cleargrad in optimizer hook

.travis.yml
Please see https://github.com/pfnet/chainer-test/pull/209
=> Suppress feature warnings in travis

chainer/dataset/download.py, tests/chainer_tests/dataset_tests/test_download.py
=> Write a test of download module

tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py, tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_nd.py, tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py, tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py
=> Reduce test time

chainer/functions/activation/leaky_relu.py, chainer/functions/activation/relu.py
=> Improve docs of leaky_relu and relu

tests/chainer_tests/training_tests/extensions_tests/test_plot_report.py
No argument is required for a static method.
=> Fix PlotReport.available and write test

chainer/functions/__init__.py, chainer/functions/math/average.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_average.py
I implemented weighted average function. It is compatible with `numpy.average`.
We can reproduce a reduced version of loss function with this function and an elementwise-loss function.
=> Average function

chainer/functions/activation/hard_sigmoid.py, chainer/functions/activation/sigmoid.py
- functions/activation/sigmoid
- functions/activation/hard_sigmoid
=> Improve docs of sigmoid, hard sigmoid

chainer_setup_build.py, cupy/cuda/cupy_cuda.h, install/build.py
This PR improves NVTX support for Windows environments, following @kmatsuura 's change.
=> Improve Windows NVTX support

chainer/functions/activation/softplus.py
- functions/activation/softplus
=> Improve docs of softplus

chainer/links/__init__.py, chainer/links/model/vision/resnet.py, tests/chainer_tests/links_tests/model_tests/test_vision.py
This PR just adds ResNet101 model and ResNet152 model under links.modes.vision besides ResNet50.
=> Add ResNet-101 and ResNet-152 to links.modes.vision

tests/chainer_tests/links_tests/model_tests/test_vision.py
=> Fix attribute order for test

chainer/functions/loss/ctc.py, tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
Fix #2292 
I added the case of  l'_s = b or l'_{s-2} = l'_s. in creation of recurrence relation.
=> CTC repeat char

docs/source/reference/links.rst
Related to #2447. This small PR adds ResNet101Layers and ResNet152Layers to the reference.
=> Add ResNetLayers to docs

chainer/function_hooks/__init__.py, chainer/function_hooks/cuda_profile.py, cupy/cuda/__init__.py, cupy/prof/time_range.py, tests/chainer_tests/function_hooks_tests/test_cuda_profile.py, tests/cupy_tests/cuda_tests/test_nvtx.py, tests/cupy_tests/prof_tests/test_range.py
=> Make a hook to mark forward and backward computation for CUDA profiler

cupy/cuda/__init__.py, cupy/prof/time_range.py, tests/cupy_tests/cuda_tests/test_nvtx.py, tests/cupy_tests/prof_tests/test_range.py
NVTX is not always available. I forbid to import nvtx directly.
See #2210
=> Check if nvtx exists

chainer/functions/connection/n_step_lstm.py
=> Check batch size in NStepLSTM

tests/cupy_tests/random_tests/test_generator.py
`test_goodness_of_fit` sometimes fails. I inserted `retry`.
=> Insert retry to choice test

chainer/links/connection/gru.py
`linear_interpolate` method is slightly more efficient.
=> GRU linear interpolate

chainer/__init__.py, chainer/initializers/__init__.py, chainer/links/connection/bilinear.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_nd.py, chainer/links/connection/dilated_convolution_2d.py, chainer/links/connection/embed_id.py, chainer/links/connection/lstm.py, chainer/links/normalization/batch_normalization.py, chainer/variable.py
=> Remove init_weight

chainer/functions/array/cast.py
=> Improve docs of cast

chainer/functions/__init__.py, chainer/functions/array/pad_sequence.py, tests/chainer_tests/functions_tests/array_tests/test_pad_sequence.py
I made a method which gets different sizes of sequences, fills with padding values and concats them.
=> Pad sequence

chainer/functions/__init__.py, chainer/functions/array/im2col.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_im2col.py
This PR adds im2col that acts on chainer.Variable.
=> Add im2col function for Chainer Variable

install/build.py
=> Add maximum supported version condition for cudnn

cupy/linalg/__init__.py, cupy/linalg/decomposition.py, docs/source/cupy-reference/linalg.rst, tests/cupy_tests/linalg_tests/test_decomposition.py
Merge after #2271.
This PR aims to add the QR decomposition to cupy.
Note: this PR is based on #1402.
=> Add QR decomposition to cupy

examples/seq2seq/europal.py, examples/seq2seq/seq2seq.py
Improvements on seq2seq.py example:
* added --input option
* some minor changes
=> A few improvements on seq2seq.py code

chainer/functions/connection/convolution_2d.py
- functions/connection/convolution_2d
Doctest result is here.
```
Document: reference/functions
-----------------------------
1 items passed all tests:
106 tests in default
106 tests in 1 items.
106 passed and 0 failed.
Test passed.
```
=> Improve docs of convolution_2d

chainer/functions/loss/vae.py, tests/chainer_tests/functions_tests/loss_tests/test_vae.py
This PR add reduce option to `F.bernoulli_nll` following the design discussed in #2325 with the same spirit of #2519
=> Add reduce option to beroulli_nll

chainer/functions/__init__.py, chainer/functions/math/average.py, chainer/functions/math/sum.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_average.py, tests/chainer_tests/functions_tests/math_tests/test_sum.py
I made keepdims argument for average function.
Merge #2507  before this PR.
=> Average keepdims

chainer/functions/math/sum.py, tests/chainer_tests/functions_tests/math_tests/test_sum.py
I implemented `keepdims` argument for `cupy.sum`. I also cleaned up the test for the method because it is complicated.
=> Sum keepdims

docs/source/conf.py
=> Add special members to the document

tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
I added retry condition to unstable test.
=> Retry unstable test

README.md
Add invitation form link for slack
Add inner link for example
=> Add Information in README

chainer/link.py
This PR fixes a grammatical error.
=> Fix a mistake in grammar

chainer/links/__init__.py, chainer/links/model/vision/googlenet.py, docs/source/reference/links.rst, tests/chainer_tests/links_tests/model_tests/test_vision.py
I added pretrained GoogLeNet link to chainer.links.model.vision .
=> Add GoogLeNet link

chainer/functions/loss/hinge.py
This PR fixes the document of `F.hinge_loss`. Mainly, inconsistency between function's arguments and mathematical definition in the document and several markups.
=> Improve the document of Hinge loss

chainer/functions/loss/crf1d.py, chainer/links/loss/crf1d.py, tests/chainer_tests/functions_tests/loss_tests/test_crf1d.py
I added reduce argument to crf1d.
related to #2558
=> Crf1d reduce

chainer/functions/loss/huber_loss.py, tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
This PR add `reduce` option to `F.huber_loss`. Rel.  #2558
=> Add reduce option to huber loss
