chainer/chainer

- index.html
When I `pip install scikit-learn` and tried to run chainer (looking at this index page,) chainer complained for scipy missing. It seems like scipy is not installed as a dependency of scikit-learn.
It would be kind for future readers, to mention the dependency on scipy here.
> Chainer also needs scipy

- docs/source/tutorial/recurrentnet.rst
The `word_data` is not defined and the `cur_word` is never used, so is it a typo?
> Fix a typo in the recurrent network tutorial

- docs/source/tutorial/recurrentnet.rst
I think `EmbedID` function should take a vocabulary size as first argument.
> Fix a bug about EmbedID() in the recurrent network tutorial

- examples/sentiment/train_sentiment.py
When GPU is used, `y.data` is `chainer.cuda.gpuarray.GPUArray`.
So, an error is occurred: `AttributeError: 'GPUArray' object has no attribute 'argmax'`
This modification is somewhat ugly...
Is there more sophisticated way?
> Fix a bug in sentiment analysis example when using GPU

- chainer/functions/batch_normalization.py
This is speedup of batch normalization.
> speeding up batch normalization

- tests/attr.py
- tests/functions_tests/test_accuracy.py
- tests/functions_tests/test_basic_math.py
- tests/functions_tests/test_batch_normalization.py
- tests/functions_tests/test_concat.py
- tests/functions_tests/test_convolution_2d.py
- tests/functions_tests/test_embed_id.py
- tests/functions_tests/test_hierarchical_softmax.py
- tests/functions_tests/test_leaky_relu.py
- tests/functions_tests/test_linear.py
- tests/functions_tests/test_local_response_normalization.py
- tests/functions_tests/test_lstm.py
- tests/functions_tests/test_mean_squared_error.py
- tests/functions_tests/test_parameter.py
- tests/functions_tests/test_pooling_2d.py
- tests/functions_tests/test_prelu.py
- tests/functions_tests/test_relu.py
- tests/functions_tests/test_reshape.py
- tests/functions_tests/test_sigmoid.py
- tests/functions_tests/test_softmax.py
- tests/functions_tests/test_softmax_cross_entropy.py
- tests/functions_tests/test_sum.py
- tests/functions_tests/test_tanh.py
- tests/test_function_set.py
This PR supports CPU-only tests and without cuDNN tests.
It uses Attribute selector plugin in nose.
http://nose.readthedocs.org/en/latest/plugins/attrib.html
-  `nosetests -a '!gpu'` : Run CPU-only tests.
-  `nosetests -a '!cudnn'` : Run without cuDNN tests.
> Support CPU-only tests #4 and without cuDNN tests.

- README.md
- scripts/chainer-cuda-requirements
- setup_cuda_deps.py
I added setup.py script for dependent libraries. Users can install dependent libraries with `setup_cuda_deps.py`. They don't need to use `chainer-cuda-requirements`.
This RP also fixes #40
> setup script for dependencies

- chainer/optimizers/ada_delta.py
Fourth argument of `AdaDelta.update_on_gpu`  must be `state`, but was `msg`, which is first component of state. This PR fixes it.
> Fix argument of AdaDelta.update_on_gpu

- tests/optimizers_tests/test_ada_delta.py
- tests/optimizers_tests/test_ada_grad.py
- tests/optimizers_tests/test_adam.py
- tests/optimizers_tests/test_momentum_sgd.py
- tests/optimizers_tests/test_rmsprop.py
- tests/optimizers_tests/test_sgd.py
Because functionality tests of optimizer behave stochastically, CI occasionally fails because of insufficient accuracy. To reduce undesired failure, threshold of accuracy is lessen to 0.7.
> Loosen accuracy threshold of functionality test of optimizers

- chainer/optimizer.py
When multi gpu FunctionSet is set in optimizer, I fail in optimzer#clip_grads()
```python
from chainer import FunctionSet, cuda
from chainer.optimizers import SGD
cuda.init(0)
model = FunctionSet(l1=F.Linear(4, 4).to_gpu(0), l2=F.Linear(4, 4).to_gpu(1))
optimizer = SGD()
optimizer.setup(model.collect_parameters())
optimizer.clip_grads(5)
#=>raise LogicError: cuMemcpyDtoH failed: an illegal memory access was encountered
```
> fix cannot call clip_grads() at multi_gpu

- examples/mnist/download_convert.py
- examples/mnist/train_mnist.py
- examples/mnist/train_mnist_model_parallel.py
Removed scikit-learn.datasets.fetch_mldata so that users can run this example without installing scipy and scikit-learn. 
The MNIST dataset is now downloaded from the original [web](http://yann.lecun.com/exdb/mnist/), converted into a dictionary of numpy.ndarray, and serialized into a local file with pickle.
This PR fixes #87.
> Remove dependency on scikit-learn from MNIST example

- chainer/functions/accuracy.py
Type of `chainer.functions.accuracy().data` using cpu is numpy.float32.
This will cause different behavior when using CPU or GPU ·
```python
x = Variable( numpy.array( [ [0. , 1.], [0., 1.,] ], dtype=numpy.float32 ) )
t = Variable( numpy.array( [ 1, 1], dtype=numpy.float32 ) )
r = F.accuracy(x, t)
print type(r.data) #=> numpy.float32
r1 = r + r # => ArgumentError: @cuda.py line:224     return drv.Device(arg)
x = Variable( cuda.to_gpu( numpy.array( [ [0. , 1.], [0., 1.,] ], dtype=numpy.float32 ) ) )
t = Variable( cuda.to_gpu( numpy.array( [1, 1], dtype=numpy.int32 ) ) ) 
r =  F.accuracy(x, t)
print type(r.data) #=>  <class 'pycuda.gpuarray.GPUArray'>
r1 = r + r
print r1.data #=> 2.0
```
> Fix return type of chainer.functions.Accuracy#forward_cpp()

- chainer/functions/inception.py
I fixed the design of Inception module. The document says that it inserts the full computational graph of Inception on top of the input variables, while the previous implementation does not implement as this and hide the computational graph. It caused the volatile flag disabled inside of the Inception module. This change fixes this inconsistency.
> Fix Inception module to consistent with the document

- chainer/optimizers/__init__.py
- chainer/optimizers/rmsprop_graves.py
- tests/optimizers_tests/test_optimizers_by_linear_model.py
This PR adds a new optimizer, RMSpropGraves, which is an RMSprop variation proposed by Alex Graves in http://arxiv.org/abs/1308.0850 and used in some papers from Google DeepMind including http://www.nature.com/nature/journal/v518/n7540/abs/nature14236.html?lang=en and http://arxiv.org/abs/1410.5401.
(This PR is the same as #48 except for adding unit tests)
> Alex Graves's RMSprop (#48 reopened)

- chainer/functions/lstm.py
Added some explanations to ``functions.lstm`` which I felt little difficult to use.
Rendered output:
> DOC: Add example to lstm doc

- chainer/functions/concat.py
- chainer/functions/embed_id.py
- chainer/functions/linear.py
- chainer/utils/type_check.py
- tests/utils_tests/test_type_check.py
I noticed that we need not restrict only int to check values.
We can check any types of variables including str and float with this patch.
for example:
```
expect(Variable('AAA', x) + 'BBB' == 'AAABBB')
```
works.
> Remove Int from type_check

- chainer/functions/embed_id.py
- chainer/functions/linear.py
- chainer/functions/lstm.py
- chainer/functions/softmax.py
- chainer/functions/softmax_cross_entropy.py
- tests/functions_tests/test_linear.py
I fixed existing type check of functions. It includes following changes:
1. Split type_check.expect calls for ndim checking and shape checking, since, if the ndim is too small, the corresponding shape accessing is failed outside of the type checking utility, which ends up with unfriendly messages.
2. I fixed the type specification of Linear function, which must accept arrays with more than two dimensions. It enables us to directly input to Linear function an array with spatial dimensions.
> Fix type check

- chainer/computational_graph.py
- chainer/function.py
- tests/test_function.py
This PR changes label of Function nodes computational graphs.
Take `Identity` function for example, this PR change from "<class 'chainer.functions.identity.Identity'>" to 'Identity'
This change simplifies the visualization of computational graphs.
* Example : Inception module(3a) of GoogLeNet
**Before**
**After**
> Simplify the output of Function.label

- chainer/functions/__init__.py
- chainer/functions/matmul.py
- tests/functions_tests/test_matmul.py
This PR adds two functions named ```matmul``` and ```batch_matmul```, both of which do matrix multiplication of two ```Variable```s representing matrices. They also can be used to compute vector inner products.
```matmul``` accepts two ```Variable```s that are 1-D or 2-D arrays. 1-D arrays are treated as column vectors while 2-D arrays are as matrices. Its output is always a 2-D array representing a matrix.
```batch_matmul``` accepts two ```Variable```s that are 2-D or 3-D arrays. 2-D arrays are treated as batches of column vectors while 3-D arrays are as batches of matrices. Its output is always a 3-D array representing a batch of matrices.
Both accept Boolean options ```transa``` and ```transb``` for transposing corresponding argument matrices.
This PR may solve #8.
> Matrix multiplication (or dot product)

- chainer/computational_graph.py
- chainer/functions/inceptionbn.py
This PR applies almost same changes as #103 to `InceptionBN` module.
We execute forward operation of all function in `inceptionBN`to enable `volatile` option of all functions in `inceptionBN` module.
Note that `examples/imagenet/train_imagenet.py` does not work unless changes of #124 are applied. So I think we should merge #124 first and merge this PR after confirming that examples run properly.
> Fix InceptionBN to execute forward of all functions in the module

- chainer/functions/pooling_2d.py
- tests/functions_tests/test_pooling_2d.py
This PR fixes #120. The bug seems to be caused by the bug (or specification?) of numpy.choose https://github.com/numpy/numpy/issues/3259. I used this function to get maximum elements using indices given by argmax. It seems that numpy.choose does not accept an array with the first axis of length more than 30, which makes the max_pooling_2d not work on the window size more than 30 (e.g. if kh = kw = 6, then the window size is kh * kw = 36, which exceeds this threshold).
In order to avoid this bug, I changed the forward implementation to directly call numpy.max instead of numpy.choose. It makes the code a bit redundant, though it runs correctly with large windows.
> Fix max_pooling_2d on CPU with large window size (fix #120)

- chainer/functions/embed_id.py
- chainer/functions/linear.py
- chainer/functions/lstm.py
- chainer/functions/softmax.py
- chainer/functions/softmax_cross_entropy.py
- chainer/utils/type_check.py
- tests/functions_tests/test_linear.py
- tests/utils_tests/test_type_check.py
I implemented `GetAttr`, `GetItem`, and `Call` classes which are sub-classes of `Expr`. These classes evluate `__getattr__`, `__getitem__` and `__call__` in `expr`. And old special classes like `Shape` are replaced with combinations of these classes.
For example this code is valid:
```
>>> s = Constant('xyz')
>>> s[1].__len__().eval()
1
```
In this situation, first `Call(GetAttr(GetItem(Constant(...), 1), '__len__'), ())` is created, and then it is evaluated.
fix #131
> Support lazy evaluation for member access, item access and function call

- README.md
- cuda_deps/setup.py
We require scikits.cuda 0.5.0b2 to support Py3. It seems some of recent updates also depend on scikits.cuda 0.5.0b2 (e.g. #116).
> Update scikits.cuda version

- chainer/testing/condition.py
- tests/functions_tests/test_accuracy.py
- tests/functions_tests/test_basic_math.py
- tests/functions_tests/test_batch_normalization.py
- tests/functions_tests/test_concat.py
- tests/functions_tests/test_convolution_2d.py
- tests/functions_tests/test_embed_id.py
- tests/functions_tests/test_hierarchical_softmax.py
- tests/functions_tests/test_leaky_relu.py
- tests/functions_tests/test_linear.py
- tests/functions_tests/test_local_response_normalization.py
- tests/functions_tests/test_lstm.py
- tests/functions_tests/test_mean_squared_error.py
- tests/functions_tests/test_negative_sampling.py
- tests/functions_tests/test_pooling_2d.py
- tests/functions_tests/test_prelu.py
- tests/functions_tests/test_relu.py
- tests/functions_tests/test_sigmoid.py
- tests/functions_tests/test_sigmoid_cross_entropy.py
- tests/functions_tests/test_softmax.py
- tests/functions_tests/test_softmax_cross_entropy.py
- tests/functions_tests/test_sum.py
- tests/functions_tests/test_tanh.py
- tests/optimizers_tests/test_optimizers_by_linear_model.py
- tests/testing_tests/test_condition.py
This PR fixes #85 .
This PR implements decorators for test cases that make them run multiple times.
Decorators are as follows
* repeat_with_success_at_least(n, m) : Pass the test case if it succeeded m times among n trials.
* retry(n) : Pass the test case if it succeeded at least once among n trials.
* repeat(n) : Pass the test case if it succeeded all n trials.
> Add test decorators that make test cases run multiple times

- chainer/computational_graph.py
- tests/test_computational_graph.py
Currently, `ComputationalGraph` is essentially a list of edges. So if we run `build_computational_graph` with variables part of which is unchained, the unchained variables are missing from the resulting computational graph. Further, if all of variables are unchained, the graph is empty set and no graph is plotted. This specification is not intuitive. 
This PR adds nodes to computational graph so that such isolated variables are restored.
> Add nodes to computational graph

- tests/functions_tests/test_concat.py
- tests/functions_tests/test_hierarchical_softmax.py
- tests/functions_tests/test_matmul.py
- tests/functions_tests/test_nonparameterized_convolution_2d.py
- tests/functions_tests/test_nonparameterized_linear.py
- tests/functions_tests/test_split_axis.py
This PR adds `condition.retry` decorator to following functions.
* `TestBinaryHierarchicalSoftmax.test_sum`
* All of numerical test fixtures of `matmul`, non-parameterized `convolution_2d`, non-parameterized `linear` and `split_axis`.
> Add condition.retry decorator to undecorated numerical tests

- examples/ptb/train_ptb.py
It might have been working without problems for this example data, but
technically speaking, by omitting dtype in the zeros() call the grad
could become too small beyond float32 precision.  As a result, it would
stop updating function parameters if you run it in GPU, as the grad
values just vanish.
> Add missing explicit dtype to accum los variable.

- chainer/functions/basic_math.py
- tests/functions_tests/test_basic_math.py
Check and cast all constants that is calculated with `Variable`.
fix #139
> Cast constant value in basic_math

- examples/imagenet/README.md
- examples/modelzoo/README.md
I fixed `README.md` in example.
> Add information that an external library is required to use Pillow

- chainer/testing/condition.py
- tests/testing_tests/test_condition.py
Simply I stored `failures` information of a result and show the first one.
Fix #150
> Show the first error message in `repeat_with_success_at_least`

- README.md
- chainer/cuda.py
- cuda_deps/setup.py
fix #196 
After this PR, we will release `chainer-cuda-deps 1.1.0.1`, and then fix all import in chainer.
> Fix dependency to scikit-cuda

- chainer/utils/type_check.py
- tests/utils_tests/test_type_check.py
When we evaluate a list of `Expr`s, type check system doesn't evaluate each value in the list. It causes confusing error.
I fixed this behavior to evaluate values in a given list.
> Evaluate values in lists and ruples recursively

- chainer/functions/sigmoid_cross_entropy.py
This small PR fixes SigmoidCrossEntropy in order to preserve a dtype to float32
(Sorry I noticed that a current implementation converts gx.dtype in backward_cpu() to float64)
> Fix SigmoidCrossEntropy to preserve numpy.float32

- chainer/functions/basic_math.py
Related to #123 
It is worth discussion whether we admit broadcast in binary operators in `basic_math` (i.e. shapes of first and second argument do not match, but their data can be computed by means of broadcast of numpy
). For now, we decided not to admit broadcast because in order to admit broadcast, we must fix backward of each operators to maintain consistency of forward and backward.
Binary operators' support of broadcast is issued as #228 .
> Add check_type_forward to binary operators in basic_math

- chainer/testing/condition.py
The issue in note is resolved by PR #179. So it does reflects the current implementation.
> Remove obsolete note in _repeat_with_success_at_least

- chainer/functions/split_axis.py
- tests/functions_tests/test_split_axis.py
`list` is illegal for `shape` of `GPUArray`. Instead use `tuple`.
> Use tuple for shape in split_axis

- examples/word2vec/README.md
- examples/word2vec/search.py
- examples/word2vec/train_word2vec.py
I implemented word2vec example including skip-gram architecture and continuous-bow architecture with HSM and negative sampling.
Note that this implementation is slower than the original even when you use GPU.
Please review this PR after #264
> Word2vec example

- chainer/functions/__init__.py
- chainer/functions/basic_math.py
- docs/source/reference/functions.rst
- tests/functions_tests/test_basic_math.py
This PR adds sin and cos functions to basic math. I implemented them for working with complex number operations, since currently chainer only supports float32. Implementation is a straightforward adaptation of `Exp` that's already implemented in `basic_math.py`. Tests are also going to be easy to translate if there's interest in this feature.
> Added sin and cos to basic_math

- chainer/functions/softmax.py
- chainer/functions/softmax_cross_entropy.py
- tests/functions_tests/test_softmax.py
- tests/functions_tests/test_softmax_cross_entropy.py
This PR extends an existing Softmax function and a SoftmaxCrossEntropy function to support replicated softmax units.
Neural Network models that output multiple discrete values have been frequently used in many fields such as NLP, CV, and audio recognition.
While caffe already supports replicated softmax layer, the current implementation of chainer does not support the replicated softmax units (i.e., SoftmaxFunction only accepts a two dimensional input array).
In this PR, if we pass d (d>2) dimensional array to the SoftmaxFunction, it regards the remaining axis as the replicated units, and computes the replicated softmax.
Please note that currently I assume the second axis as a channel and the remaining axis as replicated units. The softmax layer in caffe already supports the ``axis`` …
> Extend a softmax function and the loss layer to support replicated softmax units

- chainer/functions/__init__.py
- chainer/functions/pooling_2d.py
- docs/source/reference/functions.rst
- tests/functions_tests/test_pooling_2d.py
This PR adds a non-parameterized function which performs Spatial Pyramid Pooling (SPP). This function enables a network to accept input images of an arbitrary shape/size and generate a fixed-length feature vector regardless of the shape/size of feature maps in the next lower layer. The paper linked below shows that a network with SPP (SPP-net) boosts the accuracy of a variety of CNN for object recognition.
I tested `spatial_pyramid_pooling_2d` function as a pooling layer by replacing the last `max_pooling_2d` layer in LeNet architecture with SPP. I trained the network on MNIST dataset, and got the 99.9% accuracy. So I think it works fine.
Please see details about SPP in the paper:
"Spatial Pyramid Pooling in Deep Convolutional Networks for Visual Recognition" …
> add spatial pyramid pooling 2d function

- index.html
Master branch is sometimes incompatible to the latest release. We recommend to download the latest source instead.
fix #147
> Fix download method of examples

- tests/test_gradient_check.py
In python3 map returns iterator, which causes failure in unit tests of numerical_grad. This PR fixes this failure.
> Fix NumericalGradientTest that fails in python3

- chainer/function.py
- chainer/functions/batch_normalization.py
- chainer/functions/concat.py
- chainer/functions/convolution_2d.py
- chainer/functions/copy.py
- chainer/functions/cross_covariance.py
- chainer/functions/embed_id.py
- chainer/functions/gaussian.py
- chainer/functions/hierarchical_softmax.py
- chainer/functions/linear.py
- chainer/functions/negative_sampling.py
- chainer/functions/reshape.py
- chainer/functions/softmax.py
- chainer/functions/softmax_cross_entropy.py
- chainer/functions/softplus.py
- chainer/variable.py
- tests/functions_tests/test_dropout.py
As discussed in #209, `check_type_backward` is no longer needed. This PR removes this method and codes that relevant to it.
This PR fixes #209
> Remove check_type_backward and its relevants

- chainer/utils/type_check.py
Typical usage (type check of `Reshape.forward` where size of input shape must equal to that of self.shape)
```
def check_type_forward(self, in_types):
type_check.expect(
in_types.size() == 1,
type_check.prod(in_types[0].shape) ==
type_check.prod(self.shape)
)
```
Related to #203
> Add type_check.prod

- chainer/function.py
- chainer/functions/parameter.py
- tests/functions_tests/test_parameter.py
This PR fixes #259.
As discussed in this issue, we add `volatile` option to `Parameter.__call__` as an keyword argument.
If volatile option is omitted, this function behaves as though all inputs had `False` volatile values.
> Add volatile option to Parameter.__call__

- chainer/function_set.py
This very simple PR lets you do:
```python
>>> model = FunctionSet(l1=F.Linear(100, 100), l2=F.Linear(100, 100))
>>> l1 = model['l1']
```
I've been seeing lots of other folks doing `getattr(model, 'l1')` -- like [here](http://nbviewer.ipython.org/gist/duschendestroyer/a41fcab5f7f9ffa45387), so this is likely a better way to the same end.
> Enhancement: Added getitem to FunctionSet

- chainer/functions/basic_math.py
- tests/functions_tests/test_basic_math.py
The objective of this fix is basically same as d7836e .
Some unary operators in `basic_math` is implemented by explicitly writing kernel code. In that case, dtypes of arguments are restricted to float32. This PR imposes this restriction to `check_type_forward` of the functions.
Related to #219
> Restrict dtype of arguments in some of unary operators in basic_math

- chainer/optimizer.py
It looks to me simply wrong to copy the src variable to src device.  In fact, I bumped into "invalid memory access" error when I tried to accumulate grads between multiple GPUs.
> Fix wrong device destination in optimizer.accumulate_grads().

- cupy/cudnn.py
Fix #339. It actually just makes `cupy.cudnn` not importable if cuDNN is not available.
> Make cupy.cudnn importable only if cuDNN is available

- tests/chainer_tests/functions_tests/test_clipped_relu.py
- tests/chainer_tests/functions_tests/test_leaky_relu.py
- tests/chainer_tests/functions_tests/test_prelu.py
- tests/chainer_tests/functions_tests/test_relu.py
Unit test for `crelu` sometimes fails when a random value is around zero.
> Avoid values around zero

- chainer/functions/convolution_2d.py
- tests/chainer_tests/functions_tests/test_convolution_2d.py
When CuDNN is not used, `Convolution2D.backward_gpu` uses `cuda.linalg`, which is no longer available after CuPy is introduced. This PR removes dependency on `cuda.linalg.dot` and `cuda.linalg.add_dot` and uses `cuda.cupy.dot` instead.
> Fix Convolution2D.backward_gpu so that it does not use cuda.linalg

- README.md
The file mentioned at README
```
python cuda_deps/setup.py install
```
seems to have been vanished.
Would you please update the paragraph and let us, the users, know how to  install the latest cuda dependencies?
> Update cuda dependency paragraph in README

- chainer/functions/basic_math.py
I found a minor mistake in error message of `_check_constant_type` function in `basic_math`
> Fix error message of _check_constant_type

- README.md
- chainer/functions/clipped_relu.py
- cupy/carray.cuh
- cupy/carray.py
- cupy/cindexer.py
- cupy/cuda/compiler.py
- cupy/cuda/cublas.py
- cupy/cuda/cudnn.py
- cupy/cuda/curand.py
- cupy/cuda/driver.py
- cupy/cuda/internal.py
- cupy/cuda/runtime.py
- setup.py
This PR add partial windows support.
- Use filelock package instead of fcntl.
- Do not use zero sized array.
I tested that the example of mnist can be run in the following environments.
- WIndows7
- CUDA 7.0
- Python 2.7.10 |Anaconda 2.3.0 (64-bit)|
However, some test cases is not completed successfully.
> Add partial Windows support

- cupy/cuda/device.py
Device switching does not work. This change fixes it.
(This bug is found by the investigation for the forum report by Amit. Thank you!)
> Fix device switching by "with" statement

- chainer/optimizer.py
PyCUDA-related codes remained in `Optimizer.accumulate_grads`. This PR removes them.
> Fix Optimizer.accumulate_grads

- cupy/elementwise.py
Support for argument of `long` on Python2.
> Support for argument of 'long'

- chainer/function_set.py
It's about #381 .
To avoid error when self.\__dict\__ contains something not function.
> Added typecheck where self.__dict__ is used.

- cupy/cuda/curand.py
This PR fixes arguments passed to `curandGenerateLogNormal`
> Fix argument of curandGenerateLogNormal

- chainer/functions/connection/convolution_2d.py
When the 'Convolution2D' function is migrated to GPU, it doesn't create the variable 'max_workspace_size' for the operation in cuDNN mode.
> fix to_gpu() of Convolution2D

- .coveragerc
I wrote `.coveragerc` file which is used in `coveralls` command to ignore `caffe_pb2.py` file.
> Write coveragerc to omit caffe_pb2 file from a coverage report

- chainer/functions/array/concat.py
- tests/chainer_tests/functions_tests/array_tests/test_concat.py
When backprop'ing `functions.array.concat` the following exception is raised if the array only contains one element (see the test)
```
File "/home/eddie/chainer/chainer/variable.py", line 180, in backward
gxs = func.backward(in_data, out_grad)
File "/home/eddie/chainer/chainer/functions/array/concat.py", line 42, in backward
return xp.split(gy[0], sizes, axis=self.axis)
File "/home/eddie/chainer/cupy/manipulation/split.py", line 96, in split
return array_split(ary, indices_or_sections, axis)
File "/home/eddie/chainer/cupy/manipulation/split.py", line 32, in array_split
ret.append(ary[skip + (slice(index, size),)])
UnboundLocalError: local variable 'index' referenced before assignment
```
This was caused by `functions.array.concat.backwards` passing in None to …
> bugfix: backprop now works when concatenating a single element array

- cupy/cuda/memory.py
This PR modified to `self.ptr` exists when the exception raised(e.g. CUDARuntimeError).
> Fix memory init

- tests/chainer_tests/functions_tests/connection_tests/test_bilinear.py
This PR implements unit tests for the problem on Bilinear reported in #398 (Thanks @cemoody! ).
> Add unittest for Bilinear where out_size equals to 1

- docs/source/cupy-reference/manipulation.rst
- docs/source/cupy-reference/overview.rst
cupy.expand_dims() is available in version 1.3.1 (#343), but missing in the docs.
> Fix cupy.expand_dims() is missing in the docs

- cupy/random/generator.py
Hi,
Current `RandomState.seed()` does not really reset all of random state.
Here is a small code to reproduce this issue:
```
from __future__ import print_function
from cupy.random import get_random_state, seed
from chainer import cuda
gpu = 0
device = cuda.get_device(gpu)
with device:
seed(0)
rs = get_random_state()
for _ in range(10):
r = rs.rand(1)
print(r)
print("====")
seed(0)
rs = get_random_state()
for _ in range(10):
r = rs.rand(1)
print(r)
```
The results are here (different values are generated even though seed value is same):
```
[ 0.56154916]
[ 0.5396353]
[ 0.74978529]
[ 0.50525623]
[ 0.94698888]
[ 0.66230074]
[ 0.60323748]
[ 0.12558134]
[ 0.51783317]
[ 0.9571602]
====
[ 0.49158581]
[ 0.3454503]
[ 0.48739564]
[ 0.73569951]
[ 0.94801935]
[ 0.42100349]
[ 0.61444364]
[ …
```
> set offset.

- cupy/cuda/memory.py
- tests/cupy_tests/test_ndarray_get.py
This PR implements unit tests for `cupy.get`.
This PR essentially fixes #430 because `cupy.asnumpy` is same as `cupy.get` get the source array is on the device.
> Unittest for cupy.get

- tests/cupy_tests/random_tests/test_generator.py
Some test fixtures in `RandomState`'s unit tests substitute objects with mocking ones. But they leave the mocks as they are and it does harm to other unit tests.
This PR fixes so that mocked objects are properly restored in teardown.
> Restore mocked objects in teardown of RandomState's unit tests

- chainer/testing/attr.py
- tests/chainer_tests/test_function_set.py
- tests/chainer_tests/test_optimizer.py
This PR implements multi-GPU tests for `optimizer.accumulate_grads` and `copy_parameters_from`
See #418
I test these methods preferentially because most of typical model-parallel training procedures will use these methods.
Since this PR includes same changes same as #436, please merge #436 before this PR.
> Multi-GPU tests for accumulate_grads and copy_parameters_from

- cupy/creation/from_data.py
- cupy/cuda/memory.py
- cupy/testing/__init__.py
- cupy/testing/attr.py
- tests/cupy_tests/creation_tests/test_from_data.py
- tests/cupy_tests/manipulation_tests/test_basic.py
- tests/cupy_tests/test_elementwise.py
This PR implements
* multi_gpu decorator for cupy
* unittests for `cupy.copy`, `cupy.copyto` and `cupy.elementwise.copy` including multi-GPU ones.
* fixes for #438 
* Contrary to what I commented there, I tried to support cross-device copy in non-UVA devices. But since I do not have such environment, I could not check the corresponding code.
> Fixes relating to cross-device array copy

- chainer/testing/attr.py
- tests/chainer_tests/functions_tests/array_tests/test_copy.py
This PR implements multi-gpu unit tests for `Function.Copy`.
See #418 
This PR also includes `multi_gpu(N)` decorator, which specifies that decorated test should be run in the environment with at least N GPUs.
e.g.
* Run only CPU tests
```
nosetests -A "gpu<1" tests/
nosetests -a '!gpu' tests/
```
* Run only single GPU tests
```
nosetests -a gpu=1 tests/
```
* Run only multiple GPU tests
```
nosetests -A "gpu>1" tests/
nosetests -A "gpu>=2" tests/
```
* Run CPU tests and single GPU tests
```
nosetests -A "gpu<=1" tests/
nosetests -A "gpu<2" tests/
```
See [nose references](http://nose.readthedocs.org/en/latest/plugins/attrib.html) for details.
> Multi-GPU tests for Function.Copy

- tests/cupy_tests/test_ndarray_elementwise_op.py
I wrote a test for int operators (and, or, xor, {l,r}shift) for `ndarray`.
fix #444
> Write test for int operators of ndarray

- tests/cupy_tests/random_tests/test_generator.py
`functon.func_name` is not available in Python 3. This PR change to use `__name__` instead of `func_name`
> Use function.__name__ instead of func_name to support Python3

- examples/mnist/train_mnist.py
Since `Splitter` is not available in `model` architecture, `graph.wo_split.dot` and `graph.dot` is exactly same DAG. So, we do not need to generate the former one.
> Do not generate graph.wo_split.dot

- cupy/manipulation/shape.py
- tests/cupy_tests/manipulation_tests/test_shape.py
Contiguity is wrong after cupy.reshape:
```python
a = cupy.arange(6).reshape(2, 3)
a.flags.f_contiguous  #=> 1
```
It causes incorrect results on successive computations on the reshaped array. This PR fixes this issue.
> Fix contiguity after reshape

- examples/imagenet/compute_mean.py
- examples/imagenet/train_imagenet.py
I added root option, that represents path to the root directory of image files. This option is require to simplify test code for examples.
This PR is related to #508
> Add root option to imagenet examples

- tests/cupy_tests/random_tests/test_generator.py
`CHAINER_SEED` is set but is not restored in the teardown of `TestGetRandomState2`. This PR fixes the problem.
> Restore chainer_seed in the teardown of TestGetRandomState2

- examples/imagenet/alex.py
- examples/imagenet/train_imagenet.py
AlexNet used in `imagenet` example is different from original one in that Local Response Normalization(LRN) layers are replaced with Batch Normalizations(BN) (so, the architecture name is `alexbn` rather than `alex`). The reason for this change is that LRN was not implemented at the time the example is made. This PR implements original AlexNet and adds it to `imagenet` example.
> Add AlexNet to Imagenet example

- chainer/testing/__init__.py
- chainer/testing/parameterized.py
- cupy/testing/__init__.py
- cupy/testing/parameterized.py
- tests/chainer_tests/testing_tests/test_parameterized.py
- tests/cupy_tests/testing_tests/test_parameterized.py
This PR implements `chainer.testing.product` and `cupy.testing.product`. Basic usage (and implementation itself) is same as that of `maflib.util.product` ([Link](https://pfi.github.io/maf/maflib.html#maflib.util.product)).
> Implement chainer.testing.product and , cupy.testing.product

- tests/cupy_tests/random_tests/test_generator.py
As the [Python document](https://docs.python.org/2.7/library/os.html#os.unsetenv) indicates, it is preferable to manipulate `os.environ` directly to remove environment variable instead of using `os.unsetenv`. Actually my environment does not have bash command `unsetenv` and `os.unsetenv` does not take effect.
> Directly manipulate os.environ to remove environment variable

- cupy/__init__.py
Numpy has np.min and np.max functions. It's true that np.min == np.amin and np.max == np.amax, so I added the same aliases to cupy.
> Add min and max alias for amin and amax, to mimick numpy.

- cupy/__init__.py
- cupy/logic/truth.py
- tests/cupy_tests/logic_tests/test_truth.py
This PR implements cupy.all and cupy.any. It also implements corresponding `ndarray`'s methods (`ndarray.all` and `ndarray.any`). 
This PR fixes #409.
> Implement cupy.all, cupy.ndarray.all, cupy.any and cupy.ndarray.any

- chainer/functions/normalization/batch_normalization.py
- cupy/statistics/meanvar.py
Speeding up from 1.6 to 1.8 times in the following test case .
It's tested in branch which PR #548 is merged.
before
0:00:00.312393 0:00:00.204991
0:00:00.321782 0:00:00.205670
after 
0:00:00.167545 0:00:00.124970
0:00:00.175646 0:00:00.125602
```python
import datetime
import chainer
def testbn(shape):
bn = F.BatchNormalization(shape[0])
bn.to_gpu()
x_org = chainer.Variable(chainer.cuda.zeros(shape), volatile=False)
x = x_org
t1 = datetime.datetime.now()
for i in range(200):
x = bn(x)
y = F.sum(x)
y.data.get()
t2 = datetime.datetime.now()
y.backward()
t3 = datetime.datetime.now()
print(t2 - t1, t3 - t2)
#for memory allocation
testbn((10, 10, 10))
testbn((100, 100, 100))
#for performance test
testbn((10, 10, 10))
testbn((100, 100, 100))
```
> Improve batch_normalization performance

- tests/chainer_tests/test_gradient_check.py
> Remove eps=0.1

- chainer/functions/array/split_axis.py
When `ndim == self.axis`, line 27 is not evaluated properly: https://github.com/pfnet/chainer/compare/fix-split-axis-typecheck?expand=1#diff-9e610d281c820d44c4a0cbf0ca6263fdL27
> Fix typecheck condition of split_axis

- chainer/serializers/hdf5.py
- setup.py
The h5py is reguired hdf5.h.
But, there is no way to install the hdf5.h on Read the Docs.
> Remove h5py from install_requires on Read the Docs.

- cupy/__init__.py
- tests/cupy_tests/manipulation_tests/test_transpose.py
```x.transpose(None)``` causes error because  ```cupy.ndarray.transpose``` receives variable-length argument list ```*axes``` and thus the ```None``` become ```(None,)```.
> Fix cupy.ndarray.transpose and add test

- docs/source/reference/functions.rst
This PR removes duplicated lines in docs. I think `Noise injecting functions` part should be deleted.
> Remove duplicated lines

- chainer/functions/array/transpose.py
- tests/chainer_tests/functions_tests/array_tests/test_transpose.py
transpose() causes error when argument “axes” is None because Transpose.\_\_init\_\_()  assumes that the “axes” is iterable.
I added a line to fix it (the default behavior of “axes” is to reverse the dimension of input x).
> Fix transpose() when called with no "axes"

- chainer/links/connection/convolution_2d.py
This PR fixes #657 
I decided not to fix the test code but change the implementation because there will be some cases where we want to change use_cudnn option after the instance is constructed.
> Change Convolution2D not to use _conv_arg but to hold its elememts directly

- README.md
Users need to set environment variables to build chainer with cudnn in the next version.
> Fix installation method for cudnn

- MANIFEST.in
pyx, pxd, pxi, and header files must be included in the dist.
> Add Cython files to the chainer package

- chainer_setup_build.py
`sudo` command breaks environment variables. I set default cuda path `/usr/local/cuda` for such case.
> Set default cuda path

- chainer/serializers/hdf5.py
h5py file open and load do not close / flush their buffers, causing resource leak and causes intermittent bugs depending on program behavior.
> Fix bug with unclosed resources in serializers

- cupy/cuda/compiler.py
`reraise` makes stack trace confusing. I replaced `reraise` with `raise` simply.
> Use raise instead of reraise

- chainer/variable.py
The test is failed if `self.data.shape` contains `long` type value.
> Fix label format

- chainer/utils/walker_alias.py
Escecially when calculation error is large, `ir` get a larget value than `il`.
So, the method access `threshold[ir]` before assigining `threshold[il]`. It causes an error.
> Check index to suppress invalid access

- chainer/functions/pooling/max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
I fixed arrays for test of spatial pyramid pooling to avoid unstable behavior. See also `test_max_pooling_2d`.
> Make test of spatial pyramid pooling stable

- cupy/testing/__init__.py
- cupy/testing/array.py
- tests/cupy_tests/testing_tests/test_array.py
Correct function name is `assert_array_almost_equal_nulp`. Corresponding NumPy method called is also incorrect and fixed.
> Fix function name of cupy.testing.assert_arrays_almost_equal_nulp

- cupy/testing/helper.py
`cupy.testing.shaped_arange` treat boolean as a special case because if it did not, all elements in the resulting array were `True`, which is useless as a testing array. `cupy.testing.shaped_reverse_arange` must handle boolean in the same way.
> Change cupy.testing.shaped_reverse_arange to treat boolean as a special case.

- chainer/functions/activation/clipped_relu.py
- chainer/functions/activation/leaky_relu.py
- chainer/functions/activation/prelu.py
- chainer/functions/connection/bilinear.py
- chainer/functions/connection/embed_id.py
- chainer/functions/connection/linear.py
- chainer/functions/loss/negative_sampling.py
- chainer/links/connection/deconvolution_2d.py
- chainer/links/connection/linear.py
- chainer/links/loss/hierarchical_softmax.py
- chainer/utils/walker_alias.py
In the document of [`F.linear`](http://docs.chainer.org/en/stable/reference/functions.html#chainer.functions.linear) and [`F.embed_id`](http://docs.chainer.org/en/stable/reference/functions.html#chainer.functions.embed_id), math expression `\times` and `\top` are not properly rendered. To fix them, I replaced `\t` with `\\t` at the first commit.
In principle, as [Math support in Sphinx](http://sphinx-doc.org/ext/math.html) says:
> Keep in mind that when you put math markup in Python docstrings read by autodoc, you either have to double all backslashes, or use Python raw strings (r"raw").
So I further replaced single-backslash in doncstrings with double-backslashes.
> Fix broken math expressions in reference

- chainer_setup_build.py
setuptools (or distutils?) hides stderr of subprocess. So, user cannot check error messages of cython.
fix #775
> Show stderr of subprocess

- chainer/functions/loss/sigmoid_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
I added ``ignore_label`` to ``sigmoid_cross_entropy`` as ``softmax_cross_entropy`` has.
When groundtruth label is -``1``, corresponding prediction is ignored while computing loss.
Added ``normalize`` option works same as ``softmax_cross_entropy``.
> Add ignore_label into sigmoid_cross_entropy

- chainer/functions/pooling/spatial_pyramid_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
Fix #787 
Lack of `type_check_forward` in `SpatialPyramidPooling2D` caused #787's error. So the main objective of this change is to introduce type check to SPP.
The drawback of this change is to restrict the input SPP 4D array with `float32`. But this restriction is acceptable because it is same as ones other pooling functions have.
> Make SPP a subclass of Pooling2D

- README.md
- cupy/core/core.pyx
- cupy/core/elementwise.pxi
- cupy/core/reduction.pxi
- cupy/creation/ranges.py
- tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
This is the main difference between numpy 1.9 and 1.10.
Fix #527
> Make casting argument in ufunc, and set its default value 'same_kind'

- chainer/links/__init__.py
- chainer/links/connection/gru.py
- docs/source/reference/links.rst
- tests/chainer_tests/links_tests/connection_tests/test_gru.py
Fix #789 
I propose to add several APIs to `link.GRU`
* `reset_state`: This same API as `link.LSTM`
* `set_state`: The pair instance of `reset_state` (it is not existed in current `link.LSTM`)
I think we should add `set_state` to `link.LSTM`, too.
Also, we need to override `to_cpu` and `to_gpu` because when the link is moved to CPU (resp. GPU), we must move its state, too. Maybe we must override these methods of `link.LSTM`.
> Make GRU stateful

- chainer/functions/activation/maxout.py
- chainer/links/activation/maxout.py
- tests/chainer_tests/functions_tests/activation_tests/test_maxout.py
- tests/chainer_tests/links_tests/activation_tests/test_maxout.py
I reimplemented Maxout with `Linear` Link. The main reasons are extensibility and simplicity.
* In the original paper, the variant of Maxout is used where linear layers are replaced with convolution layers. But we cannot reuse `MaxoutFunction` to implement it because we pass the weight tensor and bias vector of `Linear` Link to `MaxoutFunction`.
* Using `Linear` Link makes the implementation of `Maxout` Link simpler.
If this PR is merged #849 and #853 are no longer meaningful.
> Fix Maxout and make it Chain

- tests/chainer_tests/serializers_tests/test_hdf5.py
> Skip hdf5 tests when h5py is not available

- docs/source/tutorial/basic.rst
- examples/imagenet/train_imagenet.py
- examples/mnist/train_mnist.py
- examples/ptb/train_ptb.py
NumPy NPZ is now the standard serialization in Chainer, since it is available even if h5py is not installed. I made tutorials and examples runnable without h5py.
> Use NPZ in examples

- tests/chainer_tests/functions_tests/math_tests/test_batch_l2_norm_squared.py
This PR applies changes of #848 to BatchL2NormSquared's unittest.
I also fix the minor coding style error.
Related to #828
> Fix unittests of BatchL2NormSquared

- chainer/functions/array/select_item.py
- tests/chainer_tests/functions_tests/array_tests/test_select_item.py
`numpy.choose` does not work when `x.shape[1] > 32`. I replaced `choose` with indexing.
fix #875
> Use indexing instead of choose

- docs/source/reference/check.rst
`gradient_check.check_backward` is missing in the reference manual.
> Add gradient_check.check_backward to check.rst

- chainer/gradient_check.py
Docstring in `check_backward` was broken. This PR fixes to it.
Related to #874
> Fix documents of check_backward

- docs/source/tutorial/function.rst
- docs/source/tutorial/gpu.rst
- docs/source/tutorial/type_check.rst
Minor fixes of typos. For clarity, added explicitly `model.to_gpu()` to the code example, as the text immediately before it suggests.
> Tutorial patch

- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_npz.py
It fixes the problem that NPZ serializer failed to deserialize optimizers, since np.savez silently removes the slashes on the head of entry keys and contiguous slashes within the keys.
> Fix NPZ serializer with duplicated slashes

- chainer/functions/connection/embed_id.py
I found that `ufunc.at` is very slow. This patch replaces `ufunc.at` with a simple for loop.
Original:
```
% time python embed_test.py
python embed_test.py  4.13s user 0.06s system 100% cpu 4.177 total
```
This patch:
```
% time python embed_test.py
python embed_test.py  0.56s user 0.07s system 100% cpu 0.625 total
```
Test code:
```
import chainer
import numpy
e = chainer.functions.EmbedID(1000, 300)
x = chainer.Variable(numpy.random.randint(0, 1000, (200)).astype(numpy.int32))
y = e(x)
y.grad = numpy.zeros((200, 300), dtype=numpy.float32)
for i in range(1000):
y.backward()
```
> Use for-loop instead of ufunc.at as it is too slow

- chainer/link.py
- tests/chainer_tests/test_link.py
to_cpu/to_gpu methods of Chain/ChainList call these methods of their children recursively, while it also calls Link.to_cpu/to_gpu which call these methods of all parameter variables in the hierarchy. It results in duplicated call of to_cpu/to_gpu of parameters in the hierarchy. I fixed this duplication in this PR by only calling to_cpu/to_gpu of parameters directly belonging to the link.
> Deduplicate Chain.to_cpu/to_gpu

- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
cuDNN is used only when cuDNN ver >=3 is installed on softmax cross entropy.
> Skip cudnn test when cudnn v2 is installed

- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
We also need to check `cuda.cudnn_enabled`
related to #927
> Check cudnn_enabled

- cupy/statistics/histogram.py
- cupy/testing/helper.py
- tests/cupy_tests/statics_tests/test_histogram.py
numpy.bincount doesn't support uint32 and int64 on 32-bit environment.
It is because a given array is casted to numpy.intp in the method.
I removed this test case from the unit test of cupy.bincount.
fix #924
> Don't test uint32 and int64 in bincount

- cupy/cuda/memory.pyx
- cupy/cuda/runtime.pxd
- cupy/cuda/runtime.pyx
fix #882.
This PR adds cudaDeviceEnablePeerAccess call right before the first copy between given two devices.
> Direct DtoD copy

- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/functions/pooling/average_pooling_2d.py
- chainer/functions/pooling/max_pooling_2d.py
- chainer/links/connection/convolution_2d.py
- chainer/links/connection/deconvolution_2d.py
- chainer/links/connection/mlp_convolution_2d.py
Use "pair of ints" instead of `(int, int)` because napoleon cannot interpret the latter.
See e.g. ksize, stride and pad argument of [max_pooling function](http://docs.chainer.org/en/stable/reference/functions.html#chainer.functions.max_pooling_2d).
> Fix document of pooling and convolution functions.

- tests/chainer_tests/test_variable.py
The current test for debug_print cannot be passed on py3. I fixed the test.
> Fix test for debug_print

- examples/mnist/README.md
MNIST example no longer depends on scikit-learn.
> Fix README of MNIST example

- chainer/functions/math/matmul.py
- tests/chainer_tests/functions_tests/math_tests/test_matmul.py
The `batch_matmul` (in GPU mode) uses  `strides[0]` of an input array as a divisor in `_mat_ptrs` (i.e. the third argument of `cuda.cupy.arange`).
https://github.com/pfnet/chainer/blob/master/chainer/functions/math/matmul.py#L23 
And strides of ndarray will be 0 when it is a broadcasted array because of rule 4 of the ufunc’s broadcasting rules.
http://docs.scipy.org/doc/numpy-1.10.0/reference/ufuncs.html
So, ZeroDivisionError will happen.
```python
A = chainer.Variable(xp.random.random((3, 2, 4), dtype=np.float32))
B = chainer.Variable(xp.random.random((4, 6), dtype=np.float32))
B = F.expand_dims(B, 0)
B = F.broadcast_to(B, (3, 4, 6))
print(B.data.shape, B.data.strides)     # —> (3, 4, 6) (0, 48, 8)
C = F.batch_metmul(A, B)  # ZeroDivisionError (only on GPU mode)
```
We can fix the …
> Fix batch_matmul to avoid ZeroDivisionError in GPU mode

- chainer/functions/math/det.py
- chainer/functions/math/inv.py
- tests/chainer_tests/functions_tests/math_tests/test_det.py
* Add `info` vector to the return value of `_inv_gpu`.
* Change `success` with `info` in the return value of `_det_gpu`
* `F.det` and `F.batch_det` does not raise `ValueError` even if some input matrices are singular.
* `F.det` and `F.batch_det` raise `numpy.LinAlgError`when input matrices are singular.
Fix #986 
Please merge #988 before this PR.
> Fix errors F.det and F.batch_det raises

- chainer/functions/evaluation/binary_accuracy.py
- tests/chainer_tests/functions_tests/evaluation_tests/test_binary_accuracy.py
Added `ignore_label` to `binary_accuracy`.
`sigmoid_cross_entropy` already have it, and it should be also considered when computing accuracy.
> Add ignore_label to binary_accuracy

- chainer/__init__.py
- chainer/function.py
- chainer/function_hooks/__init__.py
- chainer/function_hooks/timer.py
- chainer/variable.py
- docs/source/reference/function_hooks.rst
- docs/source/reference/index.rst
- tests/chainer_tests/function_hooks_tests/test_timer.py
- tests/chainer_tests/test_function_hook.py
As we have not fully discussed the specification of examples of `FunctionHook`s (especially `MemoryHook`), we separate #933 into two PRs, `FunctionHook` mechanism and examples of `FunctionHook` (subclasses of `FunctionHook`s).
This PR implements the former one.
We change the implementation from #933 in two points.
* Remove `preprocess`, `postprocess`, and `__call__` methods of `FunctionHook`.
* Make `chainer.global_function_hook` thread safe.
> Function hook

- .travis.yml
- README.md
- docs/source/install.rst
We found that chainer doesn't work with Python 3.5.0, but it works with Python 3.5.1. I changed the document, readme and travis config.
> Python 3.5.1

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_indexing.py
This PR is fixed a cupy indexig bug.
Because current cupy do not check a number of the dimension of the index, It causes memory access error.
e.g
```
In [2]: cupy.array(0)[0]
Segmentation fault (core dumped)
In [2]: cupy.array(0)[0:1]
Segmentation fault (core dumped)
In [2]: cupy.array(0)[:]
Segmentation fault (core dumped)
In [11]: cupy.arange(10)[0, 0, 0, 0]
Out[11]: array(0)
In [12]: cupy.arange(10)[0, 0, 0, 1]
Out[12]: array(360287970189639680)
```
This PR raise `IndexError`, but numpy raise `IndexError` or `ValueError`.
```
In [2]: numpy.array(0)[0]
In [5]: numpy.arange(10)[0, 0, 0, 0]
In [6]: numpy.arange(10)[0, 0, 0, 1]
=> IndexError: too many indices for array
In [3]: numpy.array(0)[0:1]
In [4]: numpy.array(0)[:]
=> ValueError: cannot slice a 0-d array
```
> check ndim at cupy indexing

- chainer/cuda.py
**before**
```
The first error message:
File "/home/wkentaro/chainer/chainer/testing/condition.py", line 57, in <lambda>
lambda: f(*args, **kwargs),
File "/home/wkentaro/chainer/tests/chainer_tests/functions_tests/loss_tests/test_smooth_l1_loss.py", line 58, in test_backward_gpu
self.check_backward(cuda.to_gpu(self.x), cuda.to_gpu(self.t))
File "/home/wkentaro/chainer/tests/chainer_tests/functions_tests/loss_tests/test_smooth_l1_loss.py", line 49, in check_backward
(x_data, t_data), None, eps=1e-2, atol=1e-3)
File "/home/wkentaro/chainer/chainer/gradient_check.py", line 224, in check_backward
assert_allclose(gx, x.grad, atol=atol, rtol=rtol)
File "/home/wkentaro/chainer/chainer/gradient_check.py", line 76, in assert_allclose
y = …
```
> Show actual type at error in cuda.to_gpu

- chainer/functions/activation/sigmoid.py
This PR is to avoid overflow error of the NumPy.
> Use tanh instead of exp in sigmoid function

- docs/source/reference/functions.rst
- docs/source/reference/links.rst
Fix #946.
In this PR, I added a heading to each function/link in the document. It makes sphinx add these items to the side menu and users can easily look through all functions/links.
NOTE: I couldn't find a reasonable way to add arbitrary items to the side menu. This solution makes the document somewhat redundant (i.e. the name of each function/class must be written twice), though the readability is (maybe) not lowered.
The updated document can be found [here](http://docs.chainer.org/en/reference-toc-catalog/).
> Add functions and links to TOC

- chainer/serializers/hdf5.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
Hi,
Related to https://github.com/pfnet/chainer/issues/811 , we cannot load optimizer from user-specified group.
This PR fix the problem and add related tests.
You can regenerate this problem by following code:
```
import chainer
from chainer.link import Chain
from chainer.links import Linear
from chainer.optimizers import AdaDelta
from chainer.serializers import HDF5Serializer
from chainer.serializers import HDF5Deserializer
import h5py
chain = Chain(linear=Linear(100, 10))
opt = AdaDelta()
opt.setup(chain)
h5 = h5py.File("test.h5")
group = h5.create_group("test")
s = HDF5Serializer(group)
s.save(opt)
h5.close()
h5 = h5py.File("test.h5")
chain = Chain(linear=Linear(100, 10))
opt = AdaDelta()
opt.setup(chain)
group = h5['test']
d = HDF5Deserializer(group)
d.load(opt)
```
This code raises …
> Fix group deserializer

- chainer/functions/connection/embed_id.py
- chainer/links/connection/embed_id.py
- tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
I implemented `ignore_label` argument for embed id.
This code is a little slow. I thinks we need to make a special kernel.
fix #832
> Support ignore_label for embed_id

- chainer/functions/loss/softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
I added an argument to change behavior of softmax cross entropy. Only when `store_forward` is True, the loss function stores forward computation result.
fix #1067
> store_forward argument for softmax cross entropy loss

- chainer/cuda.py
- tests/chainer_tests/test_cuda.py
`__eq__` method of `DummyDevice` has a bug.
> Fix eq operator of DummyDevice

- chainer_setup_build.py
- install/build.py
`target_lang` is required for old gcc.
> Set target language c++

- chainer/functions/math/inv.py
The type of `info` is required integer array.
```c
cublasStatus_t cublasSgetrfBatched(
cublasHandle_t handle, int n, float *Aarray[], int lda,
int *PivotArray, int *infoArray, int batchSize);
cublasStatus_t cublasSgetriBatched(
cublasHandle_t handle, int n, float *Aarray[], int lda,
int *PivotArray, float *Carray[], int ldc,
int *infoArray, int batchSize);
```
> Fix dtype of argument in _inv_gpu

- chainer/links/connection/embed_id.py
- tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
From chainer 1.8.0, `links.EmbedID` has `ignore_label` parameter. So we cannot unpickle an old file generated with chainer 1.7 or older. We can avoid this problem easily.
> Set default value for `ignore_label`

- chainer/functions/noise/dropout.py
- tests/chainer_tests/functions_tests/loss_tests/test_mean_squared_error.py
I found typos 'forwrad' in some codes.
> Fix typos on dropout and mean square error test codes

- cupy/core/core.pyx
- tests/cupy_tests/linalg_tests/test_product.py
Code:
```python
import numpy, cupy
numpy.dot(numpy.ones((2,2),'f'), numpy.ones((2,2), 'd'), out=numpy.ones((2,2), 'f'))
#---------------------------------------------------------------------------
#ValueError                                Traceback (most recent call last)
#<ipython-input-4-77836e7ebc0d> in <module>()
#----> 1 numpy.dot(numpy.ones((2,2),'f'), numpy.ones((2,2), 'd'), out=numpy.ones((2,2), 'f'))
#
#ValueError: output array is not acceptable (must have the right type, nr dimensions, and be a C-Array)
cupy.dot(cupy.ones((2,2),'f'), cupy.ones((2,2), 'd'), out=cupy.ones((2,2), 'f'))
#array([[ 1.,  1.],
```
> Fix bug of cupy.dot when using with `out` argument

- chainer/functions/loss/huber_loss.py
- tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
This PR fixes #1175 .
- Modified `HuberLoss`'s `backward()` so that it will compute correct gradients even when `gy` is not ones.
- Modified its test case so that `gy` is set to random values.
Since `backward()` will start to raise an error when `gy` is `None` after this PR, some existing code might stop to work.
> Fix HuberLoss's backward computation

- chainer/functions/connection/convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
Currently this has error for cudnn function:
```
======================================================================
FAIL: test_backward_gpu_nobias (test_convolution_2d.TestConvolution2DFunction_param_2)  parameter: {'c_contiguous': False, 'cover_all': True}
----------------------------------------------------------------------
File "/home/wkentaro/chainer/chainer/testing/condition.py", line 71, in wrapper
fail()
File "/home/wkentaro/chainer/chainer/testing/condition.py", line 51, in fail
instance.fail(msg)
AssertionError:
Fail: 3, Success: 0
The first error message:
File "/home/wkentaro/chainer/chainer/testing/condition.py", line 57, in <lambda>
lambda: f(*args, **kwargs),
File …
```
> Support cover_all=True in Convolutional2D

- chainer/functions/math/basic_math.py
- tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
The basic math functions accept an array of `numpy.float16`, `numpy.float32` and `numpy.float64`.
See also  #555.
> Loosen type condition in basic_math

- chainer/functions/evaluation/accuracy.py
- tests/chainer_tests/functions_tests/evaluation_tests/test_accuracy.py
Some users want to calculate accuracy except a certain label.
For example, we usually don't obtain accuracy for `<EOS>` label under a task of predicting next charcters. 
Thank you.
> accuracy: support ignore_label

- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/local_response_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_local_response_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
> Loosen type condition in normalization functions

- chainer/gradient_check.py
- tests/chainer_tests/test_gradient_check.py
In `check_backward`, we call `Variable.backward` method with the first `Variable` object of return value. It calls backward method of a creator `Function` of the first `Variable`. When a function to test is not a `Function` object but a callable object, all returned `Variable`s of the function may has different creator `Function`s. In this case, `backward` methods of other creators of `Variable`s are not called.
To fix it I add a dummy function and insert it to a computational graph.
> Fix check_gradient bug which ocurrs when a function to test returns multiple outputs

- chainer/functions/loss/softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
> Loosen type condition in softmax_cross_entropy function

- chainer/functions/evaluation/accuracy.py
- chainer/functions/evaluation/binary_accuracy.py
- tests/chainer_tests/functions_tests/evaluation_tests/test_accuracy.py
- tests/chainer_tests/functions_tests/evaluation_tests/test_binary_accuracy.py
> Loosen type condition in evaluation functions

- chainer/functions/evaluation/accuracy.py
- tests/chainer_tests/functions_tests/evaluation_tests/test_accuracy.py
Fix #1190
Let the shape of `t` be of the form `(S0, S1, ..., Sn)`, then accepted shapes of `x` is of the form `(S0, C, S1, ..., Sn[, 1, 1, ..., 1])` where `n >= 0` and the length of 1's is more than or equals to 0. This condition includes the previous condition. And it also supports the condition of `SoftMaxCrossEntropy`.
See the test cases for the combination of shapes accepted.
> Loosen inputs' shape condition of Accuracy Function

- chainer/functions/loss/negative_sampling.py
> Remove redundant enumerate function

- cupy/core/carray.cuh
When `T` is `float16`, I want to use the following code.
```python
cuda.elementwise(
'T grad, T lr', 'T param',
'param -= lr * grad',
'sgd')
```
> Add compound assignment operators of float16

- cupy/cuda/cupy_cuda.h
Lack of `cudaOutputMode_t` definition in `cupy_cuda.h` caused build failure of Read the Docs [Detail](https://readthedocs.org/projects/chainer/builds/4042871/).
I confirmed this PR makes the build successful [Detail](https://readthedocs.org/projects/chainer/builds/4049637/).
> Define cudaOutputMode_t to cupy_cuda.h

- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/functions/connection/linear.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_linear.py
- tests/chainer_tests/test_function.py
> Loosen type condition in linear, convolution_2d and deconvolution_2d

- chainer_setup_build.py
Add `-rpath` option for El-capitan.
Original work is #1153. Thank you @kcarnold !
> -rpath option for Mac OS X

- chainer_setup_build.py
This resolves 'library not loaded (Image not found)' errors on El Capitan. See #780.
> Fix rpath for OS X.

- docs/source/compatibility.rst
- docs/source/contribution.rst
As I noted in the release note of v1.9.1, we have decided to change the release cycle.
From the next release, we can include any feature updates that do not break the backward compatibility to any biweekly releases (i.e., we can made minor releases more frequently than once per six weeks). The versioning policy is kept as is.
I reflected this change to the documentation in this PR.
> Update release cycle in the documents

- tests/chainer_tests/test_cuda.py
I appended `catch_warnings` to suppress warnings in traivs.
> Suppress warnings in test

- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/links/connection/convolution_2d.py
- chainer/links/connection/deconvolution_2d.py
Some of convolution algorithm cuDNN provides are non-deterministic.
So outputs of current chainer convolution and deconvolution can be non-deterministic when cuDNN is available.
I think this might make trouble when you want to do reproducible experiments.
This PR add `deterministic` option into these two functions and links.
If `True`, the functions force cuDNN to use deterministic algorithms.
> Add `deterministic` option into convolution_2d and deconvolution_2d

- chainer/optimizers/__init__.py
- chainer/optimizers/smorms3.py
- docs/source/reference/optimizers.rst
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
This PR adds support for the SMORMS3 optimizer described here:
http://sifter.org/~simon/journal/20150420.html
This optimizer yields faster convergence on certain workloads. The cost is higher memory requirements (stores 3 parameters per weight). A CUDA kernel is provided as well.
> Add support for SMORMS3 optimizer

- docs/source/contribution.rst
As nose's document [says](http://nose.readthedocs.io/en/latest/plugins/attrib.html#expression-evaluation), we must use `--eval-attr` option to handle expression involving inequality.
> Fix document on multi-GPU test

- chainer/functions/activation/lstm.py
Use `six.moves.range` instead of `range`.
If any reason for using `range`, this PR should be rejected.
> refactoring: range -> six.moves.range

- README.md
This PR fixes travis status badge on README.md to show master branch's build status.
It's because the badge currently shows that of all branches in Chainer so it often says "build failing", it is not the case.
> Fix Travis CI status badge to show master's status.

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_scan.py
```
import cupy
cupy.array([1,1]).nonzero()
with cupy.cuda.Device(1):
cupy.array([2, 3]).nonzero() # -> CUDADriverError: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
```
> bug fix: scan kernel fails with multi gpu

- chainer/links/model/classifier.py
- tests/chainer_tests/links_tests/model_tests/test_classifier.py
Current `L.Classifier` cannot change evaluator that calculates accuracy from default `Accuracy` Function with default argument. But we have other kind of accuracy such as `binary_accuracy`. Also, `Accuracy` Function itself has an argument `ignore_label`. This PR add the argument `evaluator` to `Classifier` and make the evaluator pluggable.
> Add evaluator argument to Classifier

- chainer/functions/pooling/roi_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
I implemented fast r-cnn https://github.com/apple2373/chainer-simple-fast-rnn, and realized roi pooling with cpu does not work. It always outputs only one roi when forwarding. I just copied two lines from GPU implementation. Also I am not sure backward function is also wrong or not because I only use forwarding now.
> fix bug in roi pooling forwarding with cpu

- chainer/cuda.py
- tests/chainer_tests/test_cuda.py
The current implementation of `cuda.get_device` does not support NumPy scalar (with which this function should return DummyDevice) in non-CUDA environment, because it calls `check_cuda_available()` unnecessarily. I rechecked the definition of `get_device` and support NumPy scalar on non-CUDA environment. It also simplifies the definition.
> Support numpy scalar in get_device for non-CUDA environment

- chainer/functions/loss/contrastive.py
- tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
In Contrastive.backward(), division by zero occurs when ```dist``` is equal to zero.
```
gx0 += alpha * (1 - y) * mdist_p * mdist * -(self.diff / dist)
```
It causes that gradient value is nan.
Please see my proposed modification.
> Avoid division by zero

- cupy/__init__.py
The second argument of `reraise` needs to be an exception object. In python3, the original one causes another error.
> Fix second argument of reraise

- examples/word2vec/train_word2vec.py
- Use multi dimensional embed ID
- Fix initial parameter
- Fix default minibatch size
- Merge kernels in negative sampling
- Fix default negative sampling size (=5)
With my GTX 970, its performance is about 300Kwords/sec with minbatch-size=5000, n_units=400, window=5, HSM and CBOW model. Negative sampling is slower than HSM because its implementation is not tuned.
> Improve word2vec

- chainer/functions/pooling/max_pooling_2d.py
Hi,
Sometimes I want to use Chainer on cpu mode. Some days ago, I noticed that `MaxPooling2D.backward_cpu` is so slow and @beam2d leave a TODO comment: "Make it fast". I did it.
For training a simple LeNet like network, throughput was increased from 130 images/sec to 650 images/sec on my machine.
Here's a result of profiling which compares before applying this PR and after applying this PR. You can see that in the case of before applying, most of the time is consumed on `MaxPooling2D.backward_cpu`. After applying the patch, the most time consuming methods `tensordot`, `col2im_cpu` and `im2col_cpu`. `MaxPooling2D.backward_cpu` is still not negligible, but it's not a bottleneck any more.
I used [statprof-smarkets](https://pypi.python.org/pypi/statprof-smarkets) as a profiler.
before:
```
% …
```
> make MaxPooling2D.backward_cpu faster

- cupy/core/core.pyx
- tests/cupy_tests/linalg_tests/test_product.py
I fixed dot operator to support dot with zero-sized axis such as `(3, 0) x (0, 3)`.
related to #1336
> Support zero dot

- docs/source/reference/functions.rst
This PR adds `stack` function to Chainer reference, it suppose to be missed in #1262 .
> Add stack function missed in Chainer reference.

- chainer/functions/array/get_item.py
- tests/chainer_tests/functions_tests/array_tests/test_get_item.py
I fixed `get_item` method to support `int` and `Ellipsis`. fix #1369
> Fix get_item to support int index and ellipsis

- chainer/functions/array/concat.py
- tests/chainer_tests/functions_tests/array_tests/test_concat.py
I fixed concat function to check its argument.
> Check type of axis in initializer of concat function

- tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
triplet loss function uses maximum function, that is uncontinuous. I feel it is difficult to avoid this point, so I fixed simply retry count.
> Fix retry count to stable test

- chainer/variable.py
`self.creator is not None` is always `True`.
> Remove an unnecessary branch

- tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
- tests/chainer_tests/functions_tests/activation_tests/test_relu.py
- tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py
- tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
- tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
The default value of `use_cudnn` is `True`.
When `use_cudnn` options is `True`, we expect that functions can be used without cuDNN.
> Test use_cudnn without cuDNN

- chainer/functions/normalization/batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Type checking is loose.
```
In [1]: import numpy
In [2]: import chainer
In [3]: bn0 = chainer.links.BatchNormalization(64)
In [4]: bn0(chainer.Variable(numpy.zeros((1,100,1,1),dtype='f')))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-ddda6c9bb1a9> in <module>()
----> 1 bn0(chainer.Variable(numpy.zeros((1,100,1,1),dtype='f')))
/home/okuta/env/chainer/chainer/chainer/links/normalization/batch_normalization.pyc in __call__(self, x, test, finetune)
92         if use_batch_mean:
93             func = batch_normalization.BatchNormalizationFunction(self.eps)
---> 94             ret = func(x, self.gamma, self.beta)
95
96             if finetune: …
```
> Fix checking shape in BatchNormalizationFunction

- cupy/cuda/memory.pyx
- cupy/cuda/runtime.pyx
- tests/chainer_tests/test_cuda.py
- tests/cupy_tests/core_tests/test_ndarray_get.py
- tests/cupy_tests/cuda_tests/test_stream.py
This PR fixes the problem that `cupy.ndarray.get` or `cuda.to_gpu` fails when we give `stream` parameter. I worked with @okuta san.
> Fix async to cpu

- chainer/gradient_check.py
- tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
- tests/chainer_tests/functions_tests/activation_tests/test_elu.py
- tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py
- tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py
- tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
- tests/chainer_tests/functions_tests/activation_tests/test_lstm.py
- tests/chainer_tests/functions_tests/activation_tests/test_prelu.py
- tests/chainer_tests/functions_tests/activation_tests/test_relu.py
- tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py
- tests/chainer_tests/functions_tests/activation_tests/test_slstm.py
- tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
- tests/chainer_tests/functions_tests/activation_tests/test_softplus.py
- tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
- tests/chainer_tests/functions_tests/array_tests/test_broadcast.py
- tests/chainer_tests/functions_tests/array_tests/test_where.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_linear.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
- tests/chainer_tests/functions_tests/math_tests/test_linear_interpolate.py
- tests/chainer_tests/functions_tests/math_tests/test_maximum.py
- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
- tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
- tests/chainer_tests/test_gradient_check.py
`gradient_check.check_backward` is poor accuracy for `numpy.float16` array.
I add `dtype` option.
`check_backward` casts input arrays.
> gradient_check.check_backward supports dtype option

- chainer/training/extensions/evaluator.py
There is no `eval_loop` argument. I suppose it should be `eval_func`.
> Fix incorrect argument name in docstring

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_scan.py
This PR adds out option to cupy.core.core.scan.
Performance improvement
```
In [2]: a = cupy.arange(10000)
In [3]: %timeit cupy.core.core.scan(a)
The slowest run took 143.12 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 259 µs per loop
In [2]: a = cupy.arange(10000)
In [3]: %timeit cupy.core.core.scan(a)
The slowest run took 13.74 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 35.7 µs per loo
In [4]: b = cupy.zeros_like(a)
In [5]: %timeit cupy.core.core.scan(a,b)
The slowest run took 25.18 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 18.7 µs per loop
```
> add out option to cupy.core.core.scan & performance improvement

- cupy/core/core.pyx
Calling ``elementwise_copy`` is high cost.
> Use memset in cupy.ndarray.fill

- chainer/training/updater.py
Currently, `ParallelUpdater` can only be used with GPUs. This PR slightly modifies `ParallelUpdater` to enable CPU execution. Like other functions and modules, when `devices` include `-1` or `None`, corresponding models are placed on CPUs. This feature is useful for development iterations, e.g., to dry-run scripts on a local laptop PC without CUDA.
(As future enhancement/refactoring, I propose to define functions like `to_device` in function `concat_examples` (https://github.com/pfnet/chainer/blob/f26f08ca18cceddc225c3baf2dab48596eb81d2b/chainer/dataset/convert.py#L53) at somewhere to make them reusable.)
> Update ParallelUpdater to enable CPU execution

- chainer/dataset/convert.py
PEP8 recommends to use `def` instead of binding a lambda expression to an identifier.
> Make not to assign a lambda expression to conform to PEP8

- chainer/datasets/cifar.py
This PR fixes `UnicodeDecodeError` in `chainer.datasets.get_cifar10` and `chainer.datasets.get_cifar100` when using Python 3.
The following code raises error:
```python
import chainer
chainer.datasets.get_cifar10()
```
And give a trackback:
```
Downloading from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz...
File "/home/fohte/.pyenv/versions/3.5.2/lib/python3.5/site-packages/chainer/datasets/cifar.py", line 43, in get_cifar10
raw = _retrieve_cifar('cifar-10')
File "/home/fohte/.pyenv/versions/3.5.2/lib/python3.5/site-packages/chainer/datasets/cifar.py", line 144, in _retrieve_cifar
return download.cache_or_load_file(path, creator, numpy.load)
File "/home/fohte/.pyenv/versions/3.5.2/lib/python3.5/site-packages …
```
> Fix UnicodeDecodeError in get_cifar on python3

- chainer/datasets/image_dataset.py
- examples/imagenet/train_imagenet.py
If the image is gray scale, an error, "ValueError: axes don't match array" will occur in line 123.
> image_dataset.py doesn't work if an input image is gray scale

- tests/chainer_tests/links_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_linear.py
- tests/chainer_tests/links_tests/connection_tests/test_peephole.py
This PR fixes `gradient_check.assert_allclose` used in recent commits to `testing.assert_allclose`.
> Fix gradient_check.assert_allclose to testing.assert_allclose.

- docs/source/reference/functions.rst
This PR adds `log1p` function to reference, which seems to be missing after it was implemented.
> Add log1p function to reference.

- chainer/functions/connection/embed_id.py
- tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
This PR is for skipping checks validity if value equals `ignore_label` (#1351 ).
`embed_id ` will not raise error value is "invalid" but equals `ignore_label`.
> embed_id skip checks validity if value equals ignore label.

- chainer/functions/__init__.py
- chainer/functions/math/sqrt.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/math_tests/test_sqrt.py
This PR implements `sqrt` function with covering test for input of dtype `float16`, `float32` and `float64`.
It uses `numpy.sqrt` and `cupy.sqrt` with specifying `dtype` keyword parameter to make them return output with the same `dtype` with input.
See http://docs.chainer.org/en/stable/cupy-reference/math.html#cupy.sqrt .
> Implement square root function.

- chainer/training/extensions/_snapshot.py
- tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
Separated from #1400 
`snapshot` accepts trigger such as `trigger=(10, 'epoch')` and `MinValueTrigger` in #1400.
> snapshot and snapshot_object extension accept trigger

- cupy/manipulation/join.py
- tests/cupy_tests/manipulation_tests/test_join.py
This bug prevented us from applying `hstack` to ndarrays with `ndim=0`.
> Fix cupy.hstack

- cupy/core/core.pyx
- cupy/statistics/order.py
- tests/cupy_tests/core_tests/test_ndarray_reduction.py
- tests/cupy_tests/sorting_tests/test_search.py
Numpy's `min` and `max` return NaN when an array contains NaN value.
Note that `min` and `max` functions in CUDA ignore NaN values.
fix #1366
> Fixed min and max behavior for NaN values

- chainer/functions/__init__.py
- chainer/functions/math/sqrt.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/math_tests/test_sqrt.py
This PR implements a function that computes reciprocal of square root.
Currently it is implemented with combining Chainer functions, though it would be more efficient to use CUDA math API `rsqrt` for GPU implementation.
In contrast, numpy seems not to provide such optimized `rsqrt` counterpart.
> Implement function for reciprocal of square root.

- chainer/function.py
I used `six.raise_from` to raise an error from `except` clause.
fix #1552
> Fix nested error

- chainer/link.py
- chainer/optimizer.py
- chainer/training/updater.py
- chainer/variable.py
- examples/ptb/train_ptb.py
- examples/sentiment/train_sentiment.py
- examples/word2vec/train_word2vec.py
- tests/chainer_tests/links_tests/activation_tests/test_maxout.py
- tests/chainer_tests/links_tests/activation_tests/test_prelu.py
- tests/chainer_tests/links_tests/connection_tests/test_bias.py
- tests/chainer_tests/links_tests/connection_tests/test_bilinear.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
- tests/chainer_tests/links_tests/connection_tests/test_linear.py
- tests/chainer_tests/links_tests/connection_tests/test_lstm.py
- tests/chainer_tests/links_tests/connection_tests/test_scale.py
- tests/chainer_tests/links_tests/loss_tests/test_hierarchical_softmax.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
- tests/chainer_tests/test_link.py
- tests/chainer_tests/test_variable.py
`Variable.zerograd` requires allocated memory and fills with zero, but [these operations are not necessary](https://github.com/pfnet/chainer/blob/v1.13.0/chainer/variable.py#L375).
TODOs:
- ~~write tests~~
- write docs (I will send another PR for docs)
> Replace zerograd(s) with cleargrad(s)

- examples/mnist/train_mnist.py
- examples/mnist/train_mnist_data_parallel.py
- examples/mnist/train_mnist_model_parallel.py
This change decreases the number of snapshots taken in the MNIST example. It makes the example quickly finish.
> Take a snapshot only at the end of the learning in MNIST example

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_owndata.py
```python
>>> numpy.ndarray(()).flags['OWNDATA']
True
>>> cupy.ndarray(()).flags['OWNDATA']
False
>>> numpy.ndarray(()).view().flags['OWNDATA']
False
>>> cupy.ndarray(()).view().flags['OWNDATA']
True
```
> Fix ndarray's OWNDATA flag

- docs/source/tutorial/gpu.rst
`cuda.init()` is not removed but deprecated.
> Fix GPU tutorial

- chainer_setup_build.py
`compiler` is a keyword argument.
fix #1557
> Use keyword argument

- chainer_setup_build.py
In some environment, `distutils` raises an error. This patch ignores errors and skips installing cupy.
> Skip build when distutils raises an error

- chainer/cuda.py
- chainer/functions/__init__.py
- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/convolution_nd.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/links/__init__.py
- chainer/links/connection/convolution_nd.py
- chainer/utils/conv_nd.py
- chainer/utils/conv_nd_kernel.py
- cupy/cudnn.py
- docs/source/reference/functions.rst
- docs/source/reference/links.rst
- docs/source/reference/util/cuda.rst
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/utils_tests/test_conv.py
- tests/chainer_tests/utils_tests/test_conv_nd.py
- tests/chainer_tests/utils_tests/test_conv_nd_kernel.py
This PR implements N-dimensional convolution function and link, following #1279 which is reverted by #1542, and now support cuDNN 5.x.
In this PR, it is to support FP16, FP32 and FP64 of storing precision, and FP32 and FP64 of computing precision. FP16 computing precision will be supported through another issue, since we would require policy making on how to treat FP16 computing precision on GPUs with compute capability that does not support it.
> Support N-dimensional convolution function and link

- cupy/testing/helper.py
- tests/cupy_tests/core_tests/test_ndarray_elementwise_op.py
- tests/cupy_tests/core_tests/test_ndarray_unary_op.py
- tests/cupy_tests/linalg_tests/test_product.py
- tests/cupy_tests/manipulation_tests/test_rearrange.py
- tests/cupy_tests/sorting_tests/test_search.py
- tests/cupy_tests/statics_tests/test_histogram.py
- tests/cupy_tests/testing_tests/test_helper.py
I fixed default argument of numpy-cupy comparison. And, I set `accept_error=True` for only tests which raises errors.
fix #1419
> Change default behavior of accept_error

- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
The population statistics should not be updated while testing even if in
finetune mode.
Changed to use pre-computed population statistics when test and finetune
are both True.
> A bug-fix in BatchNormalization both test and finetune are True.

- cupy/core/core.pyx
cupy.clip returns different values (compared to numpy.clip) when a_min is greater than a_max.
`cupy.clip(cupy.arange(10), 7, 3)` must be evaluated to [7, 7, 7, 7, 7, 7, 7, 3, 3, 3].
> Fix cupy.clip

- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
`batch_normalization` and `fixed_batch_normalization` functions support the `use_cudnn` argument, while `BatchNormalization` link does not have a corresponding attribute, which is added by this PR.
> Add use_cudnn flag to BatchNormalization link

- examples/word2vec/README.md
- examples/word2vec/train_word2vec.py
I fixed word2vec example to use Trainer. I implemented a custom iterator instead of making dataset as the default iterator and converter is too slow for this example. This iterator takes mini-batch data from a dataset using `numpy.take` which is faster than `__getitem__`.
> Word2vec trainer

- examples/word2vec/train_word2vec.py
word2vec example contains a bug when a user run it with `--test` option. I fixed it to count words before trimming data for test mode.
Please execute this command:
```
$ examples/word2vec/train_word2vec.py -e 1 -b 10 -m cbow --out-type ns --test
```
related #1500
> Count words before trimming data

- tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
ndarray of numpy 1.9 doesn't support matmul operator (@). I fixed a test to use dot method instead.
> Use dot instead of matmul for numpy 1.9

- chainer/link.py
- tests/chainer_tests/test_link.py
Fix #1631.
This PR makes Link's `__init__` method to accept dtypes as well as shapes to register parameters as the following:
l = link.Link(W=((2, 3), 'd'))
where link `l` has parameter `W` with its shape of `(2, 3)` and dtype of `'d'`.
> Accept dtype to add parameters via Link's __init__ method.

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
It seems that cuDNN v2's ndconv does not accept 2 for shape.
> Fix test for cuDNN v2

- chainer_setup_build.py
- cupy/cuda/cupy_cuda.h
Exclude `cupy.cuda.nvtx` on Windows for a while to solve a build issue. This should be fixed in near future.
Ref: https://github.com/pfnet/chainer/issues/1660
> Remove nvtx on Windows for a while

- README.md
The NIPS workshop paper has been moved to another URL.
> Fixed the link to paper pdf

- examples/imagenet/alex.py
Despite the original AlexNet applies the local response normalization layer after the relu, the current example applies the relu after the local response normalization layer.
(This bug was originally reported by another guy in the nvidia event)
> Fix AlexNet in examples to use the correct order of layers

- chainer/link.py
- tests/chainer_tests/test_link.py
This fixes a bug when supplying a shape to the `__init__()` of link that contains numpy integer types. For example a shape of the form `(numpy.int64, int)` should be considered a valid shape.
> Fixed bug in link when passing numpy int types in shape.

- README.md
Reverts pfnet/chainer#1686, since the paper URL is back to the previous one.
> Revert "Fixed the link to paper pdf"

- chainer/function.py
I used multi thread and multi GPU on training for faster training.
But with chainer1.16.0, I cannot use multi thread by causing error about `_thread_local.default_backprop` is not defined.
This PR resolve this error by using global value.
> without using threading.local()

- tests/chainer_tests/test_function.py
I wrote a test of backprop mode for multi-threading environment.
related to #1705
> Write test backprop mode for multi-threading environment

- chainer/functions/loss/softmax_cross_entropy.py
I found a typo in chainer/functions/loss/softmax_cross_entropy.py line [39](https://github.com/pfnet/chainer/blob/master/chainer/functions/loss/softmax_cross_entropy.py#L39).
> Fix typo in comment.

- cupy/cuda/cupy_cuda.h
Fix build of documents by eliminating undefined reference error.
> Fix build of CuPy reference

- chainer/functions/connection/convolution_nd.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
Related to #1687 .
This PR makes `convolution_nd` function accept `ndarray` as its `x` argument. Its docstring is modified in #1687 .
> Make convolution_nd function work with ndarray.

- chainer/iterators/multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
This PR reduce training time.
master
```
% ./train_imagenet.py /data/ILSVRC/train10k.txt /data/ILSVRC/val1k.txt --arch alex --gpu 2 --epoch 2 --batchsize 64
228.25s user 55.60s system 296% cpu 1:35.78 total
```
sharedmem
```
% ./train_imagenet.py /data/ILSVRC/train10k.txt /data/ILSVRC/val1k.txt --arch alex --gpu 2 --epoch 2 --batchsize 64
209.88s user 55.53s system 552% cpu 48.033 total
```
> Use shared memory in multiprocess iterator

- chainer/datasets/image_dataset.py
In pillow>=3.0, Image object supports with statement and has close method. However, in pillow 2, Image object has none of them. To support both versions, I used close method directly only when an Image object has the method.
related to #1583
> Use close method directly instead of using with statement

- chainer/links/connection/lstm.py
- tests/chainer_tests/links_tests/connection_tests/test_lstm.py
This PR enables us to put `None` as the input size of `LSTM` and `StatelessLSTM` links.
```
a = chainer.Variable(numpy.random.uniform(0, 1, (5, 10)).astype(numpy.float32))
l = L.LSTM(None, 5)
l(a)
```
> LSTM supports parameter shape place holder

- tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
This PR fixes a test for rollaxis function, where `test_type_error_gpu` should be tested with cupy.ndarray but is tested with numpy.ndarray.
> Fix test for rollaxis.

- chainer/cuda.py
- tests/chainer_tests/test_cuda.py
Note that we do not use `isinstance` in `get_device` for performance.
> Treat future.types.newint.newint properly in get_device

- chainer/links/normalization/batch_normalization.py
In current BN implementation, it assign new values to avg_mean and avg_var.
It causes a problem when you use copy() to make a new model for validation (as ImageNet example does).
> Fix BN problem, it works with copy().

- examples/imagenet/train_imagenet.py
Fix #1691.
The current ImageNet example copies the model for evaluation in order to change the `train` flag. This code relies on an assumption that the model definition is fixed before the training, while it is not fulfilled anymore since the introduction of parameter-shape placeholder #1363. I stopped copying the model for this purpose and wrote a customized evaluator for temporarily changing the `train` flag for evaluation.
> Fix ImageNet example for conflicts of parameter-shape placeholder and model copy

- chainer/functions/connection/convolution_nd.py
This PR fixes `convolution-nd` function to use destructive `astype` method for efficiency, which is the same approach with #1444 . It improves nearly 10% of its efficiency in my handy profiling.
> Use destructive astype in convolution-nd function for efficiency.

- chainer/training/__init__.py
- chainer/training/evaluator.py
- chainer/training/extensions/evaluator.py
- tests/chainer_tests/training_tests/test_evaluator.py
Add `chainer.training.evaluator.Evaluator` and `chainer.training.evaluator.StandardEvaluator` to evaluate testing error and accuracy.
Although `chainer.training.extensions.Evaluator` can evaluate them *by itself*, *standalone extension* is strange and it should be pure training extension which call external defined evaluation procedure. Thus, I define evaluator interface(`chainer.training.Evaluator`) and move evaluating codes from `chainer.training.extensions.Evaluator` to `chainer.training.evaluator.StandardEvaluator`.
I tested `examples/mnist/train_mnist.py` and it worked.
> Extract evaluation procedure from training extension `Evaluator`

- chainer/function_hooks/timer.py
This is a bug fix.
Since the returned value is in millisecond scale, it must be divided by 1000 to change second scale.
> fix scale of elapsed_time for GPU case

- chainer/datasets/sub_dataset.py
- tests/chainer_tests/datasets_tests/test_sub_dataset.py
This PR aims to add ``seed`` option to ``split_dataset_random()`` and ``get_cross_validation_datasets_random()`` functions.
It would be useful when you split a dataset to train and test datasets, train a NN with the train dataset, and test the trained NN with the test dataset by another script.
> Add seed option to split functions

- docs/source/tutorial/basic.rst
Downloading mnist dataset takes long time. I replaced `get_mnist` function with a dummy function which generates random dataset.
> Fix doctest for training data

- .gitignore
- readthedocs.yml
I made a configuration file for rtd-bulild command. You can build the document with `rtd-build` command under the root. This command creates clean environment using virtual-env.
https://github.com/rtfd/readthedocs-build
related to #1600
> Configuration file for rtd-build command

- chainer/functions/connection/n_step_lstm.py
- cupy/cudnn.py
I fixed NStepLSTM. This fix reuses dropout descriptor instead of reproducing it.
fix #1803
> Fix dropout state bug on rnn API

- chainer/links/connection/linear.py
- chainer/links/connection/lstm.py
- tests/chainer_tests/links_tests/connection_tests/test_linear.py
- tests/chainer_tests/links_tests/connection_tests/test_lstm.py
I fixed the shape placeholder problem caused when ndarray is input.
It occurs in `Linear`, `StatelessLSTM` and `LSTM` links.
This problem caused by `len(x.data)` used for input size calculation.
When `x` is ndarray `len(x.data)` is buffer size of `x`.
Here is an example to cause the problem: (on Chainer v1.17.0)
```
>>> from chainer import links as L
>>> import numpy as np
>>> fc = L.Linear(None, 10)
>>> x = np.zeros((10, 10), dtype=np.float32)
>>> y = fc(x)
File "chainer/links/connection/linear.py", line 91, in __call__
self._initialize_params(x.size // len(x.data))
File "chainer/links/connection/linear.py", line 77, in _initialize_params
initializer=self._W_initializer)
File "chainer/link.py", line 180, in add_param …
```
> Fix link placeholder problem caused by ndarray input.

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
I fixed optimizer to initialize grads of parameters before calling hooks and update method. This fix is ineffective when updater does not affect param value when grad is None. I think efficiency is another issue.
fix #1786
> Initialize grad before Optimizer calls update method

- cupy/cuda/cudnn.pxd
- cupy/cuda/cudnn.pyx
- cupy/cuda/curand.pyx
- cupy/cuda/device.pxd
- cupy/cuda/device.pyx
We need to append "except *" to functions returning integers. If not, these functions ignore raised Exceptions.
> Append except clause to functions that returns int

- tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
This PR adds tests to dropout function.
There is only typecheck test in dropout function.
I add forward and backward tests to dropout test.
I think that these tests may not be enough but are better than nothing.
> Add forward and backward test to dropout

- chainer/functions/evaluation/classification_summary.py
- tests/chainer_tests/functions_tests/evaluation_tests/test_classification_summary.py
`xp.maximum` returns element-wise maximum values. I fixed it to use `xp.amax`.
`label_num=None` is not tested correctly.
> Use amax instead of maximum

- docs/source/install.rst
This is to solve #1852. I heard that the correct version requirement for Cython is 0.24, which is also consistent to `chainer_setup_build.py`.
> Update Cython's version requirement in the install guide

- chainer_setup_build.py
Even if old Cython is already installed, `setup.py` just says that `Please install Cython`. Making the message more informative would be beneficial.
> Update the error message about Cython's failure

- cupy/core/__init__.py
- cupy/core/core.pyx
- cupy/manipulation/dims.py
This PR moves `broadcast_to` from `cupy/manipulation/dims.py` to `cupy/core/core.pyx`. This is necessary for methods inside of `core` to call `broadcast_to`.
Some changes being made include ...
+ the method is now defined by `cpdef`.
+ on line 1682 of `core.pyx`, `j` is changed to `j % array.ndim`. This is necessary because `_strides` does not accept negative values as index
> Move broadcast_to to cupy.core.core

- chainer/link.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
Fix `cleargrads` and `zerograds` to work properly with uninitialized parameters.
> Fix cleargrads and zerograds for uninitialized parameters

- cupy/core/__init__.py
- cupy/core/core.pyx
- cupy/manipulation/join.py
This PR moves `concatenate` from `cupy/manipulation/join.py` to `cupy/core/core.pyx`.
I needed `concatenate` in `cupy.core.core` in #1863.
I had choice of either...
+ copy the entire function in `cupy/manipulation/join.py`.
+ exclude part that handles irregular cases.
I decided the latter in my implementation.
> Move part of concatenate to cupy.core.core

- chainer/links/connection/convolution_nd.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
This PR make `ConvolutionND` link support `dtype` of FP16 and FP64, which are currently supported only in `convolution_nd` function. Fix #1625.
There are the following possible approaches how to supply its parameter `dtype` to the link:
- Make `ConvolutionND` link to accept parameter `dtype` so that it can `add_param` parameters with the supplied `dtype`.
- Make initializers to be responsible of converting parameters `dtype`
This PR implements in the former approach and, as a future issue, it would be expected that shape placeholder facility also supports `dtype` of uninitialized parameters as well as their `shape`.
> Support FP16 and FP64 in N-dimensional convolution link

- cupy/linalg/norms.py
- tests/cupy_tests/linalg_tests/test_norms.py
Old version `norm` is not tested about result dtype.
Old version `numpy.norm` is broken, because `numpy.sqrt` is broken (it is fixed at v1.11.2).
> Fix norm result dtype and test it

- chainer_setup_build.py
- install/build.py
I fixed setup script to build a shared library when it checks libraries, because distutils doesn't check LDFLAGS when it build an executable.
> Try to build shared library to check dependent libraries

- tests/cupy_tests/math_tests/test_matmul.py
Only numpy>=1.10 supports `numpy.matmul`.
> Only test matmul on numpy>=1.10

- cupy/cuda/driver.pyx
`./train_imagenet.py` had stopped in my environment.
> Fix GIL bug when call cuLaunchKernel

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
The PR change `ndarray.__getitem__` to accept `ndarray` or `numpy.ndarray` in the argument. It checks for the `dtype` of arrays in the argument, and raise Error when necessary. Currently, only integer arrays are supported. 
The modification simply integrates `take` and `__getitem__`. With this PR, `a[:, idx]` returns same value as `a.take(idx, axis=1)`.
> Add integer array indexing on one axis for __getitem__

- docs/source/reference/functions.rst
`F.binary_accuracy` is implemented at #757 but missing in the manual.
> Add binary_accuracy function to the reference manual

- docs/source/reference/functions.rst
This small PR aims to add ``mean_absolute_error`` loss function merged in #1881 to the reference.
(Sorry I forgot to add it to the reference)
> Add mean_absolute_error to the reference

- chainer/datasets/tuple_dataset.py
TupleDataset.__init__() checks whether all items in the datasets argument
have the same length as datasets[0], but the doc says all datasets must
have (some) length, which should be a mistake.
> fix a doc error

- README.md
Add links to "External examples" and "Research projects using Chainer" pages in wiki to README.md.
> Add additional information to README

- chainer/training/extensions/print_report.py
- chainer/training/extensions/progress_bar.py
- chainer/training/extensions/util.py
“progress_bar” and “print_report” does not work well on windows, because
Windows command console does not support ANSI escape sequence. Adding
some functions for this. And these extensions can work well on Windows.
> Progress_bar and print_report support Windows

- docs/source/reference/functions.rst
Fixes the WARNING when compiling the documentation.
> Fixed under-title length.

- chainer/link.py
- tests/chainer_tests/test_link.py
`link_a.copyparams(link_b)` skips uninitialized parameters of `link_a`, even if the corresponding parameters of `link_b` are already initialized. With this PR, these parameters are also copied to `link_a`.
> Support copyparams to uninitialized parameters

- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
This PR suppresses `cudaMalloc` before fork in test. I am not sure whether this change is acceptable, but we must not call `cudaMalloc` in global scope.
> Suppress cudaMalloc before fork in test

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
merge after #1832  
This PR makes CuPy's `__getitem__` handle any combination of `:`, `None`, `Ellipsis`, `integer array` that NumPy can handle. This PR does not support `boolean array`.
This extends #1832 by adding supports for ...
+ multiple integer array (e.g. `a[[1, 0], [0, 1]]`)
+ combination of basic indexing and integer array (e.g. `a[1:3, [1, 0, 2]]`)
NumPy advanced array indexing specification is sometimes complicating.
A notable example is a case when array indices are not located next to each other.
Here is an example with indices located next to each other.
```python
>>> shp = (3, 4, 5, 6)
>>> a = np.arange(np.prod(shp)).reshape(shp)
>>> b = [1, 0]; c = [2, 1]
>>> idx = (slice(None), b, c, slice(None))
>>> a[idx].shape
(3, 2, 6)
```
and one where indices are not located next …
> Add multiple integer indexing & basic/adv indexing for __getitem__

- cupy/core/core.pyx
This PR fixes the latest broken master with improving its py2/py3 compatibility,
https://ci-chainer.pfidev.jp/job/chainer-sakura/298/
which is confirmed to work in jenkins build # 302.
https://ci-chainer.pfidev.jp/job/chainer-sakura/302/
> Fix ndarray.__getitem__ py2/py3 compatibility

- chainer/iterators/multiprocess_iterator.py
The current reference does not contain ``MultiprocessIterator`` due to the top of ``_last_signal = object()``.
> Add MultiprocessIterator to the reference

- cupy/core/core.pyx
`__setitem__` does not support slices with arrays, but no error is raised.
Previously, `__getitem__` raised error in such cases, but since #1832 it no longer raise error.
This PR makes `__setitem__` raise error without depending on `__getitem__`.
> raise error when array is included in slices of __setitem__

- cupy/sorting/search.py
- tests/cupy_tests/sorting_tests/test_search.py
Currently, `cupy.where` does not support arguments with only `condition`.
This PR handles that case by calling `ndarray.nonzeros`.
example
```python
>>> cond = cupy.array([True, False, True])  
>>> cupy.where(cond)
(array([0, 2]),)
```
> Support cupy.where to take arguments that only has condition

- chainer/link.py
- tests/chainer_tests/test_link.py
This bug causes a very confusing problem.
If `Chain` object contains `Link` object, `grad` of uninitialized parameter in the `Link` object will be initialized by `NaN`.
> Fix cleagrads and zerograds when use uninitialized params

- cupy/__init__.py
- cupy/binary/packing.py
- tests/cupy_tests/binary_tests/test_packing.py
This PR addresses two TODOs of CuPy by adding functions `packbits` and `unpackbits`. As confirmed in the tests, they exactly follows the behaviour of the counterparts of NumPy, except that `packbits` does not support `axis` option.
> Add packbits and unpackbits

- chainer/function_hooks/debug_print.py
I found an example code in docstring of `chainer.function_hooks.PrintHook` to fail to work.
It fails to call `chainer.function_hooks.PrintHook()` because `chainer/__init__.py` does not contain `from chainer import function_hooks`.
I am not sure if the doc is wrong, or it is a bug and the `from chainer import function_hooks` is simply forgotten in `chainer/__init__.py`.
> Fix doc of function_hooks.PrintHook to have proper import

- docs/source/cupy-reference/overview.rst
I think `nonzero` and `flatnonzero` are missing from the list in the overview page of CuPy document. This PR adds them there.
http://docs.chainer.org/en/stable/cupy-reference/overview.html#sorting-searching-and-counting
> Add nonzero and flatnonzero to the overview page of CuPy document

- chainer/functions/normalization/batch_normalization.py
> Fix eps check for batch normalization

- tests/chainer_tests/links_tests/model_tests/test_vision.py
This PR fixes test so that CI will succeed.
`test_vision.py` includes downloading large file.
Travis CI cannot run long time job.
https://travis-ci.org/pfnet/chainer/jobs/181078547#L768
> Add slow flag to test_vision for CI

- chainer/__init__.py
- chainer/utils/__init__.py
- chainer/utils/experimental.py
- docs/source/compatibility.rst
- docs/source/reference/util.rst
- docs/source/reference/util/experimental.rst
- tests/chainer_tests/utils_tests/test_experimental.py
This PR adds a function that marks an API as *experimental*.
* Developer can mark any newly added API as experimental by calling `chainer.utils.experimental`.
* Chainer can modify the interfaces of experimental APIs at any version up.
* Chainer can remove experimental mark at any minor or major version up and consider the API as *stable*. Once APIs get stable, they cannot be *experimental* again in principle.
* If users use an experimental API for the first time,`FutureWarning` is raised (one warning for each experimental API)
* Users can disable the warning by setting `chainer.disable_experimental_feature_warning`to `False`
> Experimental feature

- tests/cupy_tests/binary_tests/test_packing.py
packbits method does not work with bool array on Numpy 1.9.
> Skip test for packbits when numpy 1.9 is installed

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
This PR make `ndarray.__getitem__` behave consistently with NumPy when there is 0d array in `slices`.
> Support 0d array as argument of ndarray.__getitem__

- chainer/links/__init__.py
- chainer/links/normalization/layer_normalization.py
- docs/source/reference/links.rst
- tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py
This PR adds a new link, LayerNormalization from "Layer Normalization." by Jimmy Lei Ba, Jamie Ryan Kiros and Geoffrey E. Hinton on https://arxiv.org/abs/1607.06450.
The paper says Layer Normalization is successful specially for internal layers in RNN including LSTM and GRU. Such RNN units with incorporated Layer Normalization (like [this](https://github.com/pfnet/chainer/blob/4df382824b6ff95a012643b7aacbc9ad3f738887/chainer/links/connection/zoneoutlstm.py)) are not included in this PR. After this PR is merged, I will begin to make them.
> Add layer normalization

- tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py
Experimental feature warning is not helpful for test.
> Suppress experimental feature warnings in test

- cupy/cuda/memory.pxd
- cupy/cuda/memory.pyx
- tests/cupy_tests/cuda_tests/test_memory.py
This PR provides appropriate function name (`free_all_blocks` instead of `free_all_free` ).
`PinnedMemoryPool` already use that name.
https://github.com/pfnet/chainer/blob/8fb2902a852bfa2755da71fe6e394bbc0dbfd613/cupy/cuda/pinned_memory.pxd#L46
> Fix memory API

- examples/cifar/README.md
- examples/cifar/models/VGG.py
- examples/cifar/train_cifar.py
Chainer already has dataset loaders for CIFAR-10 and CIFAR-100 but no corresponding examples. This PR adds an example to train a convolutional neural network on either of these datasets.
> Add CIFAR-10/100 convnet example

- chainer/functions/__init__.py
- chainer/functions/evaluation/r2_score.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/evaluation_tests/test_r2_score.py
I implemented the r2_score function that calculates R^2(coefficient of determination) regression score function.
As of now, the code is compatible with scikit-learn, only when the "sample_weight" argument is set to "none". 
Is this argument necessary for chainer? If necessary, I will implement the changes.
Additionally, I would like to know whether the type of this argument is Variable or ndarray?
> Implementation of r2_score function

- chainer/links/normalization/layer_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py
Add size(an optional parameter) in ``__init__()`` as the discussion in [pull#1950](https://github.com/pfnet/chainer/pull/1950)
> Add parameter size for LayerNormalization

- tests/cupy_tests/testing_tests/test_helper.py
It looks that `assert_raises_regexp` doesn't support `with` statement?
https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_raises_regex.html
> Use callable_obj argument

- .travis.yml
- chainer/functions/loss/softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
This PR adds an option to softmax_cross_entropy function for weighting the softmax cross entropy loss with a constant vector.
> Add constant weights argument to softmax_cross_entropy function

- .travis.yml
- cupy/core/core.pyx
- cupy/core/elementwise.pxi
I inserted explicit casts to avoid cython 0.25.2 problem.
fix #1983
> Insert explicit cast for cython 0.25.2

- tests/chainer_tests/datasets_tests/test_cifar.py
Test loading the cifar-10 and cifar-100 datasets; test caching them to an `.npz` file.
These tests run slowly. When https://github.com/pfnet/chainer/issues/1514 is resolved, they should be marked as slow.
> Unit tests for cifar dataset loading.

- chainer/links/connection/inceptionbn.py
I got an exception while ```stride=2``` and ```pooltype='max'``` was passed to ```chainer.links.InceptionBN```. The detail of the exception is as follows.
```shell
File "/path/to/python/lib/site-packages/chainer/links/connection/inceptionbn.py", line 129, in __call__
y = concat.concat(outs, axis=1)
File "/path/to/python/lib/site-packages/chainer/functions/array/concat.py", line 64, in concat
return Concat(axis=axis)(*xs)
File "/path/to/python/lib/site-packages/chainer/function.py", line 189, in __call__
self._check_data_type_forward(in_data)
File "/path/to/python/lib/site-packages/chainer/function.py", line 280, in _check_data_type_forward
type_check.InvalidType(e.expect, e.actual, msg=msg), None)
File "<string>", line 2, in raise_from
chainer.utils.type_check.InvalidType: 
Invalid …
```
> Output size mismatch in InceptionBN

- tests/chainer_tests/datasets_tests/test_cifar.py
The current branch fails tests due to ``test_cifar.py``
> Fix self.assertEqual() in test_cifar.py

- chainer/utils/experimental.py
I found a doctest in the document of `chainer.utils.experimental` raised the following errors, but they were not detected by Jenkins because they were grasped. This PR fixed the doctest.
> Fix doctest of chainer.utils.experimental

- tests/chainer_tests/datasets_tests/test_cifar.py
mock object does not have called_once_with method.
related to #2009
> Fix mock method

- chainer/optimizer.py
As I reported in my issue #1946
I found checking cuda.available is not enough to use cuda kernels.
So I create this work-around that checks not only cuda availability but also GPU usage.
> fix optimizer add-hooks with cuda kernels

- examples/imagenet/train_imagenet.py
The dtype of `mean` is `numpy.float32`.
Division operation is slow.
> Improve imagenet example performance

- cupy/cuda/cupy_cudnn.h
I fixed installation failure on Windows.
Visual Studio doesn't support `#if not` directive.
I know Chainer doesn't support Windows, but I don't think `#if not` is C++ standard.
I fixed to use `#if !` instead of it.
Here is a part of error messages I got when installing Chainer 1.19.0 by `pip install chainer`.
`not` of `#if not defined(CUPY_NO_CUDA) && (CUDNN_VERSION >= 5000)` is not considered as a legal preprocessor directive and causes error.
My Environment:
* WIndows 10 (64-bit)
* Python 2.7.11 :: Anaconda 4.0.0 (64-bit)
```
c:\users\daiki.sannou\appdata\local\temp\pip-build-slnu3t\chainer\cupy\cuda\cupy_cudnn.h(595) : warning C4067: プリプロセッサ ディレクティブの後に余分な文字がありました - 改行が必要です
cupy\cuda\cudnn.cpp(3662) : error C3861: 'cudnnAddTensor_v3': 識別子が見つかりませんでした
cupy\cuda\cudnn.cpp(4319) : error …
```
> Fix installation failure on Windows.

- chainer/functions/activation/relu.py
- chainer/functions/activation/sigmoid.py
- chainer/functions/activation/tanh.py
`activation_forward` calls `ascontiguousarray`.
If input array is not c contiguous, Chainer uses ElementwiseKernel to reduce memory usage and calculation time.
> Check contiguous to reduce memory usage

- chainer/functions/connection/n_step_lstm.py
In Cudnn v5 example code, use `cudnnSetFilterNdDescriptor`.
I fix NStepLSTM code because it uses `create_tensor_nd_descriptor`.
I think it should use `create_filter_descriptor` as CUDNN Example v5.
> Use cudnn.create_filter_descriptor

- tests/chainer_tests/training_tests/test_extension.py
- tests/chainer_tests/training_tests/test_trainer.py
This PR adds tests for how extensions are executed (in response to issue #2006)
What this test checks:
- An extension inheriting `extension.Extension` is properly called and finalized.
- An extension created by `make_extension` is properly called and finalized.
- Two extensions created by `make_extension` are executed in the correct order when the default priority is used.
- Two extensions created by `make_extension` are executed in the correct order when the priorities are specified in `make_extension`.
Because there are many ways to set configurations of an extension (specifying in `trainer.extend`, specifying in `make_extension`, and having configs as class members of an extension), testing all possible paths in a clean test code is difficult.  It might be a good idea to change the …
> Add tests for  how extensions are executed (issue #2006)

- chainer/functions/pooling/max_pooling_2d.py
- chainer/functions/pooling/max_pooling_nd.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
`MaxPooling2D.backward_cpu()` causes an error when I call the method more than once.
You can reproduce the error by the following code:
```
from chainer import functions as F
x = np.ones((1, 1, 4, 4), dtype=np.float32)
h = F.max_pooling_2d(x, 2)
h.grad = np.ones_like(h.data)
h.backward()
try:
h.backward()
except IndexError as e:
print e  # index 16 is out of bounds for axis 1 with size 16
try:
h.backward()
except IndexError as e:
print e  # index 24 is out of bounds for axis 1 with size 16
```
We expect the code will print nothing, but the message as the comment will be shown.
The actual error message is like this:
```
File "C:\Users\sakurai\Anaconda2\lib\site-packages\chainer\functions\pooling\max_pooling_2d.py", line 91, in backward_cpu
gcol[indexes] = gy[0].ravel() …
```
> Fix max pooling backward cpu

- chainer/training/updater.py
Learning with GPU,  it is necessary to execute model.to_gpu() explicitly for StandardUpdater. (Otherwise we will get an array type error).
However, using ParallelUpdater, calling model.to_gpu() causes an CUDA error.
Since this behavior is difficult to understand, I think that StandardUpdater should also call model.to_gpu() automatically.
> call model.to_gpu() in StandardUpdater

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
This PR fixes a bug in cupy.ndarray.astype that does not handle conversion between `np.dtype('q')` and `np.dtype('l')`. 
A simple failing case is as follows. The assertions pass for NumPy, but fails for CuPy.
```python 
import cupy
def check_dtype_type(xp):
x = xp.array([1,2,3], np.dtype('q'))
assert x.dtype.type != np.dtype('l').type
assert x.dtype.type == np.dtype('q').type
xl = x.astype(np.dtype('l'))
assert xl.dtype.type == np.dtype('l').type
assert xl.dtype.type != np.dtype('q').type
check_dtype_type(np)
check_dtype_type(cupy)
```
This happens because equality operator is True for objects of type `numpy.dtype` (e.g. `x.dtype`, `np.dtype('q')`), but fails for type objects (`np.dtype('q').type`):
```python
>>> np.dtype('l') == np.dtype('q')
True
>>> …
```
> Make astype handle conversion b/w np.longlong and np.int64

- cupy/core/core.pyx
- docs/source/cupy-reference/difference.rst
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
Related to #1919 which the reviewer and I concluded unnecessary addition to API.
In this PR, I modified `ndarray.__setitem__` to accept argument `slices` with following items.
+ one integer array
+ combination of basic and an integer array
I did not support multiple integer arrays in `slices` in this PR, but I am planning to send PR that supports them.
Mechanism to handle one dimensional array is same as #1919.
The part of the code that processes `slices` is mostly same as #1863.
> make ndarray.__setitem__ to handle one integer array

- cupy/cuda/compiler.py
- cupy/cuda/runtime.pyx
This PR is a simple fix for deadlock issue on multi-threaded application.
I added "with nogil" to the cudaStreamAddCallback API call and I moved mod.load(cubin) outside the file lock. My application needs this fix to make it work.
Maybe we should add "with nogil" to all CUDA API call but I'm not sure what influence they have.
> Fix deadlock issue on multi-threaded application

- docs/source/reference/core/dataset.rst
- docs/source/tutorial/recurrentnet.rst
I found two typos where `concat_examples` are wrongly denoted as `concat_example`. This PR fixes them.
> Fix typo (concat_example)

- cupy/__init__.py
- cupy/core/core.pyx
- cupy/ext/__init__.py
- cupy/ext/scatter.py
- docs/source/cupy-reference/ext.rst
- docs/source/cupy-reference/overview.rst
- docs/source/cupy-reference/routines.rst
- tests/cupy_tests/core_tests/test_ndarray_scatter.py
- tests/cupy_tests/ext_tests/test_scatter.py
Merge after #2040.
Related to #1920. I found the interface of `scatter_add` in #1920 to be insufficient for implementing backward pass of `chainer.Variable.__getitem__` (#2042).
This implements the function discussed in #2042.
This PR adds
+ `scatter_add` that handles one integer array
+ `scatter_add` that handles basic indexing
+ `scatter_add` that handles combination of basic indexing and an integer array.
This does not support slices with multiple integer arrays.
> Add cupy.scatter_add with interface identical to ndarray.__setitem__

- chainer/functions/noise/dropout.py
- tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
Dropout object always makes new random mask when `__call__` method is called. For forget function, I fixed this behavior. I mean, with this patch, Dropout object checks if it has a random mask . If it has, it uses the old mask and doesn't make a new random mask.
> Make Dropout object immutable

- chainer/training/extensions/plot_report.py
- examples/mnist/train_mnist.py
This PR makes the plots created by PlotReport extension richer and adds this extension to the trainer in the MNIST example to show how to use this extension.
This PR actually adds legend to plots, and a label to x-axis, and grid to the figure.
After running `examples/mnist/train_mnist.py`, the below two plots will be saved in the result dir.
> Improve PlotReport

- tests/cupy_tests/padding_tests/test_pad.py
Old numpy does not accept array_like. [1.9](https://docs.scipy.org/doc/numpy-1.9.3/reference/generated/numpy.pad.html) [1.10](https://docs.scipy.org/doc/numpy-1.10.4/reference/generated/numpy.pad.html)
> Fix test for cupy.pad by passing lists instead of passing ndarrays

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
'assert_called_once' is not a method, instead directly check the 'call_count' property. Use 'autospec'.
Related to https://github.com/pfnet/chainer/pull/2011/
> Fix test code for convolution_2d

- cupy/core/core.pyx
I changed name of kernels used for `scatter_*` to `cupy_scatter_*`.
These names are more consistent with other kernels called by CuPy (e.g. `cupy_take`).
> Change name of kernels for scatter_* to be more consistent with other kernels

- cupy/creation/basic.py
- tests/cupy_tests/creation_tests/test_basic.py
This PR supports order option for `cupy.empty`.
> Add order option to cupy.empty

- cupy/creation/basic.py
- tests/cupy_tests/creation_tests/test_basic.py
This PR adds order option to `cupy.zeros`.
Also, I changed `cupy.zeros` to stop calling `cupy.empty`. This is more efficient and simpler.
> Add order option to cupy.zeros

- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
- tests/cupy_tests/core_tests/test_ndarray_scatter.py
This PR changes a decorator that parameterized combination of dtypes to `for_dtypes_combination`.
This is better because you can speedup tests by reducing number of combinations to tests. Also, you can test all combinations with `for_dtypes_combination` by setting an environment variable properly.
> use for_dtypes_combination decorator for array indexing tests

- cupy/__init__.py
Fix to print the original error when cupy is not successfully built.
> Fix to print the original error when cupy is not successfully built

- cupy/binary/packing.py
- tests/cupy_tests/binary_tests/test_packing.py
`packbits` and `unpackbits` of NumPy <= 1.11 have bugs against empty arrays (see https://github.com/numpy/numpy/issues/8324). I intentionally implemented this behaviour in CuPy's counterparts. These bugs are fixed at NumPy 1.12 (https://github.com/numpy/numpy/pull/8327), and thus this PR also fixes the 'bugs' in CuPy.
> Fix the simulated bug behaviour of packbits

- tests/cupy_tests/math_tests/test_arithmetic.py
numpy 1.12.0 raises when calculating negative power of integers.
```python
numpy.power(numpy.ones((), dtype=numpy.int32), -1)
```
> Fix test_arithmetic for numpy 1.12.0

- chainer/cuda.py
- tests/chainer_tests/test_cuda.py
This PR will make `cuda.get_array_module` support `Variable` arguments so that it will return the array module of `Variable.data`. It will also add tests for `cuda.get_array_module`.
> Make cuda.get_array_module support Variable

- cupy/testing/__init__.py
- cupy/testing/helper.py
- docs/source/cupy-reference/testing.rst
- tests/cupy_tests/creation_tests/test_basic.py
Merge after #2103, #2104.
This PR adds a decorator that parameterizes tests with order options.
In addition to that, the new decorator is used to simplify tests written for `cupy.empty` and `cupy.zeros`.
> Add decorators to parameterize tests with order arg

- chainer/training/extensions/plot_report.py
It's a very trivial PR. It adds `marker` and `grid` options to PlotReport class to enable to choose the axis grid on/off and the marker style. If `None` is given to `marker`, it draws the graph with no markers.
> Add marker and grid attributes to PlotReport

- chainer/training/extension.py
- chainer/training/trainer.py
- tests/chainer_tests/training_tests/test_trainer.py
This PR allows adding a lambda function as an extension,
resulting in simpler coding for simple extensions such as printing some values for debugging.
Example usage:
...
trainer.extend(lambda x: print(model.accuracy.data), trigger=(1, "iteration"))
...
> allow adding lambda functions as an extension

- cupy/cuda/cudnn.pxd
- cupy/cuda/cudnn.pyx
- cupy/cuda/cupy_cudnn.h
This PR adds cudnn wrappers around FindConvolution* functions.
cuDNN v3 and above support `cudnnFindConvolution*Algorithm`, and cuDNN v5 and above support `cudnnFindConvolution*AlogrithmEx`.
On implementation, I could not find a Cython feature to avoid a flake8 error at https://github.com/yuyu2172/chainer/blob/28eca7525e663ee9f25a6655cfecf1cca6826043/cupy/cuda/cudnn.pxd#L13.
The error is 
```
./cupy/cuda/cudnn.pxd:13:9: E125 continuation line with same indent as next logical line  
```
Basically, the error says that I should not change lines in the middle of an expression. Usually, in Python, there is a workaround, but I could not find any for this cython code.
Also, I needed to change lines because the expression exceeds the 80 characters limit.
I would like to know if it is fine to use …
> Add FindConvolution* wrappers to cupy

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_get.py
fix #2141.
It crashed when array was not c_contiguous. The test case reproduces that situation.
> Fix cupy.ndarray.get to work when device id and array id mismatch

- chainer/functions/activation/sigmoid.py
This PR improves the documentation of the element-wise sigmoid logistic function by adding a usage example.
Adding plots using sphinx extensions will be left for future PRs :).
EDIT: previously `[WIP] Add example usage to docstrings of functions and links`:
PRs welcome!
Part of improving documentaion effort. See also https://github.com/pfnet/chainer/issues/1867
TODO (finish this list):
Functions:
Links:
> Improve doc of element-wise sigmoid logistic function

- cupy/core/core.pyx
When x.size is zero, x.device is None.
> Fix cupy.ndarray.get for arrays with size 0

- chainer/initializers/__init__.py
This PR removes `scale` option from `init_weight` and `_get_initializer`, which is discussed in #2020. We should feed scaled initializer instead.
Some links uses this option. As this dependency was removed in #2020, please merge the PR before this PR.
> Remove scale option from init_weight and _get_initializer

- chainer/__init__.py
- chainer/configuration.py
- chainer/function.py
- chainer/gradient_check.py
- tests/chainer_tests/test_configuration.py
This PR implements a unified way of managing the global/thread-local configuration of Chainer. As a first step, it implements the core part of configuration (GlobalConfig and LocalConfig), and moves some easy configurations (debug mode, type check, and backprop mode) to this configuration tool. The main features are:
- We can easily add a new entry just by setting an attribute to `chainer.global_config`.
- `with chainer.using_config('XXX', yyy):` lets us change the thread-local configuration temporarily.
- We can diagnose the current configuration with `chainer.config.show()`.
I did not finish #2048 by this PR; train/test mode and use_cudnn flag are not moved to this configuration yet, because both affect a wide range of codes in Chainer and its examples, and I want to separate PRs for …
> Unified configuration

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
This PR supports boolean array for `cupy.ndarray.__setitem__`.
+ It supports boolean array indexing on axes (e.g. `a[:, np.array([True, False])]`).
+ It does not support combination of boolean arrays (e.g. `a[np.array([True, False]), np.array([False, True])]`).
Also, I changed name of internal function `_boolean_array_indexing` which was used for boolean array indexing of `__getitem__` to `_getitem_mask`. I did so because the name was vague, and it needed to be distinguishable from functions for `__setitem__`.
> Support boolean array for cupy.ndarray.__setitem__

- cupy/core/core.pyx
This PR optimizes `__getitem__` when slices contain boolean array.
I did 4 optimizations.
+ stop using flatten and use ravel instead (no DtoD memcpy)
+ avoid unnecessary `cupy_subtract` (one less kernel call)
+ stop calling `cupy.max` on result of scan. The maximum of scan is always stored at the last index.
+ use `numpy.int32` for input and output of scan whenever possible. It is faster to compute than the case when they are `numpy.int64`.
I confirmed that all the optimizations contribute to speed up.
You can benchmark speed using the following code.
The average speed of calling a boolean array indexing improved by 6x.
Before optimizations, it took 56.68 ms.
After optimizations, it took 9.38 ms.
All experiments are conducted on CUDA8.0, TitanX Pascal.
```python
import cupy
import numpy …
```
> Optimize __getitem__ for boolean array indices

- chainer/functions/pooling/unpooling_2d.py
Generally speaking, `isinstance` should not be used if possible because it is slow in some case. This PR avoid to use it to determine an array module used.
> Do not use isinstance to select array module

- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
It is natural that pooling functions (`max_pooling` and `average_pooling`) should be the left inverse of the unpooling function (i.e. `pooling(unpooling(x)) = x`). This PR adds unit tests that checks this consistency.
I found this equality does not hold in some combination of parameters (window size(`ksize`), stride, and pad). Although such a consistency is natural, I am not certain it should hold for any parameters other than the default one. It is a problem of how we determine the specification of these functions.
> Add unit test asserting that pooling are (left) inverse of unpooling

- tests/chainer_tests/initializer_tests/test_init.py
This PR adds unit tests for `chainer.initializers._get_initializer`. It does not test `scale` option as I expect this option will be removed in v2 (as I did in PR #2164)
> Add unit tests for `_get_initializer`

- chainer/functions/array/split_axis.py
- tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
> Make force_tuple True by default in split_axis to provide consistent return type.

- cupy/core/__init__.py
- cupy/core/core.pyx
- cupy/manipulation/kind.py
This PR moves`cupy.asfortranarray` under cupy.core` just like `cupy.ascontiguousarray`.
Also, the function now detects the case when copy is not necessary. `cupy.ascontiguousarray` does this conditional handling too.
> Move asfortranarray to core

- chainer/functions/activation/clipped_relu.py
- chainer/functions/activation/relu.py
- chainer/functions/activation/sigmoid.py
- chainer/functions/connection/linear.py
- functions/activation/relu
- functions/activation/clipped_relu
Changed the order or the examples to the bottom of the docstrings:
- functions/activation/sigmoid
- functions/connection/linear
> Improve docs of clipped_relu and relu, minor change on sigmoid and linear

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
This PR supports multiple integer arrays for `cupy.ndarray.__setitem__`. I rebased #1928.
I had to change interface of an internal function `_scatter_op_single` to support broader inputs.
After the change,  `_scatter_op_single` supports the input below. Also I left a comment in the code.
```
a.shape= (shape_0, ..., shape_{li-1}, shape_li, ..., shpe_ri, ..., shape_{a.ndim-1})
indices:  an integer array indexing axes from axis_li to axis_ri
li: id of the first axis that get indexed
ri: id of the last axis that get indexed
```
For example, when working on `a[[1,0], [0, 1]], a.shape=(2, 3, 4)`, you have `li=0, ri=1, indices=[3, 1]`.
Originally, `_scatter_op_single` only supported the special case of `li=ri`. In that case, I had to call `a._reshape` before passing to `_scatter_op_single` when …
> Support multiple integer arrays for cupy.ndarray.__setitem__

- cupy/core/__init__.py
- cupy/core/core.pyx
- cupy/manipulation/split.py
I optimized array_split method with Cython. The original implementation calls `__getitem__` method many times. I removed this call and made views manually, and it is simple enough.
related to #1492
> Implement array_split with cython and optimize it

- cupy/core/core.pyx
- cupy/creation/from_data.py
- tests/cupy_tests/core_tests/test_elementwise.py
- tests/cupy_tests/creation_tests/test_from_data.py
merge after #2176.
This PR adds order option to `cupy.ndarray.copy`.
> Add order option to cupy.ndarray.copy

- docs/source/cupy-reference/ufunc.rst
This PR adds to the documentation that `cupy.scatter_add` can substitute `add.at`.
> Add to the documentation that cupy.scatter_add can substitute add.at

- cupy/core/core.pyx
- tests/cupy_tests/manipulation_tests/test_shape.py
Raise same exception as numpy.
It's better to put an error message than mere assertion violation.
> Helpful error message with invalid cupy.reshape.

- cupy/core/core.pyx
- cupy/ext/scatter.py
- tests/cupy_tests/core_tests/test_ndarray_scatter.py
merge after #2099
This PR supports boolean array indices for `cupy.scatter_add`.
> Support boolean array indices for scatter_add

- chainer/iterators/serial_iterator.py
When a user uses `numpy.ndarray` as dataset, `SerialIterator` makes corrupted batch here. 
fixes #2160
> Use extend method to show understandable error message

- cupy/core/elementwise.pxi
Fix the difference between Python int and C long in chainer_tests.
> Fix 'OverflowError: Python int too large to convert to C long'

- chainer/variable.py
Even if CUDA is available, cudaGetDevice() can return
cudaErrorNoDevice when CUDA_VISIBLE_DEVICE is set to -1.
In such case, this has resulted in CUDARuntimeError.
> Ignore cudaErrorNoDevice on making device backup

- chainer/dataset/__init__.py
- chainer/dataset/convert.py
- docs/source/reference/core/dataset.rst
- tests/chainer_tests/dataset_tests/test_convert.py
I made `to_device` method public for users who want to make a custom converter method for `Updater`. I sometimes copy this method to my code by hand.
> Make to_device method public

- cupy/core/core.pyx
`ndarray.ctypes.data_as` is slower than `ndarray.ctypes.get_as_parameter`.
```
% python -m timeit -s 'import numpy,ctypes;a = numpy.zeros(10) ' 'a.ctypes.data_as(ctypes.c_void_p)'
100000 loops, best of 3: 2.95 usec per loop
% python -m timeit -s 'import numpy,ctypes;a = numpy.zeros(10) ' 'a.ctypes.get_as_parameter()'
100000 loops, best of 3: 1.9 usec per loop
```
> Improve usage of ndarray.ctypes

- chainer/link.py
- tests/chainer_tests/test_link.py
Fix https://github.com/pfnet/chainer/issues/2199
> Fix error handling when serializing uninitialized parameters

- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/functions/connection/dilated_convolution_2d.py
Are there any reasons for using for loop?
In my environment, `tensordot` is faster. (Python 3.5, GTX 760, Ubuntu 16.04)
Here is test code.
```python
import cupy
import time
from chainer.utils import conv
sy, sx = 1, 1
ph, pw = 0, 0
x = cupy.arange(300000).reshape(10, 3, 100, 100)
col = conv.im2col_gpu(x, 100, 100, sy, sx, ph, pw)
W = cupy.arange(90000).reshape(3, 3, 100, 100)
out_c, _, kh, kw = W.shape
n, c, h, w = x.shape
out_h = conv.get_conv_outsize(h, kh, sy, ph)
out_w = conv.get_conv_outsize(w, kw, sx, pw)
start = time.time()
W_mat = W.reshape(out_c, -1)
col_mats = col.reshape(n, -1, out_h * out_w)
y = cupy.empty((n, out_c, out_h, out_w), dtype=x.dtype)
y_mats = y.reshape(n, out_c, -1)
for i in range(n):
y_mats[i] = W_mat.dot(col_mats[i])
end = time.time() - start
print(end)
start = …
```
> Not to use for loop in convolution function

- cupy/core/core.pyx
- tests/cupy_tests/manipulation_tests/test_join.py
I fixed concat method to use memory-view. It is faster than list and vector.vector. In my small profile result, transpose_sequence is 25% faster than the original.
> Use memory view in concat

- chainer/function.py
- chainer/utils/type_check.py
I used thread-local variable to check a label of a current function.
fix #2081
> Insert function label in initializer of InvalidType exception for readable stack-trace

- cupy/random/distributions.py
- tests/cupy_tests/random_tests/test_distributions.py
Like numpy.random.normal.
Please see https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html .
> Support float array type loc and scale for cupy.random.normal

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
This PR adds support for `cupy.ndarray.__getitem__` to handle a boolean mask array even when the mask's shape and array's shape differ.
Most of the implementation follows/extends that of `_scatter_op_mask_single`.
Note: In addition to that, here are some other things that are added.
+ consistency among names of the masking function for getitem and setitem
+ add tests for cupy.__getitem__ that uses `cupy.ndarray` indices. I restored tests that were removed in #1912.
> Support mask for cupy.ndarray.__getitem__ when mask and array's shape differ

- docker/python2/Dockerfile
- docker/python3/Dockerfile
Add python3 version Dockerfile with a minor optimization(`--no-install-recommends`)
(expecting python3.4.3 by vanilla apt)
Public docker image supports only python2
* If accept this PR, don't forget to change build settings on docker hub, file location and explicit tagging
* Maybe it is better to support not only python3.4.3 but python3.5+ and python3.6+ individually
> Support python3 on docker

- chainer/serializers/hdf5.py
- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
- tests/chainer_tests/serializers_tests/test_npz.py
I added `strict` option to deserializers. It doesn't break compatibility.
fix #2053 
related to #2171
> Deserializer strict option

- cupy/cuda/compiler.py
Sometimes `makedirs` is failed.
This PR fixed it.
> Fix makedirs checking

- docs/source/reference/functions.rst
Documentations for `space2depth` and `depth2space` were not accessible.
This PR fixes them.
> Include space2depth and depth2space to docs

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_scatter.py
Merge after #2175 and #2126.
This PR supports multiple integer array indexing for `cupy.scatter_add`.
> Support multiple integer array indexing for cupy.scatter_add

- cupy/core/core.pyx
sgemm is slow to calculate inner product between two vectors. Instead I used prod and sum. In my test, this patch is 10 times faster than the original. @soskek reported this problem.
> Optimize dot method for two vectors

- tests/chainer_tests/serializers_tests/test_hdf5.py
This PR is a suggestion. If a maintainer thinks it's faster to self-implement it, he can do this.
The `LogReport` has the function
```python
def serialize(self, serializer: HDF5Deserializer):
if isinstance(serializer, serializer_module.Serializer):
log = json.dumps(self._log)
serializer('_log', log)
else:
log = serializer('_log', '')
import pdb; pdb.set_trace()
self._log = json.loads(log)
```
that requires to store and load strings with the serializer. Therefore there should also be a test for that.
> TestHDF5Deserializer: add test_string

- tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
Fix #2109.
This PR adds a test to check consistency of backward methods of 2D and ND pooling layers:
- max pooling layer
- average pooling layer
> Add consistency check of backward propagation between 2D and ND pooling functions

- docs/source/tips.rst
This PR fixes a typo: s/OpneBLAS/OpenBLAS/
> Fix typo in tips.rst

- cupy/__init__.py
Fix a test introduced in #2291 when cupy is not installed.
Ref: #2306
> Raise a correct exception when attempting to import broken CuPy

- chainer/links/connection/inceptionbn.py
It's never used but causes flake8 error.
> Remove importing configuration from inceptionbn.py

- chainer/configuration.py
- docs/source/reference/core.rst
- docs/source/reference/core/configuration.rst
- docs/source/reference/core/debug.rst
- docs/source/tutorial/basic.rst
This PR adds a documentation for `chainer.config` and modifies some existing docs related to any configuration entries (e.g. debug mode document, tutorial).
> Documentation of configuration

- tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
I found a typo in `tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py`
> fix typo in test_sigmoid_cross_entropy

- chainer/functions/activation/lstm.py
I fixed the LSTM document.
`L.Linear` is preferable to `F.Linear` because it has parameters (weight and bias).
> L.Linear is preferable to F.Linear in LSTM document.

- tests/cupy_tests/math_tests/test_matmul.py
The original test sometimes fails.
> Use shaped arange to avoid random behavior

- chainer/functions/activation/crelu.py
- chainer/functions/activation/elu.py
- chainer/functions/activation/sigmoid.py
- chainer/functions/activation/tanh.py
- chainer/functions/array/broadcast.py
- chainer/functions/array/concat.py
- functions/activation/crelu
- functions/activation/elu
- functions/activation/tanh
- functions/array/broadcast (including broadcast_to)
- functions/array/concat
I am not sure that this example for elu is good or not. We need a figure in the future.
Minor change on:
- functions/activation/sigmoid
I found the shape description of this is small letter (s_n).
> Improved doc of crelu, elu, tanh, broadcast, broadcast_to, concat

- cupy/__init__.py
- cupy/creation/ranges.py
- docs/source/cupy-reference/creation.rst
- tests/cupy_tests/creation_tests/test_ranges.py
This PR adds cupy.meshgrid.
*sparse* option is not supported in this PR.
> Add cupy.meshgrid

- chainer/iterators/multiprocess_iterator.py
- chainer/iterators/serial_iterator.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_serial_iterator.py
`epoch_detail` takes wrong value if the iterator is not repeated.
Here is an example.
```
dataset = [1, 2, 3]
it = chainer.iterators.SerialIterator(dataset, 2, repeat=False)
it.next() # [3, 1]
it.next() # [2]
it.epoch # 1
it.epoch_detail # 2.0
```
I think `epoch_detail` should be 1.0 in this case.
> fix epoch_detail

- docs/source/cupy-reference/difference.rst
doctest does not check `::` snippets. I replaced them with doctest format and fixed the code.
> Check code snippet using doctest

- .gitignore
.idea is config files directory which pycharm automatically creates
This PR is to ignore .idea directory from git commit.
> ignore .idea directory for pycharm users

- chainer/variable.py
- tests/chainer_tests/test_variable.py
Rel. #2072.
I've modified `Variable` class to share its actual data and gradient arrays across its copied instances including the initialized/uninitialized state. The code may not be complete yet, but would be enough to get the idea.
I guess this behavior from the docstring of `link.copy` method:
The whole hierarchy rooted by this link is copied. The copy is
basically shallow, except that the parameter variables are also
shallowly copied. It means that the parameter variables of copied one
are different from ones of original link, while they share the data and
gradient arrays.
If I had some misunderstanding and the copied Variable instances should still have mutually independent data and gradient arrays, please point it out. If what I guess is right and the change is reasonable, I will …
> Make copied Variable instances to share its data and gradient arrays.

- chainer/variable.py
- tests/chainer_tests/test_variable.py
This PR adds a reshape method to `chainer.Variable`.
The interface follows that of `numpy.ndarray.reshape`.
This PR is useful in a situation when you want to declare reshape at the end of a line rather than at the beginning. A simple example to demonstrate the visual difference is as follows.
```python
import numpy
import chainer
x = chainer.Variable(numpy.array([1,2,3,4]))
y = F.reshape(F.tile(x, 4), (4, 4))
y = F.tile(x, 4).reshape(4, 4)
```
> Add reshape method to chainer.Variable

- chainer/links/model/vision/vgg.py
It seems that the ReLU operator in the final layer of VGG is not needed.
> Remove unnecessary ReLU operator in VGG16Layers

- chainer/training/extensions/evaluator.py
- chainer/training/updater.py
- tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
- tests/chainer_tests/training_tests/test_updater.py
Now we don't need to wrap `ndarray` with `Variable` because function automatically wrap `ndarray`, and we now have `no_back_prop_mode`. This fix makes dataset more flexible. Without this patch, `dataset` must be a list of tuples of arrays, a list of dicts of arrays or a list of arrays, and it cannot support more structural datasets. With the patch, a user can use any types of datasets. All `ndarray`s are automatically wrapped with `Variable`.
Note that it may breaks compatibility when a user expects that arguments of links are `Variable`. For example, `assert x.data.ndim == (3,)` He need to use `Variable.ndim` in this case.
> Remove variable wrap

- chainer/links/connection/inceptionbn.py
- examples/imagenet/googlenetbn.py
BatchNormalization (http://docs.chainer.org/en/stable/_modules/chainer/links/normalization/batch_normalization.html#BatchNormalization) can set test-mode on `__call__(self, x, test=False)`,
but InceptionBN (http://docs.chainer.org/en/stable/_modules/chainer/links/connection/inceptionbn.html#InceptionBN) has a difference interface `__call__(self, x)` and stores test-mode as a property.
The difference confuses us.
> Fix: InceptionBN.__call__

- chainer/variable.py
- tests/chainer_tests/test_variable.py
In a similar intent as #2236, this PR adds a function to `chainer.Variable` for convenience.
> Add transpose method to chainer.Variable

- chainer/initializer.py
- tests/chainer_tests/test_initializer.py
I fixed `fan_out` in initializer.py that is different from other frameworks.
I think `get_fans` is based on keras implementation and keras used `shape[0]` as `fan_out`, but it is fixed in https://github.com/fchollet/keras/pull/2252 
Other implementation of `fan_out`:
- Caffe  
https://github.com/BVLC/caffe/blob/master/include/caffe/filler.hpp#L193
- Tensorflow  
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/initializers.py#L126
> Fix fan_out that is different from other frameworks.

- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_serial_iterator.py
I added some tests for serialization of `SerialIterator` and `MultiprocessIterator`.
> Add tests for iterator serialization

- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
> Fix indentation of unit tests of Deconvolution2D

- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
Enable deterministic mode on cuDNN v3.
This PR also fixes test cases around https://github.com/pfnet/chainer/blob/db7aa37fa2e0fe95a3a3f6f06b2cefcb6441fcb5/tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py#L85.
> Enable deterministic mode on cuDNN v3

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
This resolves issue #2366.
Three bugs are fixed
+ index is `[]`
+ index is `[[]]`
+ index is a boolean array of size 0
> Fix error with advanced indexing when a zero length array-like is the index

- chainer/initializers/__init__.py
- chainer/initializers/constant.py
- chainer/link.py
- chainer/links/connection/convolution_2d.py
- chainer/links/connection/deconvolution_2d.py
- chainer/links/connection/dilated_convolution_2d.py
- chainer/links/connection/linear.py
- chainer/links/connection/lstm.py
- chainer/links/normalization/layer_normalization.py
- chainer/optimizer.py
- chainer/variable.py
- tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
- tests/chainer_tests/test_link.py
- tests/chainer_tests/test_variable.py
Fix #1967. It includes the following changes:
- Variable supports uninitialized state, in which the data array is None.
- Link supports uninitialized variable as a parameter. Link.add_uninitialized_param and Link.has_uninitialied_params are **removed**.
- The implementations of links that use parameter shape placeholder (Convolution2D, Deconvolution2D, DilatedConvolution2D, LayerNormalization, Linear, and LSTM) are updated to use the new uninitialized parameters. The interface of them is not changed.
The two methods of Link are removed. I was first thinking about leaving them with deprecation warning, but I found that the existing code is broken even if I leave them (because the way of initializing the uninitialized parameter is changed: we had to call `link.add_param('param', shape)` in …
> Support uninitialized variable and use it for uninitialized parameters

- chainer/initializers/normal.py
`cupy.random` supports `dtype` argument because cuRAND has float32 version of API. I fixed initializer to use lower precision API.
related to #2290
> Set dtype option for cupy.random in initializer

- cupy/__init__.py
- cupy/manipulation/rearrange.py
- docs/source/cupy-reference/manipulation.rst
- tests/cupy_tests/manipulation_tests/test_rearrange.py
This PR implements cupy.flip and cupy.rot90 functions. Since numpy.flip is new feature of NumPy v1.12, the test code expect to run with NumPy v1.12 or later.
> Implement flip and rot90

- cupy/core/core.pyx
- tests/cupy_tests/creation_tests/test_from_data.py
When `copy=False` in array method, it changes shape of an original array. I fixed the method to use a view.
fix #2392
> Fix array on no copy

- chainer/links/theano/theano_function.py
As @deepali-c commented, TheanoFunction does not work with theano>=0.9 since it only supports `collections.OrderedDict` as `know_grad` argument.
https://github.com/pfnet/chainer/pull/1103#issuecomment-285270297
> Use OrderedDict for known_grad, that is only supported in theano>=0.9

- chainer/testing/condition.py
- tests/chainer_tests/testing_tests/test_condition.py
Current code calls `setup` and `teardown` twice. So, test was finished not cleanly.
> Fix repeat test

- chainer/functions/connection/embed_id.py
- chainer/utils/type_check.py
- tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
- tests/chainer_tests/utils_tests/test_type_check.py
This PR is an improvement over #2076. My apologies to making a new PR, but I mistakenly deleted the whole repository once so I cannot push to the branch used in #2076.
This version considers the case where W is a sub-class of `numpy.array` so that this case is also accepted.
> warn when numpy and cupy are used together

- chainer/functions/normalization/batch_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Fix batch normalization function to handle multi-dimensional parameters correctly and update documentation of the function to be consistent with how it is documented in the corresponding batch normalization link. Previously, the function assumed that the second dimension of the input was always the only channel dimension.
> Fix BN function channel size support

- chainer/functions/evaluation/accuracy.py
> fix typo in docstring (functions.evaluation.accuracy)

- cupy/testing/helper.py
I fixed the doctest of cupy-reference/testing.
The error is below,
```
Document: cupy-reference/testing
--------------------------------
**********************************************************************
File "cupy-reference/testing.rst", line 44, in default
Failed example:
from cupy import testing
@testing.gpu
class TestFoo(unittest.TestCase):
@testing.numpy_cupy_allclose()
def test_foo(self, xp):
xp_result = xp.zeros(10)
return xp_result
Exception raised:
File "/home/kumezawa/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "/home/kumezawa/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg/sphinx/ext/doctest.py", line 369, in compile
return …
```
> fix doctest of cupy-reference/testing

- docs/source/tutorial/type_check.rst
Before the PR, the doctest result is
```
Document: tutorial/type_check
-----------------------------
**********************************************************************
File "tutorial/type_check.rst", line 117, in default
Failed example:
utils.type_check.expect(x_type.ndim == 2)
Expected:
...
InvalidType: Expect: in_types[0].ndim == 2
Actual: 3 != 2
Got:
File "/home/kumezawa/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest default[0]>", line 1, in <module>
utils.type_check.expect(x_type.ndim == 2)
File "/home/kumezawa/dev/chainer/chainer/utils/type_check.py", line 487, in expect
expr.expect()
File …
```
> fix doctest of docs/source/tutorial/type_check

- cupy/prof/time_range.py
Before the PR, the doctest result is
```
Document: cupy-reference/prof
-----------------------------
**********************************************************************
File "cupy-reference/prof.rst", line 8, in default
Failed example:
@cupy.prof.TimeRangeDecorator()
def function_to_profile():
pass
Exception raised:
File "/home/kumezawa/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs)
File "<doctest default[0]>", line 1, in <module>
@cupy.prof.TimeRangeDecorator()
AttributeError: module 'cupy' has no attribute 'prof'
**********************************************************************
File "cupy-reference/prof.rst", line 6, in default
Failed example:
with cupy.prof.time_range('some range in …
```
> fix doctest of cupy/prof/time_range.py

- tests/chainer_tests/functions_tests/activation_tests/test_relu.py
- tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py
- tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
- tests/cupy_tests/test_cudnn.py
I splitted a test to check if cudnn is used and a test to check if expected version of API is called. The former one is for chainer test and the later is for cupy.
related to #2413
> Improve cuDNN test

- docs/source/tutorial/type_check.rst
Reverts pfnet/chainer#2434 because it leads errors on jenkins's doctest due to the version difference of Python. After this modification, Python3 makes no errors, while Python2.7 makes errors on the different description of "InvalidType".
Python3:
```
chainer.utils.type_check.InvalidType: Expect: in_types[0].ndim == 2
Actual: 3 != 2
```
Python2:
```
InvalidType: Expect: in_types[0].ndim == 2
Actual: 3 != 2
```
Python2 doesn't export the parent classes of `InvalidType`, namely, it outputs the error without `chainer.utils.type_check.`.
> Revert "fix doctest of docs/source/tutorial/type_check"

- chainer/training/updater.py
This is necessary workaround for compatibility with ChainerMN's `MultiNodeOptimizer`.
ChainerMN's `MultiNodeOptimizer` wraps an actual optimizer. There is no good reason for `MultiNodeOptimizer` to inherit `Optimizer`, as it would not use any methods nor variables of `Optimizer`. And, for some technical reasons from ChainerMN side, it is not preferable for `MultiNodeOptimizer` to inherit `Optimizer`. Therefore, this PR proposes Chainer's `Updater` to change the way to determine whether `optimizer` argument is a `dict` or not. (This is the conclusion of discussion with @beam2d -san.)
> Stop checking that optimizer is an instance of Optimizer class

- chainer/iterators/multiprocess_iterator.py
- chainer/iterators/serial_iterator.py
- chainer/training/extensions/evaluator.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_serial_iterator.py
This PR aims to improve the performance of common use cases with ChainerMN by reducing the frequency of process spawn.
In `Evaluator`, currently iterators are copied for every evaluation time. For most cases, this is not very time consuming. However, we found that this is very slow when we are using `MultiProcessIterator` with `forkserver` or `spawn` modes (c.f., https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods). Therefore, to avoid spawning new processes for each evaluation time, this PR proposes to introduce `reset` method to iterators and use it in `Evaluator`.
> Stop copying iterators for efficiency

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
This PR fixes a bug found in #2418.
> Fix Advanced indexing of Cupy's __getitem__ when an index argument is a list

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_adv_indexing.py
- tests/cupy_tests/core_tests/test_ndarray_scatter.py
This PR fixes a bug similar to #2418.
The solution is similar to #2419.
> Fix Advanced indexing of Cupy's setitem and scatter_add when an index argument is a list

- setup.py
> Stop installing chainer on python 3.5.0

- cupy/core/carray.pxi
- cupy/core/core.pxd
- cupy/core/core.pyx
- cupy/cuda/function.pyx
This PR improves performance of linear_launch() by static-typing kernel argument pointers.
One concern is that dependency from function.pyx to core.pyx is introduced,
because core.ndarray and core.Indexer must be visible to function.pyx in order to do static-typing.
In my benchmark, linear_launch() is sped up by about 30%.
> Static-type CUDA kernel argument pointers

- chainer/links/connection/lstm.py
(transported from #2287 to change the target from `master` to `_v2` branch)
The default forget bias will be better to set 1.
Let me introduce the following paper.
[An Empirical Exploration of Recurrent Network Architectures](http://jmlr.org/proceedings/papers/v37/jozefowicz15.pdf)
> Thus we recommend adding a bias of 1 to the forget gate of every LSTM in every application; it is easy to do often results in better performance on our tasks. This adjustment is the simple improvement over the LSTM that we set out to discover.
And TensorFlow's forget bias is set to 1.
[BasicLSTMCell implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py#L138)
> improve forget bias to 1

- chainer/functions/__init__.py
- chainer/functions/array/resize_images.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
This PR adds a function that resizes image like variables.
This is similar to #2272, but `resize_images` does not backpropagate to coordinate variables and has nicer API.
```python
import matplotlib.pyplot as plt
from skimage.data import astronaut
from chainer.functions import resize_images
img = astronaut().astype(np.float32)
img = np.transpose(img, (2, 0, 1))
out = resize_images(img[None], (512, 256))[0].data.transpose(1, 2, 0)
plt.imshow(out.astype(np.uint8))
plt.show()
```
> Add chainer.functions.resize_images

- tests/cupy_tests/core_tests/test_fusion.py
sqrt function in old numpy is broken. Cupy obeys newer one.
> Skip sqrt test with old numpy

- tests/cupy_tests/core_tests/test_fusion.py
itruediv between integer arrays is acceptable in NumPy 1.9. So, i fixed the test to skip this situation.
This problem can be reproduces with python3 and numpy 1.9.
> Skip itruediv test when numpy 1.9 is installed

- setup.py
Chainer and CuPy are split in version 2.
This PR helps Chainer version up.
If user has installed CuPy, Chainer install corresponding CuPy automatically.
> Set dependency for CuPy

- chainer/functions/activation/elu.py
I removed an unnecessary line in the example code.
http://docs.chainer.org/en/latest/reference/functions.html#chainer.functions.elu
> Fix typo in docstring of elu function

- chainer/functions/connection/bilinear.py
- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/convolution_nd.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/functions/connection/deconvolution_nd.py
- chainer/functions/connection/dilated_convolution_2d.py
- chainer/functions/connection/embed_id.py
- chainer/functions/connection/linear.py
- chainer/functions/connection/n_step_lstm.py
Continued from #2255.
Ths PR adds type checking codes to `functions/connection/*.py` to see if numpy and cupy are mixed (and outputs a graceful warning when they are).
I confirmed that all the related tests with @attr.gpu pass in my local environment.
> Add type check to functions/connection/*

- cupy/math/sumprod.py
- tests/cupy_tests/math_tests/test_sumprod.py
Hi,
I implement and test `cupy.cumsum` with its axis option by extending the (axis=None) version.
> cupy.cumsum:  implement its axis option

- tests/cupy_tests/core_tests/test_fusion.py
In this context, `unitest.skip` is preferable because it can report that the test is skipped.
> Use skipUnless instead of if statement

- chainer_setup_build.py
This PR follows #2423, which is already merged to the master.
In #2423, reference to nvToolsExt.h is alive even when NVTX is not found on a Windows environment and it prevents `cupy.cuda` module from being built when `check_library` function is called.
This PR removes the reference to nvToolsExt.h in such a case.
> Fix Windows NVTX support.

- chainer/functions/array/get_item.py
- tests/chainer_tests/functions_tests/array_tests/test_get_item.py
Related #2202 #2201, #2175, #2134, #2126, #2099, #2043, #1863, #1832.
Resolves issue #2042. 
This PR supports advanced indexing for `chainer.Variable.__getitem__`.
Here are lists of functionalities that are added.
+ support for integer arrays. This includes multiple integer arrays (e.g. `a[i1, i2]`) and combination of integer arrays and basic indexing (e.g. `a[i1, 2:10, i2]`).
+ support for boolean array indexing.
This PR does not support multiple boolean arrays as indexing.
> Support advanced indexing for chainer.Variable.__getitem__

- README.md
- cupy/cuda/cudnn.pxd
- cupy/cuda/cudnn.pyx
- cupy/cuda/cupy_cudnn.h
- docs/source/install.rst
This PR supports cuDNN v6.
Also, it changes argument name from `upscale` to `dilation`. Please see user guide of cuDNN v6.
> Support cuDNN v6

- chainer/function.py
- chainer/functions/activation/lstm.py
- chainer/functions/activation/prelu.py
- chainer/functions/activation/slstm.py
- chainer/functions/array/broadcast.py
- chainer/functions/array/concat.py
- chainer/functions/array/dstack.py
- chainer/functions/array/hstack.py
- chainer/functions/array/reshape.py
- chainer/functions/array/split_axis.py
- chainer/functions/array/vstack.py
- chainer/functions/connection/bilinear.py
- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/convolution_nd.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/functions/connection/deconvolution_nd.py
- chainer/functions/connection/dilated_convolution_2d.py
- chainer/functions/connection/linear.py
- chainer/functions/evaluation/accuracy.py
- chainer/functions/evaluation/classification_summary.py
- chainer/functions/math/basic_math.py
- chainer/functions/math/det.py
- chainer/functions/math/matmul.py
- chainer/functions/normalization/batch_normalization.py
- chainer/utils/type_check.py
- tests/chainer_tests/test_function.py
- tests/chainer_tests/utils_tests/test_type_check.py
It is a proto-type of lazy-type-check, that is faster type-check mechanism than the current implementation. It behaves like this:
- Run type check code with `ndarray` itself. It is very fast.
- If an error is found, make syntactic trees to show readable error message using the current type check mechanism.
- Error messages are not changed from the current one.
- #1692 can only shows stack trace.
It also fixes #1437
> Lazy typecheck

- chainer/functions/normalization/l2_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
This PR adds `axis` option to `chainer.functions.normalization` so that it can normalize arrays along arbitrary axis.
Previously, the function only supported the case when an input array is of dimension two and normalization happens in the second axis.
The default value of `axis` is set to behave identical to the previous implementation when `axis` is not supplied by the user.
> Add axis option to l2_normalization

- chainer/serializers/hdf5.py
- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
- tests/chainer_tests/serializers_tests/test_npz.py
Current `strict` options in `NpzDeserializer` and `HDF5Deserializer` work well when the link does not have a hierarchical structure, however, it automatically changes `strict` option to `True` after the 2nd level even if users explicitly specify `False`. This PR aims to fix this problem.
> Fix strict option in deserializer to support recursive calls

- chainer/training/extensions/plot_report.py
related to https://github.com/pfnet/chainer/issues/2146
`import matplotlib` sometimes throws `TypeError`. So `TypeError` also should be caught.
> Fix an exception handling problem during importing matplotlib

- chainer/functions/connection/n_step_lstm.py
Usually LSTM does not apply dropout to hidden states.
> Dropout is not required to apply to hidden states

- chainer/computational_graph.py
- chainer/function.py
- chainer/functions/activation/relu.py
- chainer/functions/array/concat.py
- chainer/functions/array/split_axis.py
- chainer/functions/math/basic_math.py
- chainer/variable.py
- tests/chainer_tests/function_hooks_tests/test_debug_print.py
- tests/chainer_tests/test_computational_graph.py
- tests/chainer_tests/test_function.py
Fix #2368. This PR implements the aggressive buffer release. It only implements the core part and memory reduction for some commonly used functions (`relu`, some arithmetics, `concat`, and `split_axis`). I tried to carefully design the API so that most existing codes will not be affected, but it actually breaks the backward compatibility and may break codes that touch computational graphs.
I quickly compared the memory consumption of the ImageNet example between this branch and Chainer v1.22. I used a batch size of 32 for both training and validation. The following is their GPU memory usage obtained by `nvidia-smi` command kicked during training. Note that I used cuDNN 5.1.3 (EDIT: and used the default workspace size of 8MB). This PR effectively reduces the memory usage. In particular, it …
> Implement aggressive buffer release

- chainer/functions/loss/softmax_cross_entropy.py
I added `ignore_label` argument to `softmax_cross_entropy`.
> Add ignore_label option to softmax_cross_entropy

- cupy/sorting/count.py
- tests/cupy_tests/sorting_tests/test_count.py
It's minor-fix. `cupy.count_nonzero` should be the same as `numpy.count_nonzero`.
> Fix count_nonzero to allow its axis option

- tests/cupy_tests/sorting_tests/test_count.py
`axis` option was introduced to `count_nonzero` in NumPy 1.12.0 . So we have to skip tests that uses this option if NumPy is older.
> Skip tests that use axis option of count_nonzero

- chainer/__init__.py
- chainer/link.py
- chainer/optimizer.py
- chainer/optimizers/ada_delta.py
- chainer/optimizers/ada_grad.py
- chainer/optimizers/adam.py
- chainer/optimizers/momentum_sgd.py
- chainer/optimizers/nesterov_ag.py
- chainer/optimizers/rmsprop.py
- chainer/optimizers/rmsprop_graves.py
- chainer/optimizers/sgd.py
- chainer/optimizers/smorms3.py
- chainer/variable.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
- tests/chainer_tests/serializers_tests/test_npz.py
- tests/chainer_tests/test_link.py
- tests/chainer_tests/test_optimizer.py
- tests/chainer_tests/test_variable.py
Fix #2008. See the design docs for the original design. It enables us to configure the hyperparameters of optimization methods differently for each parameter (e.g. using different learning rates, different weight decay coefficients). This PR contains slight modifications to that design, including the following things.
- Hyperparameter object is introduced to let the optimizer provide the default values for hyperparameters of each update rule. It enables us to configure the hyperparameter at once for all parameters for which a hyperparameter is not overridden. **Note:** I actually don't satisfy with this design, since it introduces some complexity to the implementation of any optimizer and would require some care on handling hyperparameters. Any discussions are welcome.
- Most optimizer …
> Implement UpdateRule and use it in optimizers

- chainer_setup_build.py
cuSolver depends on openmp. When i use cuSolver, i got this error and cuSolver is not enabled.
```
/usr/local/cuda/lib64/libcusolver.so.8.0: undefined symbol: GOMP_critical_end
```
The test for cuSolver is skipped in this situation.
> Add dependency to openmp for cusolver

- tests/chainer_tests/test_computational_graph.py
This PR adds tests for the `show_name` option for the computational graph builder, to check if
- setting the flag to `True` will add the variable name to the corresponding label.
- setting the flag to `False` will work vice versa.
> Tests for show_name functionality of the computational graph

- chainer/dataset/dataset_mixin.py
- tests/chainer_tests/dataset_tests/test_dataset_mixin.py
There are 2 improvement in this PR.
1. Improve getitem performance 
Performance improvement of slice access of DatasetMixin.
(test_large_dataset took 0.4 sec -> 0.3 sec with this modification in my environment.)
2. Add advanced indexing support
Allow numpy like advanced indexing access of dataset
e.g., ds[[1, 2, 4]]
> 1. Improve getitem performance 2. Add one dimensional integer array indexing support

- tests/chainer_tests/training_tests/test_trainer.py
Currently, the design of updater used in `_get_mocked_trainer` is wrong.
- `epoch_detail` before the first iteration is `1`.
It should be `0` because no samples are processed before the first iteration.
-  `epoch_detail` does not change during iterations.
This means batchsize is zero or the size of dataset is infinity. However, some test cases use epoch-base triggers.
> fix mocked trainer

- chainer/functions/array/split_axis.py
- tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
We can support that split_axis method returns zero-size array.
> Support zero-dim results in split_axis

- chainer/functions/connection/n_step_lstm.py
- tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
I fixed dropout policy on NStepLSTM. It is compatible with cuDNN's one. To check it I made a test to count dropout applied.
> Fix lstm dropout

- tests/chainer_tests/functions_tests/loss_tests/test_vae.py
As tests are not a part of `chainer` module, it is encouraged to use public API of Chainer as other libraries.
> Use `chainer.functions` alias in tests

- chainer/datasets/__init__.py
- chainer/datasets/transform_dataset.py
- docs/source/reference/datasets.rst
- tests/chainer_tests/datasets_tests/test_transform_dataset.py
This PR adds a general dataset class called `TransformDataset`.
This class lets users to apply a function to a indexed data.
It becomes handy in the case when a user wants to write a custom data augmentation code on top of the prepared dataset class.
This class decouples implementation of data augmentation code and a code to retrieve data from filesystem or from web, making it a lot easier to reuse datasets across different tasks.
The class is already used in ChainerCV, an extension library to Chainer.
> Add TransformDataset

- chainer/functions/activation/softmax.py
- tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
fix #2536, although only one axis is supported.
This PR enables the specification of an axis along which the `softmax` is computed, so that it can be used not just for "channel-wise" computation but also for situations like "pixel-wise" computation.
> Add axis option to softmax function

- examples/seq2seq/europal.py
The current open_file() function in europal.py supports opening gzipped files.
However, gzip.open functions does not automatically decode the input stream
and users must specify input encoding explicitly.
This PR fixes the issue by using sys.getdefaultencoding().
> Minor fix on gzip.open() encoding

- tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
I rewrote tests of `ManualScheduleTrigger` with `testing.parameterize`. I think this is better than a lot of test classes.
> Improve tests of manual schedule trigger

- tests/chainer_tests/functions_tests/array_tests/test_stack.py
Current unittest of `F.stack` does not check `axis=-(ndim+1)` case, which is valid. As we would like to add this case to the document (#2491), I add this case to confirm it works.
> Strengthen the unittest of F.stack

- chainer/functions/normalization/batch_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Changed the target branch of #2580 to master.
Also I added tests that use non-c-contiguous inputs as suggested in the comments in #2580. A new argument (param_shape = (3,)) is added because [cudnn is used only if `x.ndim == 4 and head_ndim == 2`](https://github.com/pfnet/chainer/blob/master/chainer/functions/normalization/batch_normalization.py#L107), which requires `len(param_shape) == 1` (or if `x.ndim == 2`, which requires `param_shape == ()` but it causes some inconsistency with the existing test codes).
> Convert inputs of batchnormalization.backward() to be C-contiguous (master)

- tests/chainer_tests/test_init_docstring.py
I fixed the test to skip external classes.
> Skip init docstring test for external classes

- docs/source/compatibility.rst
> Fix typo in docs/source/compatibility.rst

- chainer/functions/pooling/max_pooling_2d.py
- chainer/functions/pooling/pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
In the CPU code of `max_pooling_2d`, the size of the expected output is checked before calculation (in [`chainer/utils/conv.py`](https://github.com/pfnet/chainer/blob/master/chainer/utils/conv.py#L25-L28])) so that the output never becomes a 0-dimentional tensor.
However, this check is missing in the GPU code (with and without cudnn) and thus passing an invalid input to `max_pooling_2d.py` yields a very un-friendly error as exampled below.
This PR adds assertions that check the output size of `max_pooling_2d` for GPU cases, and also improves the tests to check the added behavior.
Sample output before this PR is applied:
```
>>> import chainer
>>> x_data = chainer.cuda.cupy.random.rand(4, 4, 1, 4)
>>> x = chainer.Variable(x_data)
>>> chainer.functions.max_pooling_2d(x, 3, stride=2) …
```
> Assert output size of max_pooling_2d in GPU cases

- cupy/core/fusion.py
- tests/cupy_tests/core_tests/test_fusion.py
> Fix fuse with *args without input_num

- tests/chainer_tests/functions_tests/loss_tests/test_vae.py
There are two `TestGaussianNLLInvalidReductionOption`, whose contents are different. It causes autopep8 violation in the master branch (see e.g. [this build](https://travis-ci.org/pfnet/chainer/builds/224012219)). This PR changes the name of one of them.
> Fix test name

- chainer/functions/loss/softmax_cross_entropy.py
There seems to be a print that was maybe used for debugging, it's already not needed. It produces `()` everytime the softmax_cross_entropy is called.
> Delete a noisy print

- .pep8
- .travis.yml
When i run autopep8 locally, i cannot use `--inplace` option as it loads `.pep8` file and appends `--diff` option. I removed this option from `.pep8` file.
> Fixed pep8 file to use autopep8 command locally

- examples/pos/postagging.py
If len(data) is not divisible, datasets.split_dataset_random recieve float value as ```first_size```.
This cause an error in calling ```numpy.random.permutation(len(self.dataset))``` because permutation cannot take a float object as argument.
NOTE: this error occurs in Python3
> Fixbug in chainer.datasets.split_dataset_random

- chainer/functions/__init__.py
- chainer/functions/loss/absolute_error.py
- tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py
`MeanAbsoluteError` without reduction. The new function is named `AbsoluteError`. The original `MeanAbsoluteError` is kept as is. This PR is related to #2558.
> AbsoluteError

- chainer/functions/__init__.py
- chainer/functions/loss/squared_error.py
- tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py
`MeanSquaredError` without reduction. The new function is named `SquaredError`. The original `MeanSquaredError` is kept as is. This PR is related to #2558.
> SquaredError

- examples/ptb/train_ptb.py
I added `--model` argument to specify file name to serialize. I'll fix chainer-test to test `gentext.py`  after this PR is merged.
> Add model argument to serialize

- chainer/links/theano/theano_function.py
- chainer/testing/helper.py
- cupy/testing/helper.py
- tests/chainer_tests/links_tests/theano_tests/test_theano_function.py
Theano executes initialization process when it is imported. Such behavior is undesirable especially for users who do not need theano. To minimize its side effect, it needs to be imported on initializer.
See @jekbradbury 's comment:
https://github.com/pfnet/chainer/issues/2570#issuecomment-296408191
> Import theano on initializer

- examples/word2vec/train_word2vec.py
ref: https://github.com/pfnet/chainer/issues/2636
this comment is already outdated.
ptb/download.py existed in v1.10.0 
https://github.com/pfnet/chainer/blob/v1.10.0/examples/ptb/download.py
but outdated in v1.11.0
https://github.com/pfnet/chainer/tree/v1.11.0/examples/ptb/download.py
> Remove outdated comment from example/word2vec/train_word2vec.py

- chainer/datasets/cifar.py
Avoid having separate and similar retrieval functions for cifar-10 and cifar-100.
> Refactor the cifar dataset loading code according to DRY.

- examples/imagenet/alex.py
Since "bias" keyword parameter  in L.Convolution2D.__init__() is removed, alex_fp16 example is broken.
```
File "examples/imagenet/train_imagenet.py", line 205, in <module>
main()
File "examples/imagenet/train_imagenet.py", line 132, in main
model = archs[args.arch]()
File "/home/kfukuda/chainermn/examples/imagenet/alex_v2.py", line 58, in __init__
stride=4, initialW=W, bias=bias),
TypeError: __init__() got an unexpected keyword argument 'bias'
```
I think the `bias` arguments can be simply removed in general cases.
In this case, however, FP16 dtype is used explicitly. So I replaced it with `initial_bias`.
(I'm not confident...)
> Fix broken alex_fp16 example.

- chainer/links/connection/convolution_2d.py
- chainer/links/connection/deconvolution_2d.py
- chainer/links/connection/dilated_convolution_2d.py
- chainer/links/connection/linear.py
- chainer/links/connection/lstm.py
In some module, in_channel/in_size parameter accepts None, but only int is described in docstring.
This PR add "or None" to docstring.
```
$ env/bin/pep8 chainer/links/connection/*
$
```
> Modify docstring in connection

- chainer/functions/array/spatial_transformer_sampler.py
- tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py
This PR follows a discussion in #2458.
The current implementation of `spatial_transformer_sampler` in cuDNN mode and non-cuDNN mode are different.
This happens in the case when grid is outside the range [-1, 1].
In the implementation of cuDNN, points are sampled from a zero padded image when this happens.
However, in the current implementation of non cuDNN mode, grid is clipped to range [-1, 1].
Since creating difference between cuDNN and non-cuDNN was not intended, I would like to fix it with this PR.
This also fixes a problem that the documentation is not reflecting the implementation of cuDNN.
The tests became less stable so the tolerance for error is loosened even for cuDNN implementation when grid is outside the range [-1, 1].
Also, I added a test to verify that cuDNN and non cuDNN …
> Fix spatial_transformer_sampler to behave consistently among cuDNN and non-cuDNN mode

- chainer/functions/connection/dilated_convolution_2d.py
A tensor descriptor for `xij` should be named `xji_desc`, but not `x_desc`, to be consistent with the names used in other places like [here](https://github.com/pfnet/chainer/blob/master/chainer/functions/connection/dilated_convolution_2d.py#L248).
> make variable names consistent

- chainer/functions/connection/deconvolution_2d.py
- chainer/functions/connection/deconvolution_nd.py
Currently `b` is not converted into c-contiguous in the `backward` functions of deconvolution (although it is made c-contiguous in the `forward` functions), because `b` is used as `gb = cuda.cupy.empty_like(b)` and `cuda.cupy.empty_like` always returns a c-contiguous array.
However, this behavior of `cuda.cupy.empty_like` is implementation specific that is different from how `numpy.empty_like` behaves. For a fortran array `x`, `numpy.empty_like(x)` returns a fortran array if the `order` argument is not given, as documented in https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html:
> numpy.empty_like(a, dtype=None, order='K', subok=True)
> ...
> order : {‘C’, ‘F’, ‘A’, or ‘K’}, optional
> Overrides the memory layout of the result. ‘C’ means C-order, ‘F’ means F-order, …
> Make b c-contiguous in backward for deconvolution

- chainer/functions/array/copy.py
- tests/chainer_tests/functions_tests/array_tests/test_copy.py
`Copy.backward` needs to check type of input array.
> Check input device in Copy.backward

- chainer/serializer.py
- chainer/serializers/hdf5.py
- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
- tests/chainer_tests/serializers_tests/test_npz.py
This PR makes each serializer implementation handle `None` appropriately. The change of the "specification" of AbstractSerializer may affect existing codes used by future codes, and so I make this PR for v2.
> Make None serializable

- cupy/linalg/__init__.py
- cupy/linalg/decomposition.py
- docs/source/cupy-reference/linalg.rst
- tests/cupy_tests/linalg_tests/test_decomposition.py
Merge after #2412.
This PR aims to add the Singular Value Decomposition (SVD) to cupy.
Note: this PR is based on #1402.
> Add Singular Value Decomposition to cupy

- chainer/functions/loss/triplet.py
- tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
This PR adds `reduce` option to `F.triplet` and `F.Triplet`. Related to #2558
> Add reduce option to triplet loss

- chainer/functions/array/spatial_transformer_sampler.py
Before calling cuDNN functions, arrays need to be C-Contiguous.
This was not enforced in the backward pass of the function, and this PR fixes that problem.
> Fix C-contiguity of the backward pass of spatial_transformer_sampler 

- chainer/functions/connection/n_step_lstm.py
- chainer/functions/noise/dropout.py
- chainer/functions/noise/zoneout.py
- chainer/functions/normalization/batch_normalization.py
- chainer/links/caffe/caffe_function.py
- chainer/links/connection/n_step_lstm.py
- chainer/links/connection/zoneoutlstm.py
- chainer/links/model/vision/resnet.py
- chainer/links/model/vision/vgg.py
- chainer/utils/argument.py
I applied #2556 to all functions which had `train` or `test` arguments.
> Check old arguments which is not supported in v2 to show error message.

- chainer/link.py
This PR remove redundant parentheses in link.py
> remove redundant parentheses in link.py

- cupy/core/carray.cuh
Currently kernels generated by CuPy performs pointer computation in 32-bit, which cause overflow when handling array whose size is more than 2 GiB.
The following example tries to run `arange` over 2 GiB + 4 bytes of memory, and it fails with `cudaErrorIllegalAddress`.
```
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
>>> import cupy
>>> cupy.arange(pow(2,29)+1, dtype=cupy.int32)
Exception cupy.cuda.runtime.CUDARuntimeError: CUDARuntimeError(u'cudaErrorIllegalAddress: an illegal memory access was encountered',) in 'cupy.cuda.memory.Memory.__dealloc__' ignored
File "cupy/core/core.pyx", line 1327, in …
```
> CuPy kernels cannot handle arrays over 2 GiB

- docs/source/reference/extensions.rst
Somehow both `observe_value` and `observe_lr` are missing from the documentation. Those are useful, so should be added.
> Add observe_value and observe_lr to extension.rst

- setup.py
apt `python-protobuf` is 2.5.0 on ubuntu trusty, and I found someone who encountered this problem.
```
% pip show protobuf
Name: protobuf
Version: 2.5.0
Summary: Protocol Buffers
Home-page: http://code.google.com/p/protobuf/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: New BSD License
Location: /usr/lib/python2.7/dist-packages
Requires:
% python -c 'import chainer.links.caffe.protobuf2.caffe_pb2'
File "<string>", line 1, in <module>
File "chainer/links/caffe/__init__.py", line 1, in <module>
from chainer.links.caffe import caffe_function
File "chainer/links/caffe/caffe_function.py", line 37, in <module>
from chainer.links.caffe.protobuf2 import caffe_pb2 as caffe_pb
File "chainer/links/caffe/protobuf2/caffe_pb2.py", …
```
> Chainer should depend on protobuf >= 2.6.0

- chainer/functions/loss/vae.py
- tests/chainer_tests/functions_tests/loss_tests/test_vae.py
Currently, inputs of VAE functions (`gaussian_kl_divergence`, `bernoulli_nll`, and `gaussian_nll`) must be `Variable`. But as Chainer function accepts `xp.ndarray` as well as `Variable` (see #1221). This requirement is too restrictive. This PR loosen the type condition of their inputs.
> Remove requirement that inputs of VAE functions being Variable

- chainer/functions/loss/decov.py
- tests/chainer_tests/functions_tests/loss_tests/test_decov.py
This PR adds `reduce` option to `F.Decov` and `F.decov`. Related to #2558
> Add reduce option to decov

- chainer/functions/loss/softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
> Fix the bug that F.SoftmaxCrossEntropy does not work properly when ignore_label is other than -1

- chainer/training/extensions/linear_shift.py
- tests/chainer_tests/training_tests/extensions_tests/test_linear_shift.py
Fix #2687. Note that it includes some test code duplication with #2686; these codes will be removed in v2 (see #2639). I think finishing these fixes quickly for v1 is better than refactoring these codes (which requires adding some API to `chainer.testing`) by using more time and so I didn't clean up the duplication.
> Fix resume bug of LinearShift

- chainer/functions/loss/cross_covariance.py
- tests/chainer_tests/functions_tests/loss_tests/test_cross_covariance.py
This PR adds `reduce` option to `F.CrossCovariance` and `F.cross_covariance`. Related to #2558
> Add reduce option to F.cross_covariance

- chainer/links/connection/dilated_convolution_2d.py
I remove an obsolete document about `wscale`, which is removed by #2163.
> Remove obsolete document in DilatedConvolution2D

- chainer/links/connection/gru.py
- tests/chainer_tests/links_tests/connection_tests/test_gru.py
Fixes #2285 
I changed the API of `GRU` and `StatefulGRU` to align with `LSTM`. Specifically, I change `n_units` and `n_inputs` to `in_size` and `out_size`, respectively, change the order of the two, and allow `in_size` to accept `None`.
> Fix inconsistency between GRU and LSTM

- cupy/cuda/cupy_nccl.h
- cupy/cuda/nccl.pyx
Fix the CI issue https://github.com/pfnet/chainer/pull/2213#issuecomment-300376507
> Modify the nccl wrapper for --cupy-no-cuda

- cupy/core/core.pyx
- tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
This PR allows to fill `cupy.ndarray` with a numpy scalar: 
```python
x = cupy.ndarray((2, 3, 4))
x.fill(numpy.array([42]))
```
```python
x = cupy.ndarray((2, 3, 4))
x[...] = numpy.array([42])
```
Additionally, the error message is improved when a non-scalar `numpy.ndarray` is passed to `cupy.ndarray.fill`.
> Treat numpy scalars correctly in cupy.ndarray.fill	

- chainer/cuda.py
- chainer/link.py
- chainer/links/loss/black_out.py
- chainer/links/loss/hierarchical_softmax.py
- chainer/links/loss/negative_sampling.py
To revert `to_gpu` behavior I added `_get_device` method that works as the original `get_device` and fixed Variable and links to use it.
> Revert to_gpu behaivor of links and variable

- examples/README.md
Table of contents in this short list is rather confusing.
Maybe we can get it back when the list grows longer.
> Remove TOC from examples/README.md

- chainer/links/connection/embed_id.py
I fix a bug of #2465
When `EmbedID` is given an initial weight value by `ndarray`, TypeError occured.
```
>>> import chainer.links as L
>>> import numpy as np
>>>
>>> embed = L.EmbedID(10, 3, initialW=np.zeros((10, 3)))
File "/Users/user/git/chainer/chainer/links/connection/embed_id.py", line 37, in __init__
self.add_param('W', (in_size, out_size), initializer=initialW)
File "/Users/user/git/chainer/chainer/link.py", line 192, in add_param
data = initializers.generate_array(initializer, shape, self.xp)
File "/Users/user/git/chainer/chainer/initializers/__init__.py", line 46, in generate_array
initializer(array)
TypeError: 'numpy.ndarray' object is not callable
```
Because, `EmbedID` don't use …
> Fix init weight of EmbedID

- chainer/links/model/vision/googlenet.py
This is my mistake, I incorrectly "fix"ed the docstring at commit 24a2884eed1307f874470a53d8d5bc4f33a26079, without understanding the intent.
This PR reverts the commit.
> Revert "Fix docstring"

- docs/source/tutorial/convnet.rst
Found several typos in `docs/source/tutorial/convnet.rst`
- 	detectiong => detecting
- 	segmenation => segmentation
- 	registedred => registered
> Fix several typos in tutorial

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
This PR fixes a bug of Hyperparameter on deep copy (or, strictly speaking, on unpickling).
> Make Hyperparameter copyable in Py3.6

- chainer/links/connection/mlp_convolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py
I found `wscale` option in `L.MLPConvolution2D` is not used any longer. Related to #2163
> Remove wscale option from MLPConvolution2D

- chainer/cuda.py
This PR fixes the location of `get_device_from_id` and `get_device_from_array`. Also it changes the corrupted markups.
> Fix the location of get_device_from_id and get_device_from_array

- chainer/variable.py
- tests/chainer_tests/test_function.py
- tests/chainer_tests/test_link.py
I fixed Variable to show error message when obsolete `volatile` argument is given.
> Show error when volatile flag is given

- chainer/serializers/hdf5.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
`h5py.Empty` is introduced from `h5py==2.7.0`.
> Check h5py version when serializing None

- docs/source/compatibility.rst
- docs/source/contribution.rst
This change updates API Compatibility Policy for v2. Since it includes a link to some sections of the updated contribution guide, this PR depends on #2773. Please merge #2773 before this one.
> Update API Compatibility Policy

- docs/source/tutorial/convnet.rst
Fixed typo in convnet.rst
`iput` => `input`
> Fix typo in tutorial

- chainer/serializers/hdf5.py
- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_npz.py
I came across a situation where I want to load the serialized parameters under a _certain path_.
If my understanding is correct, the only way to achieve the behavior is to write something like the following:
```py
serializers.NpzDeserializer(np.load('saved_model'))['path_of_interest'].load(obj)
```
which would produce quite a lot of the same code written in the `load_npz` method.
By applying the change I propose here, the user can obtain the same result by:
```py
serializers.load_npz('saved_model', obj, path='path_of_interest')
```
which I think is more straightforward.
> Add path option for load_npz method

- chainer/utils/experimental.py
I found a typo in docstring, and fixed it.
> Fix a variable name in docstring

- chainer/link.py
I found a wrong example in chainer.Link docstring and fixed arguments order to be valid.
> fix chainer.Link docstring

- README.md
Currently, the link in README.md is broken.
> Fix contibution guide link

- docs/source/tutorial/convnet.rst
Two models in the convnet tutorial can't work correctly due to the wrong commas at the end of lines inside model definitions.
> Remove wrong commas from network definitions in ConvNet tutorial

- chainer/optimizer.py
Fixes #2851
See also: https://stackoverflow.com/questions/29436716/why-do-you-need-if-instance-is-none-in-get-of-a-descriptor-class
> Check for None in HyperparameterProxy descriptor

- chainer/optimizer.py
> [backport] Check for None in HyperparameterProxy descriptor

- docs/source/reference/functions.rst
This PR adds `pad_sequence` function to reference, which seems to be missing after it was implemented.
> Add F.pad_sequence to the reference

- chainer/functions/array/pad_sequence.py
`F.pad_sequence` causes an error on 64bit Windows when the input arrays are `cupy.ndarray`.
The cause of the error is that the function internally creates an array of pointers, but `dtype='L'` is `np.uint32` in 64bit Windows. 
To fix it I replaced 'L' with 'P' which is [dtype for pointer type](https://docs.scipy.org/doc/numpy-1.12.0/reference/arrays.scalars.html).
> uint 	compatible: Python int 	'L'
> uintp 	large enough to fit a pointer 	'P'
The following code reproduces the error (Chainer 2.0.0, Python 3.6.1, 64bit Windows 10).
code:
```python
import cupy
x = [cupy.arange(5), cupy.arange(3)]
F.pad_sequence(x)
```
output:
```python
File "<ipython-input-13-f23231849e76>", line 5, in <module>
F.pad_sequence(x)
File …
```
> Fix F.pad_sequence error on 64bit Windows GPU

- docs/source/tutorial/convnet.rst
This PR backports #2840 and #2841 to v2.
> Fix some typoes in convnet tutorial

- chainer/datasets/ptb.py
Currently, chainer.datasets.ptb downloads the dataset from forked repository.
The contents of original repository seems to be exactly the same.
So I think it would be better chainer downloads dataset from original repository.
I checked the difference between original data and forked one in the way below.
```
$ git clone git@github.com:wojzaremba/lstm.git lstm_original
Cloning into 'lstm_original'...
remote: Counting objects: 53, done.
remote: Total 53 (delta 0), reused 0 (delta 0), pack-reused 53
Receiving objects: 100% (53/53), 1.91 MiB | 391.00 KiB/s, done.
Resolving deltas: 100% (26/26), done.
$ git clone git@github.com:tomsercu/lstm.git lstm_forked
Cloning into 'lstm_forked'...
remote: Counting objects: 72, done.
remote: Total 72 (delta 0), reused 0 (delta 0), pack-reused 72
Receiving …
```
> Update target url for ptb dataset

- chainer/training/extensions/exponential_shift.py
- chainer/training/extensions/linear_shift.py
- tests/chainer_tests/training_tests/extensions_tests/test_exponential_shift.py
- tests/chainer_tests/training_tests/extensions_tests/test_linear_shift.py
`ExponentialShift` and `LinearShift` cause an error when they are used in GPU training. Updating weights in optimizer is failed because they set `optimizer.lr` as `numpy.ndarray`.
Here is an example code.
```
import argparse
import chainer
import chainer.links as L
from chainer import training
from chainer.training import extensions
def get_trainer(dataset, model, gpu):
iterator = chainer.iterators.SerialIterator(dataset, 1)
optimizer = chainer.optimizers.MomentumSGD()
optimizer.setup(model)
updater = training.StandardUpdater(iterator, optimizer, device=gpu)
trainer = training.Trainer(updater, (10, 'iteration'))
trainer.extend(
extensions.ExponentialShift('lr', 0.1, init=0.01),
trigger=(3, 'iteration'))
trainer.extend(extensions.snapshot(), trigger=(5, 'iteration')) …
```
> Fix resuming issue of *Shift extensions

- chainer/links/model/vision/googlenet.py
- chainer/links/model/vision/resnet.py
- chainer/links/model/vision/vgg.py
- tests/chainer_tests/links_tests/model_tests/test_vision.py
When one copies a vision model, `self.functions` is not correctly copied. This PR fixes the problem by making `functions` a property.
> Make vision models copyable

- chainer/cuda.py
- chainer/dataset/convert.py
This PR implement asynchronous copy to `cupy.array`.
The stream option in `cuda.to_gpu` is deprecated, because stream option is difficult.
> Improve asynchronous host to device copy

- chainer/function.py
- chainer/variable.py
Avoid `itervalues` in `forward` and `backward` for performance
> Avoid itervalues for performance

- tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
`initial_iteration` is no longer needed.
> Remove unused parameter/serialization in test_manual_schedule_trigger.py

- chainer/variable.py
- tests/chainer_tests/test_variable.py
Fixes #2787 
Slightly reorganized str() logic to align with repr() code.
> Fix Variable repr and str failure when data is None

- docs/source/reference/functions.rst
This PR is the backport of #2863. As it is made on top of #2883, please review that PR first.
> [Backport] Add F.pad_sequence to the reference (#2863)

- chainer/variable.py
- tests/chainer_tests/test_variable.py
This PR is the backport of #2806
> [Backport] Fix Variable repr and str failure when data is None (#2806)

- chainer/cuda.py
CPU-to-GPU transfer with CUDA stream is not working.
It seems that this error was introduced in #2238.
> fix stream option not working with to_gpu

- chainer/functions/__init__.py
- chainer/functions/normalization/layer_normalization.py
- chainer/links/normalization/layer_normalization.py
- docs/source/reference/functions.rst
The current implementation of layer normalization is slow (as [this](https://github.com/chainer/chainer/pull/1950#issuecomment-265613756) mentioned). I implemented forward and backward computation explicitly as a new function.
> Optimize layer normalization

- examples/imagenet/train_imagenet_data_parallel.py
This PR will add ResNet50 for "train_imagenet_data_parallel.py". (related to #2644) 
This PR will also abort TestModeEvaluator to solve the following error. (related to #2186) 
```
$ python train_imagenet_data_parallel.py train.txt val.txt -a alex -g 0 1 2 3 -R imagenet
/home/ubuntu/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py:142: UserWarning: optimizer.lr is changed to 0.0025 by MultiprocessParallelUpdater for new batch size.
format(optimizer.lr))
File "train_imagenet_data_parallel.py", line 136, in <module>
main()
File "train_imagenet_data_parallel.py", line 112, in main
trainer.extend(train_imagenet.TestModeEvaluator(val_iter, model,
AttributeError: module 'train_imagenet' has …
```
> Fix to abort TestModeEvaluator and add resnet50.

- docs/source/reference/functions.rst
This PR adds `F.squared_error` to the document.
> Register squared error to docs

- chainer/optimizers/adam.py
I eliminated a bug that depend on the version of glibc from adam.py.
If you use glibc-2.11 or earlier, the pow() function (and also '**' operator) in python gives the following error when its result is a denormalized number. (This bug does not depend on python version but glibc version.)
The result tried in my environment is as follows.
* use glibc-2.11 or earlier
```
$ rpm -q glibc
glibc-2.11.3-17.109.1
$ python
Python 2.7.11 (default, Feb 28 2017, 20:05:35)
[GCC 4.8.5] on linux2
>>> 0.1 ** 307
1.0000000000000171e-307
>>> 0.1 ** 308
OverflowError: (34, 'Numerical result out of range')
>>> 0.1 ** 323
File …
```
> Fix a bug dependent on glibc version

- chainer/training/trainer.py
This PR makes sure that any exception raised during the training process is shown to the user before the finally clause is reached in the training loop.
This is needed because if any trainer extension or updater hangs or deadlocks (this has happened to me repeatedly when using `MultiprocessIterator`), it will appear as if Chainer has hanged, while the actual cause is the user's own code raising an exception.
Since exceptions often happen when developing new models, this fix will reduce user frustration.
By showing the exception, the user will immediately know that his/her model has a bug, and not wonder why Chainer is not responding.
This verbose behavior can be disabled with a parameter to `run()`.
I have tested this with Python 2.7.6 and 3.4.5.
Example output when adding the line `a = 1 …
> Add opt-out exception display to trainer loop before finally clause

- chainer/function_hooks/timer.py
- tests/chainer_tests/function_hooks_tests/test_timer.py
Added `print_summary()` method to Timer hook so that we can do time profile similarly with the memory profiler of https://github.com/chainer/chainer/pull/2925
An example code:
```python
from chainer.function_hooks import TimerHook
hook = TimerHook()
with hook:
trainer.run()
hook.print_report()
```
Outputs from mnist example become as followings:
```
FunctionName    ElapsedTime     Occurrence
LinearFunction  1.17sec 3900
ReLU    547.88ms        2600
SoftmaxCrossEntropy     968.39ms        1300
Accuracy        155.53ms        700
``` #
> Add print_report() method to Timer hook

- chainer/functions/pooling/upsampling_2d.py
The example shown in the docstring is somehow wrong.
The scope which avoids using cuDNN should be made right before applying `max_pooling_2d` function.
This PR fixes the example code.
> Fix the docstring of Upsampling2D

- chainer/testing/training.py
- tests/chainer_tests/testing_tests/test_training.py
This PR is related to #2484.
I added `iter_per_epoch` option to `get_trainer_with_mock_updater`. This PR also includes a bugfix  and improvement of tests.
> Add iter_per_epoch to get_trainer_with_mock_updater

- setup.py
This PR adds the mock module to `install_requires` in `setup.py`. This PR fixes #2973.
> Add mock to install_requires

- chainer/functions/noise/simplified_dropconnect.py
- chainer/links/activation/simplified_dropconnect.py
- tests/chainer_tests/functions_tests/noise_tests/test_simplified_dropconnect.py
- tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
Current dropconnect support only batchwise mask. (i.e. masked element is different with each sample in mini-batch).
This mask specification is same with the original implementation.
One of purpose of this option is memory conservation.
> Support batch-common-mask dropconnect

- chainer/functions/pooling/roi_pooling_2d.py
The value can get returned without initialization in some case.
Therefore, we should use `zeros` instead of `empty`.
For example, `sliceh.stop == `sliceh.start`, when height and ymin are very close. 
https://github.com/yuyu2172/chainer/blob/bee0deb0dae30bf0db7a2f630860cb9a4a97116d/chainer/functions/pooling/roi_pooling_2d.py#L94
> Use zeros instead of empty for ROIPooling2D CPU mode

- README.md
This PR adds links to public slack archives (both English and Japanese) to `README.md`.
Fixes #2980
> Add links to slack archive to README

- chainer/training/trainer.py
AppVeyor is failing due to insufficient timer resolution (probly).
This PR selects the best-resolution timer in the current environment.
([Python 3 time module documentation](https://docs.python.org/3/library/time.html))
**For Python >=3.3**
* `time.perf_counter` has the highest resolution.
**For Python <3.3**
* `time.clock`: On Windows, it uses `QueryPerformanceCounter` Win32 API function, which has a good resolution. On Unix, it returns the "processor time", whose definition depends on C `clock` function.
* `time.time`: Returns the time since the epoch. Not monotonic.
> Select the best-resolution timer function

- docs/source/upgrade.rst
Fixed typo between v1 and v2 code examples in documentation (chainer.Variable(x) -> chainer.Variable(x_data))
> fixed typo in upgrade doc example for volatile mode changes

- chainer/links/model/classifier.py
- tests/chainer_tests/links_tests/model_tests/test_classifier.py
To support keyword arguments in Classifier, I added `label_key` attribute to specify label variable. When a user specify `str` key, this class uses keyword argument as a label variable.
> Support keyword argument in classifier link

- chainer/functions/pooling/upsampling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_upsampling_2d.py
Type check of upsampling_2d only checks if an input variable is float, but actually it does not support float types except float32. I fixed it to support all float types.
> Support all float types in upsampling_2d

- docs/source/conf.py
Fixes #2984
(At least it works on local `readthedocs/build` docker image)
The problem was that, the previous code assumed source files are located in normal `chainer` repo directory tree.
However, in readthedocs-build, source files seem to be copied into a .egg directory under a temporary directory.
> Fix GitHub link

- docs/source/upgrade.rst
> [backport] fixed typo in upgrade doc example for volatile mode changes

- chainer/function_hooks/timer.py
- tests/chainer_tests/function_hooks_tests/test_timer.py
This PR makes `TimerHook` reentrant, i.e., the forward hook and backward hook can be nested. It is required by #2970 with which the backward of each function is written by Function calls rather than direct array computation.
> Make TimerHook reentrant

- chainer/training/__init__.py
- chainer/training/extensions/parameter_statistics.py
Fix #2981 
This PR adds import of modules that contain example training modules and `chainer.training.util` to `chainer.training.__init__`.
> Import example modules and util in chainer.training.__init__

- docs/source/comparison.rst
As promised in #2685 I have updated the framework comparison table with (almost?) every actively developed deep learning framework and several new axes of comparison. Let me know if anything seems inaccurate or irrelevant.
> Update Comparison with Other Frameworks

- chainer/link.py
Missing backquote for `:attr:`.
> fix typo in Link.disable_update

- chainer/__init__.py
- chainer/computational_graph.py
- chainer/function.py
- chainer/function_hook.py
- chainer/function_hooks/cuda_profile.py
- chainer/function_hooks/debug_print.py
- chainer/function_hooks/timer.py
- chainer/function_node.py
- chainer/functions/math/basic_math.py
- chainer/functions/math/identity.py
- chainer/functions/pooling/spatial_pyramid_pooling_2d.py
- chainer/gradient_check.py
- chainer/variable.py
- tests/chainer_tests/function_hooks_tests/test_timer.py
- tests/chainer_tests/test_computational_graph.py
- tests/chainer_tests/test_function.py
- tests/chainer_tests/test_function_node.py
- tests/chainer_tests/test_link.py
- tests/chainer_tests/test_variable.py
This PR is the first step of #2871. It implements `FunctionNode` that supports differentiable and economical backprop. The following points are changed.
- `FunctionNode` is added.
- The computational graph in Chainer now consists of `VariableNode` and `FunctionNode`.
- Each variable holds its gradient *variable* instead of gradient *array*. It is stored at `grad_var` attribute as @muupan suggested (the name is slightly simplified). `Variable.grad` is now a proxy to extract the data array of `grad_var`.
- Note that the owner of the gradient is moved from `VariableNode` to `Variable` so that we can avoid circular references in the computational graph.
- It also adds `FunctionAdapter`, which is an adapter class to convert an old-style function to a new-style one. `Function` is automatically …
> Implement the core part of the new-style differentiable function

- tests/chainer_tests/test_link.py
Adds test cases for link deepcopy (reported in #2972).
This depends on CuPy `ndarray` deepcopy fix (https://github.com/cupy/cupy/pull/254), so please merge it first.
> link deepcopy test

- docs/source/contribution.rst
*Guideline* is rather a policy than a concrete procedural direction.
I also fixed a broken markup.
TODO: port to CuPy
> Wording in contribution guide

- chainer/training/updater.py
Shamefully I mistook the sphinx's domain markup in the pull request [#3012](https://github.com/chainer/chainer/pull/3012).
:module: was not sphinx's domain. :mod: was correct.
I would like chainer's developer to merge this PR as soon as possible. (I'm really shamed...)
> fixed :module: to :mod:

- chainer/links/model/vision/resnet.py
`_make_npz` for `ResNetLayers` raises an error. This is because `_make_npz` calls `ResNet50Layers.convert_caffemodel_to_npz` but `ResNet50Layers.__init__` doesn't have `n_layers` argument.
```
$ rm ~/.chainer/dataset/pfnet/chainer/models/ResNet-50-model.npz
$ python -c 'from chainer.links import ResNet50Layers; ResNet50Layers()'
Now loading caffemodel (usually it may take few minutes)
File "<string>", line 1, in <module>
File "***/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/links/model/vision/resnet.py", line 331, in __init__
super(ResNet50Layers, self).__init__(pretrained_model, 50)
File "***/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/links/model/vision/resnet.py", line 112, in __init__
pretrained_model, self)
File …
```
> Fix _make_npz for ResNetLayers

- chainer/links/connection/n_step_lstm.py
This PR is to allow arbitrary initializers in `NStepLSTM.__init__` (See issue #1816).
> Accept initializers for weights and biases in NStepLSTM

- chainer/datasets/image_dataset.py
This pull request adds a warning about preprocessing the images to the documentation of ImageDataset and LabeledImageDataset.
The problem I had is that there are **a few grayscale images** in the dataset I want to use, while I am not aware of that. Chainer does not automatically convert the images to RGB or provide an option for that. Since previously I have used this dataset with other libraries and it works just fine, I was just confused about the errors `ValueError: all the input array dimensions except for the concatenation axis must match exactly`. 
I understand the decision you made as in #1445, however, I think it will be helpful if such a warning exists in the doc, so that people like me will not spend several hours to detect such an error.
Especially for people coming from other …
> Add warnings about preprocessing for dataset with both grayscale and RGB images.

- chainer/initializer.py
- chainer/initializers/constant.py
- chainer/initializers/orthogonal.py
- chainer/initializers/uniform.py
- chainer/link.py
- chainer/links/model/vision/googlenet.py
- chainer/links/model/vision/resnet.py
- chainer/links/model/vision/vgg.py
- chainer/links/normalization/batch_normalization.py
- chainer/links/normalization/layer_normalization.py
- chainer/optimizer.py
- chainer/optimizers/ada_delta.py
- chainer/optimizers/ada_grad.py
- chainer/optimizers/adam.py
- chainer/optimizers/momentum_sgd.py
- chainer/optimizers/nesterov_ag.py
- chainer/optimizers/rmsprop.py
- chainer/optimizers/rmsprop_graves.py
- chainer/optimizers/sgd.py
- chainer/optimizers/smorms3.py
- chainer/training/extension.py
- chainer/training/extensions/parameter_statistics.py
- chainer/training/triggers/__init__.py
- chainer/variable.py
- docs/source/comparison.rst
- docs/source/reference/core/optimizer.rst
- docs/source/tips.rst
Documentation build has been emitting a number of warnings, each of which generating invalid (corrupt) documentation.
> Fix doc warnings

- examples/README.md
Reinforcement learning examples have been added but not listed in the README in the example dir.
This PR also adds some external examples written by internal members and provided in pfnet-research, ChainerCV, and ChainerRL repositories.
> Improve example index

- examples/cifar/train_cifar_custom_loop.py
- examples/reinforcement_learning/ddpg_pendulum.py
- examples/reinforcement_learning/dqn_cartpole.py
This PR removes `chainer.cuda.get_device` from `./examples/`, which is deprecated in Chainer v2.
> Remove get_device from examples

- chainer/gradient_check.py
- tests/chainer_tests/functions_tests/activation_tests/test_maxout.py
- tests/chainer_tests/functions_tests/array_tests/test_cast.py
- tests/chainer_tests/functions_tests/array_tests/test_dstack.py
- tests/chainer_tests/functions_tests/array_tests/test_get_item.py
- tests/chainer_tests/functions_tests/array_tests/test_hstack.py
- tests/chainer_tests/functions_tests/array_tests/test_pad.py
- tests/chainer_tests/functions_tests/array_tests/test_permutate.py
- tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
- tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
- tests/chainer_tests/functions_tests/array_tests/test_select_item.py
- tests/chainer_tests/functions_tests/array_tests/test_separate.py
- tests/chainer_tests/functions_tests/array_tests/test_stack.py
- tests/chainer_tests/functions_tests/array_tests/test_vstack.py
- tests/chainer_tests/functions_tests/loss_tests/test_black_out.py
- tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
- tests/chainer_tests/functions_tests/loss_tests/test_hinge.py
- tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/math_tests/test_minmax.py
- tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
- tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
- tests/chainer_tests/links_tests/loss_tests/test_hierarchical_softmax.py
- tests/chainer_tests/test_gradient_check.py
Gradient check requires too long time. I replaced a test for `f(x, y, z)` with a test for `g(a) = f(ax, ay, az)`. Here `g'(a) = f'(ax, ay, az) \dot (x, y, z)`. We can test the implementation of gradient to compare numerical gradient of `g` and dot product of `f'` and `(x, y, z)`.
> Only use one direction of numerical grad

- docs/source/reference/core/configuration.rst
Fix a typo in docs/source/reference/core/configuration.rst, where "computational" was written "computaitonal".
> Fix typo in Chainer's configuration documentation

- docs/source/reference/core/configuration.rst
> [backport] Fix typo in Chainer's configuration documentation

- chainer/gradient_check.py
- tests/chainer_tests/test_gradient_check.py
This PR adds a testing utility to check the validity of `backward` implementation in the new-style function (#2970) for the differentiable backprop (i.e., it checks if backprop through `backward` implementation is valid for computing the "gradients of gradients").
> Add a second-order gradient check

- chainer/__init__.py
- chainer/function.py
- chainer/function_hook.py
- chainer/function_node.py
- docs/source/reference/function_hooks.rst
- tests/chainer_tests/test_function_hook.py
This PR adds `chainer.function_hooks` to `chainer.__init__.py` to align the convention that modules that concrete objects (like inheritance of `Link`) are imported. As this PR is made on top of #3152 to avoid conflicts, I would like this PR to be merged after the PR.
> Add function_hooks to __init__.py

- chainer/__init__.py
- chainer/function.py
- chainer/function_hook.py
- chainer/function_node.py
- docs/source/reference/function_hooks.rst
- tests/chainer_tests/test_function_hook.py
This PR adds `chainer.FunctionHook`, which is an alias of `chainer.function_hook.FunctionHook`. This PR also fixes code so that it does not use `chainer.function.FunctionHook`, which exists for backward compatibility.
> Add alias chainer.FunctionHook

- chainer/functions/pooling/roi_pooling_2d.py
`roi_poolig_2d_fwd` -> `roi_pooling_2d_fwd`
> fix typo in ROIPooling2D

- docs/source/conf.py
Issue: #2822 
Removing "Edit on GitHub" link
* Many people (including me) often confuse it as the link to .py file
* It's often reported broken (#1034, #2822)
TODO: Port to CuPy
> Remove "Edit on GitHub" link

- chainer/functions/array/get_item.py
Currently "Returns" section of `Variable.__getitem__` documentation is broken.
[`https://docs.chainer.org/en/stable/reference/core/generated/chainer.Variable.html#chainer.Variable.__getitem__`](https://docs.chainer.org/en/stable/reference/core/generated/chainer.Variable.html#chainer.Variable.__getitem__)
> Fix Variable.__getitem__ document

- chainer/function_node.py
- chainer/variable.py
This PR adds the function name, specified by `FunctionNode.label`, to the debug messages when `NaN` is detected (both in forward and backward computation).
The example code and the improved error message are as follows:
Code
```
class DummyFunction(chainer.Function):
def forward(self, inputs):
return np.full_like(inputs[0], np.nan, dtype=np.float32),
def backward(self, x, gy):
return None
chainer.set_debug(True)
x = np.random.uniform(-1, 1, (10, 5)).astype(np.float32)
x = DummyFunction()(x)
```
Error message
```
File "test2.py", line 17, in <module>
x = DummyFunction()(x)
File "/Users/oonokenta/sandbox/gx_check/chainer/chainer/function.py", line 211, in __call__
ret = node.apply(inputs)
File "/Users/oonokenta/sandbox/gx_check/chainer/chainer/function_node …
```
> Add function name in the debug message of NaN check

- chainer/functions/noise/dropout.py
#3181 In the original "chainer.using_config('train', train)", the word "train" is duplicated. So I converted the latter one to boolean.
> fixed document of F.dropout into more explanatory

- chainer/testing/array.py
When `assert_allclose` fails, it would be helpful to dump more infomation on arrays.
Previous:
```
error: 1.95503e-05
```
This PR:
```
assert_allclose failed: 
shape: (2, 3, 3, 2)
dtype: float32 float32
i: (0, 2, 0, 1)
x[i]: -0.30263751745224
y[i]: -0.3026570677757263
err[i]: 1.9550323486328125e-05
x: [[[[ 0.43169084  0.16512142]
[ 0.67146325  0.1099173 ]
[ 1.23372531 -0.59125972]]
[[-0.15755028  0.89751655]
[-0.51562357 -0.32308728]
[-0.00440456  0.6219334 ]]
[[-0.20816886 -0.30263752]
[ 0.99176192 -0.08260274]
[ 0.75846857 -0.07695036]]]
[[[-0.41587684  1.23625815]
[ 0.05834302  0.59018832]
[ 1.13860416  0.00345436]]
[[-0.5978561   0.72182804]
[ 0.19278584  0.35793984]
[ 0.22906038 -0.9143526 ]]
[[ 0.41658399  0.69880784]
[-0.09936009 -0.45113131]
[ 0.95919168 -0.27436191]]]]
y: [[[[ …
```
> Dump more info on assert_allclose failure

- chainer/links/model/vision/googlenet.py
- chainer/links/model/vision/resnet.py
- chainer/links/model/vision/vgg.py
Inferring from only one sample with train mode BatchNorm does not work.
I think it is necessary to use `with chainer.using_config('train', False)`.
> use test mode in ResNet predict

- chainer/links/connection/lstm.py
> Improve docs of links/connection/lstm

- chainer/links/connection/linear.py
> Improve docs of links/connection/linear

- chainer/functions/connection/linear.py
- chainer/variable.py
- tests/chainer_tests/function_hooks_tests/test_timer.py
- tests/chainer_tests/functions_tests/connection_tests/test_linear.py
This PR fixes `F.linear` to use the new-style function node interface of #2970.
It depends on #3096 (`check_double_backward`).
> New style linear function

- chainer/variable.py
it is backported in #3197 
According to the documents, `backward_cpu` returns `tuple of numpy.ndarray` objects.
> fix to pass test_function.py in v2

- chainer/functions/connection/linear.py
Documentation of `functions.linear` is broken.
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.linear.html#chainer.functions.linear
> Fix document of functions.linear

- chainer/functions/activation/clipped_relu.py
Documentation of `clipped_relu` is broken.
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.clipped_relu.html
> Fix doc of clipped_relu

- chainer/functions/activation/relu.py
- tests/chainer_tests/functions_tests/activation_tests/test_relu.py
- tests/chainer_tests/test_gradient_check.py
This PR implements new-style version of `F.relu`.
> New style relu

- chainer/__init__.py
- chainer/function_node.py
- chainer/variable.py
- docs/source/reference/core/variable.rst
- tests/chainer_tests/test_variable.py
This PR adds a convenient function `chainer.to_variable`. It can be used to force a value having a type `Variable`. This function is designed to be used in differentiable functions that may skip computation; in such a case, these functions have to conditionally wrap an array by `Variable`. The `to_variable` can be used in such a case. Note that `requires_grad` is set to `False` because of assuming such usage.
> Add chainer.as_variable

- chainer/variable.py
- tests/chainer_tests/test_variable.py
This PR adds `Variable.array` attribute, which is equivalent to and less confusing than `Variable.data`. Fix #2908.
> Add Variable.array that is less confusing than Variable.data

- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/utils/conv.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_depthwise_convolution_2d.py
This PR implements the new style version of `F.convolution_2d` and `F.deconvolution_2d`. These functions are now twice differentiable (but not three times differentiable until some functions used in backward, e.g. `F.sum`, support double backward).
> New style convolution_2d and deconvolution_2d

- chainer/functions/activation/leaky_relu.py
The definition of `leaky_relu` in the current documentation is only valid if `a <= 1`.
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.leaky_relu.html
> Fix doc of leaky_relu

- chainer/datasets/__init__.py
- chainer/datasets/svhn.py
SVHN is very similar to MNIST. I added code that will download and create datasets for train and test samples the same way `get_mnist()` does.
This code requires `scipy` in order to read the matlab format that files are officially provided in.
> Code to fetch the SVHN dataset

- docs/source/tutorial/train_loop.rst
I fixed test code in tutorial to use dummy data instead of mnist data. It is undesirable because it shows download logs and it is heavy.
> Make dummy data for document test code

- chainer/functions/math/exponential.py
- tests/chainer_tests/function_hooks_tests/test_timer.py
- tests/chainer_tests/functions_tests/math_tests/test_exponential.py
New style exp function for `Double backward support for v3`.
> New style exp function

- chainer/functions/array/cast.py
- tests/chainer_tests/functions_tests/array_tests/test_cast.py
We will use `F.cast` in backward of functions supporting mixed-use dtypes after introducing new style functions. This change removes the overhead in the "usual pass" that does not require casting.
> Make F.cast return the input as is if no cast is needed

- docs/source/contribution.rst
I wrote a quick update on the coding guidelines. The new version allows the use of shortcut aliases (e.g. `chainer.Variable` instead of `variable.Variable`) used in the code inside any function/method definitions (unless they are meant to be called from global scope code).
> Update coding guidelines on shortcut aliases

- chainer/functions/loss/mean_squared_error.py
- tests/chainer_tests/functions_tests/loss_tests/test_mean_squared_error.py
This PR is a part of #3147 and apply the new-style API to `mean_squared_error`.
> New style mean_squared_error

- chainer/link.py
- tests/chainer_tests/test_link.py
> [backport] Deny assigning links in ChainList.init_scope()

- chainer/functions/math/batch_l2_norm_squared.py
- chainer/functions/normalization/l2_normalization.py
- chainer/links/connection/linear.py
- chainer/variable.py
- docs/source/conf.py
Fixes #3234.
The problem is in autosummary's algorithm on parsing docstring: https://github.com/sphinx-doc/sphinx/blob/1.6.3/sphinx/ext/autosummary/__init__.py#L341
It treats the substring which ends with a period followed by a space (or a EOL) as the "first sentence", which trucate the string at e.g. "a.k.a. SOMETHING".
This PR interferes that algorithm by placing `\` followed by an extra space before the existing space, which translates to an empty string. (I'm not sure if this is the correct use of the sequence. But at least it works)
Additionally I put a code to check if docstrings are compliant with autosummary's algorithm.
TODO: Port to CuPy
> doc: Fix truncated summary line

- chainer/links/caffe/caffe_function.py
A simple fix for https://github.com/chainer/chainer/issues/3260 that scales the means and variances when parsing Caffe functions if the scaling factor is included in the blob.
https://github.com/BVLC/caffe/issues/4885
> CaffeFunction to take BatchNorm scaling factor into account

- chainer/functions/noise/dropout.py
This is a PR to wrap the result of dropout in test mode with `Variable`.
The reason is as follows.
In general, all functions in `chainer.functions` should return `Variable`. (which is also discussed in #3191)
However, in `chainer.functions.noise.dropout`, @ronekko kindly reported unexpected outputs like below in #3116:
```python
import chainer
x = numpy.ones(5, 'f')
with chainer.using_config('train', False):
y = chainer.functions.dropout(x)
print(type(y))  # <class 'numpy.ndarray'>
y = chainer.functions.dropout(chainer.Variable(x))
print(type(y))  # <class 'chainer.variable.Variable'>
```
This is because input is returned without any modification in test mode in dropout.
> Always return variable in chainer.functions.noise.dropout

- chainer/functions/activation/log_softmax.py
- tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
This PR implements new-style version of `F.log_softmax` as a part of #3147. This function will be used to make `F.softmax_cross_entropy` double-backpropable.
> New style log_softmax

- chainer/gradient_check.py
- tests/chainer_tests/test_gradient_check.py
This PR fixes the bug of `check_double_backward` with `params` option. In order to fully support it, it adds `params_grad_grad` option. It should be merged before v3 RC, otherwise it will be another breaking change.
> Fix params option of check_double_backward

- tests/chainer_tests/functions_tests/activation_tests/test_relu.py
`check_double_backward` in ReLU test is unstable.
> Stable ReLU test

- chainer/training/updaters/multiprocess_parallel_updater.py
- tests/chainer_tests/test_cuda.py
Avoid using deprecated `stream` option in `to_gpu` (#2238)
> Avoid using deprecated stream option in to_gpu

- chainer/cuda.py
- tests/chainer_tests/test_cuda.py
Fixed a test of `to_gpu` with `Variable` argument.
Currently, `ValueError: Unsupported dtype object` is raised instead of `TypeError`.
> Fix test of to_gpu with Variable argument

- chainer/functions/array/rollaxis.py
- tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
This PR applies new-style function API to `F.rollaxis`, as a part of #3147. Double-backpropable version of this function is used in #3296.
> New style rollaxis

- chainer/functions/array/select_item.py
- tests/chainer_tests/functions_tests/array_tests/test_select_item.py
This PR applies new-style function API to `F.select_item`, as a part of #3147. Double-backpropable version of this function is used in #3296.
> New style select_item

- chainer/functions/__init__.py
- chainer/functions/math/matmul.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/math_tests/test_matmul.py
This PR provides compatibility about `batch_matmul`.
`batch_matmul` removed by #2426. But, we can provides it easily.
> Revival batch_matmul for backward compatibility

- chainer/functions/pooling/upsampling_2d.py
This PR improves the speed of Upsampling2D on CPU by avoiding for loops.
| | forward | backward |
|-|---------|-----------|
| before | 0.3773 +- 0.0086 sec | 0.1923 +- 0.0210 sec |
| after | 0.0153 +- 0.0004 sec | 0.0110 +- 0.0003 sec |
| speedup | ~24.7 x | ~17.5 x |
The performance measurement script is here: https://gist.github.com/mitmul/b0041b4afd58eaf9489b423cb0345bbb
> Speedup Upsampling2D on CPU

- chainer/variable.py
- tests/chainer_tests/test_variable.py
I added a quick check to `Variable.backward` to skip backward when no grad is required. Such a case does not happen usually (because the output has `requires_grad=False` when all the inputs have `requires_grad=False`); this PR rather makes it clear when one reads the implementation fo `Variable.backward`.
> Fix Variable.backward for manually edited requires_grad

- chainer/function.py
Backport of #3114
In the previous backport #3162, I discarded the change to `function_hook.py`, but I should have redirected the change to `function.py` instead.
> [Backport] Fix errors in docstrings (2)

- chainer/gradient_check.py
- chainer/variable.py
- tests/chainer_tests/test_variable.py
This PR makes the double backprop support of `Variable.backward()` optional so that existing code does not suffer from increasing memory consumption and possible slow down. It replaces #3271 because this PR automatically stops creating computational graph in `backward` called from `GradientMethod.update()`.
> Make double backprop support optional

- chainer/functions/loss/softmax_cross_entropy.py
- functions/loss/softmax_cross_entropy.py
> Improve docs of softmax_cross_entropy

- chainer/testing/helper.py
Fixes #3321.
In Python2, `warnings.warn` will not raise warning multiple times from the same stack frame.
> Skip assert_warns check in Python 2

- tests/chainer_tests/test_cuda.py
When `stream` argument is not `None`, `to_gpu` method raises warnings. We need to ignore them in the test.
related to #3282
> Ignore warnings for to_gpu

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
> Avoid running certain hooks on uninitialized params

- docs/source/reference/initializers.rst
`initializers.NaN` is not documented.
> doc: Add initializers.NaN

- chainer/links/connection/gru.py
Current documentation incorrectly describes `L.GRU` as stateless.
> doc: Fix GRU stateless/stateful

- chainer/functions/noise/dropout.py
- tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
This PR implements new-style version of `F.dropout`.
It supports double backward for Chainer v3.
It is related to #3147 .
> New style dropout function

- chainer/functions/activation/log_softmax.py
- tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
Related to #3072 
Currently, `non C-contiguous array` is not supported for activation `log_softmax`.
```python
data = np.ones((2, 2), dtype=np.float32)
data = chainer.cuda.to_gpu(data, 0)
x = chainer.Variable(data)
ys = F.split_axis(x, 2, axis=1)
y = F.log_softmax(ys[0])
```
```
In [15]: y = F.log_softmax(ys[0])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-d5fb97a0352c> in <module>()
----> 1 y = F.log_softmax(ys[0])
/home/shingo/chainer/chainer/functions/activation/log_softmax.pyc in log_softmax(x)
163
164     """
--> 165     return LogSoftmax().apply((x,))[0]
/home/shingo/chainer/chainer/function_node.pyc in …
```
> call ascongituousarray in log_softmax

- tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py
get_device is deprecated. I replaced it with get_device_from_id.
> Replace get_device

- chainer/functions/math/exponential.py
Slightly optimized backward computation of `F.log2` and `F.log10`.
Time per single `F.log2.backward` call:
CPU:
```
BEFORE: 78.110 us   +/- 3.850 us
AFTER:  70.842 us   +/- 2.635 us
```
GPU:
```
BEFORE: 192.078 us   +/- 6.653 us
AFTER:  166.129 us   +/- 7.813 us
```
> Optimize backward of log2 and log10

- chainer/functions/array/spatial_transformer_grid.py
- chainer/functions/array/spatial_transformer_sampler.py
- tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_grid.py
- tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py
SpetialTransformerGrid and SpatialTransofrmerSampler are using `use_cudnn` flags to switch cudnn and non-cudnn implementation, so it ignores global/local configuration. Those `use_cudnn` should be replaced with `chainer.should_use_cudnn('>=auto')`.
> Remove use_cudnn argument from SpetialTransformerGrid/Sampler

- chainer/function_hook.py
- chainer/function_hooks/__init__.py
- chainer/function_hooks/cupy_memory_profile.py
- chainer/function_node.py
- tests/chainer_tests/function_hooks_tests/test_cupy_memory_profile.py
Fix https://github.com/chainer/chainer/issues/918
This requires cupy memory hook added at https://github.com/cupy/cupy/pull/264
Code example::
from chainer.function_hooks import CupyMemoryProfileHook
hook = CupyMemoryProfileHook()
with hook:
trainer.run()
hook.print_report()
Output example::
FunctionName  UsedBytes  AcquiredBytes  Occurrence
LinearFunction     5.16GB       179.98MB        3900
ReLU   991.82MB       458.97MB        2600
SoftmaxCrossEntropy     7.71MB         5.08MB        1300
Accuracy   617.97KB       351.00KB         700
where *FunctionName* is the name of function that calls the hook, and
*UsedBytes* is the memory bytes the function used from cupy memory
pool, and *AcquiredBytes* is the actual memory bytes the cupy memory
pool acquired from GPU device on the function …
> Cupy memory profiler with cupy memory hook

- examples/mnist/train_mnist.py
- examples/vae/README.md
- examples/vae/train_vae.py
Setting `matplotlib.use('Agg')` inside code might cause errors in some environments other than linux.
Using `MPLBACKEND=Agg` environmental variable is more preferable I think.
> Avoid to import matplotlib to set its backend Agg in code

- docs/source/compatibility.rst
- docs/source/contribution.rst
This is an update on the contribution guide that allows one to make a feature backport to the stable version.
> Add minor version policy and feature backport policy

- chainer/functions/normalization/batch_normalization.py
- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
This PR is a part of #3147. It adds double backprop support of `F.batch_normalization` and `F.fixed_batch_normalization`. Currently, the second gradient is written down with plain numpy/cupy APIs without any fusion. It would be better for performance to fuse kernels in CUDA, which is future work.
> New style batch_normalization and fixed_batch_normalization

- chainer/__init__.py
- chainer/function_node.py
- docs/source/reference/core/function.rst
- tests/chainer_tests/test_function_node.py
This PR implements `chainer.grad` function proposed at #2871. This function implements backpropagation. The most important difference from `Variable.backward()` is that users specify the set of input variables to which the errors should be backpropagated. The resulting gradients are not accumulated to `Variable.grad_var` attribute by default, so it's easier to use when users want to compute gradients w.r.t. variables not spanning the whole parameter set. This function also skips unnecessary paths to compute gradients w.r.t. specified inputs in combination with the economical backprop API of #2970.
The usage is simple:
```py
grad_inputs = chainer.grad(outputs, inputs)
```
You can also specify the initial gradients for outputs and inputs. The initial gradients for inputs are used for …
> grad function

- appveyor.yml
- chainer/iterators/multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
I rewrote the `MultiprocessIterator` using Python's `Pool` functionality. It makes codes simpler and faster, as well as making orphan/zombie process less likely.
Instead of previous "one prefetch invoked at one fetch" implementation, in my implementation background thread invokes prefetch freely, only if the maximum prefetch number allows. I think this strategy is better for utilizing idle CPU/IO time.
Resetting an iterator in the mid of iteration is also supported. Tests are changed accordingly.
The second commit changes per-batch-item shared memory allocation to the bulk allocation. This improved performance a little. 
I took a benchmark of `examples/mnist/train_mnist.py`, with `SerialIterator` changed to `MultiprocessIterator`.  It was done on EC2 g3.4xlarge instance.
```
time python …
```
> Improve MultiprocessIterator performance, functionality and stability, using Pool

- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
These tests have several problems (see #3383).
Because this renders other PRs impossible to be tested, I want to temporarily skip them.
> test: Skip multiprocess interrupt tests

- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
This PR is a backport of #3393
> [backport] test: Skip multiprocess interrupt tests

- chainer/iterators/multiprocess_iterator.py
When `type(dataset[i]) == np.ndarray`, shared memory is not used.
This PR fixes the problem.
Benchmark
```python
import chainer
import time
batch_size = 128
n_batch = 5
x = np.random.randint(
0, 2 ** 10, size=(batch_size * n_batch, 300 * 300 * 3)).astype(np.int32)
it = chainer.iterators.MultiprocessIterator(
x, batch_size, shared_mem=300 * 300 * 3 * 4, shuffle=False)
start = time.time()
results = []
print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
for i in range(n_batch):
results.append(next(it))
print('elapsed time {}s'.format(time.time() - start))
np.testing.assert_almost_equal(x, np.concatenate(results))
```
Before: elapsed time 1.141466856s
After: elapsed time 0.356211900711s
> Improve performance of MultiprocessIterator for non tuple/dict datasets

- docs/source/compatibility.rst
- docs/source/install.rst
- docs/source/reference/core/configuration.rst
> fix typo in chainer doc

- tests/chainer_tests/datasets_tests/test_svhn.py
This PR adds tests for `chainer.datasets.get_svhn`.
> Write test for get_svhn.py

- tests/chainer_tests/test_link.py
This is a PR to add tests to `Link.__delattr__` and `Chain.__delattr__`, which is pointed out in #2930.
> Add tests for __delattr__ in Link and Chain

- tests/chainer_tests/functions_tests/math_tests/test_ceil.py
- tests/chainer_tests/functions_tests/math_tests/test_floor.py
This PR changes the distribution from which inputs are sampled in TestCeil so that tests for the function are likely to pass more. Specifically, we sample less likely from discontinuous points (i.e. integer points).
> Stabilize unit tests for F.Ceil and F.Floor

- chainer/iterators/multiprocess_iterator.py
> [backport] Improve performance of MultiprocessIterator for non tuple/dict datasets

- docs/source/compatibility.rst
- docs/source/install.rst
- docs/source/reference/core/configuration.rst
> [backport] fix typo in chainer doc
