chainer/functions/loss/hinge.py, tests/chainer_tests/functions_tests/loss_tests/test_hinge.py
This PR adds `reduce` option to `F.hinge_loss`. Related to #2558
=> Add reduce option to hinge loss

examples/README.md
=> Add index page for examples

chainer/links/model/vision/googlenet.py
Fix for test_init_docstring.py
=> Fix for test_init_docstring.py

README.md
I moved information links to Top to show more easily.
=> move Information to top

chainer/functions/loss/vae.py, tests/chainer_tests/functions_tests/loss_tests/test_vae.py
This PR add reduce option to F.bernoulli_nll following the design discussed in #2325 with the same spirit of #2519
=> Add reduce option to GaussianNLL

chainer/optimizer.py
Fix https://github.com/pfnet/chainer/issues/2521.
=> Use cleargrads by default

chainer/links/model/vision/resnet.py
=> Fix ResNet101Layers to load pretrained model correctly

chainer/functions/pooling/pooling_2d.py, chainer/functions/pooling/pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
=> Support non-contiguous arrays in pooling functions

chainer/functions/loss/black_out.py, tests/chainer_tests/functions_tests/loss_tests/test_black_out.py
This PR adds `reduce` option to `F.black_out`. I also write its specification in more detail. Related to #2558.
=> Add reduce option to F.black_out

tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
I found a typo in `TestContrastive`.
=> Fix TestContrastive

docs/source/tutorial/convnet.rst
There are mistakes made by me. Sorry about that, this PR fixes those mistakes in model definitions.
=> Fix some mistakes in ConvNet tutorial

chainer/functions/connection/convolution_nd.py
- functions/connection/convolution_nd
=> Improve docs of convolution_nd

chainer/links/normalization/batch_normalization.py, chainer/utils/argument.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
I added obsolete argument to show error.
=> Raise error when obsolete argument is given

chainer/functions/loss/contrastive.py, tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
This PR adds `reduce` option to `F.contrastive`. I also fix its document. Related to #2558
=> Add reduce option to F.contrastive

chainer/functions/array/cast.py
=> Release inputs of cast

chainer/functions/array/broadcast.py
=> Release inputs of broadcast

chainer/variable.py, tests/chainer_tests/test_variable.py
=> Fix behavior of tranpose method of Variable class

docs/source/tutorial/basic.rst
Remove `use_cleargrads` from tutorial
=> Remove use_cleargrads from tutorial

chainer/functions/array/transpose_sequence.py
=> Release inputs of transpose_sequence

chainer/functions/array/select_item.py
=> Release inputs of select_item

chainer/functions/array/get_item.py
=> Release inputs of get_item

chainer/functions/array/expand_dims.py, chainer/functions/array/flatten.py, chainer/functions/array/pad.py, chainer/functions/array/permutate.py, chainer/functions/array/reshape.py, chainer/functions/array/rollaxis.py, chainer/functions/array/space2depth.py, chainer/functions/array/squeeze.py, chainer/functions/array/swapaxes.py, chainer/functions/array/tile.py, chainer/functions/array/transpose.py, chainer/functions/array/where.py
=> Release inputs of array method

chainer/functions/array/copy.py
=> Release inputs of copy

chainer/functions/array/depth2space.py
=> Relase inputs of depth2space

chainer/functions/array/fliplr.py, chainer/functions/array/flipud.py
=> Release inputs of flip functions

tests/chainer_tests/links_tests/connection_tests/test_highway.py
Fix #2649 
It seems numerical gradient of `relu` activation is causing the problem.
This PR replaces it with `tanh`.
=> Fix numerical issue in test_highway

examples/imagenet/resnet50.py, examples/imagenet/train_imagenet.py
* Added ResNet50 example, originally written by Kudo-san
* Modified train_imagenet.py accordingly.
The result is:
epoch       iteration   main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  lr
2           1000        1.79846                           0.377313                                 0.01
4           2000        1.28585                           0.525031                                 0.01
7           3000        1.13306                           0.581438                                 0.01
9           4000        1.02884                           0.61925                                  0.01
=> Add resnet50 example

examples/imagenet/resnet50.py
Somehow this commit ( https://github.com/pfnet/chainer/pull/2644/commits/2c7affce0db397a3f426a1e5204749a2134e058b ) hasn't been merged.
=> Fix ResNet50 in examples/imagenet

examples/imagenet/resnet50.py
=> Fix syntax errors

chainer/functions/array/hstack.py, chainer/functions/array/stack.py, chainer/functions/array/vstack.py
- functions/array/stack
- functions/array/hstack
- functions/array/vstack
doctest result is
```
Document: reference/functions
-----------------------------
1 items passed all tests:
117 tests in default
117 tests in 1 items.
117 passed and 0 failed.
Test passed.
```
=> Improve docs of stack, vstack, hstack

chainer/functions/evaluation/accuracy.py
- functions/evaluation/accuracy
=> Improve docs of accuracy

chainer/functions/connection/deconvolution_2d.py
- functions/connection/deconvolution_2d
=> Improve docs of deconvolution_2d

chainer/functions/array/dstack.py
=> Improve docs of dstack

chainer/functions/noise/dropout.py, chainer/functions/noise/gaussian.py, chainer/functions/noise/zoneout.py
I fixed noise inputs to release inputs.
related to #2579
=> Release inputs of noise functions

chainer/functions/pooling/average_pooling_2d.py, chainer/functions/pooling/average_pooling_nd.py, chainer/functions/pooling/max_pooling_2d.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/roi_pooling_2d.py, chainer/functions/pooling/unpooling_2d.py, chainer/functions/pooling/unpooling_nd.py, chainer/functions/pooling/upsampling_2d.py
I fixed pooling functions to release inputs.
related to #2579
=> Release inputs of pooling functions

chainer/functions/array/expand_dims.py
=> Improve docs of expand_dims

chainer/functions/math/ceil.py, chainer/functions/math/exponential.py, chainer/functions/math/exponential_m1.py, chainer/functions/math/floor.py, chainer/functions/math/identity.py, chainer/functions/math/inv.py, chainer/functions/math/minmax.py, chainer/functions/math/sqrt.py, chainer/functions/math/squared_difference.py, chainer/functions/math/sum.py
I fixed math functions to release inputs.
related to #2579
=> Release inputs of math functions

chainer/functions/array/dstack.py, chainer/functions/array/hstack.py, chainer/functions/array/vstack.py
=> Release inputs of stack methods

chainer/functions/array/broadcast.py
I think these are forgotten in #2622.
=> Release inputs of broadcast (revisited)

chainer/functions/array/copy.py
=> Improve docs of copy

chainer/functions/array/depth2space.py, chainer/functions/array/space2depth.py
- functions/array/depth2space
- functions/array/space2depth
=> Improve docs of depth2space, space2depth

chainer/link.py
This PR remove unreachable code in link.py
=> remove unreachable code in link.py

chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/deconvolution_nd.py
- functions/connection/deconvolution_nd
- functions/connection/deconvolution_2d (just added the output variables descriptions)
=> Improve docs of deconvolution nd

chainer/functions/__init__.py, chainer/functions/array/spatial_transformer_grid.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_grid.py
Merge after #2272.
This PR adds a function that generates sampling points described in https://arxiv.org/abs/1506.02025.
=> Add spatial_transformer_grid

cupy/core/core.pyx, tests/cupy_tests/core_tests/test_ndarray_indexing.py, tests/cupy_tests/manipulation_tests/test_rearrange.py
=> Fix error on reverse indexing empty dimension

chainer/functions/loss/softmax_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
I implement `broadcast_to` and use it.
=> Support broadcasting on numpy==1.9

chainer/training/extensions/exponential_shift.py, tests/chainer_tests/training_tests/extensions_tests/test_exponential_shift.py
=> Fix resuming issue of exponential shift

chainer/functions/loss/negative_sampling.py, chainer/links/loss/negative_sampling.py, tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py, tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
I added `reduce` option to negative sampling. And i fixed the original test code because it only checks results of gpu is same as that of gpu.
=> Add reduce option to links.NegativeSampling and functions.negative_sampling

chainer/functions/loss/ctc.py, tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
This PR add `reduce` option to `F.ConnectionistTemporalClassification` and `F.connectionist_temporal_classification`
Related to #2558
=> Add reduce option to F.ConnectionistTemporalClassification

chainer/links/connection/depthwise_convolution_2d.py
This PR removes `wscale` and `bias` option from `L.DepthwiseConvolution2D`.  It also removes `initialW` attribute because it does not used in the link. Further, the reason why `L.Convolution2D` is for the backward compatibility, but this link does not have a compatibility we should keep.
Although this PR changes the API of the link, it does not break compatibility because this link is not released in any version.
Related #2691
=> Clean up the API of L.DepthwiseConvolution2D

chainer/links/activation/simplified_dropconnect.py
This PR removes `wscale` option from and add `nobias` option to `L.DepthwiseConvolution2D`.
Although this PR changes the API of the link, it does not break compatibility because this link is not released in any version.
Related #2691
=> Clean up the API of L.SimplifiedDropConnect

chainer/functions/activation/softmax.py
=> Improve doc of softmax

chainer/cuda.py, chainer/function_hooks/debug_print.py, chainer/functions/array/split_axis.py, chainer/functions/loss/ctc.py, chainer/functions/loss/softmax_cross_entropy.py, chainer/functions/noise/simplified_dropconnect.py, chainer/functions/pooling/pooling_nd_kernel.py, chainer/links/connection/gru.py, chainer/links/connection/lstm.py, chainer/links/connection/n_step_gru.py, chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py, chainer/links/connection/zoneoutlstm.py, chainer/links/loss/black_out.py, chainer/optimizer.py, chainer/testing/unary_math_function_test.py, chainer/training/extensions/log_report.py, chainer/training/extensions/plot_report.py, chainer/training/updaters/multiprocess_parallel_updater.py, chainer/utils/conv_nd_kernel.py
=> Fix import style

chainer/function.py, chainer/variable.py, tests/chainer_tests/test_variable.py
The current v2 broke some users' code unintentionally. This PR fixes it.
=> Add Variable.creator setter

chainer/__init__.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py, tests/chainer_tests/test_init.py
=> Fix for no cudnn environment

tests/chainer_tests/serializers_tests/test_hdf5.py
=> Fix for no h5py environment

tests/chainer_tests/training_tests/extensions_tests/test_computational_graph.py
=> Fix flake8

README.md
I think we need to add a comment to README in the master branch.
=> Update README to give a link to the stable branch

docs/source/contribution.rst
This PR edits the contribution guide for the new branch strategy discussed off-line.
=> Adopt the new branch strategy

docker/python2/Dockerfile, docker/python3/Dockerfile
=> Use the hot fix version of CuPy in Dockerfiles

docs/source/reference/extensions.rst
Add doc reference for the ParameterStatistics extension.
=> Add doc ref for ParameterStatistics extension

examples/imagenet/train_imagenet_data_parallel.py
Thank you for your feed back, @apple2373 !
=> Replace the URL for the instruction of NCCL

docs/source/reference/extensions.rst, docs/source/tutorial/convnet.rst, examples/imagenet/train_imagenet_data_parallel.py
=> Fix document

docs/source/reference/extensions.rst, docs/source/tutorial/convnet.rst, examples/imagenet/train_imagenet_data_parallel.py
Rel #2805 
This PR is backport PR for v2.
=> [backport] Fix document

chainer/variable.py, docs/source/reference/core/variable.rst
This PR fixes the arguments of Variable in the document and adds Parameter and VariableNode to the document.
=> Fix Variable documentation

chainer/functions/loss/negative_sampling.py
I improved forward function of negative sampling.
=> Improve negative sampling gpu fwd

chainer/variable.py
=> Fix a typo

examples/seq2seq/europal.py, examples/seq2seq/seq2seq.py
=> modify seq2seq europarl

docs/source/tutorial/convnet.rst
=> Fix some typos in convnet tutorial

chainer/variable.py
=> [backport] V2 fix doc variable

docs/source/conf.py
This PR puts a link to GitHub source line to each of object documentation, instead of generating individual source page.
=> Link to GitHub source page

docs/source/conf.py
=> [backport] Link to github 

chainer/datasets/__init__.py, chainer/datasets/concatenated_dataset.py, docs/source/reference/datasets.rst, tests/chainer_tests/datasets_tests/test_concatenated_dataset.py
I added a new dataset wrapper, `ConcatenatedDataset`. This is similar to `SubsetDataset` but this dataset represents a union set of some base datasets.
=> Add ConcatenatedDataset

docs/source/upgrade.rst
=> [backport] Fix markup bug in upgrade.rst

chainer/testing/training.py, tests/chainer_tests/training_tests/test_trainer.py
=> Fix TrainerTest where elapsed time had been zero with imprecise clock

chainer/testing/training.py
In v1, I have sent a PR to fix this bug (#2472). However, it is restored in v2.
=> Fix get_trainer_with_mock_updater

chainer/links/model/vision/resnet.py
`n_layers` argument for `ResNetLayers` was missing.
=> Fix a minior bug of resnet.py

docs/Makefile, docs/source/_templates/autosummary/class.rst
These are mainly used in:
- Datasetes
- Iterators
- Variable and Parameter
=> Add additional special methods in class template

chainer/functions/array/flatten.py, chainer/functions/array/reshape.py
- functions/array/flatten
- functions/array/reshape
=> Improve docs of flatten, reshape

chainer/training/extensions/exponential_shift.py, chainer/training/extensions/linear_shift.py, tests/chainer_tests/training_tests/extensions_tests/test_exponential_shift.py, tests/chainer_tests/training_tests/extensions_tests/test_linear_shift.py
=> [backport] Fix resuming issue of *Shift extensions

chainer/links/model/vision/resnet.py
This is a backport PR of #2821 to v2.
=> [backport] Fix a minior bug of resnet.py

chainer/testing/training.py, tests/chainer_tests/training_tests/test_trainer.py
=> [backport] Fix TrainerTest where elapsed time had been zero with imprecise clock

chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py, tests/chainer_tests/links_tests/model_tests/test_vision.py
This PR is the backport of #2810
=> [Backport] Make vision models copyable(#2810)

chainer/testing/training.py
=> [Backport] Fix get_trainer_with_mock_updater (#2824)

chainer/cuda.py, chainer/link.py, docs/source/_static/css/modified_theme.css, docs/source/_templates/autosummary/class.rst, docs/source/reference/caffe.rst, docs/source/reference/check.rst, docs/source/reference/core/configuration.rst, docs/source/reference/core/dataset.rst, docs/source/reference/core/debug.rst, docs/source/reference/core/function.rst, docs/source/reference/core/link.rst, docs/source/reference/core/optimizer.rst, docs/source/reference/core/serializer.rst, docs/source/reference/core/training.rst, docs/source/reference/core/variable.rst, docs/source/reference/datasets.rst, docs/source/reference/extensions.rst, docs/source/reference/function_hooks.rst, docs/source/reference/functions.rst, docs/source/reference/graph.rst, docs/source/reference/initializers.rst, docs/source/reference/iterators.rst, docs/source/reference/links.rst, docs/source/reference/optimizers.rst, docs/source/reference/serializers.rst, docs/source/reference/triggers.rst, docs/source/reference/util/algorithm.rst, docs/source/reference/util/cuda.rst, docs/source/reference/util/experimental.rst, docs/source/reference/util/reporter.rst
This PR is the backport of #2766
=> [Backport] Improve browsability of API reference (#2766)

chainer/cuda.py, docs/source/conf.py, docs/source/install.rst, docs/source/tutorial/gpu.rst
The URL of CuPy documents was changed.
=> Fix CuPy links

chainer/functions/noise/dropout.py
=> Optimized dropout forward

chainer/cuda.py, docs/source/conf.py, docs/source/install.rst, docs/source/tutorial/gpu.rst
=> [backport] Fix CuPy links

chainer/link.py, tests/chainer_tests/test_link.py
Current code uses incorrect type object.
=> Fix hidden variable in Link and Chain

chainer/link.py, tests/chainer_tests/test_link.py
=> [backport] Fix hidden variable in Link and Chain

chainer/functions/array/flatten.py, chainer/functions/array/reshape.py
This PR is the backport of #2678
=> [Backport] Improve docs of flatten, reshape (#2678)

chainer/training/updaters/multiprocess_parallel_updater.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
`link.params()` return order is unstable, So, this code sorts by parameter name.
=> Fix gather and scatter

docs/source/reference/core/optimizer.rst
=> [backport] Add documents of Hyperparmaeter and UpdateRule

docs/source/reference/triggers.rst
=> [backport] Add BestValueTrigger to the document

chainer/functions/pooling/max_pooling_nd_kernel.py
=> [backport] Remove INFINITY

chainer/training/updaters/multiprocess_parallel_updater.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
=> [backport] Fix gather and scatter

chainer/cuda.py, chainer/optimizer.py
=> Avoid get_device

tests/chainer_tests/functions_tests/math_tests/test_bias.py, tests/chainer_tests/functions_tests/math_tests/test_scale.py, tests/chainer_tests/links_tests/connection_tests/test_bias.py, tests/chainer_tests/links_tests/connection_tests/test_scale.py
=> Replace DebugMode with using_debug

tests/chainer_tests/functions_tests/math_tests/test_bias.py, tests/chainer_tests/functions_tests/math_tests/test_scale.py, tests/chainer_tests/links_tests/connection_tests/test_bias.py, tests/chainer_tests/links_tests/connection_tests/test_scale.py
=> [backport] Replace DebugMode with using_debug

chainer/links/activation/simplified_dropconnect.py, chainer/links/caffe/caffe_function.py, chainer/links/connection/depthwise_convolution_2d.py, chainer/links/connection/n_step_gru.py, chainer/links/connection/n_step_rnn.py, tests/chainer_tests/serializers_tests/test_hdf5.py, tests/chainer_tests/serializers_tests/test_npz.py
`init_scope` is recommended now.
=> Use init_scope

chainer/cuda.py, chainer/optimizer.py
=> [backport] Avoid get_device

chainer/functions/loss/mean_squared_error.py, chainer/functions/loss/squared_error.py
This PR adds a little more descriptions of `F.squared_error` and `F.mean_squared_error`.
=> Add description of F.squared_error and F.mean_squared_error

chainer/links/normalization/batch_normalization.py
=> Fix BatchNormalization docstring

chainer/links/activation/simplified_dropconnect.py, chainer/links/caffe/caffe_function.py, chainer/links/connection/depthwise_convolution_2d.py, chainer/links/connection/n_step_gru.py, chainer/links/connection/n_step_rnn.py, tests/chainer_tests/serializers_tests/test_hdf5.py, tests/chainer_tests/serializers_tests/test_npz.py
=> [backport] Use init_scope

chainer/variable.py
Improve `_check_grad_type` performance.
=> Improve _check_grad_type

tests/chainer_tests/links_tests/connection_tests/test_tree_lstm.py
=> Remoe get_device in test

chainer/links/normalization/batch_normalization.py
This PR is a backport PR of https://github.com/chainer/chainer/pull/2926
=> [backport] Fix BatchNormalization docstring #2926

chainer/training/updaters/multiprocess_parallel_updater.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
=> Pass raw arrays to the loss function in `MultiprocessParallelUpdater`

tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
I replaced assertRegexp with assertRegex. It is deprecated.
=> Replace assertRegexp with assertRegex

tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py, tests/chainer_tests/links_tests/connection_tests/test_n_step_gru.py, tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py, tests/chainer_tests/links_tests/connection_tests/test_n_step_rnn.py, tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py, tests/chainer_tests/serializers_tests/test_hdf5.py, tests/chainer_tests/serializers_tests/test_npz.py, tests/chainer_tests/test_link.py
I replaced zerograds in unittests with cleargrads.
=> Use cleargrads instead of zerograds

tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
This is a backport PR of #2946
=> [backport] Replace assertRegexp with assertRegex

chainer/functions/loss/mean_squared_error.py, chainer/functions/loss/squared_error.py
This is a backport PR of https://github.com/chainer/chainer/pull/2941
=> [backport] Add description of F.squared_error and F.mean_squared_error

tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py, tests/chainer_tests/links_tests/connection_tests/test_n_step_gru.py, tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py, tests/chainer_tests/links_tests/connection_tests/test_n_step_rnn.py, tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py, tests/chainer_tests/serializers_tests/test_hdf5.py, tests/chainer_tests/serializers_tests/test_npz.py, tests/chainer_tests/test_link.py
This is a backport PR of #2945.
=> [backport] Use cleargrads instead of zerograds

tests/chainer_tests/optimizers_tests/test_optimizers.py, tests/chainer_tests/serializers_tests/test_hdf5.py, tests/chainer_tests/test_link.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
This PR is a backport PR of #2949
=> [backport] Use init_scope #2949

chainer/optimizers/adam.py
This PR is a backport PR of #2910
=> [backport] Fix a bug dependent on glibc version

chainer/links/connection/n_step_gru.py, chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py
=> [backport] Fix typos

chainer/variable.py, docs/source/reference/core/variable.rst
=> [backport] Fix Variable documentation

docs/source/reference/functions.rst
=> [backport] Register squared error to docs

setup.py
=> [backport] Add mock to install_requires

chainer/variable.py
This PR reduces initialization time.
=> Avoid gpu copy in initialize

tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py, tests/chainer_tests/initializer_tests/test_orthogonal.py, tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py, tests/chainer_tests/links_tests/connection_tests/test_zoneoutlstm.py, tests/chainer_tests/optimizers_tests/test_optimizers.py, tests/chainer_tests/test_gradient_check.py
I removed debug prints from the test code.
=> Remove debug print

chainer/training/updater.py
This PR adds documents to several methods of `StandardUpdater` and `ParallelUpdater`.
=> Improve documents of StandardUpdater and ParallelUpdater

tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py, tests/chainer_tests/initializer_tests/test_orthogonal.py, tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py, tests/chainer_tests/links_tests/connection_tests/test_zoneoutlstm.py, tests/chainer_tests/optimizers_tests/test_optimizers.py, tests/chainer_tests/test_gradient_check.py
=> [backport] Remove debug print

chainer/functions/pooling/roi_pooling_2d.py
=> [backport] Use zeros instead of empty for ROIPooling2D CPU mode

chainer/functions/pooling/upsampling_2d.py
=> [backport] Fix the docstring of Upsampling2D

chainer/functions/connection/bilinear.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/deconvolution_nd.py, chainer/functions/connection/dilated_convolution_2d.py, chainer/functions/connection/linear.py, chainer/utils/type_check.py
This PR deletes type check at backward because it is redundant.
=> Improve same_types and remove checking in backward

chainer/variable.py
=> [backport] Avoid gpu copy in initialize

chainer/training/updater.py
=> [backport] Improve documents of StandardUpdater and ParallelUpdater

README.md
=> [backport] Add links to slack archive to README

chainer/gradient_check.py
This PR uses `cuda.reduce` to reduce CUDA kernel launching.
=> Improve numerical grad performance on GPU

.travis.yml
=> Remove cython coding style check

.travis.yml
=> [backport] Remove cython coding style check

chainer/functions/loss/negative_sampling.py
Einsum is faster than for loop.
=> Use einsum in negative sampling foward

chainer/gradient_check.py
=> [backport] Improve numerical grad performance on GPU

chainer/link.py
=> [backport] fix typo

chainer/functions/loss/negative_sampling.py
=> [backport] Use einsum in negative sampling foward

docs/source/reference/core/training.rst
This PR adds the document of `MultiprocessParallelUpdater` to the document.
=> Add MultiprocessParallelUpdater to the document

chainer/testing/__init__.py, chainer/testing/random.py
This is Chainer counterpart of https://github.com/cupy/cupy/pull/82.
(See also: https://github.com/cupy/cupy/pull/222)
=> Deterministic test (Chainer)

docs/source/reference/core/training.rst
=> [backport] Add MultiprocessParallelUpdater to the document

tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
I replaced `DummyUpdater` with `testing.get_trainer_with_mock_updater`.
=> use get_trainer_with_mock_updater in test of ManualScheduleTrigger

chainer/functions/array/tile.py
=> [backport] Improve docs of tile

docs/source/conf.py
=> [backport] Fix GitHub link

examples/reinforcement_learning/README.md, examples/reinforcement_learning/ddpg_pendulum.py, examples/reinforcement_learning/dqn_cartpole.py
This is a v2 backport PR of #1991.
=> [backport] Add deep reinforcement learning examples

chainer/functions/__init__.py, chainer/functions/activation/selu.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/activation_tests/test_selu.py
This PR adds the SELU activation function, proposed in https://arxiv.org/abs/1706.02515. This is asked by @beam2d -san and Crissman-san.
=> Add SELU activation function

chainer/training/triggers/manual_schedule_trigger.py, tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
merge after #2987 
This PR follows the modifications conducted in #2484.
=> add serialization to ManualScheduleTrigger

chainer/cuda.py, chainer/links/connection/gru.py, chainer/links/model/vision/googlenet.py, chainer/training/updaters/multiprocess_parallel_updater.py, examples/README.md, examples/dcgan/README.md
`pfnet/chainer` is old. I replaced it with `chainer/chainer`.
=> Update pfnet/chainer -> chainer/chainer

chainer/cuda.py, chainer/links/connection/gru.py, chainer/links/model/vision/googlenet.py, chainer/training/updaters/multiprocess_parallel_updater.py, examples/README.md, examples/dcgan/README.md
=> [backport] Update pfnet/chainer -> chainer/chainer

.gitignore
Port of https://github.com/cupy/cupy/pull/304 and https://github.com/cupy/cupy/pull/319
=> Ignore generated references and tags

.gitignore
=> [backport] Ignore generated references and tags

chainer/training/updater.py
Add document of updater where TODO tag was set.
=> Add documentation of updater.

chainer/training/updater.py
=> [backport] Add documentation of updater.

chainer/functions/activation/softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
=> Call ascontiguousarray in softmax

docs/source/contribution.rst
=> [backport] Wording in contribution guide

chainer/training/updater.py
=> [backport] fixed :module: to :mod:

chainer/functions/activation/softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
=> [backport] Call ascontiguousarray in softmax

chainer/functions/math/sqrt.py, chainer/gradient_check.py
=> [backport] Fix copy

chainer/functions/__init__.py, chainer/functions/math/prod.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_prod.py
I implemented `F.prod` based on [`F.sum`](https://github.com/chainer/chainer/blob/d62be84d0fa4375d0fe18e5e6d40bc02c1847e5e/chainer/functions/math/sum.py).
=> Implement prod function

setup.cfg
Configure flake8 to ignore the .git directory.
=> Configure flake8 to ignore the .git directory

setup.cfg
=> [backport] Configure flake8 to ignore the .git directory

chainer/training/__init__.py, chainer/training/extensions/parameter_statistics.py
=> [backport] Import example modules and util in chainer.training.__init__

chainer/functions/noise/dropout.py
add the assert in ``chainer.functions.Dropout.__init__`` for dropout_ratio.
=> Check the ratio of dropout

chainer/links/model/vision/resnet.py
=> [backport] Fix _make_npz for ResNetLayers

docs/source/conf.py
Port from https://github.com/cupy/cupy/pull/354
=> Hide source link for alien objects

chainer/functions/noise/dropout.py
=> [backport] Check the ratio of dropout

chainer/training/extensions/plot_report.py, tests/chainer_tests/training_tests/extensions_tests/test_plot_report.py
=> [backport] Dynamically import matplotlib.pyplot in PlotReport

chainer/initializer.py, chainer/initializers/constant.py, chainer/initializers/orthogonal.py, chainer/initializers/uniform.py, chainer/link.py, chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py, chainer/links/normalization/batch_normalization.py, chainer/links/normalization/layer_normalization.py, chainer/optimizer.py, chainer/optimizers/ada_delta.py, chainer/optimizers/ada_grad.py, chainer/optimizers/adam.py, chainer/optimizers/momentum_sgd.py, chainer/optimizers/nesterov_ag.py, chainer/optimizers/rmsprop.py, chainer/optimizers/rmsprop_graves.py, chainer/optimizers/sgd.py, chainer/optimizers/smorms3.py, chainer/training/extension.py, chainer/training/extensions/parameter_statistics.py, chainer/training/triggers/__init__.py, chainer/variable.py, docs/source/reference/core/optimizer.rst, docs/source/tips.rst
=> [backport] Fix doc warnings

docs/source/conf.py
=> [backport] Hide source link for alien objects

chainer/functions/__init__.py, chainer/functions/math/trigonometric.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_trigonometric.py
=> Add the arctan2 function

chainer/functions/math/average.py, tests/chainer_tests/functions_tests/math_tests/test_average.py
I fixed functions.average to support tuples for axis argument.
=> Suppot tuple for axis argument in average

examples/cifar/train_cifar_custom_loop.py, examples/reinforcement_learning/ddpg_pendulum.py, examples/reinforcement_learning/dqn_cartpole.py
=> [backport] Remove get_device from examples

chainer/gradient_check.py, tests/chainer_tests/functions_tests/activation_tests/test_maxout.py, tests/chainer_tests/functions_tests/array_tests/test_cast.py, tests/chainer_tests/functions_tests/array_tests/test_dstack.py, tests/chainer_tests/functions_tests/array_tests/test_get_item.py, tests/chainer_tests/functions_tests/array_tests/test_hstack.py, tests/chainer_tests/functions_tests/array_tests/test_pad.py, tests/chainer_tests/functions_tests/array_tests/test_permutate.py, tests/chainer_tests/functions_tests/array_tests/test_resize_images.py, tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py, tests/chainer_tests/functions_tests/array_tests/test_select_item.py, tests/chainer_tests/functions_tests/array_tests/test_separate.py, tests/chainer_tests/functions_tests/array_tests/test_stack.py, tests/chainer_tests/functions_tests/array_tests/test_vstack.py, tests/chainer_tests/functions_tests/loss_tests/test_black_out.py, tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py, tests/chainer_tests/functions_tests/loss_tests/test_hinge.py, tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py, tests/chainer_tests/functions_tests/math_tests/test_minmax.py, tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py, tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py, tests/chainer_tests/links_tests/loss_tests/test_hierarchical_softmax.py, tests/chainer_tests/test_gradient_check.py
=> [backport] Only use one direction of numerical grad

chainer/link.py
=> [backport] fix typo in Link.disable_update

chainer/functions/math/basic_math.py
I implemented FunctionNode version of Neg
=> Implemented new version of neg

chainer/functions/math/basic_math.py
I implemented new version of Sub.
=> New version of sub

chainer/functions/array/transpose.py
I implemented new version of transpose.
=> New version of transpose

chainer/functions/array/cast.py, tests/chainer_tests/functions_tests/array_tests/test_cast.py
I implemented new version of cast.
=> New version of cast

chainer/gradient_check.py
=> Fix typo in docstring of gradient_check

chainer/gradient_check.py
=> [backport] Fix typo in docstring of gradient_check

chainer/function.py, chainer/function_hook.py, chainer/functions/activation/lstm.py, chainer/functions/activation/slstm.py, chainer/functions/activation/tree_lstm.py
=> Fix errors in docstrings

chainer/function.py, chainer/functions/activation/lstm.py, chainer/functions/activation/slstm.py
Backport of #3114 
Note:
`chainer/function_hook.py` and `chainer/functions/activation/tree_lstm.py` do not exist in v2 branch. So I discarded changes to them.
=> [Backport] Fix errors in docstrings

chainer/testing/__init__.py, chainer/testing/helper.py, tests/chainer_tests/test_link.py, tests/chainer_tests/test_variable.py
I inserted `assertiWarnig` to suppress warning in unit test.
=> Check DeprecationWarning in Variable

chainer/testing/__init__.py, chainer/testing/helper.py, tests/chainer_tests/test_link.py, tests/chainer_tests/test_variable.py
=> [backport] Check DeprecationWarning in Variable

chainer/functions/loss/ctc.py, chainer/functions/loss/vae.py
=> Fix doc typos

chainer/functions/loss/ctc.py, chainer/functions/loss/vae.py
=> [backport] Fix doc typos

chainer/function.py, chainer/variable.py
=> [Backport] Add function name in the debug message of NaN check

chainer/variable.py, tests/chainer_tests/test_variable.py
=> Call VariableNode.data from Parameter.initialize.

chainer/functions/loss/hinge.py
=> Improve docs of hinge

chainer/functions/connection/embed_id.py, chainer/links/connection/embed_id.py
- functions/connection/embed_id.py
=> Improve docs of embed_id

chainer/functions/connection/embed_id.py, tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
This fix supports grad of grad of EmbedID.
=> New EmbedID

chainer/functions/activation/leaky_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py
Implementing new-style version of `F.leaky_relu` (a part of #3147).
=> New style leaky_relu

chainer/variable.py, tests/chainer_tests/test_variable.py
`isnan` only accepts float type.
=> Fix nan check

chainer/functions/array/get_item.py
=> [backport] Fix Variable.__getitem__ document

docs/source/conf.py
=> [backport] Remove "Edit on GitHub" link

chainer/link.py, tests/chainer_tests/test_link.py
=> Deny assigning links in ChainList.init_scope()

chainer/cuda.py
=> Fix warning message for cuDNN

chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py
=> [backport] Use test mode in predict methods of ResNet, VGG, GoogLeNet

chainer/functions/noise/dropout.py
=> [backport] fixed document of F.dropout into more explanatory

chainer/link.py
This PR fixes #3225 by back porting #2814
=> [backport] fix chainer.Link docstring

chainer/functions/connection/linear.py
=> [backport] Fix document of functions.linear

chainer/functions/array/concat.py, chainer/functions/array/split_axis.py, chainer/functions/array/stack.py
=> New style concat and split_axis

chainer/function_hook.py, docs/source/tutorial/function.rst
This PR will fix failure of doctest
=> Fix document of FunctionHook and tutorial of Function

docs/source/tutorial/function.rst
=> [backport] Fix document of FunctionHook and tutorial of Function

chainer/functions/activation/clipped_relu.py
=> [backport] Fix doc of clipped_relu

docs/Makefile
=> [backport] Treat sphinx warnings as errors

docs/source/reference/links.rst
I fixed the link reference document.
=> Fix link document

chainer/functions/activation/leaky_relu.py
=> [backport] Fix doc of leaky_relu

chainer/functions/evaluation/binary_accuracy.py
- functions/evaluation/binary_accuracy
=> improve docs of binary_accuracy

chainer/optimizer.py
Fix misspelling of hyperparameter in chainer.optimizer.py docs comments.
=> Comment typo fix

chainer/variable.py
=> doc: Fix typo in Variable.grad

tests/chainer_tests/test_link.py
I fixed test of link to check DeprecationWarning.
merge #2932 first
related to #2545
=> Check deprecated method in test of Link

tests/chainer_tests/test_link.py
=> [backport] Check deprecated method in test of Link

chainer/functions/activation/tree_lstm.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_nd.py, chainer/functions/loss/vae.py, chainer/training/extensions/parameter_statistics.py
We need to use double backslashes in str literals.
=> Fix backslashes

chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_nd.py, chainer/functions/loss/vae.py, chainer/training/extensions/parameter_statistics.py
=> [backport] Fix backslashes

chainer/functions/array/broadcast.py, chainer/functions/array/expand_dims.py, chainer/functions/array/reshape.py, chainer/functions/array/squeeze.py, chainer/functions/math/det.py, chainer/functions/math/sum.py, tests/chainer_tests/functions_tests/array_tests/test_broadcast.py, tests/chainer_tests/functions_tests/array_tests/test_reshape.py, tests/chainer_tests/functions_tests/array_tests/test_squeeze.py, tests/chainer_tests/functions_tests/math_tests/test_sum.py
This PR improves the behavior of #3099 and #3163.
=> New style reshape, expand_dims, broadcast_to and sum

chainer/variable.py, tests/chainer_tests/test_variable.py
=> [backport] Fix nan check

docs/source/tutorial/recurrentnet.rst
changed tutorial to cope with #3136
=> changed tutorial so that it works

chainer/functions/math/batch_l2_norm_squared.py, chainer/functions/normalization/l2_normalization.py, chainer/links/connection/linear.py, chainer/variable.py, docs/source/conf.py
=> [backport] doc: Fix truncated summary line

chainer/function_node.py, chainer/functions/activation/tanh.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py, tests/chainer_tests/training_tests/extensions_tests/test_computational_graph.py
I implemented new style of tanh. Users can implement grad of grad of LSTM with this function.
=> Implement new style of tanh

chainer/functions/array/get_item.py, tests/chainer_tests/functions_tests/array_tests/test_get_item.py
This PR implements new-style version of `F.get_item` as a part of #3147. This function will be used to make `F.softmax_cross_entropy` double-backpropable.
=> New style GetItem

chainer/functions/__init__.py, chainer/functions/array/flatten.py, tests/chainer_tests/functions_tests/array_tests/test_flatten.py
This PR is a part of #3147.
Please merge #3188 before this PR.
=> New style flatten

chainer/cuda.py
=> Always raise warning when stream option is specified in to_gpu

chainer/functions/array/transpose.py
=> Improve docs of transpose

tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
Stabilizes `tanh` backward and double-backward test by adjusting tolerance.
=> test: Stabilize F.tanh

chainer/functions/array/where.py
=> Improve docs of where

chainer/functions/array/transpose.py
=> [backport] Improve docs of transpose

chainer/functions/activation/softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
Rel #3147.
This PR implements the new style softmax layer along with double backward support.
=> Implement new style softmax

chainer/cuda.py, tests/chainer_tests/test_cuda.py
=> [backport] Fix test of to_gpu with Variable argument

chainer/cuda.py
=> [backport] Fix warning message for cuDNN

chainer/datasets/image_dataset.py
=> [backport] Add warnings about preprocessing for dataset with both grayscale and RGB images.

chainer/optimizer.py
=> [backport] Comment typo fix

chainer/links/caffe/caffe_function.py
=> [backport] CaffeFunction to take BatchNorm scaling factor into account

chainer/functions/array/where.py
=> [backport] Improve docs of where

tests/chainer_tests/test_cuda.py
I inserted `assert_warns` to ignore `DeprecationWarning`.
=> Inserted assert_warns to ignore warnings

chainer/function_node.py, chainer/functions/activation/lstm.py, tests/chainer_tests/functions_tests/activation_tests/test_lstm.py
I implemented new style of LSTM function. Its gradient implementation is based on old style Function, but we can replace it with a new style Function.
=> Implement new style of LSTM function

tests/chainer_tests/test_cuda.py
=> [backport] Inserted assert_warns to ignore warnings

chainer/datasets/mnist.py
this is useful when training networks with multiple datasets (for example SVHN, which is RGB)
=> adding ability to convert mnist to rgb format

chainer/gradient_check.py
This PR improves test performance.
=> Reduce copy in check_backward

chainer/functions/math/average.py, tests/chainer_tests/functions_tests/math_tests/test_average.py
=> [backport] Suppot tuple for axis argument in average

docs/source/tutorial/basic.rst
=> [backport] Improves "Introduction to Chainer"

chainer/testing/random.py
=> Fix fix_random

chainer/testing/__init__.py, chainer/testing/random.py
This is a backport of #2985 and #3330.
=> [backport] Deterministic test (Chainer)

chainer/function_node.py
Tiny fix for the code of function_node.py
=> Remove unnecessary use of enumerate

chainer/functions/pooling/unpooling_2d.py, chainer/functions/pooling/upsampling_2d.py
=> [backport] Speedup Upsampling2D on CPU

chainer/links/connection/gru.py, docs/source/reference/links.rst
I fixed link in docstring of GRU
=> Fix link in GRU

chainer/variable.py, tests/chainer_tests/test_variable.py
Fixes #2670 
Reopening https://github.com/chainer/chainer/pull/2727
=> Make Variable unhashable

chainer/function_hook.py
Fix example indentation (follow-up for #3165).
=> doc: Fix example indent

chainer/links/connection/gru.py
=> [backport] doc: Fix GRU stateless/stateful

docs/source/reference/initializers.rst
=> [backport] doc: Add initializers.NaN

tests/chainer_tests/functions_tests/math_tests/test_exponential.py
Stabilizes exponential test by adjusting tolerance.
=> test: Stabilize exponential tests

docs/source/tutorial/recurrentnet.rst
=> [backport] changed tutorial so that it works

chainer/training/updaters/multiprocess_parallel_updater.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
This is a backport PR of #2817
=> [backport] Pass raw arrays to the loss function in `MultiprocessParallelUpdater`

chainer/functions/pooling/roi_pooling_2d.py
=> [backport] Fix typo in ROIPooling2D

tests/chainer_tests/functions_tests/math_tests/test_exponential.py
=> [backport] test: Stabilize exponential tests

chainer/functions/normalization/layer_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_layer_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py
Implementing new-style version of `F.layer_normalization` (a part of #3147).
=> New-style layer normalization

docs/source/compatibility.rst, docs/source/contribution.rst
=> [backport] Add minor version policy and feature backport policy

chainer/optimizer.py, tests/chainer_tests/test_optimizer.py
=> [backport] Avoid running certain hooks on uninitialized params

tests/chainer_tests/functions_tests/normalization_tests/test_local_response_normalization.py
Stabilizes local response normalization test by adjusting tolerance.
=> test: Stabilize local response normalization test

tests/chainer_tests/functions_tests/normalization_tests/test_local_response_normalization.py
=> [backport] test: Stabilize local response normalization test

chainer/functions/math/exponential.py
=> [Backport] Optimize backward of log2 and log10

chainer/datasets/dict_dataset.py, tests/chainer_tests/datasets_tests/test_dict_dataset.py, tests/chainer_tests/datasets_tests/test_tuple_dataset.py
=> Fix DictDataset to work in Python 3.

tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_crelu.py, tests/chainer_tests/functions_tests/activation_tests/test_elu.py, tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_lstm.py, tests/chainer_tests/functions_tests/activation_tests/test_maxout.py, tests/chainer_tests/functions_tests/activation_tests/test_prelu.py, tests/chainer_tests/functions_tests/activation_tests/test_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_selu.py, tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_slstm.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softplus.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
This PR stabilizes activation tests.
Please merge #3330 before this PR.
- Fix random seed
- Adjust threshold
- Simplify code
=> Improve activation function tests

tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
Stabilizes `test_unpooling_2d` by adjusting tolerance.
=> test: Stabilize test_unpooling_2d

tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
Stabilizes `roi_pooling_2d` test by adjusting tolerance.
=> test: Stabilize roi_pooling_2d test by adjusting tolerance

tests/chainer_tests/functions_tests/pooling_tests/test_upsampling_2d.py
Stabilize `upsampling_2d` test by adjusting tolerance
=> test: Stabilize upsampling_2d by adjusting tolerance

tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
Stabilizes `roll_axis` test by adjusting tolerance.
=> test: Stabilize roll_axis test by adjusting tolerance

docs/source/reference/extensions.rst
=> [backport] Add doc ref for ParameterStatistics extension

chainer/functions/array/squeeze.py, chainer/functions/array/swapaxes.py, chainer/functions/array/transpose.py
- functions/array/swapaxes
- functions/array/squeeze
- functions/array/transpose (very small changes)
=> Improve docs of swapaxes, squeeze, transpose

chainer/functions/array/permutate.py, chainer/functions/array/select_item.py, chainer/functions/array/separate.py
- chainer/functions/array/separate.py
- chainer/functions/array/select_item.py
- chainer/functions/array/permutate.py
=> Improve docs of separate, select_item, and permutate

tests/chainer_tests/functions_tests/pooling_tests/test_upsampling_2d.py
Current upsampling_2d_test is unstable.
=> Stabilize upsampling_2d test

examples/vae/data.py, examples/vae/train_vae.py
With this patch VAE example test time is reduced:
1:21.58 --> 8.387
=> Improve vae test mode

chainer/datasets/tuple_dataset.py
The existing documentation seemed a bit unclear. I have tried to make it easier to understand.
=> Improve TupleDataset documentation

chainer/functions/array/squeeze.py, chainer/functions/array/swapaxes.py, chainer/functions/array/transpose.py
=> [backport] Improve docs of swapaxes, squeeze, transpose

chainer/functions/array/permutate.py, chainer/functions/array/select_item.py, chainer/functions/array/separate.py
=> [backport] Improve docs of separate, select_item, and permutate

examples/vae/data.py, examples/vae/train_vae.py
=> [backport] Improve vae test mode

examples/seq2seq/README.md
=> Fixed Typo in Documentation

examples/seq2seq/README.md
=> [backport] Fixed Typo in Documentation

tests/chainer_tests/test_gradient_check.py
Adjust tolerance for `NumericalGradientTest4`
=> test: Stabilize test_gradient_check by adjusting tolerance

tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_dilated_convolution_2d.py
Stabilize test_dilated_convolution_2d by adjusting tolerance
=> test: Stabilize test_dilated_convolution_2d by adjusting tolerance

tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> test: Stabilize test_basic_math by adjusting tolerance

tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> [backport] test: Stabilize test_basic_math by adjusting tolerance

tests/chainer_tests/test_gradient_check.py
=> [backport] test: Stabilize test_gradient_check by adjusting tolerance

tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_dilated_convolution_2d.py
=> [backport] test: Stabilize test_dilated_convolution_2d by adjusting tolerance

chainer/functions/connection/n_step_lstm.py
- functions/connection/n_step_lstm.py
=> Improve docs of n_step_lstm

chainer/functions/__init__.py, chainer/functions/array/scatter_add.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_scatter_add.py
Resolve https://github.com/chainer/chainer/issues/3172
=> Add scatter_add

chainer/links/theano/theano_function.py, docs/source/reference/links.rst
Adds `TheanoFunction` and `CaffeFunction` to documentation.
=> doc: Add links for framework compatibility

chainer/links/theano/theano_function.py, docs/source/reference/links.rst
backports doc: Add links for framework compatibility #3475
=> [backport] doc: Add links for framework compatibility

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/linear.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_linear.py
Add workaround code for SGEMV error (fixes #3428 and #2744).
=> Fix SGEMV error

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/linear.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_linear.py
=> [backport] Fix SGEMV error

chainer/functions/array/swapaxes.py, tests/chainer_tests/functions_tests/array_tests/test_swapaxes.py
=> New style swapaxis function

chainer/functions/array/permutate.py, tests/chainer_tests/functions_tests/array_tests/test_permutate.py
=> New style permutate function

chainer/functions/array/swapaxes.py, tests/chainer_tests/functions_tests/array_tests/test_swapaxes.py
=> [backport] New style swapaxis function

chainer/functions/activation/softplus.py, tests/chainer_tests/functions_tests/activation_tests/test_softplus.py
=> New style softplus function

chainer/function_node.py, chainer/functions/normalization/batch_normalization.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_nd.py, chainer/serializer.py
I fixed docstrings to suppress warnings in the document.
=> Suppress warnings in the document

chainer/function_node.py, chainer/functions/normalization/batch_normalization.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_nd.py, chainer/serializer.py
=> [backport] Suppress warnings in the document

chainer/gradient_check.py
`numerical_grad` contains subtraction of very close values
So this PR uses float64 to improve accuracy and stability.
=> Improve numerical_grad accuracy

chainer/functions/array/copy.py, tests/chainer_tests/functions_tests/array_tests/test_copy.py
=> New style copy function

docs/source/_static/css/modified_theme.css
Improve appearance of "Deprecated since..." box.
Old:
New:
TODO: Port to CuPy
=> doc: Improve deprecation box style

examples/imagenet/train_imagenet.py
To reduce image data size for test, i changed intervals.
=> Change intervals in imagenet example

chainer/functions/array/where.py, tests/chainer_tests/functions_tests/array_tests/test_where.py
This PR changes `F.where` function to new style.
=> New style where function

docs/source/index.rst, docs/source/reference/index.rst, docs/source/tutorial/index.rst
Counterpart of CuPy PR: https://github.com/cupy/cupy/pull/444
**old**
**new**
=>  doc: Sort out navigation menu

docs/source/tutorial/convnet.rst
=> [backport] Minor fix in docs

chainer/functions/array/permutate.py, tests/chainer_tests/functions_tests/array_tests/test_permutate.py
=> [backport] New style permutate

chainer/functions/activation/clipped_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
New style clipped_relu function to support double backprop.
=> New style clipped_relu

chainer/training/trainer.py
=> Remove invoke_before_training argument

tests/chainer_tests/functions_tests/array_tests/test_get_item.py
=> [backport] Delete redundant test settings for get_item

chainer/cuda.py
=> Document to_gpu stream option deprecation

chainer/datasets/ptb.py, chainer/datasets/sub_dataset.py, chainer/functions/activation/tree_lstm.py, chainer/functions/array/pad_sequence.py, chainer/functions/array/split_axis.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py, chainer/functions/loss/crf1d.py, chainer/functions/math/matmul.py, chainer/functions/pooling/spatial_pyramid_pooling_2d.py, chainer/gradient_check.py, chainer/links/caffe/caffe_function.py, chainer/links/connection/lstm.py, chainer/links/connection/tree_lstm.py, chainer/links/loss/crf1d.py, chainer/training/extensions/evaluator.py, chainer/training/triggers/interval_trigger.py, chainer/training/triggers/manual_schedule_trigger.py, chainer/training/triggers/minmax_value_trigger.py, docs/source/_docstring_check.py, docs/source/conf.py
=> [backport] doc: Docstring checker to fix returns section markup

chainer/function_node.py, tests/chainer_tests/test_function_node.py
=> [backport] Type check in chainer.grad

chainer/training/trainer.py
=> [backport] Remove invoke_before_training argument

chainer/cuda.py
=> [backport] doc: Remove obsolete statement in to_gpu

chainer/testing/array.py
=> [backport] Avoid unwanted output of assert_allclose failure

chainer/functions/array/reshape.py
=> [backport] fix highlight error of chainer/functions/array/reshape.py

chainer/gradient_check.py
=> [backport] Improve numerical_grad accuracy

chainer/functions/array/transpose_sequence.py
=> New style transpose_sequence

chainer/initializers/constant.py
I fixed docstrings to supress warnings.
=> Fix docstring of constants

docs/source/reference/environment.rst
=> [backport] doc: Fix type-check reference

chainer/link.py
=> [backport] Fix doc of init_scope

chainer/gradient_check.py, tests/chainer_tests/functions_tests/array_tests/test_im2col.py, tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py, tests/chainer_tests/test_gradient_check.py
With this patch, `check_backward` uses directional derivative of random direction to check gradient.
=> Use directional derivative

chainer/gradient_check.py, tests/chainer_tests/functions_tests/array_tests/test_im2col.py, tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py, tests/chainer_tests/test_gradient_check.py
=> [backport] Use directional derivative

tests/chainer_tests/functions_tests/pooling_tests/test_upsampling_2d.py
This backports test: Stabilize upsampling_2d by adjusting tolerance #3377
=> [backport] test: Stabilize upsampling_2d by adjusting tolerance

docs/source/_static/css/modified_theme.css
=> [backport] doc: Improve deprecation box style

docs/source/_static/css/modified_theme.css
=> [backport] doc: Avoid table scroll

chainer/gradient_check.py, tests/chainer_tests/test_gradient_check.py
=> Fix check_backward

chainer/computational_graph.py, chainer/cuda.py, chainer/function.py, chainer/function_node.py, chainer/functions/array/transpose_sequence.py, chainer/functions/loss/crf1d.py, chainer/gradient_check.py, chainer/links/connection/mlp_convolution_2d.py, chainer/variable.py, docs/source/tutorial/convnet.rst, docs/source/tutorial/train_loop.rst
=> doc: Fix some markup

chainer/functions/__init__.py, chainer/functions/array/flip.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_flip.py
=> [backport] Add flip function

chainer/functions/array/transpose_sequence.py
=> [backport] New style transpose_sequence

chainer/initializers/constant.py
=> [backport] Fix docstring of constants

chainer/gradient_check.py, tests/chainer_tests/functions_tests/array_tests/test_im2col.py, tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py, tests/chainer_tests/test_gradient_check.py
=> Revert "Use directional derivative"

docs/source/conf.py
=> [backport]Doc: Fix source links for functions defined with contextlib.contextmanager

chainer/gradient_check.py, tests/chainer_tests/functions_tests/array_tests/test_im2col.py, tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py, tests/chainer_tests/test_gradient_check.py
=> Revert "[backport] Use directional derivative"

docker/python2/Dockerfile, docker/python3/Dockerfile, setup.py
Update setup.py and Docker files to v4.0.0a1.
=> Update to v4.0.0a1

.travis.yml, chainer/testing/attr.py, setup.cfg, setup.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py, tests/chainer_tests/test_runnable.py
=> [backport] Replace the test framework with PyTest

appveyor.yml
AppVeyor needs to be configured to use PyTest.
=> Configure AppVeyor to use PyTest

appveyor.yml
backport PR for Configure AppVeyor to use PyTest #3595
=> [backport] Configure AppVeyor to use PyTest

chainer/utils/__init__.py, chainer/utils/conv.py, docs/source/reference/util.rst, docs/source/reference/util/conv.rst
=> [backport] Add get_conv_outsize and get_deconv_outsize to doc

chainer/functions/loss/huber_loss.py
- chainer/functions/loss/huber_loss
=> Improve docs of huber_loss

chainer/functions/loss/sigmoid_cross_entropy.py
- chainer/functions/loss/sigmoid_cross_entropy
=> Improve docs of sigmoid_cross_entropy

chainer/functions/loss/contrastive.py, chainer/functions/loss/triplet.py
- chainer/functions/loss/contrastive
- chainer/functions/loss/triplet
=> Improve docs of contrastive and triplet

.gitignore
=> [backport] Fix for pytest migration

docs/source/tutorial/extension.rst
We cannot compile document.
Please merge as soon as possible.
=> Fix document directive typo

chainer/functions/loss/contrastive.py, chainer/functions/loss/triplet.py
=> [backport] Improve docs of contrastive and triplet

chainer/functions/loss/sigmoid_cross_entropy.py
=> [backport] Improve docs of sigmoid_cross_entropy

chainer/functions/loss/huber_loss.py
=> [backport] Improve docs of huber_loss

chainer/functions/activation/softplus.py, tests/chainer_tests/functions_tests/activation_tests/test_softplus.py
=> [backport] New style softplus function

tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
This backports test: Stabilize roi_pooling_2d test by adjusting tolerance #3376
=> [backport] test: Stabilize roi_pooling_2d test by adjusting tolerance

chainer/iterators/__init__.py, chainer/iterators/multithread_iterator.py, docs/source/reference/iterators.rst, tests/chainer_tests/iterators_tests/test_multithread_iterator.py
This PR provides multi thread iterator.
- Avoid pickle
- There is a limitation of GIL
=> Add MultithreadIterator

tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
=> [backport] Stabilize deconvolution2d test

chainer/function_node.py
=> [backport] documentation fix in FunctionNode

chainer/functions/array/broadcast.py, tests/chainer_tests/functions_tests/array_tests/test_broadcast.py
=> New style broadcast function

chainer/functions/connection/n_step_lstm.py
=> [backport] Improve docs of n_step_lstm

chainer/functions/array/separate.py, chainer/links/model/classifier.py, chainer/links/theano/theano_function.py
=> [backport]Fix doctest

chainer/functions/array/broadcast.py, tests/chainer_tests/functions_tests/array_tests/test_broadcast.py
=> [backport]New style broadcast function

chainer/functions/activation/clipped_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
=> [backport] New style clipped_relu

chainer/functions/pooling/average_pooling_nd.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/unpooling_nd.py, chainer/links/connection/tree_lstm.py, chainer/links/normalization/layer_normalization.py, chainer/links/theano/theano_function.py
=> [backport]doc: Add experimental warning in docstring

chainer/testing/random.py
=> Setup random of Python library in testing/random

chainer/testing/random.py
=> [backport] Setup random of Python library in testing/random

tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
This PR backports test: Stabilize roll_axis test by adjusting tolerance #3375
=> [backport] test: Stabilize roll_axis test by adjusting tolerance

chainer/functions/array/where.py, tests/chainer_tests/functions_tests/array_tests/test_where.py
=> [backport] New style where function

chainer/function.py
=> [backport] fix documention error in Function

chainer/functions/array/hstack.py, tests/chainer_tests/functions_tests/array_tests/test_hstack.py
New style hstack function to support double backprop.
I am unsure whether accessing `self.inputs`, i.e. the `VariableNode`s from within the `FunctionNode` is against practices. There is no need to retain the inputs since we only want to know the shapes.
=> New style hstack

chainer/testing/unary_math_function_test.py, tests/chainer_tests/testing_tests/test_unary_math_function_test.py
Backport of pull request #3603 from takagi/fix-test-math-function
=> [backport] Fix math function testing helper to support new style functions.

.travis.yml
=> [backport] run OS X test only on master/stable branch to avoid delay

chainer/functions/array/hstack.py, tests/chainer_tests/functions_tests/array_tests/test_hstack.py
=> [backport] New style hstack

chainer/training/extensions/evaluator.py
=> [backport] Add a note to the doc of Evaluator.evaluate

chainer/testing/attr.py, chainer/testing/training.py, chainer/testing/unary_math_function_test.py, setup.py
=> [backport] Remove requirements for unit testing

chainer/datasets/svhn.py, docs/source/reference/datasets.rst
=> Document get_svhn

chainer/functions/math/square.py, tests/chainer_tests/functions_tests/math_tests/test_square.py
=> [backport] New style square function

.travis.yml, chainer/testing/attr.py, chainer/testing/training.py, chainer/testing/unary_math_function_test.py, setup.py
The backport of #3624. Merge #3682 first.
=> [backport] Fix decorators to allow users to filter test cases by number of GPUs

chainer/datasets/svhn.py, docs/source/reference/datasets.rst
=> [backport] Document get_svhn

docs/source/tips.rst
=> fix cupy overview link not working

examples/seq2seq/seq2seq.py
I added `--log-interval` and `--validation-interval` to control timing to show logs and to run validation.
=> Add argument to control interval for seq2seq example

chainer/datasets/tuple_dataset.py
=> [backport] Improve TupleDataset documentation

appveyor.yml
=> [backport] fix to skip GPU tests on AppVeyor

.coveragerc
See https://github.com/chainer/chainer-test/pull/347
=> fix coveragerc to measure branch coverage and only target chainer module

docs/source/conf.py
=> [backport]Stop checking docstring compliance with autosummary

chainer/functions/array/split_axis.py
=> [backport]Fix split_axis documentation

chainer/function.py
Fix some minor errors and improve the docs of `no_backprop_mode` and `force_backprop_mode`.
=> Improve doc of context managers

chainer/functions/pooling/average_pooling_nd.py, chainer/functions/pooling/max_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
=> Fix xxx_pooling_nd causes CUDNN_STATUS_NOT_SUPPORTED for dims > 3

chainer/function.py
=> [backport] Improve doc of context managers

docs/source/reference/core/configuration.rst
=> [backport] Improve doc of configuration flags

docs/source/reference/function_hooks.rst
=> [backport]Add CUDAProfileHook and CupyMemoryProfileHook to the reference

.coveragerc
=> [backport]fix coveragerc to measure branch coverage and only target chainer module

chainer/functions/math/sum.py
=> [backport] Improve doc of sum

chainer/functions/array/permutate.py, chainer/functions/connection/embed_id.py, chainer/functions/evaluation/accuracy.py, chainer/functions/evaluation/binary_accuracy.py, chainer/functions/evaluation/classification_summary.py, chainer/functions/loss/contrastive.py, chainer/functions/loss/hinge.py, chainer/functions/loss/sigmoid_cross_entropy.py, chainer/functions/loss/softmax_cross_entropy.py, tests/chainer_tests/functions_tests/array_tests/test_permutate.py, tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py, tests/chainer_tests/functions_tests/evaluation_tests/test_accuracy.py, tests/chainer_tests/functions_tests/evaluation_tests/test_binary_accuracy.py, tests/chainer_tests/functions_tests/evaluation_tests/test_classification_summary.py, tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py, tests/chainer_tests/functions_tests/loss_tests/test_hinge.py, tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
=> [backport] Relax int type restriction

chainer/functions/pooling/average_pooling_nd.py, chainer/functions/pooling/max_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
=> [backport]Fix xxx_pooling_nd causes CUDNN_STATUS_NOT_SUPPORTED for dims > 3

.travis.yml, appveyor.yml, chainer/testing/__init__.py, chainer/testing/unary_math_function_test.py, tests/chainer_tests/functions_tests/pooling_tests/pooling_nd_helper.py
The backport of #3623. Merge #3721 first.
=> [backport] remove nose dependency in tests

.travis.yml
=> [backport] Check deprecation warining in Travis

chainer/functions/connection/n_step_rnn.py
I replaced `DropoutStates` class with CuPy's one. The current implementation causes deprecated warnings.
This patch directly uses attributes in `DropoutStates` object. It is better to make additional method in it.
=> Use cudnn.DropoutStates instead of calling API directly

tests/chainer_tests/functions_tests/math_tests/test_ceil.py, tests/chainer_tests/functions_tests/math_tests/test_floor.py
=> [backport] Stabilize unit tests for F.Ceil and F.Floor

chainer/functions/array/reshape.py, chainer/functions/pooling/upsampling_2d.py, docs/source/tutorial/type_check.rst
=> [backport] Use python 3.5 for doctest

chainer/functions/activation/elu.py, tests/chainer_tests/functions_tests/activation_tests/test_elu.py
New style ELU to support double backprop.
=> New style ELU

chainer/gradient_check.py
=> [backport]Richer gradient check output

chainer/functions/math/minmax.py, tests/chainer_tests/functions_tests/math_tests/test_minmax.py
This PR implements new style `min`, `max`, `argmin`, `argmax` functions.
=> new style minmax functions

chainer/functions/math/exponential.py, tests/chainer_tests/functions_tests/math_tests/test_exponential.py
This PR implements new style `log`, `log2` and `log10` functions.
=> new style exponential functions

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
This PR implements new style `abs` function.
I also added double backward test case for `neg` (which is already in new style)
=> new style abs function

chainer/links/connection/lstm.py, tests/chainer_tests/links_tests/connection_tests/test_lstm.py
=> [backport] Fix LSTM bias initialization

chainer/functions/activation/elu.py, tests/chainer_tests/functions_tests/activation_tests/test_elu.py
=> [backport]New style ELU

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> [backport] new style abs function

chainer/functions/math/exponential.py, tests/chainer_tests/functions_tests/math_tests/test_exponential.py
=> [backport] new style exponential functions

chainer/functions/math/minmax.py, tests/chainer_tests/functions_tests/math_tests/test_minmax.py
=> [backport] new style minmax functions

setup.cfg
=> [backport] Remove PyTest global option configuration

chainer/__init__.py, chainer/_environment_check.py, docs/source/tips.rst
=> [backport] Warn about vecLib on Mac OS X

chainer/functions/math/sqrt.py, chainer/testing/unary_math_function_test.py, tests/chainer_tests/functions_tests/math_tests/test_sqrt.py
This PR implements new `sqrt` function.
This PR needs to be rebased after merging #3603.
=> new style sqrt function

tests/chainer_tests/functions_tests/math_tests/test_average.py
=> [backport]Fix normalization warning in F.average test

chainer/functions/math/inv.py, tests/chainer_tests/functions_tests/math_tests/test_inv.py
This PR implements new style `inv` and `batch_inv` function.
=> new style inv and batch_inv function

chainer/functions/math/sqrt.py, chainer/testing/unary_math_function_test.py, tests/chainer_tests/functions_tests/math_tests/test_sqrt.py
=> [backport] new style sqrt function

README.md
=> [backport] Update stable version link in README

chainer/cuda.py, tests/chainer_tests/test_cuda.py
=> Allow to_gpu and to_cpu to accept NumPy scalars

docs/source/tips.rst
Minor fix in the docs, for consistency.
=> Fix case in doc

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
This PR implements new style `div` funciton.
=> new style div function

chainer/functions/__init__.py, chainer/functions/math/cumsum.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_cumsum.py
I implemented `F.cumsum` as `FunctionNode`.
=> Add cumsum function

docs/source/contribution.rst
=> [backport] fix contribution guide for test framework change

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> [backport] new style div function

chainer/functions/math/inv.py, tests/chainer_tests/functions_tests/math_tests/test_inv.py
=> [backport] new style inv and batch_inv function

chainer/serializers/hdf5.py, chainer/serializers/npz.py, tests/chainer_tests/serializers_tests/test_npz.py
=> [backport] Support file-like object in npz serializer

chainer/cuda.py, tests/chainer_tests/test_cuda.py
=> [backport] Allow to_gpu and to_cpu to accept NumPy scalars

chainer/functions/array/tile.py
It was just testing numpy.
https://docs.chainer.org/en/stable/reference/generated/chainer.functions.tile.html#chainer.functions.tile
=> F.tile doctest does not test our function

chainer/functions/util/forget.py
Fixes a broken link in the docs.
=> Fix doc in Forget

chainer/functions/util/forget.py
=> [backport] Fix doc in Forget

.travis.yml, setup.cfg, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
=> [backport] Use pytest-warnings to set warnings configuration

tests/chainer_tests/functions_tests/math_tests/test_inv.py
=> [backport] fix F.inv test does not test type error as expected

chainer/functions/evaluation/r2_score.py, tests/chainer_tests/functions_tests/evaluation_tests/test_r2_score.py
=> [backport] Avoid zero-division warning in F.r2_score

chainer/training/extensions/plot_report.py
=> [backport]Rename plot -> plt

chainer/functions/math/inv.py, tests/chainer_tests/functions_tests/math_tests/test_inv.py
This fixes #3765.
~~Merge #3769 first.~~ (done)
=> fix F.inv to raise exception when input has singular matrices

chainer/optimizers/adam.py, chainer/optimizers/rmsprop.py, tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
=> [backport] Check too small eps in Adam and RMSprop optimizers

chainer/function_node.py
=> [backport] Raise user-friendly error when FunctionNode is used like Function object

chainer/functions/math/inv.py, tests/chainer_tests/functions_tests/math_tests/test_inv.py
=> [backport] fix F.inv to raise exception when input has singular matrices

chainer/functions/util/forget.py
=> [backport] Improve docs of F.forget

chainer/initializers/normal.py, tests/chainer_tests/initializer_tests/test_normal.py
Derived from eq 14 in the ResNet paper.
https://arxiv.org/pdf/1502.01852v1.pdf
=> Add fan_option to HeNormal initializer

chainer/links/connection/linear.py, docs/source/reference/initializers.rst
Fixes #3287
Wrote about initializer criteria.
Also updated `L.Linear` documentation as an example.
=> Document initializer criteria

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
New style pow functions (e.g. ** including `PowVarVar`, `PowVarConst`, `PowConstVar`) to support double backprop.
=> New style pow

chainer/links/connection/linear.py, docs/source/reference/initializers.rst
=> [backport] Document initializer criteria

chainer/__init__.py, chainer/function_node.py, chainer/functions/activation/relu.py, chainer/utils/type_check.py
=> [backport] Remove function call to up performance

chainer/optimizer.py
=> [backport] Fix the problem with resuming training when switching the freezing layers

chainer/functions/array/scatter_add.py, tests/chainer_tests/functions_tests/array_tests/test_scatter_add.py
New style scatter_add function to support double backprop.
=> New style scatter_add

chainer/functions/math/clip.py, tests/chainer_tests/functions_tests/math_tests/test_clip.py
New style clip to support double backprop.
=> New style clip

chainer/functions/array/resize_images.py, tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
New style resize_images to support double backprop.
=> New style resize_images

chainer/functions/math/clip.py, tests/chainer_tests/functions_tests/math_tests/test_clip.py
=> [backport] New style clip

chainer/functions/array/resize_images.py, tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
=> [backport] New style resize_images

chainer/functions/activation/prelu.py, tests/chainer_tests/functions_tests/activation_tests/test_prelu.py
New style Parametric ReLU (PReLU) to support double backprop.
=> New style PReLU

chainer/functions/activation/prelu.py, tests/chainer_tests/functions_tests/activation_tests/test_prelu.py
=> [backport] New style PReLU

chainer/functions/math/minimum.py, tests/chainer_tests/functions_tests/math_tests/test_minimum.py
This PR implements new style `minimum` function.
=> new style minimum function

chainer/functions/loss/triplet.py, tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
New style triplet loss to support double backprop.
=> New style triplet

chainer/functions/__init__.py, chainer/functions/math/floor.py, tests/chainer_tests/functions_tests/math_tests/test_floor.py
This PR implements new style `floor` function.
I think that this `backward` implementation is not efficient compared to the old one.
Are there any better way to do `xp.zeros` efficiently with computation graph?
=> new style floor function

tests/chainer_tests/functions_tests/math_tests/test_inv.py
https://github.com/chainer/chainer/pull/3616#issuecomment-341106863
=> add double-backward test for F.inv and F.batch_inv

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> [backport] New style pow

chainer/functions/math/squared_difference.py, tests/chainer_tests/functions_tests/math_tests/test_squared_difference.py
This PR implements new style `squared_difference` function.
=> new style squared_difference function

chainer/functions/array/vstack.py, tests/chainer_tests/functions_tests/array_tests/test_vstack.py
New style vstack to support double backprop.
=> New style vstack

chainer/functions/array/tile.py, tests/chainer_tests/functions_tests/array_tests/test_tile.py
New style tile function to support double backprop.
=> New style tile

chainer/functions/array/fliplr.py, tests/chainer_tests/functions_tests/array_tests/test_fliplr.py
New style fliplr to support double backprop.
=> New style fliplr

chainer/functions/array/flipud.py, tests/chainer_tests/functions_tests/array_tests/test_flipud.py
New style flipud to support double backprop.
=> New style flipud

chainer/functions/array/flipud.py, tests/chainer_tests/functions_tests/array_tests/test_flipud.py
=> [backport] New style flipud

chainer/functions/array/fliplr.py, tests/chainer_tests/functions_tests/array_tests/test_fliplr.py
=> [backport] New style fliplr

tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
=> Use correct module path

tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
=> [backport] Use correct module path

chainer/functions/__init__.py, chainer/functions/math/fix.py, chainer/functions/math/fmod.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_fix.py, tests/chainer_tests/functions_tests/math_tests/test_fmod.py
This PR implements new style `fmod` function.
This PR also contains new function `F.fix` because it is needed in fmod backward.
(If it should be another PR, please comment)
=> introduce F.fix and make F.fmod function new style

chainer/functions/__init__.py, chainer/functions/math/fix.py, chainer/functions/math/fmod.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_fix.py, tests/chainer_tests/functions_tests/math_tests/test_fmod.py
=> [backport] introduce F.fix and make F.fmod function new style

tests/chainer_tests/functions_tests/math_tests/test_inv.py
=> [backport] add double-backward test for F.inv and F.batch_inv

chainer/functions/math/minimum.py, tests/chainer_tests/functions_tests/math_tests/test_minimum.py
=> [backport] new style minimum function

chainer/functions/__init__.py, chainer/functions/math/floor.py, tests/chainer_tests/functions_tests/math_tests/test_floor.py
=> [backport] new style floor function

docs/source/index.rst, docs/source/reference/index.rst, docs/source/tutorial/index.rst
=> [backport]  doc: Sort out navigation menu

chainer/functions/array/pad_sequence.py, tests/chainer_tests/functions_tests/array_tests/test_pad_sequence.py
=> [backport] New style pad_sequence

tests/chainer_tests/functions_tests/math_tests/test_fmod.py
Fix test instability.
Confirmed to pass 10,000 repeats.
Ref #3645
=> fix test tolerance for F.fmod double backward test

chainer/functions/math/minimum.py
=> [backport] Remove unnecessary branch in minimum forward.

tests/chainer_tests/functions_tests/math_tests/test_fmod.py
=> [backport] fix test tolerance for F.fmod double backward test

chainer/functions/math/logarithm_1p.py, tests/chainer_tests/functions_tests/math_tests/test_logarithm_1p.py
This PR implements new style `log1p` function.
=> new style log1p function

chainer/functions/activation/hard_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py
New style hard sigmoid to support double backprop.
=> New style hard sigmoid

chainer/functions/activation/crelu.py, tests/chainer_tests/functions_tests/activation_tests/test_crelu.py
New style CReLU to support double backprop.
=> New style CReLU

chainer/functions/array/pad.py, tests/chainer_tests/functions_tests/array_tests/test_pad.py
New style pad to support double backprop.
=> New style pad

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
This PR implements new style `rdiv` function.
I also fixed a wrong label of `DivFromConstant`.
The label says `variable / C` but actually it computes `C / variable`.
=> new style rdiv function

chainer/functions/__init__.py, chainer/functions/math/ceil.py, tests/chainer_tests/functions_tests/math_tests/test_ceil.py
This PR implements new style `ceil` function.
=> new style ceil function

docs/source/tutorial/function.rst
=> Fix test condition in function tutorial

chainer/functions/math/logsumexp.py, tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py
This PR implements new style `logsumexp` function.
=> new style logsumexp function

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_2d.py
This PR includes bugfix.
Rel #514
=> Add dilation to dict key and rename internal function

chainer/functions/array/reshape.py, chainer/utils/type_check.py
=> Fix doctest

chainer/functions/math/hyperbolic.py, tests/chainer_tests/functions_tests/math_tests/test_hyperbolic.py
This PR implements new style hyperbolic functions.
=> new style hyperbolic functions

chainer/functions/array/depth2space.py, chainer/functions/array/space2depth.py, tests/chainer_tests/functions_tests/array_tests/test_depth_2_space.py, tests/chainer_tests/functions_tests/array_tests/test_space_2_depth.py
New style depth2space and space2depth to support double backprop. 
Included two functions in a single PR since the changes are pretty much identical.
=> New style depth2space and space2depth

chainer/functions/math/trigonometric.py, tests/chainer_tests/functions_tests/math_tests/test_trigonometric.py
This PR implements new style trigonometric functions.
This PR needs to be rebased after #3603.
Confirmed 10000 repeats.
=> new style trigonometric functions

chainer/functions/array/depth2space.py, chainer/functions/array/space2depth.py, tests/chainer_tests/functions_tests/array_tests/test_depth_2_space.py, tests/chainer_tests/functions_tests/array_tests/test_space_2_depth.py
=> [backport] New style depth2space and space2depth

chainer/__init__.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/deconvolution_nd.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_2d.py, chainer/links/connection/deconvolution_nd.py, docs/source/reference/core/configuration.rst, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
This PR is backport of #3669 and #3831 .
=> [backport] cuDNN Convolution functions Autotuner

chainer/functions/loss/triplet.py, tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
=> [backport] New style triplet 

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> [backport] new style rdiv function

chainer/functions/__init__.py, chainer/functions/math/ceil.py, tests/chainer_tests/functions_tests/math_tests/test_ceil.py
=> [backport] new style ceil function

chainer/functions/math/logarithm_1p.py, tests/chainer_tests/functions_tests/math_tests/test_logarithm_1p.py
=> [backport] new style log1p function

chainer/serializers/npz.py
=> Use context to close opened file

docs/source/tutorial/function.rst
=> [backport] Fix test condition in function tutorial

chainer/functions/activation/hard_sigmoid.py, tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py
=> [backport]New style hard sigmoid

chainer/functions/activation/crelu.py, tests/chainer_tests/functions_tests/activation_tests/test_crelu.py
=> [backport]New style CReLU

chainer/functions/array/dstack.py, tests/chainer_tests/functions_tests/array_tests/test_dstack.py
New style dstack to support double backprop.
=> New style dstack

examples/pos/README.md, examples/pos/postagging.py
This is an example of CRF1d function. `nltk` is required.
Please merge #1451 first.
=> POS-tagging example

chainer/serializers/npz.py
=> [backport] Use context to close opened file

tests/chainer_tests/functions_tests/array_tests/test_depth_2_space.py, tests/chainer_tests/functions_tests/array_tests/test_space_2_depth.py
Fixed tolerances of failing tests, `depth_2_space` and `space_2_depth`.
=> Adjust tolerances of depth_2_space, space_2_depth tests

docs/source/tutorial/trainer.rst
=> [backport] fix doctest failure in trainer tutorial

chainer/functions/math/trigonometric.py, tests/chainer_tests/functions_tests/math_tests/test_trigonometric.py
=> [backport] new style trigonometric functions

chainer/functions/math/hyperbolic.py, tests/chainer_tests/functions_tests/math_tests/test_hyperbolic.py
=> [backport] new style hyperbolic functions

chainer/functions/math/logsumexp.py, tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py
=> [backport] new style logsumexp function

chainer/functions/math/squared_difference.py, tests/chainer_tests/functions_tests/math_tests/test_squared_difference.py
=> [backport] new style squared_difference function

tests/chainer_tests/functions_tests/array_tests/test_depth_2_space.py, tests/chainer_tests/functions_tests/array_tests/test_space_2_depth.py
=> [backport] Adjust tolerances of depth_2_space, space_2_depth tests

chainer/functions/array/dstack.py, tests/chainer_tests/functions_tests/array_tests/test_dstack.py
=> [backport] New style dstack

chainer/functions/array/pad.py, tests/chainer_tests/functions_tests/array_tests/test_pad.py
=> [backport] New style pad

chainer/functions/array/tile.py, tests/chainer_tests/functions_tests/array_tests/test_tile.py
=> [backport] New style tile

docker/python2/Dockerfile, docker/python3/Dockerfile, setup.py
=> Update to v3.1.0

chainer/functions/math/exponential_m1.py, tests/chainer_tests/functions_tests/math_tests/test_exponential_m1.py
This PR implements new style `expm1` function.
=> new style expm1 function

chainer/functions/math/batch_l2_norm_squared.py, tests/chainer_tests/functions_tests/math_tests/test_batch_l2_norm_squared.py
This PR implements new style `batch_l2_norm_squared` function.
=> new style `batch_l2_norm_squared` function

chainer/functions/math/maximum.py, tests/chainer_tests/functions_tests/math_tests/test_maximum.py
This PR implements new style `maximum` function.
=> new style maximum function

chainer/functions/loss/mean_absolute_error.py, tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
New style mean_absolute_error to support double backprop.
=> New style mean absolute error

chainer/functions/loss/squared_error.py, tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py
New style squared_error to support double backprop.
=> New style squared_error

chainer/functions/__init__.py, chainer/functions/math/sign.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_sign.py
Added the sign function with gradient 0 everywhere, mostly because it could be used when reimplementing Functions as FunctionNodes in the backward pass.
=> Add sign function

chainer/functions/loss/squared_error.py, tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py
=> [backport] New style squared_error

chainer/functions/loss/mean_absolute_error.py, tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
=> [backport] New style mean absolute error

chainer/functions/__init__.py, chainer/functions/math/sign.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_sign.py
=> [backport] Add sign function

chainer/testing/unary_math_function_test.py, tests/chainer_tests/functions_tests/math_tests/test_trigonometric.py
=> [backport] Fix test instability for trigonometric functions

chainer/functions/math/maximum.py, tests/chainer_tests/functions_tests/math_tests/test_maximum.py
=> [backport] new style maximum function

chainer/functions/math/batch_l2_norm_squared.py, tests/chainer_tests/functions_tests/math_tests/test_batch_l2_norm_squared.py
=> [backport] new style `batch_l2_norm_squared` function

chainer/dataset/download.py
=> [backport] use stderr for Downloading... message

chainer/functions/math/exponential_m1.py, tests/chainer_tests/functions_tests/math_tests/test_exponential_m1.py
=> [backport] new style expm1 function

tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
Adjusting tolerance of backward test of `convolution_nd`.
=> Adjust convolution_nd testing tolerance.

chainer/links/caffe/caffe_function.py
=> [backport] Make caffe model loading faster (~2.4 times on my benchmark)

chainer/functions/array/im2col.py, tests/chainer_tests/functions_tests/array_tests/test_im2col.py
New style im2col to support double backprop.
=> New style im2col

chainer/links/activation/maxout.py, chainer/links/activation/simplified_dropconnect.py, chainer/links/connection/bilinear.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_2d.py, chainer/links/connection/deconvolution_nd.py, chainer/links/connection/depthwise_convolution_2d.py, chainer/links/connection/dilated_convolution_2d.py, chainer/links/connection/embed_id.py, chainer/links/connection/highway.py, chainer/links/connection/inception.py, chainer/links/connection/inceptionbn.py, chainer/links/connection/linear.py, chainer/links/connection/n_step_lstm.py, docs/source/reference/initializers.rst
=> [backport] Replace array in type lists with numpy or cupy ndarray

tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
=> [backport] Adjust convolution_nd testing tolerance.

chainer/functions/math/linear_interpolate.py, tests/chainer_tests/functions_tests/math_tests/test_linear_interpolate.py
This PR implements new style `linear_interpolate` function.
=> new style linear_interpolate function

chainer/functions/array/im2col.py, tests/chainer_tests/functions_tests/array_tests/test_im2col.py
=> [backport] New style im2col

docs/source/reference/functions.rst
=> [backport] Add expm1 to the document.

chainer/links/connection/gru.py
=> Improve docs of gru

chainer/functions/math/linear_interpolate.py, tests/chainer_tests/functions_tests/math_tests/test_linear_interpolate.py
=> [backport] new style linear_interpolate function

examples/mnist/train_mnist.py
Fixes #3924 by introducing `--noplot` option in MNIST example.
=> Add `--noplot` option in MNIST example

chainer/functions/array/vstack.py, tests/chainer_tests/functions_tests/array_tests/test_vstack.py
=> [backport] New style vstack

chainer/functions/math/basic_math.py
More verbose error message that prints out the actual value.
=> Verbose error message in basic_math

tests/chainer_tests/functions_tests/array_tests/test_im2col.py
Adjusted tolerances for the `im2col` function test.
=> Adjust tolerances for im2col tests

examples/mnist/train_mnist.py
=> [backport] Add `--noplot` option in MNIST example

chainer/functions/math/basic_math.py
=> [backport] Verbose error message in basic_math

tests/chainer_tests/functions_tests/array_tests/test_im2col.py
=> [backport] Adjust tolerances for im2col tests

chainer/gradient_check.py
=> [backport] Verbose error in gradient check

tests/chainer_tests/functions_tests/math_tests/test_linear_interpolate.py
=> [backport] adjust tolerance for F.linear_interpolate double_backward tests

tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
=> [backport] Adjust tolerance for triplet loss function test

chainer/initializers/uniform.py
=> [backport] fix GlorotUniform doc

chainer/functions/normalization/l2_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
This PR implements new style `normalize` function.
=> new style normalize function

chainer/functions/loss/cross_covariance.py, tests/chainer_tests/functions_tests/loss_tests/test_cross_covariance.py
New style cross_covariance to support double backprop.
=> New style cross_covariance

chainer/testing/parameterized.py
=> [backport] Useful error message for parameterized tests

chainer/functions/loss/cross_covariance.py, tests/chainer_tests/functions_tests/loss_tests/test_cross_covariance.py
=> [backport] New style cross_covariance

chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py
=> [backport] Fix docs in n_step_xxx

chainer/testing/parameterized.py
=> [backport] catch all exceptions in parameterized test

docs/source/reference/links.rst
=> [backport] add StatefulZoneoutLSTM to docs

chainer/functions/normalization/l2_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
=> [backport] new style normalize function

chainer/functions/loss/sigmoid_cross_entropy.py
=> [backport] Fix sigmoid_cross_entropy doc about t

tests/chainer_tests/functions_tests/evaluation_tests/test_classification_summary.py
Fixes a failing case for issue #3878.
=> Avoid `NaN` in test of `F.classification_summary`

chainer/__init__.py, docs/source/reference/core/debug.rst, docs/source/reference/environment.rst
=> [backport] doc: improve debug mode documentation

examples/seq2seq/README.md
=> [backport] small fix for the example of seq2seq

docs/source/tutorial/trainer.rst
=> [backport] fix trainer tutorial evaluate example code

chainer/dataset/__init__.py, chainer/dataset/convert.py, docs/source/reference/core/dataset.rst
=> Add ConcatWithAsyncTransfer to the reference manual

chainer/dataset/convert.py
Fix doc reference in the `ConcatWithAsyncTransfer ` class.
=> Fix doc reference

docs/source/contribution.rst
=> Fix minor document bug

chainer/utils/array.py
=> [backport] Skip unnecessary array util ops

.travis.yml
=> [backport] fix macOS test in Travis

chainer/functions/loss/negative_sampling.py
Fixed documentation of the negative sampling loss function. This PR includes changes to the equation.
=> Fix documentations of negative sampling

chainer/functions/loss/absolute_error.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py
New style abolute_error to support double backprop.
=> New style absolute_error

docs/source/contribution.rst
=> [backport] Fix minor document bug

chainer/functions/loss/absolute_error.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py
=> [backport] New style absolute_error

tests/chainer_tests/functions_tests/array_tests/test_pad_sequence.py
=> Avoid NaN error in `test_pad_sequence` in debug mode

chainer/functions/loss/negative_sampling.py
=> [backport]Fix documentations of negative sampling

.gitignore, docs/source/tutorial/trainer.rst
* Fix code does not work with GPU.
* Changed all snippets as test code to ensure the code works.
* Removed unused hidden snippets.
Related to #3926.
=> Fix doctest in trainer tutorial

tests/chainer_tests/functions_tests/array_tests/test_pad_sequence.py
=> [backport] Avoid NaN error in `test_pad_sequence` in debug mode

chainer/cuda.py, tests/chainer_tests/test_cuda.py
=> [backport]Allow list, tuple and None in to_cpu and to_gpu

.gitignore, docs/source/tutorial/trainer.rst
=> [backport] Fix doctest in trainer tutorial

chainer/functions/pooling/pooling_nd.py, chainer/utils/type_check.py
=> [backport]User-friendly error checks for pooling input

chainer/functions/loss/sigmoid_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
New style sigmoid_cross_entropy to support double backprop.
=> New style sigmoid_cross_entropy

chainer/functions/loss/sigmoid_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
=> [backport] New style sigmoid_cross_entropy

chainer/computational_graph.py, chainer/cuda.py, chainer/function.py, chainer/function_node.py, chainer/functions/array/transpose_sequence.py, chainer/functions/loss/crf1d.py, chainer/gradient_check.py, chainer/links/connection/mlp_convolution_2d.py, chainer/variable.py, docs/source/tutorial/convnet.rst, docs/source/tutorial/train_loop.rst
=> [backport]doc: Fix some markup

chainer/function_node.py, chainer/variable.py
#3448 
Creating `Variable` is high cost.
=> [backport] Add get_variable_or_none to improve backward performance

chainer/testing/training.py, chainer/training/trainer.py, tests/chainer_tests/testing_tests/test_training.py
=> Add extensions as trainer argument

chainer/functions/array/copy.py, tests/chainer_tests/functions_tests/array_tests/test_copy.py
=> [backport] New style copy function

chainer/functions/connection/bilinear.py, tests/chainer_tests/functions_tests/connection_tests/test_bilinear.py
New style bilinear function to support double backprop.
=> New style bilinear

chainer/functions/noise/gaussian.py, tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
New style gaussian noise to support double backprop.
=> New style Gaussian

chainer/functions/util/forget.py
It backports Forget inputs as Variables #3788
=> [backport] Forget inputs as Variables

chainer/functions/array/pad.py
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.pad.html
=> fix broken link in chainer.function.pad document

chainer/links/connection/n_step_gru.py, chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py
=> [backport] Avoid mixing cupy.ndarray and numpy.ndarray in n_step_xxx links

chainer/functions/array/pad.py
=> [backport] fix broken link in chainer.function.pad document

chainer/function_hook.py, chainer/functions/__init__.py, chainer/gradient_check.py, chainer/training/extensions/evaluator.py, chainer/variable.py, docs/source/reference/check.rst, docs/source/reference/function_hooks.rst, docs/source/reference/functions.rst, docs/source/tutorial/convnet.rst, docs/source/tutorial/train_loop.rst
=> [backport]Function references in docs to point to FunctionNode

chainer/testing/backend.py, chainer/testing/parameterized.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
=> [backport]  Refactor unit tests for various backend configuration

chainer/functions/connection/convolution_2d.py
Add `dilate` argument to `convolution_2d` documentation.
=> Add dilate argument docs

chainer/functions/connection/n_step_rnn.py
=> [backport]Fix backprop dim for unused lstm states on gpu

chainer/functions/connection/deconvolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
Fixes #3874
This PR depends on ~#3862~ (thus ~#3850~) and ~#3848~
=> Skip cuDNN in deconvolution_2d if dilate != 1 and deterministic

tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
=> [backport] Simplify to_gpu in RNN tests

chainer/functions/connection/n_step_rnn.py
Backport PR of "Remove unused function #4051"
=> [backport] Remove unused function

chainer/functions/math/det.py, chainer/functions/math/inv.py, tests/chainer_tests/functions_tests/math_tests/test_det.py, tests/chainer_tests/functions_tests/math_tests/test_inv.py
This PR implements new style `det`, `batch_det` function.
~~This PR includes redundant error check code.  Needs to be revised once #3770 is merged.~~ (done)
~~Needs tolerance adjustments.~~ (done)
=> new style det and batch_det function

chainer/functions/loss/negative_sampling.py, tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
New style negative_sampling to support double backprop.
=> New style negative_sampling

chainer/gradient_check.py
numpy.stack is not supported until 1.10.
=> Avoid numpy.stack which is supported in NumPy 1.10

tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
I removed redundant test case class which check if cuDNN is called and simplify the test.
merge #4046 first
related to #4045
=> Simplify RNN test that check if cuDNN is called

chainer/variable.py, tests/chainer_tests/test_variable.py
=> [backport] Fix debug_print() with empty Variable

chainer/reporter.py
=> [backport] Fix the example in the document of Reporter

chainer/computational_graph.py, chainer/functions/loss/softmax_cross_entropy.py, chainer/functions/math/matmul.py, chainer/functions/noise/dropout.py, chainer/iterators/multiprocess_iterator.py, chainer/links/loss/black_out.py, chainer/links/normalization/batch_normalization.py, chainer/links/normalization/batch_renormalization.py, chainer/optimizer.py, chainer/training/extensions/evaluator.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py, tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
=> [backport]Avoid unnecessary `hasattr`

chainer/function_node.py, chainer/functions/__init__.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/evaluation/accuracy.py, chainer/functions/loss/black_out.py, chainer/functions/loss/hinge.py, chainer/functions/loss/triplet.py, chainer/functions/normalization/l2_normalization.py, chainer/functions/util/forget.py, chainer/training/extensions/evaluator.py, chainer/training/extensions/micro_average.py
=> [backport] Fix incorrect use of single backslashes in docstrings

tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
=> [backport] Simplify RNN test that check if cuDNN is called

examples/seq2seq/seq2seq.py
Fixes https://github.com/chainer/chainer/pull/4003#issuecomment-348389484
=> avoid using xp.stack in examples

examples/seq2seq/seq2seq.py
=> [backport] avoid using xp.stack in examples

chainer/testing/backend.py
=> [backport] Fix cuda import path

chainer/variable.py, tests/chainer_tests/test_variable.py
=> Update VariableNode.data if new data is assigned 

chainer/functions/connection/dilated_convolution_2d.py
https://github.com/chainer/chainer/pull/4021#issuecomment-351321748
=> v3: fix cuda import to use chainer.backends

docs/source/tutorial/trainer.rst
=> [backport] fix typo in trainer tutorial

chainer/variable.py, tests/chainer_tests/test_variable.py
=> [backport]Update VariableNode.data if new data is assigned

examples/text_classification/README.md, examples/text_classification/nets.py, examples/text_classification/nlp_utils.py, examples/text_classification/run_text_classifier.py, examples/text_classification/text_datasets.py, examples/text_classification/train_text_classifier.py
This PR adds an example of text classification with Chainer.
This example can
- switch typical architectures; RNN/CNN/BoW
- switch typical text classification datasets
- tell a simple way to save and exploit a trained model with vocabulary and other setup
=> Add text classification example

chainer/datasets/svhn.py
=> [backport] Minor change to enable using Chainer with PyPy

examples/seq2seq/seq2seq.py
As @lboloni pointed out, it does not work in GPU mode.
https://github.com/chainer/chainer/pull/4087#commitcomment-26328157
=> fix seq2seq example not working with GPU

examples/seq2seq/seq2seq.py
=> [backport] fix seq2seq example not working with GPU

docs/source/reference/functions.rst, docs/source/reference/links.rst
=> fix undocumented functions and links

docs/source/reference/functions.rst, docs/source/reference/links.rst
=> [backport] fix undocumented functions and links

chainer/reporter.py, chainer/training/extensions/log_report.py, tests/chainer_tests/test_reporter.py
=> [backport] Add serialize to Summary

examples/imagenet/googlenetbn.py
I defined the size of out1 in inc4c and inc4d in the same way as CNTK.
=> Change the size of out1 in inc4c and inc4d 

examples/imagenet/googlenetbn.py
=> [backport] Change the size of out1 in inc4c and inc4d

chainer/training/extensions/evaluator.py, tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
Squashed version of https://github.com/chainer/chainer/pull/4137 .
=> Call iterators' finalizers in Evaluator's finalizer

chainer/gradient_check.py
The purpose of normalization of the direction vector is not easily guessed from the code.
I described the purpose and assumption.
=> Write comment about direction normalization in gradient_check.check_backward

chainer/gradient_check.py
=> [backport] Write comment about direction normalization in gradient_check.check_backward

chainer/functions/math/basic_math.py, chainer/functions/math/matmul.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_matmul.py
This PR implements new style `matmul`, `batch_matmul` function and `@` operator.
Confirmed 10000 repeats pass.
=> new style matmul functions and operators

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py
=> avoid using np.stack which is introduced in NumPy 1.10

tests/chainer_tests/test_variable.py
=> [backport] add unit test for NumPy 1.14 array textual representation

chainer/training/extensions/progress_bar.py, chainer/training/triggers/early_stopping_trigger.py, chainer/training/triggers/interval_trigger.py, examples/cifar/train_cifar.py
Related to #3351 
I have tried to change the way to detect `training_length`.
=> Modify detect training length

docs/source/upgrade.rst, docs/source/upgrade_v2.rst
=> [backport] Add upgrade guide for v3 and v4

chainer/functions/math/basic_math.py, chainer/functions/math/matmul.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_matmul.py
=> [backport] new style matmul functions and operators

chainer/functions/__init__.py, chainer/functions/connection/shift.py, tests/chainer_tests/functions_tests/connection_tests/test_shift.py
This PR implements the shift function, proposed in the following paper: https://arxiv.org/abs/1711.08141
It is a useful alternative to spatial convolutions for reducing the number of model parameters.
=> Add shift function

chainer/training/extensions/evaluator.py, tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
=> [backport] Call iterators' finalizers in Evaluator's finalizer

chainer/functions/math/identity.py
=> [backport] Remove empty retain

chainer/functions/loss/ctc.py
=> [backport] Use log1p

chainer/functions/loss/huber_loss.py, tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
New style huber_loss to support double backprop.
=> New style huber_loss

chainer/functions/loss/huber_loss.py, tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
=> [backport] New style huber_loss

chainer/links/model/vision/googlenet.py
=> [backport] fix GoogLeNet to define network using init_scope

chainer/functions/loss/ctc.py
I optimized logsumexp in ctc by using a custom kernel. It is about 10% faster than the original.
=> Optimize ctc
