tests/chainer_tests/test_link.py

[backport] Add tests for __delattr__ in Link and Chain

---

chainer/function_node.py

Fixed a documentation bug in `retain_inputs()` and `retain_outputs()` and also made a few minor wording fixes.

documentation fix in FunctionNode

---

chainer/training/extensions/evaluator.py

When using `extensions.Evaluator` without the target of 'main', it occurs`KeyError`.

fix evaluator target without 'main'

---

chainer/training/extensions/evaluator.py
tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py

[backport] Fix evaluator target without 'main'

---

tests/chainer_tests/functions_tests/array_tests/test_get_item.py

This fixes a bug.
The option `dtype` is not used in the test functions.
I don't think it is necessary to check for `int32, uint32, ulonglong, uint64` because these dtypes are not differentiable.
Also, the function `__getitem__` and `scatter_add` are tested with these dtypes in tests for CuPy.

Delete redundant test settings for get_item

---

chainer/function_node.py
chainer/variable.py

`get_variable` create `Variable` when `_variable` reference is dead.
But, some functions do not need temporary `Variable` object.

Add get_variable_or_none to improve backward performance

---

chainer/functions/normalization/batch_normalization.py

The aim of this PR is to use cuDNN's batch-normalization (BN) functions safely when data type of input is fp16.
The cuDNN's BN functions support fp16 data type, but they are not used in Chainer now when data type of input is fp16. As far as I know, that is mainly because data types of some parameters like `gamma` and `beta` in BN layer must be fp32 in cuDNN's BN functions when data type of inputs is fp16 though Chainer assumes data types of inputs and parameters are the same.
Actually I've already sent a PR about this issue before (#2299). The solution of the previous PR is to decide what data type should be used for parameters like `gamma` and `beta` at the `Link` object, and keep the variables with the decided data type. With the previous PR, in case of fp16 input, the parameters data …

Use cuDNN BN functions even when inputs data type is fp16

---

chainer/functions/normalization/batch_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py

If we can use cudnn, the code below raises AttributeError because of missing inv_std.
```
import chainer
X = np.random.uniform(0, 1, (1, 1))
gamma, beta = np.ones(1), np.zeros(1)
mean, var = np.mean(X, axis=0), np.var(X, axis=0)
X, gamma, beta, mean, var = [chainer.cuda.to_gpu(e, 0) for e in [X, gamma, beta, mean, var]]
X, gamma, beta = [chainer.Variable(e) for e in [X, gamma, beta]]
y = chainer.functions.fixed_batch_normalization(X, gamma, beta, mean, var)
num = chainer.functions.sum(y)
num.backward()
```
The test of fixed_batch_normalization can not detect the error because `param_shape` used in the test does not make `can_use_cudnn` true in forward computation.
Therefore, I added a shape to the test and fixed it.

inv_std is missing in backward of FixedBatchNormalization if it use cudnn.

---

chainer/functions/normalization/batch_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py

[backport] inv_std is missing in backward of FixedBatchNormalization if it use cudnn

---

docs/source/tutorial/basic.rst

Found some links being dead in the tutorial. It seems that module names must be fully qualified.

fix dead links to modules in tutorial

---

chainer/training/extensions/log_report.py

Some triggers including `IntervalTrigger` have `serialize` method. `LogReport` should call this method in serialization.

Serialize trigger in LogReport

---

chainer/configuration.py

I think #2862 can be closed with this fix, because configuration page contains an example of `using_config`.

Add seealso link in using_config

---

.travis.yml

I changed warnings configuration to check DeprecationWarnings. Note that some `ignore` configurations are required because Python itself shows DeprecationWarnings.

Check deprecation warining in Travis

---

docs/source/tutorial/convnet.rst

Removed a line from the example code in the documentations, where an unused variable was declared. 
See #3484

Minor fix in docs

---

chainer/datasets/ptb.py
chainer/datasets/sub_dataset.py
chainer/functions/activation/tree_lstm.py
chainer/functions/array/pad_sequence.py
chainer/functions/array/split_axis.py
chainer/functions/connection/n_step_gru.py
chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py
chainer/functions/loss/crf1d.py
chainer/functions/math/matmul.py
chainer/functions/pooling/spatial_pyramid_pooling_2d.py
chainer/gradient_check.py
chainer/links/caffe/caffe_function.py
chainer/links/connection/lstm.py
chainer/links/connection/tree_lstm.py
chainer/links/loss/crf1d.py
chainer/training/extensions/evaluator.py
chainer/training/triggers/interval_trigger.py
chainer/training/triggers/manual_schedule_trigger.py
chainer/training/triggers/minmax_value_trigger.py
docs/source/_docstring_check.py
docs/source/conf.py

Fixes #3397.
Fixed corrupted "Returns" section.
I introduced the docstring checker which is triggered by sphinx autodoc.
It can perform arbitrary check if we implement a rule.

doc: Docstring checker to fix returns section markup

---

chainer/function_node.py
tests/chainer_tests/test_function_node.py

Add some type checks in `chainer.grad()`.
This prevents a pitfall like https://chainer-jp.slack.com/archives/C3UBX3V32/p1505562922000013

Type check in chainer.grad

---

chainer/functions/array/reshape.py

related to #3242.
The example code of reshape is not highlighted. It may be occurred by the parse error.
This page said following: http://www.sphinx-doc.org/en/stable/markup/code.html
> Within Python highlighting mode, interactive sessions are recognized automatically and highlighted appropriately. Normal Python code is only highlighted if it is parseable (so you can use Python as the default, but interspersed snippets of shell commands or other code blocks will not be highlighted as Python).
And this PR, I just remove the some strings in order not to make parse error, just delete the line `chainer.utils.type_check.InvalidType:`.

fix highlight error of chainer/functions/array/reshape.py

---

chainer/cuda.py

Array is copied if it is on a different device.

doc: Remove obsolete statement in to_gpu

---

chainer/testing/array.py

Related to #2936.
If error information is dumped directly to stdout, there's a problem when using `@testing.retry`: intermediate failure information is dumped even if a subsequent trial succeeded.
I fixed so that information is put into the exception.
```
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=1e-05
(mismatch 100.0%)
x: array(-0.01787613206619142)
y: array(-0.01786161959171295, dtype=float32)
assert_allclose failed: 
shape: () ()
dtype: float64 float32
i: (0,)
x[i]: -0.01787613206619142
y[i]: -0.01786161959171295
err[i]: 1.451247447846818e-05
x: -0.01787613206619142
y: -0.01786161959171295
```

Avoid unwanted output of assert_allclose failure

---

chainer/cuda.py

[backport] Document to_gpu stream option deprecation

---

chainer/link.py

Fixed some documentation around `init_scope`.
* "an initialization scope" was rendered as a code fragment, which is weird. (https://docs.chainer.org/en/stable/reference/core/generated/chainer.Chain.html#chainer.Chain.add_link)
* `self` in examples should be `link` or `chain`, shouldn't they?

Fix doc of init_scope

---

docs/source/reference/environment.rst

Currently, `chainer.Function` is referred to from `CHAINER_TYPE_CHECK` documentation, but it's better to link to [Assert and Testing](https://docs.chainer.org/en/stable/reference/check.html) page instead.

doc: Fix type-check reference

---

docs/source/_static/css/modified_theme.css

In current documentation, tables cause horizontal scroll when the content is large (e.g. [1](https://docs.chainer.org/en/v2.0.2/reference/links.html), [2](https://docs.chainer.org/en/v2.0.2/reference/environment.html)), which makes it hard to read.
This PR enables the contents of tables to wrap.
TODO: Apply to CuPy documentation

doc: Avoid table scroll

---

chainer/initializers/constant.py

This PR makes constant initializers (i.e. `initializers.Zero`, `One` and `NaN`) classes instead of functions.
Function-wise, this PR does not change anything.
The main motivation is documentation; looking at [this page](https://docs.chainer.org/en/v2.0.2/reference/initializers.html), it may confusing that their description and definition look totally different from other initializers.

Define constant initializers as classes

---

chainer/__init__.py
chainer/functions/connection/convolution_2d.py
chainer/functions/connection/deconvolution_2d.py
docs/source/reference/core/configuration.rst

This PR adds Tensor-Core support for convolutions.
With this PR, Tensor-Core is automatically used in convolution layers when Tensor-Core is available. You can also manually enable/disable use of Tensor-Core by setting global configuration variable `cudnn_use_tensor_core` to True/False like below
from chainer import configuration
configuration.config.cudnn_use_tensor_core = [True|False]
Please note that https://github.com/cupy/cupy/pull/494 needs to be used in order to test this PR.
Also I would suggest that you apply #3386 first.

Tensor-Core support for convolutions

---

chainer/functions/__init__.py
chainer/functions/array/flip.py
docs/source/reference/functions.rst
tests/chainer_tests/functions_tests/array_tests/test_flip.py

This PR adds `F.flip(x, axis)`. (Chainer has `F.flipud`, `F.fliplr` already).
The implementation is based on `FunctionNode`.

Add flip function

---

chainer/cuda.py
chainer/functions/activation/lstm.py

LSTM grad-grad calls too many kernels. I used `cupy.fuse` to combine them.
Merge #3206 first.

Fused LSTM grad-grad

---

chainer/function.py

This PR fixes wrong description of `indexes` arguments for `retain_{input,output}`.

fix documention error in Function

---

.travis.yml
chainer/testing/attr.py
setup.cfg
setup.py
tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
tests/chainer_tests/test_runnable.py

#3324 has been reverted by #3589 because it included some unrelated changes.
So this PR is for re-applying the changes only related to the purpose which is to use PyTest.

Replace the test framework with PyTest

---

.gitignore
chainer/utils/__init__.py
chainer/utils/conv.py
docs/source/reference/util.rst
docs/source/reference/util/conv.rst

`get_conv_outsize` and `get_deconv_outsize` is useful to check the output size before actual forward computations.
This PR adds them to the docs.

Add get_conv_outsize and get_deconv_outsize to doc

---

.gitignore

* Remove unneeded `__init__.py`
* Add pytest cahce directory to gitignore

Fix for pytest migration

---

chainer/testing/attr.py
chainer/testing/training.py
chainer/testing/unary_math_function_test.py
setup.py

Note: **Even though I put no-compat label, this PR does not break backward-compatibility.** Backward compatibility was broken when testing framework was replaced with PyTest. I put the label simply to signify that.
This PR removes pytest and mock requirements from Chainer normal installation.
That would reduce the possibility of trouble for users resulting from migration to PyTest.
OTOH, some parts of `chainer.testing` package depend on `pytest` and `mock`. Simply removing requirements would result in `ImportError`s when importing `chainer.testing`. To avoid that, I introduced `is_available()` functions to such modules.
This PR should be backported, because PyTest has introduced to stable branch as well.

Remove requirements for unit testing

---

.travis.yml

Travis fails on OSX Python 3.4 case because of its inspect module.
https://travis-ci.org/chainer/chainer/builds/289372879
As far as I read the source, Python 3.4.3 inspect module looks trying to compare object identity by `==` operator and it is fixed in Python 3.4.4.
Python 3.4.3
https://github.com/python/cpython/blob/f5caf2b30bfe70e5107f816c9e7f7fe3ef5299d9/Lib/inspect.py#L383
Python 3.4.4
https://github.com/python/cpython/blob/fa7193286099f8e4164f4a795afd5ad4a8e229df/Lib/inspect.py#L382
I bump Python version used in Travis OSX Python 3.4 case from 3.4.3 to 3.4.4.

Use Python 3.4.4 on Travis OSX Python 3.4 case

---

.travis.yml

[backport] Use Python 3.4.4 on Travis OSX Python 3.4 case

---

chainer/serializers/npz.py
tests/chainer_tests/serializers_tests/test_npz.py

This PR adds an option to NpzDeserializer that ignores a subset of weights stored in the given npy file.
This is useful in the case when subset of parameters do not have the same shapes as those of the corresponding parameters in the file.
`strict` can ignore copying values in the case when corresponding parameters do not exist at all.
However, there is no easy way to deal with the situation when the corresponding parameters exist, but the shapes differ. Currently, shape mismatch error is raised.
This option is originally intended to solve the above problem. However, I made it a bit more general.
This way, a user can also ignore to copy some values even if their shapes match with the ones stored in the file.

Add ignore option to NpzDeserializer

---

chainer/functions/pooling/average_pooling_nd.py
chainer/functions/pooling/max_pooling_nd.py
chainer/functions/pooling/unpooling_nd.py
chainer/links/connection/tree_lstm.py
chainer/links/normalization/layer_normalization.py
chainer/links/theano/theano_function.py

Currently, users cannot tell if a feature is experimental until they use it.

doc: Add experimental warning in docstring

---

.github/stale.yml

This PR adds a configuration of the stale bot: https://github.com/probot/stale. The numbers of `daysUntilStale` and `daysUntilClose` are borrowed from the configuration used at https://github.com/fchollet/keras. We can change the numbers if they are not suited to our case; feel free to propose other numbers.

Add a stale bot configuration

---

chainer/functions/loss/softmax_cross_entropy.py
tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py

Fix #3311 
This error often happens when all the inputs are masked, and shape is like `(0, 512, 16, 16)`

Prevent ZeroDivisionError in softmax_cross_entropy when input size is 0

---

chainer/testing/unary_math_function_test.py
tests/chainer_tests/testing_tests/test_unary_math_function_test.py

Rel #3578.
Currently `unary_math_function_unittest` decorator, that is a testing helper for math function layers, doesn't support testing new style functions introduced in Chainer v3. This PR fixes the decorator so that it can be used for the new style functions as well as the old style ones for backward compatibility.

Fix math function testing helper to support new style functions.

---

.travis.yml

As OS X container in Travis is heavy, this PR changes the config to run OS X matrix only on master/stable branch.
See also #3671 for discussion.

run OS X test only on master/stable branch to avoid delay

---

docs/source/tutorial/basic.rst

[backport] fix dead links to modules in tutorial

---

chainer/gradient_check.py
tests/chainer_tests/test_gradient_check.py

When passing the `no_grads` argument to the gradient check while at the same time specifying the `dtype` argument, all inputs are cast to the given `dtype` except the ones ignored by `no_grads`.
dtypes of function arguments are thus occasionally mixed, in particular, if a function that is being tested for correct gradients uses a kernel, an error is raises on mismatched dtypes on the kernel call.
This PR fixes this issue by always casting all inputs if `dtype` is specified no matter the value of `no_grads`.

Always cast all inputs to given dtype in gradient check

---

chainer/functions/math/square.py
tests/chainer_tests/functions_tests/math_tests/test_square.py

This PR implements new style `square` function.
I also fixed `unary_math_function_test` decorator to support testing FunctionNode.
I think this is transitional; once https://github.com/chainer/chainer/pull/3499 got merged, it is better to rewrite tests with the new function test template.

New style square function

---

.travis.yml
chainer/testing/attr.py

`pytest` does not support filtering test cases based on parameters of decorators.
(`pytest -m MARKEXPR` only checks [existence of marks and does not evaluate parameters](https://github.com/pytest-dev/pytest/blob/3.2.3/_pytest/mark.py#L167-L199))
This means that filter based on number of GPUs (as documented in the [Contribution Guide](https://docs.chainer.org/en/stable/contribution.html#how-to-run-tests)):
```
$ nosetests path/to/gpu/test.py --eval-attr='gpu<2'
```
no longer work.
This PR fixes `multi_gpu` decorator so that `CHAINER_TESTING_GPU_LIMIT` environment variable can be used to limit number of GPUs used.
The above command needs to be rewritten as:
```
$ export CHAINER_TESTING_GPU_LIMIT=1
$ pytest path/to/gpu/test.py
```

Fix decorators to allow users to filter test cases by number of GPUs

---

chainer/gradient_check.py
tests/chainer_tests/test_gradient_check.py

[backport] Always cast all inputs to given dtype in gradient check

---

docs/source/conf.py

I think Chainer stable documentation should link to CuPy stable documentation.

v3: Fix CuPy intersphinx mapping

---

chainer/__init__.py
chainer/_environment_check.py
docs/source/tips.rst

Fixes #3621.
vecLib does not work correctly in MNIST example.
In this PR, we detect it and show warning.
* Along with this check, I moved Python 3.5.0 check into `chainer._environment_check` for cleanliness of code.
* Relevant section in Tips has been removed, as it's no longer needed.
I haven't tested this PR because I don't have Mac OS X...
When reviwing, please test that it can actually detect vecLib.

Warn about vecLib on Mac OS X

---

appveyor.yml

This PR fixes a failure of AppVeyor CI introduced in https://github.com/chainer/chainer/pull/3624 .

fix to skip GPU tests on AppVeyor

---

setup.cfg

Removes 2 PyTest options globallly set in `setup.cfg`.
- `--maxfail=2`: This should be controlled by the invoker. Also I think CIs should display all errors.
- `--showlocal`: This option dumps local variables. Appearance of the output should be controlled by the invoker.
(Here invoker can be either a CI agent or a developer who invokes pytest manually)

Remove PyTest global option configuration

---

chainer/functions/array/permutate.py
chainer/functions/connection/embed_id.py
chainer/functions/evaluation/accuracy.py
chainer/functions/evaluation/binary_accuracy.py
chainer/functions/evaluation/classification_summary.py
chainer/functions/loss/contrastive.py
chainer/functions/loss/hinge.py
chainer/functions/loss/sigmoid_cross_entropy.py
chainer/functions/loss/softmax_cross_entropy.py
tests/chainer_tests/functions_tests/array_tests/test_permutate.py
tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
tests/chainer_tests/functions_tests/evaluation_tests/test_accuracy.py
tests/chainer_tests/functions_tests/evaluation_tests/test_binary_accuracy.py
tests/chainer_tests/functions_tests/evaluation_tests/test_classification_summary.py
tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
tests/chainer_tests/functions_tests/loss_tests/test_hinge.py
tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py
tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py

Current int type restriction is too strict.
This PR is relax it.

Relax int type restriction

---

docs/source/tips.rst

[backport] fix cupy overview link not working

---

docs/source/reference/function_hooks.rst

`function_hooks.CUDAProfileHook` and `function_hooks.CupyMemoryProfileHook` are very useful features but missing in the reference manual.

Add CUDAProfileHook and CupyMemoryProfileHook to the reference

---

docs/source/conf.py

Related to: #3235 
I found the current check algorithm gives false alarms for
docstrings with multi-sentence summary line.
As it's not trivial to fix this, I'm removing the check.

Stop checking docstring compliance with autosummary

---

chainer/functions/array/split_axis.py

`x` argument of `F.split_axis` should be a variable or an array, not a tuple of them.

Fix split_axis documentation

---

chainer/gradient_check.py

Currently, if `gradient_check` fails, only two values (namely the numerical gradient and the gradient computed by `backward`) are displayed.
```
Not equal to tolerance rtol=0.0001, atol=1e-05
(mismatch 100.0%)
x: array(-1.3064368690828785)
y: array(-1.3061777353286743)
```
With this PR, more informative output that can help investigate the cause will be displayed.
```
AssertionError: check_double_backward failed (eps=0.001 atol=0.001 rtol=0.01)
input[0]:
[[ -3.11279297e-01  -2.77832031e-01]
[  8.89160156e-01  -5.12207031e-01]
[ -2.27689743e-04   5.35644531e-01]]
grad_output[0]:
[[ 0.62451172 -0.03820801]
[-0.06088257 -0.52685547]
[ 0.02798462  0.08563232]]
grad_grad_input[0]:
[[-0.83984375  0.171875  ]
[ 0.19604492 -0.65527344]
[-0.37939453  0.23974609]]
check_backward failed (eps=0.001 …
```

Richer gradient check output

---

chainer/training/extensions/plot_report.py

In Chainer, both `plot` and `plt` are used as a shot form of `matplotlib.pyplot`. In [the official document](https://matplotlib.org/users/pyplot_tutorial.html), they use `plt`. So, I rewrote all `plot` to `plt` for consistency.

Rename plot -> plt

---

chainer/iterators/multiprocess_iterator.py
tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py

Numpy shares the internal state of `numpy.random` across all threads. So if we use `numpy.random` from non-main thread, random number generation will be non-deterministic, dependent on context switch timing.
It hurts reproducibility. This PR fix the problem, by creating a distinct `RandomState` for each prefetch loop.

Use a distinct RandomState in the prefetch thread of MultiProcessIterator

---

docs/source/reference/core/configuration.rst

Improve docs of the configurations flags `enable_backprop` and `train`, motivated by the fact that the difference between these two flags are not very clear in the current documentation to new users.

Improve doc of configuration flags

---

.travis.yml
appveyor.yml
chainer/testing/__init__.py
chainer/testing/unary_math_function_test.py
tests/chainer_tests/functions_tests/pooling_tests/pooling_nd_helper.py

`run_module` function still depends on `nose`.
I changed to use `pytest`.

remove nose dependency in tests

---

chainer/gradient_check.py

`direction` is reverted in #3569 
After merging #3652, this code will be enabled.
related to #3425

Remove direction

---

docs/source/contribution.rst

As test framework is changed from nose to pytest, we need to update contrib guide.
This PR documents the behavior of new decorator proposed in #3624.

fix contribution guide for test framework change

---

chainer/functions/array/reshape.py
chainer/functions/pooling/upsampling_2d.py
docs/source/tutorial/type_check.rst

Related: https://github.com/chainer/chainer-test/pull/342
Fixed doctest to pass with python 3.5.

Use python 3.5 for doctest

---

tests/chainer_tests/functions_tests/math_tests/test_average.py

If the sum of weights is close to zero, it emits `RuntimeWarning`.
```
tests/chainer_tests/functions_tests/math_tests/test_average.py::TestAverage_param_38::test_backward_cpu
chainer/functions/math/basic_math.py:303: RuntimeWarning: overflow encountered in divide
return gx0, utils.force_array(-gx0 * x[0] / x[1])
```

Fix normalization warning in F.average test

---

chainer/functions/__init__.py
chainer/functions/noise/gumbel_softmax.py
docs/source/reference/functions.rst
tests/chainer_tests/functions_tests/noise_tests/test_gumbel_softmax.py

This PR adds function which draws samples from Gumbel-Softmax distribution, described in [Categorical Reparameterization with Gumbel-Softmax](https://arxiv.org/abs/1611.01144).

Add Gumbel-Softmax sampling function

---

.travis.yml
chainer/testing/attr.py

Backport #3624.
The backport of #3624 was once merged to v3 branch in #3683, but I find that the backport PR was not made properly. This PR reverts #3683 and backports #3624 again. Please see the diff for the problem line.

[backport] Fix decorators to allow users to filter test cases by number of GPUs

---

chainer/testing/parameterized.py

In PyTest, parameterized test does not include its parameter information in the error message.
This PR does that by wrapping every test methods.

Useful error message for parameterized tests

---

chainer/serializers/hdf5.py
chainer/serializers/npz.py
tests/chainer_tests/serializers_tests/test_npz.py

This PR support file-like objects in `save_npz`/`load_npz`.

Support file-like object in npz serializer

---

chainer/functions/loss/softmax_cross_entropy.py
tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py

[backport] Prevent ZeroDivisionError in softmax_cross_entropy when input size is 0

---

tests/chainer_tests/functions_tests/math_tests/test_inv.py

The current test code for `F.inv` does not test exception case correctly.
These tests are intended to test shape check logic, but it is catching the TypeError from numpy.
```
>>> numpy.zeros(1, 2, 2)
TypeError: data type not understood
```

fix F.inv test does not test type error as expected

---

chainer/functions/evaluation/r2_score.py
tests/chainer_tests/functions_tests/evaluation_tests/test_r2_score.py

`F.r2_score` could emit zero-division warning.
This PR suppresses this warning.
```
tests/chainer_tests/functions_tests/evaluation_tests/test_r2_score.py::TestAccuracy_param_46::test_forward_cpu
/work/chainer/chainer/functions/evaluation/r2_score.py:34: RuntimeWarning: divide by zero encountered in true_divide
ret = xp.where(SS_tot != 0, 1 - SS_res / SS_tot, 0.0)\
/work/chainer/tests/chainer_tests/functions_tests/evaluation_tests/test_r2_score.py:24: RuntimeWarning: divide by zero encountered in true_divide
return numpy.where(SS_tot != 0, 1 - SS_res / SS_tot, 0.0)
```

Avoid zero-division warning in F.r2_score

---

chainer/cuda.py
tests/chainer_tests/test_cuda.py

Currently you can't write `xp is cuda.cupy` because `cuda.cupy` is not defined if CuPy is not installed.
This PR defines dummy `cuda.cupy` even when it's not installed.

Define dummy cuda.cupy when cupy is not available

---

.travis.yml
setup.cfg
tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py

I fix setup.cfg to use pytest-warnings instead of changing PYTHONWARNINGS environment variable.

Use pytest-warnings to set warnings configuration

---

chainer/links/caffe/caffe_function.py

Currently `CaffeFunction` unnecessary performs normal distribution initializations on some layers.
Furthermore, directly accessing Protobuf fields from Python is slow. [Protobuf Python extension efficiently converts repeated scalar values into a python list when slice-indexed](https://github.com/google/protobuf/blob/v3.4.0/python/google/protobuf/pyext/repeated_scalar_container.cc#L290), so using an intermediate list is faster.
This PR fixed the two inefficiencies.  I performed a benchmark loading the VGG-19 caffemodel, on my Linux desktop machine equipped with Core i5-3550 CPU.
```py
from chainer.links.caffe import CaffeFunction
from time import perf_counter
COUNT = 5
holder = [None] * COUNT
t1 = perf_counter()
for i in range(COUNT):
holder[i] = …
```

Make caffe model loading faster (~2.4 times on my benchmark)

---

chainer/function_node.py

If a user were using traditional `chainer.Function` class object and the function class were converted to `chainer.FunctionNode`, the user would get an unfriendly error: ```TypeError: 'Softmax' object is not callable```.
This PR implements `FunctionNode.__call__` which simply raises an exception with more useful message.
Additionally, if the function class in question is one of Chainer's builtin functions, it adds to the message that it's not recommended to use function classes directly.
```
>>> import chainer.functions as F
>>> f = F.Softmax()
>>> f(3)
File "/data/work/w/repos/chainer/chainer/function_node.py", line 196, in __call__
raise RuntimeError(msg)
RuntimeError: Chainer's built-in function class object …
```

Raise user-friendly error when FunctionNode is used like Function object

---

chainer/optimizers/adam.py
chainer/optimizers/rmsprop.py
tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py

The default `eps` of `1e-8` is too small for float16.
This PR lets optimizers raise `ValueError` for such cases, and fixes unit test by explicitly specifying `eps` for float16.
`RuntimeWarning` below will be suppressed with this fix.
```
tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py::TestAdam_param_0::test_linear_model_cpu
/data/work/w/repos/chainer/chainer/optimizers/adam.py:61: RuntimeWarning: divide by zero encountered in true_divide
param.data -= self.lr * m / (numpy.sqrt(v) + hp.eps)
/data/work/w/repos/chainer/chainer/functions/activation/log_softmax.py:19: RuntimeWarning: invalid value encountered in subtract
y = x - m
```

Check too small eps in Adam and RMSprop optimizers

---

setup.cfg

Theano 0.8 causes DeprecationWarning with Python 3.6. I fixed warnings configuration to ignore them. Note that problem is fixed in theano 0.9.

Ignore DeprecationWarnig caused in theano

---

chainer/functions/util/forget.py

* I think the word *internal* is ambiguous. *intermediate* instead would help understanding the behavior more easily.
* *this method* is not appropriate; `F.forget()` is a function.
* etc.

Improve docs of F.forget

---

chainer/cuda.py

Please merge cupy/cupy#472 first.
CuPy provides default memory pool in cupy/cupy#472.
So, this PR uses CuPy default memory pool.

Use CuPy default memory pool

---

setup.cfg

This PR backports the PR "Ignore DeprecationWarnig caused in theano" #3785 to v3.

[backport] Ignore DeprecationWarnig caused in theano

---

chainer/optimizer.py

This PR fixes the problem that error will occur **when resuming training from a snapshot that has different setting of `update_rule.enabled` for params**. The code reproducing the problem is here: https://github.com/jinjiren/chainer-examples/blob/master/reproducing_the_freezing_unfreezing_problem.ipynb
More specifically, when finetuning a model to a different dataset, sometimes we would like to first freeze all layers but the fc layer, and after training some epochs, we then start to train all layers. However, if we want to resume a snapshot that contains freezing layers to fully training all layers, such error will occur `KeyError: 'updater/optimizer:main/predictor/l2/W/m is not a file in the archive'`.
Full error message:
```
-------------------------------------------------------------- …
```

Fix the problem with resuming training when switching the freezing layers

---

docs/source/tutorial/trainer.rst

This PR fixes doctest failure of trainer tutorial.
`testsetup` is repalced with `testcode` with `:hide:`, as `testsetup` runs before other `testcode` blocks.

fix doctest failure in trainer tutorial

---

tests/chainer_tests/functions_tests/pooling_tests/test_upsampling_2d.py

Backport of #3410. It seems to have been left not backported, causing CI of the stable branch unstable.

[backport] Stabilize upsampling_2d test

---

chainer/functions/array/pad_sequence.py
tests/chainer_tests/functions_tests/array_tests/test_pad_sequence.py

New style pad_sequence to support double backprop.
Note that we still need the check `if gy.size == 0:` in order to make it compatible with NumPy 1.9 which changes the shape of the array in case of size 0.

New style pad_sequence

---

chainer/functions/math/minimum.py

This PR removes an unnecessary branch in `chainer.functions.minimum` forward computation, which might cause slight cost but  it would be enough to ignore.

Remove unnecessary branch in minimum forward.

---

chainer/functions/loss/sigmoid_cross_entropy.py

functions.sigmoid_cross_entropy 's document has a wrong description about `t`. This PR fixes it.

Fix sigmoid_cross_entropy doc about t

---

chainer/links/connection/linear.py
chainer/links/connection/lstm.py
chainer/links/normalization/layer_normalization.py
tests/chainer_tests/links_tests/connection_tests/test_linear.py
tests/chainer_tests/links_tests/connection_tests/test_lstm.py
tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py

Fixes #3863, avoiding 0-division when the batch dimension is 0.

Avoid zero division error in linear init call

---

chainer/dataset/download.py

Using stderr instead of stdout for Downloading... message.
stdout is captured by doctest, so it is hard to write doctests using get_mnist etc.

use stderr for Downloading... message

---

chainer/links/connection/linear.py
chainer/links/connection/lstm.py
chainer/links/normalization/layer_normalization.py
tests/chainer_tests/links_tests/connection_tests/test_linear.py
tests/chainer_tests/links_tests/connection_tests/test_lstm.py
tests/chainer_tests/links_tests/normalization_tests/test_layer_normalization.py

[backport] Avoid zero division error in linear init call

---

docs/source/reference/functions.rst

`expm1` seems to be missing in the document.

Add expm1 to the document.

---

docs/source/install.rst

Chainer v4.0 will require CuPy v4.0.

fix CuPy requirment version

---

docs/source/tutorial/basic.rst

fix linear layer math document in [Official tutorial's Links section](https://docs.chainer.org/en/stable/tutorial/basic.html#links).
Currently it says "f(x) = Wx + b", but chainer's linear layer actually calculate "f(x) = xW^\top + b".  `Links.Lenear` calls https://github.com/chainer/chainer/blob/master/chainer/functions/connection/linear.py#L78, which self-documents to calculate Y = xW^\\top + b and actually this function [transposes](https://github.com/chainer/chainer/blob/master/chainer/functions/connection/linear.py#L47) the matrix $W$.

fix Link tutorial’s linear layer document math

---

chainer/testing/parameterized.py

This PR fixes to show test parameter for exceptions other than AssertionFailure.
This is helpful to diagnose why exception occurred during writing tests.

catch all exceptions in parameterized test

---

chainer/optimizer.py
chainer/optimizers/ada_delta.py
chainer/optimizers/ada_grad.py
chainer/optimizers/adam.py
chainer/optimizers/momentum_sgd.py
chainer/optimizers/nesterov_ag.py
chainer/optimizers/rmsprop.py
chainer/optimizers/rmsprop_graves.py
chainer/optimizers/sgd.py
chainer/optimizers/smorms3.py

Code to close issue #3211 .
Allow models to be passed as an argument to an optimizer, so
```
optimizer = chainer.optimizers.SGD()
optimizer.setup(model)
```
becomes:
```
optimizer = chainer.optimizers.SGD(model)
```
Change added to all `optimizers`. Old two-line method also still valid.
Tested by running new one-line method and old method on SGD, then running new method on all `optimizers` after changing code.

Enable optimizer model setup with instantiation

---

docs/source/tutorial/basic.rst

[backport] fix Link tutorial’s linear layer document math

---

docs/source/tutorial/trainer.rst

Example code in https://docs.chainer.org/en/stable/tutorial/trainer.html#evaluate-a-pre-trained-model is broken.
`y = model(x)` raises `IndexError` because `x` is just one data, not a minibatch of length 1. (I have no idea about chaier's interface yet, but maybe it works at some previous version?)
And because the resulting `y` is not `np.array` anymore, we should access `y.data` instead. (or `y.array` ? which is better?)

fix trainer tutorial evaluate example code

---

chainer/gradient_check.py

Made two error messages related to gradient check errors more verbose. 
The messages now include actual/expected values. Simply because when actual values don't match expected values in assertions, we often want to know in what sense they differ (w/o their internal variable name).

Verbose error in gradient check

---

tests/chainer_tests/functions_tests/loss_tests/test_triplet.py

Fix `F.triplet` double_backward test occasionally failing.
Confirmed 10000 repeats.

Adjust tolerance for triplet loss function test

---

tests/chainer_tests/functions_tests/math_tests/test_linear_interpolate.py

Fix F.linear_interpolate double-backward tests occasionally failing.
Confirmed 10000 repeats.
https://travis-ci.org/kmaehashi/chainer/jobs/305198079#L1281

adjust tolerance for F.linear_interpolate double_backward tests

---

chainer/functions/connection/n_step_gru.py
chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py

This PR will fix #2944.
Bi-LSTM, Bi-GRU, and Bi-RNN need following shape (2S, B, N).
Latent docs in Bi-LSTM is fixed.
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.n_step_bilstm.html
So I just modify Bi-GRU and Bi-RNN here.

Fix docs in n_step_xxx

---

chainer/testing/parameterized.py

If `AssertionError` is re-raised from `testing.parameterized`, its original traceback is not shown.
```
E   AssertionError:
E   Fail: 1, Success: 0
E
E   The first error message:
E   Traceback (most recent call last):
E     File "/data/work/w/repos/chainer/chainer/testing/parameterized.py", line 43, in wrap
E       return method(*args, **kwargs)
E     File "/data/work/w/repos/chainer/tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py", line 93, in test_backward_cpu_gpu
E       y_g = self.link(xg, tg)
E   AttributeError: 'NegativeSamplingFunction' object has no attribute 'samples'
E
E   During handling of the above exception, another exception occurred:
E
E   Traceback (most recent call last):
E     File "/data/work/w/repos/chainer/chainer/testing/condition.py", line 60, …
```

Show original traceback in `testing.parameterized`

---

docs/source/reference/links.rst

Fixes #3485.
(for `zoneout` funciton it will be fixed in #3949)

add StatefulZoneoutLSTM to docs

---

examples/seq2seq/README.md

README's cmd is incorrect.
```
$ python wmt_preprocess.py giga-fren.release2.fixed.en giga-fren.preprocess.en \
--vocab-file vocab.en
-$ python wmt_preprocess.py giga-fren.release2.fixed.en giga-fren.preprocess.fr \
+$ python wmt_preprocess.py giga-fren.release2.fixed.fr giga-fren.preprocess.fr \
--vocab-file vocab.fr
```

small fix for the example of seq2seq

---

chainer/__init__.py
docs/source/reference/core/debug.rst
docs/source/reference/environment.rst

Debug mode is very useful to analyze various runtime problems.
However, it's not sufficiently documented.
This PR improves documentation to some extent.

doc: improve debug mode documentation

---

tests/chainer_tests/functions_tests/evaluation_tests/test_classification_summary.py

[backport] Avoid `NaN` in test of `F.classification_summary`

---

chainer/utils/array.py

Skip unnecessary array manipulation ops in array utility. 
This is particularly useful if functions are called with Variable arguments.

Skip unnecessary array util ops

---

chainer/__init__.py
chainer/cuda.py

Moving these functions to `chainer.cuda` to keep `chainer.__init__.py` uncluttered.

Move should_use_cudnn and should_use_cudnn_tensor_core to chainer.cuda

---

.travis.yml

As [Travis updated their macOS image to Xcode 8.3](https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce), macOS tests are currently failling.
This PR fixes the issue.
* Remove `pyenv-pip-rehash` installation, because it causes error and is no longer needed.
https://github.com/pyenv/pyenv-pip-rehash
* Remove `oclint` package, that conflicts with GCC installed via `hdf5`.
Some other projects are doing the same thing: https://github.com/search?utf8=%E2%9C%93&q=%22os%3A+osx%22+%22brew+cask+uninstall+oclint%22&type=Code
I confirmed that this work in my master branch. (as currently macOS tests are not enabled for PRs)
https://travis-ci.org/kmaehashi/chainer/builds/308838386

fix macOS test in Travis

---

chainer/cuda.py
tests/chainer_tests/test_cuda.py

This PR improves `cuda.to_cpu` and `cuda.to_gpu` by accepting `None` and a sequence of arrays.

Allow list, tuple and None in to_cpu and to_gpu

---

chainer/functions/pooling/pooling_nd.py
chainer/utils/type_check.py

Fixes #3554 
* Check if the spatial dimension does not include `0`
* Check if the spatial dimension is not empty `()`

User-friendly error checks for pooling input

---

chainer/__init__.py
chainer/cuda.py

[backport] Move should_use_cudnn and should_use_cudnn_tensor_core to chainer.cuda

---

chainer/gradient_check.py
tests/chainer_tests/test_gradient_check.py

This PR adds an option to `numerical_grad` and `check_backward` to check for non-differentiable inputs.

Check for non-differentiable inputs

---

chainer/function_hook.py
chainer/functions/__init__.py
chainer/gradient_check.py
chainer/training/extensions/evaluator.py
chainer/variable.py
docs/source/reference/check.rst
docs/source/reference/function_hooks.rst
docs/source/reference/functions.rst
docs/source/tutorial/convnet.rst
docs/source/tutorial/train_loop.rst

Made a couple of changes to the docs where some references to the old style `Functions` were replaced with references to `FunctionNode`s.
Some very minor grammatical errors and relevant doc changes are also included.

Function references in docs to point to FunctionNode

---

chainer/functions/util/forget.py

Fixes #3449 .
Basically, it wraps all ndarray inputs to `F.forget` as Variables to ensure that backward is called.

Forget inputs as Variables

---

chainer/testing/parameterized.py

[backport] Show original traceback in `testing.parameterized`

---

chainer/links/connection/n_step_gru.py
chainer/links/connection/n_step_lstm.py
chainer/links/connection/n_step_rnn.py

`indices` is always `numpy.ndarray`, leading to mixture of numpy/cupy ndarrays.
This fix can be tested with #4029, but I separated the PRs because #4029 might be unsafe to backport.

Avoid mixing cupy.ndarray and numpy.ndarray in n_step_xxx links

---

chainer/testing/backend.py
chainer/testing/parameterized.py
tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py

This PR depends on ~#3850~.
Currently in unit tests of functions, various data parameters (`x_dtype`, `stride`, `nobias`, etc.) and backend parameters (`use_cudnn`, `autotune`, etc.) are mixed. There are some problems regarding this scheme:
* It's exponentially difficult to add new backends.
* Some tests are duplicated. For example, CPU tests are performed for every combination of `use_cudnn`, `cudnn_deterministic`, `autotune`, etc.
This PR solves this problem by separating data and backend configuration.
To do this,
* `testing.backend.inject_backend_tests` has been introduced. A test writer can apply this decorator to a test case, so that specified test fixtures (e.g. `test_backward`) will be duplicated to as many as backend configuration combinations (specified by the test writer). Each …

 Refactor unit tests for various backend configuration

---

chainer/testing/backend.py

Fixed cuda import path to go via the new `chainer.backends` submodule.

Fix cuda import path

---

chainer/functions/connection/n_step_rnn.py

I discovered this when I didn't use all the states of the rnn
encoding further down the pipeline. My code ran fine on cpu but I
got the following error when using gpu.
```
"python3.5/site-packages/chainer/functions/connection/n_step_rnn.py",
line 449, in backward
dys = cuda.cupy.concatenate(dy_list, axis=0)
cupy.core.core.concatenate_method (cupy/core/core.cpp:64040)
ValueError: All arrays must have same shape except the axis to
concatenate
```
I think x_list[i] has correct 0th dimension (batch size) but
incorrect 1st dimension (num units). This change got my code
working - and I checked it both for a unidirectional and a
bidirectional rnn.
- Read [our contribution …

Fix backprop dim for unused lstm states on gpu

---

chainer/function_node.py
chainer/functions/connection/convolution_2d.py
chainer/functions/connection/deconvolution_2d.py

This is just a refactoring, in preparation for integrating iDeep.
* Moved `ndarray` type check to `function_node._check_data_type_forward`.
* Refactored duplicate code as a method (`_calc_out_size`)
* Isolated cuDNN forward calculation as methods.

Refactor (de)convolution_2d

---

chainer/function_node.py
tests/chainer_tests/links_tests/connection_tests/test_embed_id.py

Checks input/output array types of forward operations.
This PR may be unsafe to backport, because existing functions may be mixing cupy and numpy arrays.
Also, some builtin functions will fail to pass this check. They need to be fixed before this PR.

Check for mixed use of ndarrays

---

tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py
tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py

I replaced to_gpu in RNN tests.
related to #4045

Simplify to_gpu in RNN tests

---

chainer/reporter.py

This PR fixes the error below and removes `:` in `reporter.add_observer('my_observer:', observer)`.
I executed the example in the readthedocs, and found that `/` is inserted between the names of the observation and the key of the reported dict.
```
>>> from chainer import Reporter, report, report_scope
>>>
>>> reporter = Reporter()
>>> observer = object()  # it can be an arbitrary (reference) object
>>> reporter.add_observer('my_observer:', observer)
>>> observation = {}
>>> with reporter.scope(observation):
...     reporter.report({'x': 1}, observer)
...
>>> observation
{'my_observer:/x': 1}
```
with Chainer v3, in Python 3.

Fix the example in the document of Reporter

---

chainer/computational_graph.py
chainer/functions/loss/negative_sampling.py
chainer/functions/loss/softmax_cross_entropy.py
chainer/functions/math/matmul.py
chainer/functions/noise/dropout.py
chainer/iterators/multiprocess_iterator.py
chainer/links/loss/black_out.py
chainer/links/normalization/batch_normalization.py
chainer/links/normalization/batch_renormalization.py
chainer/optimizer.py
chainer/training/extensions/evaluator.py
tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py

I replaced `hasattr` with normal attribute lookup.
IMO `hasattr` should be avoided, because
* It's slower. In my test, it's more than 3x times slower than `self.a is None`.
* Less readable. You cannot tell what attributes a class can have without reading the actual code.
* Look weird, especially to those from other programming languages.

Avoid unnecessary `hasattr`

---

chainer/variable.py
tests/chainer_tests/test_variable.py

Fixes an error that is raised when calling `debug_print()` on a `Variable` object without `data` (https://github.com/chainer/chainer/issues/3994).

Fix debug_print() with empty Variable

---

chainer/functions/connection/convolution_2d.py
tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py

It seems that cuDNN v6 does not support backward computation of dilated convolution when deterministic algorithm (`CUDNN_CONVOLUTION_BWD_DATA_ALGO_1`) is selected.

Fix test failure with cuDNN v6

---

chainer/functions/connection/convolution_2d.py
chainer/functions/connection/deconvolution_2d.py

Without cuDNN, `_cudnn_version` is undefined.
Related to #3494.

fix F.convolution_2d and F.deconvolution_2d to work without cuDNN

---

chainer/function_node.py
chainer/functions/__init__.py
chainer/functions/connection/n_step_lstm.py
chainer/functions/evaluation/accuracy.py
chainer/functions/loss/black_out.py
chainer/functions/loss/hinge.py
chainer/functions/loss/triplet.py
chainer/functions/normalization/l2_normalization.py
chainer/functions/util/forget.py
chainer/training/extensions/evaluator.py
chainer/training/extensions/micro_average.py

`tests/chainer_tests/test_init_docstring.py` fails due to these backslashes in Python 3.

Fix incorrect use of single backslashes in docstrings

---

chainer/links/model/vision/googlenet.py
chainer/links/model/vision/resnet.py
chainer/links/model/vision/vgg.py

I suffered from RGB-BGR order difference between `__call__` and `predict` in `chainer.links.model.vison.XXX` since it's not well documented (actually it is not impossible to understand from `prepare` and `__call__` document but for beginners it's quite difficult).
Ref. https://github.com/chainer/chainer/issues/3756#issuecomment-341027872
This PR updates document just to clarify that `predict` requires RGB order and `__call__` supposes the input is converted to BGR by `prepare`.
I also wanted to put a link to `prepare` document ([here](https://docs.chainer.org/en/stable/reference/generated/chainer.links.model.vision.googlenet.prepare.html#chainer.links.model.vision.googlenet.prepare)) in `__call__` document, but I'm sorry I don't know how.

Clarify color order of arguments in ImageNets documentation

---

chainer/datasets/svhn.py

Using PyPy, the following code (chainer/datasets/svhn.py", line 5) raises an AttributeError exception, which is not handled properly.
try:
from scipy import io
_scipy_available = True
except ImportError:
_scipy_available = False
It seems reasonable that any exception raised when importing scipy.io would make SciPy be considered unavailable.
The following is the full traceback:
File "/usr/local/bin/agglplanner2", line 67, in
from dnnpredictor import *
File "/usr/local/share/agm/dnnpredictor.py", line 12, in
from chainer import Variable
File "/usr/local/lib/pypy2.7/dist-packages/chainer-4.0.0a1-py2.7.egg/chainer/init.py", line 11, in
from chainer import datasets # NOQA
File "/usr/local/lib/pypy2.7/dist-packages/chainer-4.0.0a1-py2.7.egg/chainer/datasets/ini …

Minor change to enable using Chainer with PyPy

---

chainer/links/model/vision/googlenet.py
chainer/links/model/vision/resnet.py
chainer/links/model/vision/vgg.py

[backport]Clarify color order of arguments in ImageNets documentation

---

docker/python2/Dockerfile
docker/python3/Dockerfile

From this PR: https://github.com/chainer/chainer/pull/3898. I have found a proper method to install python wheel as it is a dependency according to this error:
```
----------------------------------------
Failed building wheel for cupy
Running setup.py clean for cupy
Running setup.py bdist_wheel for chainer: started
Running setup.py bdist_wheel for chainer: finished with status 'error'
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-y_acju7c/chainer/setup.py';exec(co
mpile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpc8g4swgupip-wheel- --
python-tag cp35:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c …
```

Fix Dockerfile to be able to train mnist with GPU

---

chainer/optimizer.py

Fix AttributeError caused by `_use_fp32_update ` not being set when initializing an optimizer with a model passed as a constructor argument.

Fix optimizer AttributeError with new optimizer setup

---

tests/chainer_tests/training_tests/triggers_tests/test_interval_trigger.py
tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py

Fix tests cannot be run independently, e.g.,
```
python -m pytest tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
```

fix trigger test imports

---

examples/image_captioning/README.md
examples/image_captioning/datasets.py
examples/image_captioning/download.py
examples/image_captioning/model.py
examples/image_captioning/predict.py
examples/image_captioning/train.py

Adds an image captioning example with MSCOCO downloader/wrapper.
This implementation includes two variations of the model, one using traditional `LSTM` layers and another one using `NStepLSTM` layers.
Please feel free to comment.
~- [ ] Add beam search.~ (See in #4089 )

Add image captioning example using MSCOCO

---

docs/source/tutorial/function.rst
docs/source/tutorial/trainer.rst
docs/source/upgrade.rst

Backport of #4126
The original PR had changes in `ptb.rst` and `word2vec.rst`. But as they are newly-added in v4, I remove changes applied to these files form this PR.

[backport] fix typos in docs

---

chainer/optimizer.py
chainer/optimizers/ada_delta.py
chainer/optimizers/ada_grad.py
chainer/optimizers/adam.py
chainer/optimizers/momentum_sgd.py
chainer/optimizers/nesterov_ag.py
chainer/optimizers/rmsprop.py
chainer/optimizers/rmsprop_graves.py
chainer/optimizers/sgd.py
chainer/optimizers/smorms3.py

#3488 allowed
```
optimizer = chainer.optimizers.SGD(link=model)
```
but it costs writing a new optimizer.
Instead I propose method-chain
```
optimizer = chainer.optimizers.SGD().setup(model)
```
This PR removes the feature (added to v4.0.0b2).
Nonetheless this PR is "more compatible to v3" solution to merge the two lines on an optimizer than #3488 is.

Use method chain at Optimizer.setup 

---

chainer/links/caffe/caffe_function.py
tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py

Fixes https://github.com/chainer/chainer/issues/3098
Wrapped the Chainer pooling functions so that the kernel sizes can be computed dynamically to cover the whole input. 
Caffe reference https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L921

Support Caffe global pooling functions

---

chainer/functions/math/identity.py

Remove unneeded empty retain (it is by default empty in `FunctionNode`s).

Remove empty retain

---

chainer/variable.py
tests/chainer_tests/test_link.py

Fix #4068.
This PR fixes inconsistency when a link that has uninitialized variables is `link.copy()`ed, `link.to_gpu()`ed then initialized.

Fix inconsistency on transferring copied link with uninitialized variables to GPU.

---

chainer/variable.py

Variable.backward() has been supporting double backprop since v3.0.0rc1.

Fix the docstring of Variable.backward()

---

chainer/variable.py
tests/chainer_tests/test_link.py

[backport] Fix inconsistency on transferring copied link with uninitialized variables to GPU.

---

chainer/gradient_check.py
tests/chainer_tests/test_gradient_check.py

The current code of  `gradient_check` uses a hack that appends `identity` function in order to compute `backward` for all the variables. But doing `y[0].backward()` is not perfect since its behavior depends on the size of y[0].
It seems it is allowed to `backward` a `None` gradient as a `zeros` gradient (of unused output Variable), e.g. in `LSTM` function. `gradient_check` overwrites such `None` by `ones` if `y[0].size == 1`.
Resolves #4010

Fix a corner-case bug in gradient_check

---

chainer/optimizer.py
chainer/serializers/npz.py

This PR fixes the sphinx build error introduced in #3931.
```
/root/chainer/chainer/optimizer.py:docstring of chainer.Optimizer:: WARNING: more than one target found for cross-reference 'target': chainer.optimizers.AdaGrad.target, chainer.optimizers.RMSpropGraves.target, chainer.optimizers.SGD.target, chainer.optimizers.RMSprop.target, chainer.optimizers.NesterovAG.target, ch
ainer.optimizers.MomentumSGD.target, chainer.Optimizer.target, chainer.optimizers.SMORMS3.target, chainer.GradientMethod.target, chainer.optimizers.Adam.target, chainer.optimizers.AdaDelta.target
/root/chainer/chainer/optimizer.py:docstring of chainer.Optimizer:: WARNING: more than one target found for cross-reference 't': chainer.optimizers.AdaDelta.t, chainer.Optimizer.t, chainer.optimizers.SGD.t, …
```

prefix class name to attributes in pydoc

---

chainer/links/model/vision/googlenet.py

This PR fixes GoogLeNet to use `init_scope` instead of old `__init__` interface to avoid DeprecationWarning.

fix GoogLeNet to define network using init_scope

---

chainer/dataset/convert.py
docs/source/tutorial/convnet.rst
docs/source/tutorial/gpu.rst
docs/source/tutorial/ptb.rst
docs/source/tutorial/recurrentnet.rst
docs/source/tutorial/trainer.rst
examples/mnist/train_mnist_data_parallel.py
examples/pos/postagging.py
examples/seq2seq/seq2seq.py
examples/text_classification/nets.py
examples/text_classification/train_text_classifier.py
examples/vae/train_vae.py

In general, fix `init_scope()` and `StandardUpdater`, `ParallelUpdater` namespace problem in the documentation and examples, in addition to some wrong links in the document.

Update documentation and examples

---

tests/chainer_tests/functions_tests/array_tests/test_split_axis.py

Refactored `test_split_axis` to use `testing.backend.inject_backend_tests`.

Refactor test_split_axis

---

tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py

Refactored `test_batch_normalization` to use `testing.backend.inject_backend_tests`.

Refactor test_batch_normalization

---

chainer/training/extensions/__init__.py
chainer/training/extensions/variable_statistics_plot.py
tests/chainer_tests/training_tests/extensions_tests/test_variable_statistics_plot.py

Extension that plots mean, std, min, max and percentiles for given `Variables` (`data`, `grad`) and saves them as an image.
[Example output image](https://goo.gl/9jfH7U)
Average over all `Variables` in a model.
```python
model = MLP()
write_trigger = (1, 'epoch')
extension = chainer.training.extensions.VariableStatisticsPlot(
model, 
max_sample_size=1000, 
report_data=True, 
report_grad=True, 
trigger=write_trigger, 
file_name='stats.png')
collect_data_trigger = (1, 'iteration')
trainer.extend(extension,  trigger=collect_data_trigger)
```
Monitor a specific parameter.
```python
model = MLP()
trainer.extend(chainer.training.extensions.VariableStatisticsPlot(model.fc1.W))
```
Use cases include quick debugging of you model, visually verifying parameter initializations, checking for …

Variable statistics plot report

---

chainer/functions/connection/convolution_nd.py
chainer/functions/connection/deconvolution_nd.py
tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py

Related to #2745. This challenging PR aims to update ConvolutionND/DeconvolutionND functions to support double back propagations.
(I finally want to integrate `Convolution2D` and `ConvolutionND`, and derive `Convolution2D` as a special case of `ConvolutionND`, however, in the first stage this PR aims to rewrite `ConvolutionND` with reference to `Convolution2D`, and support double back propagations.)

New style ConvolutionND/DeconvolutionND

---

examples/README.md

* Added links to recently added examples
* Added link to Awesome Chainer
* Removed :zzz: from [pfnet-research example: Chainer-GAN-lib](https://github.com/pfnet-research/chainer-gan-lib) (it says it supports Chainer v4.0.0)
When backporting, please exclude the following examples (they are not backported):
* [Text Classification](https://github.com/chainer/chainer/tree/master/examples/text_classification)
* [POS-tagging](https://github.com/chainer/chainer/tree/master/examples/pos)
* [Variational AutoEncoder](https://github.com/chainer/chainer/tree/master/examples/vae)

update example list

---

chainer/functions/loss/ctc.py

In CTC backward process, it accumulates probabilities. That is not in the log world. So we can just use `sum` instead of `logsumexp`. And, replaced the for loop with `atomicAdd` to accumulate the same label probabilities.
related to #4248

Optimize CTC backward

---

chainer/functions/loss/ctc.py

I enhanced CTC loss function. Main difference is that in this fix I don't use recurrence connection matrix `frr` nor `brr` and instead access probability vector directory.
Please check two commits one by one. The first commit changed implementation strategy as I wrote. GPU performance degrades with the first one because it makes a lot of CUDA kernels. In the second commit, I reduced the number of kernels. Finally I only uses one elementwise kernel.
related to #4248

Improve ctc loss

---

chainer/functions/math/matmul.py

This PR is to reduce unnecessary computation in `MatMul`.
When you specify one of inputs to matmul as `required_grad=False` like below, there is no need to compute the gradient of that input, but it is computed with current master. This PR reduces that unnecessary computation.
a = Variable(a)
b = Variable(b, required_grad=False)
c = F.matmul(a, b)
I also noticed that `MatMulGrad` is not necessary if you add small fix to `MatMul`. Thus there is no `MatMulGrad` in this branch.
BTW, I found this issue when I was looking at Chainer chemistry.

Skip unnecessary backward computation in matmul

---

docs/source/reference/functions.rst

Links are not in `chainer.functions`.  (From v2?)

Fix document about links in chainer.functions

---

chainer/functions/normalization/l2_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py

The backward computation of `NormalizeL2` was wrong (for non-negligible `eps`).

Fix backward of NormalizeL2

---

chainer/functions/connection/bilinear.py
chainer/functions/math/batch_l2_norm_squared.py
chainer/utils/array.py
tests/chainer_tests/links_tests/connection_tests/test_bilinear.py

Raise deprecation warning on usage of `chainer.utils.array` since the functions included in the utility are all very primitive (and could in the future be removed).
May require discussion. Please refer to https://github.com/chainer/chainer/pull/3932.

Deprecate array util

---

tests/chainer_tests/functions_tests/noise_tests/test_dropout.py

Refactored `test_dropout` to use `testing.backend.inject_backend_tests`.

Refactor test_dropout

---

chainer/functions/activation/softmax.py

This PR aims to improve performance of softmax in non-convolution cases.
cuDNN has two modes for softmax, CUDNN_SOFTMAX_MODE_CHANNEL and CUDNN_SOFTMAX_MODE_INSTANCE (please see [here](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnSoftmaxMode_t)). For now, CUDNN_SOFTMAX_MODE_CHANNEL is always used in Chainer regardless of shape of input tensor and target axis. It is basically good for CNN, but it could be slow depending of shape of tensor. Actually, it is very slow when (N,C,H,W) = (many, some, 1, 1).
This PR adds feature to select cudnn mode based on shape of input tensor. With this PR,  CUDNN_SOFTMAX_MODE_INSTANCE is selected only when (H,W) = (1,1) and CUDNN_SOFTMAX_MODE_CHANNEL is used as default.

Add cudnn mode selection in softmax

---

docs/source/reference/core/dataset.rst

Now we have two batch conversion functions. I fixed the documentation.

Fix description of built-in batch converters

---

chainer/functions/normalization/batch_renormalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py

This is backport of #4191 except fixing of `tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py` .

[backport] Fix backward of BatchRenormalizationFunction and add tests 

---

examples/seq2seq/seq2seq.py

Seq2seq example does not use the argument of "--out".
I fixed it to work the argument correctly.

Fix unused argument(--out) of seq2seq example

---

docs/source/tutorial/basic.rst

Fix issue introduced in #4290.
`optimizer.setup(model)` now returns itself, so it will print sth like `<chainer.optimizers.sgd.SGD object at 0x7f45831ea940>` when interactive.

fix to pass doctest around optimizer.setup

---

chainer/function_hooks/cupy_memory_profile.py
tests/chainer_tests/function_hooks_tests/test_cupy_memory_profile.py

`CupyMemoryProfileHook` keeps `FunctionNode` references in the call history, thus the memory held by these functions are never released within the hook scope.
That can unnecessarily cause OOM error if multiple loops are measured at once.
```
hook = function_hooks.CupyMemoryProfileHook()
with hook:
train_loop1()
train_loop2()
train_loop3()  # memory consumption is accumulated
hook.print_report()
```
(Note: the numbers in the profiling result is not affected by accumulation)
This fix is to keep function names in the call history instead of function objects.
This is backward-incompatible, because the content of call history (which is documented) is altered.

Avoid keeping reference to function nodes in CupyMemoryProfileHook

---

chainer/function_hooks/timer.py
tests/chainer_tests/function_hooks_tests/test_timer.py

It's better to apply the same fix made in #4300 (CupyMemoryProfileHook).

Avoid keeping reference to function nodes in TimerHook

---

docs/source/conf.py
docs/source/contribution.rst
docs/source/tutorial/basic.rst
docs/source/tutorial/function.rst
docs/source/tutorial/gpu.rst
docs/source/tutorial/ptb.rst
docs/source/tutorial/recurrentnet.rst
docs/source/tutorial/word2vec.rst

Some external URLs in the document directly refer to the master branch, and they should be pointed to the corresponding tag.
I utilize sphinx.ext.extlinks to achieve this goal. However, I wonder if it is appropriate to use names 'blob' and 'tree', and actually github automatically redirects to correct URL whichever original URL is blob or tree.

Use version in external URL

---

tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py

I simplified initialization of random vectors in the NStepRNN's test.
merge #4047 first
related to #4045

Fix initialization of random vectors in the test for RNNs

---

examples/imagenet/train_imagenet.py
examples/imagenet/train_imagenet_data_parallel.py

It's a pity that ResNeXt has been implemented but not used in the ImageNet example.

Use ResNeXt in the ImageNet example

---

chainer/functions/connection/bilinear.py
chainer/functions/connection/convolution_nd.py
chainer/functions/connection/deconvolution_nd.py
chainer/functions/connection/embed_id.py

These codes are invalid as iDeep is now introduced.
Note that type consistency is now checked in FunctionNode level (#4029), so we can safely remove these checks.
Type check code in `F.linear` will be removed in #4278.

remove input type consistency checks

---

chainer/function_node.py
docs/source/upgrade.rst

Now that `ideep.mdarray` is introduced, current error message is not preciese.

Fix error messages for incompatible arrays

---

chainer/functions/connection/n_step_gru.py
chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py

I refactored BaseNStepRNN to accept concatenated arrays. With this fix, BaseNStepRNN accepts concatenated arrays. And instead, it requires length array. Arrays are concatenated with `chainer.functions.concat` in `n_step_rnn` function. This fix doesn't change the interface. After merging this fix, I'll add an argument to select if `concat` is called or not.

Accept concat array in NStepRNNs

---

chainer/functions/array/split_axis.py
tests/chainer_tests/functions_tests/array_tests/test_split_axis.py

Fix bug when we use Python3 with iDeep.

Cast to int type in split_axis

---

chainer/functions/activation/elu.py

Resolves #4264 by computing `ELU.backward` similarly to `Exp.backward`.
```python
In [1]: import chainer
In [2]: import numpy as np
In [3]: x = chainer.Variable(np.array([[0, 0]],dtype=np.float32))
In [4]: y = chainer.functions.elu(x)
In [5]: y.grad = (np.array([[0, 1e-30]],dtype=np.float32))
In [6]: y.backward(enable_double_backprop=True)
In [7]: x.grad_var.grad = np.array([[1, 1]],dtype=np.float32)
In [8]: x.grad_var.backward()
In [9]: y.grad_var
Out[9]: variable([[0.e+00, 1.e-30]])
In [10]: y.grad_var.grad
Out[10]: array([[1., 1.]], dtype=float32)
```

Improve ELU.backward

---

chainer/functions/activation/sigmoid.py
chainer/functions/activation/softplus.py
chainer/functions/activation/tanh.py
chainer/functions/array/select_item.py
chainer/functions/math/basic_math.py
chainer/functions/math/batch_l2_norm_squared.py
chainer/functions/math/linear_interpolate.py
chainer/functions/math/matmul.py
chainer/functions/math/trigonometric.py

According to the source code and [the slides about double backprop.](https://www.slideshare.net/KentaOono/comparison-of-deep-learning-frameworks-from-viewpoint-of-double-backpropagation), it seems a common practice to use `gx` and `ggx` to represent the gradients wrt `x` and `gx`.
However, some variables have contradictory names to this convention and new users may get confused about it. I hope they will be fixed by this PR.

Fix some inconsistency in gradient variable names.

---

README.md

Fixed the casing of the header in the README. 
Unless it has been discussed before, I think this looks better. For reference, see http://blog.apastyle.org/apastyle/2011/06/capitalization-after-colons.html. 
Additionally, if we want to emphasize the fact that this indeed is a _deep learning framework_, I suggest we instead change the header to `Chainer: A Deep Learning Framework`.

Fix casing of header in README

---

tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py

Reverts chainer/chainer#4370
This workaround is no longer needed, as https://github.com/cupy/cupy/pull/954 is reverted (in https://github.com/cupy/cupy/pull/964).

Revert "Skip multiprocess_parallel_updater test for timeout"

---

docs/Makefile

Sometimes I want to confirm all warnings raised by Sphinx, but currently we can only confirm one warning at a time, because `-W` is specified.
This PR allows `SPHINXOPTS` to be overridden by environment variable, so we can:
```
SPHINXOPTS= make html
```
to disable `-W`.

fix sphinx build option assignment in Makefile

---

docs/source/comparison.rst

tensorboardX can also be used with chainer without much modification.
And the following is an example of chainer extension that uses tensorboard to log data.
https://github.com/lanpa/chainer/commit/33f0c6c1d414fd4e866179d77455ee8739e1f6d2

Update comparison.rst (Web interface)

---

chainer/link.py

Fixed a bug that occur when using iDeep in chainer/link.py

Fixed a bug that occur when using iDeep in chainer/link.py

---

chainer/backends/cuda.py
tests/chainer_tests/test_cuda.py

I found a bug in `cuda.to_gpu` and `cuda.copy` that would not change the device when the device identifier is a numpy dtype. Users might use numpy to generate the device ids, and would therefore be subject to this subtle bug.
Illustrating the problem for `to_gpu`, but the same thing happens for `copy`.
```
from chainer import cuda
gpus = [0, 1, 2, 3]
batch_size = 2
eval_gpus = np.repeat(gpus, batch_size)
xs = []
for gpu in eval_gpus:
y = np.ones(1)
x = cuda.to_gpu(y, device=gpu)
xs.append(x)
for x in xs:
print(x.device)
```
Without this PR:
```
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 0>
```
With this PR (expected):
```
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 1>
<CUDA Device 1> …
```

Fix numpy dtypes bug in cuda.to_gpu and cuda.copy

---

setup.py

This PR depends on https://github.com/cupy/cupy/pull/899.
Support CuPy wheels as a dependency.

support using cupy wheels as a dependency

---

chainer/functions/math/matmul.py

If fewer indices are needed in `BatchMatMulGrad.backward`, it may cause `UnboundLocalError: local variable 'ggab' referenced before assignment`.  The bug was introduced in #3768.
Please review this after #4331 is merged.

Fix BatchMatMulGrad.backward

---

chainer/backends/intel64.py

Previous:
```
RuntimeError: iDeep is not available.
Reason: ImportError: libglog.so.0: cannot open shared object file: No such file or directory
```
This PR:
```
RuntimeError: iDeep is not available.
Reason: ImportError: libglog.so.0: cannot open shared object file: No such file or directory
Ensure ideep requirements are satisfied: https://github.com/intel/ideep
```

Improve ideep import error message fror missing shared objects

---

chainer/functions/loss/ctc.py

Calculation of forward and backward probabilities are very similar. I fixed matrix order and make them the same code. And after that, I combine all kernels and reduced the number of kernels. When batch size is small this code is 3x faster.
This fix also includes refactoring. I can split the PR.

Use the same code for calculating forward and backward probabilities in CTC

---

chainer/functions/activation/tree_lstm.py
chainer/links/connection/tree_lstm.py
tests/chainer_tests/links_tests/connection_tests/test_tree_lstm.py

Fix #3680 
ChildSumTreeLSTM should have been able to accept `link(x)` and `link(c, h, x)`. But, they were not allowed, while only `link(c1, c2, ..., h1, h2, ..., x)` (with more than 1 children) was allowed.
This PR fixed it.

Child sum treelstm with less than 2 child

---

chainer/function_node.py
tests/chainer_tests/test_variable.py

Fix the issue that `chainer.grad` ignores `Variable._old_style_grad_generator`.
Close #4114.

Detect backward of old-style functions in chainer.grad

---

chainer/functions/activation/clipped_relu.py
tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py

I added cuDNN support for `clipped_relu`. This is useful for speeding up e.g. ReLU6, which has shown to be beneficial when preparing a model trained in FP32 mode to be run in FP16 precision.
It's recently being used in MobileNetV2.
Note that this PR depends on the following CuPy PR: https://github.com/cupy/cupy/pull/938
References: 
https://arxiv.org/abs/1801.04381
https://www.reddit.com/r/MachineLearning/comments/3s65x8/tensorflow_relu6_minmaxfeatures_0_6/
http://www.cs.utoronto.ca/~kriz/conv-cifar10-aug2010.pdf

Add cuDNN support for clipped_relu

---

chainer/functions/pooling/average_pooling_nd.py
chainer/functions/pooling/max_pooling_nd.py
chainer/functions/pooling/max_pooling_nd_kernel.py
chainer/functions/pooling/pooling_nd.py
chainer/functions/pooling/unpooling_nd.py
tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_nd.py

Related to #2745. This PR aims to update `AveragePoolingND`, `MaxPoolingND`, and `UnpoolingND` to support double back propagations.
After merging this PR, I would like to integrate `Pooling2D` and `PoolingND` (it includes the support of `cover_all=True` in AveragePoolingND).
(This is a re-submission of #4131)

New style AveragePoolingND/MaxPoolingND/UnpoolingND

---

chainer/variable.py
tests/chainer_tests/test_function.py
tests/chainer_tests/test_function_node.py
tests/chainer_tests/test_variable.py

The current definition in `Variable.backward` of a "scalar" variable is an array containing 1 element.  This may cause unexpected behavior that only occurs when `batch_size=1`.  The PR proposes to fix the definition to being a 0-dimensional array.

[RFC] Require "scalar" variables to be 0-dim

---

setup.py

As CUDA 9.1 is now tested and confirmed to work, let's start distributing CUDA 9.1 wheels.
~~Depends on https://github.com/cupy/cupy-release-tools/pull/7~~ (merged)

add cupy-cuda91 wheel dependency

---

chainer/variable.py
tests/chainer_tests/test_variable.py

Variable tests failed due to warnings caused by Variables with scalar arrays.

Fix Variable tests

---

codecov.yml

This PR introduces Codecov.io to measure test coverage for diff introduced in each Pull-Request (rather than overall coverage).
The coverage will be uploaded via Jenkins (chainer-test).
Codecov.io covers most of features in Coveralls, but it does not visualize branch coverage.
So I continue to keep Coveralls configuration as is.
The meaning of the configuration is:
* Disable commenting on PRs. Just leave commit status on PR (like Travis).
* Do not measure overall coverage (it is currently measured by Coveralls).
* Measure coverage for diffs introduced in PRs.
For now, target (threshold to decide `✔︎` or `X`) is set to `0%` to avoid unnecessary confusion of contributors.
We can reconsider this rate afterwards, if needed.

add Codecov.io configuration

---

chainer/functions/pooling/unpooling_nd.py

Fixed typos in `unpooling_nd.py`.

Fix typo in unpooling_nd

---

chainer/functions/array/stack.py
chainer/functions/math/erf.py
chainer/functions/math/erfc.py
docs/source/conf.py
docs/source/imports.rst
tests/chainer_tests/functions_tests/activation_tests/test_swish.py
tests/chainer_tests/links_tests/activation_tests/test_swish.py

Some recent added codes still use deprecated `chainer.cuda`, and accordingly, I modify them to conform to latest recommendation `chainer.backends.cuda`.

Prefer chainer.backends.cuda in recent added codes

---

tests/chainer_tests/test_function_node.py

Add tests for `FunctionNode.apply()` input, output backend checks (exceptions are raised when ndarray backends are mixed https://github.com/chainer/chainer/pull/4029).
Note that this PR should not be backported since #4029 isn't.

Add test for inconsistent backend input outputs

---

chainer/dataset/convert.py
chainer/functions/activation/clipped_relu.py
chainer/functions/activation/softplus.py
chainer/functions/array/flip.py
chainer/functions/array/im2col.py
chainer/functions/connection/convolution_nd.py
chainer/functions/math/tensordot.py
chainer/functions/normalization/batch_renormalization.py
chainer/functions/pooling/average_pooling_nd.py
chainer/functions/pooling/max_pooling_nd.py
chainer/links/connection/tree_lstm.py
chainer/optimizers/adam.py
chainer/serializers/npz.py
chainer/testing/unary_math_function_test.py
chainer/training/extensions/exponential_shift.py
chainer/training/extensions/linear_shift.py
chainer/training/extensions/variable_statistics_plot.py
chainer/training/triggers/early_stopping_trigger.py
chainer/training/updaters/parallel_updater.py
chainer/utils/conv_nd.py
chainer/utils/conv_nd_kernel.py
chainer/utils/experimental.py

According to contribution guide, import statements must be organized into three parts: standard libraries, third-party libraries, and internal imports. Consequently, I make corresponding adjustments.

Group imports in the order mentioned in the contribution guide

---

tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py

I added a test case which checks RNN behavior when some gradients are None.
This fix includes the test case that checks #3042 
merge #4048 first
related to #4045, #3042

Test of RNN in the case when some gradients are None

---

chainer/functions/pooling/spatial_pyramid_pooling_2d.py
tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py

Changed one of the argument types of `spatial_pyramid_pooling_2d` from a class type to `str`, since we preferably do not want to expose these classes (considered as function implementations).

Spatial pyramid pooling method specified by string instead of type

---

chainer/functions/__init__.py

Remove `chainer.functions.Swish` class alias, which should not be public.
(Added in #4262)

Remove Swish function class alias

---

chainer/functions/__init__.py
chainer/functions/array/repeat.py
docs/source/reference/functions.rst
tests/chainer_tests/functions_tests/array_tests/test_repeat.py

Implemented `F.repeat` (Variable version of `xp.repeat`).
This feature was requested in #3632.
It is also needed to migrate `prod` function to FunctionNode.

Add repeat function

---

docs/source/upgrade.rst

Add link to CuPy upgrade guide from Chaier upgrade guide.
~~Depends on https://github.com/cupy/cupy/pull/884.~~ (merged)

add link to CuPy upgrade guide

---

chainer/functions/math/sqrt.py
tests/chainer_tests/functions_tests/math_tests/test_sqrt.py

This PR optimizes `F.rsqrt` with `cupy.ext.rsqrt`.
Fixes #4092. Depends on https://github.com/cupy/cupy/pull/846.
Tests (backward / double_backward) are confirmed to pass 10,000 repeats.

optimize rsqrt function with CuPy

---

chainer/links/connection/n_step_gru.py
chainer/links/connection/n_step_lstm.py
chainer/links/connection/n_step_rnn.py
tests/chainer_tests/links_tests/connection_tests/test_n_step_gru.py
tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py
tests/chainer_tests/links_tests/connection_tests/test_n_step_rnn.py

ChainerMN needs this change in order to parallelize NStepRNN ([MultiNodeNStepRNN](https://github.com/chainer/chainermn/blob/master/chainermn/links/n_step_rnn.py)), where each cell is transferred to the neighbour process and thus it needs the number of cells in advance.
Unfortunately, no. Currently, we prepare [a table to obtain the number of cells](https://github.com/chainer/chainermn/pull/205/files#diff-1ed392351c4f47516bae8214681548eeR11), but this solution requires high maintenance cost to keep consistency between Chainer and ChainerMN, and hinders users to define original RNNs.
I tried whether we can avoid hard-coding, but I couldn't. If there is any nice solution, I would be happy to update.

Add n_cell property to NStepRNN family

---

chainer/functions/connection/n_step_gru.py
chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py

I extracted a function to concatenate weight matrixes `ws` and bias arrays `bs`. In the current implementation of `NStepRNNBase`, it makes a large weight array made by `getRNNParamsSize` in forward and splits it in backward. I extracted this feature into a function.
This fix is for providing an interface which skips concatenation to RNN link.
Note that this fix does not change interfaces for users.

Extract a function that concatenates weight and bias matrixes for cuDNN

---

chainer/datasets/sub_dataset.py
tests/chainer_tests/datasets_tests/test_sub_dataset.py

When we use `split_dataset` or `split_dataset_random`, it won't raise error when we set `float` value to the second argument of `split_at`.
It is likely happen when we want to split dataset according to the ratio of train/validation dataset.
e.g.,
```
train_ratio = 0.8
train, val = split_dataset_random(dataset, len(dataset) * ratio)
```
This PR is to check type of `split_at` to be `int`. After this PR, above code will raise `TypeError`.

Typecheck split_at

---

chainer/link.py
tests/chainer_tests/test_link.py

`Link._device_id` does not change when transferred from GPU to intel64.

reset Link._device_id to None in to_intel64

---

chainer/functions/loss/ctc.py
tests/chainer_tests/functions_tests/loss_tests/test_ctc.py

Current CTC loss function node class concatenates input variables in its implementation. We can extract this process as a stack function call.
This fix does not change the interface.

Extract stack function from CTC loss

---

MANIFEST.in

PyPA recommends to include license to sdist. https://github.com/pypa/sampleproject/blob/master/MANIFEST.in
Fixes #3966

add license to source distribution

---

chainer/backends/cuda.py

Now that we use `isinstance` to check if a variable is integer, `newint` is no longer needed.
Related: #1629, #4380

Remove future.types.newint

---

chainer/optimizers/momentum_sgd.py
chainer/variable.py
tests/chainer_tests/test_variable.py

Currently iDeep cannot be disabled when `MomentumSGD` is used.
This makes performance worse due to the copy overhead.

Fix to disable using iDeep in optimizers if to_intel64 is not called

---

chainer/function_node.py
docs/source/upgrade.rst
tests/chainer_tests/links_tests/connection_tests/test_embed_id.py
tests/chainer_tests/test_function_node.py

This is a proposal of improved error messages in `FunctionNode.apply()`. It also changes the type of exception.
The new message should be more understandable, for example, when a user forgot to use `utils.force_array()` in their own FunctionNode.
Original and new error messages look like these:
Original
```
ValueError: numpy and cupy arrays are mixed in the forward output (MyFunc).
<class 'cupy.core.core.ndarray'>, <class 'float'>
```
This PR
```
TypeError: forward outputs must be `ndarray`s of the same array module (numpy or cupy) (MyFunc).
Actual: <class 'cupy.core.core.ndarray'>, <class 'float'>
```

Improve error messages of array type check.

---

docs/source/reference/core/configuration.rst
docs/source/reference/environment.rst

[backport] document missing environment variables

---

chainer/function_hooks/debug_print.py

It is never used, becaue there's only one argument to `print`.

Deprecate `sep` argument of `PrintHook`

---

docs/source/reference/configuration.rst

fix typo of configuration parameter

---

chainer/functions/connection/n_step_gru.py
chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py
chainer/links/connection/n_step_lstm.py
chainer/links/connection/n_step_rnn.py

I fixed typo in NStepLSTM/GRU/RNN functions.
I also fix document in NStepLSTM/RNN links to contain return variable in __call__.
This PR is related to #3903.

Fix document in NStepLSTM/GRU/RNN

---

docs/source/reference/datasets.rst

I found that the toc of reference manual has incorrect section levels. This PR fixes it.
Before:
After:

Fix sectioning of "Datasets" reference

---

chainer/training/extensions/progress_bar.py

Fixes #3969
Recalculate epoch_length not to exceed 100%
before:
<pre>
[gen@localhost chainer]$ python3 examples/ptb/train_ptb.py --test
#vocab = 10000
total [#####################################################] 107.69%
this epoch [..................................................]  0.00%
6 iter, 42 epoch / 39 epochs
0.10037 iters/sec. Estimated time to finish: -1 day, 23:59:55.730007.
</pre>
after:
<pre>
[gen@localhost chainer]$ python3 examples/ptb/train_ptb.py --test
#vocab = 10000
total [##################################################] 100.00%
this epoch [..................................................]  0.00%
6 iter, 42 epoch / 39 epochs
0.099782 iters/sec. Estimated time to finish: 0:00:00.
</pre>

[RFC]Fix progress bar

---

tests/chainer_tests/functions_tests/array_tests/test_split_axis.py

Fix regression introduced in #4153.

avoid running TestSplitAxis tests on NumPy 1.10

---

chainer/functions/normalization/batch_normalization.py
tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py

Fix that `eps` is doubly added in test mode.  This PR changes the behavior of `F.batch_normalization` if it is called without cudnn.  (Therefore it also changes `L.BatchNormalization`.)

Remove eps from batch normalization statistics

---

.travis.yml

As `v4` branch is now stable version, we should change the branch name used in Travis.

Travis test against v4 branch

---

chainer/functions/util/forget.py
tests/chainer_tests/functions_tests/util_tests/test_forget.py

New style forget to support double backprop.
~It is quite inefficient at the moment during backprop since backward is called once to set the gradients of the variables invovled in the forgotten process, and then once again to get the backpropable gradients.~

New style forget

---

chainer/training/extensions/_snapshot.py
tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py

Currently Chainer saves every snapshots in `rw-------` permission, since it uses tempfile inside.
I think this behavior is a bit different from what users usually expect, because for example `chainer.serializers.save_npz` writes output in the OS default permission, which is typically `rw-r--r--`. File creation through Python (or OS/shell) will also follow that rule by default.
This PR creates temporary directory and write a target file into the tmp dir then move to target directory, instead of using tempfile. By this approach, snapshot will automatically have OS default permission,
* ~Tests~ Done
* ~Check compatibility with older Python, other OS, ...~ (CI will do?)

Save snapshot in the OS default permission

---

chainer/variable.py
tests/chainer_tests/test_variable.py

Fixes #4113.
One thing to discuss is that what to return when the variable is not initialized (`Variable(None)`).
Considering that the following facts, I decided to return NumPy in such case:
* `xp` for empty Link returns NumPy (i.e., `chainer.Link().xp == numpy`)
* Users can safely replace `chainer.cuda.get_array_module(v)` with `v.xp` without considering any side-effects

Implement Variable.xp

---

chainer/dataset/download.py
chainer/testing/serializer.py
chainer/training/extensions/_snapshot.py
chainer/training/extensions/log_report.py
chainer/utils/__init__.py

Fixed the same issue as #4461.
This kind of use of temporary directory is very common, so I made a context manager as `utils.tempdir()`, and applied to all such instances.

Fix temporary file permission issue in LogReport

---

chainer/dataset/iterator.py
chainer/iterators/multiprocess_iterator.py
chainer/iterators/multithread_iterator.py
examples/mnist/train_mnist_custom_loop.py

This is rather a request for comment than a change request - `__del__` is often harmful because the timing and order of  objects of `__del__` is unpredictable especially when those objects have cyclic references. This commit tries to remove `__del__` and to make iterators as context manager, available in [`with` statement](https://www.python.org/dev/peps/pep-0343/). Pros and cons in my thought follows on this:
Pros
- Good for users those don't use Trainer which does explicitly finalize iterators: #4145 and #4148 are not sufficient
- Removes unpredictable behavior around garbage collection of MultiprocessIterator and related object included in object reference graph, especially when it includes cyclic reference.
- Provides a good interface to collect external resources such as files or …

Provide a cleaner way to collect threads and processes in MultiprocessIterator

---

chainer/functions/connection/convolution_2d.py
chainer/functions/connection/deconvolution_2d.py
chainer/links/connection/convolution_2d.py
chainer/links/connection/deconvolution_2d.py

I took over #4059. This PR contains fixing about incompatible interface bug.

Fix group argument of {de,}convolution_2d to keyword-only argument. 

---

chainer/functions/connection/convolution_2d.py
chainer/functions/connection/deconvolution_2d.py
chainer/links/connection/convolution_2d.py
chainer/links/connection/deconvolution_2d.py

[backport] Fix group argument of {de,}convolution_2d to keyword-only argument. 

---

chainer/functions/connection/convolution_2d.py
chainer/functions/connection/deconvolution_2d.py
chainer/links/connection/convolution_2d.py

``dilated`` option were not completely documented.
I also unified the usage of `:class:` in each pydoc.

fix docs in {convolution,deconvolution}_2d

---

tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py

This test focuses on `reduce='unknown_reduce_type'`.
This PR is related to #3409.

Simplify TestSoftmaxCrossEntropyInvalidReduce in test_softmax_cross_entropy

---

chainer/training/triggers/early_stopping_trigger.py

Fixed a mistake in the docs of EarlyStoppingTrigger.
The type of max_trigger should be 'trigger object' but it was int.

fix document in EarlyStoppingTrigger

---

chainer/functions/math/bias.py
chainer/functions/math/scale.py

I found a user, who does not care about Caffe, was confused in using `L.Bias`. I'd like to tell in the document that the meaning of the argument `axis` there is different from numpy's.

Improve docstrings about axis of Caffe functions

---

setup.py

It seems pycodestyle==2.4.0 breaks something.  To keep hacking-related packages from being overwritten by pycodestyle, let's install hacking later.

Fix installation order of hacking

---

chainer/__init__.py
chainer/_runtime_info.py
chainer/backends/cuda.py
tests/chainer_tests/test_runtime_info.py

Implements interface to print runtime information. Took over #4298.
Requires https://github.com/cupy/cupy/pull/1067.
~~TODO: add test.~~ (done)

Implement interface to print runtime information

---

examples/seq2seq/seq2seq.py

[backport] fix seq2seq example ignoring limitation for target length

---

tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py

`use_cudnn` is never used in TestForwardConsistency.
I fixed that problem and simplify the test.
This PR  is related to #3409.

Fix and simplify TestForwardConsistency in softmax_cross_entropy 

---

chainer/sequential.py

A part of the documentation for `Sequential` seems to be broken. This PR fixes it.
And this PR also adds a description about the output of `print(model_C)` in the docstring of the constructor.

Fix docstrings of Sequential

---

chainer/link.py
tests/chainer_tests/test_link.py

There was a error when I tried to use Chain.repeat.
```
class ConvBNReLU(chainer.Chain):
super(ConvBNReLU, self).__init__()
self.conv = L.Convolution2D(
None, 64, 3, 1, 1, nobias=True)
self.bn = L.BatchNormalization(64)
def __call__(self, x):
return F.relu(self.bn(self.conv(x)))
net = ConvBNReLU().repeat(16, mode='init')
```
`TypeError: copy() takes 1 positional argument but 2 were given`
This is the example in the document of Link.repeat.
It fails because Chain.copy does not have "mode" parameter.
I fixed this bug and added some tests for Chain.copy and Chain.repeat.

Fix Chain.repeat

---

examples/cifar/train_cifar_custom_loop.py
examples/mnist/train_mnist_custom_loop.py
examples/ptb/train_ptb_custom_loop.py

The non-trainer examples (that is, the "custom training loop" examples) previously had a bug that the configuration remained in training mode during test/validation.

Fix custom loop examples to disable train mode during evaluation

---

docs/source/install.rst

[backport] rewrite installation guide to align with CuPy's installation guide

---

docs/source/comparison.rst

[backport] Add higher-order derivative support of Chainer to the comparison table

---

chainer/link.py
tests/chainer_tests/test_link.py

[backport] Fix `ChainList.copy` not supporting `mode` argument

---

chainer/testing/condition.py
chainer/testing/parameterized.py
tests/chainer_tests/testing_tests/test_condition.py
tests/chainer_tests/testing_tests/test_parameterized.py

Allow individual test cases to be skipped by `self.skipTest`.
Related to #4272.

Support skipping tests decorated by condition or parametize

---

chainer/serializers/npz.py
tests/chainer_tests/serializers_tests/test_npz.py

This option was supported by `NpzDeserializer`, but not by `load_npz`.

add ignore_names option to load_npz

---

docs/source/reference/caffe.rst

Currently both "Caffe Reference Model Support" and "Caffe Model Export Support" appearing in the references on the left.

fix heading level of Caffe docs

---

chainer/training/extensions/variable_statistics_plot.py

[backport] Fix import failure when matplotlib 1.x is installed

---

docs/source/install.rst

[backport] fix dead link to CuPy installation guide

---

setup.py

Our code is currently not compatible with `hacking` 1.1 released on May 9.
https://pypi.org/project/hacking/#history
This is a temporary fix to use old `hacking` for tests.

Fix hacking version

---

tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py

* Fix incorrect test attributes.
* `chainer.using_config('use_cudnn')` was not applied correctly.

Fix incorrect attributes and incorrect indentation in pooling tests

---

tests/chainer_tests/training_tests/updaters_tests/snippets/child_reporter.py
tests/chainer_tests/training_tests/updaters_tests/snippets/raw_array.py
tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py

Fix in #4717 changed MPU to raise an error when CUDA is used in the parent process.
This PR changes the MPU tests to run in separate process to avoid test failure when #4717  got merged.
(discussion regarding this change: https://github.com/chainer/chainer/pull/4368#issuecomment-366934262)

separate MultiprocessParallelUpdater tests

---

chainer/variable.py

I found several users, including me, search for the absolute function and find `chainer.functions.absolute`, while python's `abs` is available.  Add `abs` to the docstring of `Variable` even though it does not have a "-tion" form in English.

Add abs to document of Variable

---

chainer/functions/__init__.py
chainer/functions/array/moveaxis.py
docs/source/reference/functions.rst
tests/chainer_tests/functions_tests/array_tests/test_moveaxis.py

numpy 1.13 supports moveaxis and it is more useful than existing array manipulation such as rollaxis or transpose in some cases.

Moveaxis array operation proposal

---

chainer/functions/normalization/l2_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py

The test added in the first commit failed because the output dtype was `float64`.
After the refactoring, `F.normalize` supports Frobenius norm, which is equivalent to L2 norm of flattened vector.

Fix dtype bug in F.normalize

---

chainer/functions/normalization/batch_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py

Fixes #4662.
I fixed the false warning that appeared in #3996 when the input tensor has more than 2 dimensions. Note that this PR only fixes the standard case when `axis=None`. A more sophisticated check is needed to not give false warnings for the other axis options introduced in #4266.
The following illustrates the behavior due to this PR:
```
In [1]: import numpy as np
In [2]: import chainer
In [3]: bn = chainer.links.BatchNormalization(4)
In [4]: x = np.random.rand(1, 4).astype(np.float32)
In [5]: bn(x)
/home/tommi/.pyenv/versions/3.4.3/envs/chainer-dev3.4.3/lib/python3.4/site-packages/chainer-5.0.0a1-py3.4.egg/chainer/functions/normalization/batch_normalization.py:100: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization …
```

Warn only if the BN input tensor is 2-dimensional

---

chainer/backends/intel64.py
chainer/link.py
chainer/variable.py
tests/chainer_tests/test_variable.py

Currently `to_intel64` does not copy 1-dim arrays to iDeep.
As a result, bias parameter of the Linear layer is not copied to iDeep.
This causes memory copy overhead every time Linear layer is evaluated.
`mnist.mnist.MLPPredict.time_predict` benchmark results over this PR is as follows:
https://github.com/chainer/chainer-benchmark/blob/master/benchmarks/mnist/mnist.py#L92
Before applying this PR:
```
=========== ========== ============
--             units / batchsize   
----------- -----------------------
backend    1000 / 1   1000 / 100 
=========== ========== ============
cpu-ideep   971.01μs     1.40ms   
=========== ========== ============
```
After applying this PR:
```
=========== ========== ============
--             units / batchsize   
----------- -----------------------
backend …
```

Support copying 1-dim array to ideep

---

chainer/gradient_check.py

The direction of differentiation is also needed to interpret the error output.

Output the direction of differentiation in `gradient_check` error

---

setup.cfg

Theano 1.0.2 (released on May 23rd) calls ``distutils`` with deprecated arguments ("SO").
To workaround this issue, set warningfilter for this module.
https://github.com/Theano/Theano/blob/rel-1.0.2/theano/gof/cmodule.py#L274
https://github.com/python/cpython/blob/v3.6.5/Lib/distutils/sysconfig.py#L524-L532

Fix test warning filter for Theano 1.0.2 which triggers DeprecationWarning

---

tests/chainer_tests/functions_tests/normalization_tests/test_layer_normalization.py

Thanks to #4744, test with larger `eps` passes, which I mentioned at https://github.com/chainer/chainer/pull/4744#issuecomment-388045474.  I also confirmed the new test failed before merging the fix.

Test `F.layer_normalization` with large eps

---

chainer/gradient_check.py

[backport] Output the direction of differentiation in `gradient_check` error

---

chainer/links/model/vision/resnet.py

`downsample_fb` should not be passed to `Convolution2D`.
This fixes error introduced in #4479.

Fix ResNetLayers pass wrong kwargs to Convolution2D

---

setup.py

This PR is for stable (v4) branch.
Fix #4084.

v4: fix required version of CuPy

---

chainer/functions/connection/bilinear.py

Merge #4738 first.
Ternary numpy.einsum (without `optimize` option, which is not available in old numpy) is slow.  Do some optimization manually.

Replace ternary numpy.einsum

---

chainer/functions/array/rollaxis.py
tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py

Backward should nothing in such a case, but unexpectedly it rolled the last axis of the gradient. Note: I keep the change small for this bug fix, but ideally `F.rollaxis` should do nothing when `axis == start` (I mean, it should just return `chainer.as_variable(x)` without creating a new node).

Fix `F.rollaxis` backward when `axis=0` and `start=0`

---

chainer/functions/activation/lstm.py

To remove redundant array creation overhead, I used `input_num`. Merge https://github.com/cupy/cupy/pull/868 first.

Use input_num to remove array creation overhead

---

README.md

remove slack archive. slackarchive.io" has ended.

remove slack archive

---

chainer/__init__.py
chainer/datasets/cifar.py
chainer/datasets/fashion_mnist.py
chainer/datasets/image_dataset.py
chainer/datasets/mnist.py
chainer/datasets/svhn.py
chainer/initializers/__init__.py
docs/source/reference/configuration.rst
docs/source/reference/initializers.rst
tests/chainer_tests/initializer_tests/test_init.py

This PR aims at making it easy to use fp16. By setting an environment variable `CHAINER_DTYPE=float16`, you can let weight initializers and datasets generate fp16 arrays by default instead of fp32. It makes each model definition independent from which dtype to use.
I confirmed that MNIST example runs without modifying other parts (except the eps parameter of Adam, whose default value is too small for fp16). This change does not alter the behavior of existing code unless `CHAINER_DTYPE` is set.

Add chainer.config.dtype and use it in initializers and dataset loaders.

---

chainer/functions/normalization/l2_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py

As the use of `np.linalg.norm` has been eliminated in #4763, we no longer have to limit the number of axis in `F.normalize`.

Allow more than 2 axis in `F.normalize`

---

chainer/training/updaters/multiprocess_parallel_updater.py

This PR related to #4709 , but doesn't resolve it.

Raise an error when `devices` argument given to `MultiprocessParallelUpdater` is not dict and list

---

chainer/functions/array/rollaxis.py
tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py

[backport] Fix `F.rollaxis` backward when `axis=0` and `start=0`

---

examples/sentiment/train_sentiment.py

To make the sentiment example run with trainer because I want to compare ``train_sentiment.py`` and ``train_recursive_minibatch.py`` easily.
```
$ ./train_sentiment.py --test           
epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           1690.33                           0.15991                                  1.26023       
2           572.783     453.789               0.5            0.477564                  1.88768       
3           408.466                           0.689189                                 2.39682       
4           365.993     544.563               0.736486       0.496795                  3.01825       
5           342.518                           0.754505                                 3.567         
6 …
```

Refactor sentiment example

---

chainer/training/updaters/multiprocess_parallel_updater.py

[backport] Raise an error when `devices` argument given to `MultiprocessParallelUpdater` is not dict and list

---

examples/word2vec/train_word2vec.py

[backport] Remove redundant device allocation in word2vec example

---

setup.py

I want to circumvent [imp.load_source](https://docs.python.org/3/library/imp.html), the deprecated module and undocumented function in Python3, via using exec, whereas such change may reduce code readability.

Remove deprecated imp.load_source in setup.py

---

chainer/training/updaters/multiprocess_parallel_updater.py

[backport] Raise an error when CUDA has been initialized before MultiprocessParallelUpdater is initialized

---

setup.py

[backport] Remove deprecated `imp.load_source` in `setup.py`

---

chainer/training/updaters/multiprocess_parallel_updater.py
tests/chainer_tests/training_tests/updaters_tests/snippets/cuda_init.py
tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py

[backport] Improve error message and exception type during `MultiprocessParallelUpdater` initialization

---

chainer/functions/normalization/batch_normalization.py
chainer/functions/normalization/batch_renormalization.py

Current document is quite misleading. The link `chainer.links.BatchNormalization` does not access to `running_mean` and/or `running_var`; instead it relies on in-place updates. But another link `chainer.links.BatchRenormalization` indeed accesses to the attributes.

Correct docs of batch_{re}normalization about running averages

---

chainer/link.py
tests/chainer_tests/test_link.py

[backport] Raise an error if neither `__call__` nor `forward` is defined in a link

---

chainer/links/caffe/caffe_function.py
tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py

Motivation behind this PR: #4884 (Some functions like `F.linear` exports `Reshape` layer)

Support importing Caffe Reshape layer

---

chainer/optimizer_hooks/gradient_hard_clipping.py
chainer/optimizer_hooks/gradient_lars.py
chainer/optimizer_hooks/gradient_noise.py
chainer/optimizer_hooks/lasso.py
chainer/optimizer_hooks/weight_decay.py

[backport] Document `call_for_each_param` attribute in optimizer hooks

---

tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py

Avoid directly using `FunctionNode`.

Stop using freeze_running_statistics in TestFixedBatchRenormalization

---

tests/chainer_tests/test_function_node.py
tests/chainer_tests/test_variable.py

I found the tests on the backprop routines were not very strong.  This PR adds
- `chainer.grad` tests at intermediate variables,
- `FunctionNode.backward_accumulate` tests.

Add backprop tests

---

tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py

[backport] Stop using freeze_running_statistics in TestFixedBatchRenormalization

---

setup.py

pytest-timeout>=1.3.0 requires pytest>=3.6.

Tentatively restrict pytest-timeout version to <1.3.0

---

setup.py

[backport] Tentatively restrict pytest-timeout version to <1.3.0

---

chainer/functions/loss/sigmoid_cross_entropy.py
chainer/gradient_check.py
tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py

Fix `SigmoidCrossEntropy.backward`

---

chainer/gradient_check.py

[backport] Quote example codes properly in `gradient_check`

---

chainer/exporters/caffe.py

This fixes type mismatch error on Windows 64-bit w/ Python 2.7. Fixes #4927.
https://ci.appveyor.com/project/pfnet/chainer/build/10765/job/9m4yuq02f3426yv8
(will remove WIP after I confirmed AppVeyor test pass)

Fix ValueError in caffe exporter on Windows with Python 2.7

---

.travis.yml
setup.py

It's beneficial if docs build failure is reported in each PR.

Check docs build in Travis CI

---

chainer/exporters/caffe.py
chainer/function_node.py
chainer/functions/pooling/average_pooling_nd.py
chainer/functions/pooling/max_pooling_nd.py
chainer/functions/pooling/unpooling_nd.py
chainer/functions/theano/theano_function.py
chainer/links/connection/tree_lstm.py
chainer/links/normalization/layer_normalization.py
chainer/links/theano/theano_function.py

We have changed the policy so that we no longer use the warning to
indicate that a feature is experimental, and instead we should write
the status in the documentation.

Remove experimental warning

---

docs/source/tips.rst

Refs #4933.
iDeep4py v2 seems to have different API than v1, and it also has a separate package for AVX2 environment and AVX512 environment.

Suggest users to use iDeep4py v1 for now

---

chainer/exporters/caffe.py
chainer/links/caffe/caffe_function.py
tests/chainer_tests/exporters_tests/test_caffe.py
tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py

I fixed Caffe Deconvolution layer to export properly `num_output` param. Also, I added support for importing the layer. I tested these features with [waifu2x-chainer](https://github.com/tsurumeso/waifu2x-chainer) that contains Deconvolution layer and I confirmed that it works correctly.

Add support for importing and exporting Caffe Deconvolution layer

---

chainer/functions/connection/linear.py
chainer/functions/loss/sigmoid_cross_entropy.py
chainer/functions/loss/softmax_cross_entropy.py
chainer/utils/type_check.py

Currently type check error report is difficult to understand for beginners, because:
* the name `in_types` is not intuitive
* the index `X` of `in_types[X]` in the error message is a X-th argument of the FunctionNode, so sometimes it does not match with the X-th argument of `F.xxx`.
This PR is a proposal of assigning a user-friendly name for each types.
Example output:
```
Invalid operation is performed in: SigmoidCrossEntropy (Forward)
Expect: x.shape == t.shape
Actual: (100, 1) != (100,)
```

assign user-friendly name for better type check exception message

---

chainer/functions/loss/sigmoid_cross_entropy.py
tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py

This PR partially backports #4915.

[v4] Fix `SigmoidCrossEntropy.backward`

---

tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py

[backport] Delete redundant `no_grads` from test

---

chainer/links/model/vision/googlenet.py
chainer/links/model/vision/resnet.py
chainer/links/model/vision/vgg.py
tests/chainer_tests/links_tests/model_tests/test_vision.py

[backport] Add training mode checking to `extract` vision models (ResNet, VGG16, GoogLeNet).

---

chainer/functions/array/get_item.py
tests/chainer_tests/functions_tests/array_tests/test_get_item.py

Because of boolean masks and ellipsis, it's not so easy to check if the index tuple of slices is valid.

Remove wrong length check from `GetItem.check_type_forward`

---

chainer/functions/array/get_item.py
tests/chainer_tests/functions_tests/array_tests/test_get_item.py

[backport] Remove wrong-length check from `GetItem.check_type_forward`

---

chainer/gradient_check.py
tests/chainer_tests/test_gradient_check.py

- "their gradients are ignored" in the docstring was ambiguous.
- `check_backward` is supposed to compare backward with the numerical one. Do not check computational graph.

Fix no_grads option of check_backward

---

chainer/optimizer.py
chainer/training/updaters/multiprocess_parallel_updater.py
chainer/training/updaters/parallel_updater.py
chainer/training/updaters/standard_updater.py
tests/chainer_tests/test_optimizer.py
tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py

Fixed #3044. This PR lets the built-in updaters automatically call `Optimizer.new_epoch()` when `is_new_epoch` is true for the main iterator.
**This change is incompatible with v4.** To aid the incompatibility, I added `use_auto_new_epoch` flag to `Optimizer`, which is set by the updaters. When this flag is set, `new_epoch()` called outside the updater raises an error so that users can notice duplicated calls of `new_epoch()`. It means that existing code that uses any updater and `new_epoch` simultaneously will raise an error. This error can be fixed by 1) not calling `new_epoch` outside the updater, or 2) passing `auto_new_epoch=False` to the updater.

Make updaters call `new_epoch` automatically

---

chainer/functions/__init__.py
chainer/functions/array/broadcast.py
chainer/functions/math/basic_math.py
chainer/functions/math/matmul.py
chainer/functions/math/sum.py
chainer/utils/__init__.py
chainer/utils/array.py
chainer/utils/type_check.py
docs/source/reference/functions.rst
tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
tests/chainer_tests/functions_tests/math_tests/test_matmul.py
tests/chainer_tests/utils_tests/test_array.py

This PR makes Variable operators broadcast operands automatically. To make the implementation simple, I added `utils.sum_to` and `F.sum_to`, which computes the gradient of broadcast. Note that other functions that should support automatic broadcast (e.g. `where`) are not covered in this PR. A part of #3968.

Automatic broadcast in basic_math and matmul

---

chainer/link.py
tests/chainer_tests/test_link.py

This PR fix `ChainList` that is related to #4659 and #4660
- Support array assignment of different length arrays. 
- Set correct name.

Fix operations in ChainList

---

chainer/functions/__init__.py
chainer/functions/normalization/group_normalization.py
chainer/links/__init__.py
chainer/links/normalization/group_normalization.py
docs/source/reference/functions.rst
docs/source/reference/links.rst
tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py

It is an implementation of GroupNormalization.
https://arxiv.org/pdf/1803.08494.pdf 
GN can outperform in tasks such as time-series, GANs, and object detection.
This implementation uses batch normalization internally because we can exploit their optimized implementation with less effort.

Add Group Normalization

---

chainer/functions/array/broadcast.py
tests/chainer_tests/functions_tests/array_tests/test_broadcast.py

Use `expect_broadcast_shapes`, which was added in #4679.
This also fixes #4683.

Simplify `Broadcast.check_type_forward`

---

chainer/functions/normalization/batch_renormalization.py
chainer/links/normalization/batch_renormalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py

Replace the backward tests of Batch Renormalization by comparisons with its naive implementation, which uses several `FunctionNode`s.
Batch Renormalization uses "partial gradient". The current tests in Chainer use `check_backward` so that they check gradients w.r.t. a modified forward computation.  This PR removes `freeze_running_statistics` option, which has been introduced just for these tests.
Merge #4869 first.

Improve Batch Renormalization tests

---

tests/chainer_tests/functions_tests/math_tests/test_average.py

[backport] Fix occasional test failure of `F.average` by changing lower-bound of weight.sum

---

chainer/functions/normalization/batch_normalization.py

This is trivial cleanup of batch_normalization codes. This does not change any behaviors.
1. Rename `param_ndim` to `gamma_ndim` to make meaning be more explicit.
2. Add a comment to explain what is `key_axis`.
3. Cleanup `_as4darray` logic to make meaning be more explicit.
4. Remove `_get_mode` which is not used from anywhere.

Cleanup batch_normalization

---

examples/imagenet/googlenetbn.py

This fixes the issue that `--arch googlenet_fp16` does not work.

Fix invalid keyword arguments to `L.Linear` in ImageNet example

---

examples/imagenet/googlenetbn.py

[backport] Fix invalid keyword arguments to `L.Linear` in ImageNet example

---

docs/source/install.rst

We started to support NumPy 1.14 in Chainer v5.0.0b2 / v4.2.0 (as the corresponding CuPy started to support it), but was not documented.

Support NumPy 1.14 in docs

---

chainer/optimizer_hooks/gradient_clipping.py

~20% speed up (~6.0 iters/sec => ~7.3 iters/sec) was observed
with train_ptb.py on my GPU.
Probably, it'd be better to aggregate square norms on a GPU even
on multi-GPUs, but I haven't done it because I don't have multi-GPU
environment.
Tested by:
```
> $ CHAINER_TEST_GPU_LIMIT=1 python3 -m pytest \
tests/chainer_tests/optimizer_hooks_tests/test_gradient_clipping.py
```

Run gradient clipping on GPU, if possible

---

chainer/functions/math/fft.py

I found a minor grammatical error in the docstring of chainer.functions.fft
https://github.com/chainer/chainer/blob/4bd5237f45f384a05490e92aa6c58bd0d7e134e6/chainer/functions/math/fft.py#L57

Fix verb error in chainer.functions.fft docstring

---

chainer/computational_graph.py
tests/chainer_tests/test_computational_graph.py

[backport] Fix exception not raised when unsupported format is specified when dumping computational graph

---

examples/seq2seq/README.md

Backport of #5018.
Jenkins, test this please.

[backport] Fix typo in README of seq2seq

---

chainer/links/connection/linear.py

Adressing Issue #4115 
These items are done:
- Explanation on how W and b are initialized ignores initialW and initial_bias
- There's no explanation on how out_size=None works (except in the example section)
- There's no explanation on how initialW=None works
@muupan Can you provide clarification on what you mean by this?
> The `bias` parameter doesn't exist
Also, can you give a link to the specific compatibility policy or example of the format you're looking for for this?
> shapes and dtypes of `W` and `b` should be documented
Thanks,

 Clarifications for L.Linear

---

chainer/functions/connection/linear.py

Fix <img width="69" alt="screen shot 2018-06-26 at 20 44 22" src="https://user-images.githubusercontent.com/939877/41909350-c5b7dde2-7981-11e8-9a50-79a5475552db.png">
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.linear.html

Fix broken notations in `F.linear` docs

---

tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py

[backport] Remove unused parameter from `TestBatchRenormalization`

---

chainer/backends/cuda.py
chainer/link.py
chainer/variable.py
docs/source/reference/util/cuda.rst
tests/chainer_tests/test_cuda.py
tests/chainer_tests/test_link.py

Fixes #4903. This change makes `Link.copyparams` also copies the persistent values, notably the `avg_mean`, `avg_var`, and `N` of `links.BatchNormalization`.
Note that this change is backward incompatible since the default behavior is changed. The original behavior is confusing, and the new behavior should be beneficial in most cases (including existing code). The original behavior can be reproduced by passing `copy_persistent=False`.

Copy persistent values in `Link.copyparams`

---

chainer/functions/normalization/batch_normalization.py
chainer/functions/normalization/batch_renormalization.py
chainer/links/normalization/batch_normalization.py
chainer/links/normalization/batch_renormalization.py

- `BatchRenormalizationFunction` no longer has to support `F.fixed_batch_renormalization` (#4869).
- Stop manually wrapping `ndarray` by `Variable`.

Remove obsolete codes form batch (re)normalization

---

chainer/functions/array/get_item.py
tests/chainer_tests/functions_tests/array_tests/test_get_item.py

Fix `GetItem.backward` for 0-dim boolean index

---

chainer/functions/array/get_item.py
tests/chainer_tests/functions_tests/array_tests/test_get_item.py

[backport] Fix `GetItem.backward` for 0-dim boolean index

---

docs/source/tips.rst

[backport] Fix dead link to ``numpy.dtype.kind`` in Tips

---

chainer/functions/loss/mean_absolute_error.py
tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py

This PR is a part of #4582 and generalizes `F.mean_absolute_error` to support all float dtypes other than `float32`, with losing the condition of inputs.

Support all float dtypes in `F.mean_absolute_error`

---

chainer/links/activation/maxout.py
tests/chainer_tests/links_tests/activation_tests/test_maxout.py

This PR is a part of #4582, makes `L.Maxout` use the default dtype to initialize its initial bias when a scalar value is supplied for it.

Support default dtype in `L.Maxout`

---

docs/source/guides/variables.rst

* Add "Higher-Order Derivatives" section to show usage of `Variable.grad_var`
* Mention `chainer.grad`
* Use `Variable.array` rather than `Variable.data`
* Fix dead links

Improve Variable guide

---

docs/source/reference/datasets.rst

[backport] Clarify distinction between `chainer.dataset` and `chainer.datasets`

---

chainer/variable.py

Let's support `F.some_function(scalar)` by default, while a function wrapper may handle scalar inputs differently for efficiency.
This change seems consistent with:
- `cuda.to_gpu` supports scalar input.
- Chainer is going to support automatic broadcasting.
This change may make error messages confusing, e.g. from "scalar is not ndarray" to "inputs contain cpu array and gpu array".

Accept scalar argument to `as_variable`

---

chainer/links/connection/mgu.py
tests/chainer_tests/links_tests/connection_tests/test_mgu.py

This PR is a part of #4582, makes `L.StatefulMGU` use the default dtype to initialize its initial state `h`.

Support default dtype in `L.StatefulMGU`

---

chainer/functions/math/einsum.py

Fix `F.einsum` to support NumPy 1.15

---

chainer/variable.py
tests/chainer_tests/test_variable.py

This PR follows up #4510.
The gradient of an uninitialized parameter was always initialized with NaN of `numpy.float32` when its initializer was a callable, in contrast to its data that was initialized with the default dtype. This caused mismatch of dtypes between the data and the gradient.
This PR fixes it to use the default dtype to initialize the gradient in such case so that the data and the gradient have the same dtype.

Initialize gradient of uninitialized parameter with default dtype when initializer is callable

---

chainer/links/normalization/batch_normalization.py
chainer/links/normalization/batch_renormalization.py
tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py

Backport of #5017.
This also adds a part of example doc added in #4673.

[backport] Avoid hasattr in `L.BatchNormalization`

---

chainer/dataset/download.py

We have to use `os.path.join`.

Fix dataset path to support Windows

---

chainer/training/extensions/__init__.py
chainer/training/extensions/step_shift.py
docs/source/reference/training.rst
tests/chainer_tests/training_tests/extensions_tests/test_step_shift.py

This PR adds StepShift Extension to `Trainer`.
For example, given ``k``, a multiplier ``gamma`` and an initial value ``init``, the optimizer attribute is set to ``init * gamma ^ (floor(iter / k))``.
Docs and simple unittests are added.

Add `StepShift` Extension.

---

chainer/functions/normalization/l2_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py

[backport] Avoid zero division in `F.normalize`

---

docs/source/upgrade.rst

For #4997.
This PR also fixes broken heading. (duplicated "Chainer v5")

Add upgrade guide for `Link.copyparams` changes

---

chainer/links/model/vision/resnet.py
tests/chainer_tests/links_tests/model_tests/test_vision.py

This PR is a part of #4582, makes `L.ResNetLayers` use the default dtype in its helper method.

Support default dtype in `L.ResNetLayers`

---

chainer/links/model/vision/googlenet.py
tests/chainer_tests/links_tests/model_tests/test_vision.py

This PR is a part of #4582, makes `L.GoogLeNet` use the default dtype in its methods.

Support default dtype in `L.GoogLeNet`

---

chainer/training/extensions/print_report.py
tests/chainer_tests/training_tests/extensions_tests/test_print_report.py

PrintReport extension now seems not flushing the output stream at all, and output comes after a significant delay unless ProgressBar or something is used together.
This patch would fix that, but I can't provide a test because I don't know how I can test the stream is flushed properly.

Flush the output stream after PrintReport reports

---

chainer/links/model/vision/vgg.py
tests/chainer_tests/links_tests/model_tests/test_vision.py

This PR is a part of #4582, makes `L.VGG16Layers` use the default dtype in its methods.

Support default dtype in `L.VGG16Layers`

---

chainer/links/connection/convolution_2d.py

The ValueError message of L.Convolution2D is not splitted by a space.
Before:
the number of input channels must bedivisible by the number of groups
After
the number of input channels must be divisible by the number of groups

Fix L.Convolution2D error message

---

chainer/functions/loss/mean_squared_error.py
tests/chainer_tests/functions_tests/loss_tests/test_mean_squared_error.py

This PR is a part of #4582 and generalizes `F.mean_squared_error` to support all float dtypes other than `float32`, with loosing the condition of inputs.

Support all float dtypes in `F.mean_squared_error`

---

chainer/link.py
tests/chainer_tests/test_link.py

Fix backward compatibility of `Link.__call__` MRO

---

chainer/link.py
tests/chainer_tests/test_link.py

[backport] Fix backward compatibility of `Link.__call__` MRO

---

tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py

This PR fixes a parameterized test case of `F.contrastive`. The case was introduced in https://github.com/chainer/chainer/pull/3466 .

Trivial fix for parameterized test case of F.contrastive

---

tests/chainer_tests/distributions_tests/test_bernoulli.py

#5025 has tests that leave warnings.  This PR tentatively suppresses them.
While it's clear that `entropy` method should not warn `0 * log(0)`, other methods (e.g. `log_prob`) may warn `-inf` from `log(0)`.

Ignore float warnings if testing extreme value

---

chainer/link.py
tests/chainer_tests/test_link.py

[hotfix] [backport] Fix backward compatibility of `Link.__call__` MRO

---

chainer/functions/loss/contrastive.py
tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py

This PR follows #4582, generalize `F.contrastive` support all float dtypes.

Support all float data types in `F.contrastive`

---

chainer/functions/loss/absolute_error.py
tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py

This PR follows #4582, generalizes `F.absolute_error` to support all float data types.

Support all float data types in `F.absolute_error`

---

chainer/functions/array/split_axis.py
tests/chainer_tests/functions_tests/array_tests/test_split_axis.py

This PR fixes #4153.
Outputs of `np.split` differ among numpy versions if there's an output with size 0.  It's possible that  intensionally such case had been unsupported.  #4153 added the support, but didn't work with numpy<1.11.

Support old numpy in `F.split_axis`

---

chainer/backends/intel64.py
docs/source/reference/util/cuda.rst

* Separate "CUDA Utilities" section and add iDeep.
Context: in #5095 (move ``chainer.backends.cuda.copyto`` to ``chainer.backend.copyto``), I want a generic section to add backend-agnostic functions.
* Expose `intel64.is_ideep_available` as public API, as it is convenient because users can use this to decide whether to call ``to_intel64`` or not.

Add iDeep to backend docs

---

docs/source/tips.rst

This fixes #5134.
Please merge https://github.com/chainer/chainer-test/pull/441 after this PR and backport got merged.

Avoid use of ideep in doctest

---

docs/source/tips.rst

[backport] Avoid use of ideep in doctest

---

chainer/__init__.py

This PR fixes `chainer.get_dtype()` to normalize `chainer.config.dtype` in case `chainer.config.dtype` has any of data type specifiers (dtype objects, data types, str, ...) as discussed at https://github.com/chainer/chainer/pull/5143#issuecomment-408788835

Normalize chainer.config.dtype in  chainer.get_dtype()

---

chainer/optimizers/rmsprop.py
tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py

Implement eps_inside_sqrt option to RMSprop

---

chainer/functions/connection/deconvolution_nd.py

This PR resolve error described in #5128.
The deterministic algorithm of cuDNN is incompatible with dilated convolution.

Fix the condition for the switching of cuDNN in `F.deconvolution_nd`

---

chainer/functions/loss/huber_loss.py
tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py

This PR follows #4582 to support all float dtypes in `F.huber_loss`.

Support all float dtypes in `F.huber_loss`

---

chainer/functions/math/logsumexp.py
tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py

Related to #5015 
* Used `chainer.utils.force_array`
* Added shape parameter for tests
* Skiped some tests which is specified axis other than None if input shape is 0-dim
* referred  to `functions_tests.math_tests.test_einsum._skip_if`
* But does not skip following tests
* `test_invalid_axis_type`
* `test_invalid_axis_type_in_tuple`

Support 0-dim input in `F.logsumexp`

---

chainer/functions/util/forget.py
tests/chainer_tests/functions_tests/util_tests/test_forget.py

Current `F.forget` doesn't do backward computation appropriately. If `func` includes some model parameters, their gradient parameters may not be set.
Example:
```python
import chainer.links as L
class MLP(chainer.Chain):
super(MLP, self).__init__()
self.lin = L.Linear(None, 10)
def forward(self, x):
return F.forget(self.lin, x)
def main():
model = MLP()
model.cleargrads()
x = np.random.uniform(-1, 1, (64, 768)).astype(np.float32)
x = chainer.Variable(x, requires_grad=True)
y = F.sum(model(x))
y.backward()
print(model.lin.W.grad)  # => None
print(model.lin.b.grad)  # => None
if __name__ == '__main__':
main()
```
This issue exists because current backward implementation in `F.forget` calls …

Fix backward computation in F.forget

---

chainer/backends/__init__.py
chainer/backends/cuda.py
chainer/link.py
chainer/variable.py
docs/source/reference/util/cuda.rst
tests/chainer_tests/backends_test/test_init.py
tests/chainer_tests/test_cuda.py
tests/chainer_tests/test_variable.py

This fixes #5009.
This is not to-be-backported as `backends.cuda.copyto` is introduced in #4997.

Move `backends.cuda.copyto` to `backends.copyto` and make it work with iDeep

---

chainer/functions/math/erfinv.py

This PR improves the speed of backward of `F.erfinv`.

Retain outputs in `F.erfinv`

---

chainer/link.py
tests/chainer_tests/test_link.py

Fixes #4547.
The following methods now returns params and children in consistent order.
* `Link`: `params`, `namedparams`
* `Chain`: `params`, `namedparams`, `links`, `namedlinks`, `children`

Return params and children as ordered by name in Link and Chain

---

chainer/functions/loss/decov.py
tests/chainer_tests/functions_tests/loss_tests/test_decov.py

This PR follows #4582 to support all float dtypes in `F.decov`.

Support all float dtypes in `F.decov`

---

chainer/functions/pooling/pooling_2d.py
chainer/links/caffe/caffe_function.py
chainer/links/theano/theano_function.py

- While I've not found a code to produce `DeprecationWarning` by using `chainer`, I'd like to fix `collections.Iterable`, too. (#5097)
- `disable` arg of `CaffeFunction.forward` had to be `collections.abc.Collection`, but the docstring says just `Iterable`.

Fix collections.Iterable

---

chainer/functions/loss/squared_error.py
tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py

This PR follows #4582 to support all float dtypes in `F.squared_error`.

Support all float dtypes in `F.squared_error`

---

chainer/functions/connection/bilinear.py

Do the other fix to #4736 than #4738.  `cupy>=v5.0.0b2` has moderately efficient `einsum`.
This PR should not be backported to v4.

Use `xp.einsum` in `F.bilinear`

---

chainer/function_hook.py
chainer/function_node.py

There should be no point in making it named/optional.

Avoid keyword arguments in `FunctionHook` callbacks

---

setup.cfg

I run `pytest` with
- Theano 1.0.2
- Python 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin

Ignore Theano warns in python 3.7

---

chainer/functions/array/split_axis.py
chainer/functions/loss/ctc.py
chainer/functions/math/tensordot.py
chainer/functions/normalization/batch_normalization.py
chainer/link.py
chainer/utils/__init__.py

[backport] Use collections.abc to avoid DeprecationWarning in Python 3.7

---

setup.cfg

[backport] Ignore Theano warns in python 3.7

---

chainer/functions/array/diagonal.py
chainer/functions/array/dstack.py
chainer/functions/array/expand_dims.py
chainer/functions/array/flip.py
chainer/functions/array/fliplr.py
chainer/functions/array/flipud.py
chainer/functions/array/get_item.py
chainer/functions/array/hstack.py
chainer/functions/array/im2col.py
chainer/functions/array/moveaxis.py
chainer/functions/array/pad.py
chainer/functions/array/pad_sequence.py
chainer/functions/array/permutate.py
chainer/functions/array/repeat.py
chainer/functions/array/reshape.py
chainer/functions/array/resize_images.py
chainer/functions/array/rollaxis.py
chainer/functions/array/scatter_add.py
chainer/functions/array/select_item.py
chainer/functions/array/separate.py
chainer/functions/array/space2depth.py
chainer/functions/array/spatial_transformer_grid.py

Partially addressing #4969. It fixes `diagonal`, ..., `spatial_transformer_grid` in alphabetical order of names under `chainer.functions.array`.

Improve type check messages for some array functions

---

chainer/functions/normalization/batch_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py

I added lines checking the eps value in FixedBatchNormalization as is already done in BatchNormalization. I also added the test case based on the one for functions.batch_normalization.

Check eps < CUDNN_BN_MIN_EPSILON in FixedBatchNormalization.

---

chainer/functions/math/batch_l2_norm_squared.py
tests/chainer_tests/functions_tests/math_tests/test_batch_l2_norm_squared.py

This PR follows #4582 to support all float dtypes in `F.batch_l2_norm_squared`.

Support all float dtypes in `F.batch_l2_norm_squared`

---

chainer/functions/loss/softmax_cross_entropy.py
tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py

Fix #5127 
(As a side-effect, this PR changes behavior on bad input.  In the cpu computation, except for `ignore_label`, negative `t` will be treated as `n + t`, while it was treated as `0`.)

Fix cpu codes of indexing in `F.softmax_cross_entropy`

---

tests/chainer_tests/functions_tests/math_tests/test_basic_math.py

Matmul (`@`) is not as accurate as other binary operators (`+`, `-`, `*`, `/`) are.
```
E           AssertionError: Parameterized test failed.
E           
E           Base test method: TestMatMul.test_forward_gpu
E           Test parameters:
E             z_shape: (2, 2, 3, 2)
E             dtype: <class 'numpy.float32'>
E             left_const: False
E             y_shape: (2, 4, 2)
E             x_shape: (2, 1, 3, 4)
E             right_const: False
E           
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=1e-07
E           
E           (mismatch 4.166666666666671%)
E            x: array([[[[-0.812174,  0.495421],
E                    [ 0.275101, -0.099681],
E                    [-1.200468,  0.912167]],...
E            y: array([[[[-0.812174, …
```

Adjust tolerance of TestMatMul

---

setup.cfg
tests/chainer_tests/links_tests/theano_tests/test_theano_function.py

Motivation: fix Travis failure (macOS, python 3.4).
After the change
```
% pytest -m "not slow and not gpu and not cudnn and not ideep" chainer_tests/links_tests/theano_tests -x
============================= test session starts ==============================
platform darwin -- Python 3.4.4, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /Users/tos/GitHub/chainer, inifile: setup.cfg
plugins: timeout-1.2.1, cov-2.5.1
collected 40 items / 20 deselected
chainer_tests/links_tests/theano_tests/test_theano_function.py ......... [ 45%]
...........                                                              [100%]
=============================== warnings summary ===============================
tests/chainer_tests/links_tests/theano_tests/test_theano_function.py::TestTheanoFunctionTwoOutputs_param_1 …
```

Ignore `DeprecationWarning`s at importing Theano

---

chainer/functions/connection/shift.py
chainer/functions/evaluation/accuracy.py
chainer/functions/evaluation/binary_accuracy.py
chainer/functions/evaluation/classification_summary.py
chainer/functions/evaluation/r2_score.py
chainer/functions/loss/absolute_error.py
chainer/functions/loss/contrastive.py
chainer/functions/loss/cross_covariance.py
chainer/functions/loss/ctc.py
chainer/functions/loss/decov.py
chainer/functions/loss/hinge.py
chainer/functions/loss/huber_loss.py
chainer/functions/loss/mean_absolute_error.py
chainer/functions/loss/mean_squared_error.py
chainer/functions/loss/negative_sampling.py
chainer/functions/loss/squared_error.py
chainer/functions/loss/triplet.py

Partially addressed #4969.
- `connection/shift.py`
- `evaluation/*.py`
- `loss/*.py`

Improve type check messages for some functions

---

setup.cfg
tests/chainer_tests/links_tests/theano_tests/test_theano_function.py

[backport] Ignore `DeprecationWarning`s at importing Theano

---

chainer/links/activation/maxout.py
tests/chainer_tests/links_tests/activation_tests/test_maxout.py

Merge #5058 and #5064 first.
The documentation of `L.Maxout` says that `initialW` and `initial_bias` can be initializers, but its implementation actually looks assuming that they are scalars or ndarrays.
This PR fixes `L.Maxout` to support general initializers including `Initializer` instances and callables.
Note that callables are wrapped to destructively reshape arrays to initialize into appropreate shapes for L.Maxout.

Better initializer support in `L.Maxout`

---

chainer/distributions/normal.py

This PR improves accuracy when `x` is small.

Use erfcinv for Normal.icdf

---

chainer/distributions/normal.py

`log_ndtr` is used to avoid overflow and underflow. `ndtr` is for consistency.

Use ndtr and log_ndtr in normal distribution

---

chainer/functions/math/ndtri.py

Use [`normcdfinv`](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__DOUBLE.html#group__CUDA__MATH__DOUBLE_1g78e93df6c3fbade8628d33e11fc94595) in `F.ndtri`.

Use normcdfinv in F.ndtri

---

chainer/function_node.py
chainer/variable.py

This fixes the issue that `chainer.grad` may change the current device.
I'd like to use `with device` instead of `device.use()`.  I left `dev.use()` in the worker of `MultiprocessParallelUpdater` because it's clear the process does not do other tasks.

Use `with cuda_device`

---

chainer/functions/loss/sigmoid_cross_entropy.py
tests/chainer_tests/functions_tests/loss_tests/test_sigmoid_cross_entropy.py

This PR follows #4582 to support all float dtypes in `F.sigmoid_cross_entropy`.
I found that it has relatively large error in forward computation when it computes FP64 data with CuPy. It seems that [this line](https://github.com/takagi/chainer/blob/c910fd0db9640784da9262908c7e4bdbb83c60b5/chainer/functions/loss/sigmoid_cross_entropy.py#L56) with dtype argument would cause the error between numpy and CuPy. I will check it later.

 Support all float dtypes in `F.sigmoid_cross_entropy`

---

chainer/_runtime_info.py

[backport] Include platform information to `chainer.print_runtime_info()`

---

chainer/functions/array/spatial_transformer_grid.py
tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_grid.py

This PR is a part of #4582, makes `F.spatial_transformer_gird` use the default dtype.

Support default dtype in `F.spatial_transformer_grid`

---

chainer/functions/normalization/l2_normalization.py
tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py

This PR follows #4582 to support all float dtypes in `F.normalize`.

Support all float dtypes in `F.normalize`

---

chainer/functions/pooling/roi_pooling_2d.py
tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py

This PR follows #4582 to support all float dtypes in `F.roi_pooling_2d`.

Support all float dtypes in `F.roi_pooling_2d`

---

.github/ISSUE_TEMPLATE.md

I updated the Issue template.
It needs to be merged after #5268 
- refer: https://raw.githubusercontent.com/explosion/spaCy/master/.github/ISSUE_TEMPLATE.md

Update issue-template to encourage users to use `chainer.print_runtime_info`

---

tests/chainer_tests/testing_tests/test_unary_math_function_test.py

it seems deprecated arg `is_linear` causes test fail in `AppVeyor`.
https://github.com/chainer/chainer/pull/5198#issuecomment-419634854

remove deprecated is_linear arg

---

docs/source/contribution.rst

Add quotation marks to `pip install -e '.[stylecheck]'` to allow it to work on shells like zsh that allow brace expansion.
Backwards compatible with bash shell.
Addresses issue #5301

Add quotes to stylecheck install

---

docs/source/index.rst

I think it's better to place ChainerMN docs after Chainer Reference.
Ref #5226.

Fix location of chainermn docs in sidebar

---

.travis.yml
chainer/functions/connection/linear.py
chainer/links/connection/linear.py
chainer/optimizer_hooks/gradient_lars.py
chainer/training/extensions/step_shift.py
chainer/training/extensions/variable_statistics_plot.py
examples/memnn/memnn.py
tests/chainer_tests/function_hooks_tests/test_debug_print.py
tests/chainer_tests/utils_tests/test_argument.py

Fix invalid escape sequence warnings in Python 3.6

---

chainermn/__init__.py

`chainermn.__version__` will be kept for backward compatibility, and now it points to the version of Chainer.
However, we should avoid using `pkg_resources` (c.f. #3628)
Ref #5226.

Avoid using `pkg_resources` to retrieve Chainer version

---

.travis.yml
chainer/optimizer_hooks/gradient_lars.py
chainer/training/extensions/variable_statistics_plot.py
tests/chainer_tests/function_hooks_tests/test_debug_print.py
tests/chainer_tests/utils_tests/test_argument.py

[backport] Fix invalid escape sequence warnings in Python 3.6

---

chainer/links/model/classifier.py

This PR makes the Classifier chain better explains the importance to clear the Variable attirubtes. It prevents sloppy users defines their own chain that consumes unnecessary memory. 
The docstring of `chainer.links.model.Classifier` says:
This is an example of chain that wraps another chain. It computes the
loss and accuracy based on a given input/label pair.
So it is reasnoable to assume that users often view and modify the source to define a custom chain. In fact, such a double memory allocation bug has actually happend in a project I'm work for.

Add a comment that explains why the Classifier chain clears Variable attribues.

---

setup.py

It looks the newer version of sphinx is causing test errors in Travis tests for MacOS.

Fix sphinx version to 1.7.9

---

chainer/functions/math/einsum.py
tests/chainer_tests/functions_tests/math_tests/test_einsum.py

This feature is controversial and I'd rather not support it in the next stable release.

Disallow summing over ellipsis in `F.einsum`

---

tests/chainer_tests/distributions_tests/test_kldivergence.py

Printing to stdout in tests should be avoided.

Avoid printing in test_kldivergence

---

chainer/functions/array/permutate.py
chainer/links/connection/n_step_rnn.py
tests/chainer_tests/functions_tests/array_tests/test_permutate.py
tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py

`permutate` does not have to pass `indices` as an input variable.  This allows to permutate GPU arrays by CPU indices.
This PR also fixes #5347.

Fix input variable of FunctionNode of `permutate`

---

chainer/serializers/hdf5.py
chainer/serializers/npz.py
tests/chainer_tests/serializers_tests/test_hdf5.py
tests/chainer_tests/serializers_tests/test_npz.py

Make deserializer overwrite arrays of any backend.
I locally tested the added tests fail without this fix.  Note that `type(value)(numpy.asarray(dataset))` created new `intel64.mdarray`.

Make deserializers overwrite `intel64.mdarray`

---

chainer/functions/__init__.py
chainer/functions/pooling/roi_average_align_2d.py
tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py

related to #5304 
support new interface `roi_average_align_2d`

refine roi_average_align_2d interface

---

chainer/serializers/hdf5.py
chainer/serializers/npz.py
tests/chainer_tests/serializers_tests/test_hdf5.py
tests/chainer_tests/serializers_tests/test_npz.py

[backport] Make deserializers overwrite `intel64.mdarray`

---

docs/source/upgrade.rst

Mentioned the `chainer.backend` subpackage and the new location of `get_array_module` in the upgrade guide.

Mention chainer.backend in upgrade guide

---

tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
tests/chainer_tests/functions_tests/math_tests/test_matmul.py

`numpy.matmul` may have large error (>1ulp) with `float16` inputs
```
>>> import numpy as np
>>> x = np.array([[0.8896484375, 0.767578125, 0.712890625, 0.76318359375, 0.5224609375]], 'e')
>>> y = np.array([
...     [0.76416015625, 0.68994140625],
...     [0.82861328125, 0.85205078125],
...     [0.99169921875, 0.95751953125],
...     [0.5947265625, 0.89990234375],
...     [0.61865234375, 0.98681640625]], 'e')
>>> x@y
array([[2.797, 3.152]], dtype=float16)
>>> x.astype('d')@y.astype('d')
array([[2.79993963, 3.15279126]])
```

Fix tolerance of matmul tests

---

chainer/distribution.py
chainer/distributions/normal.py

I'd like to have `Distribution.params` to get all the parameters (in the statistics' sense) in a tuple or a dict.  This name can be confusing because `Link` has `params` method with different meaning.
In ChainerRL, `params` method returns a tuple of `Variable`s.
`params` can be used to give the default implementation of `Distribution.xp`.

[RFC] Add `params` and `xp` to `Distribution`

---

chainer/functions/activation/log_softmax.py
tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py

This PR also allows 1-dim inputs.

Support negative `axis` for `F.log_softmax`

---

chainermn/functions/point_to_point_communication.py
chainermn/links/batch_normalization.py
chainermn/links/n_step_rnn.py

This PR removes unnecessary version checking in ChainerMN.
Background:
Before ChainerMN was merged into Chainer repository, ChainerMN has to check Chainer version installed in the environment. This was because some features in ChainerMN depended on Chainer's internal structures. However, ChainerMN is now integrated to Chainer and installed together. These version checking code is no longer necessary.

Remove unnecessary version checking in ChainerMN

---

chainer/training/extensions/plot_report.py
chainer/training/extensions/variable_statistics_plot.py
tests/chainer_tests/training_tests/extensions_tests/test_plot_report.py
tests/chainer_tests/training_tests/extensions_tests/test_variable_statistics_plot.py

This PR fixes the following issues.
- Python 3.7 warns `import chainer` on `import matplotlib` (`matplotlib==2.2.3`).  With `filterwarnings=error::DeprecationWarning`, pytest (3.8.0) cannot even run a test with `import chainer`.
- It seems `import chainer` is slower if `matplotlib` is installed.

Dynamically import matplotlib

---

chainer/utils/__init__.py
chainer/utils/precision.py
tests/chainer_tests/utils_tests/test_precision.py

This PR introduces `utils.mixed_presision` decorator that makes forward computation perform in FP32 for FP16 inputs, returning outputs casted back to FP16. It does nothing for FP32 and FP64 inputs.
```Python
class BatchDet(function_node.FunctionNode):
...
@utils.mixed_precision
def forward_cpu(self, x):
self.retain_inputs((0,))
self.retain_outputs((0,))
detx = utils.force_array(numpy.linalg.det(x[0]))  # numpy.linalg.det does not support FP16
return detx,
...
```

Introduce `utils.mixed_presision` decorator

---

tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py

[backport] Fix occasional test failure of `l2normalize` with float16

---

docs/source/index.rst
docs/source/install.rst

Introduce https://github.com/chainer/google-colaboratory in official docs.

Add Google Colaboratory installation steps and link to community examples

---

chainer/links/caffe/caffe_function.py

[bugfix] CaffeFunction ignores pad_w

---

chainer/_environment_check.py
chainer/_version.py
setup.py

Optional dependencies should not be decleared as requirements, as it makes difficult for users to uninstall the optional dependencies.
One of the common pitfall (when user upgraded their CUDA version):
```
pip install cupy-cuda90
pip install chainer
pip uninstall cupy-cuda90
pip install cupy-cuda92
pip install chainer
```

Check optional dependencies at runtime

---

setup.cfg

Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15

---

chainer/gradient_check.py

In the current implementation of  `gradient_check.check_backward`, computation of backward gradients / numerical gradients / some checks are mixed and very difficult to understand.
I refactored the function for readability and maintainability.

Refactor `gradient_check.check_backward`

---

setup.cfg

[backport] Ignore scipy<1.0 is warned by using deprecated feature of numpy>=1.15

---

examples/imagenet/train_imagenet_data_parallel.py

[backport] Fix `train_imagenet_data_parallel.py` example cannot be run

---

chainer/functions/activation/softmax.py
tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
tests/chainer_tests/functions_tests/activation_tests/test_softmax.py

This PR fixes a bug in #5381.
`_get_tensor4d_shape` implicitly assumed `axis` is nonnegative.  (`shape[slice(axis + 1, len(shape))]` doesn't work if `axis=-1`.)

Fix `F.softmax` and `F.log_softmax` with `axis=-1` on gpu

---

chainer/optimizer.py
tests/chainer_tests/test_optimizer.py

When a network is trained with some parameters set `update_rule.enabled=False`, the snapshot of an optimizer can't be deserialized if `strict=False` option isn't set to the deserializer.
This PR fixes the problem by checking `update_rule.enabled` at the time of deserialization. Some tests are also added.
The following is the minimal example that reproduce the issue.
```python
import chainer
from chainer import functions, links, optimizers, serializers
import numpy
class Model(chainer.Chain):
super().__init__()
self.l1 = links.Linear(10, 10)
self.l2 = links.Linear(10, 10)
def __call__(self, x, t):
h = self.l1(x)
h = self.l2(h)
h = functions.mean(h, axis=1)
return functions.sigmoid_cross_entropy(h, t)
def main():
model = Model()
optimizer = …
```

For proper resuming, don't raise KeyError at UpdateRule deserialization

---

chainer/functions/loss/softmax_cross_entropy.py

Implements `SoftmaxCrossEntropy` with `FunctionNode`.
This execution path is for single-backward only, so double-backward is not implemented.
This PR does not enhance functionality, but the overhead of `FunctionAdapter` could be reduced.

Implement no-double-backprop version of F.softmax_cross_entropy using FunctionNode

---

chainer/functions/loss/softmax_cross_entropy.py

Fix a bug in #5478 (sorry, it was my review fault). FunctionNode.forward should not return None as an output, so I fixed it. It should fix the current doctest failure in master.

Fix SoftmaxCrossEntropy grad function node

---

chainer/_runtime_info.py
chainer/backends/intel64.py
docs/source/tips.rst

See #5049
This PR includes:
* ~Fix #4948. This also improves the message during installation by displaying detected package path of CuPy. This intends to make it easy for users to understand why and where cupy/ideep4py was detected.~ iDeep requirements will be checked at runtime (#5425)
* Update docs for iDeep 2.0.
* Detect version of iDeep.
* Show iDeep version information in `chianer.print_runtime_info()`.

Update packaging for iDeep 2.0

---

chainer/variable.py

[backport] replace variable.data with variable.array in chainer.variable.py

---

chainer/variable.py

[backport] Consistently use `Variable.array` instead of `.data`

---

chainer/training/extension.py
chainer/training/extensions/_snapshot.py
chainer/training/trainer.py
examples/mnist/train_mnist.py
tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
tests/chainer_tests/training_tests/test_trainer.py

This commit also adds `snapshot_on_error` option to snapshot extension as a simple example of error handling in extensions, which I suggested at #4566. Use cases are:
* use cases like snapshots, or [checkpoints](http://chainermn.readthedocs.io/en/stable/reference/#chainermn.create_multi_node_checkpointer) it would be nice if the trainer extensions have error handling interface to preserve the *latest* trainer image, or models. See changes in this PR on snapshot extension, which has additional `snapshot_on_error` flag for actual implementation.
* ChainerUI currently just become silent when the training script dies, but it's nice if friendly message and stacktrace can be displayed on the Web UI.
* To handle some cases node failure or GPU failure in parallel training by ChainerMN.

Add error handler interface to trainer extensions

---

chainer/functions/loss/huber_loss.py

While inputs with ndim > 2 were undocumented, `backward` should not fail whenever `type_check_forward` and `forward` succeed.
Close #5487.
See also the discussion in #3867.

Fix backward of HuberLoss

---

setup.cfg

[backport] Ignore protobuf is warned by Python 3.7

---

chainer/functions/math/det.py
chainer/functions/math/inv.py
tests/chainer_tests/functions_tests/math_tests/test_det.py
tests/chainer_tests/functions_tests/math_tests/test_inv.py

Merge ~https://github.com/cupy/cupy/pull/1617~ and #5306 first.
https://github.com/takagi/chainer/compare/mixed-precision-decorator...takagi:dtype-det
This PR follows #4582 to support all float dtypes in `F.det` as well as `F.inv` used in `F.det` backward computation. Note that some routines used do not support FP16 data, `F.det` and `F.inv` compute FP16 inputs in FP32.

Support all float dtypes in `F.det` and `F.inv`

---

chainer/training/extensions/exponential_shift.py
chainer/training/extensions/inverse_shift.py
chainer/training/extensions/linear_shift.py
chainer/training/extensions/polynomial_shift.py
chainer/training/extensions/step_shift.py
docs/source/guides/extensions.rst

Using `.item()` is OK because it's checked that the object is an instance of `np.ndarray`.
`np.asscalar` is deprecated since NumPy v1.16:
```
warnings.warn('np.asscalar(a) is deprecated since NumPy v1.16, use '
>                     'a.item() instead', DeprecationWarning, stacklevel=1)
E       AssertionError: Parameterized test failed.
E
E       Base test method: TestExponentialShift.test_resume
```

Use arr.item() instead of np.asscalar(arr) to support NumPy 1.16

---

chainer/training/extensions/exponential_shift.py
chainer/training/extensions/inverse_shift.py
chainer/training/extensions/linear_shift.py
chainer/training/extensions/polynomial_shift.py
chainer/training/extensions/step_shift.py
docs/source/guides/extensions.rst

[backport] Use arr.item() instead of np.asscalar(arr) to support NumPy 1.16

---

chainer/functions/activation/softmax.py
tests/chainer_tests/functions_tests/activation_tests/test_softmax.py

Merge #5496 first.
This PR also allows 1-dim inputs.
cf. #5381

Support negative `axis` for `F.softmax`

---

docs/source/install.rst
docs/source/upgrade.rst

[backport] Chainer v5 requires CuPy v5

---

chainer/links/caffe/caffe_function.py

The current logic of the internals of `L.CaffeFunction` depends on `Variable` is not `Iterable`, which I'd like to avoid.
Split from #5444.

Avoid Iterable in CaffeFunction

---

chainer/functions/array/get_item.py
chainer/functions/array/scatter_add.py
tests/chainer_tests/functions_tests/array_tests/test_get_item.py
tests/chainer_tests/functions_tests/array_tests/test_scatter_add.py

Merge #5306 first.
~https://github.com/takagi/chainer/compare/mixed-precision-decorator...takagi:dtype-scatter-add~
This PR follows #4582 to support all float dtypes in `F.scatter_add` as well as `F.get_item` using each other in backward computation. ~Note that because some routines used do not support FP16 data, they compute FP16 inputs in FP32.~
Merge https://github.com/cupy/cupy/pull/1684 also before this PR.

Support all float dtypes in `F.scatter_add` and `F.get_item`

---

tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py

Close #5494.
- I left 267 tests (39.15 s)
- I marked 112 slow tests (104.72 s)

Tests with maxtasksperchild=1 or 10 are slow

---

chainer/functions/connection/convolution_2d.py
chainer/functions/connection/convolution_nd.py
chainer/functions/connection/deconvolution_2d.py
chainer/functions/connection/deconvolution_nd.py
chainer/utils/conv.py
chainer/utils/conv_nd.py
tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
tests/chainer_tests/utils_tests/test_conv.py
tests/chainer_tests/utils_tests/test_conv_nd.py

Fix #5403. The grouped convolution is rewritten using single `matmul` call instead of iterating over all subchannels in Python. The performance of non-cuDNN paths are improved. In particular, the degradation of `depthwise_convolution_2d` observed in #5403 is almost recovered. A quick benchmarking in my environment is: the MobileNet inference took 85.4 ms (this patch) vs 84.0 ms (v4.5.0) vs 575 ms (master).
This patch should be backported to v5, since the degradation of `depthwise_convolution_2d` is critical.

Grouped convolutions using matmul

---

chainer/distributions/uniform.py

I found `dist.log_prob(dist.sample())` is returning `-inf`.

Fix `D.Uniform.log_prob` to avoid returning -inf at boundary

---

chainer/datasets/sub_dataset.py
chainer/functions/array/get_item.py
chainer/link.py
chainer/utils/type_check.py
chainermn/functions/pseudo_connect.py
docs/source/compatibility.rst
docs/source/contribution.rst
docs/source/guides/gpu.rst
docs/source/reference/check.rst
docs/source/reference/static_graph_design.rst
docs/source/upgrade_v2.rst

[backport] Use "documentation" instead of "document" in our documentation

---

chainermn/communicators/__init__.py

[backport] ChainerMN: add an error message when mpi4py is missing

---

chainer/link.py
setup.cfg
tests/chainer_tests/test_link.py

Un-deprecate `Link.add_param` and `Link.add_link`

---

docs/source/install.rst

[backport] Add Python 3.7 support to installation docs

---

chainer/link.py
setup.cfg
tests/chainer_tests/test_link.py

[backport] Un-deprecate `Link.add_param` and `Link.add_link`

---

chainer/distributions/uniform.py

[backport] Fix `D.Uniform.log_prob` to avoid returning -inf at boundary

---

chainer/reporter.py
chainer/serializers/npz.py
chainer/testing/backend.py
tests/chainer_tests/test_reporter.py

Adds type check in `NpzDeserializer` which raises `TypeError` if unsafe casting would be imposed.
Merge #5482 first.

 Add type compatibility check in npz deserializer 

---

chainer/functions/util/forget.py

[backport] Fix docstring of `F.forget`

---

chainer/functions/loss/negative_sampling.py
tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py

Merge #5335 first.
~https://github.com/takagi/chainer/compare/dtype-scatter-add...takagi:dtype-negative-sampling-function~
This PR follows #4582 to support all float dtypes in `F.negative_sampling`. ~Note that because some routines used do not support FP16 data, it computes FP16 inputs in FP32.~

Support all float dtypes in `F.negative_sampling`

---

setup.cfg
tests/chainer_tests/utils_tests/test_type_check.py

[backport] Fix test warnings in NumPy 1.15

---

chainer/functions/array/get_item.py
tests/chainer_tests/functions_tests/array_tests/test_get_item.py
tests/chainer_tests/functions_tests/array_tests/test_scatter_add.py

[backport] Support all float dtypes in `F.scatter_add` and `F.get_item`

---

chainer/distributions/one_hot_categorical.py
tests/chainer_tests/distributions_tests/test_one_hot_categorical.py

- Old versions of NumPy do not have `stack` and `moveaxis`.
- Old versions of NumPy too strictly check `p.sum()`.

Fix `D.OneHotCategorical`

---

chainer/functions/array/resize_images.py
chainer/functions/array/spatial_transformer_sampler.py
chainer/functions/connection/linear.py
chainer/functions/evaluation/classification_summary.py
chainer/functions/evaluation/r2_score.py
chainer/functions/loss/ctc.py
chainer/functions/math/basic_math.py
chainer/functions/math/fft.py
chainer/testing/unary_math_function_test.py

This would improve the performance.

Avoid unnecessary copy in `ndarray.astype`

---

chainer/functions/loss/negative_sampling.py
tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py

[backport] Fix `F.negative_sampling` output dtype in CPU mode

---

chainer/_environment_check.py
docs/source/tips.rst

Addressing Issue #4904 
Since vecLib appears to are fixed for MNIST, removing the ReadTheDocs references to work arounds for MacOS NumPy.

Update installation guide of numpy with openblas on macOS

---

chainer/testing/__init__.py

Fixes #5632 .
Tests using for instance `inject_backend_tests` may be updated but I chose not to widen the scope of this PR.

Import testing/backend.py definitions in testing/__init__.py

---

examples/text_classification/text_datasets.py

Fix text_classification example fails on Python 3 #5590
I have confirmed that it runs fine on Python 2.7.12, 3.4.3, 3.6.4.

Fix text_classification example fails on Python 3 (#5590)

---

chainer/distribution.py

I found a small typo in the document of `chainer.distributions`

Fix a typo in the document of chainer.distributions

---

chainer/distribution.py

[backport] Fix a typo in the document of chainer.distributions

---

chainer/functions/connection/embed_id.py
tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py

This PR follows #4582, generalizes `F.embed_id` to support all float data types.

Support all float dtypes in `F.embed_id`

---

chainer/functions/activation/rrelu.py
tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py

- Fix typos, including `'train'` config.
- The shape of `r` should be the same as the shape of `x`.
- Remove `retry` from tests.  I confirmed that the cpu tests pass with `repeat(10000)`.

Fix test of `F.rrelu`

---

chainer/links/model/vision/resnet.py

[backport] Fix typo in `L.ResNetLayers`

---

chainer/dataset/convert.py

This PR aims to overlap GPU kernels and data transfer more.
Current `ConcatWithAsyncTransfer` implementation uses global synchronization to prevent a GPU kernel read arrays that might be still being transferred to GPU. This implementation is safe but it blocks a CPU thread to launch GPU kernels until data transfer to GPU is finished.   With this PR, the global synchronized is removed and CUDA events are used instead to further overlap GPU kernels and data transfers w/o blocking a CPU thread to launch GPU kernels. You should specify CUDA stream used for compute kernels by an argument `compute_stream` like below, or global synchronization is used as before.
converter = dataset.ConcatWithAsyncTransfer(compute_stream=chainer.backends.cuda.Stream.null)

Overlap compute and transfer more

---

chainer/functions/loss/ctc.py
tests/chainer_tests/functions_tests/loss_tests/test_ctc.py

This PR follows #4582, generalize `F.connectionist_temporal_classification` to support all float dtypes.

Support all float dtypes in `F.connectionist_temporal_classification`

---

setup.cfg

Ignore h5py is warned by Python 3.7

---

chainer/links/loss/hierarchical_softmax.py
tests/chainer_tests/links_tests/loss_tests/test_hierarchical_softmax.py

This PR follows #4582, making `L.BinaryHierarchicalSoftmax` support the default dtype.

Support default dtype in `L.BinaryHierarchicalSoftmax`

---

.travis.yml
setup.cfg
setup.py

The newest flake8 (3.6.0) requires pycodestyle 2.4, which has the `W504` check.
It seems `W504` needs to be added to `ignore` in `setup.py`, while the check is disabled by default.

Update style check tools to the versions compatible with pycodestyle 2.4

---

setup.cfg

[backport] Ignore h5py is warned by Python 3.7

---

chainer/link.py
tests/chainer_tests/test_link_hook.py

This change makes it easier to define original models when their links have `LinkHook`.
One expected usage is below.
```python
class MyModel(chainer.Chain):
def __init__(self, *args, **kwargs):
super(MyModel, self).__init__()
self.linear = L.Linear(10).add_hook(SomeLinkHook)
self.conv = L.Convolution2D(10, 3, 1, pad=1).add_hook(AnotherLinkHook)
...
```

Change link.add_hook to return self

---

setup.cfg

[backport] Fix regex of protobuf modules warned by Python 3.7

---

chainer/links/loss/hierarchical_softmax.py
tests/chainer_tests/links_tests/loss_tests/test_hierarchical_softmax.py

[backport] Support default dtype in `L.BinaryHierarchicalSoftmax`

---

docs/source/_static/robots.txt

After merging this we need to setup redirect from `/robots.txt` to `/en/latest/_static/robots.txt` in Cloudflare.

Add robots.txt to hide older versions from search results

---

chainerx_cc/chainerx/array_test.cc
chainerx_cc/chainerx/backward.cc
chainerx_cc/chainerx/backward.h
chainerx_cc/chainerx/backward_test.cc
chainerx_cc/chainerx/error.h
chainerx_cc/chainerx/python/error.cc

If a fallback backward function returns gradients with mismatched dtype, shape, etc., it's extremely difficult to spot the erroneous code, as the stack trace does not go through any Python code.

Improve gradient mismatch error

---

chainerx_cc/scripts/ci/jenkins/run_docker.sh

Allows explicity specifying the repo root from Jenkins build configuration.

Fix jenkins script to allow explicit repo root

---

chainerx_cc/CMakeLists.txt

I'd like to specify `-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0` to avoid ABI conflict with other libraries.

Do not overwrite CMAKE_CXX_FLAGS a user specified

---

examples/text_classification/train_text_classifier.py

This PR adds test mode to text classification example so that we can reasonably perform CI on it.
This PR is mutually dependent on https://github.com/chainer/chainer-test/pull/472 .

Add test mode to text classification example

---

tests/chainerx_tests/unit_tests/test_array.py

A new error type `chainerx.GradientError` was introduced but some Python tests were not updated accordingly. This PR fixes those failing tests.

Fix to test against new chainerx.GradientError

---

chainer/testing/array.py

Now that `__setitem__` workaround has been implemented, this function can rely on it.

Resolve _as_noncontiguous_array workaround for ChainerX

---

chainerx_cc/README.md
examples/pix2pix/README.md

- Fixed a link from chainerx_cc/README.md.
- Removed a link to Japanese README. It seems there is
https://github.com/pfnet-research/chainer-pix2pix/blob/master/README-ja.md
but it'd be better to just drop the link as documents in
other repositories can easily get stale.
I wrote an incomplete script so other markdown files are
probably OK.
https://github.com/shinh/test/blob/master/check_md_links.rb

Fix a couple of broken links from markdown files

---

chainerx_cc/examples/imagenet/resnet50.py
chainerx_cc/examples/imagenet/train_imagenet.py

I noticed that some TODOs can already be resolved.
1. chx.array(np.array(x)) => chx.array(x)
2. Use `no_backprop_mode` instead of `no_grad`
3. Use `chx.array(0)` instead of `chx.zeros(())`.

Remove some TODOs of the chainerx resnet example 

---

chainer/testing/backend.py

Fix `testing.BackendConfig` so that it can be used as a context manager multiple times.
Previously, the following code caused an error:
```
a = chainer.testing.BackendConfig({'use_cuda': True})
with a:
with a:
pass
```
```
...
File "cupy/cuda/device.pyx", line 113, in cupy.cuda.device.Device.__exit__
IndexError: pop from empty list
```

Fix `testing.BackendConfig` context for repeated use

---

chainerx_cc/third_party/pybind11.cmake

v2.2.3 can cause deprecation warning for `PyThread_create_key` at `include/pybind11/detail/internals.h:82:34`.
(fixed in https://github.com/pybind/pybind11/pull/1454)

Update pybind dependency to v2.2.4

---

chainerx_cc/chainerx/python/routines.cc
tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py

Fix scalar handling of `indices_and_sections` in `chainerx.split`

---

chainer/function_node.py
tests/chainer_tests/functions_tests/activation_tests/test_prelu.py
tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py

In ChainerX FunctionNode fallback, type mismatch will happen if the function assigns an array as its attribute.
This PR implements automatic conversion of such attributes.

`FunctionNode` automatic fallback of array attributes in forward

---

chainer/functions/array/cast.py
tests/chainer_tests/functions_tests/array_tests/test_cast.py

 Fix `F.cast` gradient for casts between the same dtypes 

---

docs/source/index.rst

Replaces "Documents" with "Documentation".

Fix wording in documentation

---

chainer/backends/cuda.py

On an environment CuPy is not installed, the following code has caused error.
```python
from chainer.backends import cuda
@cuda.fuse
def f(x, y):
return x + y
x = np.array([1,2,3])
y = np.array([1,2,3])
print(f(x, y))
```
```
File "fusesample.py", line 10, in <module>
print(f(x, y))
TypeError: <lambda>() takes 1 positional argument but 2 were given
```

Fix bug when CuPy not installed and cuda.fuse decorator used without parenthesis

---

chainer/backends/cuda.py

[backport] Fix bug when CuPy not installed and cuda.fuse decorator used without parenthesis

---

.gitignore

I made `docs/source/chainerx/reference` to be ignored.

ignore chainerx reference generated doc

---

chainer/functions/array/cast.py
tests/chainer_tests/functions_tests/array_tests/test_cast.py

[backport]  Fix `F.cast` gradient for casts between the same dtypes 

---

.gitignore

Currently, `.gitignore` includes `docs/source/reference/util/*.rst` as files to be ignored.

Fix gitignore to avoid ignoring some necessary files

---

chainerx_cc/chainerx/python/core_module.cc

As pybind uses `std::free` to free the docstrings, we should use `std::malloc` to allocate them.
https://github.com/pybind/pybind11/blob/e2b884c33bcde70b2ea562ffa52dd7ebee276d50/include/pybind11/pybind11.h#L411

Fix ChainerX Python docstring allocation issue

---

chainerx_cc/third_party/gsl-lite.cmake

Updates gsl-lite, which is required for OSX (AppleClang) support.

Update gsl-lite to v0.32.0

---

chainer/links/model/vision/resnet.py

This fixes #5700.
Test `tests/chainer_tests/links_tests/model_tests/test_vision.py` passes regardless of this fix.
Is there any good idea to add test without need of pretrained model and image?

fix usage of downsample_fb in resnet

---

chainer/datasets/pickle_dataset.py
chainer/function_hooks/cupy_memory_profile.py
chainer/function_hooks/debug_print.py
chainer/function_hooks/timer.py
chainer/training/extensions/progress_bar.py

[backport] Add `hasattr` check to user-specified `flush` call to file-like objects.

---

chainer/functions/loss/huber_loss.py

Removes an unnecessary cast pointed out at https://github.com/chainer/chainer/issues/5812#issuecomment-445548380
Rel. #5813

Remove unnecessary cast in `F.huber_loss`

---

chainer/functions/array/spatial_transformer_sampler.py
tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py

This PR follows #4582, generalize `F.spatial_transformer_sampler` to support all float dtypes.

Support all float dtypes in `F.spatial_transformer_sampler`

---

chainerx_cc/chainerx/routines/math.cc

`out` is a `const` variable (because it's a capture).
clang-tidy complains about moving from `const`.
Introduced in #5800.

Fix clang-tidy error

---

chainer/functions/connection/convolution_2d.py
chainer/functions/connection/convolution_nd.py
chainer/functions/connection/deconvolution_2d.py
chainer/functions/connection/deconvolution_nd.py

Backport of this commit to the master: e3fbae6cd7bca33381aa5eb269bf175accc26eb2, which was a part of #5725.

[v5] Document optional arguments as `None`

---

README.md

It seems that the stable version is wrong in the `README.md` file of `master` branch, though it is actually correct in the `v5` branch.
Just a simple fix.

Correct the stable version in master branch

---

docker/intel/python3/Dockerfile
docker/python3/Dockerfile

Closes #5878.
Confirmed that:
* `python3 train_mnist.py --device cuda:0` work on CUDA container
* `python3 train_mnist.py --device native:0` work on Intel container

Enable ChainerX in docker image

---

chainer/functions/normalization/local_response_normalization.py

Current implementation of `LocalResponseNormalization` is based on obsolete `chainer.Function` class.
This pull request changes it to be based on `chainer.FunctionNode`.

LocalResponseNormalization -> FunctionNode implementation

---

chainer/datasets/sub_dataset.py
tests/chainer_tests/datasets_tests/test_sub_dataset.py

[backport] Accept splitting at the tail of dataset in `split_dataset`

---

chainer/links/loss/crf1d.py
tests/chainer_tests/links_tests/loss_tests/test_crf1d.py

Currently, the parameter of CRF1d is initialized by zero.
But this parameter could be initialized randomly.
There are some example using normal distribution ([1]) and uniform distribution ([2] and [3]).
So, in this PR, I change links.loss.CRF such that it accept the attribute `initialW`.
---
[1]: http://pages.cs.wisc.edu/~jerryzhu/cs769/CRF.pdf
[2]: https://github.com/glample/tagger/blob/master/model.py#L285
[3]: https://github.com/glample/tagger/blob/master/utils.py#L44
[ 1 ]: http://pages.cs.wisc.edu/~jerryzhu/cs769/CRF.pdf

Support custom initializer in links.CRF1d

---

docs/source/reference/static_graph.rst
docs/source/reference/static_graph_design.rst

Fixes #5880.
Moves the autosummary to "design" page to "usage" page.
Also includes some markup fixes.

Fix `static_graph` module path in documentation

---

docs/source/examples/mnist.rst
docs/source/examples/train_loop.rst
docs/source/guides/functions.rst
docs/source/guides/links.rst

I found that `.data` is discouraged but is used in many places in the doc.
Hence I just changed them to `.array`, in `Guides` and `Examples` documentation. Hope this can help improve the consistency of the doc.

Change `.data` to `.array` in Guides and Examples docs

---

tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py

Add test for the cupy backend.
ChainerX is not supported.

Add test for conveter device argument in Evaluator

---

setup.py

These packages are not (no longer?) used in each CI.

Remove some CI requirements

---

docs/source/conf.py

Currently docs cannot be built in non-editable installation.
This fix allows that by setting an environment variable.
```
$ cd docs
$ CHAINER_DOCS_SKIP_LINKCODE=1 make html
```

Allow skipping linkcode in docs with environment variable

---

chainerx_cc/CMakeLists.txt
chainerx_cc/cmake/third-party.cmake
chainerx_cc/third_party/gsl-lite.cmake
chainerx_cc/third_party/gtest.cmake
chainerx_cc/third_party/optional-lite.cmake
chainerx_cc/third_party/pybind11.cmake

suggested by gtest:
https://github.com/google/googletest/commit/c45631823c983935d228557b124eff05263b2660
This change makes it possible for other projects to use
ChainerX as a cmake sub-directory.

Update third-party.cmake to follow the recent way

---

chainer/functions/activation/leaky_relu.py
tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py

When slope = 0, `F.leaky_relu` backpropagated all gradients, even at x < 0. This PR fixes this.
The following script shows the problem.
```python
import chainer
x = np.arange(-5, 5, dtype=np.float32)
v = chainer.Variable(x)
l = F.sum(F.leaky_relu(v, slope=0.0))
l.backward()
print(v.grad)
```
```output
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```
Note that this PR is not about the behavior at `x = 0`, contrary to #5876 #5877.

Fix broken `F.leaky_relu` grad when slope = 0

---

chainerx_cc/chainerx/cuda/cuda_backend_test.cc
chainerx_cc/chainerx/cuda/cuda_device_test.cc
chainerx_cc/chainerx/cuda/memory_pool.cc

Though we have not clarified the difference between unified
memory and normal GPU memory, a couple of performance
regressions were observed:
- A significant regression was observed when GPU memory usage
is close to the limit. It looked like some GPU memory was
migrated to the host even though GPU should have enough
memory.
- A tiny regression was also observed for simple element-wise
ops even when GPU memory usage is low.
The latter can be reproduced by
https://github.com/shinh/test/blob/master/unified_mem_perf.sh
https://github.com/shinh/test/blob/master/unified_mem_perf.py
on both p100 and v100.
We might eventually re-consider enabling unified memory, but
we are using no unified memory specific feature yet and I
guess this should be an opt-in feature like cupy's.

Stop using unified memory by default

---

chainerx_cc/chainerx/context.cc
chainerx_cc/chainerx/context_testdata/backend0.cc
chainerx_cc/chainerx/context_testdata/backend1.cc
chainerx_cc/chainerx/cuda/cuda.cc
chainerx_cc/chainerx/cuda/cuda.h
chainerx_cc/chainerx/cuda/cuda_backend.cc
chainerx_cc/chainerx/cuda/cuda_backend.h
chainerx_cc/chainerx/float16_test.cc
chainerx_cc/chainerx/native/native_backend.cc
chainerx_cc/chainerx/python/chainer_interop.cc
chainerx_cc/chainerx/python/core_module.cc
chainerx_cc/scripts/run-clang-tidy.sh

Fixes warnings on clang-tidy 6.0.0.
* We started to use `gsl::owner` for raw pointers.
* `cppcoreguidelines-owning-memory` is ignored for test files, because googletest causes errors.

Fix clang-tidy warnings on clang-tidy 6

---

.travis.yml
scripts/ci/travis/run-tests.sh
setup.py

Adds C++ linter checks (clang-tidy, clang-format, cpplint) in Travis CI matrix.
Depends on: ~#5859~, ~#5868~, ~#5901~, ~#5933~

Add C++ linter checks in Travis CI 

---

tests/chainer_tests/functions_tests/loss_tests/test_ctc.py

This PR adjusts testing tolerance of `F.connectionist_temporal_classification` with `float16` data.

Adjust testing tolerance of F.connectionist_temporal_classification

---

chainerx_cc/chainerx/macro.h
chainerx_cc/chainerx/python/CMakeLists.txt
chainerx_cc/chainerx/python/testing/device_buffer.cc

Fix that's required to correctly bind ChainerX custom exceptions on macOS (libc++).
More precisely, custom exceptions raised by the C++ code were treated as different types from the ones registered here https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/python/error.cc due to the default visibility configuration of pybind11 which is `hidden` and set here https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/common.h#L24. 
This PR changes the visibility to `default` and also includes changes to utilize `pybind11_add_module` which also seems to be required.
"Problems with C++ exceptions (please read!)" in https://gcc.gnu.org/wiki/Visibility

Fix visibility for pybind exception registration for macOS

---

chainer/link.py

Remove `@overload` annotations outside the stub files because it isn't supported in Python 3.5.1. It fixes #5959.
```bash
$ pyenv local 3.5.1
$ pip install typing typing_extensions
$ python
Python 3.5.1 (default, Nov 15 2018, 17:50:51) 
[GCC 5.5.0 20171010] on linux
>>> import chainer
>>> 
$ pyenv local 3.6.6
$ pip install typing typing_extensions
$ python
Python 3.6.6 (default, Jul 26 2018, 11:12:32) 
[GCC 5.4.0 20160609] on linux
>>> import chainer
>>> 
```

Remove @overload annotations outside the stub files

---

tests/chainer_tests/initializer_tests/test_normal.py
tests/chainer_tests/initializer_tests/test_orthogonal.py
tests/chainer_tests/initializer_tests/test_uniform.py

Test `scale` arg of `chainer.initializers`.
This PR adds statistical tests ~and fixes bias of sign of `Orthogonal` initializer~.

Test statistics of initializers

---

chainer/training/extensions/evaluator.py
tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py

Adding a comment for reset, as part of clarifying #5793

Warn if `reset` method is not implemented in an iterator

---

.travis.yml
scripts/ci/travis/run-tests.sh

Adds a new Travis matrix: macOS x ChainerX.
Only the native backend will be tested.
Note: Error fixes can be done in separate PRs I think. Specifically #5776 will be required.

Add Travis matrix for macOS ChainerX tests

---

chainer/functions/loss/sigmoid_cross_entropy.py
chainer/functions/loss/softmax_cross_entropy.py

Fix doc of `F.softmax_cross_entropy` on output shape with `reduce=no`

---

setup.py

Travis tests for v5 are failing because pytest-cov 2.6.1 requires pytest>=3.6

[v5] Fix pytest plugin version

---

chainer/functions/loss/sigmoid_cross_entropy.py
chainer/functions/loss/softmax_cross_entropy.py

[backport] Fix doc of `F.softmax_cross_entropy` on output shape with `reduce=no`

---

chainer/functions/connection/n_step_rnn.py
tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py

Close #5943.
This PR fix `F.n_step_rnn` to raise an appropriate error on attempting backward computation in testing mode.

Raise an appropriate error on cuDNN RNN backward in testing mode

---

chainer/testing/array.py
tests/chainer_tests/testing_tests/test_array.py

Currently `testing.assert_allclose` can show an error that is within the tolerance.
That's because the element to show is chosen by using `numpy.argmax(err)`, taking only the absolute error into account.
This PR also improves the message so that both relative and absolute errors are shown.

Fix error message of `testing.assert_allclose`

---

chainer/functions/activation/elu.py
tests/chainer_tests/functions_tests/activation_tests/test_elu.py

When `alpha >= 0.0`, `F.elu` can modified to retain output. Gradient computation becomes easier.
It might degrade the precision of gradients, but it won't be worse than `F.sigmoid`, `F.tanh`, `F.swish` or `F.softplus`. [TF also computes gradients from the output.](https://github.com/tensorflow/tensorflow/blob/96237f7b7ae6b7b8a2cbcf6d64312906b96f060b/tensorflow/core/kernels/relu_op_functor.h#L149)

improve `F.elu` memory consumption by retaining output

---

chainer/links/connection/n_step_lstm.py
chainer/links/connection/n_step_rnn.py

Fix document in NStepLSTM/NStepRNN.
Before
```
Its shape is (L_t, I), where L_t is the length of a sequence for time t
```
After
```
Its shape is (L_i, I), where L_i is the length of a sequence for batch i 
```

Fix document in NStepLSTM/NStepRNN

---

chainer/functions/math/basic_math.py

`numpy.asscalar` was deprecated in NumPy 1.16.

Avoid deprecated `numpy.asscalar`

---

chainer/training/trainer.py
chainer/training/triggers/manual_schedule_trigger.py
tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py

This PR is separated from #5565.
New optional property `finished` in `trigger` object helps to avoid unnecessary call of `Extension.initialize`.
The main target of this `finished` property is `once_trigger` in PR #5565, but the PR is now working.
So I first apply it to `manual_schedule_trigger` instead.
TODO:

Add optional property `finished` to trigger object

---

chainerx_cc/chainerx/backward.cc
chainerx_cc/chainerx/backward.h
chainerx_cc/chainerx/backward_context.cc
chainerx_cc/chainerx/backward_context.h
chainerx_cc/chainerx/backward_test.cc

This PR introduces `void Backward(const std::vector<ConstArrayRef>& inputs, ...)` which is similar to `chainer.grad` but does not return anything but instead sets the gradients of the specified inputs. It's better keep the behavior consistent with the previous `Backward` since a graph is consumed, in contrast to Chainer which allows repeated backprops. Basically, a function to extract a subgraph is introduced and this subgraph is checked for at certain places in backward to skip computations that are not required.
1. Traverse backwards (from given outputs) to create an ArrayNode -> OpNode mapping where the ArrayNode is an input to the OpNode.
2. Traverse forwards (from given inputs) to extract a subgraph (OpNode -> boolean "input included in subgraph" flags).
3. Then standard `Backward` …

ChainerX backward w.r.t. inputs (C++ chainerx.grad) 

---

chainerx_cc/chainerx/cuda/cuda_runtime.cc
chainerx_cc/chainerx/cuda/elementwise.cuh
chainerx_cc/chainerx/cuda/reduce.cuh
chainerx_cc/chainerx/macro.h

Post macro comment for consistency

---

chainer/function_hooks/timer.py
tests/chainer_tests/function_hooks_tests/test_timer.py

time.time() of python2.7 on Windows is 16 milliseconds precision.
- use more precise timer
- use assert not self.assert*
ref: https://stackoverflow.com/questions/1938048/high-precision-clock-in-python
rel: https://github.com/chainer/chainer/pull/5842#issuecomment-452553988

Use more precise timer in funciton_hooks/timer.py

---

chainer/functions/loss/ctc.py
tests/chainer_tests/functions_tests/loss_tests/test_ctc.py

[backport] Support all float dtypes in `F.connectionist_temporal_classification`

---

chainer/sequential.py
tests/chainer_tests/test_sequential.py

[backport] Add copyparams method to Sequential

---

chainer/testing/backend.py

#5904 has caused `testing.attr.multi_gpu` (put by `inject_backend_tests`) to ignore `CHAINER_TEST_GPU_LIMIT` environment variable. This PR fixes it.
(just for reference)
Another fix would be to change `unittest.skipIf` to `pytest.mark.skipif` at this line (I don't know why):
https://github.com/chainer/chainer/blob/9f243e66fc5b6a337273d965b431644d846a9cc7/chainer/testing/attr.py#L60

Fix `inject_backend_tests` `multi_gpu` test mark

---

chainer/links/theano/theano_function.py
chainer/testing/__init__.py
chainer/testing/doctest_helper.py
chainer/testing/helper.py
docs/source/conf.py
docs/source/guides/gpu.rst

Currently doctest can't be run on a single-GPU environment.
As we have increased the required sphinx version in #6001, we can use `:skipif:` option now.
I think `testing.is_requires_satisfied()` can be removed in favor of `doctest_helper.skipif_requires_satisfied()`. It has not been released yet.

Allow doctest to run in single-GPU environment

---

chainerx_cc/chainerx/cuda/cuda_device/activation.cu

Use `CudaSetDeviceScope` instead of `cudaSetDevice()`.

Fix `chainerx.maximum` to restore CUDA device

---

chainer/functions/array/split_axis.py
setup.cfg
tests/chainer_tests/functions_tests/array_tests/test_split_axis.py

This PR changes only tests, while defining `class ExperimentalWarning(FutureWarning): pass` might resolve some other issues.

Do not ignore FutureWarning other than experimental features

---

chainer/testing/parameterized.py

Previously parameterized class names are difficult to interpret.
Previous:
```
tests/chainer_tests/test_variable.py::TestBackwardAccumulate_param_0::test_backward_accumulate_cpu
```
This PR:
```
tests/chainer_tests/test_variable.py::TestBackwardAccumulate_param_0_{'in0_isvar_hasgrad': (False, False), 'in1_isvar_hasgrad': (False, False), 'in2_isvar_hasgrad': (False, False), 'var_mapping': (0, 1, 2)}::test_backward_accumulate_cpu
```
Note that Python classes and functions can have any name represented by a string (including spaces, symbols, etc.), with unlimited length.

Encode parameters in parameterized class name

---

chainerx_cc/chainerx/cuda/cuda_device.cc
chainerx_cc/chainerx/cuda/cuda_device.h
chainerx_cc/chainerx/cuda/cuda_device/memory.cc

For transfer from the host memory to the pinned memory, `std::memcpy` is faster than `cudaMemcpyAsync`.
To prevent the pinned memory from being freed before asynchronous operations are finished, `MemoryKeeper` is introduced. 
```
x = [numpy.zeros((10000,), numpy.float32)] * 100
```
* ChainerX (before)
1445us: `chainerx.asarray(x, device='cuda:0')`
* ChainerX (this PR)
1095us: `chainerx.asarray(x, device='cuda:0')`
* (For reference) CuPy
1088us: `cupy.asarray(x)`

 Avoid `cudaMemcpyAsync` for pinned memory for faster host-to-device transfer

---

chainer/functions/__init__.py
chainer/functions/array/as_strided.py
docs/source/reference/functions.rst
tests/chainer_tests/functions_tests/array_tests/test_as_strided.py

This PR is for #5036 and #5796.
This feature (F.as_strided) strides array like `numpy.lib.stride_tricks.as_strided`, but this function is itemsize-agnostic (i.e. stride size is given in unit of steps, not bytes).
This is a transported code from pytorch. The algorithm and API is the same.
This feature will be helpful in the implementation of F.stft.
If this feature would be accepted, I will create a PR of F.stft.

Add F.as_strided

---

chainer/_backend.py
chainer/backends/_chainerx.py
chainer/backends/_cpu.py
chainer/backends/cuda.py
chainer/backends/intel64.py
chainer/functions/activation/clipped_relu.py
chainer/gradient_check.py
chainer/testing/__init__.py
chainer/testing/array.py
chainer/testing/function.py
chainer/testing/parameterized.py
chainer/utils/__init__.py
chainer/utils/error.py
chainerx/__init__.py
chainerx/_fallback_workarounds.py
docs/source/reference/check.rst
tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
tests/chainer_tests/functions_tests/activation_tests/test_relu.py
tests/chainer_tests/functions_tests/array_tests/test_hstack.py
tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
tests/chainer_tests/functions_tests/connection_tests/test_linear.py
tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
tests/chainer_tests/testing_tests/test_function.py

This is an attempt to ease writing tests for functions.
When you write a new function, you need to write 3 things in the corresponding test:
* `forward`: Forward implementation which simply calls the new function.
* `forward_expected`: Forward reference implementation that returns the expected outputs.
* `generate_inputs`: Generates input arrays to test.
(this feature has been removed from this PR)
~To easily check numerical stability, the following environment variables can be used (set large number to repeatedly run the corresponding test)~
* ~```CHAINER_TEST_FORWARD_REPEAT```~
* ~```CHAINER_TEST_BACKWARD_REPEAT```~
* ~```CHAINER_TEST_DOUBLE_BACKWARD_REPEAT```~
* (merged) ~Needs https://github.com/cupy/cupy/pull/580 to run some example tests~
* (merged) ~Depends on #3551 …

`FunctionTestCase` for function tests

---

chainer/utils/walker_alias.py

Fix stochastic failure in `WalkerAlias`

---

MANIFEST.in

Fixing:
```
➜  Chainer git:(master) python setup.py build install > /dev/null
warning: no files found matching 'chainerx_cc/README.txt'
warning: no files found matching 'chainerx_cc/LINCENSE.txt'
```

Fix manifest typos

---

chainer/testing/function.py
tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
tests/chainer_tests/functions_tests/activation_tests/test_relu.py
tests/chainer_tests/functions_tests/array_tests/test_hstack.py
tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py

This is a temporary workaround to skip ChainerX float16 tests in function tests.
This workaround should be removed after ChainerX supports float16 (related: #5845).

Skip ChainerX float16 tests when FunctionTestCase is used

---

chainer/dataset/__init__.py
chainer/dataset/convert.py
chainer/training/updaters/standard_updater.py
docs/source/reference/datasets.rst
tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py

~Introduces `chainer.dataset.Converter` class.~
Introduces `chainer.dataset.converter` decorator.
In the existing converter convention, users can make their custom converters by defining a function with two arguments: a batch and a device, where "device" is an integer specifying either CPU (-1) or CUDA devices (>=0).
Now Chainer has introduced `chainer.Device` class.
To support this, a new interface for converters is required becaue existing converter functions can't handle this class.
In this PR, a new decorator `chainer.dataset.converter` is being introduced. This decorator marks the subject converter to indicate that it supports `chainer.backend.Device` argument. If `int` is given when the converter is being called, the decorator converts the argument to `chainer.backend.Device` …

Converter decorator for ChainerX device support

---

chainer/training/extensions/__init__.py
chainer/training/extensions/variable_unchain.py
chainer/training/trainer.py
docs/source/reference/training.rst

When the `configuration.config.keep_graph_on_report` flag is turned on, the computational graph created by the updater is kept *and seems not to be released* in current implementation.
I added the `unchain_backward()` after all extensions are executed.

Unchain all variables after running extensions

---

tests/chainermn_tests/communicator_tests/test_communicator.py
tests/chainermn_tests/conftest.py

This PR fixes chainermn tests.
The causes of the chainermn test clash are here
1.  use `MultiprocessIterator` without forkserver
2. Test skip mistake

Fix chainermn tests

---

chainerx_cc/chainerx/python/cuda/cuda_module.cc

Fixes `NOLINT` comment for a couple of `reinterpret_cast`s.

Add NOLINT to reinterpret cast

---

chainer/testing/parameterized.py

Fixes #6059.
The format and the hard limits are rather arbitrarily decided by intuition.
Perhaps there's room for discussion (or not).
`tests/chainer_tests/datasets_tests/test_concatenated_dataset.py`
```
tests/chainer_tests/datasets_tests/test_concatenated_dataset.py::TestConcatenatedDataset_param_0_{datasets=(array([[[[9.00619850e-01, 9.99080770e-01, 9.010....87048914,
0.76144522, 0.80512511]]]]))}::test_concatenated_dataset PASSED
tests/chainer_tests/datasets_tests/test_concatenated_dataset.py::TestConcatenatedDataset_param_0_{datasets=(array([[[[9.00619850e-01, 9.99080770e-01, 9.010....87048914,
0.76144522, 0.80512511]]]]))}::test_concatenated_dataset_slice PASSED
tests/chainer_tests/datasets_tests/test_concatenated_dataset.py::TestConcatenatedDataset_param_1_{datasets=(array([[[[0.384 …
```

Limit the length of parameterized test class name

---

chainer/link.py
chainer/links/theano/theano_function.py
tests/chainer_tests/test_link.py

When implementing a link, it's very easy to forget `super().__init__()`, and that results in difficult to understand errors (the error could be delayed, to make things worse).
```py
import chainer
import numpy
class A(chainer.Link):
#super().__init__()
self.a = chainer.Parameter(1, (2, 3))
def forward(self, x):
return x * self.a
l = A()
x = numpy.ones((2, 3), numpy.float32)
y = l(x)
```
```
AttributeError: 'A' object has no attribute '_device'
```
This PR turns the errors into more easy to understand one, and raise it earlier. 
```
RuntimeError: Link.__init__() has not been called.
```

Enforce `Link.__init__` in subclasses

---

chainerx_cc/chainerx/cuda/memory_pool.cc
chainerx_cc/chainerx/cuda/memory_pool_test.cc

Fixes the first problem of #5991

Fix thread safety of CUDA memory pool FreeUnusedBlocks

---

chainerx_cc/chainerx/python/array_index.cc
tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py

Fixes #5897
Before (using the script in #5897)
```
numpy array: 0.5639582940057153
cupy array: 2.305104177998146
chainerx (native) array: 84.79587393000838
chainerx (cuda) array: 101.06928799199522
genuine chainerx impl with shuffle (on cuda): 113.26358407300722
```
This PR
```
numpy array: 0.5752583239955129
cupy array: 2.019738340997719
chainerx (native) array: 2.341369660003693
chainerx (cuda) array: 2.20467715599807
genuine chainerx impl with shuffle (on cuda): 113.40527645299153
```

Support NumPy integers in `chainerx.ndarray.__getitem__`

---

chainerx_cc/examples/mnist_py/train_mnist.py

Fix python 3.5 incompatibility in Chainer X train_mnist.py example

---

chainer/variable.py
chainerx/__init__.py
chainerx/_device.py
chainerx_cc/chainerx/python/array.cc
chainerx_cc/chainerx/python/device.cc
tests/chainerx_tests/unit_tests/test_array.py
tests/chainerx_tests/unit_tests/test_device.py

Fixes #5916
Makes `chainerx.Device` and `chainerx.ndarray` picklable.

Fix pickling of ChainerX link

---

chainerx_cc/chainerx/python/array_index.cc

`py::isinstance<T>` is preferred over `check_`.

Use `py::isinstance` to check types

---

examples/seq2seq/seq2seq.py

This PR is quick fix for a bug in the seq2seq example. The `__call__` method of a trainer extension defined in the seq2seq example is mistakenly renamed to `forward` by this commit for LinkHook: https://github.com/chainer/chainer/pull/4912/files#diff-b41c7c0a2fadcae4e15f628ccfe20936L139
I appreciate that @niboshi and @asi1024 found this bug. Thanks both, sincerely.
I think the example tests have some room for improvement to be able to check this kind of bugs.

Fix seq2seq example

---

chainer/backend.py
chainer/function_node.py
chainer/optimizer.py
chainer/variable.py
tests/chainer_tests/test_variable.py

`parse_kwargs` is essential for our user's experience but generates non-trivial overhead especially in hotspots. One problem is that this validation mechanism is hard to optimize or remove as discussed in #6030.
This patch introduces `_unsafe_variable`, which is an optimized factory method of `Variable` only for internal use. It skips the validation to reduce the overhead generated in the framework like `FunctionNode.apply` ([here](https://github.com/chainer/chainer/blob/88d0d1ae50d7fc2592672c19d9f639406873c42f/chainer/function_node.py#L275-L278)) and `UpdateRule.update_core_chainerx` ([here](https://github.com/chainer/chainer/blob/88d0d1ae50d7fc2592672c19d9f639406873c42f/chainer/optimizer.py#L308)).
It also fixes `get_array_module` to reduce the number of function calls.
Note: It is …

Add `Variable._init_unchecked()` static method for faster instantiation

---

chainer/training/updaters/multiprocess_parallel_updater.py

In some environment, the second import failure of CuPy may raise `AttributeError` instead of `ImportError` if CUDA driver DLLs are unavailable.
```py
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
>>> import cupy
File "C:\Development\venv\kmaehashi-test\lib\site-packages\cupy\__init__.py", line 11, in <module>
from cupy import core  # NOQA
File "C:\Development\venv\kmaehashi-test\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
from cupy.core import core  # NOQA
File "cupy\core\core.pyx", line 1, in init cupy.core.core
File "C:\Development\venv\kmaehashi-test\lib\site-packages\cupy\cuda\__init__.py", line 4, in <module>
from …
```

Fix cupy import failure detection

---

chainer/utils/_collections.py
chainer/variable.py

This PR wraps a use of `collections.OrderedDict` in order to address a memory issue with Python 2.
Split from #5274.

Fix memory leak during backprop in Python 2

---

chainerx_cc/CMakeLists.txt

This should have been done in
https://github.com/chainer/chainer/commit/59cc3df5daf1fe9a6563221dc92baab20d31956d

Use `CMAKE_CURRENT_BINARY_DIR` in `CMakeLists.txt`

---

scripts/ci/steps.sh

Remove legacy `CHAINERX_CUDA_MULTITHREAD_TEST_SEGV_WORKAROUND` from Jenkins script

---

examples/mnist/train_mnist_custom_loop.py

For consistency with other examples.

Fix iterator syntax in MNIST custom loop example

---

chainer/functions/activation/log_softmax.py
chainer/functions/activation/softmax.py
chainer/functions/connection/n_step_gru.py
chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py
chainer/functions/normalization/batch_normalization.py
chainer/functions/pooling/average_pooling_nd.py
chainer/functions/theano/theano_function.py
chainer/initializers/normal.py
chainermn/functions/batch_normalization.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
tests/chainer_tests/link_hooks_tests/test_timer.py

`xp` can be `chainerx`, too.
Testing `xp is numpy` for cupy should be wrong.

Do not compare `xp` with `numpy` for cupy code path

---

chainer/links/model/classifier.py

[backport] Fix typo in `classifier.py`

---

docs/source/install.rst

Closes #6080.
(c.f. CuPy: https://github.com/cupy/cupy/pull/1986)

Document NumPy 1.16 support

---

tests/chainer_tests/functions_tests/loss_tests/test_triplet.py

Fix tolerance and numeric grad precision in `F.triplet` test

---

tests/chainer_tests/functions_tests/loss_tests/test_triplet.py

[backport] Fix tolerance and numeric grad precision in `F.triplet` test

---

chainer/function_node.py
tests/chainer_tests/test_function_node.py

Fix `FunctionNode.get_retained_outputs` to return `()` if no output is retained

---

.travis.yml

Related to Python 3.4 support drop https://github.com/chainer/chainer/issues/6131.
This PR simply removes the Ubuntu Py34 job from the Travis matrix. It is maybe worth discussing if we should bump the Python version to 3.5 of this job instead of removing it, to test Chainer without ChainerX.

Remove Travis Ubuntu Py34 job

---

chainer/function.py
chainer/function_node.py
tests/chainer_tests/test_backprop.py

This PR originally intended to support `None` as `FunctionNode` inputs in ChainerX (issue: #6120) , but during that I found that existing semantics should also change.
Previously, `get_retained_{in,out}puts` returns `Variable(None)` if the input/output is `None`.
In this PR it has changed to return `None`.
(Depends on #6118)

Fix `get_retained_{in/out}puts` to return `None` for `None` inputs/outputs

---

setup.py

Since `pytest==4.2.0`, collection of tests has become slow (it gets slower and slower over time) and times out certain CI builds. Pinning `pytest` to the previous versions gets around the problem but I'm not sure it's the right thing to do.

Fix unit test collection timeout

---

chainer/functions/activation/rrelu.py
tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py

#5619 broke `_RReLUGrad.backward`.
```
>>> x = chainer.Variable(np.random.randn(2, 3).astype('f'))
>>> y = F.rrelu(x)
>>> y.grad = np.random.randn(2, 3).astype('f')
>>> y.backward(enable_double_backprop=True)
>>> x.grad_var.grad = np.random.randn(2, 3).astype('f')
>>> x.grad_var.backward()
File "/Users/tos/GitHub/chainer/chainer/variable.py", line 1386, in backward
_backprop_to_all([self], retain_grad, loss_scale)
File "/Users/tos/GitHub/chainer/chainer/variable.py", line 1577, in _backprop_to_all
func, target_input_indexes, out_grad, in_grad)
File "/Users/tos/GitHub/chainer/chainer/_backprop_utils.py", line 116, in backprop_step
target_input_indexes, grad_outputs)
File …
```

Fix double-backprop of `F.rrelu`

---

chainer/testing/function.py

rel: #6071 
This PR makes it easier to rewriting connection_tests.
As some connection_tests use `x_dtype` and `W_dtype` instead of `dtype`, it'll be more handy to
skip chainerx if x_dtype and/or W_dtype are `numpy.float16`.
ref:
https://github.com/chainer/chainer/blob/24705fb771bf3df8a954724c5ab567d2f2248456/tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py#L24-L45
https://github.com/chainer/chainer/blob/12535b6279fb1ce55acc48e5c52ec68af9c23a05/tests/chainer_tests/functions_tests/connection_tests/test_linear.py#L21-L28

add x_dtype and W_dtype to the if statement of FunctionTestCase._skip_if_chainerx_float16

---

chainer/optimizer.py

Currently, `update_core_chainerx` in `Optimizer` class assumes that state arrays are updated in-place, but `optimizers.SMORM3` replaces the state arrays instead.

Fix `Optimizer` to convert state arrays back to ChainerX

---

chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py
tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py

Close #5436.
This PR makes RNN and LSTM functions check input size consistency with their input values and weights when using cuDNN.
- `F.n_step_rnn`
- `F.n_step_birnn`
- `F.n_step_lstm`
- `F.n_step_bilstm`

Check input size consistency in RNN and LSTM when using cuDNN

---

docs/source/reference/check.rst

Document `chainer.testing.FunctionTestCase` (#3499) because it is public (from the naming convention).

Add `FunctionTestCase` to documentation

---

chainer/functions/connection/n_step_lstm.py
chainer/functions/connection/n_step_rnn.py
tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py
tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py

[backport] Check input size consistency in RNN and LSTM when using cuDNN

---

scripts/ci/travis/steps.sh

Attempts to fix Travis failure due to unrecognized option `--quiet` to `brew upgrade` (it might be the case that's it's always been unrecognized but silently ignored, until the recent brew refactoring in 2.0.0).

Remove bad brew option from Travis CI

---

examples/seq2seq/seq2seq.py

On Python3, `open` built-in function uses platform dependent encoding when `encoding` parameter is not supplied. This can cause `UnicodeDecodeError` in seq2seq example.
This PR fixes `seq2seq.py` to use `io.open` instead of built-in `open` to supply `encoding` parameter on both Python2 and Python3 environments to make the example work properly.

Fix seq2seq example encoding problem on Python3

---

examples/seq2seq/seq2seq.py

[backport] Fix seq2seq example encoding problem on Python3

---

docs/source/imports.rst

Add imports of initializers and math, required in "Define your own function" examples.
In examples, provided in https://docs.chainer.org/en/stable/guides/functions.html#links-that-wrap-functions, there are two missing imports: `from chainer import initializers` and `import math`.
```
class EltwiseParamProduct(Link):
def __init__(self, shape):
super(EltwiseParamProduct, self).__init__()
self.W = chainer.Parameter(**initializers**.Normal(scale=1.), shape)
def forward(self, x):
return self.W * x
```
```
class Linear(Link):
def __init__(self, in_size, out_size):
super(Linear, self).__init__()
self.W = chainer.Parameter(
initializers.Normal(1. / math.sqrt(in_size)),
(out_size, in_size))
self.b = chainer.Parameter(0, (out_size,))
def forward(self, …
```

Add imports of initializers and math, required in "Define your own function" examples

---

chainerx_cc/chainerx/native/native_device/dot.cc

This change may help for this failure https://github.com/chainer/chainer/pull/6218#issuecomment-463043900.
Although accumulation in `float` on float16 `Dot` offers better accuracy, it requires memory allocation. So I do not include `float` accumulation in this PR.

Use FMA in `NativeDevice::Dot`

---

chainer/functions/connection/n_step_lstm.py
docs/source/examples/seq2seq.rst
examples/seq2seq/seq2seq.py

Fixes the seq2seq example to enable ChainerX devices.
~Depends on #5832.~

ChainerX seq2seq example

---

chainer/functions/pooling/roi_average_align_2d.py
chainer/functions/pooling/roi_max_align_2d.py
tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py

currently, when `spatial_scale > 1.0` is given, the function hangs.

support spatial_scale >= 1.0 in roi_average_align_2d.py

---

chainerx_cc/chainerx/native/native_device/dot.cc

Improvement of #6227. Use single precision arithmetic in half precision `Dot` of the native backend. This PR may improve accuracy and speed. Note that some workspace memory is used.

Use float accumulation in ChainerX float16 `Dot`

---

chainer/functions/activation/relu.py

Chainer can pass dtype hint to CuPy.

Improve `F.relu` performance with CuPy

---

tests/chainer_tests/test_gradient_check.py

Removes unnecessary call redirection.

Cosmetic fix to `test_gradient_check`

---

chainer/__init__.py
chainer/links/activation/maxout.py
chainer/variable.py

Fixes unintentional usage of `is_arrays_compatible()` and replaces with `get_array_types()`.

Fix inappropriate usage of `is_arrays_compatible`

---

chainer/variable.py
tests/chainer_tests/test_variable.py

Fixes #6279 
Introduces `Variable.chx_view()` which returns a view (`chx.ndarray`) of the original array.

Unwrap ChainerX connected array from `Variable`

---

chainer/_backend.py

1.86 us -> 0.54 us (only if `device` is either `CpuDevice` or `Intel64Device`).
```py
with chainer.using_device(device):
pass
```

Improve performance of `using_device` for NumPy and Intel64 devices

---

chainer/iterators/multiprocess_iterator.py

Finalization routine of `MultiprocessIterator` hangs when uncaught exception is triggered. Tested with Python 3.6.6 on Linux x86_64. Even though `with` statement is generally recommended, the hang is undesirable. This PR workaround the issue by skipping `MultiprocessIterator` finalization after `atexit` hook execution.
Such type of a hang occurs if `iterator.__del__` is called when the interpreter finalizing itself. In the following program, probably the traceback held by the exception object defers `__del__` call until the interpreter finalization.
```python
import chainer
class Dataset(chainer.dataset.DatasetMixin):
def __len__(self):
return 100
def get_example(self, i):
return i
def main():
dataset = Dataset()
iterator = chainer.iterators.MultiprocessIterator(dataset, 16, repeat=False, …
```

skip MultiprocessIterator finalization at exit

---

README.md
chainer/datasets/__init__.py
chainer/datasets/kmnist.py
chainer/datasets/kuzushiji_mnist.py
docs/source/reference/datasets.rst
tests/chainer_tests/datasets_tests/test_mnist.py

I'd like to suggest adding the Kuzushiji-MNIST dataset to Chainer.
The Kuzushiji-MNIST dataset is designed to be an
MNIST-like dataset focusing on handwritten Japanese
characters. All data features of KMNIST are identical to
MNIST, such as number of train and test images, image
size, etc with the intent of making it easy to run any
MNIST-based analysis or benchmarks against this new
dataset.
Details available here: https://github.com/rois-codh/kmnist

add Kuzushiji-MNIST dataset

---

chainer/testing/parameterized.py

`testing.parameterize` needs the same fix as 630a2da1cd1b619560dcec015d6bbf9a345e537e.

Fix error message of parameterized test

---

chainer/variable.py

It seems the order is reversed.
But what does this advice mean?
> If the size of this variable accidentally becomes one, set zero to grad.

Fix warning message for backward on a scalar array

---

tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py

Close #6314.
The source of the error: `dtype.type(lower + upper)` in `F.rrelu` is more accurate than `numpy.mean([lower, upper], dtype=dtype)` in the test.
```
>>> np.mean([0.0005, 2.0005], dtype=np.float16)
1.0
>>> np.float16((0.0005 + 2.0005) / 2)
1.001
```

Improve accuracy of test of `F.rrelu`

---

tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py

Applies the function test case https://github.com/chainer/chainer/pull/3499.
~`chainer.Function` also needs automatic attribute fallback #5745 for F.batch_renormalization to support ChainerX.~
`chainer.Function` attribute fallback is implemented in #5828.

Simplify `F.batch_renormalization` test 

---

examples/imagenet/train_imagenet.py

Fix to check `device` is ChainerX device in the ImageNet example correctly. `device` is `chainer.Device` not `chainerx.Device`.

Fix to check chainerx device in ImageNet example

---

chainer/backend.py
chainer/backends/_chainerx.py
chainer/function.py
chainer/function_node.py
chainer/functions/array/get_item.py
chainer/functions/array/scatter_add.py
chainer/functions/array/select_item.py
chainer/functions/loss/negative_sampling.py
chainer/functions/loss/softmax_cross_entropy.py
chainer/functions/math/basic_math.py
chainer/functions/normalization/batch_normalization.py
chainer/link.py
chainer/optimizer.py
chainer/variable.py
chainerx/_fallback_workarounds.py
tests/chainer_tests/backends_tests/test_chainerx.py
tests/chainer_tests/functions_tests/array_tests/test_stack.py
tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
tests/chainer_tests/functions_tests/loss_tests/test_hinge.py
tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
tests/chainer_tests/test_function_node.py
tests/chainer_tests/test_link.py
tests/chainer_tests/test_optimizer.py
tests/chainer_tests/test_variable.py

Fixes #6310 
`to_chainerx` -> `to_chx`
`from_chainerx` -> `from_chainerx`
`Variable.chainerx_array` -> `Variable.chx_array`

Rename `chainerx` -> `chx` in public API

---

chainer/_backend.py
tests/chainer_tests/test_backend.py

Add `__ne__` to `chainer.Device` to make `!=` operator work correctly in all environments because `!=` is not the inverse of `==` in Python 2.
```python
$ pyenv local 2.7.15
$ python
Python 2.7.15 (default, Jun 15 2018, 17:41:47) 
[GCC 5.4.0 20160609] on linux2
>>> import chainer
>>> d1 = chainer.backend._cpu.CpuDevice()
>>> d2 = chainer.backend._cpu.CpuDevice()
>>> d1 == d2
True
>>> d1 != d2
True
```

Add `__ne__` in Device for Python 2

---

chainer/testing/__init__.py
chainer/testing/_bundle.py
chainer/testing/parameterized.py
tests/chainerx_tests/op_utils.py
tests/chainerx_tests/unit_tests/routines_tests/test_connection.py

`@pytest.mark.parametrize` only allows simple list / product of parameters.
With this fix, `op_test` can utilize `@chainer.testing.parameterize`.
Also added `@chainer.testing.parameterize_pytest` which allows pytest-style parameterization.
Depends on #6248.

Use Chainer-style parameterization in ChainerX op test 

---

chainer/variable.py
tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
tests/chainer_tests/test_variable.py

* Without messages, it's difficult to understand the cause.
* Python [officially suggests](https://docs.python.org/3/library/exceptions.html#NotImplementedError) that these methods should not be defined if not supported, but I think the built-in message is not informative enough: ```TypeError: '<' not supported between instances of 'Variable' and 'int'```
* Changed `NotImplementedError` to `TypeError` to match Python's built-in behavior.
```
NotImplementedError
```
```
TypeError: Variables do not support < operator. You could use `array` attribute instead.
```

Improve errors for disabled `Variable` operators

---

examples/imagenet/dali_util.py

This PR aims to fix dtype mismatch issue in imagenet example when DALI and fp16 (chainer.config.dtype = float16) are used together.

Fix dali_util in imagenet example for fp16

---

README.md

"See the installation guide for more details.." → "See the installation guide for more details."

Remove the duplicate periods in Installation of README.md

---

tests/chainer_tests/functions_tests/array_tests/test_diagonal.py

Simplifies `test_diagonal` by using `testing.FunctionTestCase`.

Simplify `F.diagonal` test

---

chainer/configuration.py

2.84 us -> 2.05 us
```py
with chainer.using_config('debug', False):
pass
```

Improve performance of `using_config`

---

tests/chainer_tests/exporters_tests/test_caffe.py
tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py

This PR suppresses a `DeprecationWarning` raised by the Caffe function tests in Python 3.7 with `protobuf==3.7.0`.

Suppress warning in caffe test

---

examples/imagenet/train_imagenet.py

This PR fixes to use the right device in the imagenet example ran with the DALI iterator.

Fix to use right device for DALI iterator in imagenet example

---

chainerx_cc/chainerx/dtype.h
chainerx_cc/chainerx/routines/type_util.h
chainerx_cc/chainerx/routines/type_util_test.cc

Fixes #6418.
Scalar types can take precedence if they have wider kinds than the arrays.

ResultType to take kind into account

---

chainer/functions/math/log_ndtr.py

If we use `chainer.functions.log_ndtr` of now implementation, we may get nan variable,
```
>>> x = cupy.linspace(-20, -10, 11).astype(np.float32)
>>> x = chainer.Variable(x)
>>> y = chainer.functions.log_ndtr(x)
>>> chainer.grad([y], [x])
[variable([      nan,       nan,       nan,       nan,       nan,       nan,
nan,       inf, 12.082214, 11.089464, 10.098132])]
```
so, I fixed this.
```
>>> x = cupy.linspace(-20, -10, 11).astype(np.float32)
>>> x = chainer.Variable(x)
>>> y = chainer.functions.log_ndtr(x)
>>> chainer.grad([y], [x])
[variable([20.049751, 19.052343, 18.055216, 17.058424, 16.062021, 15.066087,
14.070718, 13.076037, 12.082214, 11.089464, 10.098093])]
```

change backward of `F.log_ndtr` to avoid nan

---

tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
tests/chainer_tests/functions_tests/activation_tests/test_softplus.py
tests/chainer_tests/functions_tests/array_tests/test_diagonal.py

This PR adds testcases to input ChainerX arrays, even if the tested functions don't have ChainerX specific implementations.  @niboshi suggested the change.

Add ChainerX test to `FunctionTestCase`s

---

tests/chainer_tests/function_hooks_tests/test_timer.py

The PR fixes a test failure introduced by #6254.  With `unit='ns'`, a long cell can change the number of spaces.

Fix regex in `test_print_report`

---

chainer/testing/function.py

Fixes a typical `TypeError` when joining non `str`s. 
E.g.
```
In [1]: ''.join(type(i) for i in [1,2,3])
...
TypeError: sequence item 0: expected str instance, type found
```

Fix `str.join` `TypeError` in `FunctionTestCase` helper
