chainer/chainer

chainer/functions/array/separate.py, tests/chainer_tests/functions_tests/array_tests/test_separate.py
I made a Separate function node. Originally `separate` function is implemented with `split_axis` and `reshape`. It creates a lot of `Reshape` function node. This PR reduces the number of function nodes.
=> Optimize separate

chainer/functions/loss/ctc.py
=> [backport] Optimize ctc

chainer/gradient_check.py, tests/chainer_tests/test_gradient_check.py
=> [backport] Fix a corner-case bug in gradient_check

chainer/variable.py
=> [backport] Fix the docstring of Variable.backward()

chainer/optimizer.py, chainer/serializers/npz.py
=> [backport] prefix class name to attributes in pydoc

chainer/optimizer.py, chainer/optimizers/adam.py
=> [backport] Raise appropriate error when `Adam.lr` is evaluated before updating starts

docs/source/tutorial/gpu.rst
fix #3660
As currently contribution guide does not mention pydoc at all, I'll write that in separate PR. (raised an issue for now: #4221)
=> raise friendly error for multi-gpu doctest failures

docs/source/tutorial/gpu.rst
=> [backport] raise friendly error for multi-gpu doctest failures

tests/chainer_tests/functions_tests/normalization_tests/test_local_response_normalization.py
Refactored `test_local_response_normalization` to use `testing.backend.inject_backend_tests`.
=> Refactor test_local_response_normalization

examples/sentiment/train_sentiment.py
- Read [our contribution guide](http://docs.chainer.org/en/stable/contribution.html).
- Does you code conform to our coding guidelines?
- Also take a look at [our compatibility policy](http://docs.chainer.org/en/stable/compatibility.html).
=> fix typo in example code

examples/sentiment/train_sentiment.py
=> [backport] fix typo in example code

tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
Refactored `test_average_pooling_2d` to use `testing.backend.inject_backend_tests`.
=> Refactor test_average_pooling_2d

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, docs/source/_static/css/modified_theme.css, docs/source/index.rst
Add Slack Chat and Chainer forums link to docs index
Add Slack Chat to PR template
=> Add Slack Chat link to docs and PR template

.github/ISSUE_TEMPLATE.md, README.md, docs/source/_static/css/modified_theme.css, docs/source/index.rst
=> [backport] Add Slack Chat link to docs and PR template

tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
Refactored `test_max_pooling_2d` to use `testing.backend.inject_backend_tests`.
=> Refactor test_max_pooling_2d

tests/chainer_tests/functions_tests/activation_tests/test_lstm.py
Refactored `test_lstm` to use `testing.backend.inject_backend_tests`.
=> Refactor test_lstm

examples/README.md
=> [backport] update example list

tests/chainer_tests/functions_tests/array_tests/test_concat.py
Refactored `test_concat` to use `testing.backend.inject_backend_tests`.
=> Refactor test_concat

chainer/functions/loss/ctc.py
I simplify the code. The original code has redundant process.
=> Fix creation method of identity matrix

chainer/reporter.py
This PR is trivial, but from v3, using variable.data is discouraged as noted [here](https://github.com/chainer/chainer/blob/master/chainer/variable.py#L624).
=> use variable.array instead of variable.data in reporter.py

chainer/optimizer.py, tests/chainer_tests/serializers_tests/test_npz.py
=> [backport] Serialize t of UpdateRule

tests/chainer_tests/training_tests/triggers_tests/test_interval_trigger.py, tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
=> [backport] fix trigger test imports

chainer/links/connection/gru.py
=> [backport] Improve docs of gru

docs/source/tutorial/convnet.rst, docs/source/tutorial/gpu.rst, docs/source/tutorial/trainer.rst
=> [backport] Update documentation and examples

docs/source/reference/functions.rst
=> [backport] Fix document about links in chainer.functions

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
This PR implements `floordiv` / `rfloordiv` operation for Variable.
=> implement floordiv and rfloordiv

chainer/functions/loss/ctc.py, tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
I simplified CTC. It also support ndarray without Variable wrap.
=> Simplify CTC code

chainer/training/extensions/variable_statistics_plot.py, docs/source/reference/extensions.rst
Add missing doc ref for newly introduced extension.
=> Add missing extension doc ref

chainer/links/connection/n_step_gru.py, chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py
All NStepRNNs contain similar codes. I refactored them to reduce redundant codes.
fix #4105
=> Refactor RNNs

docs/source/tutorial/gpu.rst
=> deepcopy to Link.copy

chainer/functions/loss/ctc.py, tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
=> [backport] Simplify CTC code

docs/source/tutorial/gpu.rst
=> [backport] deepcopy to Link.copy

.travis.yml
=> [backport] fix osx travis build failure

chainer/functions/array/stack.py
I implemented Stack function node to improve stack function. It is two times faster with this test code:
```
import time
import chainer
import cupy
xp = cupy
cupy.cuda.Stream.null.synchronize()
x = chainer.Variable(xp.zeros((32, 256)))
xs = [x] * 100
begin = time.time()
for i in range(1000):
chainer.functions.stack(xs, axis=1)
cupy.cuda.Stream.null.synchronize()
end = time.time()
print('%f sec' % (end - begin))
```
=> Optimize stack

examples/seq2seq/seq2seq.py
=> [backport] Fix unused argument(--out) of seq2seq example

docs/source/tutorial/convnet.rst
Fix invisible indentation with tabs, though it really affects nothing.
=> Fix invisible indentation with tabs in the document

chainer/functions/connection/n_step_gru.py
Fixing a minor notation error on the description of n_step_bigru
=> Fixing a minor notation error on the description of n_step_bigru

chainer/functions/connection/n_step_gru.py
=> [backport] Fix notation error

chainer/functions/__init__.py, chainer/functions/math/tensordot.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_tensordot.py
This PR is to support tensordot as Chainer's function. You can use this function like numpy tensordot as below. Off course, it is backprop-able.
import chainer
import numpy
a = chainer.Variable(numpy.random.rand(4,3,2))
b = chainer.Variable(numpy.random.rand(3,2,5))
c = chainer.functions.tensordot(a, b, axes=((1,2), (0,1)))
=> Tensordot support

chainer/functions/pooling/average_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
iDeep support in F.average_pooling_2d (Separated from #3865. Based on #4276.)
=> iDeep: F.average_pooling_2d

docs/source/conf.py, docs/source/contribution.rst, docs/source/tutorial/basic.rst, docs/source/tutorial/function.rst, docs/source/tutorial/gpu.rst, docs/source/tutorial/recurrentnet.rst
=> [backport] Use version in external URL

chainer/links/connection/inceptionbn.py
=> [backport] Fix docstring

chainer/function_node.py, chainer/variable.py
=> Fix backward_accumulate to accept only tuples

chainer/functions/activation/lstm.py, chainer/functions/activation/tree_lstm.py, tests/chainer_tests/functions_tests/activation_tests/test_lstm.py
iDeep support in F.lstm and F.tree_lstm (Separated from #3865. Based on #4276.)
=> iDeep: F.lstm and F.tree_lstm

tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
=> [backport] Fix initialization of random vectors in the test for RNNs

chainer/__init__.py
iDeep feature is experimental, so it should be disabled by default.
=> Make ideep disabled by default

chainer/functions/connection/linear.py, tests/chainer_tests/functions_tests/connection_tests/test_linear.py
iDeep support in F.linear (Separated from #3865. Based on #4276.)
=> iDeep: F.linear

chainer/functions/activation/relu.py, tests/chainer_tests/functions_tests/activation_tests/test_relu.py
iDeep support in F.relu (Separated from #3865. Based on #4276.)
=> iDeep: F.relu

chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py
I removed redundant stack function in RNN. `_stack_weight` is implemented for LSTM.
=> Remove redundant stack

chainer/functions/noise/dropout.py, tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
iDeep support in F.dropout (Based on #4276.)
=> iDeep: F.dropout

chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py
=> [backport] Remove redundant stack

chainer/functions/normalization/batch_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
iDeep support in F.batch_normalization (Separated from #3865. Based on #4276.)
=> iDeep: F.batch_normalization

chainer/function_node.py, chainer/variable.py
=> [backport] Fix backward_accumulate to accept only tuples

chainer/variable.py
Added `intel64.check_ideep_available()`
=> Add ideep availability check in Variable.to_intel64

docs/source/upgrade.rst
update upgrade guide for changes made in #4300 and #4323.
=> add function hook changes to upgrade guide

chainer/functions/array/split_axis.py, tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
iDeep support in F.split_axis (Separated from #3865. Based on #4276.)
=> iDeep: F.split_axis

chainer/functions/pooling/max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
iDeep support in F.max_pooling_2d (Based on #4276.)
=> iDeep: F.max_pooling_2d

chainer/optimizers/momentum_sgd.py, chainer/optimizers/sgd.py, tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
iDeep support in optimizers.SGD and optimizers.MomentumSGD (Separated from #3865. Based on #4278.)
=> iDeep: optimizers.SGD and optimizers.MomentumSGD

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
iDeep support in F.convolution_2d and F.deconvolution_2d (Separated from #3865. Based on #4276.)
=> iDeep: F.convolution_2d and F.deconvolution_2d

chainer/functions/normalization/l2_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
=> [backport] Fix backward of NormalizeL2

chainer/links/normalization/batch_renormalization.py
chainer.cuda.get_device is deprecated.
=> use get_device_from_id instead of get_device

chainer/links/normalization/batch_renormalization.py
=> [backport] use get_device_from_id instead of get_device

tests/chainer_tests/training_tests/test_updater.py
=> [backport] Avoid mutable default argument

chainer/testing/attr.py
=> [backport] Simplify chained comparison

chainer/backends/cuda.py, chainer/functions/array/resize_images.py, chainer/functions/array/scatter_add.py, chainer/functions/array/spatial_transformer_sampler.py
Depends on https://github.com/cupy/cupy/pull/894
=> Support cupyx namespace

docs/source/reference/functions.rst
=> add F.shift to docs

chainer/functions/activation/lstm.py
This PR partially resolves #4319
=> Fix lstm backward arguments

docs/Makefile
=> [backport] fix sphinx build option assignment in Makefile

.pep8, .travis.yml, docs/source/contribution.rst, setup.cfg
`autopep8` command can use `setup.cfg` file automatically.
=> Fix autopep8 config

chainer/training/updaters/multiprocess_parallel_updater.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
=> [backport] Fix crash bug when a child is reporting a value when using MultiprocessParallelUpdater

examples/mnist/train_mnist_custom_loop.py
=> [backport] Fix some options of MNIST example not working

tests/chainer_tests/test_function.py, tests/chainer_tests/test_function_node.py, tests/chainer_tests/test_variable.py
=> [backport] Add test cases for various shapes as function input

chainer/backends/cuda.py, tests/chainer_tests/test_cuda.py
=> [backport] Fix numpy dtypes bug in cuda.to_gpu and cuda.copy

docs/source/_autosummary_check.py, docs/source/conf.py
I added functionality to check autosummary automatically, by reverse-generating a list of exported features.
Now we can catch the documentation error when adding new feature.
I started with Functions and Links, but if this idea is acceptable, I can just add another modules.
By #4037 and this PR,
```
$ SPHINXOPTS= make check-html
```
will print:
```
chainer/docs/source/_autosummary_check.rst:75: WARNING: unknown document: reference/generated/chainer.functions.f1_score
chainer/docs/source/_autosummary_check.rst:76: WARNING: unknown document: reference/generated/chainer.functions.precision
chainer/docs/source/_autosummary_check.rst:77: WARNING: unknown document: reference/generated/chainer.functions.recall
chainer/docs/source/_autosummary_check.rst:86: WARNING: unknown document: …
```
=> add autosummary check to documents

README.md, docs/source/install.rst, setup.py
=> [backport] Prefer pip in installation guide; Add sphinx in docs requirements

chainer/link.py, tests/chainer_tests/test_link.py
=> Fix link.to_intel64 for persistent values

chainer/functions/__init__.py, chainer/functions/activation/swish.py, chainer/links/__init__.py, chainer/links/activation/swish.py, docs/source/reference/functions.rst, docs/source/reference/links.rst, tests/chainer_tests/functions_tests/activation_tests/test_swish.py, tests/chainer_tests/links_tests/activation_tests/test_swish.py
This PR implements [Swish activation function](https://arxiv.org/abs/1710.05941) and the corresponding Link with trainable parameter `beta`.
I wrote this for self-education. Any comments or suggestions would be appreciated.
=> Add Swish activation function.

chainer/functions/noise/simplified_dropconnect.py, tests/chainer_tests/functions_tests/noise_tests/test_simplified_dropconnect.py, tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
This PR implements new style `simplified_dropconnect` function.
=> new style simplified_dropconnect function

chainer/functions/math/matmul.py
Backport only the bugfix in #4349
=> [backport] Fix BatchMatMulGrad.backward

tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
`test_multiprocess_parallel_updater` does not specify appropriate test marks.
=> Fix test of multiprocess_parallel_updater

.pep8, .travis.yml, docs/source/contribution.rst, setup.cfg
=> [backport] Fix autopep8 config

chainer/functions/noise/simplified_dropconnect.py, tests/chainer_tests/functions_tests/noise_tests/test_simplified_dropconnect.py, tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
=> [backport] new style simplified_dropconnect function

docs/source/_autosummary_check.py, docs/source/conf.py
=> [backport] add autosummary check to documents

chainer/functions/activation/elu.py
=> [backport] Improve ELU.backward

codecov.yml
=> [backport] add Codecov.io configuration

chainer/functions/array/get_item.py
=> [backport] Improve docs of get item

chainer/functions/__init__.py, chainer/functions/math/fft.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_fft.py
I implemented back-propable FFT.
This interface is different from that of `xp.fft` because Variable does not support complex.
=> Implement FFT

chainer/functions/pooling/unpooling_nd.py
=> [backport] Fix typo in unpooling_nd

chainer/training/triggers/__init__.py, chainer/training/triggers/time_trigger.py, docs/source/reference/triggers.rst, tests/chainer_tests/training_tests/triggers_tests/test_time_trigger.py
I implemented a trigger that is invoked periodically.
=> Implement time trigger

chainer/training/extensions/parameter_statistics.py, tests/chainer_tests/training_tests/extensions_tests/test_parameter_statistics.py
=> Default statistics to get array modules

tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
=> [backport] Test of RNN in the case when some gradients are None

docs/source/reference/datasets.rst
=> Fix the index page of datasets in documentation

tests/chainer_tests/test_variable.py
Add tests for features deprecated in #4199.
=> add backward test for old-styled sclar variable

chainer/functions/pooling/average_pooling_nd.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/max_pooling_nd_kernel.py, chainer/functions/pooling/pooling_nd.py, chainer/functions/pooling/unpooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_nd.py
=> [backport] New style AveragePoolingND/MaxPoolingND/UnpoolingND

chainer/functions/noise/zoneout.py, tests/chainer_tests/functions_tests/noise_tests/test_zoneout.py
=> [backport] new style zoneout function

chainer/functions/normalization/batch_normalization.py
=> [backport] add warning for batch normalization when batchsize=1 and train=True

docs/source/upgrade_v2.rst
Added missing whitespace in docs.
=> Fix docs format in upgrade guide

chainer/training/extensions/evaluator.py
=> fix Evaluator.device docs

docs/source/comparison.rst
=> [backport] Update comparison.rst (Web interface)

docs/source/upgrade_v2.rst
=> [backport] Fix docs format in upgrade guide

docs/source/comparison.rst
=> [backport] add ChainerUI link to comparison table

chainer/training/extensions/evaluator.py
=> [backport] fix Evaluator.device docs

docs/source/guides/extensions.rst
Fix document test failure introduced in #4215.
=> fix underline in docs

docs/source/tutorial/extension.rst
=> [backport] updated english for extension documentation

MANIFEST.in
=> [backport] add license to source distribution

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
ideep backend has the ability to fuse several add operation into one sum primitive. This PR is to accelerate the mutli_add on intel64 backend.
=> Accelerate multi-add for intel64 backend

docs/source/upgrade.rst
=> [backport] add link to CuPy upgrade guide

chainer/functions/normalization/batch_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Fixes #1960 using value exposed via https://github.com/cupy/cupy/pull/1011.
Also fixed wrong comments.
=> Fix to use CUDNN_BN_MIN_EPSILON

tests/chainer_tests/test_optimizer.py, tests/chainer_tests/training_tests/triggers_tests/test_interval_trigger.py, tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
`UserWarning` is occurring when running the test.
I fixed it to be processed correctly.
=> Reduce UserWarning

chainer/dataset/convert.py
Fix test failure introduced in #4164.
=> fix doctest failure in chainer.dataset.concat_examples

chainer/backends/cuda.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/deconvolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py, tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py, tests/chainer_tests/functions_tests/connection_tests/test_dilated_convolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_mlp_convolution_2d.py, tests/chainer_tests/test_cuda.py
Please merge #3781 and cupy/cupy#715 before this PR.
=>  Delegate cuDNN convolution operation to CuPy

chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py, chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py
=> [backport] Fix document in NStepLSTM/GRU/RNN

docs/source/_templates/autosummary/class.rst
This fixes #3821.
Related to #4480.
=> document arithmetic special functions

docs/source/_templates/autosummary/class.rst
=> [backport] document arithmetic special functions

docs/source/install.rst, docs/source/tips.rst
I wrote documents for iDeep support.
=> add document on using iDeep

chainer/functions/loss/ctc.py
I improved docstring of CTC. I only appended shape information.
fix #3053
=> Improve docstring of CTC

docs/source/reference/index.rst
~~Depends on #4488.~~ (merged)
=> Fix order of items in Reference section

chainer/variable.py
After the offline discussion with @hvy regarding #4495, I thought it is better to explicitly state what operators are supported for Variables.
=> improve docs for supported operators in Variable

chainer/variable.py
=> [backport] improve docs for supported operators in Variable

chainer/dataset/convert.py
=> [backport] Fix doctest

docs/source/reference/index.rst
=> [backport] Fix order of items in Reference section

.travis.yml
=> [backport] Travis test against v4 branch

chainer/functions/util/forget.py, tests/chainer_tests/functions_tests/util_tests/test_forget.py
=> [backport] New style forget

chainer/__init__.py, docs/source/reference/debug.rst
=> [backport] fix debug mode documentation

docs/source/install.rst, docs/source/tips.rst
=> [backport] add document on using iDeep

chainer/training/extensions/_snapshot.py, tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
=> [backport] Save snapshot in the OS default permission

chainer/functions/loss/ctc.py
=> [backport] Improve docstring of CTC

chainer/serializers/hdf5.py, chainer/serializers/npz.py, tests/chainer_tests/serializers_tests/test_hdf5.py, tests/chainer_tests/serializers_tests/test_npz.py
=> [backport] Support deserializing into array of different dtype

docker/intel/python2/Dockerfile, docker/intel/python3/Dockerfile, docker/python2/Dockerfile, docker/python3/Dockerfile
Chainer part of the same fix as in https://github.com/cupy/cupy/pull/1060.
=> use --no-cache-dir in Dockerfile

docker/intel/python2/Dockerfile, docker/intel/python3/Dockerfile, docker/python2/Dockerfile, docker/python3/Dockerfile
=> [backport] use --no-cache-dir in Dockerfile

chainer/functions/normalization/batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
=> [backport] Remove eps from batch normalization statistics

chainer/variable.py, tests/chainer_tests/test_variable.py
=> [backport] Implement Variable.xp

chainer/functions/connection/deconvolution_2d.py
Ideep support dilated convolution. Enable it in Chainer can improve SSD performance.
=> Support dilated convolution on ideep backend

chainer/function_node.py, tests/chainer_tests/test_function_hook.py
=> Call FunctionHooks in chainer.grad

chainer/function_node.py, tests/chainer_tests/test_function_hook.py
=> [backport] Call FunctionHooks in chainer.grad

docs/source/reference/training.rst
I separated each Extensions into category and added description.
=> improve description of Extensions

docs/source/reference/training.rst
=> [backport] improve description of Extensions

docs/source/upgrade.rst
Upgrade guide for https://github.com/chainer/chainer/pull/3977
=> add upgrade guide for optimizer_hooks namespace

docs/source/upgrade.rst
Fix CI failure introduced in #4468.
=> fix dead link to optimizer hooks

chainer/exporters/__init__.py, chainer/exporters/caffe.py, docs/source/reference/caffe.rst, examples/caffe_export/README.md, examples/caffe_export/export.py, setup.py, tests/chainer_tests/exporters_tests/test_caffe.py
=> Implement caffe export

docs/source/upgrade.rst
=> [backport] add upgrade guide for optimizer_hooks namespace

chainer/exporters/__init__.py, chainer/exporters/caffe.py, docs/source/reference/caffe.rst, examples/caffe_export/README.md, examples/caffe_export/export.py, setup.py, tests/chainer_tests/exporters_tests/test_caffe.py
=> [backport] Implement caffe export

chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/links/connection/convolution_2d.py
=> [backport] fix docs in {convolution,deconvolution}_2d

tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
=> Simplify TestSoftmaxCrossEntropyInvalidReduce in test_softmax_cross_entropy

chainer/training/triggers/early_stopping_trigger.py
=> [backport] fix document in EarlyStoppingTrigger

docs/source/reference/configuration.rst
=> add document for chainer.config.lazy_grad_sum

chainer/functions/connection/local_convolution_2d.py
=> [backport] Fix a typo

chainer/functions/array/depth2space.py, chainer/functions/array/space2depth.py
Optimize the depth2space & space2depth functions by reducing the number of operations.
=> Optimize depth2space & space2depth funcs by reducing operations

chainer/variable.py, tests/chainer_tests/test_variable.py
Fixes the issue found in https://github.com/chainer/chainer/pull/4577#discussion_r180058824
=> Fix to_intel64 not updating VariableNode.data

chainer/link.py, chainer/variable.py, tests/chainer_tests/test_link.py, tests/chainer_tests/test_variable.py
=> Fix to_intel64 to check if it is suitable for iDeep

docs/source/reference/configuration.rst
=> [backport] add document for chainer.config.lazy_grad_sum

chainer/link.py, chainer/variable.py, tests/chainer_tests/test_link.py, tests/chainer_tests/test_variable.py
=> [backport] Fix to_intel64 to check if it is suitable for iDeep

chainer/variable.py, tests/chainer_tests/test_variable.py
=> [backport] Fix to_intel64 not updating VariableNode.data

setup.py
=> [backport] Fix installation order of hacking

chainer/functions/math/bias.py, chainer/functions/math/scale.py
=> [backport] Improve docstrings about axis of Caffe functions

chainer/utils/argument.py, tests/chainer_tests/utils_tests/test_argument.py
I want to make exception message more similar to that in Python.
=> Improve chainer.utils.argument exception message

chainer/__init__.py, chainer/link.py, chainer/sequential.py, chainer/variable.py, docs/source/reference/links.rst, tests/chainer_tests/test_link.py, tests/chainer_tests/test_sequential.py, tests/chainer_tests/test_variable.py
=> [backport] Add Sequential class for easy model definition of a single-stream computational graph

chainer/training/extensions/_snapshot.py, tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
Reverts chainer/chainer#4524
This backport PR was originally intended for v4 but was incorrectly based on v3.
=> Revert "[backport] Save snapshot in the OS default permission"

chainer/backends/cuda.py
=> improve docs of get_device_from_array

tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
=> [backport] Fix and simplify TestForwardConsistency in softmax_cross_entropy

chainer/utils/argument.py, tests/chainer_tests/utils_tests/test_argument.py
=> [backport] Improve chainer.utils.argument exception message

chainer/functions/array/depth2space.py, chainer/functions/array/space2depth.py
=> [backport] Optimize depth2space & space2depth funcs by reducing operations

chainer/backends/cuda.py
=> [backport] improve docs of get_device_from_array

chainer/functions/connection/n_step_rnn.py
I removed redundant member variables and instead fixed the function to use retained inputs/outputs.
=> Removed redundant member variables

chainer/training/extensions/__init__.py, chainer/training/extensions/fail_on_nonnumber.py, docs/source/reference/training.rst, tests/chainer_tests/training_tests/extensions_tests/test_fail_on_nonnumber.py
=> [backport] Add extension to kill training when NaN or Inf is detected (FailOnNonNumber)

docs/source/tips.rst
=> Add FAQ for MultiprocessIterator + OpenCV problem

docs/source/tips.rst
=> [backport] Add FAQ for MultiprocessIterator + OpenCV problem

chainer/sequential.py
=> [backport] Fix docstrings of Sequential

chainer/functions/connection/n_step_rnn.py
=> [backport] Removed redundant member variables

chainer/link.py, tests/chainer_tests/test_link.py
=> [backport] Fix Chain.repeat

chainer/functions/normalization/batch_normalization.py
=> [backport] Use rsqrt in batch_normalization

chainer/functions/math/sqrt.py
=> [backport] improve F.rsqrt performance in CPU

chainer/dataset/download.py, chainer/testing/serializer.py, chainer/training/extensions/_snapshot.py, chainer/training/extensions/log_report.py, chainer/utils/__init__.py
=> [backport] Fix temporary file permission issue in LogReport

chainer/optimizer_hooks/__init__.py, chainer/optimizer_hooks/gradient_lars.py, docs/source/reference/optimizers.rst, tests/chainer_tests/optimizer_hooks_tests/test_gradient_lars.py
=> [backport] Support Layer-wise Adaptive Rate Scaling(LARS)

docs/source/guides/index.rst, docs/source/guides/report.rst
=> [backport] add tutorial for Reporter and report.

chainer/training/extensions/variable_statistics_plot.py
=> Fix import failure when matplotlib 1.x is installed

chainer/testing/condition.py, chainer/testing/parameterized.py, tests/chainer_tests/testing_tests/test_condition.py, tests/chainer_tests/testing_tests/test_parameterized.py
=> [backport] Support skipping tests decorated by condition or parametize

docs/source/reference/caffe.rst
=> [backport] fix heading level of Caffe docs

docs/source/examples/ptb.rst
=> Update math formula typo

setup.py
=> [backport] Fix hacking version

docs/source/examples/ptb.rst
=> [backport] Update math formula typo

docs/source/examples/word2vec.rst
=> [backport] Update word2vec.rst

chainer/links/normalization/batch_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
This PR fixes some issues I wasn't aware of when I reviewed #4266.
- Move the document of `axis` to the correct position
- Add `axis` test to links_test
=> L.BatchNormalization: miscellaneous fixes

docs/source/index.rst
=> [backport] Update top sentences in documentation

docs/source/examples/seq2seq.rst
=> [backport] Update seq2seq.rst

chainer/training/updaters/multiprocess_parallel_updater.py
=> Raise an error when CUDA has been initialized before MultiprocessParallelUpdater is initialized

chainer/functions/connection/bilinear.py, tests/chainer_tests/functions_tests/connection_tests/test_bilinear.py
=> Fix regression in bilinear

chainer/variable.py, tests/chainer_tests/test_variable.py
Fixes https://github.com/chainer/chainer/issues/3878#issuecomment-388775372
=> Fix lazy_grad_sum debug mode

chainer/variable.py, tests/chainer_tests/test_variable.py
=> [backport] Fix lazy_grad_sum debug mode

chainer/functions/loss/mean_absolute_error.py, chainer/variable.py, tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py, tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
=> Select current device using grads of outputs in addition to inputs during backward

chainer/functions/normalization/l2_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
=> [backport] Fix dtype bug in F.normalize

chainer/functions/connection/bilinear.py, tests/chainer_tests/functions_tests/connection_tests/test_bilinear.py
=> [backport] Fix regression in bilinear

docs/source/contribution.rst
Write steps to build docs for contributors.
(context: https://github.com/chainer/chainer/pull/4397#issuecomment-387044030)
=> add doc build steps to contrib guide

chainer/functions/loss/huber_loss.py
Forward and backward computations of Huber loss function are optimized.
* `xp.abs` is used instead of `abs`,
* `out` arguments are aggressively used for efficient memory access,
* `chainer.function.clip` is used for the backward computation.
CUDA kernel would achieve better performance, but it is out of scope of this PR.
=> Optimize Huber loss by simpler calculation

chainer/variable.py
=> [backport] Add abs to document of Variable

chainer/functions/loss/huber_loss.py
=> [backport] Optimize Huber loss by simpler calculation

docs/source/examples/train_loop.rst
=> [backport] Update train_loop.rst

chainer/backends/intel64.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/links/connection/convolution_2d.py
=> [backport] grouped convolution for intel64 backed environment

docs/source/contribution.rst
=> [backport] add doc build steps to contrib guide

chainer/dataset/iterator.py, chainer/iterators/multiprocess_iterator.py, chainer/iterators/multithread_iterator.py, examples/mnist/train_mnist_custom_loop.py
=> [backport] Provide a cleaner way to collect threads and processes in MultiprocessIterator

chainer/backends/intel64.py, chainer/link.py, chainer/variable.py, tests/chainer_tests/test_variable.py
=> [backport] Support copying 1-dim array to ideep

chainer/training/extensions/__init__.py, chainer/training/extensions/polynomial_shift.py, docs/source/reference/training.rst, tests/chainer_tests/training_tests/extensions_tests/test_polynomial_shift.py
- Does you code conform to our coding guidelines?
- Also take a look at [our compatibility policy](https://docs.chainer.org/en/stable/compatibility.html).
Please deprecate the PR #4667 . Thanks.
=> Added the support of PolynomialShift in the extensions of training.

chainer/functions/math/prod.py, tests/chainer_tests/functions_tests/math_tests/test_prod.py
This PR implements new style `prod` function.
~~This PR depends on `F.repeat` proposed in PR #3735.~~ (merged)
=> new style prod function

chainer/variable.py, tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py, tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
=> [backport] Select current device using grads of outputs in addition to inputs during backward

chainer/functions/math/sparse_matmul.py, chainer/utils/sparse.py, docs/source/reference/util/sparse.rst
Some documentations and examples related to newly introduced sparse matrices.
=> Sparse matrix example docs

docs/source/reference/training.rst
I added the documentation for the pros/cons of multi-gpu's updaters.
I just use the following question's answer.
https://groups.google.com/forum/#!topic/chainer/X5rw86qs8Ug
=> Document the pros and cons of the multi-GPU updaters

README.md
=> [backport] update URL in README

chainer/datasets/transform_dataset.py
=> Fix a documenation bug in `TransformDataset`

chainer/exporters/caffe.py
=> [backport] Fix comment in `caffe.py`

tests/chainer_tests/training_tests/updaters_tests/snippets/child_reporter.py, tests/chainer_tests/training_tests/updaters_tests/snippets/raw_array.py, tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
=> [backport] separate MultiprocessParallelUpdater tests

examples/cifar/train_cifar_custom_loop.py, examples/mnist/train_mnist_custom_loop.py, examples/ptb/train_ptb_custom_loop.py
=> [backport] Fix custom loop examples to disable train mode during evaluation

setup.cfg
=> [backport] Fix test warning filter for Theano 1.0.2 which triggers DeprecationWarning

chainer/functions/math/prod.py, tests/chainer_tests/functions_tests/math_tests/test_prod.py
=> [backport] Support double-backprop in `F.prod`

chainer/dataset/download.py, chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py
Printing to stdout makes the feature hard to test by doctest.
Similar fix to https://github.com/chainer/chainer/pull/3886.
This fixes CI error in #4714.
Also fixed to flush the stream.
=> Show progress report to stderr

chainer/dataset/download.py, chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py
=> [backport] Show progress report to stderr

tests/chainer_tests/functions_tests/math_tests/test_minmax.py
The checks have to be aware of `axis`:
```
y = x.max(axis=self.axis, keepdims=True)
if numpy.all((x > y - 2 * eps).sum(axis=self.axis) == 1):
```
=> Fix input checks of `TestMin` and `TestMax`

chainer/functions/connection/bilinear.py
=> [backport] Replace ternary numpy.einsum

chainer/training/updaters/parallel_updater.py
=> Select devices appropriately when calling user code in ParallelUpdater

tests/chainer_tests/functions_tests/math_tests/test_minmax.py
=> [backport] Fix input checks of `TestMin` and `TestMax`

chainer/training/updaters/parallel_updater.py
=> [backport] Select devices appropriately when calling user code in `ParallelUpdater`

examples/mnist/train_mnist_custom_loop.py
=> Simplify classification custom loop example

examples/word2vec/train_word2vec.py
=> Remove redundant device allocation in word2vec example

chainer/optimizer_hooks/gradient_hard_clipping.py, chainer/optimizer_hooks/gradient_lars.py, chainer/optimizer_hooks/gradient_noise.py, chainer/optimizer_hooks/lasso.py, chainer/optimizer_hooks/weight_decay.py
=> Add call_for_each_param to docs

docs/source/tips.rst
It is a common pitfall esp. for beginners. (#4783)
=> Add type check trouble shooting to FAQ

chainer/functions/loss/contrastive.py, tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
This PR implements new style `contrastive` function
~~Merge this after #3735.~~ (done)
~~WIP: needs tolerance adjustments.~~ (done)
=> Support double-backprop in `F.contrastive`

chainer/datasets/transform_dataset.py
=> [backport] Fix a documenation bug in `TransformDataset`

chainer/functions/loss/contrastive.py, tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
=> [backport] Support double-backprop in `F.contrastive`

tests/chainer_tests/function_hooks_tests/test_cuda_profile.py
Currently the test works because `Variable.__add__` doesn't check `None`.  Tests shouldn't depend on this behavior.
=> Set output grad in `TestCUDAProfileHook`

chainer/iterators/multithread_iterator.py, chainer/iterators/serial_iterator.py, chainer/training/extensions/evaluator.py, tests/chainer_tests/training_tests/extensions_tests/test_evaluator.py
=> [backport] Issue a warning when `repeat` attribute of some iterators in `Evaluator` is `True`

appveyor.yml, setup.py
=> [backport] Remove flake8 from AppVeyor test

chainer/testing/attr.py
=> [backport] Mark multi_gpu tests as gpu tests

chainer/functions/array/spatial_transformer_grid.py, chainer/functions/array/spatial_transformer_sampler.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py, chainer/functions/noise/dropout.py, chainer/functions/noise/zoneout.py, chainer/functions/normalization/batch_normalization.py, chainer/links/caffe/caffe_function.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/deconvolution_2d.py, chainer/links/connection/n_step_rnn.py, chainer/links/connection/zoneoutlstm.py, chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py, chainer/links/normalization/batch_normalization.py, chainer/training/extension.py, chainer/training/trainer.py, chainer/utils/argument.py, chainer/variable.py
I want to remove overhead of argument processing in `chainer.functions`.
=> Improve argument processing performance

chainer/functions/array/moveaxis.py, chainer/functions/array/rollaxis.py
`rollaxis` is not a good function when it is used to move an axis forward.
=> Improve the documentation of `F.moveaxis` and discourage `F.rollaxis`

chainer/exporters/caffe.py, tests/chainer_tests/exporters_tests/test_caffe.py
Fixes #4858.
I also improved tests to compare results between original link and re-imported link.
~Blocked by #4875.~(merged)
=> Fix Caffe exporter to export eps of BatchNormalization layer

chainer/links/caffe/caffe_function.py, tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
=> [backport] Support importing Caffe Reshape layer

.travis.yml, appveyor.yml
=> [backport] Deselect gpu tests instead of skipping them

docs/source/examples/train_loop.rst
Replace 0xa0 (nbsp) with 0x20 (space) in documentation
=> Replace 0xa0 (nbsp) with 0x20 (space) in documentation

docs/source/examples/train_loop.rst
=> [backport] Replace 0xa0 (nbsp) with 0x20 (space) in documentation

chainer/exporters/caffe.py
=> [backport] Fix ValueError in caffe exporter on Windows with Python 2.7

chainer/distribution.py, docs/source/reference/distributions.rst, docs/source/reference/index.rst
I add a reference of distribution.
#4773
=> Add distribution reference

tests/chainer_tests/links_tests/activation_tests/test_simplified_dropconnect.py
See https://github.com/chainer/chainer/issues/4656#issue-315705686
=> Delete redundant `no_grads` from test

.travis.yml, setup.py
=> [backport] Check docs build in Travis CI

chainer/link.py, tests/chainer_tests/test_link.py
=>  Support remove/replace child link in ChainList #4659

chainer/exporters/caffe.py, tests/chainer_tests/exporters_tests/test_caffe.py
I implemented Caffe LeakyReLU layer. Merge #4936 first.
=> Add support for exporting Caffe LeakyReLU layer

chainer/distributions/normal.py
fixed a document of `chainer.distributions.Normal`.
=> [fix] normal document

chainer/links/connection/mlp_convolution_2d.py, chainer/links/model/classifier.py, chainer/optimizer.py, docs/source/guides/functions.rst, docs/source/reference/functions.rst
=> Improve function reference and documentation

chainer/function.py, chainer/gradient_check.py, chainer/links/connection/mlp_convolution_2d.py, chainer/links/model/classifier.py, chainer/optimizer.py, chainer/training/triggers/minmax_value_trigger.py, docs/source/reference/functions.rst
=> [backport] Improve documentation about wrapper functions

docs/source/index.rst, docs/source/performance.rst, docs/source/reference/configuration.rst
=> [backport] Add Performance Best Practices document

chainer/links/connection/mlp_convolution_2d.py, chainer/links/model/classifier.py, chainer/optimizer.py, docs/source/guides/functions.rst, docs/source/reference/functions.rst
=> [backport] Improve function reference and documentation

tests/chainer_tests/test_function_node.py, tests/chainer_tests/test_variable.py
=> [backport] Add backprop tests

chainer/functions/__init__.py, chainer/functions/array/diagonal.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/array_tests/test_diagonal.py
This PR adds numpy-compatible (taking-)diagonal operation to `chainer.functions`.
=> Add `F.diagonal`

chainer/functions/pooling/max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
Refs https://github.com/chainer/chainer/pull/4421#issuecomment-395377917
=> Implement `return_indices` option to `F.max_pooling_2d`

chainer/functions/math/matmul.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
=> Raise an error on 0-dim input to matmul

chainer/optimizers/adam.py
=> Fix Adam alpha argument explanation

chainer/functions/pooling/max_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
Refs https://github.com/chainer/chainer/pull/4421#issuecomment-395377917
=> Implement `return_indices` option to `F.max_pooling_nd`

chainer/functions/noise/dropout.py, tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
Refs https://github.com/chainer/chainer/pull/4421#issuecomment-395377917
=> Implement mask and return_mask option to `F.dropout`

chainer/functions/noise/gaussian.py, tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
Refs https://github.com/chainer/chainer/pull/4421#issuecomment-395377917
=> Implement eps and return_eps option to `F.gaussian`

chainer/functions/normalization/batch_renormalization.py, chainer/links/normalization/batch_renormalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
=> [backport] Deprecate `F.fixed_batch_renormalization`

chainer/functions/pooling/max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
=> [backport] Implement `return_indices` option to `F.max_pooling_2d`

chainer/functions/pooling/max_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
=> [backport] Implement `return_indices` option to `F.max_pooling_nd`

chainer/functions/noise/gaussian.py, tests/chainer_tests/functions_tests/noise_tests/test_gaussian.py
=> [backport] Implement eps and return_eps option to `F.gaussian`

chainer/functions/noise/dropout.py, tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
=> [backport] Add `mask` and `return_mask` option to `F.dropout`

tests/chainer_tests/functions_tests/math_tests/test_average.py
Fixed the lower bound of `self.w.sum()`.
(#3766)
=> Fix occasional test failure of `F.average` by changing lower-bound of weight.sum

docs/source/examples/cnn.rst
Fixes:
* the second LeNet5 model definition does not work
* class name typo (`ResNet152layers` -> `ResNet152Layers`)
* some snippets are not tested (fixes #4697)
=> Improve CNN example docs

docs/source/reference/datasets.rst
This PR is to add document of ZippedImageDataset and MultiZippedImageDataset to chainer document.
No code modification is included.
=> Add `ZippedImageDataset` and `MultiZippedImageDataset` to document

tests/chainer_tests/links_tests/model_tests/test_vision.py
=> Fix kwarg name in `TestResNetLayers`

tests/chainer_tests/links_tests/model_tests/test_vision.py
Tests introduced in #4675 was unnecessary.
=> Remove unnecessary tests

chainer/distributions/normal.py, chainer/testing/distribution_test.py, tests/chainer_tests/distributions_tests/test_normal.py
- Make user pass variables to `Distribution` if grad is needed.
- Check `test_targets` members are valid.
- Don't override `setUp`.
=> Refactor distribution

docs/source/reference/datasets.rst
=> [backport] Add `ZippedImageDataset` and `MultiZippedImageDataset` to documentation

docs/source/upgrade.rst
Add upgrade guide for ``auto_new_epoch`` introduced in #4608.
=> Add upgrade guide for `auto_new_epoch`

chainer/optimizers/adam.py
=> [backport] Fix Adam alpha argument explanation

chainer/training/updaters/standard_updater.py
=> Fix cross-reference links in StandardUpdater

chainer/training/updaters/standard_updater.py
=> [backport] Fix cross-reference links in StandardUpdater

chainer/functions/pooling/upsampling_2d.py
Updated docs according to https://github.com/chainer/chainer/pull/4890 .
=> Update docs in upsampling_2d according to new max_pooling_2d

chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py
I deleted docs of some parameters which do not exist yet.
=> Fix docs of n_step_rnn and n_step_lstm

chainer/functions/pooling/upsampling_2d.py
=> [backport] Update docs in upsampling_2d according to new max_pooling_2d

chainer/computational_graph.py
=> [backport] Fix docstrings in computational_graph

chainer/backends/cuda.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py, chainer/functions/noise/dropout.py, tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
This PR implements cuDNN support for dropout operation.
Its implementation depends on https://github.com/cupy/cupy/pull/479 .
=> Support cuDNN in F.dropout

tests/chainer_tests/test_variable.py
=> Fix `test_default_backward`

docs/source/install.rst
=> [backport] Support NumPy 1.14 in docs

chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py
=> [backport] Fix docs of n_step_rnn and n_step_lstm

chainer/functions/math/fft.py
=> [backport] Fix verb error in chainer.functions.fft docstring

tests/chainer_tests/test_variable.py
=> [backport] Fix `test_default_backward`

chainer/optimizer_hooks/gradient_clipping.py
=> [backport] Run gradient clipping on GPU, if possible

chainer/functions/connection/n_step_gru.py
=> [backport] Fix typo in `n_step_gru` docs

chainer/functions/connection/dilated_convolution_2d.py, chainer/links/connection/dilated_convolution_2d.py
=> [backport] Add notes about relationship between dilated_convolution_2d and convolution_2d

chainer/links/connection/linear.py
Backport of #4983.
Jenkins, test this please.
=> [backport] Clarify how arguments are handled in `L.Linear` docs

docs/source/contribution.rst, docs/source/reference/check.rst
=> Add rules regarding use of pytest module

docs/source/contribution.rst, docs/source/reference/check.rst
=> [backport] Add rules regarding use of pytest module

docs/source/_templates/autosummary/class.rst
=> [backport] Fix typo in comment in template

chainer/links/normalization/batch_normalization.py, chainer/links/normalization/batch_renormalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
=> Support default dtype in `L.BatchNormalization` and `L.BatchRenormalization`

chainer/initializer.py, chainer/initializers/constant.py, chainer/initializers/orthogonal.py, chainer/initializers/uniform.py, chainer/link.py, chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py, chainer/links/normalization/batch_normalization.py, chainer/links/normalization/layer_normalization.py, chainer/training/extension.py, chainer/variable.py, docs/source/_napoleon_patch.py, docs/source/conf.py
=> [backport] Fix attribute name collisions in docstring

docs/source/contribution.rst, setup.cfg, setup.py
=> Update style check tools

chainer/functions/loss/ctc.py, chainer/functions/math/batch_l2_norm_squared.py, chainer/functions/math/sparse_matmul.py, chainer/functions/pooling/roi_pooling_2d.py, chainer/functions/pooling/upsampling_2d.py, chainer/training/updaters/multiprocess_parallel_updater.py
Some functions do not cache kernels correctly, causing memory leak.
=> Fix kernels not memorized

chainer/links/connection/inceptionbn.py, tests/chainer_tests/links_tests/connection_tests/test_inceptionbn.py
This PR is a part of #4582, makes `L.InceptionBN` support default dtype.
=> Support default dtype in `L.InceptionBN`

chainer/functions/math/basic_math.py
This PR fixes the multi_add part of #5055.
=> Fix ideep call in MultiAdd

docs/source/guides/variables.rst
=> [backport] Improve Variable guide

chainer/distributions/laplace.py, chainer/distributions/normal.py, chainer/testing/distribution_test.py, chainer/variable.py, tests/chainer_tests/distributions_tests/test_laplace.py, tests/chainer_tests/distributions_tests/test_normal.py
=> Support 0-dim params in distributions

chainer/variable.py
=> Revert #5075

docs/source/reference/caffe.rst
=> [backport] Update caffe.rst

tests/chainer_tests/test_cuda.py
An empty array will has actual device id in cupy/cupy#946 .
=> Remove test_get_dummy_device_for_empty_array

chainer/training/extension.py, chainer/training/trainer.py
=> Add extension.name clarification

chainer/distributions/__init__.py, chainer/distributions/bernoulli.py, docs/source/reference/distributions.rst, tests/chainer_tests/distributions_tests/test_bernoulli.py, tests/chainer_tests/distributions_tests/test_kldivergence.py
=> Add Bernoulli distribution

chainer/dataset/download.py
=> [backport] Fix dataset path to support Windows

chainer/backends/cuda.py, docs/source/reference/util/cuda.rst
This exposes Chainer interface for RawKernel (https://github.com/cupy/cupy/pull/1398).
=> Add raw kernel function

chainer/training/extensions/print_report.py, tests/chainer_tests/training_tests/extensions_tests/test_print_report.py
Resubmitting #4758 to master branch.
=> Flush the output stream after PrintReport reports

chainer/links/connection/convolution_2d.py
=> [backport] Fix L.Convolution2D error message

chainer/training/extensions/print_report.py, tests/chainer_tests/training_tests/extensions_tests/test_print_report.py
=> [backport] Flush the output stream after PrintReport reports

chainer/training/extension.py, chainer/training/trainer.py
=> [backport] Add docs for `Extension.name`

tests/chainer_tests/links_tests/model_tests/test_vision.py
Fix the issue introduced in #4912.
=> Fix test failure of TestResNetLayers

chainer/backends/intel64.py, docs/source/reference/util/cuda.rst
=> [backport] Add iDeep to backend docs

examples/vae/net.py
typically people use beta to refer to this value. https://arxiv.org/abs/1804.03599
- Does you code conform to our coding guidelines?
- Also take a look at [our compatibility policy](https://docs.chainer.org/en/stable/compatibility.html).
=> Rename VAE hyperparameter `C` to `beta` in the example

chainer/functions/connection/convolution_2d.py
=> Avoid numpy.ascontiguousarray when iDeep is used

docs/source/glance.rst
=> [backport] Fix cross-link and format of Chainer at a glance documentation

tests/chainer_tests/functions_tests/math_tests/test_erfinv.py
=> Fix a class name in `test_erfinv`

chainer/functions/loss/hinge.py, tests/chainer_tests/functions_tests/loss_tests/test_hinge.py
This PR follows #4582 to support all float dtypes in `F.hinge`.
=> Support all float dtypes in `F.hinge`

chainer/datasets/__init__.py, chainer/datasets/pickle_dataset.py, docs/source/reference/datasets.rst, tests/chainer_tests/datasets_tests/test_pickle_dataset.py
I implemented `PickleDataset` that uses a simple file to store data and uses Pickle to serialize data. Users can use it to improve read performance.
=> Implemented dataset using pickle

chainer/functions/math/prod.py, tests/chainer_tests/functions_tests/math_tests/test_prod.py
=> Use `F.cumprod` in backward of `F.prod`

tests/chainer_tests/datasets_tests/test_pickle_dataset.py
This PR fixes Windows test failure introduced by #4581.
=> Fix windows test failure

chainer/distributions/normal.py
Use `erfc` to avoid cancellation. This may relate to #5183.
=> Avoid cancellation in Normal

chainer/functions/__init__.py, chainer/functions/math/erfcx.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_erfcx.py
=> Implement erfcx

chainer/functions/math/erfinv.py
=> Fix docstring of erfinv

.gitignore
=> [backport] Add .pytest_cache/ to .gitignore

chainer/functions/__init__.py, chainer/functions/pooling/roi_align_2d.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/pooling_tests/test_roi_align_2d.py
`roi_align_2d` is an extension of `roi_pooling_2d`, which is often used for object detection.
I use this function to reproduce [Mask R-CNN paper](https://arxiv.org/abs/1703.06870) result [here](https://github.com/wkentaro/chainer-mask-rcnn#coco-results).
=> Add roi_align_2d function

setup.py
Doctest requires sphinx to run.
=> Add sphinx to doctest requirements

tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
=> [backport] Simplify and stabilize softmax_cross_entropy test

docs/source/tips.rst
=> Change iDeep in tips.rst to Chainer Backend for Intel Architecture

tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
=> Fix occasional test failure of `contrastive`

chainer/functions/math/basic_math.py, chainer/functions/math/batch_l2_norm_squared.py, chainer/functions/math/clip.py, chainer/functions/math/cumprod.py, chainer/functions/math/cumsum.py, chainer/functions/math/det.py, chainer/functions/math/digamma.py, chainer/functions/math/einsum.py, chainer/functions/math/erf.py, chainer/functions/math/erfc.py, chainer/functions/math/erfinv.py, chainer/functions/math/exponential.py, chainer/functions/math/exponential_m1.py, chainer/functions/math/fft.py, chainer/functions/math/fmod.py, chainer/functions/math/hyperbolic.py, chainer/functions/math/inv.py
Partially addressed https://github.com/chainer/chainer/issues/4969, improving type check messages for function nodes.
=> Improve type check messages for some math functions

tests/chainer_tests/functions_tests/normalization_tests/test_l2_normalization.py
=> [backport] Fix occasional test failure of `l2normalize`

chainer/functions/loss/softmax_cross_entropy.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
=> [backport] Fix cpu codes of indexing in `F.softmax_cross_entropy`

chainer/functions/__init__.py, chainer/functions/math/ndtr.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_ndtr.py
Add cumulative distribution function of normal distribution.
=> Add `F.ndtr`

chainer/functions/__init__.py, chainer/functions/math/log_ndtr.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_log_ndtr.py
Add `log_ndtr`. This PR depends on #5237.
=> Add log_ndtr

chainer/functions/activation/log_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
I implemented `axis` argument for `log_softmax` like `softmax`.
=> Support axis argument for log_softmax

chainer/functions/math/logsumexp.py, tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py
=> [backport] Support 0-dim input in `F.logsumexp`

chainer/functions/__init__.py, chainer/functions/math/ndtri.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/math_tests/test_ndtri.py
https://github.com/chainer/chainer/pull/5242#issuecomment-414215183
=> Add `F.ndtri`

chainer/functions/math/lgamma.py, chainer/functions/math/linear_interpolate.py, chainer/functions/math/logarithm_1p.py, chainer/functions/math/logsumexp.py, chainer/functions/math/matmul.py, chainer/functions/math/maximum.py, chainer/functions/math/minimum.py, chainer/functions/math/minmax.py, chainer/functions/math/polygamma.py, chainer/functions/math/prod.py, chainer/functions/math/sparse_matmul.py, chainer/functions/math/sqrt.py, chainer/functions/math/square.py, chainer/functions/math/squared_difference.py, chainer/functions/math/sum.py, chainer/functions/math/tensordot.py, chainer/functions/math/trigonometric.py, chainer/functions/noise/dropout.py, chainer/functions/noise/gaussian.py, chainer/functions/noise/simplified_dropconnect.py
=> Improve type check messages for some functions

tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
=> [backport] Fix occasional test failure of `contrastive`

chainer/distributions/normal.py
Use `ndtri` in normal distribution.
=> Use ndtri in normal distribution

tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
=> [backport] Trivial fix for parameterized test case of F.contrastive

docs/source/reference/iterators.rst
=> Fix toc level of Order sampler examples

chainer/functions/__init__.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/pooling_tests/test_roi_align_2d.py
This is a tentative fix (should be removed in #5198) to keep compatibility between betas.
=> Rename roi_align_2d to roi_average_align_2d

docs/source/glance.rst
=> [backport] Improve Iterator description in Chainer at a glance documentation

tests/chainer_tests/distributions_tests/test_categorical.py
I removed extreme test of `D.Categorical` temporarily.
=> Comment out extreme test of D.Categorical

chainer/functions/math/sparse_matmul.py
=> Avoid mutating in_params of coo_matmul

chainer/training/trainer.py, docs/source/guides/serializers.rst, examples/seq2seq/seq2seq.py
=> [backport] Fix seq2seq example to support `--resume` option and improve docs

chainer/distributions/categorical.py
Use #5215 to improve https://github.com/chainer/chainer/pull/5028#discussion_r205992337
=> Use log_softmax in `D.Categorical`

chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_nd.py, tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py
=> [backport] Support None for the in_channels argument in ConvolutionND/DeconvolutionND

chainer/links/normalization/batch_normalization.py
=> Add explanation about switching the three modes.

chainer/link.py
=> [v4] Amend chainer.Chain document

chainer/link.py
=> Amend chainer.Chain document

examples/cifar/train_cifar.py
The original code takes a snapshot only at the last epoch.
I fixed the code to take a snapshot at each epoch.
=> fix extensions.snapshot()

examples/cifar/train_cifar.py
=> [backport] Fix snapshot trigger in CIFAR example

chainer/function_hook.py
=> [backport] Fix `FunctionHook` documentation

chainer/function_hooks/debug_print.py
=> Fix PrintHook fails if grad is None

docker/python2/Dockerfile, docker/python3/Dockerfile
**This PR is for v4 branch.**
This intends to use CuPy minor versions (hot fix).
=> Fix Dockerfile in v4 branch to use CuPy minor versions

chainer/function_hooks/debug_print.py
=> [backport] Fix PrintHook fails if grad is None

chainer/links/connection/gru.py, chainer/links/connection/lstm.py, chainer/links/connection/mgu.py, chainer/links/connection/peephole.py, chainer/links/connection/zoneoutlstm.py, chainer/links/loss/black_out.py, chainer/links/loss/hierarchical_softmax.py, chainer/links/loss/negative_sampling.py
=> Make link.to_*pu return self

chainer/links/connection/gru.py, chainer/links/connection/lstm.py, chainer/links/connection/mgu.py, chainer/links/connection/peephole.py, chainer/links/connection/zoneoutlstm.py, chainer/links/loss/black_out.py, chainer/links/loss/hierarchical_softmax.py, chainer/links/loss/negative_sampling.py
=> [backport] Make link.to_*pu return self

chainer/functions/array/where.py, chainer/functions/math/maximum.py, chainer/functions/math/minimum.py, tests/chainer_tests/functions_tests/array_tests/test_where.py, tests/chainer_tests/functions_tests/math_tests/test_maximum.py, tests/chainer_tests/functions_tests/math_tests/test_minimum.py
=> Automatic broadcast: minimum, maximum, where

tests/chainer_tests/distributions_tests/test_multivariate_normal.py
Fix a part of https://github.com/chainer/chainer/issues/3766#issuecomment-414241013
=> Stabilize backward tests in TestTriangularInv

chainer/links/connection/convolution_nd.py, tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py, tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py
This PR fixes a bug where the shape of `W` in `L.ConvolutionND` is wrong.
=> Fix a shape of W in L.ConvolutionND

chainer/iterators/__init__.py, chainer/iterators/dali_iterator.py, docs/source/reference/iterators.rst, examples/imagenet/dali_util.py, examples/imagenet/train_imagenet.py
This PR is based on #5067.
- Added experimental warning
- Added `dali_util.py`
=> [takeover] Support DALI

.travis.yml
Stable branch has been switched to `v5`. This change lets Travis look that.
=> Travis test against v5 branch

docs/source/chainermn/installation/guide.rst, docs/source/chainermn/tutorial/tips_faqs.rst
In #5226, I found some docs are not synced with commit https://github.com/chainer/chainermn/commit/f66d35e56810d7e67c509ffb05db3e3a816e6e7b
ChainerMN code is OK.
=> Merge ChainerMN docs from master branch

setup.py
=> [backport] Fix typo in setup.py

.travis.yml
=> [backport] Travis test against v5 branch

chainermn/functions/point_to_point_communication.py, chainermn/links/batch_normalization.py, chainermn/links/n_step_rnn.py
=> [backport] Remove unnecessary version checking in ChainerMN

chainer/distributions/beta.py, tests/chainer_tests/distributions_tests/test_beta.py
=> Fix beta distribution

chainer/optimizers/adam.py
- Does you code conform to our coding guidelines?
- Also take a look at [our compatibility policy](https://docs.chainer.org/en/stable/compatibility.html).
=> Update Adam for iDeep 2.0

chainer/optimizers/adam.py
=> [backport] Update Adam for iDeep 2.0

chainer/distributions/beta.py
=> [backport] add document for `D.Beta`

chainer/functions/loss/discriminative_loss.py
=> Fix docstring of discriminative loss

chainer/backends/cuda.py, chainer/links/model/vision/resnet.py, tests/chainer_tests/functions_tests/activation_tests/test_lstm.py, tests/chainer_tests/functions_tests/activation_tests/test_tanh.py, tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py, tests/chainer_tests/test_variable.py
=> [backport] Fix some E241 style errors

docs/source/chainermn/installation/guide.rst, docs/source/chainermn/tutorial/tips_faqs.rst
=> [backport] Merge ChainerMN docs from master branch

chainer/reporter.py
=> [backport] Fix typos in doc of `chainer.report`

docs/source/reference/configuration.rst
=> [backport] Fix a ReST escape

chainer/distributions/log_normal.py, chainer/distributions/utils.py, chainer/functions/loss/discriminative_loss.py, chainer/utils/precision.py, tests/chainer_tests/distributions_tests/test_bernoulli.py, tests/chainer_tests/distributions_tests/test_beta.py, tests/chainer_tests/distributions_tests/test_categorical.py, tests/chainer_tests/distributions_tests/test_dirichlet.py, tests/chainer_tests/distributions_tests/test_kldivergence.py, tests/chainer_tests/distributions_tests/test_laplace.py, tests/chainer_tests/distributions_tests/test_log_normal.py, tests/chainer_tests/distributions_tests/test_multivariate_normal.py, tests/chainer_tests/distributions_tests/test_normal.py, tests/chainer_tests/distributions_tests/test_pareto.py, tests/chainer_tests/distributions_tests/test_uniform.py, tests/chainer_tests/distributions_tests/test_utils.py
=> Fix style of imports

chainer/distributions/log_normal.py, chainer/distributions/utils.py, tests/chainer_tests/distributions_tests/test_bernoulli.py, tests/chainer_tests/distributions_tests/test_beta.py, tests/chainer_tests/distributions_tests/test_categorical.py, tests/chainer_tests/distributions_tests/test_dirichlet.py, tests/chainer_tests/distributions_tests/test_kldivergence.py, tests/chainer_tests/distributions_tests/test_laplace.py, tests/chainer_tests/distributions_tests/test_log_normal.py, tests/chainer_tests/distributions_tests/test_multivariate_normal.py, tests/chainer_tests/distributions_tests/test_normal.py, tests/chainer_tests/distributions_tests/test_uniform.py, tests/chainer_tests/distributions_tests/test_utils.py
=> [backport] Fix style of imports

chainer/graph_optimizations/static_graph_utilities.py
=> [backport] fix typo in static graph optimization

chainer/sequential.py
- Use doctest
- Avoid tab characters
- Fix syntax
=> Fix docstring of chainer.Sequential

chainer/sequential.py
=> [backport] Fix docstring of chainer.Sequential

chainer/functions/connection/convolution_2d.py
=> Validate shape of weight in F.convolution_2d

chainer/training/extensions/warmup_shift.py
=> [backport] Fix docstrings to follow OpenStack Style Guidelines 

docs/source/index.rst, docs/source/install.rst
=> [backport] Add Google Colaboratory installation steps and link to community examples

chainer/function_node.py, tests/chainer_tests/test_function_node.py
`func.outputs` is a tuple of `weakref`s of `VariableNode`s.
=> Fix FunctionNode.retained_outputs

chainer/links/caffe/caffe_function.py
=> [backport] [bugfix] CaffeFunction ignores pad_w

chainer/function_node.py, tests/chainer_tests/test_function_node.py
=> [backport] Fix FunctionNode.retained_outputs

tests/chainer_tests/test_gradient_check.py
=> [backport] Relax tolerance of check_double_backward test

chainermn/communicators/mpi_communicator_base.py
=> [backport] Dedup assertion in MpiCommunicatorBase.allreduce

examples/imagenet/train_imagenet_data_parallel.py
there is a minor bug in the example code.
=> Fix `train_imagenet_data_parallel.py` example cannot be run

chainer/functions/activation/softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
=> [backport] Fix `F.softmax` and `F.log_softmax` with `axis=-1` on gpu

chainer/variable.py
=> Consistently use `Variable.array` instead of `.data`

chainer/backends/cuda.py, docs/source/chainermn/installation/guide.rst
=> [backport] Fix dead fragments to CuPy docs

chainer/_runtime_info.py, chainer/backends/intel64.py, docs/source/tips.rst
=> [backport] Update packaging for iDeep 2.0

chainer/functions/__init__.py, chainer/functions/loss/discriminative_loss.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/loss_tests/test_discriminative_margin_based_clustering_loss.py
=> [backport] Add discriminative margin based clustering loss

docs/source/glance.rst, examples/glance/glance.py
- Removes weird blank lines
- Adds line numbers
=> Improve code sample appearance in docs

docs/source/glance.rst, examples/glance/glance.py
=> [backport] Improve code sample appearance in docs

chainer/functions/loss/huber_loss.py
=> [backport] Fix backward of HuberLoss

chainer/functions/loss/discriminative_loss.py
=> [backport] Fix docstring of discriminative loss

docs/source/upgrade.rst
=> [backport] Improve FunctionNode upgrade guide

examples/mnist/train_mnist_custom_loop.py
Other MNIST examples use `SerialIterator`.
=> Use `SerialIterator` in `train_mnist_custom_loop.py`

chainer/functions/activation/softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
=> [backport] Support negative `axis` for `F.softmax`

chainer/functions/math/basic_math.py, tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
* Removed unnecessary preprocessing
* Use `math.log` in preference to `numpy.log` (`math` is faster)
* ~~Changed class names~~
=> Simplify scalar handling in `basic_math`

chainer/functions/normalization/batch_renormalization.py, chainer/links/normalization/batch_renormalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
=> [backport] In-place update in `F.batch_renormalization`

docs/source/install.rst
=> [backport] Add support for NumPy 1.15 in docs

docs/source/upgrade.rst
=> Add upgrade guide for get_device_from_array

docs/source/upgrade.rst
=> [backport] Add upgrade guide for get_device_from_array

docker/python2/Dockerfile, docker/python3/Dockerfile, docs/source/upgrade.rst
=> [backport] Update base docker image

tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py
Test code has been modified since when we confirmed Python 3.7 compatibility.
=> Fix test for python 3.7

tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py
=> [backport] Fix test for python 3.7

chainer/reporter.py, chainer/testing/backend.py, tests/chainer_tests/test_reporter.py
=> Fix `reporter.Summary` float value deserialization

README.md, chainermn_bibtex.txt
=> [backport] Add ChainerMN paper to references

chainer/training/triggers/minmax_value_trigger.py, tests/chainer_tests/training_tests/triggers_tests/test_minmax_trigger.py
Hi, I want to resume training from a snapshot where I'm using ```MinValueTrigger```/```MaxValueTrigger```, so I've written serialization code for ```BestValueTrigger```.
Some tests are failing, but it seems to be due to #5401.
=> Serialize BestValueTrigger

chainer/reporter.py, chainer/testing/backend.py, tests/chainer_tests/test_reporter.py
=> [backport] Fix `reporter.Summary` float value deserialization

chainer/functions/util/forget.py
=> Fix docstring of `F.forget`

chainer/training/updaters/multiprocess_parallel_updater.py, chainer/training/updaters/parallel_updater.py, chainer/training/updaters/standard_updater.py
=> [backport] Fix typo in updaters

setup.cfg, tests/chainer_tests/utils_tests/test_type_check.py
Chainer counterpart for https://github.com/cupy/cupy/pull/1755
=> Fix test warnings in NumPy 1.15

examples/mnist/train_mnist_custom_loop.py
=> [backport] Use `SerialIterator` in `train_mnist_custom_loop.py`

chainer/functions/loss/negative_sampling.py, chainer/links/loss/negative_sampling.py, tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py, tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
Refactored test of `L.NegativeSampling` as well.
=> Add `return_samples` argument to `F.negative_sampling` and `L.NegativeSampling`

chainer/functions/loss/negative_sampling.py, tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
=> [backport] Support all float dtypes in `F.negative_sampling`

chainer/_version.py, docs/source/install.rst
Improve documentation and environment check for ideep (see #5592).
=> Improve iDeep version checking

docs/source/install.rst
=> [v5] Update docs for iDeep constraints

docs/source/guides/extensions.rst
=> extensions guide: method to implement is __call__

chainer/functions/__init__.py, chainer/functions/pooling/roi_average_pooling_2d.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_pooling_2d.py
EDIT:
- add `roi_average_pooling_2d`
~~- rename `roi_pooling_2d` -> `roi_max_pooling_2d`~~
~~- add `roi_pooling_2d` with `operation` arg for interface~~
=> Add `F.roi_average_pooling_2d`

docs/source/guides/extensions.rst
=> [backport] extensions guide: method to implement is __call__

chainer/functions/activation/slstm.py, tests/chainer_tests/functions_tests/activation_tests/test_slstm.py
I implement double backward of SLSTM function.
SLSTM still can not support higher-order derivatives,
but it supports double backward.
#4449
=> Implement double backward of SLSTM function

chainer/functions/pooling/roi_average_align_2d.py
update `roi_average_align_2d` doc to refer `roi_average_pooling_2d`
=> update roi_average_align_2d doc to refer roi_average_pooling_2d

docs/source/upgrade.rst, setup.py
* Upgrade guide for #5425
* Add requirement to setuptools as discussed in #5472
=> Require setuptools and add docs for #5425

chainer/functions/loss/negative_sampling.py, tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
=> Fix `F.negative_sampling` output dtype in CPU mode

chainer/functions/pooling/roi_average_align_2d.py
=> [backport] Update `F.roi_average_align_2d` doc to refer wrapper function

chainer/functions/__init__.py, chainer/functions/pooling/roi_max_pooling_2d.py, docs/source/reference/functions.rst, tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_pooling_2d.py
- add new interface function `roi_max_pooling_2d`
- add doc
- add test
this is related to #5285, #5198.
=> Add `F.roi_max_pooling_2d`

chainer/functions/array/resize_images.py, chainer/functions/array/spatial_transformer_sampler.py, chainer/functions/connection/linear.py, chainer/functions/evaluation/classification_summary.py, chainer/functions/evaluation/r2_score.py, chainer/functions/loss/ctc.py, chainer/functions/math/fft.py, chainer/testing/unary_math_function_test.py
=> [backport] Avoid unnecessary copy in `ndarray.astype`

chainer/functions/pooling/roi_average_align_2d.py, chainer/functions/pooling/roi_average_pooling_2d.py
Related to https://github.com/chainer/chainer/pull/5304#discussion_r229417576
This PR fixes args check in `roi_average_pooling_2d.py` and`roi_average_align_2d.py`.
@Hakuyume can you review this?
=> fix args check in roi_average_align_2d.py and roi_average_pooling_2d.py

chainer/functions/pooling/average_pooling_2d.py, chainer/functions/pooling/average_pooling_nd.py, chainer/functions/pooling/max_pooling_2d.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/pooling_2d.py, chainer/functions/pooling/pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
Please merge cupy/cupy#1735 first.
=> Simplify pooling with cuDNN

chainer/distributions/one_hot_categorical.py, tests/chainer_tests/distributions_tests/test_kldivergence.py
This PR follows up #5372 to add KL divergence test for `D.OneHotCategorical` .
=> Add KL divergence test for D.OneHotCategorical

chainer/_environment_check.py, docs/source/tips.rst
=> [backport] Update installation guide of numpy with openblas on macOS

chainer/testing/__init__.py
=> [backport] Import testing/backend.py definitions in testing/__init__.py

chainer/backends/cuda.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py, chainer/functions/noise/dropout.py
Please merge cupy/cupy#1734 first.
=> Avoid cuDNN handle around DropoutStates

chainer/link.py
=> [backport] Fix typo of example code in Chain docstring

chainer/backends/cuda.py, chainer/functions/activation/log_softmax.py, chainer/functions/activation/softmax.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py, chainer/functions/noise/dropout.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Please merge cupy/cupy#1736 first.
=> Simplify softmax with cuDNN

chainer/links/model/vision/resnet.py
=> Fix typo in resnet

chainer/backends/cuda.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/connection/n_step_rnn.py, chainer/functions/noise/dropout.py
=> [backport] Avoid cuDNN handle around DropoutStates

chainer/functions/activation/rrelu.py, tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
=> [backport] Fix test of `F.rrelu`

chainer/exporters/caffe.py, chainer/sequential.py
=> Fix typo in docstrings

chainer/exporters/caffe.py, chainer/sequential.py
=> [backport] Fix typo in docstrings

docs/source/conf.py, docs/source/reference/datasets.rst, docs/source/reference/links.rst
=> [backport] Include ChainerCV doc

chainer/functions/pooling/average_pooling_2d.py, chainer/functions/pooling/average_pooling_nd.py, chainer/functions/pooling/max_pooling_2d.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/pooling_2d.py, chainer/functions/pooling/pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py, tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py, tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
=> [backport] Simplify pooling with cuDNN

chainer/links/activation/simplified_dropconnect.py, chainer/links/activation/swish.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_2d.py, chainer/links/connection/deconvolution_nd.py, chainer/links/connection/deformable_convolution_2d.py, chainer/links/connection/depthwise_convolution_2d.py, chainer/links/connection/dilated_convolution_2d.py, chainer/links/connection/embed_id.py, chainer/links/connection/linear.py, chainer/links/connection/local_convolution_2d.py, chainer/links/connection/lstm.py, chainer/links/connection/n_step_rnn.py, chainer/links/connection/parameter.py, chainer/links/connection/peephole.py, chainer/links/connection/zoneoutlstm.py, chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py, chainer/links/normalization/group_normalization.py, chainer/links/normalization/layer_normalization.py, chainer/links/theano/theano_function.py
More consistent use of `Variable.array`.
Related PRs: #5386 #5488 #5495
=> More consistent use of Variable.array in codes under links

examples/wavenet/README.md, examples/wavenet/generate.py, examples/wavenet/modules.py, examples/wavenet/net.py, examples/wavenet/requirements.txt, examples/wavenet/train.py, examples/wavenet/utils.py
Add an example of mel-spectrogram vocoder using WaveNet based on https://github.com/dhgrs/chainer-Fast-WaveNet
I tested training with docker image chainer/chainer:v4.1.0-python3. After 600k iterations with default parameters, we can get audible results like [here](https://github.com/dhgrs/chainer/blob/wavenet_result/examples/wavenet/result.wav). This result was generated from a mel-spectrogram of a speaker in CMU Arctic Dataset and never be used in training.
=> Add WaveNet example

chainer/links/activation/simplified_dropconnect.py, chainer/links/activation/swish.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_2d.py, chainer/links/connection/deconvolution_nd.py, chainer/links/connection/deformable_convolution_2d.py, chainer/links/connection/depthwise_convolution_2d.py, chainer/links/connection/dilated_convolution_2d.py, chainer/links/connection/embed_id.py, chainer/links/connection/linear.py, chainer/links/connection/local_convolution_2d.py, chainer/links/connection/lstm.py, chainer/links/connection/n_step_rnn.py, chainer/links/connection/parameter.py, chainer/links/connection/peephole.py, chainer/links/connection/zoneoutlstm.py, chainer/links/model/vision/googlenet.py, chainer/links/model/vision/resnet.py, chainer/links/model/vision/vgg.py, chainer/links/normalization/group_normalization.py, chainer/links/normalization/layer_normalization.py, chainer/links/theano/theano_function.py
=> [backport] More consistent use of `Variable.array` in codes under links

chainer/dataset/convert.py
=> [backport] Overlap compute and transfer more

chainer/_backprop_utils.py
=> Fix docs for backprop_step

chainer/functions/activation/clipped_relu.py, docs/source/reference/functions.rst, docs/source/reference/variable.rst
Takeover #4887.
Close #5498.
Changes to each doc of function will be made after the idea is reviewed.
=> Add documentation of `ndarray`

chainer/functions/activation/clipped_relu.py
=> Simplify array type information fields in function documentation

chainer/functions/activation/log_softmax.py, chainer/functions/activation/softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py, tests/chainer_tests/functions_tests/activation_tests/test_softmax.py, tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
=> [backport] Simplify softmax with cuDNN

chainer/gradient_check.py, tests/chainer_tests/test_gradient_check.py
Added some consistency checks between `grad_outputs` and function outputs in `numerical_grad`.
Fixed some tests accordingly.
=> Add gradient consistency checks in `numerical_grad`

chainermn/communicators/mpi_communicator_base.py
=> Use chainer.utils.size_of_shape in ChainerMN

chainer/distributions/multivariate_normal.py, chainer/distributions/normal.py
=> [backport] Use automatic broadcasting instead of `F.repeat`

chainer/_backprop_utils.py
=> [backport] Fix docs for backprop_step

chainer/links/normalization/batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Fix #5682 . I have done test but I was not able to do multi-GPU test.
=> Fix BatchNormalization with lazy initialization fail on GPU #5682

chainer/functions/activation/clipped_relu.py, docs/source/reference/functions.rst, docs/source/reference/variable.rst
=> [backport] Add documentation of `ndarray`

chainer/distribution.py, chainer/distributions/bernoulli.py, chainer/distributions/beta.py, chainer/distributions/categorical.py, chainer/distributions/chisquare.py, chainer/distributions/dirichlet.py, chainer/distributions/exponential.py, chainer/distributions/gamma.py, chainer/distributions/gumbel.py, chainer/distributions/laplace.py, chainer/distributions/log_normal.py, chainer/distributions/multivariate_normal.py, chainer/distributions/normal.py, chainer/distributions/one_hot_categorical.py, chainer/distributions/pareto.py, chainer/distributions/poisson.py, chainer/distributions/uniform.py
=> Make docs in chainer.distribution* refer `ndarray`

.travis.yml, setup.cfg, setup.py
=> [backport] Update style check tools to the versions compatible with pycodestyle 2.4

chainer/gradient_check.py, tests/chainer_tests/test_gradient_check.py
=> [backport] Add gradient consistency checks in `numerical_grad`

chainer/distribution.py, chainer/distributions/bernoulli.py, chainer/distributions/beta.py, chainer/distributions/categorical.py, chainer/distributions/dirichlet.py, chainer/distributions/laplace.py, chainer/distributions/log_normal.py, chainer/distributions/multivariate_normal.py, chainer/distributions/normal.py, chainer/distributions/uniform.py
=> [backport] Make docs in chainer.distribution* refer `ndarray`

chainer/link.py, tests/chainer_tests/test_link_hook.py
=> [backport] Change `Link.add_hook` to return `self`

chainer/links/normalization/batch_normalization.py, tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
=> [backport] Fix BatchNormalization with lazy initialization fail on GPU #5682

chainerx_build_helper.py, docs/rtd_conda.yml, docs/source/conf.py, readthedocs.yml, setup.py
=> Build ChainerX on ReadTheDocs

.travis.yml
=> Return exitcode of `make html` to Travis

chainerx_cc/CMakeLists.txt, chainerx_cc/chainerx/routines/connection_test.cc, chainerx_cc/chainerx/routines/manipulation_test.cc, chainerx_cc/chainerx/routines/normalization_test.cc, chainerx_cc/chainerx/routines/pooling_test.cc
Checked without CUDA backend with:
* clang version 5.0.1-4
* clang version 6.0.0-1ubuntu2
=> Fixes for clang

docs/source/upgrade_v2.rst
=> [backport] Fix typo in v2 Upgrade Guide

chainermn/optimizers.py
This PR fixes bugs of MultiNodeOptimizer in ChainerMN.
=> Bugfix of MultiNodeOptimizer with loss scaling

examples/text_classification/train_text_classifier.py
=> [backport] Add test mode to text classification example

chainer/training/updaters/multiprocess_parallel_updater.py
=> fix side effect of MultiprocessParallelUpdater

chainer/utils/array.py
`_setitem` and `_getitem` workarounds for ChainerX does not support backpropagation.
It's better to strictly prohibit them when the arrays have graphs.
=> Forbid fallback get/setitem for arrays with backprop required

chainer/gradient_check.py
This PR sets the device with `chainer.using_device` during `gradient_check.check_backward`.
Some ChainerX workarounds are also resolved by this fix.
=> Switch device during gradient_check

chainer/links/loss/negative_sampling.py, tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
This PR follows #4582, making `L.NegativeSampling' support the default dtype.
=> Use default dtype in `L.NegativeSampling`

docs/source/index.rst
=> [backport] Fix wording in documentation

chainer/functions/activation/crelu.py, chainer/functions/activation/elu.py, chainer/functions/activation/hard_sigmoid.py, chainer/functions/activation/leaky_relu.py, chainer/functions/activation/log_softmax.py, chainer/functions/activation/lstm.py, chainer/functions/activation/maxout.py, chainer/functions/activation/prelu.py, chainer/functions/activation/relu.py, chainer/functions/activation/rrelu.py, chainer/functions/activation/selu.py, chainer/functions/activation/sigmoid.py, chainer/functions/activation/slstm.py, chainer/functions/activation/softmax.py, chainer/functions/activation/softplus.py, chainer/functions/activation/swish.py, chainer/functions/activation/tanh.py, chainer/functions/activation/tree_lstm.py
=> Make docs of activation functions refer `ndarray`

chainer/functions/math/clip.py, tests/chainer_tests/functions_tests/math_tests/test_clip.py
=> Remove `F.clip` type restriction

chainer/iterators/multiprocess_iterator.py
=> Add comment to MultiprocessIterator.__copy__

.gitignore
=> [backport] Fix `.gitignore` to avoid ignoring some necessary files

examples/pix2pix/README.md
=> [backport] Fix a couple of broken links from markdown files

chainer/links/model/vision/resnet.py
=> [backport] fix usage of downsample_fb in resnet

chainer/functions/connection/n_step_rnn.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_gru.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
=> [backport] Use new RNN implementation

docs/source/examples/cnn.rst
=> Add explanations for lenet5

examples/ptb/train_ptb_custom_loop.py, examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py
=> Use iter.reset() in ptb example

examples/ptb/train_ptb_custom_loop.py, examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py
=> [backport] Use `iter.reset()` in PTB example

chainer/functions/normalization/batch_normalization.py, chainer/functions/normalization/batch_renormalization.py, chainermn/functions/batch_normalization.py, tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
=> [backport] Simplify batch normalization with cuDNN

docs/source/examples/cnn.rst
=> [backport] Add explanations for lenet5

chainerx_cc/chainerx/routines/manipulation.cc, chainerx_cc/chainerx/routines/math.cc, chainerx_cc/chainerx/routines/normalization.cc, chainerx_cc/chainerx/routines/pooling.cc
=> Code enhancements: avoid array copies

docs/source/reference/initializers.rst
=> Add description for initializer dtype

chainer/dataset/convert.py, chainer/dataset/iterator.py, chainer/datasets/pickle_dataset.py, chainer/functions/array/repeat.py, chainer/functions/connection/n_step_lstm.py, chainer/functions/loss/contrastive.py, chainer/functions/loss/ctc.py, chainer/functions/loss/negative_sampling.py, chainer/functions/math/average.py, chainer/functions/math/inv.py, chainer/gradient_check.py, chainer/graph_optimizations/static_graph.py, chainer/iterators/multiprocess_iterator.py, chainer/iterators/multithread_iterator.py, chainer/iterators/serial_iterator.py, chainer/links/caffe/caffe_function.py, chainer/links/loss/hierarchical_softmax.py, chainer/links/model/classifier.py, chainer/testing/condition.py, chainer/training/extensions/parameter_statistics.py, chainer/training/extensions/variable_statistics_plot.py, chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc, docs/source/glance.rst, docs/source/reference/iterators.rst, tests/chainer_tests/functions_tests/connection_tests/test_n_step_lstm.py, tests/chainer_tests/utils_tests/test_type_check.py
I have made some small fixes to spelling and grammar across the whole codebase. I think these changes are rather uncontroversial.
I also added a clarifying sentence in the mushroom tutorial, maybe that needs to be checked for contents.
=> some small fixes to grammar and spelling

CODE_OF_CONDUCT.md
=> [backport] Add Code of Conduct

.travis.yml, scripts/ci/travis/run-tests.sh
Follow-up of #5858.
Simply separates Travis sequences as a file.
=> Refactor Travis script

chainer/function.py, chainer/function_node.py, tests/chainer_tests/test_backprop.py
ChainerX array attribute fallback for `chainer.Function` similar to #5745
=> Automatic ChainerX fallback of array attributes in `Function` 

chainer/datasets/sub_dataset.py, tests/chainer_tests/datasets_tests/test_sub_dataset.py
=> Accept splitting at the tail of dataset in `split_dataset`

chainer/function.py, chainer/function_node.py
`_is_chainex_fallback_mode` -> `_is_chainerx_fallback_mode`
=> Fix typo on internal attribute

docs/source/reference/static_graph.rst, docs/source/reference/static_graph_design.rst
=> [backport] Fix `static_graph` module path in documentation

docs/source/examples/mnist.rst, docs/source/examples/train_loop.rst, docs/source/guides/functions.rst, docs/source/guides/links.rst
=> [backport] Change `.data` to `.array` in Guides and Examples docs

chainer/functions/normalization/local_response_normalization.py
=> [backport] LocalResponseNormalization -> FunctionNode implementation

chainer/functions/connection/linear.py
`xW^\top + b` is so confusing.
=> Write "Wx + b" in the document of `Linear`.

chainer/functions/activation/relu.py
Fixes #5866. Some refactoring of code style is done as well.
=> Do not retain input on iDeep `F.relu`

chainer/functions/activation/leaky_relu.py, tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py
=> [backport] Fix broken `F.leaky_relu` grad when slope = 0

chainer/functions/connection/linear.py
=> [backport] Write "Wx + b" in the document of `Linear`.

chainer/functions/connection/embed_id.py, tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
=> [backport] Support all float dtypes in `F.embed_id`

chainerx_cc/chainerx/python/graph.cc, chainerx_cc/scripts/run-clang-tidy.sh
Related: #5867
Fixes for clang-tidy 6: #5901 (merged)
=> Fix for clang-tidy 7

chainer/functions/activation/crelu.py, chainer/functions/activation/elu.py, chainer/functions/activation/hard_sigmoid.py, chainer/functions/activation/leaky_relu.py, chainer/functions/activation/log_softmax.py, chainer/functions/activation/lstm.py, chainer/functions/activation/maxout.py, chainer/functions/activation/prelu.py, chainer/functions/activation/relu.py, chainer/functions/activation/rrelu.py, chainer/functions/activation/selu.py, chainer/functions/activation/sigmoid.py, chainer/functions/activation/slstm.py, chainer/functions/activation/softmax.py, chainer/functions/activation/softplus.py, chainer/functions/activation/swish.py, chainer/functions/activation/tanh.py, chainer/functions/activation/tree_lstm.py
=> [backport] Make docs of activation functions refer `ndarray`

chainer/functions/connection/bilinear.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/deconvolution_nd.py, chainer/functions/connection/deformable_convolution_2d_sampler.py, chainer/functions/connection/depthwise_convolution_2d.py, chainer/functions/connection/dilated_convolution_2d.py, chainer/functions/connection/embed_id.py, chainer/functions/connection/linear.py, chainer/functions/connection/local_convolution_2d.py, chainer/functions/connection/shift.py
=> [backport] Make docs of connection functions refer `ndarray`

chainer/links/loss/crf1d.py, tests/chainer_tests/links_tests/loss_tests/test_crf1d.py
=> [backport] Support custom initializer in links.CRF1d

tests/chainer_tests/test_gradient_check.py
This PR adjusts tolerance of a test of numerical gradient.
=> Adjust testing tolerance of numerical gradient

tests/chainer_tests/test_gradient_check.py
=> [backport] Adjust testing tolerance of numerical gradient

chainer/backends/_chainerx.py, chainer/functions/array/get_item.py, chainer/functions/array/scatter_add.py, chainer/functions/loss/negative_sampling.py, tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py, tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
Fixes `L.NegativeSampling` for ChainerX.
=> `L.NegativeSampling` ChainerX support

chainer/datasets/transform_dataset.py
=> [backport] Transform dataset documentation fix

docs/source/examples/dcgan.rst
This PR tries to improve the note in DCAN. See Issue #5908 for more details.
=> Update the note in DCGAN example to be compatible with the code.

setup.py
=> [backport] Check integrity of CuPy wheel for CUDA 10

chainer/functions/pooling/roi_pooling_2d.py
Use `FunctionNode` on `ROIPooling2D` instead of `Function`.
=> Use FunctionNode on ROIPooling2D

tests/chainer_tests/initializer_tests/test_normal.py, tests/chainer_tests/initializer_tests/test_orthogonal.py, tests/chainer_tests/initializer_tests/test_uniform.py
=> [backport] Test statistics of initializers

docs/source/examples/dcgan.rst
=> [backport] Update the note in DCGAN example to be compatible with the code.

chainer/functions/pooling/roi_pooling_2d.py
=> [backport] Use FunctionNode on ROIPooling2D

chainerx_cc/chainerx/cuda/cuda_device/memory.cc
=> Fix code formatting

chainer/functions/connection/n_step_rnn.py, tests/chainer_tests/functions_tests/connection_tests/test_n_step_rnn.py
=> [backport] Raise an appropriate error on cuDNN RNN backward in testing mode

chainer/testing/array.py, tests/chainer_tests/testing_tests/test_array.py
=> [backport] Fix error message of `testing.assert_allclose`

chainer/sequential.py, tests/chainer_tests/test_sequential.py
=> Add copyparams method to Sequential

docs/source/glance.rst
I found the introductory sentence to the code snippet that introduces the `trainer` quite confusing, so I rewrite it. Also I added one introductory sentence to the `Extensions` section. Please check if the explanation is appropriate and understandable, thanks.
=> Some small improvements to the Mushrooms example

chainer/links/connection/n_step_lstm.py, chainer/links/connection/n_step_rnn.py
=> Fix document in NStepLSTM/NStepRNN

chainer/links/connection/mgu.py
Neither 8eacd20e35f31f124da36759953a21b29871e72f nor a later merge commit fixed `StatefulMGU`
=> Override _to_device for consistency

docs/source/chainermn/installation/guide.rst
=> [backport] Improve installation guide of ChainerMN

chainer/functions/pooling/max_pooling_2d.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/pooling_2d.py, chainer/functions/pooling/pooling_nd.py
This change stops managing memory in max pooling specific manner for reducing memory usage on inference.
=> Stop managing memory in max pooling specific manner

scripts/ci/travis/run-tests.sh
=> Fix travis script to continue on failure in each step

chainer/functions/loss/vae.py, tests/chainer_tests/functions_tests/loss_tests/test_vae.py
Add feature based on #5939 .
I changed the name to 'mean' as it is more commonly used throughout the other parts of the documentation/code.
=> Add 'mean' value as an option for vae loss reduce

chainer/utils/precision.py, tests/chainer_tests/utils_tests/test_precision.py
=> [backport] Introduce `utils.mixed_presision` decorator

chainer/links/loss/negative_sampling.py, tests/chainer_tests/links_tests/loss_tests/test_negative_sampling.py
=> [backport] Use default dtype in `L.NegativeSampling`

chainer/functions/activation/rrelu.py, tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
=> Add type check for `r` arg of `F.rrelu`

chainer/function_hooks/timer.py, tests/chainer_tests/function_hooks_tests/test_timer.py
=> [backport] Use more precise timer in funciton_hooks/timer.py

tests/chainer_tests/functions_tests/loss_tests/test_ctc.py
=> [backport] Adjust testing tolerance of F.connectionist_temporal_classification

chainerx_cc/chainerx/python/CMakeLists.txt
Fix CMakeLists.txt related to CUDA specific Python bindings.
=> Fix CUDA specific Python binding

docs/source/chainerx/index.rst, docs/source/chainerx/tips.rst
Fixes #6018 .
Should be merged after the actual feature ~https://github.com/chainer/chainer/pull/5821~.
=> Document CuPy memory pool sharing

tests/chainer_tests/conftest.py
=> Test if the default CUDA device keeps being 0 after each test

chainer/link_hook.py, chainer/link_hooks/__init__.py, chainer/link_hooks/timer.py, docs/source/reference/links.rst, setup.py, tests/chainer_tests/link_hooks_tests/test_timer.py
=> [backport] add a naive TimerHook LinkHook.

tests/chainer_tests/conftest.py
=> [backport] Test if the default CUDA device keeps being 0 after each test

chainerx_cc/chainerx/cuda/memory_pool_test.cc, chainerx_cc/chainerx/testing/threading.h
Fixes the second problem of #5991
=> Fix FixedCapacityDummyAllocator in CUDA memory pool test

scripts/ci/chainerx/setup-ubuntu.sh
Fixes https://github.com/chainer/chainer/issues/5929.
=> Upgrade clang-tidy to 6.0

docs/source/examples/mnist.rst, docs/source/guides/serializers.rst
=> [backport] Fix wrong MNIST MLP anchor

tests/chainer_tests/functions_tests/array_tests/test_concat.py
Applies the function test case https://github.com/chainer/chainer/pull/3499.
=> Simplify `F.concat` test

chainerx_cc/chainerx/python/array.cc, tests/chainer_tests/functions_tests/activation_tests/test_crelu.py, tests/chainer_tests/functions_tests/activation_tests/test_elu.py
=> Simplify `F.crelu` and `F.elu` test

chainer/links/model/classifier.py
=> fix typo in classifier.py

examples/seq2seq/seq2seq.py
=> [backport] Fix seq2seq example

chainerx_cc/chainerx/routines/connection.cc, chainerx_cc/chainerx/routines/connection_test.cc
Extension of https://github.com/chainer/chainer/pull/6066 (pooling) to convolutions.
~Depends on https://github.com/chainer/chainer/pull/6064.~
=> Validate Conv, ConvTranspose stride

chainerx_cc/chainerx/routines/pooling.cc, chainerx_cc/chainerx/routines/pooling_test.cc
Fixes https://github.com/chainer/chainer/issues/6025.
~Depends on https://github.com/chainer/chainer/pull/6064.~
=> Validate `{Max,Average}Pool` `kernel_size` and `stride`

chainer/training/updaters/multiprocess_parallel_updater.py
=> Reduce memory usage in `MultiprocessParallelUpdater`

chainer/training/updaters/multiprocess_parallel_updater.py
=> [backport] Reduce memory usage in `MultiprocessParallelUpdater`

scripts/ci/travis/run-step.sh, scripts/ci/travis/run-tests.sh, scripts/ci/travis/steps.sh
=> Fix Travis CI ignoring non-last command errors in each step

scripts/ci/travis/run-tests.sh, scripts/ci/travis/steps.sh, tests/chainerx_tests/acceptance_tests/conftest.py
=> Run ChainerX python tests in Travis CI

.travis.yml, scripts/ci/travis/run-tests.sh, scripts/ci/travis/steps.sh
=> Enable ChainerX C++ test in Travis CI

chainerx.md
The section here has been moved to the docs.
=> Remove anchor to non-existing section

chainer/optimizers/adam.py, chainer/optimizers/corrected_momentum_sgd.py, chainer/optimizers/momentum_sgd.py
Remove unnecessary shape checks because these optimizers work on any shape of parameters.
=> Use ideep in optimizers properly

docs/source/install.rst
=> [backport] Document NumPy 1.16 support

chainer/training/updaters/multiprocess_parallel_updater.py
=> [backport] Fix cupy import failure detection

docs/source/guides/index.rst, docs/source/index.rst, docs/source/reference/index.rst
=> Reorganize documentation for easier access to tutorials and examples

chainer/backends/cuda.py
=> CuPy cannot be enabled when cuDNN is unavailable

.travis.yml
=> Remove Travis macOS Py34 job

chainer/optimizers/adam.py, chainer/optimizers/corrected_momentum_sgd.py, chainer/optimizers/momentum_sgd.py
=> [backport] Use ideep in optimizers properly

examples/chainermn/mnist/train_mnist_dual_parallel.py
=> [backport] Refactor `train_mnist_dual_parallel.py`

tests/chainermn_tests/communicator_tests/test_communicator.py, tests/chainermn_tests/conftest.py
=> [backport] Fix chainermn tests

docs/source/guides/index.rst, docs/source/index.rst, docs/source/reference/index.rst
=> [backport] Reorganize documentation for easier access to tutorials and examples

chainer/dataset/iterator.py, chainer/iterators/multiprocess_iterator.py, chainer/iterators/multithread_iterator.py
=> Call `Iterator.finalize` from `__del__` and `__exit__`

chainer/training/extensions/variable_statistics_plot.py
=> Do not compare `xp` with `numpy` for cupy code path (cont.)

chainerx_cc/chainerx/array.h, chainerx_cc/chainerx/array_test.cc
=> Check Array constructor for nullptr

chainerx/_docs/backprop.py, chainerx_cc/chainerx/array.cc, chainerx_cc/chainerx/array.h, chainerx_cc/chainerx/python/backward.cc, tests/chainerx_tests/unit_tests/test_backward.py
Python binding `chainerx.grad` for the corresponding C++ implementation `chainerx::Grad`.
=> `chainerx.grad` Python binding

chainer/function_node.py, chainerx_cc/chainerx/backward_builder.cc, chainerx_cc/chainerx/python/chainer_interop.cc, tests/chainer_tests/test_backprop.py
Fixes #6120
~(Depends on #6121)~
=> Support FunctionNode None inputs in ChainerX 

appveyor.yml
=> Remove commented-out Py34 matrix from AppVeyor

appveyor.yml, scripts/ci/chainerx/jenkins/run.sh, scripts/ci/steps.sh, scripts/ci/travis/run-tests.sh, scripts/ci/travis/steps.sh
=> Stop mypy in CIs

setup.cfg, tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
#5949 left uncaught `FutureWarning`s.
=> Fix filtering `FutureWarning`

chainer/datasets/ptb.py
Fixes https://github.com/chainer/chainer/issues/6148.
=> Fix old and broken PTB url

chainer/datasets/ptb.py
=> [backport] Fix old and broken PTB url

tests/chainer_tests/functions_tests/activation_tests/test_tanh.py
This PR rewrites `functions.tanh`.
rel: #6071
=> Simplify `F.tanh` test

chainer/links/connection/deconvolution_2d.py, tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
=> Add dilate argument to L.Deconvolution2D

docs/source/upgrade.rst
=> [backport] Add upgrade guide for use of forward method

tests/chainer_tests/functions_tests/activation_tests/test_sigmoid.py
This PR aims at rewriting sigmoid function test.
rel: #6071
=> Simplify `F.sigmoid` test

tests/chainer_tests/functions_tests/loss_tests/test_mean_squared_error.py
Applies the function test case https://github.com/chainer/chainer/pull/3499.
=> Simplify `F.mean_squared_error` test

examples/seq2seq/README.md
This PR makes a minor fix on README of seq2seq example.
=> Minor fix on README of seq2seq example

examples/seq2seq/README.md
=> [backport] Minor fix on README of seq2seq example

tests/chainer_tests/functions_tests/activation_tests/test_hard_sigmoid.py
=> simplify `F.hard_sigmoid` test

chainer/functions/activation/rrelu.py, chainer/functions/loss/vae.py, chainer/functions/noise/simplified_dropconnect.py, chainer/functions/pooling/max_pooling_2d.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/upsampling_2d.py, chainer/functions/util/forget.py
=> Make docs of functions refer `ndarray`

chainer/dataset/convert.py, chainer/function.py, chainer/function_hook.py, chainer/function_node.py, chainer/initializer.py, chainer/initializers/__init__.py, chainer/initializers/constant.py, chainer/links/activation/simplified_dropconnect.py, chainer/links/connection/gru.py, chainer/links/connection/lstm.py, chainer/links/normalization/batch_normalization.py, chainer/utils/sparse.py, chainer/variable.py
=> [backport] Add references for n-dimensional arrays

docs/source/imports.rst
=> [backport] Add imports of initializers and math, required in "Define your own function" examples

chainer/optimizer.py
=> Fix ChainerX fallback for replaced optimizer state

examples/imagenet/README.md
=> [backport] Imagenet README.md typo

chainer/datasets/ptb.py
Docstrings can contain long URLs.
=> Update URL of PTB dataset

chainer/datasets/svhn.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_rnn.py, chainer/functions/loss/negative_sampling.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_2d.py, chainer/links/connection/deconvolution_nd.py, chainer/links/connection/mlp_convolution_2d.py, chainer/links/connection/n_step_rnn.py, chainer/training/extensions/_snapshot.py, chainer/variable.py
https://github.com/chainer/chainer/pull/6182#issuecomment-460939096
This PR also fixes the link to `` :class:`~chainer.datasets.TupleDataset` ``
=> Avoid `# NOQA` in docstrings

chainer/datasets/ptb.py
=> [backport] Update URL of PTB dataset

chainerx_cc/chainerx/macro.h
=> Write comment about `CHAINERX_VISIBILITY_HIDDEN`

tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
=> Rewrite the tests of `F.average_pooling_2d`

tests/chainer_tests/functions_tests/activation_tests/test_selu.py
Simplified F.selu test using testing.FunctionTestCase.
Ref. #6071
=> Simplify `F.selu` test

chainer/functions/activation/relu.py
=> [backport] Improve `F.relu` performance with CuPy

chainer/_backprop_utils.py
This improves the performance of backprop.
19.1ms -> 16.3ms (using the same measurement as #6263)
=> Avoid `contextmanager` in backprop

chainer/variable.py
This PR is performance improvement that relates #6016.
=> Use `_has_chainerx_array` in `Variable`

chainer/variable.py
`get_variable` is called many times.
=> Improve `get_variable` performance

chainer/exporters/caffe.py, tests/chainer_tests/exporters_tests/test_caffe.py
Add group option value of Convolution2D to caffe exporter
=> add group option value of Convolution2D to Caffe exporter

chainer/exporters/caffe.py, chainer/links/caffe/caffe_function.py, tests/chainer_tests/exporters_tests/test_caffe.py, tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
I implement Caffe Sigmoid layer.
=> Add support for importing and exporting Caffe Sigmoid layer

chainerx_cc/chainerx/python/routines.cc, chainerx_cc/chainerx/routines/math.cc, chainerx_cc/chainerx/routines/math.h, chainerx_cc/chainerx/routines/math_test.cc, tests/chainerx_tests/unit_tests/routines_tests/test_math.py
=> Support ChainerX TrueDivide for integer types

chainer/exporters/caffe.py, chainer/links/caffe/caffe_function.py, tests/chainer_tests/exporters_tests/test_caffe.py, tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
=> [backport] Add support for importing and exporting Caffe Sigmoid layer

chainer/exporters/caffe.py, tests/chainer_tests/exporters_tests/test_caffe.py
=> [backport] add group option value of Convolution2D to Caffe exporter

chainer/functions/activation/rrelu.py, chainer/functions/loss/vae.py, chainer/functions/noise/simplified_dropconnect.py, chainer/functions/pooling/max_pooling_2d.py, chainer/functions/pooling/max_pooling_nd.py, chainer/functions/pooling/upsampling_2d.py, chainer/functions/util/forget.py
=> [backport] Make docs of functions refer `ndarray`

chainer/_backprop_utils.py, chainer/function_node.py, chainer/variable.py, tests/chainer_tests/test_backprop_utils.py
I use #6263.
before
```
25958.642209880054 us
```
after
```
22730.355970561504 us
```
=> Pass debug flag to `backprop_step`

chainer/iterators/multiprocess_iterator.py
=> Revert "skip MultiprocessIterator finalization at exit"

chainer/function.py, tests/chainer_tests/test_function_node.py
=> Make Chainer backprop modes affect ChainerX counterparts

chainer/__init__.py, chainer/configuration.py, chainer/functions/normalization/batch_normalization.py
=> [backport]  Reduce `chainer.is_debug()` overhead

chainer/_backprop_utils.py, chainer/function.py, chainer/variable.py
Removed `is_var_gx` argument, etc.
=> Simplify `_check_grad_type`

examples/seq2seq/seq2seq.py
=> Remove `PrintReport` entries in seq2seq example

chainerx_cc/chainerx/native/native_device/reduction.cc
=> Improve accuracy of ChainerX native float16 Sum

tests/chainer_tests/functions_tests/activation_tests/test_softplus.py
Simplifies `test_softplus` by using `testing.FunctionTestCase`
Fixes part of issue #6071
Passes all tests on my Ubuntu 16.04 system.
=> test_softplus : Simplify `F.softplus` test

chainer/function_node.py, chainer/variable.py
I use #6263 
before
22.832 ms
after
21.415 ms
=> Improve hook handling in backward

chainer/variable.py
=> [backport] Fix warning message for backward on a scalar array

chainer/utils/type_check.py, docs/source/install.rst
Partially fixes https://github.com/chainer/chainer/issues/6131.
=> Update docs for Python 3.4 end-of-life

chainer/functions/connection/convolution_nd.py, chainer/functions/connection/deconvolution_nd.py
=> Use `utils.size_of_shape` in `F.convolution_nd` and `F.deconvolution_nd`

chainer/testing/function.py, tests/chainerx_tests/op_utils.py, tests/chainerx_tests/unit_tests/routines_tests/test_connection.py, tests/chainerx_tests/unit_tests/routines_tests/test_math.py
=> ChainerX test tool for ops

chainermn/iterators/__init__.py, chainermn/iterators/synchronized_iterator.py, docs/source/chainermn/reference/index.rst, tests/chainermn_tests/iterators_tests/test_iterator_compatibility.py, tests/chainermn_tests/iterators_tests/test_synchronized_iterator.py
As Travis test for #5396 fails with unknown reason I'm reopening with latest master.
=> Add Synchronized Iterator (Rebased version of #5396)

examples/seq2seq/seq2seq.py
=> [backport] Remove `PrintReport` entries in seq2seq example

tests/chainer_tests/functions_tests/activation_tests/test_maxout.py
Simplified F.maxout test using testing.FunctionTestCase.
Ref. #6071
=> Simplify `F.maxout` test

tests/chainer_tests/functions_tests/math_tests/test_sum.py
Simplified F.sum test using testing.FunctionTestCase.
Ref. #6071
=> Simplify `F.sum` test

tests/chainer_tests/functions_tests/activation_tests/test_leaky_relu.py
Simplified F.leaky_relu test using testing.FunctionTestCase.
Ref. #6071
=> Simplify `F.leaky_relu` test

chainer/datasets/svhn.py, chainer/functions/connection/convolution_2d.py, chainer/functions/connection/deconvolution_2d.py, chainer/functions/connection/n_step_gru.py, chainer/functions/connection/n_step_rnn.py, chainer/links/connection/convolution_2d.py, chainer/links/connection/convolution_nd.py, chainer/links/connection/deconvolution_2d.py, chainer/links/connection/deconvolution_nd.py, chainer/links/connection/mlp_convolution_2d.py, chainer/variable.py
=> [backport] Avoid `# NOQA` in docstrings

docs/source/chainermn/installation/troubleshooting.rst
The content was old so I fixed it.
=> Fix ChainerMN Step-by-Step Troubleshooting

tests/chainerx_tests/op_utils.py
=> Document ChainerX op test tool
