chainer/chainer

- docs/source/chainermn/reference/index.rst
> Add chainermn.links.create_mnbn_model document

- chainer/backends/cuda.py
CuPy provides thread local stream.
> Simplify `_array_to_gpu` with stream argument

- .travis.yml
Modifies job names to make it easier to grasp what's being tested.
> Write test types in Travis CI job names

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/arithmetic.cu
- chainerx_cc/chainerx/cuda/float16.cuh
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/arithmetic.cc
- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- chainerx_cc/chainerx/routines/math_test.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Add ChainerX `FloorDivide`

- chainer/initializer.py
Fix minor errors such as missing call to `str.format`.
> Fix error messages in `get_fans`

- tests/chainer_tests/exporters_tests/test_caffe.py
- tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
> [backport] Suppress warning in caffe test

- chainer/sequential.py
- tests/chainer_tests/test_sequential.py
> Forbid calling empty `Sequential`

- examples/cifar/train_cifar_custom_loop.py
Fix the training script with a custom loop to use `args.out` and modify the names of model and optimizer.
> Use `args.out` in `train_cifar_custom_loop.py`

- chainer/functions/normalization/batch_normalization.py
This PR aims to fix a fp16 related issue of batch normalization layer, resulting in NaN.
When dtype of x is fp16 and cudnn is used, "output cache" memory for cudnn is allocated as fp16 array now, but it must be allocated as fp32 array. 
imagenet example, resnet50, fp16
```
w/o this PR
epoch       iteration   main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  lr
1           32          nan         nan                   0              0                         0.01
2           64          nan         nan                   0              0                         0.01
3           96          nan         nan                   0              0                         0.01
```
```
with this PR
epoch       iteration   main/loss   validation/main/loss  main/accuracy …
```
> Fix fp16 issue in batch normalization

- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/naive_communicator.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This PR adds the support for fp16 in naive comm.
Related to https://github.com/chainer/chainer/issues/6330
ToDo:
> support for fp16 in naive comm

- chainer/initializer.py
> [backport] Fix error messages in `get_fans`

- docs/source/guides/functions.rst
Some codes in the document was not tested. Found when reviewing #6179.
> Test all codes in guides/functions

- tests/chainerx_tests/op_utils.py
> Fix comment style of `op_utils.py`

- chainerx_cc/chainerx/routines/connection.cc
Avoid code divergence with regard to the existence of bias.
> Refactor `chainerx::Linear`

- chainer/testing/function.py
```
E   chainer.testing.function.FunctionTestError: Parameterized test failed.
E   
E   Base test method: TestReLU_use_chainerx_false__chainerx_device_None__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_forward
E   Test parameters:
E     contiguous: None
E     dtype: <class 'numpy.float16'>
E     shape: (3, 2)
E   
E   
E   (caused by)
E   FunctionTestError: Outputs of forward() do not match the expected values.
E   Indices of outputs that do not match: 0
E   Expected shapes and dtypes: (3, 2):float16
E   Actual shapes and dtypes:   (3, 2):float16
```
```
E   chainer.testing.function.FunctionTestError: Parameterized test failed.
E   
E   Base test method: …
```
> Improve `FunctionTestCase` error message

- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Fixes https://github.com/chainer/chainer/issues/6368.
> Fix lazy init of `BatchNormalization` link

- chainerx_cc/chainerx/routines/type_util_test.cc
Makes a duplicated test unique.
> Fix duplicated test

- docs/source/guides/functions.rst
> [backport] Test all codes in guides/functions

- chainer/functions/math/log_ndtr.py
> [backport] change backward of `F.log_ndtr` to avoid nan

- chainer/functions/connection/n_step_gru.py
- chainer/functions/connection/n_step_lstm.py
- chainer/functions/connection/n_step_rnn.py
- chainer/links/connection/n_step_lstm.py
- chainer/links/connection/n_step_rnn.py
Fix the link to `chainer.Variable` in chainer/(functions | links)/n_step_(rnn | lstm | gru).py.
> Use :class:`~chainer.Variable` in RNNs docs

- tests/chainer_tests/functions_tests/activation_tests/test_softmax.py
Simplify F.softmax test using testing.FunctionTestCase
> Simplify `F.softmax` test

- tests/chainer_tests/functions_tests/math_tests/test_squared_difference.py
Simplified F.test_squared_difference test using testing.FunctionTestCase
Ref. #6071
> Simplify `F.test_squared_difference` test

- tests/chainer_tests/functions_tests/math_tests/test_minimum.py
Simplified F.minimum test using testing.FunctionTestCase.
Ref. #6071
> Simplify `F.minimum` test

- tests/chainer_tests/functions_tests/array_tests/test_vstack.py
Simplifies `test_vstack` using `function.FunctionTestCase`
> Simplify `F.vstack` test

- tests/chainer_tests/functions_tests/math_tests/test_maximum.py
Simplified F.maximum using testing.FunctionTestCase.
Ref. #6071
> Simplify `F.maximum` test

- tests/chainerx_tests/op_utils.py
Strides should be checked when using `NumpyOpTest`.
> Add strides check in `NumpyOpTest`

- chainerx/__init__.pyi
- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/activation.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/activation.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- chainerx_cc/chainerx/routines/math_test.cc
Add minimum to chainerx
Ref. #6423
> Add `minimum` to chainerx

- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
> [backport] Fix lazy init of `BatchNormalization` link

- tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_pooling_2d.py
Test various spatial_scale for roi_average_pooling_2d as #5634
> test various spatial_scale for roi_average_pooling_2d

- tests/chainer_tests/functions_tests/array_tests/test_tile.py
Simplifies `test_tile` using `testing.FunctionTestCase`
> Simplify `F.tile` test

- chainermn/communicators/pure_nccl_communicator.py
- chainermn/nccl.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/links_tests/test_batch_normalization.py
- tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
> [backport] Fix NCCL version check error in ChainerMN

- chainer/functions/loss/softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
> Fix `F.softmax_cross_entropy` float16 under/overflow

- setup.py
> [backport] Restrict pytest requirement

- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/native/native_device/dot.cc
- chainerx_cc/chainerx/routines/linalg.cc
- tests/chainerx_tests/dtype_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
Partially fixed https://github.com/chainer/chainer/issues/6436
> Mixed dtype: dot

- chainerx_cc/chainerx/cuda/cuda_device/activation.cu
- chainerx_cc/chainerx/cuda/cuda_device/exp_log.cu
- chainerx_cc/chainerx/cuda/cuda_device/misc.cu
- chainerx_cc/chainerx/native/native_device/activation.cc
- chainerx_cc/chainerx/native/native_device/exp_log.cc
- chainerx_cc/chainerx/native/native_device/misc.cc
- chainerx_cc/chainerx/routines/math.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
~Merge #6364 first.~
Close #6373.
> ChainerX dtype promotion: mathematical functions

- tests/chainerx_tests/dtype_utils.py
Input dtypes should be permutated.
> Test result dtype permutation

- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device/indexing.cc
- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/indexing.h
- chainerx_cc/chainerx/routines/indexing_test.cc
> Support `chainerx::Take` indices other dtype than int64

- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
Part of  #6401
~Depends on #6424~
> Rewrite ChainerX linalg tests 

- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
> Fix test class name

- tests/chainer_tests/functions_tests/array_tests/test_squeeze.py
Simplifies `squeeze_test` using `testing.FunctionTestCase`
> Simplify `F.squeeze` test

- tests/chainerx_tests/unit_tests/routines_tests/test_normalization.py
> Rewrite ChainerX `fixed_batch_norm` test 

- examples/imagenet/dali_util.py
> [backport] Fix `dali_util` in imagenet example for fp16

- examples/mnist/train_mnist_custom_loop.py
> [backport] Fix iterator syntax in MNIST custom loop example

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Rewrite ChainerX arithmetics tests

- chainer/functions/normalization/batch_normalization.py
- chainer/links/connection/n_step_rnn.py
> [backport] Avoid `# NOQA` in docstrings (cont.)

- setup.cfg
Backport of #5949
(conflict resolved manually)
> [backport] Do not ignore FutureWarning other than experimental features

- docs/source/reference/check.rst
> [backport] Remove duplicated entry in reference

- tests/chainerx_tests/unit_tests/routines_tests/test_logic.py
> Rewrite ChainerX logic tests

- chainer/testing/function_link.py
- chainerx_cc/chainerx/routines/CMakeLists.txt
- tests/chainerx_tests/op_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
Part of #6401
~Depends on #6437~
~Depends on  #6526~
> Rewrite ChainerX indexing tests 

- tests/chainerx_tests/unit_tests/routines_tests/test_pooling.py
> Rewrite ChainerX pooling tests

- chainer/functions/activation/rrelu.py
> Fix rrelu document

- chainer/functions/activation/rrelu.py
> [backport] Fix rrelu document

- docs/source/reference/check.rst
> [backport] Add gradient_check.check_double_backward in reference

- examples/dcgan/net.py
> [backport] Fix DCGAN example to work with default dtype

- chainer/gradient_check.py
- chainer/testing/__init__.py
- chainer/testing/function_link.py
- chainer/testing/parameterized.py
- chainerx_cc/chainerx/cuda/cuda_conv.cc
- chainerx_cc/chainerx/cuda/cuda_conv.h
- chainerx_cc/chainerx/cuda/cuda_conv_test.cc
- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/conv.cc
- chainerx_cc/chainerx/cuda/cudnn.cc
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/conv.cc
- chainerx_cc/chainerx/native/native_device/pool.cc
- chainerx_cc/chainerx/native/tensor_dot.cc
- chainerx_cc/chainerx/native/tensor_dot.h
- chainerx_cc/chainerx/routines/connection.cc
- chainerx_cc/chainerx/routines/connection.h
- tests/chainerx_tests/array_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
Fixes part of #6436 
Depends on: ~#6518~, ~#6524~, (~#6520~)
> Mixed dtype `chainerx::conv` and `chainerx::conv_transpose`

- examples/wavenet/generate.py
- examples/wavenet/modules.py
- examples/wavenet/net.py
- examples/wavenet/utils.py
Rel. #6168.
This PR fixes the wavenet example to support the default dtype feature, especially performing in FP16 mode.
> Fix wavenet example to support the default dtype

- chainer/function_node.py
- tests/chainer_tests/test_function_node.py
> Check lengths of args of `chainer.grad`

- chainer/functions/connection/n_step_gru.py
- chainer/functions/connection/n_step_lstm.py
- chainer/functions/connection/n_step_rnn.py
- chainer/links/connection/n_step_rnn.py
- tests/chainer_tests/links_tests/connection_tests/test_n_step_gru.py
- tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py
- tests/chainer_tests/links_tests/connection_tests/test_n_step_rnn.py
> [backport] Fix `chainer.links.NStepRNN` and its variants

- tests/chainerx_tests/unit_tests/routines_tests/test_sorting.py
Part of #6401 
~Depends on #6438~
> Rewrite ChainerX sorting tests

- chainerx_cc/chainerx/routines/connection.cc
- chainerx_cc/chainerx/routines/linalg.cc
- chainerx_cc/chainerx/routines/linalg.h
- tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
Part of  #6436 
~Depends on #6510.~
> Mixed dtype support in `chainerx.linear`

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Rewrite ChainerX math tests

- chainerx.md
> [doc] update broken link in chainerx.md

- chainer/optimizer.py
> Fix `:meth:` link

- examples/imagenet/README.md
- examples/imagenet/alex.py
- examples/imagenet/dali_util.py
- examples/imagenet/googlenetbn.py
- examples/imagenet/train_imagenet.py
- examples/imagenet/train_imagenet_data_parallel.py
> [backport] Remove FP16 specific models from imagenet example

- chainer/optimizer.py
> [backport] Fix `:meth:` link

- chainer/functions/math/erfcinv.py
- chainer/functions/math/erfcx.py
- chainer/functions/math/erfinv.py
> [backport] Improve docs and exception message in `F.erfcx`, `F.erfcinv` and `F.erfinv`

- chainer/gradient_check.py
- tests/chainerx_tests/unit_tests/routines_tests/test_activation.py
> Rewrite ChainerX activation tests

- chainer/functions/normalization/batch_normalization.py
- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/device.cc
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/routines/normalization.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_normalization.py
> Mixed dtype: `BatchNorm` and `FixedBatchNorm`

- docs/source/chainermn/tutorial/tips_faqs.rst
- examples/chainermn/imagenet/train_imagenet.py
This PR fixes #5631 by rewriting a dummy function from a lambda to an explicitly defined local function.
> Fix broken imagenet example

- chainerx_cc/chainerx/cuda/cuda_conv.cc
- chainerx_cc/chainerx/routines/connection.cc
> Remove obsolete assertions

- chainer/functions/__init__.py
- chainer/functions/activation/clipped_relu.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
Add relu6 function to `clipped_relu.py`
Ref. #6376 #1448
> Add ReLU6 as an alias to F.clipped_relu

- tests/chainer_tests/functions_tests/math_tests/test_prod.py
Simplify `F.prod` test using testing.FunctionTestCase.
Ref. #6071
> Simplify `F.prod` test

- chainer/functions/math/sparse_matmul.py
- chainer/variable.py
- setup.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
> Fix F632 (use ==/!= to compare str)

- docs/source/reference/check.rst
Closes #6257
(found during writing #4986.)
> Fix missing module declaration

- chainerx/__init__.pyi
- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/misc.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/misc.cc
- chainerx_cc/chainerx/numeric.h
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- chainerx_cc/chainerx/routines/math_test.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Add square to chainerx
Ref. #6423
> Add square to chainerx

- tests/chainer_tests/functions_tests/math_tests/test_einsum.py
> Adjust tolerances of `F.einsum` tests

- chainerx_cc/chainerx/array.cc
- chainerx_cc/chainerx/array.h
- chainerx_cc/chainerx/cuda/cuda_device/arithmetic.cu
- chainerx_cc/chainerx/native/native_device/arithmetic.cc
- chainerx_cc/chainerx/routines/linalg.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math_test.cc
- tests/chainerx_tests/dtype_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
- tests/chainerx_tests/unit_tests/test_array.py
~Merge #6481 first.~
Close #6385.
> Mixed dtype: arithmetics

- chainerx_cc/CMakeLists.txt
Addresses this comment: https://github.com/chainer/chainer/pull/6647#discussion_r269444247
> Check `CMAKE_BUILD_TYPE`

- chainer/functions/array/resize_images.py
- chainer/functions/array/spatial_transformer_grid.py
- chainer/functions/array/spatial_transformer_sampler.py
> Fix typo: 'Notatition' -> 'Notation'

- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- chainermn/extensions/allreduce_persistent.py
- chainermn/functions/batch_normalization.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
Addresses #6199 .
* Add global dtype and shape check before every allreduce when debug enabled
* Add `isfinite` check after every allreduce when debug enabled
* Cleanup around allreduce_grad and MNBN forward/backward
* Internal allreduce call of AllreducePersistent replaced with general allreduce()
> Add shape and dtype check before allrecuce

- tests/chainermn_tests/communicator_tests/test_communicator.py
> Clean up test code

- chainerx_cc/chainerx/backward_builder.cc
- chainerx_cc/chainerx/backward_builder.h
> Make `BackwardBuilder::Target` less stateful

- chainermn/communicators/mpi_communicator_base.py
> [backport] Change the deprecated `collections`

- tests/chainer_tests/functions_tests/math_tests/test_einsum.py
> [backport] Adjust tolerances of `F.einsum` tests

- chainer/functions/array/resize_images.py
- chainer/functions/array/spatial_transformer_grid.py
- chainer/functions/array/spatial_transformer_sampler.py
> [backport] Fix typo: 'Notatition' -> 'Notation'

- chainer/functions/normalization/layer_normalization.py
inspired from https://github.com/chainer/chainer/pull/6678#discussion_r270008149.
> remove unnecessary broadcasts from `functions.layer_normalization`

- chainer/functions/normalization/l2_normalization.py
Same as https://github.com/chainer/chainer/pull/6680
> remove unnecessary broadcasts from `functions.l2_normalization`

- docs/source/reference/check.rst
> [backport] Fix missing module declaration

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
This PR simplifies the tests of `F.convolution_2d` and `F.convolution_nd`.
Rel: #6071
> Simplify tests of `F.convolution_2d` and `F.convolution_nd`

- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Fix for https://github.com/cupy/cupy/pull/2117
> Fix test failure in cuDNN v7.5

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Suppress numpy warnings in math tests

- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
> [backport] Fix test failure in cuDNN v7.5

- chainer/distributions/normal.py
Rel. 6168.
cuRAND supports only FP32 and FP64. This PR fixes `D.Normal`, which uses `cupy.random`, to handle FP16 properly to sample.
> Properly handle FP16 in `D.Normal`

- examples/cifar/train_cifar_custom_loop.py
> [backport] Use `args.out` in `train_cifar_custom_loop.py`

- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- scripts/ci/steps.sh
- scripts/ci/travis/steps.sh
Fixes #6646 
Depends on ~#6647~ and ~#6648~
> Run ChainerX python tests in debug build

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/indexing.cc
- chainerx_cc/chainerx/native/native_device/pool.cc
- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/indexing.h
> Op registration: indexing

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/comparison.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/comparison.cc
- chainerx_cc/chainerx/routines/logic.cc
- chainerx_cc/chainerx/routines/logic.h
> Op registration: logic

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/activation.cu
- chainerx_cc/chainerx/cuda/cuda_device/trigonometric.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/activation.cc
- chainerx_cc/chainerx/native/native_device/trigonometric.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
> Op registration: trigonometric

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
Tried relaxing tolerances for failing py2 tests. I have however not verified this fail rate locally since I couldn't reproduce it.
> Relax tolerances in convolution nd function test

- docs/source/guides/functions.rst
Fix `make doctest` error introduced in #4986
> Fix test failures in FunctionNode implementation guide

- docs/source/guides/functions.rst
- docs/source/imports.rst
> [backport] Write guides to implement new-style functions

- .travis.yml
> Travis test against v6 branch

- .travis.yml
> [backport] Travis test against v6 branch

- examples/reinforcement_learning/ddpg_pendulum.py
- examples/reinforcement_learning/dqn_cartpole.py
Part of #6661.
It seems no other fix is needed for running ChainerX.
> Use new device in reinforcement learning example

- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/cuda/cudnn.cc
> [backport] Avoid throwing in destructors

- scripts/ci/travis/steps.sh
> [backport] Fix Travis with macOS

- chainer/gradient_check.py
>  Improve error message of `gradient_check.check_double_backward`

- chainer/distributions/bernoulli.py
- chainer/distributions/normal.py
- examples/vae/train_vae.py
> Support ChainerX in VAE example

- chainerx_cc/chainerx/cuda/cuda_device/comparison.cu
- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- chainerx_cc/chainerx/cuda/cuda_device/trigonometric.cu
- chainerx_cc/chainerx/native/native_device/comparison.cc
- chainerx_cc/chainerx/native/native_device/indexing.cc
- chainerx_cc/chainerx/native/native_device/pool.cc
- chainerx_cc/chainerx/native/native_device/reduction.cc
- chainerx_cc/chainerx/native/native_device/trigonometric.cc
- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/indexing.h
- chainerx_cc/chainerx/routines/logic.cc
- chainerx_cc/chainerx/routines/logic.h
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- chainerx_cc/chainerx/routines/sorting.cc
- chainerx_cc/chainerx/routines/sorting.h
> [backport] Make device functions public

- chainer/__init__.py
- docs/source/reference/configuration.rst
> Enable `use_ideep` and `lazy_grad_sum` by default

- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/indexing.h
Fixed an obsolete comment and wrote a TODO pointed out in
https://github.com/chainer/chainer/pull/6744#discussion_r272861573
https://github.com/chainer/chainer/pull/6744#discussion_r272862407
~_Backport after https://github.com/chainer/chainer/pull/6760._~
> Fix comments and add TODO to indexing routines

- chainer/distributions/bernoulli.py
- chainer/distributions/normal.py
- examples/vae/train_vae.py
> [backport] Support ChainerX in VAE example

- chainer/__init__.py
- docs/source/reference/configuration.rst
> Revert "Enable `use_ideep` and `lazy_grad_sum` by default"

- examples/word2vec/train_word2vec.py
Part of #6661
Merge #6768 first.
> Support ChainerX in word2vec example 

- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- tests/chainerx_tests/unit_tests/routines_tests/test_sorting.py
Fixes https://github.com/chainer/chainer/issues/6742
> Fix ArgMax of CUDA when all values are negative

- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- tests/chainerx_tests/unit_tests/routines_tests/test_sorting.py
> [backport] Fix ArgMax of CUDA when all values are negative

- chainerx/_fallback_workarounds.py
- examples/wavenet/generate.py
- examples/wavenet/train.py
> Support ChainerX in wavenet example

- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/indexing.h
> [backport] Fix comments and add TODO to indexing routines

- examples/image_captioning/README.md
- examples/image_captioning/download.py
It takes quite a time. It's unfriendly if progress is not shown.
> Show download progress bar in image-captioning example

- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/cuda/cudnn.cc
- chainerx_cc/chainerx/cuda/cudnn.h
> [backport] Refactor CUDA batch norm tensor descriptor

- examples/dcgan/net.py
- examples/dcgan/train_dcgan.py
- examples/dcgan/updater.py
> [backport] Support ChainerX in DCGAN example

- examples/reinforcement_learning/ddpg_pendulum.py
- examples/reinforcement_learning/dqn_cartpole.py
> [backport] Support ChainerX in reinforcement learning example

- chainer/training/extensions/evaluator.py
> [backport] Fix `Evaluator` for `chainer.dataset.converter`

- chainerx/__init__.pyi
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Add squared_difference to chainerx
Ref. #6423 
Depends on #6486
> Add `squared_difference` to chainerx

- chainer/functions/math/maximum.py
- chainer/functions/math/square.py
- chainer/functions/math/squared_difference.py
- functions/math/square.py
- functions/math/maximum.py
- functions/math/squared_difference.py
> Improve docs of square, maximum and squared_difference

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Fix test failures in math test

- chainerx_cc/chainerx/array_to_device_test.cc
- chainerx_cc/chainerx/context.cc
- chainerx_cc/chainerx/context.h
> [backport] Remove `Backend` ctor and use `CreateBackend`

- chainerx/_fallback_workarounds.py
- examples/wavenet/generate.py
- examples/wavenet/train.py
> [backport] Support ChainerX in wavenet example

- .github/ISSUE_TEMPLATE.md
A closing backtick has been missing.
> Make it easier to copy the instruction in the issue template

- chainerx_cc/chainerx/cuda/cublas.cc
- chainerx_cc/chainerx/cuda/cublas.h
- chainerx_cc/chainerx/cuda/cuda_conv.cc
- chainerx_cc/chainerx/cuda/cuda_conv_test.cc
- chainerx_cc/chainerx/cuda/cuda_device.cc
- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/cuda/cuda_device/conv.cc
- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/cuda_device/pool.cu
- chainerx_cc/chainerx/cuda/cudnn.cc
> Add `cuda_internal::DeviceInternals` to wrap handle etc.

- chainerx_cc/chainerx/cuda/cuda_device.h
and some cosmetics. Addresses
- https://github.com/chainer/chainer/pull/6820#discussion_r273831592
- https://github.com/chainer/chainer/pull/6820#discussion_r273832130
> Clean up `DeviceInternals`

- chainerx_cc/chainerx/cuda/cublas.cc
- chainerx_cc/chainerx/cuda/cublas.h
- chainerx_cc/chainerx/cuda/cuda_conv.cc
- chainerx_cc/chainerx/cuda/cuda_conv_test.cc
- chainerx_cc/chainerx/cuda/cuda_device.cc
- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/cuda/cuda_device/conv.cc
- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/cuda_device/pool.cu
- chainerx_cc/chainerx/cuda/cudnn.cc
> [backport] Add `cuda_internal::DeviceInternals` to wrap handle etc.

- chainer/backend.py
- docs/source/reference/util/cuda.rst
`chainer.get_device` is used in some official examples.
> Add `chainer.get_device` to doc

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/arithmetic.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/arithmetic.cc
- chainerx_cc/chainerx/native/native_device/pool.cc
- chainerx_cc/chainerx/routines/connection.cc
- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- chainerx_cc/chainerx/routines/statistics.cc
> Op registration: arithmetic

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/cuda_device_test.cc
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/dot.cc
- chainerx_cc/chainerx/native/tensor_dot.cc
- chainerx_cc/chainerx/routines/connection.cc
- chainerx_cc/chainerx/routines/linalg.cc
- chainerx_cc/chainerx/routines/linalg.h
Part of #6692.
Depends on #6820.
> Op registration: linalg

- chainerx/__init__.py
- chainerx/_docs/routines.py
- chainerx/math/misc.py
> [backport] Remove `chainerx.square` fallback since it is implemented in C++

- chainerx_cc/chainerx/cuda/cuda_device.h
> [backport] Clean up `DeviceInternals`

- chainerx/__init__.pyi
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Add `squared_difference` to chainerx

- chainerx_cc/chainerx/cuda/cuda_conv_test.cc
- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/conv.cc
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/conv.cc
- chainerx_cc/chainerx/routines/connection.cc
- chainerx_cc/chainerx/routines/connection.h
> Op registration: connection

- chainer/device_resident.py
- tests/chainer_tests/test_link.py
> Fix stack overflow caused when `to_gpu`/`to_cpu`/`to_intel64` were overridden

- tests/chainer_tests/functions_tests/activation_tests/test_elu.py
> [backport] Fix `F.elu` test numeric error

- chainerx_cc/chainerx/array.cc
- chainerx_cc/chainerx/array_to_device_test.cc
- chainerx_cc/chainerx/context.h
- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/copy.cu
- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/cuda_device/fill.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/copy.cc
- chainerx_cc/chainerx/native/native_device/fill.cc
- chainerx_cc/chainerx/routines/CMakeLists.txt
- chainerx_cc/chainerx/routines/creation.cc
- chainerx_cc/chainerx/routines/manipulation.cc
- chainerx_cc/chainerx/routines/misc.h
> Op registration: array members

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/device.cc
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/CMakeLists.txt
- chainerx_cc/chainerx/native/native_device/batch_norm.cc
- chainerx_cc/chainerx/op_registry.h
- chainerx_cc/chainerx/routines/normalization.cc
- chainerx_cc/chainerx/routines/normalization.h
> [backport] Op registration: normalization

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Fix test failures in math test

- chainerx/__init__.pyi
- chainerx/_docs/routines.py
- chainerx_cc/chainerx/cuda/cuda_device/misc.cu
- chainerx_cc/chainerx/cuda/numeric.cuh
- chainerx_cc/chainerx/native/native_device/misc.cc
- chainerx_cc/chainerx/numeric.h
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- docs/source/chainerx/reference/routines.rst
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Add `chainerx.ceil`

- examples/memnn/test_memnn.py
- examples/memnn/train_memnn.py
Part of #6661 
Note: previously `test_memnn.py` ran only using NumPy, ignoring `--gpu` option. This has been fixed altogether.
> Support ChainerX in memnn example

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
> [backport] Add AdaBound (and AMSBound)

- chainerx.md
> [backport] Fix broken link in `chainerx.md`

- chainer/link_hook.py
- chainer/link_hooks/spectral_normalization.py
- tests/chainer_tests/link_hooks_tests/test_spectral_normalization.py
> [backport] Improve `link_hooks.SpectralNormalization`

- tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
> Fix `F.rrelu` test instability

- chainerx_cc/chainerx/cuda/cuda_device/activation.cu
- chainerx_cc/chainerx/cuda/cuda_device/arithmetic.cu
- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/cuda/cuda_device/comparison.cu
- chainerx_cc/chainerx/cuda/cuda_device/conv.cc
- chainerx_cc/chainerx/cuda/cuda_device/copy.cu
- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/cuda_device/exp_log.cu
- chainerx_cc/chainerx/cuda/cuda_device/fill.cu
- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
- chainerx_cc/chainerx/cuda/cuda_device/misc.cu
- chainerx_cc/chainerx/cuda/cuda_device/pool.cu
- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- chainerx_cc/chainerx/cuda/cuda_device/trigonometric.cu
- chainerx_cc/chainerx/cuda/op_regist.h
- chainerx_cc/chainerx/native/native_device/activation.cc
- chainerx_cc/chainerx/native/native_device/arithmetic.cc
- chainerx_cc/chainerx/native/native_device/batch_norm.cc
- chainerx_cc/chainerx/native/native_device/comparison.cc
- chainerx_cc/chainerx/native/native_device/conv.cc
- chainerx_cc/chainerx/native/native_device/copy.cc
- chainerx_cc/chainerx/native/native_device/dot.cc
- chainerx_cc/chainerx/native/native_device/exp_log.cc
- chainerx_cc/chainerx/native/native_device/fill.cc
- chainerx_cc/chainerx/native/native_device/indexing.cc
- chainerx_cc/chainerx/native/native_device/misc.cc
- chainerx_cc/chainerx/native/native_device/pool.cc
- chainerx_cc/chainerx/native/native_device/reduction.cc
- chainerx_cc/chainerx/native/native_device/trigonometric.cc
- chainerx_cc/chainerx/native/op_regist.h
Fixes https://github.com/chainer/chainer/issues/6864
> Rename `CHAINERX_REGISTER_OP_{NATIVE,CUDA}` to `CHAINERX_{NATIVE,CUDA}_REGISTER_OP`

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
This PR fixes the renamed `filename` argument of `PlotReport` hasn't been effective.
> Fix `filename` arg of `PlotReport`

- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
> Fix `F.max_pooling_nd` test instability

- tests/chainer_tests/functions_tests/activation_tests/test_rrelu.py
> [backport] Fix `F.rrelu` test instability

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
> [backport] Fix `filename` arg of `PlotReport`

- tests/chainer_tests/functions_tests/connection_tests/test_bilinear.py
Simplifies`test_bilinear` using `testing.FunctionTestCase`.
> Simplify `F.bilinear` test

- chainer/function_node.py
- chainer/variable.py
- tests/chainer_tests/test_function_node.py
- tests/chainer_tests/test_variable.py
> [backport] Fix unchain gradient pull

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
Follow-up: #6866 
Write intention of `del` in comments.
> Add comments on `del`

- chainer/distributions/independent.py
- tests/chainer_tests/distributions_tests/test_independent.py
> [backport] Update `distributions.independent`

- docs/source/_templates/search.html
> [backport] Use search index

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Skips backward/double-backward tests for inputs that results in non-finite outputs.
Differentiable domains are different among inverse trigonometric functions.
> Fix test parameters in ChainerX math tests

- chainerx/_fallback_workarounds.py
- chainerx_cc/chainerx/array.cc
- chainerx_cc/chainerx/array.h
- chainerx_cc/chainerx/python/array.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_logic.py
> Stop fallback in `chainerx.{all/any}`

- examples/cifar/README.md
- examples/cifar/train_cifar.py
- examples/cifar/train_cifar_custom_loop.py
> [backport] Support ChainerX in CIFAR example

- chainer/datasets/pickle_dataset.py
> Fix typo in `pickle_dataset.py`

- chainer/datasets/pickle_dataset.py
> [backport] Fix typo in `pickle_dataset.py`

- scripts/ci/travis/run-tests.sh
> [backport] Fold Travis test outputs

- chainer/training/extensions/_snapshot.py
- tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
> [backport] Allow `snapshot_object` have `condition` and `writer` option

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
> Use `filename` in PlotReport example

- docs/source/reference/check.rst
> Document `chainer.testing.LinkTestCase`

- tests/chainer_tests/functions_tests/math_tests/test_ceil.py
Simplifies test_ceil using testing.FunctionTestCase
> Simplify `F.ceil` test

- tests/chainer_tests/functions_tests/math_tests/test_floor.py
Simplifies test_floor using testing.FunctionTestCase
> Simplify `F.floor` test

- chainerx/_fallback_workarounds.py
- tests/chainer_tests/functions_tests/math_tests/test_fmod.py
Simplifies test_fmod using testing.FunctionTestCase
> Simplify `F.fmod` test

- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
> Revert "Simplify  `F.deconvolution_2d` test"

- chainerx/_fallback_workarounds.py
- examples/seq2seq/seq2seq.py
- examples/text_classification/nlp_utils.py
- examples/text_classification/run_text_classifier.py
- examples/text_classification/train_text_classifier.py
> [backport] Support ChainerX in text classification example 

- tests/chainer_tests/test_variable.py
Refactor `Variable.addgrad` test to use `inject_backend_tests`.
Preparation for supporting Chainerx (for #6983, #6857)
> Refactor `Variable.addgrad` test

- tests/chainerx_tests/unit_tests/routines_tests/test_pooling.py
Fixes https://github.com/chainer/chainer/issues/6914.
> Fix flaky ChainerX `max_pool` test

- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/py_cached_objects.h
- chainerx_cc/chainerx/python/scalar.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Support NumPy scalars in ChainerX arithmetics

- docs/source/reference/check.rst
> [backport] Document `chainer.testing.LinkTestCase`

- chainerx_cc/chainerx/cuda/numeric.cuh
- chainerx_cc/chainerx/numeric.h
A minor conventional code fix.
> Prefix macro with CHAINERX as per convention

- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_npz.py
> [backport] Fix TypeError during BN deserialization on win64

- tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py
> [backport] Fix test failure in `test_spatial_transformer_sampler.py`

- tests/chainer_tests/functions_tests/array_tests/test_separate.py
Simplifies test_separate using testing.FunctionTestCase
> Simplify `F.separate` test

- chainer/dataset/convert.py
- tests/chainer_tests/dataset_tests/test_convert.py
> [backport] Fix `ConcatWithAsyncTransfer`

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Added broadcast tests in binary-arithmetic operation tests in `test_math.py`.
This PR changes the name of the parameter of shapes which `BinaryMathTestBase` and  `InplaceBinaryMathTestBase`take: `shape` -> `in_shapes`.
> Add broadcast test in `test_math.py`

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
> [backport] Use `filename` in PlotReport example

- tests/chainer_tests/functions_tests/math_tests/test_logsumexp.py
Simplifies test_logsumexp using testing.FunctionTestCase
> Simplify `F.logsumexp` test

- tests/chainer_tests/functions_tests/evaluation_tests/test_binary_accuracy.py
Simplifies test_binary_accuracy using testing.FunctionTestCase
> Simplify `F.binary_accuracy` test

- tests/chainer_tests/functions_tests/evaluation_tests/test_accuracy.py
Simplifies test_accuracy using testing.FunctionTestCase
> Simplify `F.accuracy` test

- chainerx/_fallback_workarounds.py
- tests/chainer_tests/functions_tests/math_tests/test_fix.py
Simplifies test_fix using testing.FunctionTestCase
> Simplify `F.fix` test

- tests/chainer_tests/functions_tests/array_tests/test_reshape.py
Simplifies `test_reshape` using `testing.FunctionTestCase
> Simplify `F.reshape` test

- tests/chainer_tests/functions_tests/normalization_tests/test_layer_normalization.py
Simplifies `test_layer_normalization` using `testing.FunctionTestCase`
> Simplify `F.layer_normalization` test

- tests/chainer_tests/functions_tests/activation_tests/test_prelu.py
Simplifies `test_prelu` using testing.FunctionTestCase
> Simplify `F.prelu` test

- tests/chainer_tests/functions_tests/array_tests/test_flatten.py
Simplifies `test_flatten` using `testing.FunctionTestCase`
> Simplify `F.flatten` test

- tests/chainer_tests/functions_tests/array_tests/test_dstack.py
Simplifies `test_dstack` using `testing.FunctionTestCase`
Simplifies part of issue #6071
> Simplify `F.dstack` test

- tests/chainer_tests/functions_tests/math_tests/test_inv.py
Simplifies test_inv using testing.FunctionTestCase
> Simplify `F.inv`, `F.batch_inv` test

- tests/chainer_tests/functions_tests/evaluation_tests/test_r2_score.py
Simplifies test_r2_score using testing.FunctionTestCase
> Simplify `F.r2_score` test

- tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_nd.py
Simplifies `test_unpoolin_nd` using `testing.FunctionTestCase`
> Simplify `F.unpooling_nd` test

- tests/chainer_tests/functions_tests/math_tests/test_cumsum.py
Simplifies test_cumsum using testing.FunctionTestCase
> Simplify `F.cumsum` test

- tests/chainer_tests/functions_tests/math_tests/test_fft.py
Simplifies test_fft using testing.FunctionTestCase
> Simplify `F.fft`, `F.ifft` test

- tests/chainer_tests/functions_tests/math_tests/test_matmul.py
SImplifiies `test_matmul` using `testing.FunctionTestCase`
> Simplify `F.matmul` test

- tests/chainer_tests/functions_tests/array_tests/test_permutate.py
Simplifies test_permutate using testing.FunctionTestCase
> Simplify `F.permutate` test

- tests/chainer_tests/functions_tests/array_tests/test_scatter_add.py
Simplifies test_scatter_add using testing.FunctionTestCase
> Simplify `F.scatter_add` test

- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_npz.py
> [backport] Set `allow_pickle=True` 

- chainerx_cc/chainerx/CMakeLists.txt
I fixed cmake for windows because almost test are failed.
> Cmake for Windows(clang-cl)

- tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
Fix #6906.
Fixed to avoid non-differential inputs.
> Fix flaky HuberLoss test

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Fix flaky `chainerx.tan` test

- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/manipulation.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
> [backport] Fix subview of zero-sized arrays

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Fix flaky `chainerx.tan` test

- tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
> [backport] Fix flaky Huber loss test

- chainerx_cc/chainerx/routines/indexing.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
> [backport] Fix `At` output offset

- chainerx_cc/chainerx/routines/manipulation.cc
> [backport] Fix handling of ndarray offsets

- scripts/ci/travis/run-tests.sh
> [backport] Increase the default columns in Travis CI

- examples/reinforcement_learning/ddpg_pendulum.py
- examples/reinforcement_learning/dqn_cartpole.py
> [backport] Fix reinforcement_learning example to work with default dtype

- docs/source/chainerx/contribution.rst
> [backport] Update ChainerX contribution guide

- chainer/backends/_chainerx.py
- chainer/backends/_cpu.py
- chainer/backends/cuda.py
- chainer/backends/intel64.py
- tests/chainer_tests/test_backend.py
This PR addresses #6772 
I am not sure if this would need a unit test. Please tell if any modification is required.
@niboshi
> Define `__str__` for `Device` classes

- scripts/ci/travis/steps.sh
> [backport] Display `pytest` summary

- appveyor.yml
- scripts/ci/steps.sh
> [backport] Display `pytest` summary (cont.)

- .mergify.yml
Integrating [Mergify](https://mergify.io/) for automatic merge.
https://doc.mergify.io/index.html
> Add `.mergify.yml`

- chainer/backends/_chainerx.py
- chainer/backends/_cpu.py
- chainer/backends/cuda.py
- chainer/backends/intel64.py
- tests/chainer_tests/test_backend.py
> [backport] Define `__str__` for `Device` classes

- examples/pos/postagging.py
Part of https://github.com/chainer/chainer/issues/6661.
~It is incredibly slow with `'cuda:0'`, mostly because of `links.CRF1d`.~ With Debug build...
> Support ChainerX in POS-tagging example

- chainerx_cc/chainerx/python/chainer_interop.cc
> [backport] Fix construction of `std::shared_ptr` with custom deleter in `chianer_interop.cc`

- chainer/training/triggers/interval_trigger.py
- chainer/training/triggers/manual_schedule_trigger.py
- tests/chainer_tests/training_tests/triggers_tests/test_interval_trigger.py
- tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
> [backport] Fix trigger constructors to raise errors instead of assertion failures

- docs/source/chainermn/installation/guide.rst
> [backport] Update supported MPI list

- chainer/functions/__init__.py
- chainer/functions/math/arctanh.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/math_tests/test_arctanh.py
This function is intended to be used to model a Gaussian distribution squashed by tanh as described in https://arxiv.org/abs/1812.05905.
> Add `F.arctanh`

- chainer/utils/type_check.py
- tests/chainer_tests/utils_tests/test_type_check.py
> [backport] Make `InvalidType` picklable

- chainer/optimizers/__init__.py
- chainer/optimizers/adam.py
- docs/source/reference/optimizers.rst
This PR aims at making each Adam variant easier to initialize intuitively & more accessible.
> Make adam variants more accessible

- chainerx_cc/chainerx/cuda/cuda_conv.cc
> Support TensorCore in `chainerx::Conv`

- docs/source/chainerx/install/index.rst
wrote a document about BLAS for ChainerX
> Document `CHAINERX_ENABLE_BLAS` environment variable

- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
> Avoid importing object

- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
> [backport] Avoid importing object

- chainer/functions/pooling/unpooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
> [backport] Fast integer scale unpooling

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
> [backport] Fix documentation of renamed arguments

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
Addresses the comment https://github.com/chainer/chainer/pull/6932#pullrequestreview-228592982
> Remove extra spaces in docstrings

- tests/chainer_tests/functions_tests/math_tests/test_bias.py
Simplifies test_bias using testing.FunctionTestCase
> Simplify `F.bias` test

- tests/chainer_tests/functions_tests/math_tests/test_hyperbolic.py
Simplifies test_hyperbolic using testing.FunctionTestCase
> Simpify `F.cosh`, `F.sinh` test

- examples/modelzoo/evaluate_caffe_net.py
Part of #6661.
For CUDA, no obvious performance difference between CuPy and ChainerX with AlexNet.
> Support ChainerX in Model Zoo example

- chainer/optimizers/adam.py
> Fix spelling of AMSGrad

- chainer/optimizers/adam.py
> Fix AdamW docstring

- chainermn/communicators/_memory_utility.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- chainermn/optimizers.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This PR adds zero fill mode in allreduce of chainermn.
The PR solves https://github.com/chainer/chainer/issues/6759
> add zero fill mode in allreduce of chainermn

- chainermn/communicators/_memory_utility.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- chainermn/optimizers.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
> [backport] Add zero fill mode in allreduce of chainermn

- chainer/_backend.py
- chainer/backend.py
- chainer/backends/_chainerx.py
- chainer/backends/_cpu.py
- chainer/backends/cuda.py
- chainer/backends/intel64.py
- chainer/device_resident.py
- docs/source/conf.py
- docs/source/reference/backends.rst
Depends on #7099
Documents some newly introduced device-related objects.
> Document backend and device objects

- README.md
- chainer/_version.py
- docs/source/conf.py
Following up https://github.com/chainer/chainer/pull/7155.
> Update version to v6.0.0 (follow-up)

- docs/source/_autosummary_check.py
> [backport] Support Sphinx 2.0 and use absolute path to support the latest RTD

- .mergify.yml
> [backport] Add `.mergify.yml`

- chainer/training/extensions/computational_graph.py
- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/extensions/variable_statistics_plot.py
> [backport] Remove extra spaces in docstrings

- tests/chainer_tests/functions_tests/math_tests/test_tensordot.py
Simplifies `test_tensordot` using `testing.FunctionTestCase`
> Simplify `F.tensordot` test

- tests/chainer_tests/functions_tests/math_tests/test_cumprod.py
Simplifies test_cumprod using testing.FunctionTestCase
> Simplify `F.cumprod` test

- chainer/backend.py
- chainer/backends/cuda.py
- docs/source/reference/backends.rst
Document `chainer.backend.get_device_from_array`.
> Document `backend.get_device_from_array`

- chainerx_build_helper.py
- chainerx_cc/CMakeLists.txt
- chainerx_cc/chainerx/array_repr.cc
- chainerx_cc/third_party/gtest.cmake
- write a hack for MSVC
- upgrade gtest (1.80 has a bug on MSVC)
https://github.com/google/googletest/issues/1138
> made enable to compile chainerx with MSVC

- chainer/functions/array/copy.py
Fixes https://github.com/chainer/chainer/issues/7133.
> Document `F.copy` view behavior

- chainer/variable.py
- tests/chainer_tests/test_link.py
- tests/chainer_tests/test_variable.py
Fixes #6983
~Depends on #6982~
> Support ChainerX in `Variable.addgrad`

- chainerx_cc/chainerx/routines/binary.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/routines_util.h
Consistent case `InPlace` -> `Inplace`.
> Consistent cases for Inplace

- chainer/link.py
- tests/chainer_tests/test_link.py
Fixes https://github.com/chainer/chainer/issues/7172.
> `Link.serialize` to support ChainerX

- docs/source/reference/optimizers.rst
> [backport] Add `optimizers.MSVAG` to documentation

- chainer/backend.py
- chainer/backends/cuda.py
- docs/source/reference/backends.rst
> [backport] Document `backend.get_device_from_array`

- tests/chainer_tests/test_variable.py
This is mainly a code refactoring, but also added `(0,)` shape in these tests.
> Split `Variable.grad` and `Variable.grad_var` tests

- examples/image_captioning/train.py
> Support device specifier in image captioning example

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
- tests/chainerx_tests/unit_tests/routines_tests/test_trigonometric_hyperbolic.py
> Move `TestTanh` from `test_math.py` to test_trigonometric_hyperbolic.py

- chainermn/links/batch_normalization.py
- tests/chainermn_tests/links_tests/test_batch_normalization.py
> Fix uncopyable MultiNodeBatchNormalization

- chainer/functions/normalization/batch_renormalization.py
> [backport] Avoid unnecessary updates in `F.batch_renormalization`, and related fixes

- chainer/functions/array/copy.py
> [backport] Document `F.copy` view behavior

- chainer/distribution.py
- chainer/function.py
- chainer/function_node.py
- chainer/link.py
- chainer/optimizer.py
- chainer/optimizer_hooks/gradient_noise.py
- chainer/training/extensions/computational_graph.py
- chainer/variable.py
- docs/source/chainermn/installation/guide.rst
- docs/source/chainerx/tips.rst
- docs/source/contribution.rst
- docs/source/examples/cnn.rst
- docs/source/examples/mnist.rst
- docs/source/guides/functions.rst
- docs/source/guides/variables.rst
- docs/source/performance.rst
- docs/source/reference/configuration.rst
- docs/source/reference/links.rst
- docs/source/upgrade.rst
- docs/source/upgrade_v2.rst
It is recommended to ... -> It is recommended that you ...
> Fix grammatical errors in documentation

- chainer/distribution.py
- chainer/function.py
- chainer/function_node.py
- chainer/link.py
- chainer/optimizer.py
- chainer/optimizer_hooks/gradient_noise.py
- chainer/training/extensions/computational_graph.py
- chainer/variable.py
- docs/source/chainermn/installation/guide.rst
- docs/source/chainerx/tips.rst
- docs/source/contribution.rst
- docs/source/examples/cnn.rst
- docs/source/examples/mnist.rst
- docs/source/guides/functions.rst
- docs/source/guides/variables.rst
- docs/source/performance.rst
- docs/source/reference/configuration.rst
- docs/source/reference/links.rst
- docs/source/upgrade.rst
- docs/source/upgrade_v2.rst
> [backport] Fix grammatical errors in documentation

- examples/mnist/train_mnist_model_parallel.py
Some more internal fixes are needed to support ChainerX.
> Support device specifiers in MNIST model parallel example

- examples/image_captioning/train.py
> [backport] Support device specifier in image captioning example

- examples/pix2pix/train_facade.py
Part of https://github.com/chainer/chainer/issues/6661.
Needs
- `unchain_backward`, similar to #7055.
> Support device specifiers in pix2pix example 

- chainer/training/updaters/parallel_updater.py
- examples/mnist/train_mnist_data_parallel.py
> [backport] Support device specifiers in MNIST data parallel example

- examples/pix2pix/train_facade.py
> [backport] Support device specifiers in pix2pix example 

- examples/sentiment/test_thin_stack.py
> Fix sentiment example test

- tests/chainer_tests/test_variable.py
Separated the test and fixed to use `inject_backend_tests`.
~Depends on #7191~
> Refactor `Variable.zerograd` test 

- examples/static_graph_optimizations/cifar/train_cifar.py
- examples/static_graph_optimizations/cifar/train_cifar_custom_loop.py
- examples/static_graph_optimizations/mnist/train_mnist.py
- examples/static_graph_optimizations/mnist/train_mnist_custom_loop.py
- examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py
> [backport] Support device specifiers in static graph example 

- examples/sentiment/test_thin_stack.py
> [backport] Fix sentiment example test

- tests/chainer_tests/test_variable.py
> Refactor `Variable.copydata` test

- chainer/backend.py
- tests/chainer_tests/test_variable.py
Fixes #7221
~Depends on #7224~
> Support ChainerX in `Variable.copydata`

- chainer/training/updaters/multiprocess_parallel_updater.py
- tests/chainer_tests/training_tests/updaters_tests/snippets/child_reporter.py
- tests/chainer_tests/training_tests/updaters_tests/snippets/cuda_init.py
- tests/chainer_tests/training_tests/updaters_tests/snippets/raw_array.py
- tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
> [backport] `MultiprocessParallelUpdater` to support new devices

- docs/source/examples/ptb.rst
- examples/ptb/train_ptb.py
- examples/ptb/train_ptb_custom_loop.py
Part of https://github.com/chainer/chainer/issues/6661.
Needs
- `unchain_backward` with ChainerX for TBPTT: Probably needs some discussion.
- ~`int / chainerx.ndarray` https://github.com/chainer/chainer/pull/7075 (Edit: merged)~
> Support device specifiers in PTB example

- chainer/utils/type_check.py
> [backport] Fix typos in chainer.utils.type_check

- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- chainerx_cc/chainerx/routines/statistics.h
I forgot to move some declarations in #7222.
> Move declaration of `AMax` and `AMin` to statistics routines

- examples/chainermn/parallel_convolution/README.md
- examples/chainermn/parallel_convolution/train.py
- examples/image_captioning/README.md
- examples/image_captioning/train.py
- examples/mnist/README.md
- examples/mnist/train_mnist.py
- examples/static_graph_optimizations/mnist/README.md
- examples/static_graph_optimizations/mnist/train_mnist.py
- examples/vae/README.md
- examples/vae/train_vae.py
- examples/wavenet/requirements.txt
- examples/wavenet/train.py
> Use Agg backend in examples with plot functionality

- examples/mnist/train_mnist_data_parallel.py
Part of #7220
~Depends on #7226~
> Support ChainerX in MNIST data parallel example 

- scripts/ci/chainerx/jenkins/run_docker.sh
> [backport] Use CUDA_VISIBLE_DEVICES in ChainerX tests

- examples/image_captioning/model.py
- examples/image_captioning/predict.py
Fixes #7205
Part of #6661
~Depends on #7204~
> Support device specifier in image captioning example (`predict.py`) 

- chainer/links/activation/swish.py
> [backport] Fix capitalization of `F.relu` in doc

- docs/source/examples/ptb.rst
- examples/ptb/train_ptb.py
- examples/ptb/train_ptb_custom_loop.py
> [backport] Support device specifiers in PTB example

- chainerx_build_helper.py
- chainerx_cc/CMakeLists.txt
- chainerx_cc/chainerx/array_repr.cc
- chainerx_cc/third_party/gtest.cmake
> [backport] Fix ChainerX compilation with MSVC

- examples/imagenet/train_imagenet_data_parallel.py
> [backport] Support device specifiers in ImageNet data parallel example

- chainer/_backend.py
- chainer/backends/_chainerx.py
- chainer/backends/cuda.py
> [backport] Improve device documentation

- .mergify.yml
> [backport] Improve mergify configuration

- chainerx_cc/chainerx/cuda/numeric.cuh
- chainerx_cc/chainerx/numeric.h
Same fix included in a PR for CuPy https://github.com/cupy/cupy/pull/2204
> Fix integral negative powers

- chainer/dataset/tabular/__init__.py
- chainer/dataset/tabular/_as_mode.py
- chainer/dataset/tabular/_slice.py
- chainer/dataset/tabular/tabular_dataset.py
e.g. `chainer.dataset.tabular.slice.Slice` -> `chainer.dataset.tabular._slice._Slice`
> Use `_` for private classes under `chainer.dataset.tabular`

- chainer/variable.py
- tests/chainer_tests/functions_tests/array_tests/test_copy.py
- tests/chainer_tests/test_variable.py
Fixes #7190
~Depends on #7199~
> Call `require_grad()` on ChainerX `Variable.grad` setter 

- chainer/link.py
> [backport] Fix to clarify the description about initializer argument

- examples/chainermn/cifar/models/VGG.py
- examples/chainermn/cifar/train_cifar.py
Source code for using chainermn with cifar.
Use data parallel.
Source code base is `chainer/examples/cifar/train_cifar.py`.
It confirmed the operation verification.
> Add CIFAR example to ChainerMN

- chainer/distributions/bernoulli.py
- tests/chainer_tests/distributions_tests/test_bernoulli.py
> [backport] Fix a bug in `Bernoulli.log_prob`

- tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py
(+ rename tests + added some comments)
> Rewrite `StandardUpdater` tests with pytest style assertion

- tests/chainer_tests/test_variable.py
Fixes #7307
(including improvement to `chainer.as_variable` test)
> Add `chainer.as_array` test

- examples/ptb/gentxt.py
> Support ChainerX in PTB gentxt example

- chainer/functions/normalization/l2_normalization.py
> [backport] Fix `F.normalize` documentation

- examples/ptb/gentxt.py
> [backport] Support ChainerX in PTB gentxt example

- chainermn/communicators/_communication_utility.py
- chainermn/datasets/scatter_dataset.py
- tests/chainermn_tests/datasets_tests/test_dataset.py
> [backport] Fix a bug that root is ignored in  scatter_dataset and bcast

- chainer/functions/math/clip.py
- tests/chainer_tests/functions_tests/math_tests/test_clip.py
Spin-off from: #7285 
Also adds some `None` checks too.
> Add tests for clip function with None parameter to min/max

- examples/wavenet/train.py
> [backport] Warn NaN in FP16 mode in wavenet example

- examples/static_graph_optimizations/mnist/train_mnist.py
- examples/static_graph_optimizations/mnist/train_mnist_custom_loop.py
> [backport] Warn NaN in FP16 mode in static_graph_optimizations/mnist example

- examples/sentiment/train_sentiment.py
> [backport] Warn NaN in FP16 mode in sentiment example

- examples/static_graph_optimizations/cifar/train_cifar.py
- examples/static_graph_optimizations/cifar/train_cifar_custom_loop.py
> [backport] Warn NaN in FP16 mode in static_graph_optimizations/cifar example

- examples/reinforcement_learning/ddpg_pendulum.py
- examples/reinforcement_learning/dqn_cartpole.py
> [backport] Warn NaN in FP16 mode in reinforcement learning examples

- examples/memnn/train_memnn.py
> [backport] Warn NaN in FP16 mode in memnn example

- examples/pos/postagging.py
> [backport] Warn NaN in FP16 mode in pos example

- examples/word2vec/train_word2vec.py
> [backport] Warn NaN in FP16 mode in word2vec example

- chainerx_cc/chainerx/python/array.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_misc.py
Fixes https://github.com/chainer/chainer/issues/7341.
> Python operator `__abs__` with `chainerx.ndarray`

- chainer/functions/noise/dropout.py
- tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
> [backport] Fix condition to invoke cuDNN dropout

- tests/chainer_tests/functions_tests/math_tests/test_average.py
Simplifies test_average using testing.FunctionTestCase
> Simplify `F.average` test

- examples/pix2pix/train_facade.py
> [backport] Warn NaN in FP16 mode in pix2pix example

- docs/source/reference/static_graph.rst
> Fix format of `static_graph.rst`

- chainerx/__init__.py
- chainerx_cc/chainerx/python/array_index.cc
- chainerx_cc/chainerx/python/core_module.cc
- tests/chainerx_tests/unit_tests/test_constants.py
Fixes #7368 
See also: https://docs.scipy.org/doc/numpy/reference/constants.html
> Add NumPy constants to ChainerX

- .pfnci/config.pbtxt
- .pfnci/hint.pbtxt
- .pfnci/run.sh
- .pfnci/script.sh
This PR will add CI configs for the following targets:
- https://ci.preferred.jp/chainer.py27and35/
- https://ci.preferred.jp/chainer.py37/
Note that this should be backported.
> Add CI configs

- chainermn/links/batch_normalization.py
- tests/chainermn_tests/links_tests/test_batch_normalization.py
> [backport] Fix uncopyable MultiNodeBatchNormalization

- docs/source/reference/static_graph.rst
> [backport] Fix format of `static_graph.rst`

- examples/vae/train_vae.py
> [backport] Warn NaN in FP16 mode in vae example

- .pfnci/config.pbtxt
- .pfnci/hint.pbtxt
- .pfnci/run.sh
- .pfnci/script.sh
> [backport] Add configuration of new CI system

- chainerx_cc/cmake/FindCuDNN.cmake
~Depends on #7418~
* Put comments
* tabs -> spaces for consistency.
>  Put comments in `FindCuDNN.cmake`

- tests/chainer_tests/optimizers_tests/test_optimizers.py
Minor code fix in optimizer tests.
> DRY optimizer test parameterizations

- chainerx/__init__.pyi
- chainerx/_docs/routines.py
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/manipulation.cc
- chainerx_cc/chainerx/routines/manipulation.h
- docs/source/chainerx/reference/routines.rst
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
> Add `chainerx.dstack` and `chainerx.atleast_3d`

- chainer/variable.py
- chainerx/__init__.pyi
> [backport] Add type hints to `Variable`

- chainerx_cc/chainerx/backward.cc
Fixed a comment in the ChainerX backward implementation.
> Fix wrong comment in ChainerX backward implementation

- README.md
This list is for long not maintained.
> Remove "Research projects using Chainer" from README

- docs/source/_static/robots.txt
> [backport] Fix robots.txt to allow indexing root

- README.md
> [backport] Remove "Research projects using Chainer" from README

- chainer/functions/activation/swish.py
> [backport] Add reference and warning to `F.swish` document

- chainer/functions/normalization/l2_normalization.py
This PR aims at improving the documentation of `F.normalize` following the review comment (https://github.com/chainer/chainer/pull/7062#discussion_r288926402).
> Improve `F.normalize` documentation

- chainer/links/connection/deformable_convolution_2d.py
> [backport] Change Deformable Convolution 2D docs to match arguments

- chainer/functions/normalization/l2_normalization.py
> [backport] Improve `F.normalize` documentation

- chainer/functions/loss/absolute_error.py
- tests/chainer_tests/functions_tests/loss_tests/test_absolute_error.py
> Fix `F.absolute_error` for ChainerX

- chainer/functions/connection/convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
Close #7304.
This PR make `F.convolution_2d` check if the supplied dilation is positive integer.
> Check positive dilation in `F.convolution_2d`

- chainer/functions/connection/deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
Rel. #7304.
This PR make F.deconvolution_2d check if the supplied dilation is positive integer.
> Check positive dilation in `F.deconvolution_2d`

- chainer/functions/array/copy.py
- tests/chainer_tests/functions_tests/array_tests/test_copy.py
Currently `F.copy` only supports transfer between non-ChainerX devices / between non-ChainerX devices.
With this PR `F.copy` supports trasfer between non-ChainerX and ChainerX, but only if no backprop is required.
(Originally meant for #7330, but it turned out that #7330 does not require this fix.)
> Support `F.copy` between non-ChainerX and ChainerX devices only if backprop is not required

- chainer/functions/connection/deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
> [backport] Check positive dilation in `F.deconvolution_2d`

- chainer/functions/connection/convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
> [backport] Check positive dilation in `F.convolution_2d`

- chainer/training/updaters/standard_updater.py
- tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py
Replaces #7324
Required in #7330
> Add `input_device` to `StandardUpdater`

- chainer/dataset/tabular/tabular_dataset.py
> Fix typo in `tabular_dataset.py`

- chainer/optimizer_hooks/weight_decay.py
- tests/chainer_tests/optimizer_hooks_tests/test_weight_decay.py
> Make `WeightDecay` aware of loss scale

- examples/mnist/train_mnist_model_parallel.py
Part of #7220
Merge after #7472
> Support ChainerX in MNIST model parallel example

- chainer/optimizer_hooks/weight_decay.py
- tests/chainer_tests/optimizer_hooks_tests/test_weight_decay.py
> [backport] Make `WeightDecay` aware of loss scale

- tests/chainermn_tests/communicator_tests/test_communicator.py
> [backport] Change 0 to 0.0 for python2

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
> [backport] Fix AdamW update rule regression on CPU

- chainer/functions/array/where.py
- chainer/utils/type_check.py
- tests/chainer_tests/functions_tests/array_tests/test_where.py
> [backport] Fix type check of `F.where`

- examples/ptb/train_ptb.py
> Implement `reset` method in the PTB example

- examples/ptb/train_ptb.py
> [backport] Implement `reset` method in the PTB example

- chainer/distributions/bernoulli.py
- chainer/distributions/beta.py
- chainer/distributions/categorical.py
- chainer/distributions/cauchy.py
- chainer/distributions/chisquare.py
- chainer/distributions/dirichlet.py
- chainer/distributions/exponential.py
- chainer/distributions/gamma.py
- chainer/distributions/geometric.py
- chainer/distributions/gumbel.py
- chainer/distributions/independent.py
- chainer/distributions/laplace.py
- chainer/distributions/log_normal.py
- chainer/distributions/multivariate_normal.py
- chainer/distributions/normal.py
- chainer/distributions/pareto.py
- chainer/distributions/poisson.py
- chainer/distributions/uniform.py
- chainer/distributions/utils.py
* Backslashes for breaking long lines should be discouraged (https://www.python.org/dev/peps/pep-0008/#maximum-line-length).
* Positions of new lines should reflect the structure of expressions.
> Fix code style for long expressions

- chainer/distributions/bernoulli.py
- chainer/distributions/beta.py
- chainer/distributions/categorical.py
- chainer/distributions/cauchy.py
- chainer/distributions/chisquare.py
- chainer/distributions/dirichlet.py
- chainer/distributions/exponential.py
- chainer/distributions/gamma.py
- chainer/distributions/geometric.py
- chainer/distributions/gumbel.py
- chainer/distributions/independent.py
- chainer/distributions/laplace.py
- chainer/distributions/log_normal.py
- chainer/distributions/multivariate_normal.py
- chainer/distributions/normal.py
- chainer/distributions/pareto.py
- chainer/distributions/poisson.py
- chainer/distributions/uniform.py
- chainer/distributions/utils.py
> [backport] Fix code style for long expressions

- chainerx_cc/chainerx/python/routines.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py
The python binding code for routines initialization has been split according to the code splitting in the routines/ package.
> Split python binding math routines

- tests/chainermn_tests/communicator_tests/test_mpi.py
> [backport] Add a test to reproduce the bcast deadlock problem

- setup.py
> [backport] Fix typing requirements

- chainer/functions/connection/embed_id.py
- chainer/links/connection/embed_id.py
> [backport] Correct Embed ID documentation

- docs/source/guides/extensions.rst
Part of #5484. This PR fixes the current documentation, which is inconsistent with the implementation.
> Fix inconsistent document for extension finalizer

- docs/source/guides/extensions.rst
> [backport] Fix inconsistent document for extension finalizer

- chainer/functions/activation/clipped_relu.py
Following up on https://github.com/chainer/chainer/pull/7118.
> Use `chainerx.clipped_relu` in `F.clipped_relu`

- chainer/links/model/vision/resnet.py
> [backport] Fix typos in ResNet prepare method

- docs/source/chainerx/install/index.rst
> Document `CHAINERX_CUDNN_USE_CUPY`

- chainer/functions/array/expand_dims.py
Just fixes a few typos in the docs.
> Fixes typos in expand_dims.py

- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/activation.cc
- chainerx_cc/chainerx/routines/activation.h
- tests/chainerx_tests/unit_tests/routines_tests/test_activation.py
> Add chainerx.elu

- chainer/gradient_check.py
- tests/chainer_tests/functions_tests/array_tests/test_cast.py
Part of https://github.com/chainer/chainer/issues/6071.
~Depends on a change in gradient check in #6621 . In particular https://github.com/chainer/chainer/pull/6621/files#diff-643267efb2f2b096c96a529d2818281dR1016~
> Simplify `F.cast` test

- chainer/functions/array/expand_dims.py
> [backport] Fixes typos in expand_dims.py

- chainermn/functions/collective_communication.py
- tests/chainermn_tests/functions_tests/test_collective_communication.py
This commit adds fp16 tests to collective functions.
The tests are also changed from unittest to plain tests to use the
parameterize.
> Add fp16 support to collective functions

- tests/chainer_tests/test_optimizer.py
~`UpdateRule.update` does not handle multiple devices with loss scaling.~
This PR includes test refactoring. (part of #7541)
Fixes #7584
> Refactor optimizer test for multi-backend

- tests/chainer_tests/functions_tests/activation_tests/test_crelu.py
- tests/chainer_tests/functions_tests/activation_tests/test_maxout.py
> Fix y_shape not used in tests

- chainermn/links/create_mnbn_model.py
- tests/chainermn_tests/links_tests/test_create_mnbn_model.py
This PR solved https://github.com/chainer/chainer/issues/7567
> fix a bug of `chainermn.links.create_mnbn_model`

- chainermn/links/create_mnbn_model.py
- tests/chainermn_tests/links_tests/test_create_mnbn_model.py
Backport of https://github.com/chainer/chainer/pull/7603
> [backport] fix a bug of chainermn.links.create_mnbn_model

- chainer/distribution.py
- chainer/distributions/cauchy.py
- chainer/distributions/chisquare.py
- chainer/distributions/dirichlet.py
- chainer/distributions/exponential.py
- chainer/distributions/gamma.py
- chainer/distributions/geometric.py
- chainer/distributions/gumbel.py
- chainer/distributions/one_hot_categorical.py
- chainer/distributions/pareto.py
- chainer/distributions/poisson.py
- chainer/functions/activation/slstm.py
- chainer/functions/array/as_strided.py
- chainer/functions/connection/linear.py
- chainer/functions/loss/discriminative_loss.py
- chainer/functions/math/det.py
- chainer/graph_optimizations/static_graph.py
- chainer/training/extensions/variable_statistics_plot.py
- docs/source/examples/dcgan.rst
- docs/source/guides/functions.rst
- examples/imagenet/dali_util.py
- tests/chainer_tests/distributions_tests/test_bernoulli.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_align_2d.py
> [backport] Use `backend.get_array_module` not `cuda.get_array_module`

- docs/source/guides/extensions.rst
> Correct missing parenthesis in documents

- chainer/optimizer.py
* There were code duplication.
* `GradientMethod` used private attributes/methods of `Optimizer`.
> Avoid code duplication and access violation between `Optimizer` and `GradientMethod`

- examples/sentiment/train_recursive_minibatch.py
> [backport] Warn NaN in FP16 mode in sentiment example's recursive minibatch version

- tests/chainer_tests/functions_tests/math_tests/test_polygamma.py
Simplifies `test_polygamma` using `testing.FunctionTestCase`
> Simplify `F.polygamma` test

- chainer/functions/math/average.py
> Fix a typo in chainer/functions/math/average.py 

- chainerx_cc/chainerx/backward_context.h
> [backport] Tiny Fix of `BackwardContext` comment

- chainerx_cc/chainerx/error.h
- chainerx_cc/chainerx/python/error.cc
- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/shape.h
- chainerx_cc/chainerx/shape_test.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
> Raise python `IndexError` if the index `__getitem__` takes is out of bounds

- chainer/functions/activation/prelu.py
- chainer/functions/activation/swish.py
- chainer/functions/connection/bilinear.py
- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/convolution_nd.py
- chainer/functions/connection/deconvolution_2d.py
- chainer/functions/connection/deconvolution_nd.py
- chainer/functions/connection/deformable_convolution_2d_sampler.py
- chainer/functions/connection/depthwise_convolution_2d.py
- chainer/functions/connection/embed_id.py
- chainer/functions/connection/linear.py
- chainer/functions/connection/local_convolution_2d.py
- chainer/functions/loss/black_out.py
- chainer/functions/loss/negative_sampling.py
- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/batch_renormalization.py
- chainer/functions/normalization/group_normalization.py
- chainer/functions/normalization/layer_normalization.py
- chainer/links/activation/prelu.py
> [backport] Explain corresponding `Link`s

- chainer/functions/array/broadcast.py
> [backport] Minor grammar Improvements to broadcast documentation.

- chainer/function_node.py
This fixes minor grammar and typo fixes. The semantics should be double-checked in case my understanding is wrong.
> Edits Function Node docs.

- chainer/function_hooks/cupy_memory_profile.py
- tests/chainer_tests/function_hooks_tests/test_cupy_memory_profile.py
> [backport] Fix unit selection of CupyMemoryProfiler

- chainermn/communicators/communicator_base.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- chainermn/extensions/allreduce_persistent.py
- chainermn/functions/batch_normalization.py
- chainermn/optimizers.py
- docs/source/chainermn/reference/index.rst
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/communicator_tests/test_node_aware_communicator_base.py
- tests/chainermn_tests/links_tests/test_batch_normalization.py
This PR is one of PRs to solve https://github.com/chainer/chainer/issues/6670#issuecomment-505402604
> refactor `allreduce_grad()` and functions related with it

- chainer/optimizer.py
> [backport] Avoid code duplication and access violation between `Optimizer` and `GradientMethod`

- chainer/function_node.py
> Fix flake8 error

- chainerx_cc/chainerx/array.cc
- chainerx_cc/chainerx/array.h
- chainerx_cc/chainerx/axes.h
- chainerx_cc/chainerx/axes_test.cc
- chainerx_cc/chainerx/backward.cc
- chainerx_cc/chainerx/backward_context.cc
- chainerx_cc/chainerx/backward_context.h
- chainerx_cc/chainerx/op_node.h
- chainerx_cc/chainerx/shape.h
- chainerx_cc/chainerx/shape_test.cc
- chainerx_cc/chainerx/strides.h
- chainerx_cc/chainerx/strides_test.cc
Part of #7662 (first bullet, `gsl::span` and `gsl::make_span`).
> Use `absl::Span` and related helpers instead of `gsl::span`

- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/routines.cc
> Use curly braces for constructors

- chainerx/_fallback_workarounds.py
- chainerx_cc/chainerx/CMakeLists.txt
- chainerx_cc/chainerx/array_index.cc
- chainerx_cc/chainerx/array_index.h
- chainerx_cc/chainerx/python/array_index.cc
- chainerx_cc/chainerx/routines/indexing.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
Resolve #7560.
~Depends on #7559.~
~Depends on #7614.~
> Support ellipsis in `Array::At` and `__getitem__`

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
> [backport] Avoid code duplication in optimizer hook implementation

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
> [backport] Fix AMSGrad with intel64 backend

- chainer/optimizer_hooks/gradient_lars.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_lars.py
> GradientLARS optimizer hook working with chainerx

- chainer/initializers/__init__.py
- chainer/initializers/constant.py
- tests/chainer_tests/initializer_tests/test_constant.py
- tests/chainer_tests/initializer_tests/test_normal.py
- tests/chainer_tests/initializer_tests/test_orthogonal.py
- tests/chainer_tests/initializer_tests/test_uniform.py
I blowed up the previous PR #7531 .
Adds support for chainerx arrays on chainer initializers
> Added chainerx support on initializers

- tests/chainer_tests/optimizer_hooks_tests/test_lasso.py
> test `optimizer_hooks.Lasso` for ChainerX

- chainer/variable.py
- tests/chainer_tests/functions_tests/math_tests/test_average.py
- tests/chainer_tests/test_variable.py
I added this method similar in spirit with `chainer.Variable.reshape`.
> add Variable.mean

- examples/text_classification/train_text_classifier.py
> [backport] Example fix: stateful triggers cannot be reused

- chainerx_cc/chainerx/python/kwarg.h
- chainerx_cc/chainerx/python/routines.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
> Make `device` argument a keyword only argument.

- chainer/functions/activation/lstm.py
- chainer/functions/activation/slstm.py
- chainer/functions/activation/tree_lstm.py
- chainer/functions/array/spatial_transformer_grid.py
- chainer/functions/array/spatial_transformer_sampler.py
- chainer/functions/connection/deformable_convolution_2d_sampler.py
- chainer/functions/connection/depthwise_convolution_2d.py
- chainer/functions/connection/shift.py
- chainer/functions/loss/black_out.py
- chainer/functions/loss/ctc.py
- chainer/functions/loss/negative_sampling.py
- chainer/functions/loss/triplet.py
- chainer/functions/noise/dropout.py
- chainer/functions/noise/gumbel_softmax.py
- chainer/functions/noise/zoneout.py
- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/batch_renormalization.py
- chainer/functions/normalization/local_response_normalization.py
- chainer/functions/pooling/spatial_pyramid_pooling_2d.py
- chainer/links/activation/prelu.py
- chainer/links/activation/swish.py
- chainer/links/connection/inceptionbn.py
- chainer/links/connection/tree_lstm.py
- chainer/links/normalization/batch_normalization.py
- chainer/links/normalization/batch_renormalization.py
- chainer/optimizer_hooks/gradient_lars.py
- chainer/optimizer_hooks/gradient_noise.py
- chainer/optimizers/adam.py
- chainer/optimizers/corrected_momentum_sgd.py
- chainer/optimizers/msvag.py
> [backport] Remove backslashes to continue lines of link targets

- chainer/functions/array/concat.py
Use `six.integer_types` for `axis` check in `F.concat`
> Use `six.integer_types` for axis check in `F.concat`

- tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
> [backport] Fix GroupNormalization tests

- chainer/link_hooks/spectral_normalization.py
> [backport] Fixes spectral normalization chainerx conversion

- chainer/function_node.py
> [backport] Edits Function Node docs.

- docs/source/contribution.rst
> [backport] Improve contribution docs

- tests/chainerx_tests/unit_tests/routines_tests/test_explog.py
> Relax atol/rol of `chainerx.erf` float16 test

- chainer/optimizer_hooks/gradient_hard_clipping.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_hard_clipping.py
> Fix `optimizer_hooks.GradientHardClipping` for ChainerX

- chainer/functions/activation/crelu.py
- chainer/functions/array/moveaxis.py
- chainer/functions/math/cumprod.py
- chainer/functions/math/cumsum.py
- chainer/functions/math/logsumexp.py
- chainer/functions/math/minmax.py
- chainer/functions/math/prod.py
- chainer/functions/math/sum.py
- chainer/functions/math/tensordot.py
- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/l2_normalization.py
- chainer/links/normalization/batch_normalization.py
> Use `six.integer_types` for axis checks

- chainer/functions/array/expand_dims.py
> [backport] Fixes a grammar error

- chainerx/__init__.pyi
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/activation.cc
- chainerx_cc/chainerx/routines/activation.h
- tests/chainerx_tests/unit_tests/routines_tests/test_activation.py
> Add `chainerx.softplus`

- chainer/iterators/multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
> [backport] Fix pickling issues on `MultiprocessIterator`

- chainerx_cc/chainerx/routines/manipulation.cc
> Fix offset in `chainerx::Flip`

- setup.cfg
> [backport] Fix warning filter for protobuf

- chainer/function_node.py
- tests/chainer_tests/test_function_node.py
> [backport] Fixes an error on chainer.grad for multiple devices

- chainer/optimizer.py
- chainer/variable.py
- tests/chainer_tests/test_optimizer.py
- tests/chainer_tests/test_variable.py
>  Fix `UpdateRule.use_fp32_update` for uninitialized parameter 

- tests/chainer_tests/optimizer_hooks_tests/test_weight_decay.py
> test `optimizer_hooks.WeightDecay` for ChainerX

- tests/chainer_tests/optimizer_hooks_tests/test_gradient_noise.py
> test `optimizer_hooks.GradientNoise` for ChainerX

- chainerx_cc/CMakeLists.txt
> Require CUDA if `CHAINERX_BUILD_CUDA` is set

- tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
> [backport] Fix flaky `TestContrastive`

- chainer/functions/__init__.py
- chainer/functions/normalization/_standardize.py
- chainer/functions/normalization/standardize.py
- chainer/link_hooks/weight_standardization.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/normalization_tests/test_standardize.py
- tests/chainer_tests/link_hooks_tests/test_weight_standardization.py
This PR adds [Weight Standardization](https://arxiv.org/abs/1903.10520).
Please wait for the experimental result of CIFAR-10 until tomorrow.
> Add `WeightStandardization` link hook

- chainer/functions/activation/crelu.py
- chainer/functions/array/moveaxis.py
- chainer/functions/math/cumprod.py
- chainer/functions/math/cumsum.py
- chainer/functions/math/logsumexp.py
- chainer/functions/math/minmax.py
- chainer/functions/math/prod.py
- chainer/functions/math/sum.py
- chainer/functions/math/tensordot.py
- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/l2_normalization.py
- chainer/links/normalization/batch_normalization.py
> [backport] Use `six.integer_types` for axis checks

- chainer/_version.py
- docker/intel/python2/Dockerfile
- docker/intel/python3/Dockerfile
- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version to v6.2.0

- chainer/_environment_check.py
- docs/source/install.rst
- docs/source/upgrade.rst
> Revert "Warn users for Python 2"

- docs/source/install.rst
> Revert "[v6] Add a note for Python 2 drop in v7"

- chainer/optimizers/adam.py
> [backport] Fix Adam FP16 overflow on gpu kernels

- tests/chainermn_tests/links_tests/test_multi_node_chain_list.py
This commit adds mixed16 tests to multi-node chain list
> Add Mixed16 tests to multi-node chain List

- chainer/functions/math/average.py
- tests/chainer_tests/functions_tests/math_tests/test_average.py
#7681 will be fixed if CPU with NumPy >= 1.12 or GPU.
> Make `F.average` as accurate as backend

- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
This commit adds mixed16 tests to all the p2p communications
> Add mixed16 tests to point_to_point communications

- chainer/functions/noise/dropout.py
- tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
> Change `F.dropout` to use cuDNN by default

- chainer/functions/pooling/max_pooling_2d.py
> [backport] Fix TypeError in `max_pooling_2d`

- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
> [backport] Fix test of `chx.reshape`

- chainer/dataset/tabular/__init__.py
- chainer/dataset/tabular/from_data.py
- docs/source/reference/datasets.rst
- tests/chainer_tests/dataset_tests/tabular_tests/test_from_data.py
> Add `chainer.dataset.tabular.from_data`

- scripts/ci/travis/steps.sh
> Revert #6754

- chainer/utils/type_check.py
> Fix `type_check` error message on evaluating bool expression

- chainer/utils/type_check.py
> [backport] Fix module in msg of `type_check`

- scripts/ci/travis/steps.sh
> [backport] Revert #6754

- chainerx_cc/chainerx/routines/activation.cc
This reduces memory consumption.
> Use scalar array in `chx.leaky_relu`/`elu`

- setup.py
> Relax typing version requirement in Python 3

- setup.py
> Remove mypy from requirements

- chainer/functions/normalization/decorrelated_batch_normalization.py
- chainer/links/normalization/decorrelated_batch_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_decorrelated_batch_normalization.py
> Fix decorrelated batch normalization when groups ≠ 1

- chainer/dataset/__init__.py
- chainer/dataset/convert.py
- docs/source/reference/datasets.rst
- tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py
> Add base `Converter` class

- tests/chainermn_tests/functions_tests/test_collective_communication.py
This commit add mixed16 tests to all the collective functions
> Add mixed16 tests to collective functions

- tests/chainermn_tests/functions_tests/test_pseudo_connect.py
This commit adds mixed16 tests to pseudo connect
> Add mixed16 tests to pseudo_connect

- chainer/_environment_check.py
- docs/source/install.rst
- docs/source/upgrade.rst
Re-submit of #7766 for v7.0.0b3 release.
> Drop support for Python 2.7

- chainerx_cc/CMakeLists.txt
Fixes https://github.com/chainer/chainer/issues/7815.
> Add OpenMP option for cuSOLVER

- chainermn/links/create_mnbn_model.py
- tests/chainermn_tests/links_tests/test_create_mnbn_model.py
> [backport] Fix create_mnbn_model() bug

- .pfnci/hint.pbtxt
> Add `test_accuracy.py` to the list of slow test files

- scripts/ci/chainerx/jenkins/Dockerfile.template
> [backport] Switch current directory in Jenkins tests

- chainerx/__init__.pyi
- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- chainerx_cc/chainerx/kernels/reduction.h
- chainerx_cc/chainerx/native/native_device/reduction.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/reduction.cc
- chainerx_cc/chainerx/routines/reduction.h
- tests/chainerx_tests/unit_tests/routines_tests/test_reduction.py
> Add `chainerx.nansum`

- chainer/functions/math/clip.py
> [backport] Fix `F.clip` for NumPy 1.17

- chainerx/__init__.pyi
- chainerx_cc/chainerx/kernels/sorting.h
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/sorting.cc
- chainerx_cc/chainerx/routines/sorting.h
- tests/chainerx_tests/unit_tests/routines_tests/test_sorting.py
> Add `chainerx.count_nonzero`

- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
Simplifies `test_max_pooling_2d` using `testing.FunctionTestCase`
> Simplify `F.max_pooling_2d` test

- examples/text_classification/run_text_classifier.py
Fixed issue #6770 by adding a print prompt before stdin
> Fixed issue #6770

- tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
> [backport] Configure tolerances of `F.average_pooling_2d` test

- tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
> [backport] Fix flaky `TestHuberLoss`

- chainer/training/extensions/_snapshot.py
- chainer/training/extensions/snapshot_writers.py
- examples/mnist/train_mnist.py
- tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
> [backport] Add automatic management of snapshots (deletion and load)

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
> [backport] Refactor convolution functions tests

- chainer/functions/rnn/slstm.py
- tests/chainer_tests/functions_tests/rnn_tests/test_function_slstm.py
Fix for SLSTM for omitted upstream gradients. The PR also includes some optimizations as well.
This PR replaces https://github.com/chainer/chainer/pull/7859.
LSTM should probably be fixed too after https://github.com/chainer/chainer/pull/7808.
> Fix SLSTM for omitted upstream gradients

- chainermn/communicators/communicator_base.py
This PR solves https://github.com/chainer/chainer/issues/7849
> Add scatter interface to CommunicatorBase

- chainermn/communicators/communicator_base.py
- docs/source/chainermn/reference/index.rst
This PR adds `scatter()`  to doc
> Add scatter to doc

- tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
> [backport] Sample stable inputs in tests of group normalization

- chainerx/__init__.pyi
- chainerx_cc/chainerx/cuda/cuda_device/arithmetic.cu
- chainerx_cc/chainerx/cuda/numeric.cuh
- chainerx_cc/chainerx/kernels/arithmetic.h
- chainerx_cc/chainerx/native/native_device/arithmetic.cc
- chainerx_cc/chainerx/numeric.h
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/arithmetic.cc
- chainerx_cc/chainerx/routines/arithmetic.h
- chainerx_cc/chainerx/routines/misc.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py
> Revert "Add `chainerx.fmod`"

- chainerx_cc/chainerx/cuda/cuda_device/linalg.cu
Renamed variable 'devInfo' -> 'devinfo'.
> Rename a variable in CUDA SVD kernel

- chainer/_backprop.py
- chainer/functions/activation/rrelu.py
- chainer/functions/connection/embed_id.py
- chainer/gradient_check.py
- chainer/initializers/orthogonal.py
- chainer/links/caffe/caffe_function.py
- chainer/links/connection/deconvolution_2d.py
- chainer/links/connection/deconvolution_nd.py
- chainer/links/model/vision/vgg.py
- chainer/links/rnn/lstm.py
- chainer/optimizer.py
- chainer/training/extensions/evaluator.py
- chainer/training/triggers/manual_schedule_trigger.py
- chainer/training/triggers/once_trigger.py
- chainermn/communicators/__init__.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/global_except_hook.py
- chainermn/links/multi_node_chain_list.py
- examples/chainermn/mnist/train_mnist_dual_parallel.py
- examples/mnist/train_mnist_data_parallel.py
- examples/mnist/train_mnist_model_parallel.py
- tests/chainer_tests/test_gradient_check.py
> Insert missing spaces between concatenated string literals

- chainer/link.py
- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
- tests/chainer_tests/test_link.py
> Fix in-place update of arrays in `Link.serialize` and `optimizers.Adam`

- tests/chainer_tests/functions_tests/array_tests/test_cast.py
> [backport] Avoid testing `F.cast` from negative floating-point to unsigned

- chainer/serializers/hdf5.py
- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
- tests/chainer_tests/serializers_tests/test_npz.py
> [backport] Fix ChainerX non native deserialization

- README.md
> Update stable version in README

- tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
> Relax fp16 tolerances in `TestContrastive`

- chainer/functions/pooling/average_pooling_nd.py
- chainer/functions/pooling/max_pooling_nd.py
- chainer/functions/pooling/pooling_nd.py
Part of #5452
Introducing `pooling_nd._CudnnPoolingNDImpl` refactored out of `pooling_nd._PoolingND`.
`_CudnnPoolingNDImpl` is a cuDNN implementation object that is now held by `_PoolingND`.
> Refactor `pooling_nd` functions

- docs/source/install.rst
> Add 1.17 to supported NumPy versions

- chainermn/communicators/_memory_utility.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
This PR solves  https://github.com/chainer/chainer/issues/6641
> Support for CUDA async in batched copy

- chainerx_cc/chainerx/native/CMakeLists.txt
- chainerx_cc/third_party/abseil.cmake
- chainerx_cc/third_party/gsl-lite.cmake
- chainerx_cc/third_party/gtest.cmake
- chainerx_cc/third_party/pybind11.cmake
fixed #7966 
- ~~Does your code conform to our coding guidelines?~~
No real code is involved, only cmake scripts is modified to support building on Windows 10 with VS2019 with CUDA 10.1
- ~~Did you write sufficient documentation?~~
- ~~Also, take a look at [our compatibility policy](https://docs.chainer.org/en/stable/compatibility.html).~~
> Fix Windows build of ChainerX

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
> [backport] Fix multi-device loss scaling

- chainerx/_fallback_workarounds.py
- tests/chainer_tests/functions_tests/connection_tests/test_embed_id.py
Depends #7960 
Merge after #7960
> Simplify `F.embed_id` test

- tests/chainer_tests/links_tests/loss_tests/test_crf1d.py
> [backport] Fix tolerance in `L.CRF1d` test

- docs/source/reference/static_graph.rst
- examples/static_graph_optimizations/mnist/train_mnist.py
> [backport] Fix `static_graph` docs code examples

- chainer/dataset/tabular/from_data.py
- tests/chainer_tests/dataset_tests/tabular_tests/test_from_data.py
https://github.com/chainer/chainer/pull/7276#issuecomment-515828977
> Support callable in tabular.from_data

- chainer/_version.py
- docker/intel/python2/Dockerfile
- docker/intel/python3/Dockerfile
- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version to v7.0.0b3

- chainer/_version.py
- docker/intel/python2/Dockerfile
- docker/intel/python3/Dockerfile
- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version to v.6.3.0

- tests/chainer_tests/functions_tests/math_tests/test_inv.py
> [backport] Relax float16 tolerances in `F.batch_inv` test

- chainer/training/extensions/_snapshot.py
A followup of https://github.com/chainer/chainer/pull/6856, fixing some documentation.
> Add undocumented arguments to snapshot extension signature

- chainer/training/extensions/_snapshot.py
> [backport] Add undocumented arguments to snapshot extension signature

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
> [backport] Relax tolerances in old cuDNN convolution tests

- tests/chainer_tests/functions_tests/rnn_tests/test_function_lstm.py
`F.lstm` test is taking too much time.
Separates `grad_outputs` parameterization.
> Avoid testing full combinations in `F.lstm` test parameterization

- tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
> [backport] Fix flaky `negative_sampling`

- appveyor.yml
> Drop Python 2 AppVeyor configuration

- .travis.yml
> Drop Python 2 Travis CI configuration

- .pfnci/config.pbtxt
- .pfnci/run.sh
Takes over #8015
Part of #8005
> Drop Python 2 PFN CI configuration

- chainerx_cc/chainerx/python/array.cc
- tests/chainerx_tests/conftest.py
- tests/chainerx_tests/unit_tests/test_array.py
Fixes #7974 
Alternate implementation to #7983 after discussing it with @niboshi
> Change return policy for `chx::Device` object on `ndarray` pickling

- chainer/device_resident.py
- chainer/training/updaters/standard_updater.py
- tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py
> Raise `FutureWarning` on GPU-to-GPU transfer in `StandardUpdater`

- chainerx_cc/chainerx/numeric.h
Fixes https://github.com/chainer/chainer/issues/8038.
> Fix `-Wabsolute-value` for clang

- chainerx_cc/chainerx/native/native_device/indexing.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
> Fix native `AddAt` implementation for float16 arrays

- chainer/backend.py
> [backport] Fix doc of `backend.copyto`

- chainerx_cc/chainerx/native/native_device/reduction.cc
- chainerx_cc/chainerx/native/reduce.h
- chainerx_cc/chainerx/reduction_kernel_arg.cc
- chainerx_cc/chainerx/shape.h
Refactored `NativeCumsumKernel` introduced in #7558.
> Generalize and simplify `NativeCumsumKernel`

- docker/intel/python2/Dockerfile
- docker/python2/Dockerfile
> [backport] Fix NumPy version in Dockerfile

- chainer/functions/activation/rrelu.py
- chainer/functions/connection/embed_id.py
- chainer/gradient_check.py
- chainer/links/caffe/caffe_function.py
- chainer/links/connection/deconvolution_2d.py
- chainer/links/connection/deconvolution_nd.py
- chainer/links/connection/lstm.py
- chainer/links/model/vision/vgg.py
- chainer/optimizer.py
- chainer/training/extensions/evaluator.py
- chainer/training/triggers/manual_schedule_trigger.py
- chainer/training/triggers/once_trigger.py
- chainermn/communicators/__init__.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/global_except_hook.py
- chainermn/links/multi_node_chain_list.py
- examples/chainermn/mnist/train_mnist_dual_parallel.py
- examples/mnist/train_mnist_data_parallel.py
- tests/chainer_tests/test_gradient_check.py
> [backport] Insert missing spaces between concatenated string literals

- tests/chainer_tests/links_tests/normalization_tests/test_decorrelated_batch_normalization.py
> [backport] Refactor `DecorrelatedBatchNormalizationTest` and add stable input

- tests/chainer_tests/optimizers_tests/test_optimizers.py
Adds an extra test for test coverage of optimizers.
Merge after  #7918
>  Add test for optimizers test coverage 

- chainerx_cc/chainerx/backward_builder.cc
Fixed #8087 
Just syntax issue.
> use standard constructor

- chainerx/_docs/__init__.py
- chainerx/_docs/utils.py
- docs/source/chainerx/reference/ndarray.rst
> Document `chainerx.to_numpy`

- chainer/functions/normalization/decorrelated_batch_normalization.py
> [backport] Remove unused argument from decorrelated batch norm

- examples/wavenet/modules.py
- examples/wavenet/net.py
Replace Convolution2D with (k, 1)-size kernels with Convolution1D, etc.
And rename `__call__` methods to `forward`.
> Use some latest features for the WaveNet example

- tests/chainer_tests/serializers_tests/test_hdf5.py
> [backport] Explicit `h5py.File` `mode`

- chainer/functions/loss/contrastive.py
> [backport] Fix eps in `Contrastive.backward`

- chainerx_cc/chainerx/backward_builder.h
- chainerx_cc/chainerx/context.h
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/float16.h
- chainerx_cc/chainerx/float16_test.cc
- chainerx_cc/chainerx/kernel_registry.h
- chainerx_cc/chainerx/native/kernel_regist.h
- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/chainer_interop.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/testing/threading.h
- scripts/ci/travis/run-tests.sh
> Revive clang-tidy test in Travis CI

- chainermn/functions/batch_normalization.py
- chainermn/functions/collective_communication.py
- chainermn/links/batch_normalization.py
- chainermn/links/create_mnbn_model.py
See: 
https://www.python.org/dev/peps/pep-0008/#imports
https://docs.openstack.org/hacking/latest/user/hacking.html#imports
> Fix coding style of some imports in ChainerMN

- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- chainerx_cc/chainerx/cuda/reduce.cuh
- chainerx_cc/chainerx/native/reduce.h
- tests/chainerx_tests/unit_tests/routines_tests/test_reduction.py
> Add cuda `ScanKernel`

- chainer/training/updaters/multiprocess_parallel_updater.py
> [backport] Fix deadlock on MultiprocessIterator and MultiprocessParallelUpdater

- examples/imagenet/dataset_util.py
- examples/imagenet/train_imagenet.py
- examples/imagenet/train_imagenet_data_parallel.py
This PR fixes an issue #8063. Would you please review and merge this PR if it's ok!
> Separate training script into main part and data submodule to avoid an error related to NVIDIA DALI.

- setup.cfg
> Remove TODO fixed by #7528

- chainerx/__init__.pyi
- chainerx/_docs/routines.py
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/loss.cc
- chainerx_cc/chainerx/routines/loss.h
- docs/source/chainerx/reference/routines.rst
- tests/chainerx_tests/unit_tests/routines_tests/test_loss.py
Reverts chainer/chainer#8051
Please refer to https://github.com/chainer/chainer/issues/8106 for why it's being reverted.
> Revert "Add mean_squared_error for chainerX"

- chainer/testing/parameterized.py
> [backport] Make parameterized test names deterministic

- tests/chainer_tests/functions_tests/array_tests/test_im2col.py
Fixes #8035
* Before this PR: 2 failures in 180,824 trials
* With this PR: No failure in 1,000,000 trials
> Relax tolerance of im2col test

- tests/chainer_tests/functions_tests/array_tests/test_im2col.py
> [backport] Relax tolerance of im2col test

- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
> Filter DeprecationWarning in test_maniplation.py

- chainer/functions/__init__.py
- chainer/functions/math/zeta.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/math_tests/test_zeta.py
This PR aims to add Zeta function from Tensorflow as per Issue #1448 
I plan to follow this route -
> Add zeta function

- chainer/link.py
- tests/chainer_tests/test_link.py
> Fixes deepcopy for chain parameters

- chainerx/__init__.pyi
- chainerx/_docs/routines.py
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/manipulation.cc
- chainerx_cc/chainerx/routines/manipulation.h
- docs/source/chainerx/reference/routines.rst
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
> [chainerx] Adds vsplit

- chainer/link.py
- tests/chainer_tests/test_link.py
> [backport] Fixes deepcopy for chain parameters

- docs/source/chainerx/install/index.rst
Fixes https://github.com/chainer/chainer/issues/8041.
Also improves related existing documentation.
> Documentation improvement `CHAINERX_ENABLE_{BLAS,LAPACK}`

- tests/chainerx_tests/unit_tests/routines_tests/test_loss.py
> Fix missing dtype checks in ChainerX loss test

- chainer/_version.py
- docker/intel/python2/Dockerfile
- docker/intel/python3/Dockerfile
- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version to v6.4.0

- examples/wavenet/generate.py
- examples/wavenet/modules.py
- examples/wavenet/net.py
- examples/wavenet/utils.py
This PR related to #8156, #8157 and https://github.com/chainer/chainer-test/issues/528. And focus on https://github.com/chainer/chainer/pull/8157#pullrequestreview-292267361.
FYI: Now I'm working on add tests for WaveNet example.
> Fix `generate.py` in examples/wavenet

- examples/wavenet/net.py
- examples/wavenet/utils.py
`Convolution1D` caused an error because the input shape was still 4D. So converted.
> Fix chainer#8156

- chainer/testing/parameterized.py
> Fix `__str__` of parameterized class

- chainer/testing/parameterized.py
> [backport] Fix `__str__` of parameterized class

- .pfnci/hint.pbtxt
- .pfnci/run.sh
> Disable flaky test retry in flexCI

- tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
> [backport] Fix overflow warning in div backward test

- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
> [backport] Relax `BatchNormalization` backward test tolerances

- setup.cfg
This problem should be resolved by https://github.com/cupy/cupy/pull/2488.
> Remove `ImportWarning` ignore entry

- tests/chainer_tests/serializers_tests/test_hdf5.py
> [backport] Fix comparison with casting in hdf5 serializer test

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
> [backport] Adjust `TestConvolution2DFunction::test_double_backward` fp16 tolerance

- chainer/functions/normalization/batch_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
This PR is a follow up of the PR #8149 with:
1. tests added for x and gamma/beta have different dtypes
2. bugs fixes in the BN
This PR should be merged after #8149
> Fix bugs when x and gamma/beta have different dtypes in BN

- chainermn/extensions/__init__.py
- chainermn/extensions/multi_node_evaluator.py
- docs/source/chainermn/reference/index.rst
- tests/chainermn_tests/extensions_tests/test_multi_node_evaluator.py
Addresses #7305. Example usage is this: https://gist.github.com/kuenishi/3c9420ee01af86edcd77d73524fb1435
> A new multi-node evaluator for force_equal_length=False

- chainer/functions/connection/n_step_gru.py
- chainer/functions/connection/n_step_rnn.py
- chainer/links/connection/n_step_lstm.py
- chainer/links/connection/n_step_rnn.py
> [backport] Fix RNN documentation

- chainermn/communicators/__init__.py
- chainermn/communicators/communicator_base.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- docs/source/chainermn/reference/index.rst
- tests/chainermn_tests/communicator_tests/test_communicator.py
With this change, communicator configuration can be changed after creation.
> New configuration system of communicator inspired by links

- tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py
> [backport] Fix tests of `L.BatchRenormalization` and adjust tolerances

- chainer/_runtime_info.py
- docs/source/reference/util.rst
- tests/chainer_tests/test_runtime_info.py
> [backport] Add document print runtime info

- setup.py
> Fix attrs version

- chainerx_cc/chainerx/cuda/memory_pool.h
It's a virtual base class. Should have one.
> Add virtual destructor in CUDA `Allocator`

- chainerx_cc/chainerx/device.h
Remove unused classes `{Max,Average}PoolForwardBackward`.
> Remove unused classes `{Max,Average}PoolForwardBackward` 

- setup.py
- tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
> Fix caffe test with protobuf>=3.8

- .pfnci/hint.pbtxt
- .pfnci/run.sh
> [backport] Disable flaky test retry in flexCI

- setup.py
> [backport] Fix attrs version

- setup.py
- tests/chainer_tests/links_tests/caffe_tests/test_caffe_function.py
> [backport] Fix caffe test with protobuf>=3.8

- .pfnci/config.pbtxt
> [backport] Increase CPU memory for test instance in PFN CI

- setup.py
See #8228
#8228 will be completed by chainer/chainer-test#530
> Add "jenkins" extras

- setup.py
> [backport] Add "jenkins" extras

- chainerx/__init__.pyi
- chainerx/_docs/routines.py
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/manipulation.cc
- chainerx_cc/chainerx/routines/manipulation.h
- docs/source/chainerx/reference/routines.rst
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
> [chainerx] Adds hsplit

- chainer/functions/normalization/batch_normalization.py
Addresses https://github.com/chainer/chainer/pull/8175#pullrequestreview-295345169
Takes over  #8206
Note that  #8211 is required to enable relevant test configurations in CIs.
> Refactor ideep workarounds in `F.batch_normalization`

- chainer/functions/normalization/batch_normalization.py
https://github.com/chainer/chainer/pull/8266#issuecomment-540364066
> Revert #8216

- chainer/gradient_check.py
Fixes #8025
Ran the test with the same parameters 100,000 times without a failure.
Small elements in the direction vector leads to instability on gradients comparison.
In order to avoid that, absolute values are capped at 0.1 / sqrt(N) at minimum, where N is the number of elements. Other elements are scaled uniformly so that the total L2 norm will remain 1.
> Fix directional gradient stability in `gradient_check`

- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/creation.cc
- chainerx_cc/chainerx/routines/creation.h
> Remove `device` argument from `chainerx.diag` and `chainerx.diagflat`

- chainer/gradient_check.py
- chainerx/_fallback_workarounds.py
- tests/chainer_tests/test_gradient_check.py
- Use weighted root mean square to fix small values.  https://github.com/chainer/chainer/pull/8236#discussion_r331945995
- Test the sampling routine.
> Fix algorithm to avoid small directions in `gradient_check`

- setup.cfg
Fix issues like chainer/chainer-test#534.
> Make ImportWarning just a warning in tests

- .github/ISSUE_TEMPLATE.md
- README.md
- docs/source/index.rst
> [backport] Replace Slack invitation links

- chainer/distributions/independent.py
- chainer/functions/loss/softmax_cross_entropy.py
- chainer/functions/pooling/spatial_pyramid_pooling_2d.py
- chainer/training/extensions/_snapshot.py
- examples/imagenet/dali_util.py
- examples/imagenet/train_imagenet.py
- examples/mnist/train_mnist.py
- tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
> [backport] Update variable names for consistent naming convention

- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/manipulation.cc
- chainerx_cc/chainerx/routines/manipulation.h
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
References: #6423 
To-Do:
* Update test for no `condition` case.
* Figure the correct way for test.
* Add Documentation
> [WIP] Add `chainerx.copyto`

- chainer/_version.py
- docker/intel/python2/Dockerfile
- docker/intel/python3/Dockerfile
- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version to v6.5.0

- .pfnci/config.pbtxt
This change is required for this CI script update: https://github.com/chainer/chainercv/pull/935.
> Include `.git` in ChainerCV compatibility CI

- tests/chainer_tests/functions_tests/pooling_tests/pooling_nd_helper.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_align_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_average_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_align_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_spatial_pyramid_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
- Fix #7923.
- Unify the implementation.
> Fix inputs of pooling function tests

- onnx_chainer/functions/__init__.py
- onnx_chainer/functions/array.py
- onnx_chainer/mapping.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
This PR adds `Permutate` exporter to `onnx_chainer`.
> Add Permutate exporter to onnx_chainer

- tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_decorrelated_batch_normalization.py
See 7dbfab0d84942653b88b86a3306ba1417bdf5609.  Close #6908.
> Fix Decorrelated Batch Normalization tests

- .pfnci/config.pbtxt
- docs/source/onnx_chainer/introduction/index.rst
- onnx_chainer/.flexci/run_test.bat
- onnx_chainer/.flexci/run_test.sh
- onnx_chainer/export.py
- setup.py
- update onnx version, 1.5 -> 1.6
- add CI job, run tests under onnx 1.5
- update CUDA on Windows, 10.0 -> 10.1
**not** include opset11 tests
> Update onnx version

- docs/source/onnx_chainer/introduction/index.rst
followed #8333 , add link to example.
> Fix docs of ONNX export introduction

- chainerx_cc/chainerx/routines/indexing.h
Including https://github.com/chainer/chainer/pull/8281#discussion_r333466640
> Code clean up for `routines/indexing.h`

- tests/chainer_tests/functions_tests/array_tests/test_cast.py
> Relax float16 forward tolerance of `F.cast` test

- .pfnci/run.sh
Related: #6625
Applies in flexCI results as well.
> Show pytest summary in flexCI

- scripts/ci/travis/run-tests.sh
> Set CHAINER_CI in Travis CI

- .pfnci/run.sh
> Set CHAINER_CI in Chainer tests in FlexCI

- tests/conftest.py
> Print installed packages in pytest

- chainer/testing/function_link.py
> Print actual array values in `FunctionTest` modified input error

- tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
Fix #8024.
`dist` differs at most `4 * eps`.
> Avoid non-differential point in `TestTriplet`

- .pfnci/config.pbtxt
- .pfnci/script.sh
> [backport] Use different docker image for each base development branch

- chainer/functions/loss/softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
> [backport] Fix SCE with ChainerX and normalize

- chainer/optimizer.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
Closes #8387 
Notice that pickling an optimizer will also dump the associated model.
> Fix pickling of optimizers

- tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
> [backport] Avoid non-differential point in `TestTriplet`

- chainer/training/extensions/_snapshot.py
> Fix style in `_snapshot.py`

- docs/source/chainermn/tutorial/step2_datasets_evaluators.rst
> Fix scatter_dataset part of ChainerMN tutorial 

- docs/source/chainermn/installation/guide.rst
- docs/source/install.rst
- docs/source/reference/configuration.rst
- docs/source/upgrade.rst
Rel: https://github.com/chainer/chainer/pull/8405
> Update minimum required python version to 3.5.2

- chainerx_cc/third_party/abseil.cmake
> Fix CMake target name for abseil

- .pfnci/run.sh
> [backport] Show pytest summary in flexCI

- chainer/links/connection/n_step_gru.py
> [backport] Fix documentation of NStepGRUBase

- tests/conftest.py
> [backport] Print installed packages in pytest

- scripts/ci/travis/run-tests.sh
> [backport] Set CHAINER_CI in Travis CI

- chainer/optimizer_hooks/gradient_hard_clipping.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_hard_clipping.py
> [backport] Fix `optimizer_hooks.GradientHardClipping` for ChainerX

- chainer/testing/function_link.py
> [backport] Print actual array values in `FunctionTest` modified input error

- .pfnci/run.sh
> [backport] Set CHAINER_CI in Chainer tests in FlexCI

- scripts/ci/chainerx/jenkins/run.sh
> [backport] Set CHAINER_CI in ChainerX tests in Jenkins

- README.md
> [backport] Link to examples directory for the current branch

- README.md
- chainer2019_bibtex.txt
> [backport] Changes citation to new KDD paper

- chainer/optimizer.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
> [backport] Fix pickling of optimizers

- chainerx_cc/chainerx/cuda/memory_pool_test.cc
> Add unsigned integer suffix

- .mergify.yml
> Add ChainerMN and ONNX-chainer tests to Mergify requirements

- examples/mnist/README.md
- examples/mnist/train_mnist_data_parallel_updater.py
In some cases a simpler example other than imagenet can be useful for debugging the MultiprocessParallelUpdater
> Add MNIST MultiprocessParallelUpdater example

- chainerx/_docs/routines.py
> Fix typo in math expressions

- chainer/links/connection/n_step_lstm.py
- chainer/links/connection/n_step_rnn.py
> [backport] Fix n-step RNN docs

- onnx_chainer/functions/__init__.py
- onnx_chainer/functions/array.py
- onnx_chainer/mapping.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
This Pull Request is intend to add support of Rollaxis in ONN-Chainer (#8427).
> Support Rollaxis in ONNX-Chainer

- tests/chainerx_tests/unit_tests/routines_tests/test_rnn.py
Fixes #8274
0 failure in 10,000 runs (I feel a bit silly but checked anyway)
> Fix random in ChainerX n-step GRU test

- tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_decorrelated_batch_normalization.py
> [backport] Fix Decorrelated Batch Normalization tests

- chainer/functions/loss/negative_sampling.py
> [backport] Compute `F.negative_sampling` in fp32 for fp16 inputs

- chainer/functions/normalization/batch_normalization.py
> [backport] Fix ChainerX fallback condition in batch normalization

- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
> [backport] Register uninitialized persistents

- chainerx_cc/chainerx/backend_testdata/CMakeLists.txt
Alternative to https://github.com/chainer/chainer/pull/8447.
> Lookup macOS undefined symbols at runtime in backend tests

- .travis.yml
- examples/test_utils.py
- examples/tests/test_imagenet.py
- scripts/ci/travis/run-tests.sh
- scripts/ci/travis/steps.sh
Follow-up of #7475
Adds a matrix in Travis CI for example tests.
> Run example tests in Travis CI

- examples/imagenet/.testdata/replacements/train_imagenet.py
This PR fixes the CI failure caused by the conflict between #8074 and #8251
> Fix example test data

- tests/chainer_tests/functions_tests/math_tests/test_cholesky.py
Avoid Jenkins failure introduced in #8202.
> Remove ChainerX `F.cholesky` test

- chainer/functions/array/reshape.py
- docs/source/tips.rst
> [backport] Update expected messages of `type_check` errors

- chainer/backends/cuda.py
- setup.cfg
> Ignore `cupy.util.PerformanceWarning` in pytest

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
> [backport] Skip some `Convolution2D` tests for older numpy versions

- tests/chainer_tests/distributions_tests/test_utils.py
> [backport] Fix flaky test of `_modified_xlogx`

- .pfnci/script.sh
> [backport] Add error message for invalid base branch in pfnCI

- .pfnci/config.pbtxt
- .pfnci/run.sh
> [backport] Adjust timeout and build memory usage in FlexCI

- chainer/_version.py
- docker/intel/python2/Dockerfile
- docker/intel/python3/Dockerfile
- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version to v6.6.0

- chainer/_version.py
- docker/intel/python3/Dockerfile
- docker/python3/Dockerfile
> Bump version to v7.0.0

- chainer/reporter.py
> [backport] Add try/finally block to yield in reporter.py

- chainer/datasets/sub_dataset.py
> Replaced n_fold with n_folds

- chainer/links/rnn/n_step_rnn.py
- tests/chainer_tests/links_tests/rnn_tests/test_link_n_step_rnn.py
I separate this PR from #8438, which aims to support custom initializer in NStepRNN first.
https://github.com/chainer/chainer/pull/8438
> Support custom initializers in NStepRNN

- onnx_chainer/mapping.py
- tests/onnx_chainer_tests/functions_tests/test_rnn.py
This depends on #8492 and #8493, and I made this PR as a draft PR because it contains a workaround to avoid `ValidationError`.
> Add NStepGRU link converter example to ONNX-Chainer test

- chainermn/extensions/checkpoint.py
> Fix typo: chainermn.extension -> chainermn.extensions

- tests/chainer_tests/functions_tests/loss_tests/test_decov.py
> [backport] Use `FunctionTestCase` to test `F.decov`

- chainer/functions/connection/n_step_gru.py
- chainer/functions/connection/n_step_lstm.py
- chainer/functions/connection/n_step_rnn.py
> [backport] Fix several documentation errors in chainer.functions.rnn.*

- chainer/_version.py
- docker/intel/python2/Dockerfile
- docker/intel/python3/Dockerfile
- docker/python2/Dockerfile
- docker/python3/Dockerfile
> Bump version to v6.7.0

- chainer/_version.py
- docker/intel/python3/Dockerfile
- docker/python3/Dockerfile
> Bump version to v7.1.0

- chainer/_version.py
- docker/intel/python3/Dockerfile
- docker/python3/Dockerfile
> Bump version to v7.2.0

- chainer/_version.py
- docker/intel/python3/Dockerfile
- docker/python3/Dockerfile
> Bump version to v7.4.0

- onnx_chainer/.flexci/run_test.bat
> Fix onnxruntime version for CI failure

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/source/contribution.rst
- docs/source/index.rst
Credit also goes to @himkt (#8535, thanks!)
> Add message about maintenance phase

- docs/rtd_conda.yml
- readthedocs.yml
> Bump python version for RTD build

- setup.py
Fix `pytest-cov` (chainer/chainer-test#603) and `coverage` (chainer/chainer-test#546).
> Update `[jenkins]` requirement

- examples/optuna/chainer_integration.py
- examples/optuna/chainer_simple.py
- examples/optuna/chainermn_integration.py
- examples/optuna/chainermn_simple.py
Updated the four optuna examples and fixed the line lengths. 🙇‍♂️
> Update optuna examples
