chainer/chainer

- examples/imagenet/train_imagenet.py
This PR fixes imagenet example to properly pass device ID, where #6397 was not enough.
This change is tested in https://github.com/chainer/chainer-test/pull/495.
> Properly pass device ID to DALI pipelines in imagenet example

- chainer/function_hooks/cupy_memory_profile.py
- tests/chainer_tests/function_hooks_tests/test_cupy_memory_profile.py
Same as #6254.
The units of memory profile are not aligned in current version.
It is hard to find a bottleneck.
This PR adds option `align` to the member function `print_report()`.
> Add option `unit` to `CupyMemoryProfileHook.print_report()`

- chainerx_cc/chainerx/routines/CMakeLists.txt
- chainerx_cc/chainerx/routines/type_util.cc
- chainerx_cc/chainerx/routines/type_util.h
Introduced `type_util.cc` and moved some `ResultTypeResolver` method definitions to it, to avoid multiple definitions error when including the header in multiple files.
> Fix ResultTypeResolver multiple definitions

- chainer/function_hooks/timer.py
The PR renew the example output (L36--40) to present the behavior of the new (#6254) default value `unit='auto'`.
This change is same as https://github.com/chainer/chainer/pull/6256#pullrequestreview-210474886.
> Fix docment in `TimerHook`

- docs/Makefile
- scripts/ci/travis/steps.sh
For first-time contributors, I'd like to make `make html` always finish.
Merge chainer/chainer-test#500 first.
> Remove `SPHINXOPTS` env from Makefile

- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
Fixes a part of #6071
~As `F.softmax_cross_entropy` has an integer input, `gradient_check` also needs a fix for ChainerX.~
Fixed by omitting `t` from `generate_inputs`. The previous fix caused `F.sigmoid_cross_entropy` test to fail.
> Simplify `F.softmax_cross_entropy` test

- tests/chainer_tests/functions_tests/activation_tests/test_log_softmax.py
Simplifies `test_log_softmax` using `testing.FunctionTestCase`.
Fixes part of issue #6071
> Simplify `F.log_softmax` test

- chainer/testing/function.py
Adds `FunctionTestCase.check_forward_outputs()` which can be overridden.
Introduced for use in #6437.
> Customizable forward output check in `testing.FunctionTestCase`

- chainer/functions/normalization/group_normalization.py
- chainer/links/normalization/group_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
Memory consumption reduced and speed slightly improved.
* cuDNN's batch normalization routine is directly called to simplify computation graph.
* `x_hat = (x - mean) / std` is re-computed at backward phase to reduce memory consumption.
* Some `ElementwiseKernel` and `ReductionKernel` are used to reduce kernel calls.
Note that if we cache `x_hat`, speed can be further improved. But I think memory consumption is more crucial, because Group Normalization is particularly useful when batch size can't be increased due to memory limit.
Regarding speed, time to train ResNet50 with 224 x 224 input images becomes 94.5%. Validation was done at each epoch, and train/valid split ratio was 8/2. Batch size was 32. The benchmark environment is as follows.
* CPU: Ryzen7 2700X
* GPU: ZOTAC GTX 1080 Ti Amp …
> improve `F.group_normalization` via cuDNN call

- examples/imagenet/dali_util.py
This PR follows #6429 to use `__future__.division` so that the imagenet example correctly runs with DALI in Python2. This change is tested in chainer/chainer-test#495.
> Use __future__.division in imagenet example with Python2

- tests/chainer_tests/functions_tests/array_tests/test_fliplr.py
Simplifies `test_flipr` using `testing.FunctionTestCase`
> Simplify `F.flipr` test

- examples/.gitignore
- examples/mnist/.gitignore
Current `examples/.gitignore` added by https://github.com/chainer/chainer/pull/2205 only ignores examples/result.
But I don't think this is expected behavior because every single example folder like `'mnist'` and `'dcgan'` has `README.md` and some users would run an experiment in one specific example folder.
IMO, it is natural to assume users to run a MNIST example by `python train_mnist.py ...` instead of `python mnist/train_mnist.py ...`.
> Fix examples/.gitignore

- tests/chainer_tests/functions_tests/array_tests/test_flipud.py
Simplifies `test_flipud` using `testing.FunctionTestCase`
> Simplify `F.flipud` test

- tests/chainer_tests/functions_tests/array_tests/test_moveaxis.py
Simplifies `test_moveaxis` using `testing.FunctionTestCase`
> Simplify `F.moveaxis` test

- tests/chainer_tests/functions_tests/array_tests/test_rollaxis.py
Simplifies `test_rollaxis` using `testing.FunctionTestCase`
solves part of issue #6071
> Simplify `F.rollaxis` test

- chainer/utils/error.py
Passing a single ndarray to `_format_array_props` yields unintuitive results. This PR simply asserts that it's never called that way.
> Assert that input to array props formatter is a list or tuple

- chainer/testing/attr.py
This issue was originally reported in CuPy (https://github.com/cupy/cupy/issues/1917).
The same fix as done in CuPy: https://github.com/cupy/cupy/pull/2055
> Avoid using pytest attributes during import

- chainer/functions/pooling/average_pooling_nd.py
- chainer/functions/pooling/average_pooling_nd_kernel.py
- tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_nd.py
Closes #6210 and related to #6071
> Fix backward of `F.average_pooling_nd` with pad_value of None

- tests/chainer_tests/functions_tests/array_tests/test_pad.py
Follows #6393. This PR fixes the test of `F.pad` in Python2.
> Fix `F.pad` test for Python2

- chainer/testing/attr.py
> [backport] Avoid using pytest attributes during import

- chainerx_cc/.clang-tidy
so that's it's easier to work with (`Checks:` is getting longer).
> Fix style of `.clang-tidy`

- chainer/optimizer.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
This PR aims to support "dynamic" loss scaling.
Loss scaling is already available with current Chainer, but it is "static" loss scaling. You have to select an appropriate loss scaling factor before training, hence becoming kind of hyper parameter.
With this PR, there is no need to select scaling factor in advance. The appropriate scaling factor is dynamically determined by just adding following line to your training script.
optimizer.loss_scaling('dynamic', interval=1000)
When "dynamic" loss scaling is enabled, whole grads of parameters are checked every iteration, more specifically after backward() and before update() to see if there are NaNs in the grads. Initially the scaling factor is set to 1 and it will be doubled every iteration as long as there is no NaN in the grads. Once NaN is …
> Dynamic loss scaling

- chainer/functions/normalization/group_normalization.py
- chainer/links/normalization/group_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
This PR aims to complete `F.group_normalization` tests by adding np.float16 and np.float64.
Tolerance for fp16 is the same as that of `F.batch_normalization` test.
> Add float16 and float 64 to `F.group_normalization` test

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
Fixes #6299
With this fix, `Adam` no longer complains the default `eps` to be too small for float16 parameters.
Similar fix to #6366
> Change intermediate dtype of `Adam` for float16 parameters to float32

- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/group_normalization.py
This PR follows https://github.com/cupy/cupy/pull/2060 and https://github.com/cupy/cupy/pull/2072 to make `cupy.cudnn.batch_normalization_forward_training` keep backward compatibility, and must be merged simultaneously with https://github.com/cupy/cupy/pull/2072
> Keep backward compatibility on cupy.cudnn.batch_normalization_forward_training

- tests/chainer_tests/functions_tests/array_tests/test_vstack.py
#6410 changed inputs to an `ndarray` from a list of `ndarray`s.
> Fix input of `F.vstack` to a list of ndarrays

- tests/chainer_tests/functions_tests/array_tests/test_swapaxes.py
Simplifies `test_swapaxes` using `testing.FunctionTestCase`
> Simplify `F.swapaxes` test

- tests/chainer_tests/functions_tests/array_tests/test_transpose.py
Simplifies `test_transpose` using `testing.FunctionTestCase`.
> Simplify `F.transpose` test

- chainer/functions/activation/prelu.py
- fixed wrong explanation (#6454)
- fixed wrong explanation _Its first argument is assumed to be the minibatch dimension._ -> _Its first axis is assumed to be the minibatch dimension._
- moved explanation of broadcasting to note directive.
> Refactor Documentation of F.prelu

- chainermn/communicators/pure_nccl_communicator.py
- chainermn/nccl.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/links_tests/test_batch_normalization.py
- tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
'nccl.get_version()' in the CuPy master returns 0 when using the old version (such as 2.2) of NCCL.
It is the cause of a bug in `PureNcclCommunicator` in ChainerMN.
This PR fixes it.
> fix NCCL version check error in ChainerMN

- .travis.yml
- tests/chainer_tests/test_gradient_check.py
Trying to work around the Travis CI failure for Python 3.4 on MacOS with Accelerate NumPy by skipping the test.
> Fix Python 3.4 NumPy Accelerate polyfit error

- setup.py
The requirement is unnecessarily too strict.
Related: #6164
> Loosen pytest requirement

- chainermn/communicators/_communication_utility.py
- chainermn/communicators/_memory_utility.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- chainermn/functions/batch_normalization.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This commit add fp16 support to the chainermn communicators including:
- flat_communicator
- hierarchical_communicator
- non_cuda_aware_communicator
- two_dimensional_communicator
- single_node_communicator
Since the MPI does not support Allreduce on fp16,
the model will first be converted into fp32 if it is originally in fp16
for Allreduce. The model will get converted back to fp16 after the all
reduce.
- Also, take a look at [our compatibility …
> Adding fp16 support to the chainermn Communicators

- chainer/functions/connection/n_step_gru.py
- chainer/functions/connection/n_step_lstm.py
- chainer/functions/connection/n_step_rnn.py
- chainer/links/connection/n_step_rnn.py
- tests/chainer_tests/links_tests/connection_tests/test_n_step_gru.py
- tests/chainer_tests/links_tests/connection_tests/test_n_step_lstm.py
- tests/chainer_tests/links_tests/connection_tests/test_n_step_rnn.py
This PR resolves #6262.
> `NStepLSTM` raises `cudaErrorIllegalAddress` when `n_layers>1` *and* `device>0` with multi-gpu environment.
> 
> This phenomenon is not observed when `n_layers=1` or `device=0`.
> Fix `chainer.links.NStepRNN` and its variants

- chainer/__init__.py
- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/batch_renormalization.py
- chainer/links/normalization/batch_normalization.py
- docs/source/reference/configuration.rst
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
- tests/chainer_tests/test_init.py
This PR introduces a new default dtype mode named `mixed16`. With this mode, Chainer basically uses `float16` as the default float dtype, but when Chainer decides that it is better to use higher precision representation for numerical stability and computational efficiency, it uses other float dtypes, esp. `float32`.
The batch normalization fix is based on #6265.
`chainer.mixed16` is a new dtype-like object. It can be passed to any numpy/cupy functions, where the dtype is interpreted as `float16`. Therefore, most existing code will just behave like the conventional FP16 mode. Specifying environment variable `CHAINER_DTYPE=mixed16` is equivalent to `chainer.global_config.dtype = chainer.mixed16`.
`chainer.get_dtype()` is extended to handle `mixed16` in a special manner. By passing an option …
> `mixed16` mode and its support in `L.BatchNormalization`

- tests/chainer_tests/functions_tests/activation_tests/test_swish.py
Simplifies `test_swish` by using `testing.FunctionTestCase`
Fixes part of issue #6071
> Simplify `F.swish` test

- chainerx_cc/chainerx/cuda/cuda_conv.cc
`gw` is always contiguous because it's a brand-new array.
> Remove unnecessary `AsContiguous` in `CudaConv::ConvGradWeight`

- chainer/functions/array/cast.py
- tests/chainer_tests/functions_tests/array_tests/test_cast.py
With this fix, `F.cast` supports casts involving non-float dtypes.
> Support non-float cast in `F.cast`

- tests/chainerx_tests/op_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> Force camel case class name for `OpTest`

- chainerx/testing/__init__.py
- chainerx/testing/dtypes.py
- tests/chainerx_tests/unit_tests/testing_tests/test_dtypes.py
> Add `chainerx.testing.integral_dtypes`

- chainer/functions/normalization/batch_normalization.py
- chainer/links/connection/n_step_rnn.py
#6184 missed these docstrings.  I found these when I made its backport PR.
```
% grep '" *# *NOQA' **/*.py
chainer/link.py:        """  # NOQA
chainer/link.py:        """  # NOQA
chainerx/testing/helper.py:    """  # NOQA
```
I left these because they have long summary lines.
> Avoid `# NOQA` in docstrings (cont.)

- chainerx_cc/chainerx/routines/linalg.cc
Some TODOs, so that they won't be forgotten.
> Write TODOs to address `Dot` backward cast

- chainer/testing/parameterized.py
This PR makes the following code work.
```py
shapes = [
(1, 2),
(3, 4, 5)
]
@chainer.testing.parameterize_pytest('shape', shapes)
class TestFoo...
```
> Fix `parameterize_pytest` to allow parameterizing with tuples

- examples/imagenet/dali_util.py
Follows #6462 .
This PR fixes the imagenet example to use float division instead of `__future__.division` for Python2 to compute cropping size.
> Use float division instead of `__future__.division` for Python2

- chainerx_cc/chainerx/routines/normalization.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_normalization.py
Partially fixes https://github.com/chainer/chainer/issues/6401
Also fixes a bug in `BatchNorm` for "None" upstream gradients.
> Rewrite ChainerX `batch_norm` test

- examples/imagenet/dali_util.py
> [backport] Use float division instead of `__future__.division` for Python2

- docs/source/reference/check.rst
This PR removes duplicated `chainer.testing.get_trainer_with_mock_updater` in the reference's "Asserting and Testing" section.
> Remove duplicated entry in reference

- chainer/link.py
- chainer/links/connection/convolution_2d.py
- chainer/links/connection/linear.py
- chainer/links/normalization/batch_normalization.py
- chainer/sequential.py
- tests/chainer_tests/test_link.py
- tests/chainer_tests/test_sequential.py
Currently, the representation of models implemented using Chain and ChainList is not so helpful to get to know about the model structure as follows.
```
% cat model_resnet.py
from chainer.links.model.vision.resnet import ResNet50Layers
model = ResNet50Layers(pretrained_model=None)
print(model)
% python model_resnet.py
<chainer.links.model.vision.resnet.ResNet50Layers object at 0x108fc4e48>
```
I think it is useful for users if registered links are printed, even though chainer has the define-by-run policy.
Below demonstrates the representation of ResNet50 with the pathces on this PR, and it seems better than before to understand its architecture.
```
ResNet50Layers(
(bn1): BatchNormalization(size=64, decay=0.9, eps=2e-05, dtype=<class 'numpy.float32'>, use_gamma=True, use_beta=True), …
```
> Human readable representation of link and chain

- chainer/functions/normalization/batch_normalization.py
Removed commented out code from `_BNMode` used in batch normalization.
> Remove commented out code from `_BNMode`

- docs/source/reference/check.rst
Rel. 5408.
This PR adds `gradient_check.check_double_backward` to the reference.
> Add gradient_check.check_double_backward in reference

- examples/dcgan/net.py
Rel. #6168.
This PR fixes DCGAN example to work with the default dtype feature.
> Fix DCGAN example to work with default dtype

- chainer/link_hook.py
This PR updates the example of `chainer.LinkHook` docstring.
> Override `forward` in `LinkHook` documentation

- chainerx_cc/chainerx/routines/connection.cc
This PR fixes a weird dimension check in chainerx/routines/connection where chainerx::Linear evaluates `w.ndim()` twice and the first evaluation does not make sense.
> Fix dimension check of `chainerx::Linear`

- chainer/link_hook.py
> [backport] Override `forward` in `LinkHook` documentation

- tests/chainermn_tests/functions_tests/test_collective_communication.py
Before the PR, some tests use grads of outputs.
> Check grads of inputs to test backward of collective communication

- chainerx_cc/chainerx/routines/creation.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
Reference #6604 
After this PR, the return type of  `chainerx.linspace` will be the default float which is similar to what numpy does.
> Fix linspace

- chainer/functions/array/resize_images.py
- tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
The speed of `resize_images` improved about 1.5-3x on GPU and 0.5-3x on CPU depending on data (explained later.)
For GPU, I wrote custom kernel. Performance gain is consistent in any benchmark.
For CPU,
* Images are processed by each panel that consists of image rows. The size of a panel is chosen to fit in CPU cache. This optimization is especially useful when running multiple processes in parallel.
* Temporal objects and computations in the loop are minimized, so as to exploit the above cache memory optimization as much as possible.
*  `numpy.einsum` is used to for interpolation. Benchmark founds it is fast.
* `numpy.bincount` is used in backward, instead of `numpy.add.at`.
On CPU, I optimized to the data with small batch/channel size and multi processes. This is because
* Some users …
> Improve `F.resize_images` speed

- chainer/functions/normalization/batch_normalization.py
Backport of #6323 and #6497.
Merge cupy/cupy#2094 first.
> [backport] Fix fp16 issue in batch normalization + Keep backward compatibility on cupy.cudnn.batch_normalization_forward_training

- tests/chainerx_tests/op_utils.py
I replicated the logic in `chainer/testing/_bundle.py`.
This fixes the warning messages in #6599, which are invalid, I think.
> Make `op_test` decorator remove the previous class

- chainer/testing/function_link.py
The `dict` class attribute could be mutated by derived classes causing unexpected check parameters (tolerances and epsilon) to be used in tests.
> Avoid mutating `FunctionTestBase` class attributes

- examples/memnn/memnn.py
This PR fixes the memnn example to use `F.matmul` rather than `F.batch_matmul`, which is deprecated now. With `F.matmul`, the memnn example can work in FP16 mode.
> Use `F.matmul` instead of `F.batch_matmul` in memnn example

- chainer/testing/function_link.py
> Avoid mutating `LinkTestCase` and `LinkInitializersTestCase` class attributes

- chainer/functions/activation/clipped_relu.py
With reference to #6622 , ChainerX version of Clipped ReLU forward is implemented using 'chainerx.minimum' implemented with respect to #6477
> Implemented ChainerX version of Clipped ReLU forward

- tests/chainermn_tests/communicator_tests/test_communicator.py
This PR fixes NCCL_UNHANDLED_CUDA_ERROR during CI. 
The recently-added mixed16 tests creates PureNcclCommunicator repeatedly in very short intervals. This may cause unhandled cuda error from NCCL library.
> Destroy NCCL communicator after every use 

- chainerx.md
Part of https://github.com/chainer/chainer/issues/6629.
The ChainerX product backlog is now made public.
> Include a link to ChainerX product backlog

- chainerx_build_helper.py
Required in #6646 
Set `CHAINERX_BUILD_TYPE=Debug` when installing Chainer to build ChainerX in debug mode.
Possible values: `Debug` or `Release` (default)
>  Environment variable to set ChainerX Python binding build type 

- chainermn/communicators/__init__.py
- chainermn/communicators/hierarchical_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- chainermn/communicators/single_node_communicator.py
- chainermn/communicators/two_dimensional_communicator.py
- docs/source/chainermn/installation/guide.rst
- docs/source/upgrade.rst
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/extensions_tests/test_allreduce_persistent.py
- tests/chainermn_tests/functions_tests/test_collective_communication.py
- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
- tests/chainermn_tests/links_tests/test_multi_node_chain_list.py
- tests/chainermn_tests/links_tests/test_n_step_rnn.py
- tests/chainermn_tests/optimizer_tests/test_multi_node_optimizer.py
From https://github.com/chainer/chainer/pull/6482#issuecomment-472272599 :
* We'll deprecate NCCL 2.2 and older version at Chainer v6
* We'll drop NCCL 2.2 support at Chainer v7
* We'll change Chainer(MN) according to deprecation schedule above.
I concluded we don't have to change any of cupy code and range of supported NCCL versions. Thoughts?
> Deprecate old NCCL versions and related communicators

- chainer/testing/parameterized.py
`{dtype=<class 'numpy.float32'>}` in a class name looks unnecessarily verbose.
- This PR changes it to `{dtype=float32}`.
- Modules (e.g. `<module 'numpy' from 'path/to/numpy/__init__.py'>`) are left, because `inject_backend_tests` is used.
> Generate shorter class names for parameterized tests

- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
It seems `attr.multi_gpu` does not work after `@testing.parameterize` is applied.
Code to reproduce the issue:
`CHAINER_TEST_GPU_LIMIT=1 pytest tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py`
> Fix testing condition of `BatchNormalizationMultiGpuTest`

- examples/pix2pix/updater.py
`x_in.unchain_backward()` seems unnecessary because `x_in` is a root in the computation graph.
> Remove unnecessary `unchain_backward()` in seq2seq example

- chainermn/communicators/mpi_communicator_base.py
This commit solves the Issue #6637. It removes the deprecated usage
of abc from `collections`, which will be removed in Python3.8.
The abc is now imported as `from chainer.utils import collections_abc`,
which aligns with `chainer` code base.
For more details of deprecated usage of abc in collections, please refer
to issue #6637.
> Change the deprecated `collections`

- chainerx_cc/chainerx/array_body.cc
- chainerx_cc/chainerx/array_body.h
- chainerx_cc/chainerx/backward.cc
- chainerx_cc/chainerx/backward_context.cc
- chainerx_cc/chainerx/check_backward.cc
> Allow `ArrayBody::GetArrayNode` to return null

- chainer/backend.py
- docs/source/reference/util/cuda.rst
> Fix `chainer.backend.get_array_module` documentation

- .travis.yml
I would like to redefine the purpose of Travis CI to quick automatic checks for all contributors. In this regard, recent situations of Travis CI's long job queue is not desirable. This change reduces the number of jobs running on Travis CI by reducing the jobs following the redefined purpose.
- Checks that are covered by Jenkins will only run for PRs (master/stable branches are removed).
- Windows tests are removed (we will use our new CI infrastructure for them).
- Only one combination of Ubuntu/py environment is used for each PR (namely Ubuntu16.04 py35).
- macOS py27 test will run for each PR instead of macOS py35 (for wider py versions coverage combined with Ubuntu test).
> Minimize the Travis CI matrix

- examples/memnn/memnn.py
> [backport] Use `F.matmul` instead of `F.batch_matmul` in memnn example

- chainer/functions/evaluation/classification_summary.py
Address issue https://github.com/chainer/chainer/issues/6514 by fixing the typo in the definition for recall in the docstring. Also add definition for "fn" as false negatives".
> Fixes typo in docstring for classification_summary

- chainer/functions/__init__.py
- chainer/functions/normalization/decorrelated_batch_normalization.py
- chainer/links/__init__.py
- chainer/links/normalization/decorrelated_batch_normalization.py
- docs/source/reference/functions.rst
- docs/source/reference/links.rst
- tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
- tests/chainer_tests/functions_tests/util_tests/test_forget.py
- tests/chainer_tests/links_tests/normalization_tests/test_decorrelated_batch_normalization.py
take over #4686 
Both `F.decorrelated_batch_normalization` and `F.fixed_decorrelated_batch_normalization` do no support double backward. (rel: #4449)
> add decorrelated batchnormalization (take-over)

- chainer/functions/normalization/batch_normalization.py
`F.batch_normalization` always allocates and updates dummy mean and var if they aren't given by the caller. Those dummies are only required when calling cuDNN so I changed the logic to condition these allocations/updates.
> BatchNormalization to only allocate dummy mean and var in cuDNN path

- docs/source/reference/util/cuda.rst
> [backport] Fix `chainer.backend.get_array_module` documentation

- chainermn/communicators/pure_nccl_communicator.py
- chainermn/functions/batch_normalization.py
- chainermn/links/batch_normalization.py
- chainermn/nccl.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/links_tests/test_batch_normalization.py
This PR adds support for fp16 and mixed16 in `MultiNodeBatchNormalization` of ChainerMN.
Solved https://github.com/chainer/chainer/issues/6198 and https://github.com/chainer/chainer/issues/6457
Related to https://github.com/chainer/chainer/pull/6331
> Support for fp16 and mixed16 in `MultiNodeBatchNormalization` of ChainerMN

- chainer/optimizer.py
This PR fixes optimizer fallback from ChainerX with non-default devices. The issue was that the current device was never set when falling back meaning that running MNIST with a non-default device e.g. `--device='cuda:2'` lead to an array-current-device mismatch error.
> Fix ChainerX optimzer fallback for non-default devices

- tests/chainer_tests/functions_tests/array_tests/test_expand_dims.py
Simplifies `test_expand_dims` using testing.FunctionTestCase
> Simplify `F.expand_dims` test

- chainer/distributions/__init__.py
- chainer/distributions/bernoulli.py
- chainer/distributions/beta.py
- chainer/distributions/categorical.py
- chainer/distributions/cauchy.py
- chainer/distributions/chisquare.py
- chainer/distributions/dirichlet.py
- chainer/distributions/exponential.py
- chainer/distributions/gamma.py
- chainer/distributions/geometric.py
- chainer/distributions/gumbel.py
- chainer/distributions/independent.py
- chainer/distributions/laplace.py
- chainer/distributions/log_normal.py
- chainer/distributions/multivariate_normal.py
- chainer/distributions/one_hot_categorical.py
- chainer/distributions/pareto.py
- chainer/distributions/poisson.py
- chainer/distributions/uniform.py
- docs/source/reference/distributions.rst
- examples/vae/net.py
- tests/chainer_tests/distributions_tests/test_independent.py
Typical DL frameworks which handle probabilistic distributions such as Tensorflow Probability and PyTorch Distributions have `Independent` distribution class. I implemented the same interface in Chainer.
`Independent` distribution reinterprets some of the batch dims of distribution as event dims. This is mainly useful for changing the shape of the result of `distribution.log_prob(x)`, and it makes code clearer and simpler. For example, the current official example of the VAE's objective function is like
```python
...
q_z = D.Normal(loc=mu(x), log_scale=ln_sigma(x))
z = q_z.sample(k)
p_x = D.Bernoulli(logit=h(z))
p_z = D.Normal(zeros_array, ones_array)
reconstr = F.mean(F.sum(p_x.log_prob(
F.broadcast_to(x[None, :], (k,) + x.shape)), axis=-1))
kl_penalty = …
```
> Add `distributions.Independent`

- chainer/functions/evaluation/classification_summary.py
> [backport] Fixes typo in docstring for classification_summary

- examples/memnn/download.py
(Fancy)URLopener is deprecated since Python 3.3.
https://docs.python.org/3/library/urllib.request.html#urllib.request.FancyURLopener
> Replace deprecated URLopener in `download.py`

- examples/text_classification/text_datasets.py
> [backport] Fix text_classification example fails on Python 3 (#5590)

- tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
Simplifies `test_resize_image` using `testing.FunctionTestCase`
> Simplify  `F.resize_image` test.

- docs/source/guides/functions.rst
- docs/source/imports.rst
I started to write docs on how to implement user-defined new-style functions.
I'd like to discuss two points:
Currently I'm planning to describe this way:
> In the following sections, we first introduce steps to implenent an old-style function. After that we describe the difference of implementation between old-style functions and new-style functions.
Or, should we completely rewrite the guide to use new-style functions?
I think old-style functions are still convenient for many people, as the implementation cost is less than new-style, so I'd like to proceed with the current style.
I think the name "old-style" make users feel "it is not recommended to use".
How about giving less-aggressive name, like "classic-style" or "conventional"?
> Write guides to implement new-style functions

- chainer/device_resident.py
- tests/chainer_tests/test_link.py
In `DeviceResident.to_gpu`, `chainer.backend.GpuDevice`, which is incompatible with `to_gpu`, was incorrectly captured for backward-compatibility call to overridden `to_gpu`.
> Fix `DeviceResident.to_gpu` fallback argument

- docs/source/upgrade.rst
Partially fixes https://github.com/chainer/chainer/issues/6131.
> Append to v6 upgrade guide about Python 3.4 support drop

- examples/dcgan/train_dcgan.py
- examples/image_captioning/train.py
- examples/mnist/train_mnist.py
- examples/mnist/train_mnist_custom_loop.py
- examples/pix2pix/train_facade.py
- examples/ptb/train_ptb.py
- examples/ptb/train_ptb_custom_loop.py
- examples/sentiment/train_sentiment.py
- examples/seq2seq/seq2seq.py
- examples/text_classification/train_text_classifier.py
- examples/vae/train_vae.py
- examples/word2vec/search.py
- examples/word2vec/train_word2vec.py
This PR partially accesses #6398 and related to #3500 and #6378.
- Avoid comparisons with empty string by setting `args.resume` as `None` by default.
- Extend `Trainer` instance with `extensions.snapshot`
- [custom loop] Fix ignorance of `args.resume` and add messages to be more user-friendly.
> Improve chainer examples

- chainermn/communicators/mpi_communicator_base.py
- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
This PR add FP16 to send/recv function pair in ChainerMN for mpi.
> Add FP16 support to send/recv

- scripts/ci/travis/steps.sh
The PR fixes Travis fails to install python (2.7.10 and 3.5.1) using pyenv.  I reproduced the same error on my MacBook by
```
brew install openssl@1.1
pyenv install 2.7.10  # fail
brew uninstall openssl@1.1
pyenv install 2.7.10  # pass
```
Updating `openssl@1.1` did not fix the problem.
The update of pyenv, which includes pyenv/pyenv#1302, probably caused the error, while I've not figured out why openssl 1.1 makes the installation fail.
> Fix Travis with macOS

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
`chainerx.max` has nondifferentiable points and CI is failing.
> Dodge nondifferentiable inputs in `chainerx.max` test

- docs/source/upgrade.rst
> [backport] Append to v6 upgrade guide about Python 3.4 support drop

- chainer/training/extensions/evaluator.py
`Evaluator` was not aware of `chainer.dataset.converter` (#5832).
> Fix `Evaluator` for `chainer.dataset.converter`

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/copy.cu
- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/cuda_device/fill.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/im2col.cc
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/copy.cc
- chainerx_cc/chainerx/native/native_device/dot.cc
- chainerx_cc/chainerx/native/native_device/fill.cc
- chainerx_cc/chainerx/routines/creation.cc
- chainerx_cc/chainerx/routines/creation.h
- chainerx_cc/chainerx/routines/manipulation.cc
Part of #6692.
Note that `Device::AsType` and `Device::Fill` are not covered in this PR. Although similar to other device methods covered in this PR, these methods do not have corresponding routines and are instead exposed as `Array` methods `Array::AsType`, `Array::Fill`.
> Op registration: creation

- chainerx/_fallback_workarounds.py
- tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
Simplified F.mean_absolute_error test using testing.FunctionTestCase.
Ref. #6071
> Simplify `F.mean_absolute_error` test

- chainerx_cc/chainerx/cuda/float16.cuh
- tests/chainerx_tests/unit_tests/test_array.py
> Fix `chainerx.astype` casting from `float16` to `bool` in CUDA

- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/cuda/cudnn.cc
- chainerx_cc/chainerx/cuda/cudnn.h
I feel `CudnnBNTensorDescriptor` was a bit obscure.
This PR makes it apparent that it's a "derived tensor descriptor".
> Refactor CUDA batch norm tensor descriptor

- chainerx_cc/chainerx/cuda/float16.cuh
- tests/chainerx_tests/unit_tests/test_array.py
> [backport] Fix `chainerx.astype` casting from `float16` to `bool` in CUDA

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Dodge nondifferentiable inputs in `chainerx.max` test

- chainer/link.py
The `initializer` argument of the functions accept a scalar value, but it is not explicitly documented in some places. This patch fixes these docstrings.
> Fix to clarify the description about initializer argument

- tests/chainer_tests/initializer_tests/test_normal.py
- tests/chainer_tests/initializer_tests/test_orthogonal.py
- tests/chainer_tests/initializer_tests/test_uniform.py
The tests `test_initializer_statistics_slow_*` might be too slow.  This PR reduces the number of samples.  After the change, `pytest -m 'not gpu and slow' chainer_tests/initializer_tests` takes `83.54 seconds` for the 128 slow cpu tests on my laptop.
> Make too slow initializers' tests faster

- examples/wavenet/README.md
- examples/wavenet/generate.py
- examples/wavenet/train.py
* Make `--input` and `--model` options mandatory in `generate.py`.
* Use `python` instead of `python3` in `README.txt`.
* Check existence of dataset directory.
> Trivial fixes to Wavenet example

- chainerx/__init__.py
- chainerx/_docs/routines.py
- chainerx/math/misc.py
`chainerx.square` was implemented in C++ in https://github.com/chainer/chainer/pull/6486 in but the fallback Python implementation was hiding it. This PR removes the fallback. Verified the C++ implementation at least locally using existing tests and it seemed fine.
> Remove `chainerx.square` fallback since it is implemented in C++

- examples/word2vec/train_word2vec.py
> [backport] Support ChainerX in word2vec example 

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py
This PR adds [AdaBound (ICLR2019)](https://openreview.net/forum?id=Bkg3g2R9FX).
This PR is the same as #6367, but the learning progress is confirmed in the local environment.
Note: The parameter `final_lr_rate` is different formation from original paper for exclusion of redundant calculation,
`final_lr_rate = alpha_star / alpha`.
> Add AdaBound (and AMSBound)

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/activation.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/activation.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Implement array vs array functionality to `chainerx.minimum`

- chainer/device_resident.py
- tests/chainer_tests/test_link.py
> [backport] Fix stack overflow caused when `to_gpu`/`to_cpu`/`to_intel64` were overridden

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/routines/normalization.cc
- chainerx_cc/chainerx/routines/normalization.h
If a user wants to call a device op without going through the routines, the concrete state classes for each backend must be public. This PR addresses this issue for BN.
_See also https://github.com/chainer/chainer/pull/6800#issuecomment-482001492_
> Make `BatchNorm` states public

- chainerx_cc/chainerx/cuda/cuda_device.h
- chainerx_cc/chainerx/cuda/cuda_device/activation.cu
- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/cuda_device/exp_log.cu
- chainerx_cc/chainerx/cuda/cuda_device/misc.cu
- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/native/native_device.h
- chainerx_cc/chainerx/native/native_device/activation.cc
- chainerx_cc/chainerx/native/native_device/exp_log.cc
- chainerx_cc/chainerx/native/native_device/misc.cc
- chainerx_cc/chainerx/native/native_device/pool.cc
- chainerx_cc/chainerx/native/native_device/reduction.cc
- chainerx_cc/chainerx/routines/math.cc
- chainerx_cc/chainerx/routines/math.h
- chainerx_cc/chainerx/routines/statistics.cc
> Op registration: math

- chainer/link_hook.py
- chainer/link_hooks/spectral_normalization.py
- tests/chainer_tests/link_hooks_tests/test_spectral_normalization.py
This PR enables `chainer.link_hooks.SpectralNormalziation` to support ideep, chainerx, and multiple GPUs.
> Improve `link_hooks.SpectralNormalization`

- docs/source/reference/initializers.rst
A minor change to the documentation for the default initializer behavior in case of `None`. 
Initializers can be usually be "specified" as arguments in `Link.__init__` and I think this change makes it a bit clearer what it means.
> Document fix in default initializer

- .gitignore
This PR adds `*.dylib` to `.gitignore` for macOS.
```
% python -c 'import chainer; chainer.print_runtime_info()'
Platform: Darwin-18.2.0-x86_64-i386-64bit
Chainer: 6.0.0b3
NumPy: 1.17.0.dev0+e6147b9
CuPy: Not Available
iDeep: Not Available
```
> Make git ignore `chainerx/libchainerx.dylib`

- chainer/training/extensions/_snapshot.py
- tests/chainer_tests/training_tests/extensions_tests/test_snapshot.py
This commit also aligns behaviour of `snapshot_object` to `snapshot` for future potential extensions of both functions.
> Allow snapshot_object have condition and writer option

- chainerx.md
I can not access [this url](https://github.com/pfnet/chainerx/tree/master/chainerx_cc/chainerx/python).
I think this url is a private repository.
> Fix broken link in `chainerx.md`

- chainer/function_node.py
- chainer/variable.py
- tests/chainer_tests/test_function_node.py
- tests/chainer_tests/test_variable.py
This change would use Null gradients for child nodes that have been
unchained. References issue #6027. As opposed to current behavior:
```python
>>> import numpy as np; import chainer; import chainer.functions as F
>>> x = chainer.Variable(np.arange(4).astype('f').reshape(2, 2)); x
variable([[0., 1.],
[2., 3.]])
>>> h0, h1 = F.split_axis(x, [1], axis=0); h0, h1
(variable([[0., 1.]]), variable([[2., 3.]]))
>>> y = F.sum(h0)
>>> z = F.sum(h1)
>>> h0.unchain()
>>> x.grad, h0.grad, h1.grad
(None, None, None)
>>> y.backward()
>>> x.grad, h0.grad, h1.grad
(None, array([[1., 1.]], dtype=float32), None)
>>> z.backward()
>>> x.grad, h0.grad, h1.grad
(array([[1., 1.],
[1., 1.]], dtype=float32), None, None)
```
we would get this:
```python
>>> import numpy as np; import chainer; import …
```
> Fix unchain gradient pull

- .gitignore
> [backport] Make git ignore `chainerx/libchainerx.dylib`

- chainer/testing/unary_math_function_test.py
This PR fixes the occasional test failure in `test_erfc.py`.
> Relax tolerance for float16 in `unary_math_function_unittest`

- examples/vae/net.py
Rel. #6168.
This PR fixes the VAE example to support the default dtype feature.
> Support default dtype in vae example

- chainerx_cc/chainerx/cuda/cuda_device/reduction.cu
- chainerx_cc/chainerx/native/native_device/reduction.cc
The macro `CHAINERX_REGISTER_OP_{NATIVE, CUDA}` was renamed to `CHAINERX_{NATIVE, CUDA}_REGISTER_OP` in #6865 but it is not applied to #6752. This PR fixes it.
Fixes #6923.
> Rename the macro name for `AMinOp`

- chainer/testing/unary_math_function_test.py
> [backport] Relax tolerance for float16 in `unary_math_function_unittest`

- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_nd.py
> [backport] Fix `F.max_pooling_nd` test instability

- docs/source/_templates/search.html
Closes #6876.
It seems [Elasticsearch index](https://docs.readthedocs.io/en/stable/development/search.html) generated by RTD is broken.
Added workaround to use Sphinx search by default.
* before: https://kmaehashi-chainer.readthedocs.io/en/latest/search.html?q=PlotReport&check_keywords=yes&area=default
* after: https://kmaehashi-chainer.readthedocs.io/en/use-search-index/search.html?q=PlotReport&check_keywords=yes&area=default
> Use search index

- chainer/utils/type_check.py
- tests/chainer_tests/utils_tests/test_type_check.py
The following error is often occurred while using multiprocessing, then hide details of InvalidType exception.
This PR fixes this problem.
```pycon
>>> from chainer.utils.type_check import InvalidType
>>> import pickle
>>> pickle.loads(pickle.dumps(InvalidType('foo', 'bar')))
TypeError: __init__() missing 1 required positional argument: 'actual'
```
> Make `InvalidType` picklable

- tests/chainer_tests/functions_tests/loss_tests/test_triplet.py
> [backport] Relax tolerances and avoid non-differentiable points for FP16 in triplet loss tests

- chainerx_cc/chainerx/cuda/op_regist.h
- chainerx_cc/chainerx/native/op_regist.h
Aligning `CHAINERX_{NATIVE,CUDA}_REGISTER_ELTWISE_...` to `CHAINERX_{NATIVE,CUDA}_REGISTER_OP `.
> Align macro parameter name

- chainer/training/triggers/early_stopping_trigger.py
- tests/chainer_tests/training_tests/triggers_tests/test_early_stopping_trigger.py
"Patients" means something different.
The original argument is kept without deprecating it, because it will not cause any problem.
It could be deprecated of course.
> Rename `patients` argument to `patience` in `EarlyStoppingTrigger`

- examples/cifar/README.md
- examples/cifar/train_cifar.py
- examples/cifar/train_cifar_custom_loop.py
> Support ChainerX in CIFAR example

- chainer/_backprop_utils.py
`_get_columns` returned `str` if `COLUMNS` is set in Python 2.
Found in a test failure in #6948.
> Fix terminal column width retrieval in backprop traceback in Python 2

- chainer/_backprop_utils.py
> [backport] Fix terminal column width retrieval in backprop traceback in Python 2

- scripts/ci/travis/run-tests.sh
In Travis CI, pytest renders the progress of the tests in 80 columns.
This requires quite a bit of scroll to reach the end of outputs.
Merge #6949 first.
> Increase the default columns in Travis CI

- tests/chainer_tests/functions_tests/math_tests/test_exponential_m1.py
Simplifies test_exponential_m1 using testing.FunctionTestCase
> Simplify `F.expm1` test

- chainer/testing/function_link.py
Document the following attributes:
* `test_name`
* `backend_config`
> Document passive attributes in `FunctionTestCase`

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Part of #6912.
Currently, the pre-mapped array is casted to a float16 array before reduction. This loss of trailing digits seems avoidable by supporting reduction kernel for `LogSumExp` for each device.
> Fix flaky `TestLogSumExp`

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Part of #6912.
`chainerx.min` has non-differential points.
> Fix flaky `TestMin`

- chainerx_cc/chainerx/cuda/cudnn.cc
- chainerx_cc/chainerx/cuda/cudnn.h
cuDNN descriptor move semantics were implicitly defined and could lead to double free/destroy. This issue was present in `DeriveBatchNormTensorDescriptor` but was hidden because of NRVO. 
This PR fixes those issues by simply disallowing move and copy, except for the ones currently required. We can allow more as needed and this is explained in the TODOs.
> Fix cuDNN descriptor double destroy

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Fix flaky `TestLogSumExp`

- chainer/functions/activation/relu.py
- tests/chainer_tests/functions_tests/activation_tests/test_relu.py
`cudnnActivationBackward` requests input layer data. Current ReLU implementation uses CuPy one.
But, In ReLU case we can pass output layer data as input layer data.
- Speed up with FP16. cuDNN method is faster than CuPy.
- Reduce memory consumption with cuDNN mode.
> Use cuDNN in ReLU

- tests/chainerx_tests/unit_tests/routines_tests/test_pooling.py
> [backport] Fix flaky ChainerX `max_pool` test

- chainer/dataset/convert.py
- tests/chainer_tests/dataset_tests/test_convert.py
The PR fixes #6838.
Note: `ConcatWithAsyncTransfer` does not support the new device specifiers, but I left it.
> Fix `ConcatWithAsyncTransfer`

- tests/chainer_tests/serializers_tests/test_npz.py
> [backport] Quickfix: skip tests that fail with NumPy 1.16.3

- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/manipulation.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
A sub-view of a zero-sized array (e.g. a sub-view of shape `(2, 0)` of an array one that has a shape of `(7. 0)`) should always have an offset of 0. Having a non-zero offset would yield an invalid address when for instance creating a new array based on it.
In short, this fix was missing for ChainerX.
https://github.com/cupy/cupy/blob/master/cupy/core/_routines_indexing.pyx#L322-L323
~_TODO: Need to add tests._~ Done.
> Fix subview of zero-sized arrays

- tests/chainer_tests/functions_tests/math_tests/test_minmax.py
Simplifies test_minmax using testing.FunctionTestCase
> Simplify 'F.min', 'F.max' test

- tests/chainer_tests/functions_tests/math_tests/test_exponential.py
Simplifies test_exponential using testing.FunctionTestCase
> Simplify 'F.exp', 'F.log' test

- chainerx_cc/chainerx/routines/indexing.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
Fixed offset calculation for `At`. The current implementation is similar to getitem of CuPy https://github.com/cupy/cupy/blob/master/cupy/core/_routines_indexing.pyx#L267.
> Fix `At` output offset

- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_npz.py
This PR fixes the issues with NumPy 1.16.3.
- #4530 is postponed.
- ChainerCV: chainer/chainercv#853
> Set `allow_pickle=True` 

- tests/chainer_tests/functions_tests/math_tests/test_linear_interpolate.py
Simplifies test_linear_interpolate using testing.FunctionTestCase
> Simplify `F.linear_interpolate` test

- tests/chainer_tests/functions_tests/math_tests/test_batch_l2_norm_squared.py
Simplifies test_batch_l2_norm_squared using testing.FunctionTestCase
> Simplify `F.batch_l2_norm_squared` test

- examples/reinforcement_learning/ddpg_pendulum.py
- examples/reinforcement_learning/dqn_cartpole.py
Rel #6168.
This PR fixes the reinforcement learning example to work with the default dtype feature.
> Fix reinforcement_learning example to work with default dtype

- chainer/testing/function_link.py
- chainerx/_fallback_workarounds.py
- tests/chainer_tests/functions_tests/math_tests/test_sign.py
Simplifies test_sign using testing.FunctionTestCase
> Simplify `F.sign` test

- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/routines/manipulation.cc
When converting a ChainerX array into a CuPy array, the base pointer was incremented by the offset. This PR changes the behavior such that the base pointer is kept and the offset is specified via the "offset" parameter.
> Fix handling of ndarray offsets

- chainerx_cc/chainerx/routines/manipulation.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Fixes https://github.com/chainer/chainer/issues/7050.
Also, simplified the backward of `Stack` to use `Split` and removed `StackGrad`.
> Support mixed dtypes in `Stack`

- chainerx_cc/chainerx/native/reduce.h
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
This fixes #7038.
```python
import chainerx as chx
import cupy as cp
def _unstable_sum(xp, **kwargs):
a = xp.zeros((2, 512*512), **kwargs)
a[0, :] = 1.0
a[1, :] = 0.1
return a.sum()
print(_unstable_sum(np, dtype=np.float32))                      # 288358.0
print(_unstable_sum(cp, dtype=cp.float32))                      # 288352.0
print(_unstable_sum(chx, dtype=chx.float32, device='cuda:0'))    # 288352.0
print(_unstable_sum(chx, dtype=chx.float32, device='native:0'))  # old 286720.0 new 288358.40625
```
I confirmed the correctness of the routine up to 1023.
```python
import chainerx as chx
for i in range(1024):
a = chx.arange(i, device='native:0') + 1
print(i, i * (i + 1) // 2, a.sum())
```
I'll remove WIP sign after test codes are added.
> implement NumPy-like pairwise reduction for stability

- setup.py
Currently CI is broken in master.
It turned out that cause is protobuf==3.8.0rc1 being used in CIs.
In some CIs we install Chainer with `python setup.py install`, which causes pre-release dependencies to be installed (pypa/setuptools/issues/855).
This PR is a temporary workaround.
We should probably always use pip for installing chainer.
> Exclude protobuf 3.8.0rc1 from dependencies

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Fix #6912.
Fixed to avoid non-differentiable inputs.
> Fix flaky `chainerx.abs` test

- scripts/ci/travis/steps.sh
Many times tests fail spuriously in CI.
Due to the dense error trace and warnings displayed by
pytest, it is hard to figure out the failed test cases.
One can suppress the information displayed with flags but
this becomes a problem when actual test fails.
This PR is a hack to display failed tests at the end without
suppressing the log and errors from pytest.
But I hope it will save some trouble of sailing through those
stack traces and warnings just to find out that those were irrelevant.
References : 
* https://stackoverflow.com/a/49450167/5602957
* https://stackoverflow.com/questions/24617397/how-to-print-to-console-in-py-test/38806934#38806934
* https://github.com/pytest-dev/pytest/issues/3952
Example:
> Display `pytest` summary

- chainerx_cc/chainerx/cuda/cuda_device/exp_log.cu
- chainerx_cc/chainerx/native/native_device/exp_log.cc
Simplify device implementation of `Exp`, `Log` and `Log10`.
> Use macro in exp_log.{cc/cu}

- appveyor.yml
- scripts/ci/steps.sh
Follow-up of https://github.com/chainer/chainer/pull/6625, adding the same options to other `pytest` executions.
> Display `pytest` summary (cont.)

- setup.py
> [backport] Exclude protobuf 3.8.0rc1 from dependencies

- chainerx_cc/chainerx/routines/manipulation.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Copies were made by `chainerx::Reshape` where views would suffice, due to an unnecessarily strict check. This PR fixes that check.
A side note. `chainerx::ExpandDims` simply calls `chainexr::Reshape` to add an axis. This should in practice not incur a copy. However, it could in certain cases. The following assertion would e.g. fail. This is fixed and tested in this PR.
```python
import chainerx as chx
a = chx.random.uniform(-1, 1, (2, 1, 3)).T
b = a.reshape(1, 3, 1, 2)  # Just an "expand dims".
assert a.data_ptr == b.data_ptr  # Would fail, meaning a copy was created.
```
> Fix `Reshape` copy condition

- docs/source/chainermn/installation/guide.rst
This PR updates the document for latest information about supported versions of MPI.
This PR fixes #5740 .
Memo:
To review the document locally,  do
```
$ cd docs
$ make html
```
> Update supported MPI list

- chainer/training/triggers/interval_trigger.py
- chainer/training/triggers/manual_schedule_trigger.py
- tests/chainer_tests/training_tests/triggers_tests/test_interval_trigger.py
- tests/chainer_tests/training_tests/triggers_tests/test_manual_schedule_trigger.py
Some triggers with public interfaces used to assert on the user-given inputs. This PR changes those assertions to checks that raise errors.
> Fix trigger constructors to raise errors instead of assertion failures

- chainerx_cc/chainerx/python/chainer_interop.cc
Instead of creating a `std::shared_ptr` with a custom deleter, an unintended constructor of `py::object` was called (argument were implicitly converted) without any custom deleters being set. This PR fixes this bug.
> Fix construction of `std::shared_ptr` with custom deleter in `chianer_interop.cc`

- chainerx_cc/chainerx/routines/manipulation.cc
https://github.com/chainer/chainer/pull/7065/files#diff-1a0097987b5e6a8fe06006b09904a09fR767 caused the error:
```
/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-ntqn56g1/chainerx_cc/chainerx/routines/manipulation.cc:667:19: error: no matching function for call to 'max'
offset += std::max(shape[axis] - 1, 0L) * strides[axis];
^~~~~~~~
/Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:2717:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long long' vs. 'long')
max(const _Tp& __a, const _Tp& __b)
^
/Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:2727:1: note: candidate template ignored: could not match …
```
> Fix build with clang

- docs/source/chainerx/install/index.rst
> [backport] Document `CHAINERX_ENABLE_BLAS` environment variable

- chainer/functions/pooling/unpooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_unpooling_2d.py
I added a code path for faster unpooling when the output shape is an integer multiple of the input shape. This happens e.g. when upsampling the previous result of 2x2 max pooling, which is a common use case. This PR speeds up the forward pass about 1.7-3.2 times for this case.
MWE:
With batch and channel size 1, this PR makes the unpooling 1.7 times faster:
```
In [1]: import numpy as np; import cupy; import chainer.functions as F; x = cupy.arange(1, 128*64+1).reshape((1, 1, 64, 128)).astype(np.float32)
In [2]: %timeit F.unpooling_2d(x, 2, outsize=(x.shape[2]*2, x.shape[3]*2))
178 µs ± 18.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [3]: %timeit F.unpooling_2d(x, 2, outsize=(x.shape[2]*2, x.shape[3]*2))
99.2 µs ± 93.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops …
```
> Fast integer scale unpooling

- .mergify.yml
* Disable strict mode (it does not get along with manually-triggered CIs)
* Do not require approval (it takes some steps to approve a PR. `st:test-and-merge` works as an alternative).
> Improve mergify configuration

- tests/chainer_tests/initializer_tests/test_normal.py
- tests/chainer_tests/initializer_tests/test_orthogonal.py
- tests/chainer_tests/initializer_tests/test_uniform.py
> [backport] Make too slow initializers' tests faster

- tests/chainer_tests/functions_tests/math_tests/test_logarithm_1p.py
Simplifies test_logarithm_1p using testing.FunctionTestCase
> Simplify `F.log1p` test

- docs/source/performance.rst
Fix link to point the latest ChainerMN documentation as it has been merged to Chainer.
> Fix link to ChainerMN docs in performance guide

- examples/sentiment/train_recursive_minibatch.py
- examples/sentiment/train_sentiment.py
Added progress bar for user-friendliness. Other examples also use this progress bar (setting).
Also, please see https://github.com/chainer/chainer/pull/7087#discussion_r282409705.
> Add progress bar to sentiment analysis example

- tests/chainer_tests/functions_tests/normalization_tests/test_local_response_normalization.py
Simplifies `test_local_response_normalization`
using `testing.FunctionTestCase`
> Simplify `F.local_response_normalization` test

- chainer/testing/function_link.py
> [backport] Document passive attributes in `FunctionTestCase`

- chainer/functions/array/copy.py
- tests/chainer_tests/functions_tests/array_tests/test_copy.py
ChainerX support in `F.copy`.
(Required in #6857, separated from #6859)
~TODO: test~
> Support ChainerX in `F.copy`

- docs/source/performance.rst
> [backport] Fix link to ChainerMN docs in performance guide

- chainerx_cc/chainerx/cuda/numeric.cuh
Fixes a warning, `warning: pointless comparison of unsigned integer with zero`. This warning is by the way only raised for the `.cuh`.
> Fix pointless comparison warning

- examples/mnist/inference.py
Part of #6661.
Note that the model must be transferred (in the case the destination device is a ChainerX device) after loading the data from the npz since `Link.serialize` does not yet support ChainerX. I'll address that in a separate issue/PR.
> Support ChainerX in MNIST inference example

- chainer/functions/activation/lstm.py
- chainer/functions/activation/slstm.py
- chainer/functions/activation/tree_lstm.py
- chainer/functions/array/spatial_transformer_grid.py
- chainer/functions/array/spatial_transformer_sampler.py
- chainer/functions/connection/deformable_convolution_2d_sampler.py
- chainer/functions/connection/depthwise_convolution_2d.py
- chainer/functions/connection/shift.py
- chainer/functions/loss/black_out.py
- chainer/functions/loss/ctc.py
- chainer/functions/loss/negative_sampling.py
- chainer/functions/loss/triplet.py
- chainer/functions/noise/dropout.py
- chainer/functions/noise/gumbel_softmax.py
- chainer/functions/noise/zoneout.py
- chainer/functions/normalization/batch_normalization.py
- chainer/functions/normalization/batch_renormalization.py
- chainer/functions/normalization/local_response_normalization.py
- chainer/functions/pooling/spatial_pyramid_pooling_2d.py
- chainer/links/activation/prelu.py
- chainer/links/activation/swish.py
- chainer/links/connection/inceptionbn.py
- chainer/links/connection/tree_lstm.py
- chainer/links/normalization/batch_normalization.py
- chainer/links/normalization/batch_renormalization.py
- chainer/optimizer_hooks/gradient_lars.py
- chainer/optimizer_hooks/gradient_noise.py
- chainer/optimizers/adam.py
- chainer/optimizers/corrected_momentum_sgd.py
- chainer/optimizers/msvag.py
Follow the example in ReST reference:
```
External hyperlinks, like `Python
<http://www.python.org/>`_.
```
http://docutils.sourceforge.net/docs/user/rst/quickref.html#external-hyperlink-targets
> Remove backslashes to continue lines of link targets

- docs/source/chainermn/reference/index.rst
I found that the method exists but the doc is missing.
> Add missing doc entry for `CommunicatorBase.allgather`

- chainer/functions/normalization/batch_renormalization.py
Each commit fixes a minor error.  The biggest change is to exclude `eps` from `running_var`.
> Avoid unnecessary updates in `F.batch_renormalization`, and related fixes

- chainermn/communicators/mpi_communicator_base.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This PR aims to support Tagged communication of send_obj and recv_obj on `MpiCommunicatorBase`.
MPI_Status support is also included.
Please check https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/MPI/Comm.pyx#L1168 .
Default behavior of mpi4py's recv without tag is interpreted as `ANY_TAG`, therefore I followed it.
> Support Tagged communication with MPI_Status.

- chainerx_cc/chainerx/cuda/cuda_conv.cc
- chainerx_cc/chainerx/cuda/cuda_conv.h
This PR aims to fix the issue below.
* "CUDNN_STATUS_BAD_PARAM" occurs when ChainerX and float16 are used in the imagenet example due to improper setting of cudnn convolution math type.
> Fix float16 and TensorCore related issue in ChainerX

- chainerx_cc/chainerx/routines/logic.cc
> Remove duplicated code in logic.cc

- docs/source/chainermn/reference/index.rst
> [backport] Add missing doc entry for `CommunicatorBase.allgather`

- chainer/variable.py
> [backport] Fix typo in `Variable.backward`

- chainer/training/updaters/parallel_updater.py
- examples/mnist/train_mnist_data_parallel.py
~Part of #6661~
~TODO: Needs `Variable.addgrad` support for ChainerX~
Some more internal fixes are needed to support ChainerX.
> Support device specifiers in MNIST data parallel example

- chainer/backend.py
- chainer/function.py
- chainer/function_node.py
- chainer/functions/normalization/group_normalization.py
- chainer/gradient_check.py
- chainer/initializers/__init__.py
- chainer/optimizer_hooks/gradient_clipping.py
- chainer/optimizer_hooks/gradient_hard_clipping.py
- chainer/optimizer_hooks/gradient_lars.py
- chainer/optimizer_hooks/gradient_noise.py
- chainer/optimizer_hooks/lasso.py
- chainer/optimizer_hooks/weight_decay.py
- chainer/optimizers/ada_delta.py
- chainer/optimizers/ada_grad.py
- chainer/optimizers/adam.py
- chainer/optimizers/corrected_momentum_sgd.py
- chainer/optimizers/momentum_sgd.py
- chainer/optimizers/msvag.py
- chainer/optimizers/nesterov_ag.py
- chainer/optimizers/rmsprop.py
- chainer/optimizers/rmsprop_graves.py
- chainer/optimizers/smorms3.py
- chainer/reporter.py
- chainer/variable.py
- tests/chainer_tests/links_tests/connection_tests/test_lstm.py
- tests/chainer_tests/links_tests/connection_tests/test_peephole.py
- tests/chainer_tests/links_tests/connection_tests/test_tree_lstm.py
- tests/chainer_tests/links_tests/connection_tests/test_zoneoutlstm.py
- tests/chainer_tests/test_variable.py
Now that Chainer has its own device abstraction, we should avoid using `DummyDevice` outside `backends.cuda` module.
Also replaces `cuda.get_device_from_array` with `backend.get_device_from_array`.
Some uses are left for respective reasons. (cupy-specific code, being handled in another PR (#6982), etc.)
> Avoid using `cuda.DummyDevice` and `cuda.get_device_from_array`

- examples/static_graph_optimizations/cifar/train_cifar.py
- examples/static_graph_optimizations/cifar/train_cifar_custom_loop.py
- examples/static_graph_optimizations/mnist/train_mnist.py
- examples/static_graph_optimizations/mnist/train_mnist_custom_loop.py
- examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py
Part of #6661.
All of the sub-examples of the static graph optimization example, specifying a ChainerX device fail and need separate fixes. For instance, this error is raised. https://github.com/chainer/chainer/blob/master/chainer/graph_optimizations/static_graph.py#L738
> Support device specifiers in static graph example 

- docs/source/glance.rst
- examples/glance/glance.py
This example already requires `matplotlib`, so this check has no effect.
More importantly, it is nonessential for learning Chainer at a glance.
> Remove `PlotReport.available()` check in glance example

- tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
Merge #7189 first.
This PR adds a TensorCore test in `TestConv` which reproduces the error mentioned in #7189.
> Add Tensor Core test for `chainerx.conv` and `chainerx.conv_transpose`

- chainer/backends/_chainerx.py
- chainer/device_resident.py
- chainer/training/updaters/standard_updater.py
- chainer/variable.py
- examples/imagenet/train_imagenet.py
Should be slightly faster, easier to read. 
Note that `CpuDevice` and `Intel64Device` cannot be distinguished so those occurrences are left unchanged..
> Check device instance using `xp` when possible

- chainer/training/updaters/multiprocess_parallel_updater.py
- tests/chainer_tests/training_tests/updaters_tests/snippets/child_reporter.py
- tests/chainer_tests/training_tests/updaters_tests/snippets/cuda_init.py
- tests/chainer_tests/training_tests/updaters_tests/snippets/raw_array.py
- tests/chainer_tests/training_tests/updaters_tests/test_multiprocess_parallel_updater.py
Support new chainer devices with `MultiProcessParallelUpdater`.
Required for https://github.com/chainer/chainer/pull/7164.
> `MultiprocessParallelUpdater` to support new devices

- chainer/_backend.py
- chainer/backends/_chainerx.py
- chainer/backends/cuda.py
- List concrete devices in `chainer.backend.Device` docstring.
- Document
* `ChainerxDevice.fallback_device`
* `ChainerxDevice.from_fallback_device`
* `GpuDevice.from_device_id`
> Improve device documentation

- scripts/ci/chainerx/jenkins/run_docker.sh
Currently ChainerX always uses GPU {0,1} for testing. It should be randomly selected like done in chainer-test.
https://github.com/chainer/chainer-test/blob/8420a5880e12cabb00d7cde5796870891c2c2892/docker.py#L812-L822
> Use CUDA_VISIBLE_DEVICES in ChainerX tests

- chainerx_cc/cmake/FindCuDNN.cmake
Fixes #7244
This is a Chainer-side fix to support sharing cuDNN library with wheel-distributed CuPy, by manually specifying the paths of header and library files.
CuPy needs https://github.com/cupy/cupy/pull/2208 and https://github.com/cupy/cupy-release-tools/pull/35.
> Allow `CUDNN_LIBNAME` to be specified by environment variable

- chainer/links/activation/swish.py
I also checked outputs of the following:
```zsh
git grep 'functions\.[A-Z]'
git grep 'F\.[A-Z]'
git grep 'links\.[a-z]' | grep -v import | grep -v 'links\.model'
git grep 'L\.[a-z]'
```
> Fix capitalization of `F.relu` in doc

- chainer/links/connection/linear.py
- tests/chainer_tests/links_tests/connection_tests/test_linear.py
> Fix initialization of `L.Linear` when called with `n_batch_axes`

- chainer/function_node.py
From the documentation, I expect `outputs` to be cleared as well (even though they're weak refs).
Additionally I put an error message for ChainerX fallback function nodes.
> Clear outputs in `FunctionNode.unchain`

- chainer/training/extensions/value_observation.py
They're triggered at non-default interval of `(1, 'epoch')`, but it's not documented.
> Document `observe_value` and `observe_lr` trigger interval

- examples/imagenet/train_imagenet_data_parallel.py
Part of #6661.
~`MultiprocessParallelUpdater` does not support the new devices it seems and need to be fixed for this example to work.~ Fixed by https://github.com/chainer/chainer/pull/7245
> Support device specifiers in ImageNet data parallel example

- chainer/__init__.py
- chainer/configuration.py
- chainer/functions/util/forget.py
- chainer/links/normalization/batch_renormalization.py
- tests/chainer_tests/functions_tests/util_tests/test_forget.py
Fix #7255.
The PR adds a private flag for forward of `F.forget`, in order to avoid consuming additional memory unless `F.forget` requires it.
> Fix recomputation of `L.BatchRenormalization` 

- chainer/__init__.py
- chainer/variable.py
- docs/source/reference/variable.rst
`chainer.as_variable` can be used to easily write code that accepts either `Variable` or `ndarray` as input. However, the opposite is not possible directly from `chainer`, but we must write `chainer.variable.as_array`. I think it's inconsistent that `chainer.variable.as_variable` and `chainer.as_variable` exist, but only `chainer.variable.as_array` and not `chainer.as_array`. I propose that we make the API consistent by exposing the method from `chainer`. What do you think?
> Add `chainer.as_array` for consistency with `chainer.as_variable`

- chainer/links/connection/linear.py
- tests/chainer_tests/links_tests/connection_tests/test_linear.py
> [backport] Fix initialization of `L.Linear` when called with `n_batch_axes`

- chainerx_cc/chainerx/backward.cc
- chainerx_cc/chainerx/backward_test.cc
- tests/chainerx_tests/unit_tests/test_backward.py
> Make `chx.backward` not cause error even if backprop is not required

- chainerx/math/misc.py
A temporary fix (until https://github.com/chainer/chainer/pull/7285 is merged) that allows `chainerx.clip` and `chainerx.ndarray.clip` to take `None` interval arguments.
> Support `None` arguments in `chainerx.clip` and `chainerx.ndarray.clip`

- chainerx_cc/chainerx/cuda/cuda_device/activation.cu
- chainerx_cc/chainerx/native/native_device/activation.cc
- chainerx_cc/chainerx/routines/logic.cc
- chainerx_cc/chainerx/routines/logic.h
- chainerx_cc/chainerx/routines/math.cc
- tests/chainerx_tests/dtype_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_logic.py
- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
This PR makes `chainerx::Maximum` and `chainerx::Minimum` accept Boolean dtypes like as `chainerx::Greater` and `chainerx::Less` do.
> Support bool dtypes in `chainerx::{Max,Min}imum`

- chainer/testing/parameterized.py
> Improve type check in _values_to_dicts so it works with unicode of python 2 too

- tests/chainerx_tests/op_utils.py
If `skip_backward/skip_double_back` is False, the test
is marked as skipped, even when the Forward is checked
and passes successfully. This change will make sure that,
even these tests are marked as PASS by Pytest.
I have a feeling that I saw an issue regarding the same.
But I am unable to find it. Would put a reference to it if
I am able to do so.
> [chainerx][tests] fix skipped_backward tests to return as PASS

- chainer/distributions/bernoulli.py
- tests/chainer_tests/distributions_tests/test_bernoulli.py
Fixed a bug mentioned in https://github.com/chainer/chainer/issues/7057 .
This bug was caused by unintended broadcasting in the backward method.
I added a test that reproduces the bug and fixed it referencing this code https://github.com/chainer/chainer/blob/c92db3396d55a2a351d1bee1a47e33e85dd144b2/chainer/functions/math/basic_math.py#L176  .
> Fix a bug in `Bernoulli.log_prob`

- chainer/testing/parameterized.py
> [backport] Improve type check in `_values_to_dicts` so it works with unicode of python 2 too

- chainerx/_docs/routines.py
> [backport] Fix invalid escape sequences in ChainerX routine docstrings

- scripts/ci/travis/steps.sh
- setup.py
Is there any reason why these are overwritten to `-j2` ?
> Use external $MAKEFLAGS instead if set in Travis CI script

- chainermn/communicators/_communication_utility.py
- chainermn/datasets/scatter_dataset.py
- tests/chainermn_tests/datasets_tests/test_dataset.py
This PR fixes a critical bug, which is related to `scatter_dataset` and `bcast` routines.
`scatter_dataset()` has a parameter called `root`. It is expected that `root` is passed to the underlying MPI collective routines, in particular `Bcast()`. However, the routines are actually hard-coded so the `root` is always rank 0 and the `root` parameter is ignored. The test did not detect the bug.
The PR fixes the bug in two steps. 
First, the test is fixed. The problem in `check_scatter_dataset`  was that all ranks have the same data when the test begins, so if the `root` argument is ignored, rank 0 performed `bcast` and all process obtained the data so the test succeeded.
Second, the code is fixed.
> Fix a bug that root is ignored in  scatter_dataset and bcast

- examples/wavenet/requirements.txt
It looks a typo in wavenet's `requirements.txt`
> Fix typo in wavenet example requirements

- chainerx_cc/chainerx/cuda/cuda_device/misc.cu
- chainerx_cc/chainerx/native/native_device/misc.cc
- chainerx_cc/chainerx/routines/misc.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_misc.py
Fix #7320.
Depends on #7298.
```
chainerx::Square(bool array) -> throws DtypeError
chainerx::Square(intX array) -> returns intX array
chainerx::Square(floatX array) -> returns floatX array
```
> Fix DtypeError in `chainerx.square`

- chainer/functions/noise/dropout.py
- tests/chainer_tests/functions_tests/noise_tests/test_dropout.py
Derives from #7185.
@niboshi I couldn't find why `test_call_cudnn_backward` fails, could you give me a hand?
> Fix condition to invoke cuDNN dropout

- examples/wavenet/train.py
This PR fixes the wavenet example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in wavenet example

- examples/static_graph_optimizations/mnist/train_mnist.py
- examples/static_graph_optimizations/mnist/train_mnist_custom_loop.py
This PR fixes the static_graph_optimizations/mnist example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in static_graph_optimizations/mnist example

- examples/wavenet/train.py
- examples/word2vec/train_word2vec.py
This PR fixes the word2vec example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in word2vec example

- examples/sentiment/train_sentiment.py
This PR fixes the sentiment example to warn possible NaN in FP16 mode.
(train_recursive_minibatch.py causes dtype mismatch in FP16 mode, so I will fix it later)
> Warn NaN in FP16 mode in sentiment example

- examples/static_graph_optimizations/cifar/train_cifar.py
- examples/static_graph_optimizations/cifar/train_cifar_custom_loop.py
This PR fixes the static_graph_optimizations/cifar example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in static_graph_optimizations/cifar example

- examples/dcgan/train_dcgan.py
This PR fixes the dcgan example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in dcgan example

- examples/reinforcement_learning/ddpg_pendulum.py
- examples/reinforcement_learning/dqn_cartpole.py
This PR fixes the reinforcement learning examples to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in reinforcement learning examples

- examples/memnn/train_memnn.py
This PR fixes the memnn example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in memnn example

- examples/pos/postagging.py
This PR fixes the pos example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in pos example

- examples/pix2pix/train_facade.py
Rleated to #6168.
This PR fixes the pix2pix example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in pix2pix example

- examples/dcgan/train_dcgan.py
> [backport] Warn NaN in FP16 mode in dcgan example

- docs/source/examples/train_loop.rst
The example raises an error if it run with Chainer v6.  The `epoch` attribute of some iterator classes become readonly after #5669.
> Avoid setting `test_iter.epoch` manually in the tutorial of training loop

- chainer/functions/pooling/max_pooling_2d.py
- chainer/functions/pooling/max_pooling_nd.py
This PR enables developers to use a deterministic max pooling implementation in cudnn when `config.cudnn_determinisitic` is set `True`.
> Support cudnn deterministic max pooling

- examples/vae/train_vae.py
This PR fixes the vae example to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in vae example

- chainermn/functions/point_to_point_communication.py
This PR improves float16 support for model parallelization.  The bug was found in #6575.
> Bugfix: `MultiNodeChainList` should not assume float32

- docs/source/examples/train_loop.rst
> [backport] Avoid setting `test_iter.epoch` manually in the tutorial of training loop

- tests/chainermn_tests/communicator_tests/test_communicator.py
This PR fixes #7370 .
The bug happens because Python has different arithmetic calculation behavior in version 2 and 3.
```
v = 0.0
for i in range(communicator.size):
if i % 2 == 0:
v += i + 2
v /= communicator.size
```
The variable `v` is `[1 1 1 1]` in Python2 and `[1.0 1.0 1.0 1.0]`  in Python3, because Python3's division implicitly converts integer values to float.
Thus, to pass the test in Python2, the initial value of `v` must be `0.0`, instead of `1`.
> Change 0 to 0.0 for python2

- chainer/backend.py
- tests/chainer_tests/test_backend.py
> Improve `get_device` error message when ChainerX is not available

- chainer/variable.py
- chainerx/__init__.pyi
Add and fix type hints of some methods in `Variable`. Split from #6072.
> Add type hints to `Variable`

- setup.py
install `chainerx` when `READTHEDOCS_PROJECT` name is `chainer`.
this PR stop installing `chainerx` in other projects depending chainer.
> Avoid installing ChainerX when building docs of other projects on ReadTheDocs

- chainer/__init__.py
- chainer/configuration.py
- chainer/graph_optimizations/static_graph.py
- chainer/graph_optimizations/static_graph_utilities.py
- docs/source/reference/configuration.rst
- docs/source/reference/static_graph.rst
- tests/chainer_tests/graph_optimization_tests/test_static_graph_models.py
Part of https://github.com/chainer/chainer/issues/7220.
Introduces a configuration flag `use_static_graph`, which is `True` by default and in which case does not introduce any new behavior to existing code. However, when set to `False`, the static graph decorators simply become "NOOP"s and the code will run as if there were no decorators there.
This is convenient to quickly turn off the static subgraph optimization feature with little change to the code. ChainerX is for instance not supported by the static subgraph optimization and this flag would then be useful.
> Allow turning off the static subgraph optimizations using a config

- setup.py
> [backport] Avoid installing ChainerX when building docs of other projects on ReadTheDocs

- chainerx_cc/chainerx/testing/array_check.h
Since the namespace is incomplete when it's used outside it causes compilation error
> Make `EXEPECT_ARRAY_*` macros able to used outside ChainerX

- chainer/backend.py
Changed to raise an a more appropriate error in `get_device`. 
Also made the error message a bit friendlier.
> `get_device` to raise a more correct error types

- chainer/backends/cuda.py
- tests/chainer_tests/test_backend.py
Related: #7145:
>Before this PR, it returned a seemingly invalid device:
>
>```
>>>> chainer.get_device(chainer.backends.cuda.DummyDevice)
><GpuDevice (cupy):-1>
>```
`DummyDevice` is not a `cupy.cuda.Device`: this inheritance is not appropriate.
> Fix `cuda.DummyDevice` inheritance

- chainerx_cc/cmake/FindCuDNN.cmake
> In `FindCuDNN.cmake`, prioritize explicit variables over environment variables

- chainer/functions/array/resize_images.py
- tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
I add a functionality to make `resize_images` consistent with OpenCV.
`align_corners=True`: current implementation
`align_corners=False`: consistent with OpenCV
```python
import cv2
x = np.array([[1, 2, 0],
[3, 4, 0],
[0, 0, 0]], dtype=np.float32).reshape(1, 1, 3, 3)
y = F.resize_images(x, (6, 6)).data
print(y)
y = F.resize_images(x, (6, 6), align_corners=False).data
print(y)
opencv_y = cv2.resize(x[0].transpose(1, 2, 0), (6, 6))
print(opencv_y)
```
> add align_corners option to `resize_images`

- chainer/initializers/__init__.py
- chainerx/__init__.pyi
- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/python/shape.cc
- chainerx_cc/chainerx/python/shape.h
- chainerx_cc/chainerx/python/testing/device_buffer.cc
- tests/chainerx_tests/conftest.py
- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
- Add `Sequence[int]` support for `shape` arguments in ChainerX functions, which only accept `int` and `Tuple[int]` at the moment.
- Fix tests to check if `shape` is a list of integers
Fixes #7427.
I added `#include <pybind11/stl.h>` to `chainerx_cc/chainerx/python/shape.h` to avoid the following compilation error. It maybe related to pybind/pybind11#1055.
<details><summary>error message</summary>
<p>
```
...
[ 98%] Building CXX object chainerx/python/CMakeFiles/_core.so.dir/shape.o
[100%] Linking CXX shared module /home/user/chainer/chainerx/_core.so
/home/user/chainer/build/temp.linux-x86_64-3.6/pybind11/include/pybind11/stl.h:179:49: error: type ‘struct type_caster’ violates one definition rule [-Werror=odr]
template <typename Type, typename Alloc> struct type_caster<std::vector<Type, …
```
> Add `Sequence` support for `shape` arguments

- chainer/functions/array/resize_images.py
- tests/chainer_tests/functions_tests/array_tests/test_resize_images.py
merge after https://github.com/chainer/chainer/pull/7429
Current implementation of `resize_images` only supports bilinear interpolation.
This PR adds `nearest` interpolation.
> Add nearest mode to resize_images

- docs/source/_static/robots.txt
ReadTheDocs returns 302 instead of 301 for the root, so it may be indexed by search engine.
```
$ curl --head https://docs.chainer.org/
HTTP/2 302
...
```
We should allow indexing it.
> Fix robots.txt to allow indexing root

- chainer/links/connection/deformable_convolution_2d.py
I think that it looks `Args` in comment is old one.
I fixed it.
> Change Deformable Convolution 2D docs to match arguments

- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Sorry missed adding `dstack` to test parameters.
> Add missing parameter `dstack` to `invalid_shape` test

- examples/static_graph_optimizations/cifar/train_cifar.py
- examples/static_graph_optimizations/cifar/train_cifar_custom_loop.py
- examples/static_graph_optimizations/mnist/train_mnist.py
- examples/static_graph_optimizations/mnist/train_mnist_custom_loop.py
Part of https://github.com/chainer/chainer/issues/7220.
The examples are "supported" by disabling the static subgraph optimization feature altogether.
However, the PTB example remains unsupported similar to the original PTB example as explained here https://github.com/chainer/chainer/issues/7220#issuecomment-496785612.
> Support ChainerX in static subgraph optimization examples

- chainerx/_fallback_workarounds.py
We don't allow numpy or cupy arrays to reach fallback functions on chainer x, and we also forbid advanced indexing of chainerx arrays using numpy or cupy arrays.
The behavior is according to the following code:
```
x = chx.array([[0., 1., 2.], [3., 4., 5.]],dtype=chx.float32,device='cuda:0')
xnp = np.array([[0., 1., 2.], [3., 4., 5.]])
x_i = (chx.array([1],device='cuda:0'),)
x_inp = np.array([1])
x_icp = cp.array([1])
x_tup = ([1],)
print(chx.fix(x)) #ALLOWED
print(chx.fix(xnp)) #TYPE ERROR
print('CX ',x[x_i]) #ALLOWED
print('NP ',x[x_inp])#TYPE ERROR
print('CP ',x[x_icp])#TYPE ERROR
print('TU ',x[x_tup])#ALLOWED
```
> Explicit check of chainerx arrays on fallback functions

- chainerx_cc/chainerx/cuda/cuda_device/dot.cu
- chainerx_cc/chainerx/cuda/float16.cuh
`cuda_fp16.hpp` seems to assume `cuda_fp16.h` is included beforehand.
On the other hand `cuda_fp16.h` includes `cuda_fp16.hpp` at the end of it.
Thus it's only necessary to include `cuda_fp16.h`.
Found in #7407.
> Include `cuda_fp16.h` instead of `cuda_fp16.hpp`

- chainer/function_node.py
- chainer/variable.py
Split from #7393.
In `FunctionNode` ChainerX fallback, `ChainerxDevice` is already taken from inputs.
No need of guessing it again with `to_chx()` when creating output variables.
> In `FunctionNode` ChainerX fallback, reuse `ChainerxDevice` taken from inputs to create outputs

- chainer/backend.py
- tests/chainer_tests/test_backend.py
> [backport] Improve `get_device` error message when ChainerX is not available

- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/backprop_mode.cc
- chainerx_cc/chainerx/python/backward.cc
- chainerx_cc/chainerx/python/chainer_interop.cc
- chainerx_cc/chainerx/python/check_backward.cc
- chainerx_cc/chainerx/python/context.cc
- chainerx_cc/chainerx/python/graph.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/python/testing/device_buffer.cc
- chainerx_cc/chainerx/python/testing/testing_module.cc
Seems this style is more smart and it's only needed in chainerx_cc/chainerx/python:
https://pybind11.readthedocs.io/en/stable/basics.html#keyword-arguments
> The `_a` suffix forms a C++11 literal which is equivalent to `arg`. Note that the literal operator must first be made visible with the directive `using namespace pybind11::literals`. This does not bring in anything else from the `pybind11` namespace except for literals.
> Use py::arg literal in ChainerX python binding

- chainer/_backend.py
- chainer/backends/_chainerx.py
- chainer/backends/_cpu.py
- chainer/backends/cuda.py
- chainer/backends/intel64.py
- tests/chainer_tests/backends_tests/test_chainerx.py
- tests/chainer_tests/backends_tests/test_cpu.py
- tests/chainer_tests/backends_tests/test_cuda.py
- tests/chainer_tests/backends_tests/test_intel64.py
Add `is_array_supported` method on `backend.Device`. It is for `Variable` which checks if the specified value is reassignable to itself. This is split from #6072.
> Add `is_array_supported` method on `backend.Device`

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
Fix #7365.
I added a simple test to check against the behavior of a past version. We may want similar tests for other optimizers, too (out-of-scope of this PR, though). Feel free to discuss if there is a better way to catch this kind of regression.
> Fix AdamW update rule regression on CPU

- chainer/initializers/__init__.py
Fix the pydoc in `generate_array` because it actually accepts an `int` value as a `shape`.
Ref. #7446.
> Fix the type of `shape` in `generate_array`

- tests/chainer_tests/dataset_tests/test_convert.py
- tests/chainer_tests/test_backprop.py
- tests/chainer_tests/test_variable.py
It seems `unittest.expectedFailure` does not work with `pytest --pdb`.
> Use `pytest.mark.xfail` instead of `unittest.expectedFailure`

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
Fixes #7312
Takes over #7313
After writing tests, I found that relying on `from_chx` causes `update_core_cpu` to be incorrectly called for `cuda:0` ChainerX parameter if it's uninitialized. It has been fixed altogether.
> Fix `GradientMethod` ChainerX fallback for uninitialized parameters

- chainerx_cc/chainerx/array.cc
- chainerx_cc/chainerx/array_test.cc
- chainerx_cc/chainerx/backend.h
- chainerx_cc/chainerx/cuda/cuda_backend.cc
- chainerx_cc/chainerx/cuda/cuda_backend_test.cc
- chainerx_cc/chainerx/native/native_backend.h
- chainerx_cc/chainerx/native/native_backend_test.cc
Split from #7393.
Also added `Backend::IsNative()`.
> Avoid transferring from a native device to another in `Array::ToNative()`

- chainer/functions/connection/embed_id.py
- chainer/links/connection/embed_id.py
Fixes the Documentation for Embed ID. Outcome differs from the example code.
> Correct Embed ID documentation

- chainerx_cc/CMakeLists.txt
Fixes #7408
Requires ~#7441~ and ~https://github.com/cupy/cupy/pull/2245~
If `CHAINERX_CUDNN_USE_CUPY` (either environment variable or cmake `-D` option) is set, cmake script tries to find installed cupy package and use `cudnn.h` and `libcudnn.so.<ver>` in its installation.
> Add ChainerX build option to use cuDNN from CuPy installation 

- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/communicator_tests/test_mpi.py
This PR fixes #7093 by adding a test to reproduce deadlock in mpi4py's Bcast function.
> Add a test to reproduce the bcast deadlock problem

- chainerx_cc/chainerx/array.cc
- chainerx_cc/chainerx/cuda/cuda_device/copy.cu
- chainerx_cc/chainerx/kernels/misc.h
- chainerx_cc/chainerx/native/native_device/copy.cc
- chainerx_cc/chainerx/routines/creation.cc
- chainerx_cc/chainerx/routines/manipulation.cc
As CopyKernel is a special case of AsTypeKernel.
https://github.com/chainer/chainer/projects/2#card-20163727
Have done reverse of what is mentioned on card as CopyKernel is subset of 
AsTypeKernel.
> Remove ChainerX `CopyKernel`

- chainermn/communicators/two_dimensional_communicator.py
This commit fixes a bug on two_dimensional_communicator, which can be
triggered when running on a certain mpi topology.
This closes #6882 
> Bugfix for pytest 2x2

- tests/chainermn_tests/links_tests/test_multi_node_chain_list.py
This commit add FP16 test to test_multi_node_chain_list.py along with
the FP32.
`pytest.mark.parametrize` is added to switch between `numpy.float32` and
`numpy.float16`.
> Add FP16 test to multi_node_chain_list

- setup.py
typing == 3.7.4 doesn't work well with Python2.
https://ci.preferred.jp/chainer.py2.cv/15182/
This PR is kind a hot fix.
> Pin typing == 3.6.6

- chainerx_cc/third_party/pybind11.cmake
PR #7561 uses `py::ellipsis` which is supported from v2.3.0.
> Update pybind version

- chainer/initializers/__init__.py
> [backport] Fix documentation for `shape` in `generate_array`

- examples/vae/train_vae.py
> Fix typo in `examples/vae/train_vae.py`

- examples/vae/train_vae.py
> [backport] Fix typo in `examples/vae/train_vae.py`

- examples/sentiment/train_recursive_minibatch.py
Rel #6168.
This PR fixes the sentiment example's recursive minibatch version, `train_recursive_minibatch.py`, to support the default dtype feature so that it works in FP16 mode.
> Support default dtype in sentiment example's recursive minibatch version

- examples/sentiment/train_recursive_minibatch.py
Rel. #6168,  and following #7438.
This PR fixes the sentiment example's recursive minibatch version to warn possible NaN in FP16 mode.
> Warn NaN in FP16 mode in sentiment example's recursive minibatch version

- chainerx_cc/chainerx/backward_context.h
The comment seems incorrect to me because I don't see any argument/variable named `"input_grads_storage"`.
> Tiny Fix of `BackwardContext` comment

- tests/chainer_tests/functions_tests/activation_tests/test_crelu.py
- tests/chainer_tests/functions_tests/activation_tests/test_maxout.py
> [backport] Fix y_shape not used in tests

- chainer/distribution.py
- chainer/distributions/cauchy.py
- chainer/distributions/chisquare.py
- chainer/distributions/dirichlet.py
- chainer/distributions/exponential.py
- chainer/distributions/gamma.py
- chainer/distributions/geometric.py
- chainer/distributions/gumbel.py
- chainer/distributions/one_hot_categorical.py
- chainer/distributions/pareto.py
- chainer/distributions/poisson.py
- chainer/functions/activation/slstm.py
- chainer/functions/array/as_strided.py
- chainer/functions/connection/linear.py
- chainer/functions/loss/discriminative_loss.py
- chainer/functions/math/arctanh.py
- chainer/functions/math/det.py
- chainer/graph_optimizations/static_graph.py
- chainer/training/extensions/variable_statistics_plot.py
- docs/source/examples/dcgan.rst
- docs/source/guides/functions.rst
- examples/imagenet/dali_util.py
- tests/chainer_tests/distributions_tests/test_bernoulli.py
- tests/chainer_tests/functions_tests/pooling_tests/test_roi_max_align_2d.py
This PR replaces (deprecated) `cuda.get_array_module` with `chainer.backend.get_array_module` / `backend.get_array_module`.
Before
```shell
~/.ghq/github.com/crcrpar/chainer master ⇡
py37 ❯ git grep -n -e cuda\.get_array_module
chainer/distribution.py:337:        return cuda.get_array_module(*self.params.values())
chainer/distributions/cauchy.py:80:        xp = cuda.get_array_module(self.loc)
chainer/distributions/cauchy.py:88:        xp = cuda.get_array_module(self.loc)
chainer/distributions/cauchy.py:108:        xp = cuda.get_array_module(self.loc)
chainer/distributions/chisquare.py:64:        xp = cuda.get_array_module(self.k)
chainer/distributions/dirichlet.py:77:        xp = cuda.get_array_module(self.alpha)
chainer/distributions/exponential.py:77:        xp = …
```
> Use `backend.get_array_module` not `cuda.get_array_module`

- chainerx_cc/chainerx/python/routines.cc
Rename some functions added in #7031.
> Rename split functions in pybind implementation

- chainer/function_node.py
> Skip `None` array in `FunctionNode` NaN check

- chainer/function_node.py
> [backport] Skip `None` array in `FunctionNode` NaN check

- examples/sentiment/train_recursive_minibatch.py
> [backport] Support default dtype in sentiment example's recursive minibatch version

- chainer/variable.py
Follow up #7146.
Apparently #7146 tried to fix this incorrectly placed comment, but forgot to remove the one in the original place.
> Remove moved comment

- docs/source/guides/extensions.rst
> [backport] Correct missing parenthesis in documents

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
`UpdateRule` and `Optimizer` have duplicate code implementation for hooks.
Indeed they have slightly different and inconsistent behavior in some points, including an error type which has been fixed.
Depends on #7585
> Avoid code duplication in optimizer hook implementation

- examples/text_classification/train_text_classifier.py
With the original example, the best model will never be saved as the trigger is consumed with the Trainer snapshot, whose extension is added right before the extension for best model added. As triggers are stateful, one trigger object cannot be used for multiple extensions (If reusing a trigger for multiple extensions is really the use case, maybe we could change Chainer, though...). Anyway we might have cleared this out at document. BTW is example bug is also to be tagged as bug?
Thanks for finding this out, @chezou .
> Example fix: stateful triggers cannot be reused

- chainer/initializers/constant.py
- chainer/initializers/normal.py
- chainer/initializers/orthogonal.py
- chainer/initializers/uniform.py
- tests/chainer_tests/initializer_tests/test_constant.py
- tests/chainer_tests/initializer_tests/test_normal.py
- tests/chainer_tests/initializer_tests/test_orthogonal.py
- tests/chainer_tests/initializer_tests/test_uniform.py
Initializers were not checking the actual device id in multi gpu environments.
The lack of tests using the cuda_id 1 hid this behavior.
This PR fixes this problem and reworks the test to use the `inject_backend_tests`
ChainerX support will be added in another PR.
> Fix `initializers.Identity` for ideep backend

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
AMSGrad's state `vhat` should be updated.  The intention of `out=vhat` (https://github.com/chainer/chainer/pull/4032#discussion_r169032555) was unclear, which led to an error in #6388 (2f05180c8a02b5651ff5d9b51324d6400be7bd04).
> Fix AMSGrad with intel64 backend

- .gitignore
- chainerx/__init__.py
- chainerx_build_helper.py
> Emit build info of ChainerX and stop hiding `ImportError`

- chainer/functions/array/squeeze.py
> [backport] Fix typo in `F.squeeze` documentation

- chainer/function_node.py
- tests/chainer_tests/test_function_node.py
Some operations where not inside the `with chainer.using(device)` on `chainer.grad`
leading to errors when refactoring the grad tests to use different devices.
> Fixes an error on chainer.grad for multiple devices

- chainer/optimizer_hooks/gradient_clipping.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_clipping.py
Fixes #7640
There were unit tests for internal implementation `_sum_sqnorm`.
This PR includes refactoring of this function, so I removed the unit tests and replaced with improved `TestGradientClipping`.
> Fix `optimizer_hooks.GradientClipping` for ChainerX

- chainer/initializers/constant.py
- chainer/initializers/normal.py
- chainer/initializers/orthogonal.py
- chainer/initializers/uniform.py
- tests/chainer_tests/initializer_tests/test_constant.py
- tests/chainer_tests/initializer_tests/test_normal.py
- tests/chainer_tests/initializer_tests/test_orthogonal.py
- tests/chainer_tests/initializer_tests/test_uniform.py
> [backport] Fix `initializers.Identity` for ideep backend

- chainer/functions/normalization/batch_renormalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_batch_renormalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py
Fix #7506.
The statistics tests were unexpectedly passing because they didn't test with large `eps`.
Split from #7104.
> Exclude eps from `running_var` of `F.batch_renormalization`

- chainer/_backend.py
- chainer/backends/_chainerx.py
- chainer/backends/_cpu.py
- chainer/backends/cuda.py
- chainer/backends/intel64.py
- tests/chainer_tests/backends_tests/test_chainerx.py
- tests/chainer_tests/backends_tests/test_cpu.py
- tests/chainer_tests/backends_tests/test_cuda.py
- tests/chainer_tests/backends_tests/test_intel64.py
Background: `_sum_sqnorm_grads` in #7641
`devices_map` would not be required.
> Make devices hashable

- chainerx_cc/chainerx/python/shape.cc
https://clang.llvm.org/extra/clang-tidy/checks/readability-else-after-return.html
> Avoid else after return

- tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
This PR improves `shape` parameters in group normalization tests:
1. Use smaller array.
2. The config `dict(shape=(3, 8), groups=4)` has unstable backward because it
standardizes the inputs per two samples.
Close #6911.
> Fix GroupNormalization tests

- chainerx/_docs/routines.py
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/loss.cc
- chainerx_cc/chainerx/routines/misc.cc
- chainerx_cc/chainerx/routines/misc.h
- docs/source/chainerx/reference/routines.rst
- tests/chainerx_tests/unit_tests/routines_tests/test_misc.py
Follow up of https://github.com/chainer/chainer/pull/7063.
Removed `squared_difference` as it's a duplicate of `squared_error`. Which one to keep could be discussed but the one that's kept is closer to MSE and might be easier to find. It might however sound unnatural in a situation where we don't want to compute any losses.
Also fixed documentations of functions introduced in #7063.
> Remove `squared_difference` and fix docs

- chainer/link_hooks/spectral_normalization.py
When doing spectral normalization, if using chainerx 
the link gamma parameter is not being converted back to chainerx after the fallback due to the lack of svd.
This PR proposes to use @toslunar solution in #7455 to avoid this issue.
This PR enables #7520 spectral_normalization tests to complete without errors.
> Fixes spectral normalization chainerx conversion

- chainer/training/triggers/interval_trigger.py
- tests/chainer_tests/training_tests/triggers_tests/test_interval_trigger.py
This PR implements `IntervalTrigger.__str__`.
I want this because I'm setting an IntervalTrigger as a default argument for `argparse.ArgumentParser` and the help message is now messy like below.
```
--log-interval N_iter
Frequency of log. (default: <chainer.training.triggers
.interval_trigger.IntervalTrigger object at
0x2aebbea172e8>)
```
> Implement IntervalTrigger.__str__

- tests/chainerx_tests/unit_tests/routines_tests/test_loss.py
Fix #7696.
Fixed flaky `chainerx.huber_loss` backward/double-backward test like as #6924.
> Fix flaky TestHuberLoss

- chainer/datasets/pickle_dataset.py
- tests/chainer_tests/datasets_tests/test_pickle_dataset.py
fix: #7589
If already addressing this issue, I apologize.
I resolved this issue by using `multiprocessing.util.register_after_fork()` .
This function register hooks to be triggered when initializing child process.
`_FileReader` is a wrapper to hold filepath and re-open the file after fork.
> Fix PickleDataset crash when use multiprocessing

- chainer/functions/array/concat.py
> [backport] Use `six.integer_types` for axis check in `F.concat`

- chainer/iterators/multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
When using `MultiprocessParallelUpdater` the `MultiprocessIterator` objects
are pickled when starting the workers.
The `MultiprocessIterator` object has an internal `_Communicator` object which holds a
threading.lock and is pickled too. However, this kind of object is not serializable with pickle.
This patch makes the `MultiprocessParallelUpdater` class to implement the pickle interface and relies on chainer `serialize` interface to implement object pickling.
> Fix pickling issues on `MultiprocessIterator`

- chainer/datasets/pickle_dataset.py
- tests/chainer_tests/datasets_tests/test_pickle_dataset.py
> [backport] Fix `PickleDataset` crash when using multiprocessing

- setup.cfg
This PR tries to address #7433.
> Fix warning filter for protobuf

- chainer/variable.py
- tests/chainer_tests/test_variable.py
Fixes #7734
Note that `Variable.dtype` is out of scope.
`Variable(None)` should be eventually prohibited (#6116).
> Fix `Parameter.dtype` for uninitialized parameter

- tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
Fix #7704.
https://github.com/chainer/chainer/blob/23941e89ea4725f63a53ac532d51b521352dd506/chainer/functions/loss/contrastive.py#L83
Hard to calculate numerical gradient correctly when `x1 - x2` includes a value around zero.
> Fix flaky `TestContrastive`

- chainer/reporter.py
- tests/chainer_tests/test_reporter.py
> Fix reporter for multi-thread use

- chainer/testing/array.py
This PR reproduces the bug: #7726.
~Merge #7727 first.~
> Reverse input array for non-contiguous tests

- chainer/functions/loss/contrastive.py
Related to #7704.
In `Contrastive.backward`, eps(=`1e-7`) is added to `dist` to avoid zero-division. However, when the dtype of input arrays are `float16` it cause overflow because float16 arrays can't express `1e7`.
> Fix eps in `Contrastive.backward`

- chainer/utils/type_check.py
- tests/chainer_tests/utils_tests/test_type_check.py
I think it's useful when debugging.
Without this, it's difficult to debug in `check_type_forward` because you cannot write something like
```py
if x_type.dtype == numpy.float32:
print("OK")
```
which would result in:
```
RuntimeError: Don't convert Expr to bool. Please call Expr.eval method to evaluate expression.
```
You cannot write something like this either (which is suggested by the error message above):
```py
if (x_type.dtype == numpy.float32).eval():
print("OK")
```
which would result in:
```
AttributeError: 'bool' object has no attribute 'eval'
```
That's because `check_type_forward` is called twice in different modes, with different way of evaluation.
This is not intuitive.
> Allow bool evaluation in `type_check`

- chainer/utils/type_check.py
- tests/chainer_tests/utils_tests/test_type_check.py
Reverts chainer/chainer#6414, because the discussion on the benefit brought by #6414 surely supersedes what the current behavior does hasn't finished.
> Revert "Allow bool evaluation in `type_check`"

- docs/source/install.rst
> Add a note for Python 2 drop in v7

- chainer/variable.py
- tests/chainer_tests/test_variable.py
> [backport] Fix `Parameter.dtype` for uninitialized parameter

- chainer/optimizer.py
- tests/chainer_tests/test_optimizer.py
> [backport]  Fix `UpdateRule.use_fp32_update` for uninitialized parameter 

- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Silence the warning messages.  See also #6556 and 495a43068e6a4ea31d11e43ff195bbf417e7b5b8.
> Fix test of `chx.reshape`

- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
Fix #7690
Found that it was due to lack of precision as some values were not being converted to FP32 during intermediate calculations.
> Fix Adam FP16 overflow on gpu kernels

- chainer/optimizer_hooks/gradient_hard_clipping.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_clipping.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_hard_clipping.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_lars.py
- tests/chainer_tests/optimizer_hooks_tests/test_gradient_noise.py
- tests/chainer_tests/optimizer_hooks_tests/test_lasso.py
- tests/chainer_tests/optimizer_hooks_tests/test_weight_decay.py
- tests/chainer_tests/optimizer_hooks_tests/utils.py
- tests/chainer_tests/test_runnable.py
Fixes #7759
This PR was originally intended to refactor the tests (#7759) but I found a bug in `optimizer_hooks.GradientHardClipping`. I can split the PR if it's preferable.
> Fix `optimizer_hooks.GradientHardClipping` for scalar array

- chainer/functions/math/average.py
- tests/chainer_tests/functions_tests/math_tests/test_average.py
> [backport] Make `F.average` as accurate as backend

- chainer/functions/array/resize_images.py
Hello, I found that my source code that running at v6 causes an error at v7.
The corresponding source code is as follows.
```
hoge = F.resize_images(hoge, (100, 1))
hoge = F.resize_images(hoge, (1, 100))
```
This problem is caused by the following PR.
#7429 #7443 
The problem is `y_scale = (H - 1) / (out_H - 1)` because when output size was 1, zero division will happen. 
I wonder why we calculate `y_scale = (H - 1) / (out_H - 1)` here, and bilinear mode and nearest options  calculate `y_scale = H / out_H` instead of `y_scale = (H - 1) / (out_H - 1)`
But the easy solution is to change the part back into the v6 as follows.
https://github.com/chainer/chainer/blob/7191660634e151dd4f27e97437bee5c53bef177c/chainer/functions/array/resize_images.py#L195
I provide a modified source code according …
> fix "zero division" in resize image

- chainer/functions/pooling/max_pooling_2d.py
This is a fix to the following error 
`TypeError: Cannot cast ufunc add output from dtype('int64') to dtype('uint8') with casting rule 'same_kind'`
that I encountered while rewriting `test_max_pooling_2d`
> Fix TypeError in `max_pooling_2d`

- chainerx/__init__.py
Fix #7730.
```
File "/home/imanishi/chainer/chainerx/__init__.py", line 10, in <module>
'$ pip install -e {}'.format(root_dir))
ImportError: Reinstall Chainer in "editable" mode.
$ pip install -e /home/imanishi/chainer
```
> Improve chainerx import check

- chainermn/communicators/pure_nccl_communicator.py
> [backport] Avoid unload module call in PureNcclCommunicator

- chainerx/__init__.pyi
- chainerx/_docs/routines.py
- chainerx_cc/chainerx/cuda/cuda_device/fill.cu
- chainerx_cc/chainerx/kernels/creation.h
- chainerx_cc/chainerx/native/native_device/fill.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/creation.cc
- chainerx_cc/chainerx/routines/creation.h
- docs/source/chainerx/reference/routines.rst
- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
This PR adds [`tri`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tri.html), [`tril`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html), [`triu`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html) routines.
With reference to #6423 and #6764
> Add `tri*` routines to ChainerX

- chainerx_cc/chainerx/routines/reduction.cc
Removed an unused lambda capture in the `Cumsum` routine.
Reference: https://travis-ci.org/chainer/chainer/jobs/562937926#L3237
> Remove unused lambda capture of `axis`

- chainer/utils/type_check.py
> [backport] Fix `type_check` error message on evaluating bool expression

- tests/chainermn_tests/communicator_tests/test_communicator.py
The `unique` here is confusing, which can mean the opposite to some people.
For example:
Each run has an unique order => Each run has a different order.
`Deterministic` is more clear as an opposite to `Random`.
> Unique -> deterministic

- chainer/training/extensions/log_report.py
- chainer/training/extensions/plot_report.py
- chainer/training/trainer.py
- examples/mnist/train_mnist.py
- tests/chainer_tests/training_tests/test_trainer.py
I sometimes need to know the loss and accuracy before the training (iteration=0), but currently I'm not sure how to do this with the Trainer class.
This PR achieves it.
It writes loss and accuracy result even if the epoch is 0.
```
cd examples/mnist
python train_mnist.py
```
```
cd tests/chainer_tests/training_tests/triggers_tests
python test_interval_trigger.py
```
> Invoke extensions before training

- chainer/dataset/tabular/_slice.py
- tests/chainer_tests/dataset_tests/tabular_tests/test_slice.py
`numpy.ndarray` supports mixture of ints and bools as slice indices. This PR adds same functionality to `TabularDataset.slice`.
> Support mixed indices in `TabularDataset.slice`

- chainermn/communicators/communicator_base.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- docs/source/chainermn/reference/index.rst
- tests/chainermn_tests/communicator_tests/test_communicator.py
This commit adds finalize function to the mpi_communicator_base.
The `finalize` finalizes and cleans up resource of the communicator.
After the `finalize` is called, the communicator should not be used again.
In `finalized` is overrided in `non_cuda_aware_communicator` and `pure_nccl_communicator` to clean up the intra nccl communicator
> Add finalize method to CommunicatorBase class

- chainer/functions/normalization/decorrelated_batch_normalization.py
Follow up on https://github.com/chainer/chainer/pull/7707 removing an unused argument from a private function in decorrelated batch normalization.
> Remove unused argument from decorrelated batch norm

- tests/chainermn_tests/communicator_tests/test_communicator.py
This commit fixes a typo in test_communicator which causes the nccl
communicator in non_cuda_aware_communicator cannot be identified and destroyed.
> Fix a typo in test_communicator

- chainermn/extensions/__init__.py
- chainermn/extensions/multi_node_early_stopping_trigger.py
- chainermn/extensions/observation_aggregator.py
- tests/chainermn_tests/extensions_tests/test_multi_node_early_stopping_trigger.py
- tests/chainermn_tests/extensions_tests/test_observation_aggregator.py
This commit adds `chainermn.extensions.observation_aggregator` which summarizes a specific observation in the trainer over all processes.
This is the implementation of #6974.
> Add observation_aggregator

- chainer/gradient_check.py
- chainer/testing/function_link.py
- tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
- tests/chainer_tests/testing_tests/test_function_link.py
Allow `None` in gradient check inputs and `None` gradients to be generated by `FunctionTestCase`.
This is needed if we want to allow generating `None` "gy" and still test double backward (in this case, the inputs to gradient check for double backward will include `None`) or generate `None` "ggx". This applies to functions with multiple outputs e.g. https://github.com/chainer/chainer/pull/7805.
> Allow `None` inputs to gradient check and generating `None` gradients in `FunctionTestCase`

- chainermn/communicators/pure_nccl_communicator.py
It was not possible to distinguish whether NCCL is old or not installed.
> Improve NCCL availability error in `PureNcclCommunicator`

- chainermn/communicators/__init__.py
- chainermn/communicators/_memory_utility.py
- chainermn/communicators/dummy_communicator.py
- chainermn/communicators/flat_communicator.py
- chainermn/communicators/mpi_communicator_base.py
- chainermn/communicators/naive_communicator.py
- chainermn/communicators/non_cuda_aware_communicator.py
- chainermn/communicators/pure_nccl_communicator.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
This commit does following adjustments:
1. moving the batched_copy from pure_nccl_communicator to the
base class of communicators, which enables batched_copy in all the
communicators.
2. A batched_copy parameter is added to the __init__ of all the
communicators.
3. The warning when using batched_copy on creating communicators
other than pure_nccl_communicator is removed.
> Add batched_copy to All Communicators

- chainer/testing/function_link.py
This is needed in #7804, to avoid default `float64` casting in cuDNN-backed `F.n_step_rnn` which only supports `float32`.
> Add `numerical_grad_dtype` to `FunctionTestCase` and `LinkTestCase`

- chainer/functions/math/clip.py
Part of #7741
From NumPy 1.17, `numpy.clip(x, self.x_min, self.x_max)` returns `float64` array even if `x.dtype` is `float16`.
> Fix `F.clip` for NumPy 1.17

- tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
Part of #7741
From NumPy 1.17, `x.clip(0, self.z)` returns `float64` array even if `x.dtype` is `float16`.
> Fix `F.clipped_relu` test for NumPy 1.17

- tests/chainer_tests/functions_tests/loss_tests/test_huber_loss.py
Fix #6906.
PR #6924 set `eps` to avoid non-differential point, but it was not large enough.
> Fix flaky `TestHuberLoss`

- chainer/functions/array/split_axis.py
- tests/chainer_tests/functions_tests/array_tests/test_split_axis.py
If `SplitAxis.backward` is called with `None` upstream gradients, zero-filled arrays are constructed using `self._xp`. However, this `self._xp` attribute is not set for the intel64 path. This PR fixes this issue.
Depends on https://github.com/chainer/chainer/pull/7831.
> Fix backward of `split_axis` for intel64 when `grad_ouputs` contains `None`

- tests/chainerx_tests/unit_tests/routines_tests/test_connection.py
> Skip flaky `TestConv*TensorCore`

- chainerx_cc/chainerx/cuda/cuda_device/linalg.cu
- chainerx_cc/chainerx/native/native_device/linalg.cc
- chainerx_cc/chainerx/routines/linalg.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
With this PR `linalg.solve` supports input with different dtypes.
With reference to #6764.
> Add support for input with different dtypes for 'linalg.solve' in ChainerX

- chainer/testing/array.py
Included `rtol * abs(b)`, `atol` and the sum of those two in the output of `allclose`. 
`allclose` is used in the numerical gradient check and contributes to the error message. It makes life easier when working with https://github.com/chainer/chainer/issues/6903 and debugging failures of numerical gradient checks in general.
> Include `rtol * abs(b)` in `allclose` output

- tests/chainer_tests/functions_tests/activation_tests/test_clipped_relu.py
> [backport] Fix `F.clipped_relu` test for NumPy 1.17

- tests/chainerx_tests/unit_tests/routines_tests/test_normalization.py
Fixes https://github.com/chainer/chainer/issues/6913.
Repeated over thousand times without failures locally.
Basically aligned the test configuration to Chainer. The computed gradients were identical to Chainer's BN (fp16 has known instabilities, but for fp32 and fp64) so I don't think the implementation is wrong. Please see the issue for further details.
> Fix `BatchNorm` flaky of ChainerX

- tests/chainer_tests/functions_tests/pooling_tests/test_average_pooling_2d.py
Fixes #7703
`check_double_backward_options` was not configured.
> Configure tolerances of `F.average_pooling_2d` test

- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
Fix #7809.
Use `atol` because directional derivative is tested.
> Fix `test_TrilTriu`

- chainerx_cc/chainerx/python/routines.cc
> Fix copies for `linalg.svd` python bindings layer in ChainerX

- scripts/ci/travis/steps.sh
TravisCI is failing after the homebrew formula updates to `open-mpi-4.0.1_2`.
> Fix MPI installation for macOS

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
This PR modifies the `deconvolution` tests to follow the `testing.FunctionTest` approach.
This is the first step towards eliminating the flakyness of the convolution related tests.
Merge before #7864
> Refactor convolution functions tests

- chainer/backend.py
- tests/chainer_tests/test_backend.py
- tests/chainer_tests/test_variable.py
> Fix `backends.copyto` from chainerx to non-chainerx

- tests/chainer_tests/links_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py
Refactor links_tests convolution nd and 2d to use the backend injection and testing.LinksTestCase
format.
Merge before #7864
> Relax tolerances in convolution link tests when using old cuDNN

- tests/chainer_tests/links_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_deconvolution_nd.py
> [backport] Relax tolerances in convolution link tests when using old cuDNN

- tests/chainerx_tests/math_utils.py
Fixes #7845
```
pytest --count 1000  -s -v -rfEX --tb=short tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py -k '_Sub_ and float16 and cuda'
```
Before: `7 failed, 59993 passed, 26690000 deselected in 4267.15 seconds`
After fix: `60000 passed, 26690000 deselected in 4166.01 seconds`
> Relax float16 tolerances in ChainerX binary math tests

- docs/source/reference/static_graph.rst
- examples/static_graph_optimizations/mnist/train_mnist.py
> Fix `static_graph` docs code examples

- tests/chainerx_tests/unit_tests/routines_tests/test_reduction.py
Fixes #7861
Ran 10000 trials without error.
> Fix `chainerx.logsumexp` test tolerance

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Fix `chainerx.logsumexp` test tolerance

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
Depends #7863 #7868  Merge after #7863 #7868 
Fixes #7693 and #7695 
When using cudnn 5.x convolution tests often suffer from precision related issues.
This PR relax the tolerance requirements when using cudnn <6.
1000 runs of test_backward for ConvolutionND
cudnn 5.2 - 45 failures (4.5%)
cudnn 7 - 0 failures
cudnn 5.2 with higher tolerance - 0 failures
> Relax tolerances in convolution function tests when using old cuDNN

- scripts/ci/travis/steps.sh
Reverts chainer/chainer#7872
Homebrew/homebrew-core@52ae4857839ec471372014e03beec872477dc0f7 fixed the issue.
> Revert "Fix MPI installation for macOS"

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
> [backport] Relax tolerances in convolution function tests when using old cuDNN

- chainer/functions/rnn/lstm.py
- tests/chainer_tests/functions_tests/rnn_tests/test_function_lstm.py
Same fix as https://github.com/chainer/chainer/pull/7891 but for LSTM, instead of SLSTM.
The double backward implementation can be further optimized by the way, but that should be done in a different PR and my understanding is that this omitted gradient is a rather rare case in practice.
> Fix LSTM for omitted upstream gradients

- chainer/links/model/vision/resnet.py
- tests/chainer_tests/links_tests/rnn_tests/test_link_n_step_gru.py
- tests/chainer_tests/links_tests/rnn_tests/test_link_n_step_lstm.py
- tests/chainer_tests/links_tests/rnn_tests/test_link_n_step_rnn.py
- tests/chainermn_tests/links_tests/test_n_step_rnn.py
This PR replace variables/keywords `n_layer` with `n_layers`.
Although most changes do not break compatibility,
there is the breaking change in `BuildingBlock`.
https://github.com/chainer/chainer/compare/master...himkt:fix-var-name-n-layer?expand=1#diff-b27899a8e6e2ef04c4b64bb26c60669aR548
> Replace n_layer with n_layers for consistency

- tests/chainer_tests/functions_tests/normalization_tests/test_group_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
> Sample stable inputs in tests of group normalization

- chainer/function.py
- tests/chainer_tests/test_function.py
Fixed a bad test for old style `Function` and the corresponding code to prevent it from happening again.
> Avoid `ndarray.data` access and fix wrong test

- tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
> Avoid unstable inputs in tests of decorrelated batch normalization

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
Backport of #7874
`BinaryMathTestBase` is not defined in `math_utils.py` in `v6`.
> [backport] Relax float16 tolerances in ChainerX binary math tests

- tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py
Relax `TestTrueDiv` tolerances when using fp16 to be in the same range than #7874 
Fixes #7785
> FlakyTests: TrueDiv relax fp16 tolerance

- tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
> [backport] Avoid unstable inputs in tests of decorrelated batch normalization

- chainer/functions/array/split_axis.py
> [backport] Fix backward of `split_axis` for intel64 when `grad_ouputs` contains `None`

- chainer/functions/pooling/max_pooling_2d.py
The precision of `F.max_pooling_2d` was degraded when `dtype = float64` (to `float32`).
Fixes #7911: It seems the precision is not enough in numeric gradient when `dtype = float32`.
Tested with
`pytest -x -m 'not chainerx and gpu and not cudnn' -v -rfEX --tb=short tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py -k 'test_backward and float32 and param_1_'`
for 100000 trials without any error (without this fix, the first failure was around ~1000th).
> Fix precision in `F.max_pooling_2d`

- chainer/functions/pooling/max_pooling_2d.py
> [backport] Fix precision in `F.max_pooling_2d`

- tests/chainer_tests/links_tests/normalization_tests/test_decorrelated_batch_normalization.py
Solves #6908 
This PR aims to solve the flakiness of #6908 when using links.
PR #7900 fixed it only for functions and not for links.
Here we apply the same solution originally devised by @toslunar.
Moreover, we refactor the test to use the `LinkTestCase` in order to reduce the code size.
Before this fix: 290 failures out of 10000 runs.
After the fix 0 failures are observed.
> Refactor `DecorrelatedBatchNormalizationTest` and add stable input

- tests/chainer_tests/functions_tests/array_tests/test_cast.py
Fixes  #7892
The result of a cast from a negative floating-point number to an unsigned integer is not specified. Avoid testing that condition.
> Avoid testing `F.cast` from negative floating-point to unsigned

- chainer/links/model/vision/resnet.py
Related to https://github.com/chainer/chainer/pull/7871.
I apologize that I forgot adding `DeprecationWarning` in `warnings.warn`.
FIY. @emcastillo
> Add DeprecationWarning to initializer of BuildingBlock

- chainer/function.py
- tests/chainer_tests/test_function.py
> [backport] Avoid `ndarray.data` access and fix wrong test

- chainer/link.py
- chainer/optimizers/adam.py
- tests/chainer_tests/optimizers_tests/test_optimizers.py
- tests/chainer_tests/test_link.py
> [backport] Fix in-place update of arrays in `Link.serialize` and `optimizers.Adam`

- chainer/backend.py
- tests/chainer_tests/test_backend.py
This PR backports `backend.copyto` parts of (#7226, #7835).
> [backport] Fix `backends.copyto` from/to chainerx

- chainer/serializers/hdf5.py
- chainer/serializers/npz.py
- tests/chainer_tests/serializers_tests/test_hdf5.py
- tests/chainer_tests/serializers_tests/test_npz.py
Fixed https://github.com/chainer/chainer/issues/7829 (npz and HDF5). The copy logic is simply the same as in `backend.copyto`.
> Fix ChainerX non native deserialization

- tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py
Closes #7702
I confirmed that both backward and double backward tests are flaky.
After adjusting the parameter, flakiness has been resolved in my environment.
> Fix flaky power test

- tests/chainer_tests/functions_tests/rnn_tests/test_function_tree_lstm.py
The double backward tests have to be skipped due to the following error:
`RuntimeError: cannot twice-differentiate an old style Function "TreeLSTM"`
> `F.tree_lstm` test for ChainerX

- tests/chainer_tests/functions_tests/loss_tests/test_contrastive.py
> [backport] Relax fp16 tolerances in `TestContrastive`

- docs/source/install.rst
> [backport] Add 1.17 to supported NumPy versions

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Relax fp16 tolerance in `TrueDiv` test

- tests/chainer_tests/links_tests/loss_tests/test_crf1d.py
Fixes #7925 
Tested 100000 trials without any error:
`pytest -v -rfEX --tb=short tests/chainer_tests/links_tests/loss_tests/test_crf1d.py  -k 'test_forward_cpu and float16 and param_1_'`
> Fix tolerance in `L.CRF1d` test

- tests/chainer_tests/functions_tests/math_tests/test_inv.py
Fixes #7969
Confirmed `test_backward` passes for 100000 repeats.
>`pytest -m 'not gpu and not chainerx' -v -x -rfEX --tb=short tests/chainer_tests/functions_tests/math_tests/test_inv.py -k 'BatchInv and test_backward'`
> Relax float16 tolerances in `F.batch_inv` test

- chainerx_cc/chainerx/cuda/cuda_device_test.cc
- chainerx_cc/chainerx/cuda/memory_pool.cc
- chainerx_cc/chainerx/cuda/memory_pool.h
- chainerx_cc/chainerx/cuda/memory_pool_test.cc
This PR implements hook functionality for MemoryPool objects.
To discuss:
* Is the interface of hooks sufficient? For example, hook functions don't have access to MemoryPool.
* FreePostprocessHook seems a little meaningless.
* ~~It might be better to add a test in CudaDeviceTest as well?~~
> Implement hooks for memory pool in ChainerX

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_nd.py
Aims to fix #7695 
Double backward test was failing [Jenkins](https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1828/testReport/)
> Relax tolerances in old cuDNN convolution tests

- tests/chainer_tests/functions_tests/loss_tests/test_negative_sampling.py
Fixes https://github.com/chainer/chainer/issues/7958.
Relaxes `rtol` for float16 backward tests. Verified locally for 50k repetitions to all pass.
Also includes some cosmetics for readability.
`rtol` for double backward should probably be relaxed too but I'm leaving that to after flaky failures have been observed since this one is rare already.
> Fix flaky `negative_sampling`

- chainerx_cc/chainerx/routines/manipulation.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_manipulation.py
Fixes a floating point exception in reshape in ChainerX, raising an error similar to NumPy.
The changes are quite self-describing so please refer to them.
> Fix floating point exception in ChainerX inferred reshape

- tests/chainer_tests/test_gradient_check.py
Fixes #7973
Confirmed by 100000 repeats
> Relax tolerances in `gradient_check` test

- chainerx/_docs/routines.py
It seems other integer dtypes including `uint8` are supported.
> Remove obsolete note about `chainerx.take` indices dtype

- tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py
Fixes #8008
Confirmed to pass 100000 times in a row, both in backward and double-backward tests:
`pytest tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py -k 'float16 and test_backward_cpu and _param_1_'`
`pytest tests/chainer_tests/functions_tests/loss_tests/test_squared_error.py -k 'float16 and test_double_backward_cpu and _param_1_'`
> Fix numerical gradient precision in `F.squared_error` test

- tests/chainer_tests/test_gradient_check.py
> [backport] Relax tolerances in `gradient_check` test

- chainer/initializers/__init__.py
- chainer/initializers/constant.py
- chainer/variable.py
- tests/chainer_tests/test_variable.py
Merge before #7525
When trying to create a `variable.Parameter` with an `initializer.Constant` that uses an array other than NumPy, the call to the `initialize` method will faill when trying to generate the array, as the `variable.Parameter` class expects the initializer to be internally using a `numpy.ndarray` if its `initializer.Constant`.
When the `initializers.Constant` tries to copy an array to an array residing on another backend it explicitly moves its fill_value to the target device. This allows to have the `Parameter` initialized with numpy arrays as the  convention requires.
> Support CuPy/ChainerX arrays when initializing `variable.Parameter` objects

- docker/intel/python2/Dockerfile
- docker/python2/Dockerfile
This PR fixes the docker build failure.
(Python 2 is no longer supported in NumPy 1.17)
Although Py2 is no longer supported in master branch, I'd like to fix in master branch as we need to re-release the docker image for v7.0.0b3 (and v6.3.0) using these Dockerfiles.
> Fix NumPy version in Dockerfile

- tests/chainerx_tests/unit_tests/routines_tests/test_misc.py
> Avoid non-differentiable point in min/max tests

- tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py
Closes #7785 
The real reason behind the flakiness of this tests is #7991 but since it is not easily solvable, we decided to increase the tolerance.
100k runs of the double_backward tests with parameter combinations of float16 types and several shapes tests without issues.
> Adjust TrueDiv tolerances

- chainer/backend.py
#7226 didn't fix the doc.  Is it a public spec of `chainer.backend.copyto` to support `chainerx.ndarray`?
> Fix doc of `backend.copyto`

- chainer/functions/normalization/batch_normalization.py
- chainermn/functions/batch_normalization.py
- chainermn/links/batch_normalization.py
This PR refactors the `batch_normalization` in `chainermn`.
The motivation is to merge the `batch_normalization` code in `chainermn` into the `batch_normalization` in `chainer`, which can reduce the code redundancy, and enables features in `batch_normalization` in `chainer` into `chainermn`.
This PR resolves #6533
> Refactor `F.batch_normalization` and ChainerMN backend implementations

- chainerx_cc/chainerx/native/CMakeLists.txt
- chainerx_cc/chainerx/native/native_device/cblas.h
- chainerx_cc/chainerx/native/native_device/dot.cc
ChainerX's native_device can't utilize BLAS libraries which don't have `cblas.h` (e.g. intel mkl). This PR adds ChainerX's `cblas.h` and removes workaround codes in CMakeLists.txt.
> Add cblas.h and modified CMakeLists.txt

- chainer/functions/normalization/decorrelated_batch_normalization.py
- chainer/links/normalization/decorrelated_batch_normalization.py
- tests/chainer_tests/functions_tests/normalization_tests/test_decorrelated_batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_decorrelated_batch_normalization.py
> [backport] Fix decorrelated batch normalization when groups ≠ 1

- tests/chainerx_tests/dtype_utils.py
- tests/chainerx_tests/math_utils.py
This PR suppresses the number of combinations of `in_out_dtypes` to reduce test execution time.
`python -m pytest tests/chainerx_tests/unit_tests/routines_tests/`
- `8c8025e`: 167127 items
- `d51b93b`: 158359 items
> Suppress number of combinations of in_out_dtype

- chainerx_cc/chainerx/native/reduce.h
Fixes https://github.com/chainer/chainer/issues/8072.
By the way, shouldn't `Cumsum` accept an `const OptionalAxes&` instead of an `optional<int8_t>` @asi1024 ?
> Fix `-Wbraced-scalar-init` for clang

- tests/chainer_tests/serializers_tests/test_hdf5.py
Always pass `mode` to `h5py.File`. 
There was a recent new release `2.10.0` of `h5py`, deprecating `mode=None`. Travis is currently failing because of this update.
> Explicit `h5py.File` `mode`

- tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py
This closes #6910.
- Fix `eps` handling.  The wrong tests (maybe from #7202) were unexpectedly passing because large `eps` was not tested.
- Make sure `rmax` and `dmax` are tested.
- Fix tolerances.
- Adjusting `atol` is preferred to adjusting `rtol` if forward of some normalization is tested.
- I confirmed the new tests pass with `@condition.repeat(3000)`.
- `testing.assert_allclose(actual, desired)` (due to `rtol`)
> Fix tests of `L.BatchRenormalization` and adjust tolerances

- tests/chainer_tests/test_variable.py
Close #8093.  `np.empty(...) * 2` may cause `RuntimeWarning: overflow encountered in multiply`
See also #5001, #6653.
> Fix flaky tests with `np.empty`

- chainer/initializers/constant.py
- tests/chainer_tests/test_variable.py
An alternative to https://github.com/chainer/chainer/pull/8043 on request per @toslunar.
> Correctly cast `fill_value` in constant initializer

- chainerx_cc/CMakeLists.txt
- chainerx_cc/chainerx/python/routines.cc
fixed #8084
to be conservative, instead of `add_definitions(-DCHAINERX_ENABLE_LAPACK=1)` in `CMakeLists.txt`, I remove `add_definitions(-DCHAINERX_ENABLE_LAPACK=0)` and add proper test in code.
> fix env CHAINERX_ENABLE_LAPACK=0 causes error

- docs/source/chainerx/install/index.rst
Fixes the position of an anchor.
As an example, try following [this link](https://docs.chainer.org/en/v7.0.0b3/chainerx/install/index.html#chainerx-install).
> Fix heading anchor in ChainerX docs

- .travis.yml
- scripts/ci/travis/run-step.sh
Travis CI doesn't have timestamps in log outputs (https://github.com/travis-ci/travis-ci/issues/4968)
It's difficult to tell how much time it takes in each command.
> Add timestamp to Travis CI log

- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
Some parameterizations were simply ignored.
> Avoid unnecessary test condition in `F.max_pooling_2d` test

- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
Fixes #7986 
Confirmed to pass 4,000 times
pytest --count=1000 unit_tests/routines_tests/test_linalg.py -k 'PseudoInverse and _param_3_'
> Fix matrix generation in linear algebra `PseudoInverse` test

- .pfnci/.gitignore
- .pfnci/config.pbtxt
- .pfnci/py27and35.Dockerfile
- .pfnci/py37.Dockerfile
- .pfnci/script.sh
This PR adds scripts to create base images used for Chainer CI. Chainer CI targets build Docker images using scripts out of Chainer repository.
This PR creates new 4 CI targets "chainer.docker.(py37|py27and35).(test|push)", but they will not be trigger automatically mainly because they take about ten minutes.
> Add scripts for Docker base images for Chainer CI

- chainer/function_node.py
- chainer/optimizer.py
- chainer/variable.py
- chainerx_cc/chainerx/backward.cc
- chainerx_cc/chainerx/backward.h
- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/backward.cc
- tests/chainer_tests/optimizer_hooks_tests/test_weight_decay.py
- tests/chainer_tests/test_function_node.py
- tests/chainer_tests/test_optimizer.py
- tests/chainer_tests/test_variable.py
Reworks #7763
Closes #7756
Instead of exposing a `loss_scale` attribute on Chainerx arrays. 
We do the loss scaling on the arrays that belong to input variables, parameters or must be explicitly retained at the end of the ChainerX backward pass.
> Loss scale support for chainerx 

- chainer/training/updaters/multiprocess_parallel_updater.py
When using MultiprocessIterator in conjunction with MultiprocessParallelUpdater
The iterators are not finalized on MultiprocessParallelUpdater.finalize method.
The iterator state is cleanup while the python process exits and the iterator internal state is now inconsistent. The iterator uses an internal thread that gets stuck and tries to perpetually join it 
deadlocking the execution.
> Fix deadlock on MultiprocessIterator and MultiprocessParallelUpdater

- chainerx_cc/chainerx/routines/arithmetic.cc
- chainerx_cc/chainerx/routines/arithmetic.h
Removes unused headers but I could be missing some.
> Remove unused headers in `arithmetic.{h,cc}`

- chainer/testing/random.py
- tests/chainerx_tests/op_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_rnn.py
Allow the `fix_random` decorator to be used with `OpTest`. It was previously not possible.
The motivation behind this PR is to allow flaky tests (in particular https://github.com/chainer/chainer/issues/8032 and https://github.com/chainer/chainer/issues/8033) to have their seeds fixed. I'll send a separate PR to addressed these tests.
> Allow `fix_random` decorator to be used with `OpTest`

- chainer/testing/random.py
- tests/chainerx_tests/unit_tests/routines_tests/test_rnn.py
Fixes https://github.com/chainer/chainer/issues/8032 and https://github.com/chainer/chainer/issues/8033 (cc. @kmaehashi) by fixing random seeds.
The cause of the flakiness was due to inputs to the ReLU activation values close to 0 while the non-differentiable point detection failed to get around this, so we decided to just fix the seed for now.
Depends on https://github.com/chainer/chainer/pull/8136.
> Fix flaky `NStepRNN` and `NStepBiRNN`

- setup.cfg
~This will resolve #8123.~
This will resolve issues related to `import cupy` when testing Chainer with `pytest`. (#8138)
> Add `ignore::ImportWarning` to `setup.cfg`

- chainerx/_docs/routines.py
It is supposed that the following note in the documentation of `chainerx.maximum` is obsolete:
> Note:
> maximum of ndarray and ndarray is not supported yet.
> Remove obsolete note in `chainerx.maximum` doc

- chainerx/_docs/routines.py
- docs/source/chainerx/reference/routines.rst
This PR adds the missing documentation for `chainerx.minimum` .
> Add documentation for `chainerx.minimum`

- chainer/testing/__init__.py
- chainer/testing/matrix.py
- tests/chainer_tests/testing_tests/test_matrix.py
This PR adds a helper function for testing numerical functions that are sensitive to singular values (e.g. linalg functions). See the docstring for the interface and specification.
I'm planning to use this function in #7997 and some other flaky test fixes. The design and implementation are influenced by some existing tests that generate such matrices, e.g. #7900, https://github.com/cupy/cupy/pull/2084.
Comments and suggestions are welcome.
> Add `testing.generate_matrix` to get matrices of given singular values

- tests/chainer_tests/functions_tests/array_tests/test_cast.py
> Avoid `empty` in `F.cast` test that can cause overflow warning

- tests/chainerx_tests/conftest.py
- tests/chainerx_tests/unit_tests/routines_tests/test_logic.py
Separated from #8082
* Make the test order deterministic
* Make the string representations of tests (= test parameters) deterministic
> Make xdist usable in ChainerX tests

- chainer/functions/normalization/batch_normalization.py
This PR fixes a bug in cupy
elementwise of batch_normalization by assign different dtypes to mean
and var. 
This close #8148
> Fix bugs in cupy elementwise in batch_normalization

- setup.cfg
Follow the style
```
[pytest]
filterwarnings =
error
ignore::UserWarning
```
in https://docs.pytest.org/en/latest/warnings.html.
After the fix, I expect less number of editors will insert tabs by default.  (See also #8154)
> Fix style of `setup.cfg`

- tests/chainer_tests/iterators_tests/test_iterator_compatibility.py
- tests/chainer_tests/iterators_tests/test_multiprocess_iterator.py
- tests/chainer_tests/iterators_tests/test_multithread_iterator.py
- tests/chainer_tests/iterators_tests/test_serial_iterator.py
Chainer `DictionarySerializer` and `NpzDeserializer` offer the same functionality as the `DummySerializer` and `DummyDeserializer` used in the iterators test code.
> Remove `DummySerializer` and  `DummyDeserializer` from `iterators_tests`

- chainer/testing/matrix.py
- tests/chainer_tests/testing_tests/test_matrix.py
I found in #7997 that `generate_matrix` fails to generate zero-sized matrices with NumPy<=1.15. Zero-sized shapes are tested in various functions, so it's convenient to support them in `generate_matrix`. I will use this fix in #7997.
> Support zero-sized matrix in `generate_matrix`

- tests/chainer_tests/functions_tests/math_tests/test_basic_math.py
Fixes #8094
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/341/TEST=chainer-py3,label=mn1-p100/
>`FAIL tests/chainer_tests/functions_tests/math_tests/test_basic_math.py::TestVariableConstantArrayOp_param_0_{dtype=float16}::test_div_backward_cpu`
```
18:34:08 E       RuntimeWarning: Parameterized test failed.
18:34:08 E       
18:34:08 E       Base test method: TestVariableConstantArrayOp.test_div_backward_cpu
18:34:08 E       Test parameters:
18:34:08 E         dtype: <class 'numpy.float16'>
18:34:08 E       
18:34:08 E       
18:34:08 E       (caused by)
18:34:08 E       RuntimeWarning: overflow encountered in true_divide
```
> Fix overflow warning in div backward test

- .pfnci/hint.pbtxt
- tests/chainer_tests/functions_tests/evaluation_tests/test_accuracy.py
Close #7819.
It's unlikely for `TestAccuracy` to fail with only a few testing parameters, because the implementation of `F.accuracy` is not complicated.
> Fix `TestAccuracy`: Randomly reduce testing parameters

- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Attempts to fix https://github.com/chainer/chainer/issues/8145.
I can not reproduce this backward test failure locally but it has now occurred twice in our CI. I choose to relax the tolerances to be identical to that of the forward test (they used to be 10 times smaller utilizing the default values of `check_backward`). This should've at least made the two failing tests to pass. Again, I have not been able to verify the change in failure rates locally.
> Relax `BatchNormalization` backward test tolerances

- chainermn/links/batch_normalization.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
- tests/chainermn_tests/datasets_tests/test_mnist.py
- tests/chainermn_tests/extensions_tests/test_allreduce_persistent.py
- tests/chainermn_tests/extensions_tests/test_observation_aggregator.py
- tests/chainermn_tests/functions_tests/test_point_to_point_communication.py
- tests/chainermn_tests/links_tests/test_batch_normalization.py
- tests/chainermn_tests/links_tests/test_create_mnbn_model.py
- tests/chainermn_tests/links_tests/test_multi_node_chain_list.py
- tests/chainermn_tests/links_tests/test_n_step_rnn.py
- tests/chainermn_tests/optimizer_tests/test_double_buffering_optimizer.py
- tests/chainermn_tests/optimizer_tests/test_multi_node_optimizer.py
This PR contains two fixes for ChainerMN to pass the CI tests.
1. A bug fix in the `batch_normalization`, from `copy` to use `__deepcopy__` to match the behavior of `chainer`.
2. Replace all the deprecated `to_gpu` to `to_device` in all the tests
> Bug Fix: "copy" => "__deepcopy__" in ChainerMN "batch_normalization" & replace "to_gpu"

- tests/chainer_tests/serializers_tests/test_hdf5.py
Fixes #8181 
Succeeded 100,000 times without a failure.
> Fix comparison with casting in hdf5 serializer test

- chainer/testing/condition.py
- tests/chainer_tests/testing_tests/test_condition.py
> Allow `pytest.skip()` in combination with `testing.repeat`/`retry`

- chainermn/extensions/__init__.py
- chainermn/extensions/_multi_node_snapshot.py
- docs/source/chainermn/reference/index.rst
- tests/chainermn_tests/extensions_tests/test_multi_node_snapshot.py
Addresses https://github.com/chainer/chainer/issues/7947 . We'll deprecate multi-node checkpointer we already have, once this PR is merged.
Basic design is to let users define replica sets, which is supposed to be same, typically models or trainers in data-paralellism. But we often define rank 0 process' trainer as special trainer to inject observability extensions such as LogReport, PrintReport - which makes the trainer a bit different from those in other ranks. In that case, the most typical use case, the replica sets are defined as `[0,]` mentioning `0` as explicit replica set and the remaining `1..comm.size`as implicit replica set.
Then the wrapped snapshot object is only called at rank 0 and 1 (minimal number in the latter set), names suffixed with its rank numbers e.g. …
> More efficient multi-node snapshot

- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
Fix #7976.
~Note on the solution: the test case sometimes result in an output matrix with very large values, where the computational error exceeds the threshold by a large margin. Instead of increasing the threshold (which will make the most random cases meaningless), I changed the input generation to generate the output instead of input so that we can control the output scale.~
Update: following the comments from @asi1024, I understood that the problem is not solved essentially by the above method. I developed a tool to create a well-behaving matrix in #8077, and rewrote this PR using it.
> Fix flaky tests of `chx.linalg.solve`

- chainerx_cc/CMakeLists.txt
Potentially save developer from preprocessing error due to macro expansion when accidentally include `windows.h`, e.g. `nvToolsExt.h` will do this.
> Add `WIN32_LEAN_AND_MEAN` definition

- chainer/distributions/cauchy.py
[The Cauchy distribution page]((https://docs.chainer.org/en/stable/reference/generated/chainer.distributions.Cauchy.html)) does not show the $x_0$ correctly due to the typo.
So I fixed it. By applying this PR, the page shows it correctly:
> Fix a typo in the Cauchy distribution page

- chainer/distributions/cauchy.py
> [backport] Fix a typo in the Cauchy distribution page

- setup.py
Just left comments for Read the Docs related paths in the setup script where code might not be obvious.
> Write Read the Docs related comments in setup.py

- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- chainerx_cc/chainerx/cuda/cuda_device/rnn.cu
- chainerx_cc/chainerx/kernels/normalization.h
- chainerx_cc/chainerx/kernels/pooling.h
- chainerx_cc/chainerx/kernels/rnn.h
- chainerx_cc/chainerx/routines/normalization.cc
Following practices to avoid object slicing.
> Delete move and copy of virtual `*GradState` classes

- chainer/functions/array/resize_images.py
Recently, a nearest mode was added to `resize_images`: https://github.com/chainer/chainer/commit/f8b3524a983b7785e90e7cb25e54e27f154b1dee
The function documentation should reflect this.
> Fix resize_images documentation to reflect recent code changes

- tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py
Fixes https://github.com/chainer/chainer/issues/8145 (reopened by https://github.com/chainer/chainer/issues/8145#event-2676456289).
Inherently flaky test parameterizations introduced in https://github.com/chainer/chainer/pull/8175/files#diff-73bf7ec0733e38d72fc70a0850f9d5a3R62-R63 are fixed.
> Fix flaky `TestBatchNormalization`

- tests/chainer_tests/serializers_tests/test_hdf5.py
Chainer is tested with h5py>=2.5.
https://github.com/chainer/chainer-test/blob/b1b40421a2d7c73b86590575b19b82c801a12778/run_combination_test.py#L21
#8182 uses a feature of h5py>=2.9 (h5py/h5py#1061).
> Fix `HDF5Serializer` test for h5py<2.9

- chainer/_runtime_info.py
> [backport] Display ChainerX availability in `print_runtime_info`

- chainerx/_docs/routines.py
It looks that the documentation for the loss functions are missing in the ChainerX reference.
https://docs.chainer.org/en/v7.0.0b4/chainerx/reference/routines.html#loss-functions
> Set up documentation for loss functions in ChainerX

- tests/chainerx_tests/math_utils.py
Fixes  #7737
Tested with the same parameters as https://github.com/chainer/chainer/issues/7737#issuecomment-535459958 for 38277 times in a row without a failure.
> Relax tolerances in ChainerX unary math tests

- chainerx/_docs/routines.py
This PR adds the missing documentation for `chainerx.ravel`.
https://docs.chainer.org/en/v7.0.0b4/chainerx/reference/routines.html#array-manipulation-routines
> Add documentation for `chainerx.ravel`

- chainerx_cc/chainerx/cuda/cuda_device.cc
- chainerx_cc/chainerx/cuda/cuda_device.h
`std::queue::empty()` is not thread safe.
> Fix possible data race in CUDA memory keeper

- chainerx_cc/CMakeLists.txt
- chainerx_cc/chainerx/CMakeLists.txt
- chainerx_cc/examples/CMakeLists.txt
External libraries (e.g. abseil) can emit compiler warnings.
This fix prevents such warnings from being errors.
> Suppress warnings-as-errors from external libraries

- tests/chainerx_tests/unit_tests/routines_tests/test_math.py
> [backport] Relax tolerances in ChainerX unary math tests

- chainerx_cc/chainerx/native/native_device/cblas.h
https://clang.llvm.org/extra/clang-tidy/checks/readability-avoid-const-params-in-decls.html
> Conform to readability-avoid-const-params-in-decls

- chainerx_cc/CMakeLists.txt
Writes the name of the CMake generator when building. Could be friendly when testing alternative generators (c.f. https://github.com/chainer/chainer/pull/8194).
> Write CMake generator when building

- chainerx_cc/chainerx/device.h
- chainerx_cc/chainerx/kernels/pooling.h
`AveragePoolPadMode` was no longer used in `device.h`.
> Remove unused forward declaration of `AveragePoolPadMode` enum

- chainerx_cc/scripts/run-clang-format.sh
Since its expected in CI and in ubuntu 18.04 it can be installed as clang-format-6.0
https://github.com/chainer/chainer/blob/d0cfc08d64cd63c40a745501b1a9e05502bdfaba/scripts/ci/chainerx/setup-ubuntu.sh#L8
> Use clang-format-6.0 if possible and track the version of clang-format

- tests/chainermn_tests/links_tests/test_multi_node_chain_list.py
This commit removes the lagacy filters.
This closes #8245
> Remove legacy DeprecationWarning filter from `test_multi_node_chain_list`

- tests/chainermn_tests/links_tests/test_n_step_rnn.py
This commit adds the fp16 tests to the n_step_rnn tests.
The chainer.testing is used to parameterize and switch between the
float16 and float32.
The old `chainer.cuda` is replaced with `chainer.backends.cuda`
> Add fp16 test to `test_n_step_rnn`

- chainerx/_docs/routines.py
- docs/source/chainerx/reference/routines.rst
This PR adds ``chainerx.sigmoid_cross_entropy``'s missing documentation.
> Add documentation for ``chainerx.sigmoid_cross_entropy``

- tests/chainer_tests/serializers_tests/test_hdf5.py
> [backport] Fix `HDF5Serializer` test for h5py<2.9

- chainer/functions/loss/softmax_cross_entropy.py
This PR removes a comment in `F.softmax_cross_entropy`, which looks obsolete and makes no sense now:
https://github.com/chainer/chainer/blob/5ea0cd395e02f2a190408f446f90657d4374a506/chainer/functions/loss/softmax_cross_entropy.py#L147
It is supposed that it was originally introduced at https://github.com/chainer/chainer/commit/bc0409074645809e2ccabdfb131df527569d9a41#diff-b795608ebf49fbc4e2379c9f44daa1d6R46 to note why getting `normalize` attribute with `getattr()`.
> Remove obsolete comment in `F.softmax_cross_entropy`

- chainermn/communicators/_memory_utility.py
- chainermn/extensions/multi_node_evaluator.py
- examples/chainermn/mnist/train_mnist.py
This PR implements ChainerMN on ChainerX integration.
With this PR, the MNIST example works on ChainerX.
Note that you need to set the following environmental variables when you install Chainer fro m source to activate ChainerX.
```
export CHAINERX_BUILD_CUDA=1
export CHAINERX_ENABLE_BLAS=1
export CHAINER_BUILD_CHAINERX=1
```
```
export MAKEFLAGS=-j16
```
is also helpful.
> ChainerX + ChainerMN integraiton on MNIST

- chainerx_cc/chainerx/cuda/cuda_backend.cc
- chainerx_cc/chainerx/cuda/cuda_backend.h
- chainerx_cc/chainerx/native/native_backend.cc
- chainerx_cc/chainerx/native/native_backend.h
Static variables in headers will be unique symbols, which are
shared among multiple shared objects. This means you cannot
load multiple shared objects which are linked against
ChainerX since kernel registrations in the second shared
object will fail due to the dup kernel detection.
It would be better to get rid of unique symbols created in
reduce.cuh (kMaxBlockSize), but this would be safer since this
is a constant value.
> Do not expose global_kernel_registry

- chainer/_environment_check.py
The steps described in the message was insufficient to build a correct CuPy installation.
Users need to uninstall all of them first.
> Fix CuPy installation detection error message

- chainer/variable.py
Introduced in #7670
`axis` is left because it's common to give the corresponding argument in `numpy.mean` as positional.
> Make `weights` and `keepdims` arguments in `Variable.mean` keyword-only

- chainer/link_hooks/weight_standardization.py
> Make arguments of `WeightStandardization` keyword-only

- tests/chainer_tests/functions_tests/math_tests/test_scale.py
Simplifies `test_scale` using `testing.FunctionTestCase`
solves part of issue #6071
> Simplify `F.scale` test

- .github/ISSUE_TEMPLATE.md
- README.md
- docs/source/index.rst
Old Slack invitation links had expired for some reason.
Replacing it with new `bit.ly` link which redirects to GitHub Pages (repo: https://github.com/chainer/join-slack), which then automatically redirects to the actual invitation page.
The invitation link should "never expire" (according to Slack), but to detect accidental expiration, inviation links are now tested in https://travis-ci.org/chainer/join-slack as well.
> Replace Slack invitation links

- chainer/gradient_check.py
Based on #8236
Simplifies the implementation of direction vector sampling in `gradient_check`, by avoiding repeated loops.
> Simplify direction vector sampling in `gradient_check`

- chainer/training/trainer.py
> Make `call_before_training` argument of `Trainer.extend` keyword-only

- chainer/dataset/tabular/from_data.py
> Make `size` argument of `tabular.from_data` keyword-only

- chainermn/extensions/multi_node_early_stopping_trigger.py
- chainermn/extensions/observation_aggregator.py
> Make arguments in `ObservationAggregator` and `MultiNodeEarlyStoppingTrigger` keyword-only

- chainermn/datasets/scatter.py
> Make `force_equal_length` argument in `scatter_dataset` and `scatter_index` keyword-only

- chainer/backend.py
- chainer/backends/_chainerx.py
- chainer/backends/cuda.py
- chainer/device_resident.py
- chainer/function.py
- chainer/initializer.py
- chainer/initializers/__init__.py
- chainer/link.py
- chainer/link_hook.py
- chainer/links/connection/linear.py
- chainer/testing/parameterized.py
- chainer/types.py
- chainer/variable.py
- chainermn/communicators/communicator_base.py
- docs/source/_napoleon_patch.py
Close #8240.
[edited: 2019/10/08] I revised module list by running following command.
`grep -v "=.\+# type: " **/*.py| grep "# type: "`
This intended to exclude variable annotations. (https://github.com/chainer/chainer/pull/8248#issuecomment-538743366)
<details>
```
chainer/backend.py:    # type: (types.DeviceSpec) -> Device
chainer/backends/_chainerx.py:        # type: (chainerx.Device) -> None
chainer/backends/cuda.py:    from cupy import ndarray  # type: ignore # NOQA
chainer/backends/cuda.py:    from cupy.cuda import Device  # type: ignore # NOQA
chainer/backends/cuda.py:    from cupy.cuda import Event  # type: ignore # NOQA
chainer/backends/cuda.py:    from cupy.cuda import Stream  # type: ignore # NOQA
chainer/backends/cuda.py:    class ndarray(object):  # type: ignore # for type …
```
> Use type hint for method declaration

- README.md
`pip install cupy` is not recommended for general users.
> Put a link to CuPy installation guide in README instead of a command instruction

- tests/chainer_tests/functions_tests/math_tests/test_scale.py
- tests/chainer_tests/functions_tests/noise_tests/test_zoneout.py
Backprop tests have little benefit to specify small tolerances because numerical computation of gradients is not necessarily accurate.
> Stop setting too small tolerances in backprop tests

- onnx_chainer/export.py
When update onnx 1.6, exporting with `input_shapes` does not work. `onnx.shape_inference.infer_shape` does not allow output `Type` is cleared, and emits `TypeInferenceError`. To resolve it, exporting clears dimension information instead of `Type`.
[before]
```
>       inferred_model_str = C.infer_shapes(model_str)
E       RuntimeError: Parameterized test failed.
E
E       Base test method: TestCustomizedInputShape.test_output
E       Test parameters:
E         shape_option: ('N', 3, 28, 28)
E         x_shape: (10, 3, 28, 28)
E
E
E       (caused by)
E       RuntimeError: [TypeInferenceError] type case mismatch. existing=0 inferred=1
```
[after]
> Fix dim clearing on output

- .pfnci/hint.pbtxt
- chainer/testing/parameterized.py
- scripts/ci/travis/steps.sh
- tests/chainer_tests/conftest.py
- tests/chainerx_tests/conftest.py
- tests/conftest.py
See #8210
Adding `CHAINER_TEST_PAIRWISE_PARAMETERIZATION` environment variable and only set it to `always` in Travis CI.
> Add `CHAINER_TEST_PAIRWISE_PARAMETERIZATION` and enable it only in Travis CI

- chainerx_cc/CMakeLists.txt
- chainerx_cc/third_party/abseil.cmake
- chainerx_cc/third_party/gsl-lite.cmake
- chainerx_cc/third_party/gtest.cmake
- chainerx_cc/third_party/pybind11.cmake
Previously, in #7966, there is an attempt to fix gtest crt linkage. It just don't work actually, it 'fixed' it simply by accident.
1. In those `chainerx_cc/third_party/*.cmake` files, the configure stage is disabled since the configure command is set to an empty string.
2. according to [add_subdirectory](https://cmake.org/cmake/help/v3.15/command/add_subdirectory.html) doc
> The CMakeLists.txt file in the specified source directory will be processed immediately by CMake before processing in the current input file continues beyond this command.
the `${CMAKE_CURRENT_BINARY_DIR}/googletest-src` is added first and then followed with a `set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)`. So, on the first pass of configure-build (trigged by setup.py), crt error, on the second pass, it …
> fix gtest linkage weirdness

- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/device.h
- chainerx_cc/chainerx/python/routines.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
When is device=None.
closes #8259
> Inherit input ndarray device in chainerx.ascontiguousarray

- chainer/functions/normalization/batch_normalization.py
There are two kinds of intel64 support:
- to use intel64 routine; and
- not to be broken with other intel64 enhancements.
https://github.com/chainer/chainer/pull/8175/files#r329861075 missed the latter point.  For example, backward of `h = bn(x); y = F.relu(h)` may give `isinstance(h.grad, intel64.mdarray)` even if `x.array` is not.
Nonetheless `astype` can be avoided.
By the way,
- `_BNMode.can_use_ideep` has been too strict from #6456.  `intel64.inputs_all_ready` checks `x.dtype` but it seems intended to use intel64 if `(x.dtype, gamma.dtype) == (float16, float32)`.  https://github.com/chainer/chainer/blob/4f4dda143fafccd914345ac28d750f5be1a99ef8/chainer/functions/normalization/batch_normalization.py#L634
- I don't fix this issue in this PR.
- #8175 correctly fixed the condition for …
> Fix intel64 support of `F.batch_normalization`

- chainer/functions/loss/negative_sampling.py
Fix #8289.
`F.negative_sampling` includes reduction operations, which lose accuracy when the inputs are fp16. In this PR, `F.negative_sampling` is fixed to use fp32 for computation. The flaky test then passed for 100k times repeats.
> Compute `F.negative_sampling` in fp32 for fp16 inputs

- chainer/functions/loss/softmax_cross_entropy.py
- tests/chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py
`F.softmax_cross_entropy` with ChainerX ndarrays used to return wrong results when called with default arguments (`reduce='mean'`, `normalize=True` and `ignore_label=-1`) with ignored labels in the target `t`. The issue was that `normalize` was not accounted for. This PR fixes this issue and addresses some TODOs.
> Fix SCE with ChainerX and normalize

- .pfnci/hint.pbtxt
#7670 roughly doubled the number of testcases in `test_average` and #8211 disabled pairwise testing in FlexCI.
I found the failure in https://ci.preferred.jp/chainer.py27and35.gpu/35308/
<details>
```
2019-10-17 16:01:32.581641 STDOUT 2318] 	[SUCCESS] /chainer/tests/chainer_tests/training_tests/updaters_tests/test_standard_updater.py (221 passed, 37 deselected in 4.18 seconds)
2019-10-17 16:01:32.628795 STDOUT 2318] 	[TIMEOUT] /chainer/tests/chainer_tests/functions_tests/math_tests/test_average.py (60 seconds)
2019-10-17 16:01:32.628820 STDERR 2318] 	[DEBUG] failed to wait a command: python3.5 -m pytest -m not slow and (gpu or cudnn or cuda) /chainer/tests/chainer_tests/functions_tests/math_tests/test_average.py: signal: killed
2019-10-17 16:01:32.628801 STDOUT 2318] …
```
> `test_average` is slow in FlexCI

- .pfnci/config.pbtxt
- .pfnci/run.sh
- chainermn/testing/device.py
- setup.py
- tests/chainermn_tests/testing_tests/test_device.py
This PR fixes a bug in the `get_device` in `chainermn.testing`,
which uses native when specifying to use gpu with `gpu_id=0`,
as the `0` is considered as `False` in `if`.
This PR also includes a unit test for the `chainermn.testing`, as well as installing ChainerX in the `chainermn-cpu` and `chainermn-gpu` tests.
The time limit for both tests are increased as the building with chainerx takes too much time, and to match with other chainer tests.
> Bugfix: unable to use `gpu_id=0` in ChainerMN testing `get_device`

- tests/chainermn_tests/datasets_tests/test_mnist.py
This PR adds ChainerX tests for both cpu and gpu to the mnist tests.
A little code cleanup is also included.
This PR depends on #8304, and should be merged after it.
This PR resolves the `test_mnist` case in #8031.
> Add ChainerX to test_mnist in chainermn_tests

- chainerx_cc/chainerx/backward.cc
Fixes #8050 
Simplify subgraph construction in ChainerX and fix a failure for when intermediate arrays also appeared as output in `chainerx::Grad`.
> Fix subgraph construction for ChainerX backward

- chainerx_cc/chainerx/backward.cc
`forward_op_nodes` does not have to know whether a node is in `outputs`.  
Close #8050.  See also #8049.
> Simplify `CreateSubgraph`

- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
Thanks to @shinh for the implementation.
Before:
0.09902286529541016
After:
0.0009851455688476562
> Make contiguous case for `chainerx::Take` faster

- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
Reworked it similar to #8295 
IndexableArrays uses the 1D specialized template whenever it is possible.
For 40 runs of a pathological case, execution time decreased from 0.18 seconds to 0.02
Please note that `addat` is not currently exposed to the python API.
```python
def bench(name, ary_fn):
np.random.seed(42)
x = np.zeros((20, 96, 132)).astype(np.float32)
y = np.random.rand(20, 96, 36, 11).astype(np.float32)
indices = np.random.randint(132, size=(36, 11)).astype(np.int32)
a = chx.array(x, device='cuda:0')
b = chx.array(y, device='cuda:0')
indices = chx.array(indices, device='cuda:0')
for i in range(10):
cuda = chx.addat(a,indices,b,axis=2)
cupy.cuda.device.Device().synchronize()
start = time.time()
for i in range(40):
cuda = chx.addat(a,indices,b,axis=2) …
```
> Make contiguous case for `chainerx::AddAt` faster

- chainerx/_docs/routines.py
An alternative to https://github.com/chainer/chainer/pull/8306, keeping the current gradient behavior but document it instead.
> Document properties of computed gradients in `cholesky` and `eigh`

- tests/chainerx_tests/unit_tests/routines_tests/test_loss.py
Closes #8315
This patch sets the same tolerances of `LossBase` for `SoftmaxCrossEntropy` 
Before the patch 2,500 Failures every 10,000 runs.
The real reason behind the test failures seems to be #7991, but we don't have a mechanism to avoid precision loss on intermediate calculations.
> Adjust `SoftmaxCrossEntropy` test tolerances

- docs/source/onnx_chainer/introduction/index.rst
This PR fixes typos in `docs/source/onnx_chainer/introduction/index.rst`.
> Fix typos in ONNX-Chainer introduction

- onnx_chainer/functions/array.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
This PR fixes `IndexError: list index out of range` when the `Separate` node has only single output.
> Fix onnx_chainer's exporter of Separate to handle single output case

- chainer/links/rnn/n_step_gru.py
This PR fixes documentation of `chainer.links.NStepGRUBase.`
`NStepRNN` and `NStepBiRNN` here should be `NStepGRU` and `NStepBiGRU` respectively.
> Fix documentation of NStepGRUBase

- chainerx_cc/chainerx/array.h
- chainerx_cc/chainerx/array_index.h
- chainerx_cc/chainerx/routines/indexing.h
Allows the examples to be built
Closes #8276
> Default index mode for chainerx `Take`

- chainermn/extensions/observation_aggregator.py
- tests/chainermn_tests/extensions_tests/test_multi_node_early_stopping_trigger.py
This PR adds ChainerX tests into the `multi_node_early_stopping`. 
This PR solve part of #8031
> Add ChainerX pytest in `multi_node_early_stopping`

- tests/onnx_chainer_tests/functions_tests/test_loss.py
latest ONNXRuntime supports float type inputs (ref:https://github.com/microsoft/onnxruntime/issues/1537) on OntHot, don't have to skip them.
> Revert output value check on SoftmaxCrossEntropy

- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
Fixes #8237 (forward test)
Runs 100,000 times without a failure.
> Relax tolerances of ChainerX linalg forward tests

- tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
It seems `chainer.testing.LinkTestCase` supports backprop test with higher-prec `dtype` by overwriting parameters.  Use it and close #6911.
> Use `LinkTestCase` for `L.GroupNormalization`

- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
~Probably this fixes  #8268.  (Reopen the issue later if it does not.)~
This PR reduces the failure rate of `test_Meshgrid`.
The outputs are six arrays of the shape `(6, 5, 3, 3, 6, 3)`, which seems too big to test backward with `float16`, in the failed example.
> Fix test_Meshgrid

- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
I don't know there's a special reason to test (6, 6) in addition to (3, 3).
Reducing it for (possibly)
* Shorter test runtime
* Ease of investigation in case of failure
* Numerical stability
> Reduce shape in ChainerX linalg test

- chainer/functions/evaluation/accuracy.py
Current F.accuracy with `ignore_label` implementation requires host-side branch `if total == 0`.
This causes unnecessary sync between forward and backward computation.
By this PR, we can avoid this synchronization so it can accelerate CPU-intensive model training (i.e. Mixed-precision training)
I've tried the Advanced Indexing feature, but it cannot help.
> Remove host-side branch on `F.accuracy` with `ignore_label`

- chainer/functions/normalization/batch_normalization.py
> Fix ChainerX fallback condition in batch normalization

- scripts/ci/chainerx/jenkins/run.sh
> Set CHAINER_CI in ChainerX tests in Jenkins

- chainerx_cc/chainerx/routines/indexing.cc
- chainerx_cc/chainerx/routines/indexing.h
- Throw exceptions instead of assertion
- Fix function comment
- Rename `AddAt` as a backward of `At` to `AtGrad`, as it's confusing that
the two functions have the same name.
> Enhance `chainerx::AddAt` as a public function

- chainerx_cc/chainerx/array.h
- chainerx_cc/chainerx/backward.cc
- chainerx_cc/chainerx/backward.h
- chainerx_cc/chainerx/python/array.cc
- chainerx_cc/chainerx/python/array.h
- chainerx_cc/chainerx/python/axes.h
- chainerx_cc/chainerx/python/backward.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/routines/creation.cc
- chainerx_cc/chainerx/routines/creation.h
- chainerx_cc/chainerx/routines/evaluation.cc
- chainerx_cc/chainerx/routines/evaluation.h
- chainerx_cc/chainerx/slice.h
* Member type of `std::initializer_list` does not have to be `const`.
* `absl::optional` of lightweight types should be passed by value.
> C++ cosmetic fixes

- chainerx_cc/CMakeLists.txt
Currently only one `--generate-code` option can be given by `CHAINERX_NVCC_GENERATE_CODE`.
This PR allows multiple codes, delimited by semicolons.
> Allow multiple code in `CHAINERX_NVCC_GENERATE_CODE`

- chainerx_cc/chainerx/float16.cc
- chainerx_cc/chainerx/float16_test.cc
Closes  #8366 
When casting a Chainerx array in the native backend to float16 the float16 code differs subtly from the numpy one in the rounding of elements. 
https://github.com/numpy/numpy/blob/1f8fb2ca31a7f41a23c60e4ffcb38b3e0cb201f7/numpy/core/src/npymath/halffloat.c#L339-L347
This caused the IRemainder test to yield 150 failures for 1 million runs.
After fixing the number went down to 0.
The fp64 to fp16 case has been similarly fixed to match the numpy logic as some of the calculations were different and it was not clear where did they come from.
> Fix rounding on float16 conversions

- setup.py
Was packaging this for nixpkgs and noticed some odd import behaviors.
`typing` package is a backport and doesn't need to be imported for python>=3.5
see https://github.com/python/typing/issues/573
> Remove typing requirement

- chainerx_cc/chainerx/routines/linalg.h
- tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py
Avoid using `forward_accept_errors` and replace them with `pytest.raises` for the negative tests for the `chainerx.linalg` routines.
Also added some missing tests and removed seemingly redundant parameterizations. 
C.f. https://github.com/chainer/chainer/issues/6764#issuecomment-548729290 and https://github.com/chainer/chainer/issues/8362.
> Fix negative tests for `chainerx.linalg.*`

- onnx_chainer/functions/pooling.py
Currently ONNX-Chainer uses a trick on `max_pool_nd(2d)` converter with `cover_all=True`. From opset=11, `MaxPool` operator supports `ceiling_mode` to follow the extrapolation.
> Use ceiling_mode on exporting to ONNX MaxPool

- chainer/functions/connection/convolution_2d.py
- chainer/functions/connection/deconvolution_2d.py
Currently `Convolution2DGradW` uses `VariableNode` to retrieve shape and dtype information of `W`, but it's not necessary.
> Avoid using `VariableNode` in `F.convolution_2d` backward implementation

- .travis.yml
- scripts/ci/travis/steps.sh
- scripts/ci/travis/xpytest-hint-chainerx.pbtxt
- Not applied to `chainer_test` because of an overhead.  Imports are not cached among files by `xpytest`.  The number of test files in `chainerx_test` is small.
- It seems Travis CI has 2 cores, but NumPy-heavy tests did not speed up by the condition: `--thread=2` and `OMP_NUM_THREADS=1`.
- Manual installation/upgrade is required because `xpytest` requires golang version >= 1.12, while Travis provides 1.11 unless the project is golang.
- See #8082 for the attempt with `pytest-xdist`.
> Use xpytest to parallelize tests

- .pfnci/config.pbtxt
- .pfnci/script.sh
This fixes the issue that CuPy master is used for Chainer v6 tests.
After this got merged, configure CuPy webhook to trigger https://ci.preferred.jp/chainer.docker.py25and35.push/ and https://ci.preferred.jp/chainer.docker.py37.push/ for `v6` branch.
> Use different docker image for each base development branch

- examples/seq2seq/README.md
Fix typo in `/examples/seq2seq/README.md` :D
> Fix typo in `/examples/seq2seq/README.md`

- .pfnci/config.pbtxt
* Copy configuration from master branch.
* Activate `chainer.py2.cv`, `chainer.py2.cv.gpu`, `chainer.py2.cv.examples` configurations (copy configuration from the default config) and enable `include_dot_git` for https://github.com/chainer/chainercv/pull/935 .
* Disable onnx-chainer related tests to avoid invoking them in v6.
See also: https://github.com/cupy/cupy/pull/2591
> [v6] Add missing FlexCI configurations

- examples/seq2seq/README.md
> [backport] Fix typo in `/examples/seq2seq/README.md`

- onnx_chainer/functions/pooling.py
- tests/onnx_chainer_tests/functions_tests/test_poolings.py
Support `cover_all=True` on Chainer's `Unpool2d`. Simply recalculate output size. Interpolation logic is differ between Chainer and ONNXRuntime, and output values checking is skipped.
> Support cover_all=True on Unpooling2D in exporting to ONNX

- chainer/functions/array/reshape.py
- docs/source/tips.rst
The documentation fix after #4680.
Error messages are not checked by default because of [`IGNORE_EXCEPTION_DETAIL`](https://docs.python.org/3/library/doctest.html#doctest.IGNORE_EXCEPTION_DETAIL) in [`doctest_default_flags`](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#confval-doctest_default_flags).
> Update expected messages of `type_check` errors

- .travis.yml
Since some API used in onnx package isn't available until 3.5.2
Rel:
- https://github.com/cython/cython/issues/1880
- https://github.com/pybind/pybind11/issues/314
> Change version of python in travis macos test

- README.md
As pointed out in https://github.com/chainer/chainer/pull/7956#issuecomment-523247129, Examples links to master branch even when a user is browsing other branch.
> Link to examples directory for the current branch

- chainer/functions/pooling/max_pooling_2d.py
- tests/chainer_tests/functions_tests/pooling_tests/test_max_pooling_2d.py
This PR fixes a bug found in #7923.  `v = maxval` was missing.  `master` branch is already fixed by #7939, which is confirmed by #8328, too.
> [v6] Fix kernel of double backward of max_pooling_2d

- chainerx_cc/chainerx/float16_test.cc
In some cases the suffix is needed to avoid a compiler warning: comparison between signed and unsigned integers.
> Add unsigned suffix in float16 test

- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
This function is unused since #8295 and  #8299
> Remove unused function

- tests/chainer_tests/testing_tests/test_function_link.py
> Use `fix_random` in xfail backward tests

- chainerx_cc/chainerx/backend_testdata/CMakeLists.txt
I think these are not necessary.
> Remove chainerx dependency from test backends

- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
- Make the input values and the output shape smaller to fix the flakiness of the test. (Fix #8268)
- Avoid builtin `random` because `numpy.random` is available.
> Fix `TestMeshgrid`

- tests/chainerx_tests/array_utils.py
- tests/chainerx_tests/unit_tests/routines_tests/test_indexing.py
Previously it was always an all-false array.
> Fix random condition in `chainerx.where` test

- tests/chainer_tests/functions_tests/math_tests/test_det.py
A test is preventing [a compatibility breaking CuPy PR](https://github.com/cupy/cupy/pull/2437) from being merged. This PR temporarily skips the test. The test should be updated to use the new interface introduced in this CuPy PR and then unskipped.
> Temporarily skip test that will break after CuPy #2437

- tests/chainer_tests/links_tests/normalization_tests/test_group_normalization.py
> [backport] Use `LinkTestCase` for `L.GroupNormalization`

- onnx_chainer/replace_func.py
This PR fixes `AttributeError` in `onnx_chainer.replace_func.WrappedFunctionNode.forward`.
The `self.name` is not defined and I assume that this is a mistake of `self.custom_function_node_name`.
> Fix AttributeError in WrappedFunctionNode.forward

- chainer/testing/random.py
- tests/chainerx_tests/op_utils.py
by adding method name arguments to `fix_random`.
> Avoid using private `_fix_random`

- chainerx_cc/CMakeLists.txt
Ignore unused function warnings in NVCC that comes from CUDA system headers.
It's not possible to ignore warnings selectively in system headers because CMake's CUDA module doesn't support `SYSTEM` specification for include directories (https://gitlab.kitware.com/cmake/cmake/issues/16464), so relevant warnings from all the sources are ignored.
> Ignore unused function warning in NVCC

- chainermn/communicators/mpi_communicator_base.py
- tests/chainermn_tests/communicator_tests/test_communicator.py
The chainerx array preserves device id inside, which will also be
pickled during the mpi communications and causes future errors.
This PR prevents such cases by raising ValueError when calling
`x_obj` with the chainerx array.
> Raise ValueError when calling `xxx_obj` with ChainerX array in ChianerMN

- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Like uninitialized parameters, uninitialized persistents have to be registered to `Link` for serialization. They cannot be class attributes because of `Link.to_device`.
Fix #8441.
> Register uninitialized persistents

- scripts/ci/travis/xpytest-hint-chainerx.pbtxt
To avoid test flakiness, all possibly slow tests have to be hinted.
Default timeout of xpytest is 60s.
Fix #8425.
> Annotate tests that usually run >30s

- onnx_chainer/replace_func.py
- tests/onnx_chainer_tests/test_replace_func.py
With the current implementation, `alt_func` is allowed to return a `dict`, but it is flattened into a tuple. For example, 
```python
def f(x):
return {"a": x+1, "b": x-1}
```
returns a `dict`, while `onnx_chainer.replace_func.fake_as_funcnode(f, 'F')` returns a tuple, so that the consumer of the result who expects `dict` does not work.
This PR fixes the problem by explicitly saving the structure as a skeleton and reconstructing original structure from the skeleton and flattened values.
As a side effect, not only a single level of `tuple`/`list`/`dict` but also arbitrary nesting of `tuple`/`list`/`dict` is allowed in return value.
> Fix onnx_chainer.replace_func.fake_as_funcnode to reconstruct return value structure

- chainerx_cc/chainerx/CMakeLists.txt
Just a DRY refactoring of `CMakeLists.txt`.
> Avoid repeatedly enumerating submodules

- chainerx_cc/chainerx/CMakeLists.txt
- chainerx_cc/chainerx/cuda/CMakeLists.txt
- chainerx_cc/chainerx/native/CMakeLists.txt
- chainerx_cc/chainerx/routines/CMakeLists.txt
- chainerx_cc/chainerx/testing/CMakeLists.txt
* Previously the `main` function was included in `chainerx` via `chainerx_testing`, if `CHAINERX_BUILD_TEST` was set. Removed `main` from `chainerx_testing`.
* Avoid referencing `gtest` multiple times.
* ChainerX submodules are included in `chainerx`. Removed redundancy.
* Use `CUDA_ADD_EXECUTABLE` instead of `add_executable` for `chainerx_cuda_test`.
> Fix ChainerX CMake test dependencies

- onnx_chainer/functions/__init__.py
- onnx_chainer/functions/array.py
- onnx_chainer/mapping.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
This PR adds `TransposeSequence` exporter to ONNX-Chainer
This exporter supports only limited cases where input or output length is 1.
> Add TransposeSequence exporter to ONNX-Chainer

- chainer/testing/parameterized.py
This is a tiny PR porting over a small change to parameterized test naming that I proposed in cupy/cupy#2633 (and at pytest-dev/pytest#6152).  If the object being parameterized has a `__name__` attribute string, then this will be used rather than falling back to the  `__repr__`.  Functions, classes and modules all have this attribute and it tends to make the parameterized test names more concise and readable.
As a specifc example, the cupy module's `__repr__` is quite long:
```
<module 'cupy' from '/home/lee8rx/miniconda3_ne...r/lib/python3.7/site-packages/cupy/__init__.py'>
```
whereas the `__name__` is just
```
cupy
```
> Use `__name__` attribute in parameterized test names when available

- chainer/function_node.py
- tests/chainer_tests/test_function_node.py
> Correct `FunctionNode.forward` output type message

- chainer/functions/loss/mean_absolute_error.py
- tests/chainer_tests/functions_tests/loss_tests/test_mean_absolute_error.py
Close #6702.
This PR fixes `F.mean_absolute_error` to use an intermediate dtype for FP16 inputs. `numpy.mean` is not used because old numpy does not use extra precision for FP16.
https://docs.scipy.org/doc/numpy-1.9.2/reference/generated/numpy.mean.html
https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.mean.html
> Use intermediate dtype in `F.mean_absolute_error` for FP16

- .travis.yml
The changes in #8361 to upgrade golang was dirty.
> Fix conflict between #8251 and #8361

- onnx_chainer/functions/__init__.py
- onnx_chainer/functions/array.py
- onnx_chainer/mapping.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
This Pull Request addresses #8449. The implementation encodes an equivalent of the following NumPy snippet:
```python
row_idxs = np.nonzero(np.ones(t.shape))[0]
n_cols = x.shape[1]
idxs = row_idxs * n_cols + t
output = np.ravel(x)[idxs]
```
I could have used [`Range`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Range) to create `row_idxs`, but found that some of other ONNX conversion tools out there have not supported it yet. So I settled on the sequence of [`ConstantOfShape`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConstantOfShape) followed by [`NonZero`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#nonzero) to create the indices.
I'm not sure if I correctly used `support` decorator. Among the ops used in the implementation, …
> Add support of SelectItem in ONNX-Chainer

- setup.cfg
This was preventing ChainerX from running with newer pytest versions
```
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parametrize_device_name - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
```
> Add `parametrize_device_name` to setup.cfg

- chainer/functions/__init__.py
- chainer/functions/math/cholesky.py
- docs/source/reference/functions.rst
- tests/chainer_tests/functions_tests/math_tests/test_cholesky.py
This PR aims to add Cholesky Decomposition as per the issue #1448 
Route taken to complete this feature -
> Add Cholesky Decompostion

- chainerx_cc/chainerx/cuda/cuda_device/batch_norm.cc
- tests/chainerx_tests/unit_tests/routines_tests/test_normalization.py
Takeover #8302 
Error only happened on the Debug version of ChainerX because of an assert that was doing a CUDNN call with an invalid shape.
> Support `chainerx.batch_norm` with 2D input on CUDA

- scripts/ci/steps.sh
`pip` hides installation log for `cmake`/`make` etc. by default.
> Enable verbose flag when installing chainer in Jenkins

- scripts/ci/steps.sh
> Avoid ChainerX slow tests in Jenkins

- onnx_chainer/functions/array.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
`GatherElements` is more intuitive for `F.select_item` converter, but remain current logic for some runtimes which not support `GatherElements` operator.
ref: https://github.com/chainer/chainer/pull/8450#issuecomment-555285981
> SelectItem using GatherElements for ONNX opset>=11

- chainerx_cc/chainerx/macro.h
- chainerx_cc/chainerx/python/CMakeLists.txt
- chainerx_cc/chainerx/python/array_index.cc
- chainerx_cc/chainerx/python/axes.cc
- chainerx_cc/chainerx/python/backend.cc
- chainerx_cc/chainerx/python/backprop_mode.cc
- chainerx_cc/chainerx/python/backward.cc
- chainerx_cc/chainerx/python/chainer_interop.cc
- chainerx_cc/chainerx/python/check_backward.cc
- chainerx_cc/chainerx/python/common_export.h
- chainerx_cc/chainerx/python/context.cc
- chainerx_cc/chainerx/python/core_module.cc
- chainerx_cc/chainerx/python/cuda/cuda_module.cc
- chainerx_cc/chainerx/python/device.cc
- chainerx_cc/chainerx/python/dtype.cc
- chainerx_cc/chainerx/python/error.cc
- chainerx_cc/chainerx/python/graph.cc
- chainerx_cc/chainerx/python/routines.cc
- chainerx_cc/chainerx/python/scalar.cc
- chainerx_cc/chainerx/python/shape.cc
- chainerx_cc/chainerx/python/slice.cc
- chainerx_cc/chainerx/python/strides.cc
- chainerx_cc/chainerx/python/testing/device_buffer.cc
- chainerx_cc/chainerx/python/testing/testing_module.cc
Instead of tweaking the default visibility (#5936), this PR applies `PYBIND11_EXPORT` to relevant classes, as suggested in https://github.com/pybind/pybind11/issues/1272#issuecomment-364132532.
> Use `PYBIND11_EXPORT` instead of visibility hack

- tests/chainer_tests/testing_tests/test_function_link.py
> [backport] Use `fix_random` in xfail backward tests

- chainerx_cc/chainerx/cuda/cuda_device/fill.cu
- chainerx_cc/chainerx/cuda/cuda_device/indexing.cu
- chainerx_cc/chainerx/cuda/cuda_device/pool.cu
- chainerx_cc/chainerx/cuda/cuda_device/rnn.cu
- chainerx_cc/chainerx/cuda/elementwise.cuh
- tests/chainerx_tests/unit_tests/test_array_index.py
Closes  #8385 
Changes had no measurable impact on smaller arrays Elementwise timing.
Native is not included in the tests since it takes several minutes.
> [RFC]Avoid overflow on index calculations when using large arrays

- tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py
Closes #7946
The reason behind the flakiness is the use of a numpy version < 1.17
1.17 fixed a bug in the float16 implementation.
What happens is that forward_expected is comparing all the backends against the cpu implementation using numpy. And when using CUDA the results in float16 might sightly differ in some corner cases dut to the cpu-gpu difference (numpy bug) in fp16 implementation. Other tests that rely on numpy for forward_expected are most likely to be affected by this.
This failure only happens with grouped convolutions.
> Skip some `Convolution2D` tests for older numpy versions

- scripts/ci/steps.sh
> [backport] Avoid ChainerX slow tests in Jenkins

- .travis.yml
Bumps Python v2 to 2.7.16 in the osx Travis config.
Some recent change to Travis macos image made v2.7.10 unable to be built.
> [v6] Fix Travis Openssl Error in OSX

- scripts/ci/chainerx/jenkins/Dockerfile.template
Use CuPy v6 branch in Chainer v6 ChainerX test
> [v6] Use CuPy v6 in ChainerX test in Jenkins

- chainer/optimizer_hooks/gradient_hard_clipping.py
Backport of #7760
It only does the relevant change to the hard clipping hook but leaves out the test refactoring.
I can include it if needed.
merge after #8377
> [backport] Fix `optimizer_hooks.GradientHardClipping` for scalar array

- chainerx_cc/chainerx/cuda/cusolver.cc
Seems `CUSOLVER_STATUS_IRS_*` is added but can't be handled in current code
> Add workaround for cuSolver 10.2's new enums

- tests/chainer_tests/distributions_tests/test_utils.py
> Fix flaky test of `_modified_xlogx`

- onnx_chainer/functions/array.py
- onnx_chainer/functions/normalization.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
From opset11, Slice operator supports step input. Along with, add to check opset version when using GatherND.
> Support step slicing on ONNX export

- tests/onnx_chainer_tests/test_replace_func.py
> Remove unnecessary export on ONNX replace function test

- tests/chainer_tests/functions_tests/math_tests/test_det.py
The compatibility issue with `cupy.linalg.det` is fixed by cupy/cupy#2660.
Supersedes #8444.
> Revert #8434

- tests/chainermn_tests/links_tests/test_create_mnbn_model.py
This PR is a part of #8031. It adds ChainerX tests to test_create_mnbn_model.py
> Add chainerx tests to test_create_mnbn_model

- tests/chainermn_tests/extensions_tests/test_checkpoint.py
This PR is a part of #8031. It adds ChainerX tests to test_checkpoint.py
> Add chainerx tests to test_checkpoint.py

- tests/chainermn_tests/datasets_tests/test_empty_dataset.py
- tests/chainermn_tests/datasets_tests/test_mnist.py
- tests/chainermn_tests/datasets_tests/test_scatter.py
This PR is a part of #8031. It adds ChainerX tests to `test_emtpy_dataset.py` and `test_scatter.py` that use numpy arrays.
> Add chainerx test to dataset_tests

- onnx_chainer/export.py
- onnx_chainer/functions/__init__.py
- onnx_chainer/functions/math.py
- onnx_chainer/mapping.py
- onnx_chainer/replace_func.py
- tests/onnx_chainer_tests/functions_tests/test_maths.py
Sign is not implemented as `FunctionNode` and ONNX-Chainer cannot convert such functions. This PR support them, at first support `sign`.
> Support sign function on exporting ONNX

- tests/chainermn_tests/extensions_tests/test_allreduce_persistent.py
This PR is a part of #8031. It adds ChainerX tests to `test_allreduce_persistent.py`.
> Add ChainerX test to test_allreduce_persistent.py

- tests/chainerx_tests/array_utils.py
Fixes https://github.com/chainer/chainer/issues/8274, https://github.com/chainer/chainer/issues/8032 and https://github.com/chainer/chainer/issues/8033.
The above issues address ChainerX n-step RNN flaky tests. They were once worked around by https://github.com/chainer/chainer/pull/8136 by fixing the random seeds. However, https://github.com/chainer/chainer/pull/8342 made these tests non-deterministic since it changed the default behavior of `array_utils.uniform` to create new random states instead of utilizing the previous NumPy global `numpy.random`. This PR makes the tests deterministic again by defaulting to `numpy.random`.
> Allow `array_utils.uniform` to be deterministic with `fix_random` by default

- tests/chainermn_tests/optimizer_tests/test_multi_node_optimizer.py
This PR adds chainerx tests into multi_node_optimizer in chainermn.
This PR solves part of #8031.
The test class is changed to inherit from `object` instead of `unitest.TestCase` to support `pytest.parametrize`
> Add chainerx tests into multi_node_optimizer

- .pfnci/config.pbtxt
- .pfnci/run.sh
* Sometimes test fails due to timeout. Changing deadline from 15 min to 20 min. https://ci.preferred.jp/chainer.py37.cpu/
* As observed in tests of https://github.com/chainer/chainer/pull/8360 (e.g. https://ci.preferred.jp/chainer.py27and35.gpu/47617/) build concurrency is too high and memory consuming. I talked with @asi1024 and adjusted build concurrency to `max(16, nproc)`.
> Adjust timeout and build memory usage in FlexCI

- chainer/functions/normalization/batch_normalization.py
- chainer/memory_layouts.py
- tests/chainer_tests/links_tests/normalization_tests/test_batch_normalization.py
Miss configuration in the tests made nhwc batchnorm test to use always cudnn.
There was a bug when using NHWC without cudnn due to doing reductions in the incorrect axes.
> Fix `BatchNormalization` for NHWC without cudnn

- chainer/functions/connection/convolution_2d.py
- chainer/links/connection/convolution_2d.py
- tests/chainer_tests/links_tests/connection_tests/test_convolution_2d.py
Convolution2d should not use `cudnn_fast` compute mode if cudnn is not enabled.
The changes required for this involve modifying `im2col` and `col2im` to support NHWC layout
The compute mode can only be checked at the link creation time but the associated function checks `use_cudnn` at forward time. Ideally we should check this at creation time in the link, but since chainer allows to dynamically change some of the backend properties based on the input I deferred the check to the function `forward`.
> Raise `RuntimeError` when using `cudnn_fast` without cudnn

- chainer/reporter.py
In `reporter.py`, a logging context stack is maintained as its internal thread-local variable named `_thread_local.reporters`.
In `Reporter.scope()` function, a Reporter object is pushed and popped to the stack in `__enter__()` and `__exit__()` function. 
If the `yield` omits an exception, the `__exit__()` is not called and the stack becomes an inconsistent state. In most use cases, such runtime error causes program termination thus the bug does not matter a lot.
However, in rare cases, such as #8384, it matters.
The bug forces the whole `pytest` process to terminate during a test.
This PR fixes the problem by adding `try/finally` block around the `yield` sentence so the pop operation is done correctly and the stack is kept consistent.
The error message from #8384 test looks like this: …
> Add try/finally block to yield in reporter.py

- tests/chainer_tests/functions_tests/math_tests/test_zeta.py
Fix #8166.
I have repeated the test 200K times without failure.
This PR fixes two parts of `TestZeta`.
- Relaxes the tolerances. `1e-3` is too tight for float16 tests.
- Fix the range of the generated input parameters.
> Fix flaky `TestZeta`

- chainerx_cc/chainerx/index_iterator.h
- tests/chainerx_tests/unit_tests/test_array_index.py
Thanks to @asi1024 @shinh 
ChainerX indexer used pretty expensive int64 division and modulo operations when calculating array indexes on CUDA.
This was noticeable when arrays were not contiguous, severely affecting the execution time of even simple kernels as `ElementWise` ones.
This PR replaces the code for index calculation with the same one as Cupy.
In the following test time for chainerx is reduced from 0.70 secs to 0.27
```python
import cupy
import chainer
import chainerx as chx
import time
def test_bench(name, xp, alloc_fn):
np.random.seed(42)
x = np.random.rand(800,389,2,66).astype(np.float32)
y = np.random.rand(800,389,2,66).astype(np.float32)
a = alloc_fn(x)
b = alloc_fn(y)
a = np.swapaxes(a, 2, 3)
b = np.swapaxes(b, 2, 3)
for i in range(1):
cuda = …
```
> Fast `IndexIterator` for CUDA

- onnx_chainer/mapping.py
This is because links in `chainer.links` usually import functions from submodules (e.g. `chainer.functions.rnn`) directly instead of importing them from `chainer.functions`.
> Allow ONNX-Chainer's patch_functions to patch functions in modules other than chainer.functions

- onnx_chainer/functions/array.py
- tests/onnx_chainer_tests/functions_tests/test_arrays.py
In addition to the case where the input or output is length 1, this PR newly adds support for cases where all inputs have the same shape.
> Extend ONNX-Chainer's TransposeSequence converter to support more cases

- tests/chainer_tests/functions_tests/math_tests/test_cholesky.py
Use smaller `eps` to compute gradient numerically, because 2nd-order grad of `x ** 0.5` has factor of `x ** -1.5`.
Close #8481.
> Fix flaky test: `TestCholesky`

- chainermn/extensions/observation_aggregator.py
- tests/chainermn_tests/extensions_tests/test_observation_aggregator.py
This PR depends on #8508
This PR is a replacement of #8322 by @belldandyxtq 
This PR adds ChainerX tests into the observation_aggregator
This PR partially solves #8031. This PR depends on #8321
~NOTE: This PR is completed w.r.t. the code, but it causes SEGV depending on the order of test cases in test_observatgion_aggregator.py. I guess it is because of the behavior of ChainerX's device setting. We need a deeper investigation on this issue.~
fixed!
> Add chainerx test in observation_aggregator

- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
This PR fixes the test of `chainerx.fromfile` to skip when the `dtype` is `bool_` and mode is text. It is because that, with NumPy 1.18, `numpy.fromfile` gives a `DeprecationWarning` in such case to make CI fail. With NumPy <1.18, it suppose to silently return invalid data, an empty array, and happens to pass the test.
https://github.com/numpy/numpy/releases/tag/v1.18.0
> np.fromfile and np.fromstring will error on bad data
> Skip `chainerx.fromfile` test when dtype is bool_ and mode is text

- tests/chainer_tests/functions_tests/loss_tests/test_decov.py
`FunctionTestCase` defaults to `numerical_grad_dtype = numpy.float64`, which would reduce the flakiness of the test.
Close #8512.
> Use `FunctionTestCase` to test `F.decov`

- tests/chainerx_tests/unit_tests/routines_tests/test_creation.py
> [backport] Skip `chainerx.fromfile` test when dtype is bool_ and mode is text

- docs/source/chainerx/install/index.rst
Since ChainerX is already included in released version of Chainer, I  believe that it is no longer necessary to specify `--pre`.
> Remove '--pre' from 'pip install' commands in ChainerX installation document

- chainer/functions/rnn/n_step_gru.py
- chainer/functions/rnn/n_step_lstm.py
- chainer/functions/rnn/n_step_rnn.py
This PR contains two doc fixes:
* fixing weight matrix sizes from `(I, N)` to `(N, I)`, and
* fixing bias/weight indexes in `n_step_birnn` from `i + di` to `2 * i + di`.
> Fix several documentation errors in chainer.functions.rnn.*

- setup.py
I don't know why, but `chainer>=7.0.0` is released in python2.
This PR stops installing `chainer>=7.0.0` in python2.
`chainer>=7.0.0` includes type hint in https://github.com/chainer/chainer/pull/8248, which breaks backward compatibility in python 2.
Documentation says Chainer drops python 2 support, so there is no need to release chainer>=7.0.0 in python2.
I also want to stop releasing `chainer>=7.0.0` because python2 is unfortunately system python for Ubuntu 16.04, 18.04.
There are several people who are forced to use Python2 in this age.
I want to do releasing like `matplotlib`, but I don't have enough knowledge about releasing.
> Do not install chainer>=7.0.0 in python2

- examples/cifar/train_cifar_custom_loop.py
- examples/mnist/train_mnist_custom_loop.py
- examples/static_graph_optimizations/cifar/train_cifar_custom_loop.py
- examples/static_graph_optimizations/mnist/train_mnist_custom_loop.py
Fix accuracy calculation of custom loop examples.
When the size of data (`len(train)`) is not a multiple of the batch size, the number of data used in one epoch is not equal to `len(train)`.
> Fix accuracy calculation of custom loop examples

- README.md
Hi!
[Optuna]( (optuna.org) ) is a new hyperparameter optimization library, and we’ve written an integration module for Chainer to make it easy to use Optuna to search for good hyperparameter settings and prune unpromising trials. We’re looking for ways to let Chainer users know this is available and thought a badge to show Optuna integration is available would be helpful.
Here’s our example of using the pruning integration with Chainer: https://github.com/optuna/optuna/blob/master/examples/pruning/chainer_integration.py
If there are other ways you would recommend reaching out to Chainer users to let them know about Optuna, please let us know.
Thanks!
> Add Optuna to README.md

- chainer/links/normalization/batch_normalization.py
- tests/chainer_tests/graph_optimization_tests/test_static_graph_models.py
Closes #8324 
When using `static_graph`, if the `Link.forward` allocates some intermediate array constant (zeros) and the associated function does not retain this input, the static graph fails when calling forward, as this input won't be correctly retrieved.
Solves this issue by allocating beta inside of a `static_code` function as described by:
https://docs.chainer.org/en/stable/reference/static_graph_design.html
An alternative could be to retain `beta` in the function forward, but `beta` is not being used in gradient calculation, hence it does not respect the semantics of `retain_inputs`.
Minimum example to reproduce
```python
import chainer
import chainer.links as L
import numpy
class TestBN(chainer.Chain):
super(TestBN, self).__init__() …
```
> Calculate `beta` with `static_code` on `F.BatchNormalization.forward`

- README.md
Related: #7948
I don't know how this section would be useful.
> Remove stable version section from README

- chainer/_environment_check.py
CuPy counterpart: https://github.com/cupy/cupy/pull/2766
> Remove py2 warnings

- chainer/dataset/convert.py
- tests/chainer_tests/dataset_tests/test_convert.py
This tries to fix a bug that happens when using  `MultiprocessParallelUpdater` with `forkserver` or `spawn` as the start mode.
There is an error because the multiprocessing module tries to pickle the converter function and this one has lost its complete import route from the `func_name` or `__name__` attribute due being decorated with `converter`.
Essentially I avoid the name classing in the module by not using the decorator.
I tried to solve this using `functools.wrap` but the case its trickier than it seems at first.
> Allow `concat_arrays` to be pickable

- .pfnci/py27and35.Dockerfile
Used to fix a failure in CuPy pfnCI as it is cloning chainer master:
Related https://github.com/cupy/cupy/pull/3162
https://ci.preferred.jp/chainer.docker.py27and35.push/53691/
> Remove python 2.7 builds

- chainer/functions/connection/local_convolution_2d.py
Result shape should be `(n, c_O, h_O, w_O)` instead of `(n, c_I * c_O, h_O, w_O)`.
Example section is written correctly.
```
>>> x = np.random.uniform(0, 1, (2, 3, 7, 7))
>>> W = np.random.uniform(0, 1, (2, 5, 5, 3, 3, 3))
>>> b = np.random.uniform(0, 1, (2, 5, 5))
>>> y = F.local_convolution_2d(x, W, b)
>>> y.shape
(2, 2, 5, 5)
```
Here, `W`'s shape shows `(c_O, h_O, w_O, c_I, k_H, k_W) = (2, 5, 5, 3, 3, 3)`,  so `y.shape` is `(2, 2, 5, 5) = (n, c_O, h_O, w_O)`.
If it was `(n, c_I * c_O, h_O, w_O)`, `y.shape`  must be `(2, 6, 5, 5)`.
> Fix local_convolution_2d result shape documentation

- .travis.yml
- scripts/ci/travis/steps.sh
This PR partially fixes Travis macOS failure on the `master` branch by using a newer Python 3.5.x.
> Fix Travis macOS failure

- .pfnci/chainermn.Dockerfile
- .pfnci/config.pbtxt
- .pfnci/run.sh
- .pfnci/script.sh
- chainer/testing/parameterized.py
- onnx_chainer/.flexci/run_test.sh
py27and37.gpu needed to lower the concurrency to 20 threads, seems that some change in somewhere might have changed the order in which some tests were executed causing out-of-memory errors.
for onnxchainer.py37.gpu cupy v8 was being installed, setting <8.0.0 in the requirements was enough.
chainermn now installs cupy in the same way as the chainer tests instead of using a prebuilt wheel that we deleted. We need to push this before to make cupy aware of this and push the new image
AppVeyor error
```
Downloading https://files.pythonhosted.org/packages/f1/2c/717bdd12404c73ec0c8c734c81a0bad7048866bc36a88a1b69fd52b01c07/numpy-1.19.0.zip (7.3MB)
Complete output from command python setup.py egg_info:
File "<string>", line 1, in <module>
File …
```
> Fix Chainer CIs

- chainer/reporter.py
The PR fixes an example of a global API of `Reporter`.  Note that the CI (`make doctest`) didn't run the examples because they were quoted.
> Fix `Reporter` example

- chainer/datasets/pickle_dataset.py
- tests/chainer_tests/datasets_tests/test_pickle_dataset.py
This PR solves #7768.
- Skip the test for `PickleDataset._after_hook()` on Windows
- Support `spawn` and `forkserver` start method
- Make picklable `PickleDataset`
- Make picklable `_FileReader`
- cf. [Programming guidelines for multiprocessing](https://docs.python.org/3.6/library/multiprocessing.html#the-spawn-and-forkserver-start-methods)
> Add support for `spawn` and `forkserver` start method in `PickleDataset`

- chainermn/extensions/multi_node_evaluator.py
Closes #8546
In some cases `local_mean_dict.values()` is empty. For example in the above issue, it is empty for the rank 1 since the example explicitly creates an empty dataset for this rank. 
https://github.com/chainer/chainer/blob/8b9e9c014716077366845fdb5bf780644c067952/examples/chainermn/mnist/train_mnist_dual_parallel.py#L124-L126
Also metrics are not reported for rank 1.
https://github.com/chainer/chainer/blob/8b9e9c014716077366845fdb5bf780644c067952/examples/chainermn/mnist/train_mnist_dual_parallel.py#L107-L110
> Fix array indexing in `create_multi_node_evaluator`

- docker/intel/python3/Dockerfile
- docker/python3/Dockerfile
NumPy 1.19 does not support Python 3.5 which is the default system python in Ubuntu 16.
(avoid upgrading setuptools/pip as they are installed via package maanger)
> Use numpy 1.18.x for Docker images

- chainer/_version.py
- chainer/backends/cuda.py
- onnx_chainer/.flexci/run_test.sh
Although we do not support CuPy v8 + Chainer v7, this mitigates the situation that Chainer cannot run on CuPy v8. (#8582)
> Mitigate breaking changes in CuPy v8

- tests/chainer_tests/testing_tests/test_function_link.py
There is a small typo in tests/chainer_tests/testing_tests/test_function_link.py.
Should read `contiguousness` rather than `cotiguousness`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, cotiguousness -> contiguousness

- chainer/backends/cuda.py
When cuDNN is unavailable, `import cupy.cudnn` fails immediately so the preloading warning to install cuDNN is not displayed. This fixes the import order to show preloading warning.
> Import cupy.cuda.cudnn first to show preload warning

- chainer/backends/cuda.py
When cupy>=10 is installed, importing chainer immediately raises the following error.
```python
>>> import cupy; cupy.__version__
'10.0.0'
>>> import chainer
File "/usr/local/lib/python3.9/site-packages/chainer/__init__.py", line 10, in <module>
from chainer import backends  # NOQA
File "/usr/local/lib/python3.9/site-packages/chainer/backends/__init__.py", line 1, in <module>
from chainer.backends import cuda  # NOQA
File "/usr/local/lib/python3.9/site-packages/chainer/backends/cuda.py", line 124, in <module>
_cupy_major = numpy.lib.NumpyVersion(cupy.__version__).major
File "/usr/local/lib/python3.9/site-packages/numpy/lib/_version.py", line 59, in __init__
raise ValueError("Not a valid numpy version string") …
```
> Prevent importing chainer immediately raises an error with cupy>=10

- chainer/functions/connection/deconvolution_2d.py
- tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py
This PR fixes wrong arguments of `_set_cover_all` in deconvolution_2d.py,
which causes an error during double-backprop of 2D convolution when CPU is used.
```py
>>> x = ch.Variable(np.ones((1, 1, 3, 3), dtype="float32"))
>>> w = ch.Variable(np.ones((1, 1, 2, 2), dtype="float32"))
>>> y = F.convolution_2d(x ** 2, w)
>>> g, = ch.grad([y], [x], enable_double_backprop=True)
>>> F.sum(g).backward()
File "/home/testuser/ch/chainer/chainer/variable.py", line 1581, in backward
_backprop._backprop_to_all(
File "/home/testuser/ch/chainer/chainer/_backprop.py", line 225, in _backprop_to_all
_backprop_utils.backprop_step(
File "/home/testuser/ch/chainer/chainer/_backprop_utils.py", line 140, in backprop_step …
```
> Fix `_set_cover_all` in deconvolution_2d.py
